### ISSUE TITLE
Encoding of winrt-api/windows.ui.core/characterreceivedeventargs_keycode.md is unclear

### ISSUE THREAD

**Issue by Wumpf** [MicrosoftDocs/winrt-api#10]
The documentation doesn't state how CharacterReceivedEventArgs.KeyCode is encoded. 
However, I've found this answer on stackoverflow that claims that .Net's Convert.ToChar will do the trick:
http://stackoverflow.com/questions/16783820/handling-virtualkey-in-windows-8-store-apps-with-c-sharp

So I assume that it is a UTF32 character. Can somebody please clarify and note the correct usage in the documentation?

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for your feedback! I've updated the topic to include this detail.
