### ISSUE TITLE
wrong namespace

### ISSUE THREAD

**Issue by bkrauth** [MicrosoftDocs/winrt-api#1001]
in UWP, the namespace: should be System.ComponentModel, not Windows.UI.Xaml.Data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e72e60f-6e5e-05c9-fce2-9f77407c29a7
* Version Independent ID: 69ff2813-b9ab-fcc5-47e0-d38a96ad730e
* Content: [INotifyPropertyChanged Interface (Windows.UI.Xaml.Data) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.inotifypropertychanged#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.inotifypropertychanged.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.inotifypropertychanged.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@bkrauth , thanks for the feedback. This is the correct namespace when using C++ and XAML. The .NET language projection uses System.ComponentModel, and this is noted both in the description and in the remarks.
