### ISSUE TITLE
Link to "FocusManager" in remarks section is broken

### ISSUE THREAD

**Issue by jevansaks** [MicrosoftDocs/winrt-api#1002]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.gotfocus#remarks. FocusManager URL goes to https://docs.microsoft.com/en-us/uwp/api/focusmanager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f84c5c4-7431-d2db-0890-7e9df7680bf6
* Version Independent ID: cc598142-d050-8f42-4ef8-44fb7baa19a3
* Content: [UIElement.GotFocus Event (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.gotfocus#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
I've pushed an update for the link. Thanks
