### ISSUE TITLE
What is the time unit of this interval?

### ISSUE THREAD

**Issue by intruder01** [MicrosoftDocs/winrt-api#1003]
I did not see the unit defined in the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 514975f3-09f7-a810-edac-f12ffc312868
* Version Independent ID: ebb1a570-954a-a240-4229-ee472bbf7315
* Content: [GpioPin.DebounceTimeout Property (Windows.Devices.Gpio) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiopin.debouncetimeout#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiopin.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiopin.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @intruder01. Thanks for filing this issue, and my apologies for the long delay in responding.

The property's type is [TimeSpan](https://docs.microsoft.com/uwp/api/windows.foundation.timespan), and its duration is a time period expressed in 100-nanosecond units. However, note (from the docs at the link there) that this type is projected differently into different WinRT language projections.

Thanks!
Steve
