### ISSUE TITLE
Link to list of data type ids

### ISSUE THREAD

**Issue by dlech** [MicrosoftDocs/winrt-api#1004]
It would be nice to have a link to https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc00437f-a6a4-ceae-a96d-d7b539dc9e9f
* Version Independent ID: 77520eb0-ecc7-938e-4252-7b5919658f0a
* Content: [BluetoothLEAdvertisementDataSection.DataType Property (Windows.Devices.Bluetooth.Advertisement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementdatasection.datatype#Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisementDataSection_DataType)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisementdatasection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisementdatasection.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @dlech. Thanks for filing this issue, and my apologies for the long delay in responding.

Good idea, I've added that link. I'll go ahead and close the issue.

Thanks again!
Steve
