### ISSUE TITLE
Additional note about subnet address and subnet mask arguments.

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1006]
The subnet address must match with the subnet mask provided. I.e. if we provide 10.1.1.1 with subnet mask as 24 assuming interface will treat it as equivalent to 10.1.1.0, it doesn't. The constructor OR even the StartWithMainTransport or other Start methods of the VPN Channel don't throw an exception. However, route does not get added and functionality does not work as expected. 

Therefore, you need to have all the bits after the subnet-mask set to '0' in the subnet address provided as argument to have the route added successfully. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 349f67a7-67e8-064c-c3f6-17dde2b59102
* Version Independent ID: 46b59648-00f4-ab19-19ed-b59671f6032c
* Content: [VpnRoute(HostName, Byte) Constructor (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnroute.-ctor#Windows_Networking_Vpn_VpnRoute__ctor_Windows_Networking_HostName_System_Byte_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnroute.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnroute.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Assigning to Peter as SME; please confirm that we want to make this change to the docs, and then please assign this GiHub issue back to me (`stevewhims`) along with any recommendations for exactly what to change, and I'll do the rest. ~Steve

**Comment by stevewhims** [comment]
Hi, @defaultshr, I'll go ahead and close this issue now. We can still work on it while it's closed, and I'll send another notification to the feature team. If they can confirm the suggested change and let me know, then I'll update the docs.

Thanks again!
Steve
