### ISSUE TITLE
Sample for appServerKey to buffer?

### ISSUE THREAD

**Issue by madenwala** [MicrosoftDocs/winrt-api#1010]
Could you please add sample code for converting your appServerKey from string to IBuffer? Leaving that PDF link to the specification just made a dev's job so much harder when it doesn't need to be this difficult. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5c4a234-d8c6-6801-e756-04dd544d3c6c
* Version Independent ID: fa804c5c-78a1-36bd-a010-5eb3059b63ee
* Content: [PushNotificationChannelManagerForUser.CreateRawPushNotificationChannelWithAlternateKeyForApplicationAsync Method (Windows.Networking.PushNotifications) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.pushnotifications.pushnotificationchannelmanagerforuser.createrawpushnotificationchannelwithalternatekeyforapplicationasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.pushnotifications.pushnotificationchannelmanagerforuser.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.pushnotifications.pushnotificationchannelmanagerforuser.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by andrewleader** [comment]
Closing as Mohammed is now using the normal javascript web push APIs and normal WNS APIs.

If someone needs this, let us know and we'll prioritize accordingly.

**Comment by DanieleScipioni** [comment]
Hello, I need the example.

**Comment by andrewleader** [comment]
Hey @DanieleScipioni, do you also work at MS? Reach out to me on email, my alias is `aleader`
