### ISSUE TITLE
Unambiguous Xaml specification of Source

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/winrt-api#1013]
This page
https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Core.MediaSource
can be reached from here
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/media-playback
That page says:
"Add media to your app by creating a MediaPlayerElement object in XAML and set the Source to a MediaSource ..."
and gives a simple XAML example of
Source="Videos/video1.mp4"
Only it ain't that easy.  Is it?  There needs to be a working unambiguous means of specifying a local file [StorageFile] in XAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b37599f-d860-5c1b-4e07-678369865c15
* Version Independent ID: 794108ff-c268-c3ce-0195-3d56516ca9e6
* Content: [MediaSource Class (Windows.Media.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Core.MediaSource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediasource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediasource.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by jwmsft** [comment]
@mrmsbarnes , thanks for bringing this to our attention. The correct way to set the Source in XAML is to use the [ms-appx URI scheme](https://docs.microsoft.com/windows/uwp/app-resources/uri-schemes).

'Source="ms-appx:///Videos/video1.mp4"'

The MediaPlayerElement class page shows this, and I've updated the Media Playback page to show the correct code, as well.

**Comment by mrmsbarnes** [comment]
To Jim Walker

Thank you very much.  I think this helps get the right info in the right place.
