### ISSUE TITLE
Is it must to implement plugin as out-of-process background task 

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1014]
Can VPN plugin be implemented in the in-process background task? OR is it mandatory to specify the task entry-point in the manifest file and have it run as purely out-of-process background task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a88e25-2948-fb1e-146e-b99eb119afe6
* Version Independent ID: e85f2e71-e3bc-c611-aaa3-529ddf81c38d
* Content: [IVpnPlugIn Interface (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.ivpnplugin)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.ivpnplugin.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.ivpnplugin.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Adding Peter for his input.

**Comment by bronze1man** [comment]
I have seen all part of the code running in the same process. 
"GetCurrentProcessId()" return the same value after the "VpnManagementAgent.ConnectProfileAsync" call and duration the callback in "IVpnPlugIn.Connect".
Code example : https://github.com/ysc3839/UWPToyVpn

Uwp project : c# / c++/winRT
Target version: windows 10, version 1809 (10.0; Build 17763)
Test windows machine: OS build 17763.503

**Comment by stevewhims** [comment]
@defaultshr, are you still blocked on this question? Thanks! ~Steve

**Comment by stevewhims** [comment]
Let's go ahead and close this optimistically. @defaultshr, if you're still blocked then please reopen it and I'll keep requesting info about it internally.
