### ISSUE TITLE
Note about this being mandatory field to be set.

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1015]
You may add a note in this page saying this is a mandatory field to be set. Otherwise, the VpnManagementAgent's AddProfileFromObjectAsync returns error saying *Other*. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764ee751-0e05-f871-da83-a7d1b4a1d146
* Version Independent ID: 47df9efb-b79f-b18b-671a-b6eeaa4c4803
* Content: [VpnPlugInProfile.VpnPluginPackageFamilyName Property (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnpluginprofile.vpnpluginpackagefamilyname#Windows_Networking_Vpn_VpnPlugInProfile_VpnPluginPackageFamilyName)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnpluginprofile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnpluginprofile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Assigning to Peter as SME; please confirm that we want to make this change to the docs, and then please assign this GiHub issue back to me (`stevewhims`) along with any recommendations for exactly what to change, and I'll do the rest. ~Steve

**Comment by stevewhims** [comment]
This one's been open for a while, so it's probably not a high priority to fix. I'll close the issue, and I'll send one last heads up email to the SME.

Thanks!
Steve
