### ISSUE TITLE
This is a mandatory field which shall contain atleast one IP:port entry.

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1016]
Kindly mark an additional note. For background task to receive 'connect' trigger successfully, the VpnPluginProfile's ServerUris must have at least one IP:port entry present for C++/CX. 

In case of C#, it expects URL scheme too (e.g. http:192.168.1.135:50000).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9d68c0f-60c4-6a4d-b322-c693309165aa
* Version Independent ID: 2f358df4-5554-042d-b404-7f69af944369
* Content: [VpnPlugInProfile.ServerUris Property (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnpluginprofile.serveruris#Windows_Networking_Vpn_VpnPlugInProfile_ServerUris)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnpluginprofile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnpluginprofile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Assigning to Peter as SME; please confirm that we want to make this change to the docs, and then please assign this GiHub issue back to me (`stevewhims`) along with any recommendations for exactly what to change, and I'll do the rest. ~Steve

**Comment by stevewhims** [comment]
Hi, @defaultshr, I'll go ahead and close this issue now. We can still work on it while it's closed, and I'll send another notification to the feature team. If they can confirm the suggested change and let me know, then I'll update the docs.

Thanks again!
Steve
