### ISSUE TITLE
Confusing FlagsAttribute description

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1018]
All of the enum classes with FlagsAttribute specified seem to have this text: "This enumeration has a System.FlagsAttribute attribute that allows a bitwise combination of its member values."

The type System.FlagAttributes only makes sense in .Net (where the System namespace lives), and even there it would be more useful to show [flags] in the example code.

Also, having that attribute doesn't *allow* a bitwise combination of its member values, it's just a hint that anyone consuming the enum should treat it as bit flags.

A better description would be something like "This enumeration supports a bitwise combination of its member values".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08981f1a-e071-dcf9-e6be-5d9c8cd73fa5
* Version Independent ID: 204a9dc6-cb81-9a3e-83bb-18d9e60fcc49
* Content: [ElementHighContrastAdjustment Enum (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.ElementHighContrastAdjustment)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.elementhighcontrastadjustment.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.elementhighcontrastadjustment.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@mijacobs , this FlagsAttribute text is added in the doc build, so I'm passing this feedback along to you. FWIW, I believe this is a carry-over from WPF docs (for example, [DataGridHeadersVisibility](https://docs.microsoft.com/dotnet/api/system.windows.controls.datagridheadersvisibility).

**Comment by mijacobs** [comment]
@jwmsft : assigning this to @mimisasouvanh

**Comment by Karl-Bridge-Microsoft** [comment]
@MikeHillberg - Sorry for the delayed response. I logged a bug against our engineering team to address.

**Comment by jwmsft** [comment]
Closing this issue since it's being tracked internally.
