### ISSUE TITLE
Which versions of UWP?

### ISSUE THREAD

**Issue by Shadolio** [MicrosoftDocs/winrt-api#1019]
My App targets Windows 10 version 1809 and also has it as Minimum version. I cannot find this property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08b14dc1-9480-76fb-db85-308d0dcec01f
* Version Independent ID: 1dc3033d-ea42-c97d-81b5-caa9e5ef5dc6
* Content: [NavigationView.SettingsItem Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.settingsitem)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
The doc page isn't showing the versions which we will look into separately. But SettingsItem property existed since the beginning of NavigationView (16299) so I wouldn't expect that NavigationView would work but SettingsItem doesn't. Can you provide more details?
