### ISSUE TITLE
Then, please give examples on using PageFooter

### ISSUE THREAD

**Issue by Shadolio** [MicrosoftDocs/winrt-api#1020]
The documentation says that it can contain additional elements. What type of additional elements? Please give us examples or use cases for using PageFooter. It also remarks that if we place a NavigationViewItem, it will not raise an ItemInvoked event; it has to be in the MenuItems collection.

In other words, I want to add a few NavigationViewItems in the PaneFooter, but I want them to extend the menu items, i.e. can be selected and show same visual animation as items in MenuItems.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a8d719-6253-b4a0-07bc-bcf8a1fca2bc
* Version Independent ID: df9f3178-84d5-1db4-4d3d-9abed8a3f9e2
* Content: [NavigationView.PaneFooter Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-gb/uwp/api/windows.ui.xaml.controls.navigationview.panefooter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
These might be answered in the general page for [Navigation View](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#pane-footer), but that's not very discoverable from here.

**Comment by Shadolio** [comment]
Unfortunately, there are no details in that place either; just one screenshot example that does not show the behaviour, and without explanation. :(

**Comment by jevansaks** [comment]
We've had other users frustrated about this as well. We're tracking some bugs on the product github, but I would recommend you upvote this feature request since that sounds like really what you want: https://github.com/Microsoft/microsoft-ui-xaml/issues/375
