### ISSUE TITLE
Issues in encapsulation path when GetVpnSendPacketBuffer is used

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1022]
I notice an issue when GetVpnSendPacketBuffer  is used as source of buffers for encapsulation. About 45 to 50 buffers get encoded and sent out. However, after that I notice encapsulate callback does not get invoked at all. To work around, I had to remove the L3 buffers present in L3 packet list and modify them to be added to encapsulatedPackets list. 

However, in the decapsulate path, the GetVpnReceivePacketBuffer works perfectly fine. 

Could you kindly have this issue investigated for GetVpnSendPacketBuffer . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5adcdc9-4141-129e-f4e9-16732804f139
* Version Independent ID: 32a413ee-77ec-fcd1-a0de-ab9027b88f7a
* Content: [VpnChannel.GetVpnSendPacketBuffer Method (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnchannel.getvpnsendpacketbuffer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnchannel.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnchannel.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Adding @PeterSmithRedmond for help. :)

**Comment by 5ngs94jzqw** [comment]
I have found a "good" workaround to this bug:
* In IVpnPlugin::Encapsulate call packets.RemoveAtBegin() to get the buf, then use channel.GetVpnSendPacketBuffer() to get a new buffer and copy data into the buffer and append it to encapulatedPackets, then call packets.Append(buf) after you finish use that VpnPacketBuffer object. This way the bug will disappear.

It looks like that all VpnPacketBuffer need to be in the packets or in the encapulatedPackets after the call return.

**Comment by stevewhims** [comment]
Hi, @5ngs94jzqw, it's good to hear that you've found a workaround. Peter, if you'd like me to change the docs, and you can give me details, then I can do that. But I'll tentatively close this issue now (please re-open it if necessary). Thanks! ~Steve
