### ISSUE TITLE
Ordering of Items in is incorrect

### ISSUE THREAD

**Issue by adwilso** [MicrosoftDocs/winrt-api#1023]
The ordering of values in the DeploymentOptions table is incorrect on the docs website. It is sorted in order of alphebetical by name, not by the value of the flag

https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.deploymentoptions

![image](https://user-images.githubusercontent.com/1334452/55988896-e5dfb980-5c59-11e9-8adc-63fc89bbba35.png)

It is correct in the source: https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.management.deployment/deploymentoptions.md

**Comment by GrantMeStrength** [comment]
Unfortunately this is an artifact of our publishing system, and in this case, cannot be changed.
