### ISSUE TITLE
Bluetooth Low Energy

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/winrt-api#1024]
It is unclear if this is only for classic or is it also what one must use when searching for Bluetooth Low Energy advertisements? If it works for the latter, is there a way to get advertisement information or can this only be done in C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15a7d73d-8f8c-1e3e-1e50-1ec9bf120eac
* Version Independent ID: bf42a0cf-8bcb-fa15-9caa-07abaefb172e
* Content: [DeviceWatcher Class (Windows.Devices.Enumeration) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicewatcher#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.devicewatcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.devicewatcher.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. 

Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
