### ISSUE TITLE
C++ implementation

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/winrt-api#1025]
There is no example for C++. The critical headache in C++ is lack of documentation for the header files to access these functions. Worse, some of these methods appear to be supported in C#. That needs to be clearly stated if that is indeed true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f050bab3-2598-d27a-ee77-51db6c8be504
* Version Independent ID: 10b526d7-df3c-979a-d654-72c573c03d15
* Content: [DeviceInformation Class (Windows.Devices.Enumeration) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Enumeration.DeviceInformation#Windows_Devices_Enumeration_DeviceInformation_CreateWatcher)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceinformation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to share your feedback and I sincerely apologize for the delayed response. We are in the process of trying to add [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/) code examples to as many articles as possible to provide equivalence with C#, and I will make sure this article is added to our list.
