### ISSUE TITLE
Dead links for Remarks -> Accessing a ResourceDictionary object in code -> C#

### ISSUE THREAD

**Issue by stephenteodori** [MicrosoftDocs/winrt-api#1026]
There are several dead or broken links in the "Remarks -&gt; Accessing a ResourceDictionary object in code -&gt; C#" portion of the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5576bf3b-1cdf-849e-ab18-cae270ab93d9
* Version Independent ID: c1f594e7-7ba2-6aa5-3cfb-4f482480e024
* Content: [ResourceDictionary Class (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.resourcedictionary#remarks)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.resourcedictionary.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.resourcedictionary.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The links are fixed now.
