### ISSUE TITLE
Missing parameteres in declarations of generic types

### ISSUE THREAD

**Issue by jjakubovic** [MicrosoftDocs/winrt-api#103]
Like here: 
https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicewatcher#events_

DeviceWatcher::EnumerationCompleted event is declared like this:

public event TypedEventHandler EnumerationCompleted

But it should be:

public event TypedEventHandler<DeviceWatcher^, Object^> EnumerationCompleted

Also the description of parameters of generic type is missing. E.g. what does the Object^ parameter represent?

I can see this throughout the whole UWP documentation at docs.microsoft.com. 

J.

**Comment by kevinyr** [comment]
Checking to see where we're at with this issue.

**Comment by kevinyr** [comment]
The fix for this issue will be rolled out in the next week.

**Comment by jjakubovic** [comment]
Thanks for the fix :-). I'll check it in couple of days, because I still see the old version.
