### ISSUE TITLE
Broken Link: App Installer APIs

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/winrt-api#1032]
The See Also section includes a link to the App Installer APIs: https://docs.microsoft.com/en-us/windows/msix/app-installer/app-installer-apis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa316497-db9b-25ea-d1e1-c9baf2853721
* Version Independent ID: 8d9f51dd-58c2-fccc-4d02-d4d2620383f7
* Content: [PackageManager.AddPackageByAppInstallerFileAsync(Uri, AddPackageByAppInstallerOptions, PackageVolume) Method (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.addpackagebyappinstallerfileasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
Just checked in a fix. Should be published shortly.
