### ISSUE TITLE
C++/winrt example?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#1034]
Could you show an example of how to provide the filetypechoices in C++/winrt?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01d53cf3-82a2-782e-46a8-c51e26bfcec7
* Version Independent ID: d886fe8a-c4c6-0273-0261-599c22b3e68d
* Content: [FileSavePicker.FileTypeChoices Property (Windows.Storage.Pickers) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.filesavepicker.filetypechoices)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.filesavepicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.filesavepicker.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by jevansAN** [comment]
OK, in case it's any help let me offer a solution. It took some time. Let's say the file type is txt and we've declared the FileSavePicker. The key is to use Collections:

hstring fileExtension = to_hstring(L".txt");
Windows::Foundation::Collections::IVector<hstring> extensions{winrt::single_threaded_vector<hstring>() };
extensions.Append(to_hstring(L".txt"));
m_file_save_picker.SuggestedFileName(L"Untitled");
m_file_save_picker.FileTypeChoices().Insert(L"Text file",extensions);

**Comment by knicholasa** [comment]
Hi @jevansAN, thanks for the feedback and your example. I'm going to update the document to include an example very similar to the one you've shared. Looks like you're on the right track already with your code. The new content should show up next week.
