### ISSUE TITLE
Lack of detail

### ISSUE THREAD

**Issue by sjb-sjb** [MicrosoftDocs/winrt-api#1036]
The page should state what interfaces the ItemsSource must implement and which ones it may implement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3264745a-dfeb-acea-166b-004796c6fe8b
* Version Independent ID: 34fa0562-e9eb-b774-ab03-9b4c1e8ea32a
* Content: [TreeView.ItemsSource Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.itemssource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by predavid-zz** [comment]
@jwmsft - could you please update this doc to address this issue:  https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents

**Comment by jwmsft** [comment]
Doc is updated (same info as ItemsControl.ItemsSource).
