### ISSUE TITLE
Unclear use of the FromBluetoothAddressAsync

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/winrt-api#1037]
When writing a client:
The documentation is insufficient to understand what these methods do and when they should be used, in particular the FromBluetoothAddressAsync(address, addressType). It is not clear if the address type is for the client (setting it indicates how I am going to act) or the peer (I need to specify if the peer device is using resolvable random addressing). If I am a client watching advertisements, there is no way to obtain the BluetoothAddressType from the BluetoothLEAdvertisementReceivedEventArgs. At least I could not find anything. 

Thus by inference I can only assume that the address type is how the client is to behave. If that is true, what happens if one does NOT specify the address type?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedb9559-6da0-2e91-eaef-12d9e9bfff4f
* Version Independent ID: cf9ff409-0028-5b6c-b77e-3987ad23671d
* Content: [BluetoothLEDevice.FromBluetoothAddressAsync Method (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync#Windows_Devices_Bluetooth_BluetoothLEDevice_FromBluetoothAddressAsync_System_UInt64_Windows_Devices_Bluetooth_BluetoothAddressType_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @brianreinhold. Thanks for filing this issue, and my apologies for the long delay in responding.

The address type is of the peer. I've updated the topic with more info. As for retrieving the address type from event args, there is a **BluetoothLEAdvertisementReceivedEventArgs.BluetoothAddressType** property in the [SDK Insider Preview](https://www.microsoft.com/software-download/windowsinsiderpreviewSDK).

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close the issue now.

Thanks!
Steve
