### ISSUE TITLE
No examples for C++/winRT

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/winrt-api#1038]
What one needs to do for C++/WinRT UWP can look quite different than C# and it would be REALLY, REALLY helpful if C++/winRT examples were provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedb9559-6da0-2e91-eaef-12d9e9bfff4f
* Version Independent ID: cf9ff409-0028-5b6c-b77e-3987ad23671d
* Content: [BluetoothLEDevice.FromBluetoothAddressAsync Method (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync#Windows_Devices_Bluetooth_BluetoothLEDevice_FromBluetoothAddressAsync_System_UInt64_Windows_Devices_Bluetooth_BluetoothAddressType_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @brianreinhold. Thanks for filing this issue, and my apologies for the long delay in responding.

You're right, the two languages do look very different, syntactically. Until we have a C++/WinRT code example in this topic, one suggestion would be for you to study the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) documentation, which contains lots of code examples showing many different techniques for calling Windows Runtime APIs from C++. It's likely that you'll learn enough there to use these APIs from C++/WinRT and/or to convert any C# code to C++/WinRT. In addition, fyi, any topic (across the Windows dev content) that has a C++/CX code example now also has a C++/WinRT code example.

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now. Please reopen if I made a mistake in closing. ~Steve
