### ISSUE TITLE
Connection is critical ... how long will an attempt last?

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/winrt-api#1039]
After discovering a device and calling the following

IAsyncOperation&lt;Windows::Devices::Bluetooth::BluetoothLEDevice&gt; async =  
		BluetoothLEDevice::FromBluetoothAddressAsync(eventArgs.BluetoothAddress(), BluetoothAddressType::Random);
	BluetoothLEDevice bluetoothLEDevice = async.get();
bluetoothLEDevice.ConnectionStatusChanged({ this, &BtleHandler::onConnectionStatusChanged });

it is unclear how long the system waits for a connection, or if there is ever a timeout, or what. There does not appear to be a timeout option ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedb9559-6da0-2e91-eaef-12d9e9bfff4f
* Version Independent ID: cf9ff409-0028-5b6c-b77e-3987ad23671d
* Content: [BluetoothLEDevice.FromBluetoothAddressAsync Method (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @brianreinhold. Thanks for filing this issue, and my apologies for the long delay in responding.

I've updated the **FromBluetoothAddressAsync** and **FromIdAsync** topics with more details about connections.

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close the issue now.

Thanks!
Steve
