### ISSUE TITLE
Missing description of Data​Writer​Store​Operation result

### ISSUE THREAD

**Issue by jjakubovic** [MicrosoftDocs/winrt-api#104]
https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datawriterstoreoperation

Data​Writer​Store​Operation::GetResults() returns uint, but it's not documented, what does this uint represent. From the sample for DataWriter it can be seen that it's the number of stored bytes, but the meaning should be clear from the function documentation.

Is this the right place to report this stuff? There's a ton of issues like this in new docs.microsoft.com :-(, but I see only ~20 issues in the database.

J.

**Comment by laurenhughes** [comment]
Thanks for calling this out! This is the right place to report any issues with the documentation. You can also make updates directly to our docs via the "Edit" button on the page and submit them as a pull request.
 
I updated the description for the GetResults return value, which will be published shortly.
