### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by MichaelLHerman** [MicrosoftDocs/winrt-api#1040]
Some documentation on the event args would be nice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 625d81a4-bb1e-0379-90dc-66cf17ea107f
* Version Independent ID: 3e8fc3d2-a808-e1be-c97d-2f33e9107827
* Content: [ItemContainerGenerator.ItemsChanged Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemcontainergenerator.itemschanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemcontainergenerator.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemcontainergenerator.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Yeah, I don't know why this page doesn't have any content. @IrinVoso even the delegate and type information is missing from this page.

**Comment by mijacobs** [comment]
@jwmsft I believe this is yours.

**Comment by jwmsft** [comment]
Sorry for the delayed response, and thanks for the feedback. The doc build has been fixed to add links to the delegate, but in this case it still takes several clicks to find the event args, so I've added a direct link.
