### ISSUE TITLE
Description of StandardUICommandKind is misleading

### ISSUE THREAD

**Issue by YuliKl** [MicrosoftDocs/winrt-api#1046]
This page states: "Specifies the pre-defined commands (**including behavior**, and various UI-related properties, methods, and events) that can be used with a StandardUICommand." To me, this implies that when I choose the Share command kind, share behavior is built in and works for free. But that's not true. I still have to implement the share behavior in my app. 

The [Commanding article](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/commanding) has a more modest and more accurate description that we should copy here: "the StandardUICommand class exposes a set of standard platform commands with pre-defined properties such as icon, keyboard accelerator, and description."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 311d9e5d-557b-786a-1df9-ac3354edd55d
* Version Independent ID: a6258287-2bc0-131c-2f67-037b4ff5c7e2
* Content: [StandardUICommandKind Enum (Windows.UI.Xaml.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.standarduicommandkind)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.standarduicommandkind.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.standarduicommandkind.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @YuliKl. I've updated the StandardUICommand.Kind and StandardUICommandKind topics as suggested.
