### ISSUE TITLE
Set state without triggering an event?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#1049]
In C++/winrt it is not clear how one sets the state of a CheckBox, derived from ToggleButton. IsChecked is said here to "Get or Set" the state, but setting the state by writing theCheckBox.IsChecked(true) also calls the event handler for the CheckBox, which may not be appropriate if one is just initializing the button's visual state. Perhaps the meaning of the IReference&lt;bool&gt; argument needs more explanation here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13e2af68-ce69-575c-8370-4800c9f73af0
* Version Independent ID: 9283198c-6878-5d1c-0e01-195f262d3694
* Content: [ToggleButton.IsChecked Property (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.togglebutton.ischecked)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.togglebutton.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.togglebutton.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
Sorry, not following. You're right that setting IsChecked also calls the event handler, whether it's a ToggleButton or a CheckBox. Are you suggesting that there should be an initialization mode where it doesn't raise the event?

**Comment by jevansAN** [comment]
Thanks, Mike. Yes, that is what I was suggesting. Is there no way to set the visual state of a checkbox without raising an event? For instance, when preparing a panel  of options and you want to show the currently-chosen ones? That is, to merely alter the visual appearance of the checkbox?

Jeff


On Apr 24, 2019, at 5:07 PM, MikeHillberg <notifications@github.com> wrote:

Sorry, not following. You're right that setting IsChecked also calls the event handler, whether it's a ToggleButton or a CheckBox. Are you suggesting that there should be an initialization mode where it doesn't raise the event?

**Comment by MikeHillberg** [comment]
There's nothing like that today. You could [propose it](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose) in the GitHub repo. This sounds similar to [ISupportInitialize](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.isupportinitialize?view=netframework-4.8), but that just defers the change notifications rather than suppressing them altogether.

**Comment by jevansAN** [comment]
Seems odd to me. Never before saw a checkbox control whose state could not be initialized without triggering an action. How is one expected to prepare a panel of options for viewing so that they show the currently chosen options? I will work around it by setting the state before declaring the event handler, but that means I can't later change the state for whatever reason without triggering an event.

**Comment by jevansaks** [comment]
You could attach the event listeners *after* setting the initial state so your callbacks don't get confused?

**Comment by jevansAN** [comment]
Yes, that's exactly what I'm going to do. But it forecloses any possibility of changing the visual state programmatically once the event handlers are declared. There are cases where that would be useful: e.g. if a user chooses a certain option that implies some other action should automatically be taken as well.  For example, an informative checkbox might say whether an item carries a text label; but if it is unchecked and gets chosen it would make sense to bring up the action for editing a text label. Yet you don't want to bring up that editor when just setting the checkbox state to reflect the current condition of the chosen object. Seems to me it would make sense to be able to programmatically set the visual state of a checkbox without triggering its associated action.  Used to be able to do that.
