### ISSUE TITLE
Supported version info missing

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/winrt-api#1050]
On most of the properties there's a section saying which version it's supported from, like this:
### Additional features and requirements
|  |  |
|:--- |:--- |
| Device family	| Windows 10, version 1803 (introduced v10.0.17134.0) |
| API contract | Windows.Foundation.UniversalApiContract (introduced v6) |

This is missing from the events, and according to the PlatformAnalyzer this event isn't supported on all versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ffc0cf-bd29-b1c6-7e4e-370b2a6f1cf0
* Version Independent ID: ff9e53af-7764-d1fe-4797-a1553ea87439
* Content: [NavigationView.PaneClosing Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.paneclosing)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@mimisasouvanh @mijacobs Another issue with API info not appearing.

**Comment by mimisasouvanh** [comment]
We have an internal bug to track this issue: Bug 79037: [UWP] event members pages are missing API contracts, requirements info

**Comment by jwmsft** [comment]
This issue is fixed.
