### ISSUE TITLE
The return parameter datatype is Platform::Array<unsigned char> type for C++/CX

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1051]
Kindly correct the return parameter type for C++/CX as above. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6b3b846-8817-348f-eb72-7f67df8cd816
* Version Independent ID: a8466ff6-57ac-0b7c-f9c9-4db568292e37
* Content: [CryptographicBuffer.CopyToByteArray(IBuffer, Byte\[\]) Method (Windows.Security.Cryptography) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.cryptographicbuffer.copytobytearray)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **misatran**

**Comment by stevewhims** [comment]
Hi, and apologies for the delay in responding. It looks like since this was filed, the language picker for this topic has had C++/CX removed from it. So there is no rendering of the C++/CX syntax here.

Apologies for that. Let's close this Not Repro.
