### ISSUE TITLE
typo, xaml instead of xml

### ISSUE THREAD

**Issue by jingweihaha** [MicrosoftDocs/winrt-api#1057]
The following example shows how to create a StackPanel of items.

XML =&gt; should be XAML

Copy
&lt;StackPanel Margin="20"&gt;
    &lt;Rectangle Fill="Red" Width="50" Height="50" Margin="5" /&gt;
    &lt;Rectangle Fill="Blue" Width="50" Height="50" Margin="5" /&gt;
    &lt;Rectangle Fill="Green" Width="50" Height="50" Margin="5" /&gt;
    &lt;Rectangle Fill="Purple" Width="50" Height="50" Margin="5" /&gt;
&lt;/StackPanel&gt;
XML =&gt; should be XAML

Copy
&lt;Grid x:Name="LayoutRoot"  Width="500" Height="500"&gt;
    &lt;StackPanel x:Name="MyStackPanel"&gt;
        &lt;TextBlock x:Name="TB1" Text="First Name" Width="77" HorizontalAlignment="Left"/&gt;
        &lt;TextBlock x:Name="TB2" Text="Last Name" Width="78" HorizontalAlignment="Left"/&gt;
        &lt;TextBlock x:Name="TB3" Text="Address" Width="60" HorizontalAlignment="Left"/&gt;
    &lt;/StackPanel&gt;
&lt;/Grid&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7b1dd9-2ec9-9b35-ff40-452d45ccfad1
* Version Independent ID: d9b5d656-9342-3799-e969-be7d411bd051
* Content: [StackPanel Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.stackpanel#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.stackpanel.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.stackpanel.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This is fixed.
