### ISSUE TITLE
Adding more details in Properties and Methods table.

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#1064]
It would be nice if the description column for Properties and Methods contained information regarding the Contract version or Windows Build version where such member was introduced and save time navigating to each individual entry page to figure out a map of build requirements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 724827cf-15a5-d5d6-5679-b4712d2c03ee
* Version Independent ID: cc05a8ff-4afb-bf61-fb81-fe02bf1bb7a0
* Content: [Compositor Class (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositor.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositor.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@JuanMejiaVelez, thanks for the suggestion. Adding to the generated member tables would require getting this suggestion through the backlog of the doc's engineering team. Instead, I've added a version history table that shows members that were added after the original release of the class. Hopefully this will help.
