### ISSUE TITLE
GetPreviewFrameAsync(VideoFrame) memory leak on Win10 19H1 

### ISSUE THREAD

**Issue by shenyaocn** [MicrosoftDocs/winrt-api#1066]
GetPreviewFrameAsync(VideoFrame) memory leak after update to 19H1 in my UWP app. 
I use following code like:
using (var frame = new VideoFrame(BitmapPixelFormat.Nv12, (int)props.Width, (int)props.Height))
                {
    while(bCapturing)
    {
        var previewFrame = await avCapture.GetPreviewFrameAsync(frame); // the issue disappear when I comment this line
        previewFrame.SoftwareBitmap.CopyToBuffer(nv12Pixels.AsBuffer());
    }
}
I use Visual Studio 2017 Community with 10.0.17763.0 SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35486802-4632-23d9-e2d1-1089dade42a7
* Version Independent ID: 968a2126-fca1-0ab7-3d6b-3509156b0396
* Content: [MediaCapture.GetPreviewFrameAsync Method (Windows.Media.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture.getpreviewframeasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapture.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapture.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by shenyaocn** [comment]
It seems a issue about Intel display driver. It disappears when I switch to Nvidia video card. And use MediaFrameReader on 1903 can fix this issue. I have use it in my app. https://www.microsoft.com/store/apps/9WZDNCRDMDRM

**Comment by stephenstarkie** [comment]
I have also seen a similar problem and can recreate it using the microsoft sample; https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/CameraGetPreviewFrame.  If I try this sample on Win10v1809 there is no leak.  If I try it on v1903, there is.  Also see; https://stackoverflow.com/questions/56647650/how-to-fix-memory-leak-in-getpreviewframeasync for more details

**Comment by shenyaocn** [comment]
> I have also seen a similar problem and can recreate it using the microsoft sample; https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/CameraGetPreviewFrame. If I try this sample on Win10v1809 there is no leak. If I try it on v1903, there is. Also see; https://stackoverflow.com/questions/56647650/how-to-fix-memory-leak-in-getpreviewframeasync for more details

Well, use MediaFrameReader on 1903 can fix this issue.

**Comment by stephenstarkie** [comment]
@shenyaocn Thanks - we'll give that a go

**Comment by shenyaocn** [comment]
@stephenstarkie You are welcome

**Comment by stephenstarkie** [comment]
We have tried the MediaFrameReader API; it works well, and fixes the problem (with less code!)
