### ISSUE TITLE
Remarks typo

### ISSUE THREAD

**Issue by MichaelKintscher** [MicrosoftDocs/winrt-api#1068]
Under Remarks: "The other two are Height and Height."... shouldn't one of those say "MinHeight"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c35ae096-1edc-0c96-814d-3bd4d89831ac
* Version Independent ID: aecc60fa-fd5e-5f14-9eb3-bbb53410395b
* Content: [FrameworkElement.MaxHeight Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.maxheight#Windows_UI_Xaml_FrameworkElement_MaxHeight)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.frameworkelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.frameworkelement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MichaelKintscher** [comment]
Also same issue appears to be under "See also"

**Comment by MikeHillberg** [comment]
Thanks for reporting this. Both MaxHeight and MinHeight were confused. [Fixes](https://github.com/MicrosoftDocs/winrt-api/pull/1071) are [pending](https://github.com/MicrosoftDocs/winrt-api/pull/1070/files).
