### ISSUE TITLE
returns UnauthorizedAccessException

### ISSUE THREAD

**Issue by trivalik** [MicrosoftDocs/winrt-api#1069]
I have an app with capabilities of "systemManagement". But anyway on windows 10.0.17763.316 the app returns with the exception on call of DateTimeSettings.SetSystemDateTime:
Message = "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"

But the code works on the raspberry 3.

Complete capabilities:

  &lt;Capabilities&gt;
    &lt;Capability Name="privateNetworkClientServer" /&gt;
    &lt;Capability Name="internetClient" /&gt;
    &lt;iot:Capability Name="systemManagement" /&gt;
  &lt;/Capabilities&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ce488b-a880-e9e1-8566-d144ff8b9870
* Version Independent ID: 83c07d66-3098-9a16-fc25-93a95886e369
* Content: [DateTimeSettings.SetSystemDateTime(DateTime) Method (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.datetimesettings.setsystemdatetime)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.datetimesettings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.datetimesettings.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn

**Comment by trivalik** [comment]
Please forward this error to your internals, since I have no ability to provide this error to microsoft.

**Comment by fabiozehnder** [comment]
was this solved? I am experiencing the same issue

**Comment by trivalik** [comment]
If you experiencing it, I guess no. Feel free to report it as mentioned in first reply.
