### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by jsmcneal** [MicrosoftDocs/winrt-api#1080]
Grid.ColumnSpan and Grid.RowSpan raise a 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beef116a-75c0-8f7c-24e9-30010f2fa9f7
* Version Independent ID: 464670d2-f758-0816-5868-4452f40ed8d7
* Content: [Grid Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Grid)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.grid.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.grid.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by chrisglein** [comment]
Links appear to be fixed MD references:

```
Then, you apply the [Grid.Row](grid_row.md) and [Grid.Column](grid_column.md) attached properties
```

As opposed to other references in the doc that work:

```
| Column | Gets or sets the column alignment of an element when child layout is processed by a parent Grid layout container.<ul><li>Type: int</li><li>Identifier field: <a href="https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.grid.columnproperty">ColumnProperty</a></li>
```

**Comment by MikeHillberg** [comment]
We have a general issue of how to present attached properties in the docs. For example in this case, there is no Grid.Row API; there's a RowProperty property which is rarely used, and static Set/GetRow methods.

I think the best fix for this is to make these link to the attached properties section [later in the page](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Grid#xaml-attached-properties).

**Comment by jwmsft** [comment]
Links to attached properties have been updated.
