### ISSUE TITLE
XAML accessiblity sample is old

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/winrt-api#1082]
Hello, accessibility is such an important topic now. It would be nice if the provided sample would be compilable with the recent VS+Win10 versions. Right now the sample in the section "See also" is for Windows 8.

https://code.msdn.microsoft.com/windowsapps/XAML-accessibility-sample-d63e820d

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b19312-d5aa-8024-9009-d56f43898596
* Version Independent ID: 4f9ea65e-5c52-3d3c-75c9-596c175dca13
* Content: [AutomationProperties Class (Windows.UI.Xaml.Automation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
thanks @ArchieCoder. I've updated the all links to point to more up to date samples and snippets.
