### ISSUE TITLE
IList<> under "Property Value" needs hotlink to IList<> page.

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1084]
IList&lt;&gt; under "Property Value" needs hotlink to IList&lt;&gt; page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6105a555-a5b4-7708-a665-ffc358295bf2
* Version Independent ID: 12263154-994b-c5c3-fb24-9005322e4ec7
* Content: [Frame.BackStack Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame.backstack#Windows_UI_Xaml_Controls_Frame_BackStack)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.frame.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.frame.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
This seems to be something in the doc generation system itself. @mimisasouvanh can you take a look?

**Comment by mimisasouvanh** [comment]
Created internal bug to track this issue: Bug 111640: IList<> under "Property Value" needs hotlink to IList<> page

**Comment by jwmsft** [comment]
This issue has been fixed.
