### ISSUE TITLE
What is the effect of the different options?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/winrt-api#1089]
In what way does these different options affect how `ExtendedExecutionForegroundSession` operate and function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acec2c-fc60-b978-4c7b-560be44ce787
* Version Independent ID: 0f4c7d92-55ac-7823-9121-0fefe66040a3
* Content: [ExtendedExecutionForegroundReason Enum (Windows.ApplicationModel.ExtendedExecution.Foreground) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundreason)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundreason.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundreason.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to submit an issue. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers) offer timely answers to questions like this.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open thread for follow-ups. Thanks!
