### ISSUE TITLE
Under which circumstances is extended execution revoked?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/winrt-api#1090]
What is it that triggers this event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83453813-ebfc-3f29-3ebd-dc82d7d9d3c5
* Version Independent ID: 330ce105-340b-97eb-fdd7-27c9353c7c88
* Content: [ExtendedExecutionForegroundSession.Revoked Event (Windows.ApplicationModel.ExtendedExecution.Foreground) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundsession.revoked)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundsession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.extendedexecution.foreground.extendedexecutionforegroundsession.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to submit an issue. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers) offer timely answers to questions like this.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open thread for follow-ups. Thanks!
