### ISSUE TITLE
Color.FromArgb not found in See also

### ISSUE THREAD

**Issue by LiangJianyi** [MicrosoftDocs/winrt-api#1096]
This link https://docs.microsoft.com/en-us/uwp/windows.ui/color_fromargb.md is invalid. In C# example, SolidColorBrush myBrush = new SolidColorBrush(Color.FromArgb(255, 20, 20, 90));
This code work because the Color.FromArgb method from System.Drawing;
System.Drawing.Brush cannot convert to Windows.UI.Xaml.Media.Brush or Windows.UI.Colors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf44abe-5f48-ee4f-550f-59714b47ea5c
* Version Independent ID: 2be86069-70f0-1678-5311-dc3693101a0c
* Content: [SolidColorBrush Class (Windows.UI.Xaml.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.SolidColorBrush#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.solidcolorbrush.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.solidcolorbrush.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@mijacobs @mimisasouvanh @mikehillberg I think this another case of C# having a different projection for  the WinRT member. Can we have a better way to create these kinds of links and detect these broken ones in the system before customers encounter them?

**Comment by mimisasouvanh** [comment]
@jevansaks These broken links can be caught in a CATS test, no? Looks like the broken link is hand-authored and should be https://docs.microsoft.com/en-us/dotnet/api/windows.ui.color.fromargb?view=dotnet-uwp-10.0. Am I misunderstanding the request here?

**Comment by jevansaks** [comment]
@mimisasouvanh This is a confusing thing about our projections. In C# it would be Color.FromArgb but in C++ you would use ColorHelpers.FromArgb. It would be nice to have a way where these types of links don't have to always be hand authored but we can have a way to link in such a way that you see the right function for the language you're using. @MikeHillberg may have thoughts too.

**Comment by mimisasouvanh** [comment]
@jevansaks Ah thanks for the explanation! I will talk to @IrinVoso more about this and create an internal tracking customer suggestion.

**Comment by jwmsft** [comment]
This link has been fixed.
