### ISSUE TITLE
Styles use unsupported styles

### ISSUE THREAD

**Issue by shmuelie** [MicrosoftDocs/winrt-api#11]
Examples are using styles that are not supported in Windows 10.

**Comment by kevinyr** [comment]
Hi Samuel, can you please point us to a specific example?

**Comment by kevinyr** [comment]
no response. closing.

**Comment by shmuelie** [comment]
Gah, saw your question, meant to answer and then completely forgot! Can't remember where it was so if I find them again I'll reopen
