### ISSUE TITLE
Bad rendering 

### ISSUE THREAD

**Issue by PapierenTijger** [MicrosoftDocs/winrt-api#1103]
The test is full of codes like "@Windows.Devices.Gpio.GpioPin.Write(Windows.Devices.Gpio.GpioPinValue)?text=GpioPin.Write" i think this is a rendering issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a9bba-c463-fbd4-ecec-68d2551a7560
* Version Independent ID: 6f488284-d88d-d64c-28d7-6fb2552de80c
* Content: [GpioPinDriveMode Enum (Windows.Devices.Gpio) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiopindrivemode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiopindrivemode.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiopindrivemode.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @PapierenTijger. Thanks for filing this issue, and apologies for the delay in responding. I've published a fix for this rendering issue, so I'll go ahead and close the issue.

Thanks again!
Steve
