### ISSUE TITLE
Should specify how you would set this value in the code behind

### ISSUE THREAD

**Issue by colinkiama** [MicrosoftDocs/winrt-api#1104]
It's not obvious that you have to use the "\u{hexcode}" syntax when setting this value in the code behind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b918ce6e-8aed-f7df-7e36-11981cb8605a
* Version Independent ID: 7bd20d62-02ee-3ced-9d72-179e63088558
* Content: [FontIcon.Glyph Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.fonticon.glyph#Windows_UI_Xaml_Controls_FontIcon_Glyph)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.fonticon.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.fonticon.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Agreed, this could be more clear with an example.

**Comment by StevenEdwardWood** [comment]
"/u{hexcode}" doesn't work either.  I tried many variations of it.  Fortunately, Roy LI, the moderator for the UWP MSDN Forum, provided the syntax "\x[hexcode]" which works.  For example in C#:
AppBarButton NewAppBarButton = new AppBarButton();
NewAppBarButton.Icon = New FontIcon();
NewAppBarButton.Icon.FontFamily = new FontFamily("Segoe MDL2 Assets");
NewAppBarButton.Icon.Glyph = "\xE700";

**Comment by colinkiama** [comment]
The example you've shown is perfect!

**Comment by ranaprathap2** [comment]
Thanks for the example ! :-)

**Comment by BrandonKuenzi** [comment]
Thank you! Saved my bacon! This really should be part of the documentation.

**Comment by sbeaudoin** [comment]
The question is : Why two different means to identify the same value to the same property of the same class?  Would it be better to standardize?  Now, it would break existing code.  I don't understand the original reason they did it this way.
