### ISSUE TITLE
Using UWP Windows.System.Launcher from desktop apps is under-documented

### ISSUE THREAD

**Issue by metathinker** [MicrosoftDocs/winrt-api#1107]
Since Windows 10 version 1903 (19H1), some of the static methods in the [Windows.System.Launcher](https://docs.microsoft.com/en-us/uwp/api/Windows.System.Launcher) class have been callable from a Windows classic/desktop application.

To do this, you need to do the following:

1. Call a Launcher method that takes a [LauncherOptions](https://docs.microsoft.com/uwp/api/windows.system.launcheroptions) object as a secondary parameter. (I believe that all such methods of Launcher will work for desktop apps, but I am unsure.)
1. After creating the LauncherOptions object but before passing it to Launcher, use IUnknown::QueryInterface() to get a reference to the object as an [IInitializeWithWindow](https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nn-shobjidl_core-iinitializewithwindow), and then call [Initialize(hwnd)](https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nf-shobjidl_core-iinitializewithwindow-initialize) with the HWND of an appropriate owner window.

Unfortunately, the only mention of any part of this procedure, or that Launcher is even usable from desktop apps, is on the below-linked page for [the LauncherOptions constructor](https://docs.microsoft.com/uwp/api/windows.system.launcheroptions.-ctor).

I don't think this is sufficient because:
- If you want to call Launcher methods from a desktop app, it is not obvious that you need to provide the owner window to LauncherOptions instead of Launcher directly.
- LauncherOptions' top-level page does not even mention that LauncherOptions implements IInitializeWithWindow, which makes the note about IInitializeWithWindow in the page about the LauncherOptions ctor even more surprising and incongruous.

To fix this gap, I would suggest that Launcher's doc pages be revised to mention that Launcher can be used from desktop apps using the above procedure, and as an extra hint, LauncherOptions' main doc page should be revised to say that LauncherOptions implements IInitializeWithWindow and that can be used to allow Launcher to be used from desktop apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b307847-adcf-8708-bc14-7bd494f30149
* Version Independent ID: 4dbc1ad8-a07b-ccde-9076-6ecead8e1bcc
* Content: [LauncherOptions Constructor (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcheroptions.-ctor#Windows_System_LauncherOptions__ctor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.launcheroptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.launcheroptions.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by HO-COOH** [comment]
Please, this needs to be addressed, or people get wasting time using WinUI 3.

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. There was information added to these docs in March 2022 about calling from desktop apps, with a link added for more info and examples. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!

**Comment by HO-COOH** [comment]
@alvinashcraft Just see the [issue](https://github.com/microsoft/WindowsAppSDK/issues/4460). The documentation is vague about 
> To access this page with a URI, use the ms-settings:appsfeatures-app URI and pass an optional parameter of the package family name of the app.

And nothing with that "optional parameter" we have tried so far worked
