### ISSUE TITLE
Incorrect information for language projections

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1108]
This page doesn't indicate the interfaces that are implemented by the classes. Note that which interfaces are implemented depends on the language. At the WinRT API level, this class implements IVector&lt;IInspectable&gt;, but in C# that shows up as IList&lt;Object&gt;.

And because of that translation, the members here aren't all correct. For example, in C++ this class has an Append method (from IVector&lt;T&gt;), but in C# it has an Add method (from ICollection&lt;T&gt;).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1684ad70-cbb8-b19f-b2cf-36abe3bd71d6
* Version Independent ID: 3d033312-d028-855f-1727-cb809d5fea2c
* Content: [ItemCollection Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.ItemCollection)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemcollection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemcollection.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@MikeHillberg Are you thinking this is an infrastructure bug or something we should try to handle in the way our docs are written?

@mijacobs  and @mimisasouvanh  as well

**Comment by mijacobs** [comment]
Thanks, Mike. We've filed a bug against the engineering team to track this issue.
