### ISSUE TITLE
Incapable of manipulating VpnPacketBufferList

### ISSUE THREAD

**Issue by bdbai** [MicrosoftDocs/winrt-api#111]
Hi there!
According to [this page](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnpacketbufferlist), most of the methods are marked as `Not supported.`. Please point out the alternative methods to those unsupported ones :).
IMHO a VpnPacketBufferList object shouldn't be  immutable. 

https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.networking.vpn/vpnpacketbufferlist_append_1519252907.md  
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.networking.vpn/vpnpacketbufferlist_addatbegin_136422118.md  
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.networking.vpn/vpnpacketbufferlist_append_1519252907.md  
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.networking.vpn/vpnpacketbufferlist_clear_556466.md

**Comment by mattwojo** [comment]
Hey @mcleblanc -- I'm having trouble finding an owner for this API Ref - could you help with finding the right person to address this issue?

**Comment by stevewhims** [comment]
Thanks for the heads up, @bdbai. I've removed the "Not supported", since these APIs are, in fact, supported. That change will go live tomorrow (Oct 26 2017).

**Comment by bdbai** [comment]
@stevewhims hooray! Thanks for tracking and fixing.

**Comment by stevewhims** [comment]
Btw, the topic to check is https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnpacketbufferlist#Methods (the methods AddAtBegin, Append, Clear, First, RemoveAtBegin, and RemoveAtEnd should no longer say "Not supported."). I expected this to be refreshed this morning but I'll give it the rest of the day. My commits were merged into master less than 24 hours ago and it can take some time before master goes live. Thanks for your patience!

**Comment by stevewhims** [comment]
Ok, the fix is now live. To verify, see links in previous comment.

**Comment by stevewhims** [comment]
@bdbai, this is fixed now. Feel free to close the issue if you're ok with the resolution.
