### ISSUE TITLE
Implementation details / example required?

### ISSUE THREAD

**Issue by bjthomson** [MicrosoftDocs/winrt-api#1110]
I was looking at GpioController with a view to building a library for some custom PC hardware.
I found someone asking the same questions, and implemented 

public  class MyGpioProvider : IGpioProvider
public  class MyGpioPinProvider : IGpioPinProvider
public  class MyGpioControllerProvider : IGpioControllerProvider

but I couldn't see how to wire in the new classes so that we could use

var gpio = GpioController.GetDefault();

I was misled by the names ending in "Provider" - these are not providers in the regular sense, they don't derive from ProviderBase they are simply interfaces, as denoted by the "I" at the front and I can't find an abstract factory to instantiate one. Also as they deal with hardware (unmanaged resources), shouldn't they implement IDisposable?

After much boogling, I discovered

LowLevelDevicesController.DefaultProvider = new SimulatedProvider.AggregateProvider();
and after implementing an AggregateProvider, it did indeed return a MyGpioController object. 

However 

GpioController.GetDefault() returns a GpIoController, not IGpioControllerProvider, so not quite there yet.

Also I can't find a way of adding more than one, so the method

public static IAsyncOperation&lt;IReadOnlyList&lt;MyGpioController&gt;&gt; GetControllersAsync(IGpioProvider provider)
 seems rather redundant, and potentially broken - it takes a parameter IGpioProvider but returns a list of MyGpioController?

All told, the whole thing seems a little half-baked, I'm really not sure its worth the effort.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5edd752-2d2c-152d-3d92-5b612bfec73e
* Version Independent ID: 4cbe1b61-b319-8507-9f3b-6d5b86e44e6b
* Content: [Windows.Devices.Gpio.Provider Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.provider#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.provider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.provider.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @bjthomson. Thanks for filing this issue, and my apologies for the delay in responding.

I've updated the topic to provide more info/clarification here. I'll leave the issue open for a while.

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
