### ISSUE TITLE
Document out of date

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/winrt-api#1112]
I noticed that the "See also" section has two different links with the same text so went to edit them, only to discover that the change I was going to make was previously made in Aug 31, 2018 but has yet to be reflected on the public site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ed25ed-18b6-c7d3-0b86-85f2576f7e65
* Version Independent ID: ba757ab4-5904-a39f-1828-5862c7635fdf
* Content: [CharacterCasing Enum (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.charactercasing#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.charactercasing.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.charactercasing.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@mijacobs I've seen other reports of this that the GitHub edits don't appear to be making it to the live site. Can you follow up?

**Comment by mijacobs** [comment]
GitHub updates have been merged into the live branch; this is an issue with SeeAlso links ignoring link text. We have a bug against the engineering team.
