### ISSUE TITLE
The description of `MaxBatchSize` is incorrect

### ISSUE THREAD

**Issue by MartinZikmund** [MicrosoftDocs/winrt-api#1113]
It seems the `Barometer.MaxBatchSize` documentation is a copy of the documentation of `Barometer.ReportLatency` so it is not clear what `MaxBatchSize` actually stands for

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5812255d-75c7-e390-12b5-7fdbfc78e3c2
* Version Independent ID: e431ca6f-1bf8-1dfb-697a-47d8bdd860ad
* Content: [Barometer.MaxBatchSize Property (Windows.Devices.Sensors) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.barometer.maxbatchsize#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.sensors.barometer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.sensors.barometer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @MartinZikmund! I revised the topic with the correct info.
