### ISSUE TITLE
 Document Details

### ISSUE THREAD

**Issue by chenburiram** [MicrosoftDocs/winrt-api#1115]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d51ee8cf-254f-52c0-7919-ad6dcc7a6649
* Version Independent ID: 0ebef3b9-696a-1742-3c8a-fd1cdfbbb2f4
* Content: [Windows.Networking.Connectivity Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.connectivity.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.connectivity.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by ginami** [comment]
Hi @chenburiram -- please let us know if you have feedback on our docs! Thank you!
