### ISSUE TITLE
Wrong text in Remarks UWP Slider.IntermediateValue

### ISSUE THREAD

**Issue by bkrauth** [MicrosoftDocs/winrt-api#1124]
Remarks section contains text from the SnapsTo property, rather than the IntermediateValue property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84ad7f6-1ae0-0db4-f9cc-d0f194d58442
* Version Independent ID: 5a6456b9-406f-6070-49ae-d22e2fca58f7
* Content: [Slider.IntermediateValue Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.slider.intermediatevalue#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.slider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.slider.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. The SnapsTo information was there because it's closely related to the IntermediateValue property. To avoid confusion, the text has been updated and includes a link to SnapsTo.
