### ISSUE TITLE
Content Source in docs.ms feedback issues

### ISSUE THREAD

**Issue by nxtn** [MicrosoftDocs/winrt-api#1126]
When providing feedback on the Windows Runtime API docs, there is a **Content Source** link in the generated GitHub issue to https://cpubwin.visualstudio.com (not accessible to the public), but in other docs it would point to a GitHub page. Just to confirm if it's by design.

For example,

- Issue: #1121 
- Content Source: https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.focusmanager.yml&version=GBlive&_a=contents
- GitHub page: https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.xaml.input/focusmanager_gettingfocus.md

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @NextTurn - thanks for pointing this out! 

I've logged this with our engineering team and a fix is in progress.
