### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by cdaylin** [MicrosoftDocs/winrt-api#1128]
Should the following sentence be updated by changing "false" to "true"?

This is because the existing On* definitions may have provided handling for an event that sets a Handled property value to false in some event's event data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a54ef3-1a1b-a755-79c0-d8d1ad6961de
* Version Independent ID: 192c8623-02ab-69a0-0f98-d7515bb5254f
* Content: [Control Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
You are correct! I will fix.

**Comment by jwmsft** [comment]
Fixed.
