### ISSUE TITLE
Please show what Exceptions can be thrown

### ISSUE THREAD

**Issue by bkrauth** [MicrosoftDocs/winrt-api#1129]
There are more exceptions, such as when internet is not available (cable unplugged).  Please show a more complete list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20e93d8-c2ed-adf0-233a-6ebb95015d95
* Version Independent ID: 4645a338-dc9a-dbfe-fd3b-f5620a5d3435
* Content: [HttpClient.GetBufferAsync(Uri) Method (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient.getbufferasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
I'm adding Peter for his advice and input on this issue. Peter, please let me know what info you'd like me to add to this topic. Just FYI, I've added my thoughts below about my understanding of our policy (in general) toward documenting exceptions; this API may be one of those unusual cases.

So...

Except in rare cases, it's our policy not to document exceptions, for a couple of reasons.

One reason is that a well-designed API throws only under conditions where the API isn't being used correctly. So, those conditions can (and should) be found and fixed at development/debug time. So, for a well-designed API, it'd be unnecessary to write production code that catches exceptions. The idea of this design is that for a condition such as an unplugged ethernet cable, where that's not a programming error, the API should not be throwing exceptions; but rather APIs should be able to communicate that condition in parameters or return values (if possible).

The other reason is that a Windows Runtime API itself indicates success/failure by returning an HRESULT value, and certain values result in programming-language-specific exceptions. So while we can document HRESULTs (and we do so for COM APIs), it's not that straightforward for Windows Runtime APIs.

We do have rare examples of APIs not following this prescription, and so we can document HRESULT values there.

Thanks!
~Steve

**Comment by PeterSmithRedmond** [comment]
I'll agree with Steve's analysis, and I can add some history and some technical details.

Windows.Web HttpClient now includes Try APIs (e.g., [TryGetBufferAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient.trygetbufferasync) ) to help solve the "too many exception" problem. The original thinking for the "throw on network exception" decision was to be compatible with other Windows APIs. As more people use these API, it's clear that that was a mistake: the exceptions are awkward to handle in code.

The HRESULT we surface can easily be an unfiltered HRESULT from the networking stack. An HTTP request depends on an enormous number of components in Windows. We depend on the network adapters sending requests at all, the IP layer for routing, the name resolution (DNS) system to find the HTTP server and the underlying HTTP engine which in turn needs to handle the cookie database, manage connections, and more. In addition, the HttpClient has a "filter" model; we can get exceptions from components that get plugged into the HTTP pipeline.

What many people do is divide all network requests into two buckets: ones that should be retried on failure, and ones that shouldn't. If an request is worth retrying on error, your network code then retries (using an exponential back-off so you don't slam the server or network with requests) up to a fixed number of times. I've found from experience that many network errors will potentially self-correct if a request is re-tried.

**Comment by stevewhims** [comment]
I'll go ahead and tentatively close this issue, then (but we can re-open if I made a mistake by doing that). Peter, if you feel that your guidance above isn't sufficiently covered in the docs, then I'd be happy to make corrections if you could give me the details.

Thanks!
Steve
