### ISSUE TITLE
Document that InjectKeyboardInput caps the number of inputs per call

### ISSUE THREAD

**Issue by docbrown** [MicrosoftDocs/winrt-api#1131]
If I call `InjectKeyboardInput` with more than 12 instances of `InjectedInputKeyboardInfo`, I get an `ArgumentException`. The documentation does not mention this limit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 558306cf-3156-4a8d-e27b-b62f9541599c
* Version Independent ID: 6a866c18-3969-7df8-218f-377cf8eeebd5
* Content: [InputInjector.InjectKeyboardInput(IIterable&lt;InjectedInputKeyboardInfo&gt;) Method (Windows.UI.Input.Preview.Injection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.inputinjector.injectkeyboardinput)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.preview.injection.inputinjector.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.preview.injection.inputinjector.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

The topic has been updated with more detail.
