### ISSUE TITLE
BROKEN: Leaks memory under Windows 10 v1903

### ISSUE THREAD

**Issue by stephenstarkie** [MicrosoftDocs/winrt-api#1134]
We upgraded two Surface Pro 4's to v1903 and both started leaking memory on this call.  See; https://stackoverflow.com/questions/56647650/how-to-fix-memory-leak-in-getpreviewframeasync and https://github.com/microsoft/Windows-universal-samples/issues/1108 and https://github.com/MicrosoftDocs/winrt-api/issues/1066 which suggests to use MediaFrameReader instead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35486802-4632-23d9-e2d1-1089dade42a7
* Version Independent ID: 968a2126-fca1-0ab7-3d6b-3509156b0396
* Content: [MediaCapture.GetPreviewFrameAsync Method (Windows.Media.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture.getpreviewframeasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapture.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapture.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions please see the [developer support page](https://developer.microsoft.com/windows/support) for your support options. I have alerted the feature team to this issue and will make any updates to the documentation related to this issue, as needed.

**Comment by stephenstarkie** [comment]
Always happy to help! My apologies; my intention was to point out an issue with the documentation; namely that the API doesn't perform as documented, in that the documentation doesn't document the side effect of leaking memory.  Unfortunately, closing this issue means that it gets less visibility and people wont realise that there is a very significant problem - perhaps the documentation could include a pointer to alternative ways of achieving the desired functionality, such as using https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframereader instead?  Are there other workarounds Microsoft know of that might help developers and could be added to the documentation?  Could you point us to where known issues with APIs are listed?  Perhaps each documentation page should list known issues so that they are visible and people can work around them?  Many companies are obliged by software standards such as IEC 62304 and even EU directives (and now regulations such as Regulation(EU) 2017/745) to list known issues with software they release.  I know in other places Microsoft is very proud of being standards compliant (https://www.microsoft.com/en-us/trustcenter/compliance/iso-iec-27001), perhaps documentation could also do this?

**Comment by drewbatgit** [comment]
Hello, the feature team is investigating this issue. As soon as they are able to verify and reproduce the bug and provide accurate technical details about the nature of the bug, affected platforms, and/or potential workarounds, I will add that information to the documentation. While that might take some time, they did agree that we should point people to the MediaFrameReader API for scenarios where a large number of frames are being captured. I have added a note to this affect to the documentation for both overloads of the GetPreviewFrameAsync method. Thanks for your feedback.

**Comment by stephenstarkie** [comment]
I think that's a great idea; thanks.  We have implemented the MediaFrameReader API instead and it works well.
