### ISSUE TITLE
Has this page not been updated?

### ISSUE THREAD

**Issue by StevenEdwardWood** [MicrosoftDocs/winrt-api#1136]
AVI is not listed; however, when I set Container.Subtype = "avi" there is no exception and the Container.Subtype is set to "AVI" so AVI is a predefined value.  

Also, according to the UWP Supported Codecs Container Subtypes "fMP4" and "MKV" are supported; however, setting Container.Subtype to "fMP4" or "MKV" causes an exception of "Value does not fall within the expected range." so they appear to have not been added to the System.Collections.ListDictionaryInternal used by Windows.Media.MediaProperties.ContainerEncodingProperties.put_Subtype(String value) so I will be posting on the product feedback as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9a35be-7a90-f36b-4278-d4d34a306319
* Version Independent ID: 5d07139d-4205-38fe-5195-026564b06816
* Content: [ContainerEncodingProperties.Subtype Property (Windows.Media.MediaProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.containerencodingproperties.subtype#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.containerencodingproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.containerencodingproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by SaschaIoT** [comment]
Set ContainerEncodingProperties.Subtype to "MPEG2TS" causes System.ArgumentException: 'Value does not fall within the expected range.'. I added the bug to GitHub repository: https://github.com/MicrosoftDocs/windows-uwp/issues/2087

**Comment by drewbatgit** [comment]
Sorry for the delayed response. This page was updated in January, 2020 to accurately reflect the currently supported subtypes.
