### ISSUE TITLE
Dead links (404)

### ISSUE THREAD

**Issue by ajpeacock0** [MicrosoftDocs/winrt-api#1137]
The following links under **Remarks** are dead (404)
&gt; For functionality similar to this member, see [Add(String,Object)](https://docs.microsoft.com/en-us/uwp/api/valueset_add_2) and [Add(KeyValuePair)](https://docs.microsoft.com/en-us/uwp/api/valueset_add_1).

As well as the 2 links under **See also**
- [Add(String,Object)](https://docs.microsoft.com/en-us/uwp/api/valueset_add_2)
- [Add(KeyValuePair)](https://docs.microsoft.com/en-us/uwp/api/valueset_add_1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9592346f-d97d-cd8f-b97d-dd6ec07b87da
* Version Independent ID: d15dcc43-7d17-8a82-0b4a-73a727b3d083
* Content: [ValueSet.Insert(String, Object) Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.valueset.insert#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.valueset.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.valueset.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Just checked in the fix for this. Should be published shortly.
