### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by liam-tuite** [MicrosoftDocs/winrt-api#1141]
"Use AdaptiveTrigger s..."
- should be "Use AdaptiveTriggers"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58e278f-7e7e-dc67-ba2f-4461723b216a
* Version Independent ID: e98a6aca-970b-b5ef-f2ad-450772e1cc50
* Content: [AdaptiveTrigger Class (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.AdaptiveTrigger#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.adaptivetrigger.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.adaptivetrigger.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Fixed
