### ISSUE TITLE
The ICommand no have a link

### ISSUE THREAD

**Issue by LiangJianyi** [MicrosoftDocs/winrt-api#1147]
It does not contain a hyperlink to a page that describing ICommand.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d8f12be0-a60b-f43f-8668-6dd59808d8ba
* Version Independent ID: 7ba16a79-d738-7fbb-2db4-b2be11bcc9f2
* Content: [ContentDialog.CloseButtonCommand Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.ui.xaml.controls.contentdialog.closebuttoncommand#Windows_UI_Xaml_Controls_ContentDialog_CloseButtonCommand)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
I believe this is related to the problem of language-specific mappings not having a consistent doc linkage experience.

**Comment by jwmsft** [comment]
This issue has been fixed.
