### ISSUE TITLE
Needs information and/or an example on how to use a custom data format.

### ISSUE THREAD

**Issue by JosephClampett** [MicrosoftDocs/winrt-api#1149]
Detail how to use a custom identifier and how to construct a RandomAccessStream for an arbitrary object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd0e6e0-c1fc-6f5d-9552-1d11dbff8320
* Version Independent ID: 4aba3b11-3c28-e6a5-865a-5daea64c590c
* Content: [DataPackage.SetData(String, Object) Method (Windows.ApplicationModel.DataTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackage.setdata)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.datapackage.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.datapackage.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by verelpode** [comment]
Hello, I agree with @JosephClampett.  I would much appreciate some documentation that explains how to place a custom data format on the clipboard.  

Likewise, I would also much appreciate UWP documentation that explains how to do the UWP equivalent of Win32's ["Private Clipboard Formats"](https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats#private-clipboard-formats).  How can a **private** object or data be placed on the clipboard?  Private meaning an object or data that is local to the process that puts it on the clipboard, not intended to be usable or available to other processes.  i.e. in some situations, we need copy & paste within the same app and don't have the ability to convert the object to a format that other apps can use.  Some objects are **not serializable** but we need to use them with copy & paste regardless.  Windows supports private formats, but how can this be performed in UWP?

**Comment by verelpode** [comment]
Is that a bug in GitHub?  Directly prior to this message, GitHub says:
> verelpode unassigned eliotcowley 41 minutes ago

I didn't unassign @eliotcowley and AFAIK I don't have access to assign or unassign anyone in the MicrosoftDocs repo.

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

For a code example that demonstrates how to share custom data formats, see the [https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/ShareSource](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/ShareSource) sample (the ShareCustomData.xaml and ShareCustomData.xaml.cs files).

For further assistance, the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to technical questions about UWP development.
