### ISSUE TITLE
null vs NULL

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#1150]
'null' won't work in cpp/winrt, am I right? Seems NULL is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae1c7ac-0a5f-2801-7360-134e21ac4b91
* Version Independent ID: db699579-ba8f-7d89-a1c7-cfa05e7743d3
* Content: [PointerRoutedEventArgs.GetCurrentPoint(UIElement) Method (Windows.UI.Xaml.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.pointerroutedeventargs.getcurrentpoint)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.pointerroutedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.pointerroutedeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @jevansAN. Unfortunately, the language selector only affects the syntax block and code snippets on a page. At this time, text content of the docs cannot be updated per the language selector and must be generic.
