### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by knightmeister** [MicrosoftDocs/winrt-api#1155]
This page reads like it's been automatically generated and does not explain what the property does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f4ed49-494b-921a-bd9c-f3427a9f5e6b
* Version Independent ID: 58f58315-8bf2-f5f9-95d0-6633a39a19b0
* Content: [TreeViewItem.HasUnrealizedChildrenProperty Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeviewitem.hasunrealizedchildrenproperty#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeviewitem.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeviewitem.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. We are working on improving our API reference documentation to provide more information and links to other relevant articles.

The `HasUnrealizedChildrenProperty`  property is just the Dependency Property identifier for the `HasUnrealizedChildren` property. You can learn more about Dependency Properties in the [Dependency Properties Overview](https://docs.microsoft.com/windows/uwp/xaml-platform/dependency-properties-overview).

If you're looking for information about the `HasUnrealizedChildren` property, you can learn more in the [TreeView](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/tree-view) article, specifically the [Fill a node when it's expanding](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/tree-view#fill-a-node-when-its-expanding) section.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
