### ISSUE TITLE
Heart Rate Sample does not run under Windows 10

### ISSUE THREAD

**Issue by stevennyman** [MicrosoftDocs/winrt-api#1158]
Heart rate sample does is not a UWP app and cannot be opened or built with Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f9e9d6-6609-bd06-d20d-087010de1e60
* Version Independent ID: ca6d38c2-a6ba-0f58-93db-b6963604d152
* Content: [Windows.Devices.Bluetooth.GenericAttributeProfile Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Bluetooth.GenericAttributeProfile#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @stevennyman. Thanks for filing this issue, and my apologies for the delay in responding.

I've updated the topic with a link to the correct sample (the Win10 UWP sample): [Bluetooth Low Energy sample](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BluetoothLE).

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since it's been a while, and it feels resolved. ~Steve
