### ISSUE TITLE
Regular email address?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/winrt-api#1163]
Hi,
I can spot two email address options:
- `EmailNameOrAddress`
- `EmailSmtpAddress`

What should the option used for a regular email input i.e. `name@domain.com`, with no names or smtp-domain-only addresses?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1cd6b7c-96a7-a750-ec88-a6be6b2ffc97
* Version Independent ID: d570118f-5584-9e68-f84f-fba18ebecff8
* Content: [InputScopeNameValue Enum (Windows.UI.Xaml.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.inputscopenamevalue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.inputscopenamevalue.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.inputscopenamevalue.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @weitzhandler, as described in the topic:


EmailNameOrAddress | 60 | Input scope is intended for working with an email name or full email address.
-- | -- | --
EmailSmtpAddress | 5 | Input scope is intended for working with a Simple Mail Transport Protocol (SMTP) form e-mail address (accountname@host).

Your example would be EmailSmtpAddress. The desc for EmailNameOrAddress is a little ambiguous. I'll update ASAP.
