### ISSUE TITLE
Camera in WPF app?

### ISSUE THREAD

**Issue by JohnStraumann** [MicrosoftDocs/winrt-api#1164]
Hello: I am trying to take a picture with the PC Webcam in a WPF app, does this namespace only work in Universal Windows Platform (UWP) apps? If so, can you tell me how to access the camera in a WPF app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e3bb9e-8901-f4db-82f3-e28b97b6f3df
* Version Independent ID: 336a4e71-b0e3-ef85-4c45-4b5ed65bc7f8
* Content: [Windows.Media.Capture Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I asked the camera feature team about this and there is not a C# API for USB cameras that is available from WPF. However there are C++/win32 code that you could theoretically call from WPF, but you would have to handle the bridging code yourself. I would recommend consulting the  [developer forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) for information about calling win32 code from C#.
