### ISSUE TITLE
How do I know If a device supports app data backup?

### ISSUE THREAD

**Issue by kevin-jing** [MicrosoftDocs/winrt-api#1165]
"If the device that runs this app supports app data backup", how do I know If a device supports app data backup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e6a57e-2928-4a93-64de-e49850ff988e
* Version Independent ID: a68f98bb-c15b-cdc9-8932-dcdec5f9f10f
* Content: [ApplicationData.LocalFolder Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localfolder#Windows_Storage_ApplicationData_LocalFolder)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdata.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdata.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by GrantMeStrength** [comment]
Ensure that the device is running a version of Windows that supports app data backup and restore functionality. This feature is available in Windows 10 and later versions, allowing users to back up app data to the cloud via their Microsoft account. Even if the operating system supports app data backup, it's crucial that the user has enabled the backup feature in their system settings. Users can configure these settings in the "Update & Security" section under "Backup" in the Windows Settings app.
