### ISSUE TITLE
Issue with binding on selectedItems

### ISSUE THREAD

**Issue by dimOk00** [MicrosoftDocs/winrt-api#1167]
This is really annoying that we can bind on SelectedItem, but can't on SelectedItems. 

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7a573be5-2021-f240-d200-ccb0a918c58d
* Version Independent ID: 287a5b16-ac4a-25cf-0c8f-9ae5245a93d0
* Content: [ListViewBase Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/ru-ru/uwp/api/windows.ui.xaml.controls.listviewbase)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
This is more of a feature request. Can you file this on https://github.com/microsoft/microsoft-ui-xaml/issues ? We'd prefer if you filed it so that you can get updates about the issue. If not, I can file it for you.
