### ISSUE TITLE
I cannot get the Windows.System.MemoryManager's appmemoryusagelimitchanging event to fire after following this documentation.

### ISSUE THREAD

**Issue by SoccerGee** [MicrosoftDocs/winrt-api#1168]
Here is my code:

```
  Windows.System.MemoryManager.addEventListener(
    "appmemoryusagelimitchanging",
    eventArgs => {
      console.log('this', eventArgs);
    };
  );
```

Nothing is ever logged when sending the application to the background.  However, this event fires correctly:

```
  const webUIApplication = Windows.UI.WebUI.WebUIApplication;
  webUIApplication.addEventListener(
    'enteredbackground',
    event => {
      try {
        // things
      } catch (e) {
        // error things
      }
    }
  );
```

Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4920f93-3797-6c0d-5fde-4538fcee8a5e
* Version Independent ID: ef5c70d3-6d69-8270-8d73-baeb7b6ba16b
* Content: [MemoryManager.AppMemoryUsageLimitChanging Event (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.memorymanager.appmemoryusagelimitchanging#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.memorymanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.memorymanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
