### ISSUE TITLE
Document access key workaround

### ISSUE THREAD

**Issue by YuliKl** [MicrosoftDocs/winrt-api#1170]
Currently, there's no way to set access keys on NavigationView's Back button and Settings item. https://github.com/microsoft/microsoft-ui-xaml/issues/941 lists some utility code that provides a workaround. This utility should be documented in docs.microsoft.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4dc6f7-f3bd-16b7-7dbc-56727af3fb97
* Version Independent ID: 89dadeaf-9bba-a58a-24cb-f731de2b7265
* Content: [NavigationView Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Docs have been updated.
