### ISSUE TITLE
I assume  It will append the text to the file

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/winrt-api#1176]
I wanted to look in this documentation to verify if my assumption is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dce19346-9252-ec27-5487-fb395c9cf876
* Version Independent ID: a5b53654-73d7-12b3-4ba4-e4d03b2ef4a1
* Content: [FileIO.WriteTextAsync Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileio.writetextasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.FileIO.WriteTextAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileio.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by LokiMidgard** [comment]
Ok, I just saw `AppendTextAsync` so I was probably wrong :)

**Comment by knicholasa** [comment]
You got it :) The [Work with files](https://docs.microsoft.com/en-us/windows/uwp/get-started/fileio-learning-track) doc talks about this in [the section on writing text to a file](https://docs.microsoft.com/en-us/windows/uwp/get-started/fileio-learning-track#write-text-to-a-file). **WriteTextAsync** will replace the contents of the file, while **AppendTextAsync** will append it.

**Comment by mhdshameel** [comment]
I don't see Write**Bytes**Async or WriteBufferAsync. How do I do this if I wanted to append bytes[] to the file.
