### ISSUE TITLE
GlobalSystemMediaTransportControlsSessionPlaybackInfo.PlaybackStatus Has the wrong type listed

### ISSUE THREAD

**Issue by zadjii-msft** [MicrosoftDocs/winrt-api#1178]
The docs list `Windows.Media.MediaPlaybackStatus` as the type of this property, when the actual type is `Windows.Media.Control::GlobalSystemMediaTransportControlsSessionPlaybackStatus`. Both enums have the same states, but they're ordered differently, so straight casting them also won't work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472fdbba-fd94-be90-e69c-b8dee0846ce8
* Version Independent ID: 270deb52-8ff0-5f52-0e8b-4b4ca12610f4
* Content: [GlobalSystemMediaTransportControlsSessionPlaybackInfo.PlaybackStatus Property (Windows.Media.Control) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionplaybackinfo.playbackstatus#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.control.globalsystemmediatransportcontrolssessionplaybackinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.control.globalsystemmediatransportcontrolssessionplaybackinfo.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your feedback. The type information is automatically generated by our doc build system from the source files, so it will require an engineering fix to correct this issue. I've opened a bug to drive this fix.

**Comment by drewbatgit** [comment]
This has been fixed by the engineering team. The page now renders the correct type. Thank you for reporting this issue.
