### ISSUE TITLE
Doc mistake

### ISSUE THREAD

**Issue by saintmatthieu** [MicrosoftDocs/winrt-api#1179]
Isn't "Creates a new AudioFrameOutputNode" that should be stated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df08eff6-351c-d331-3d1c-ce454c6c06e1
* Version Independent ID: ffe83cb3-f6ca-c56a-9b98-7b017a0d8b9e
* Content: [AudioGraph.CreateFrameOutputNode Method (Windows.Media.Audio) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.audio.audiograph.createframeoutputnode#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audiograph.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audiograph.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for catching this error! It has been fixed.
