### ISSUE TITLE
Links to generic types with specific type arguments are unusable

### ISSUE THREAD

**Issue by konsoletyper** [MicrosoftDocs/winrt-api#1183]
There are lots of links like these: `IAsyncOperationWithProgress&lt;IBuffer, ulong&gt;`, where the whole text is a single link. This makes this link unusable, since in case of APIs that return interfaces like IAsyncOperation, IVector, etc, I often interested in type argument's API rather than in generic type API. Compare this to [Files.lines](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#lines-java.nio.file.Path-) example in javadoc, where Stream and String are separate links pointing to Stream and String class documentation correspondingly. So in case of `IAsyncOperationWithProgress&lt;IBuffer, ulong&gt;` there should be three links (IAsyncOperationWithProgress, IBuffer, ulong).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed1fd878-072d-0fe9-cc21-a61097a191d7
* Version Independent ID: b8a905bc-7df5-e496-db72-5b32a4969a6b
* Content: [IHttpContent.ReadAsBufferAsync Method (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.ihttpcontent.readasbufferasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.ihttpcontent.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.ihttpcontent.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @konsoletyper, thanks for raising this issue. For this topic, I refactored the link (and the "See also") in the way you suggested. I did the same for another 34 topics in this namespace where the parameter types are non-primitive. ~Steve

**Comment by konsoletyper** [comment]
Hello. I don't think this issue can be closed. I don't think you should change documentation text to resolve it. I believe you guys generate documentation in the way similar to Javadoc, JSDoc, doxygen, etc. And I believe that text like

> Returns  
> IAsyncOperationWithProgress<IBuffer, ulong>

Is generated automatically from method signature. So the **proper** way is to update you documentation generation tool, not specific documentation pages. Please, reopen this issue and fix documentation generator.

**Comment by stevewhims** [comment]
You're right, @konsoletyper, getting that improved systematically would be great. So, I've filed an internal work item tracking that work. And I'll monitor it along with the others in my list. I'll go ahead and re-close here, since I'm taking care of it internally.

In this case, the writer had added links manually, so I think it was worth fixing/improving those.

Thanks again!
~Steve

**Comment by konsoletyper** [comment]
Thanks! Hope they'll able to fix documentation generator soon.
