### ISSUE TITLE
MediaPlaybackList.MaxPrefetchTime property description is confusingly worded

### ISSUE THREAD

**Issue by jbrianceau** [MicrosoftDocs/winrt-api#1185]
MediaPlaybackList.MaxPrefetchTime property is currently described in [windows.media.playback/mediaplaybacklist_maxprefetchtime.md](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.media.playback/mediaplaybacklist_maxprefetchtime.md) as:

> the maximum time before a MediaPlaybackItem in the list is expected to play that the media content associated with the item is retrieved.

That looks grammatically incorrect, and is very likely to give a headache to whoever tries to actually understand what this property is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f884a94-bc38-826e-6e46-7cb25b5a492a
* Version Independent ID: b30a4d8b-98b6-a397-69d7-134820ae5fde
* Content: [MediaPlaybackList.MaxPrefetchTime Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacklist.maxprefetchtime)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacklist.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacklist.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
The language has been updated to the following: "The prefetch time is the amount of time before an item is expected to begin playing that the system retrieves the item's media content."
