### ISSUE TITLE
Wrong default Minimum and Maximum values for ProgressBar

### ISSUE THREAD

**Issue by kathyang** [MicrosoftDocs/winrt-api#1187]
This docs page says "By default Minimum is 0 and Maximum is 1", but if you click into the page for Maximum you can see that the default Maximum value for ProgressBar is 100 - and if you create an empty project with just a ProgressBar the max value defaults to 100, not 1. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5be89c6-f6db-1c30-70a0-53859fb22671
* Version Independent ID: 99788db9-1138-7a5d-b86d-5a1e5f374e33
* Content: [ProgressBar Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.progressbar#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.progressbar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.progressbar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by kikisaints** [comment]
Created an internal PR to fix this typo.

**Comment by jwmsft** [comment]
Doc is updated.
