### ISSUE TITLE
MouseWheelParameters.DeltaScale does not reflect "Choose how many lines to scroll each time" Mouse setting

### ISSUE THREAD

**Issue by alexnesh** [MicrosoftDocs/winrt-api#1189]
As stated in the title - the `MouseWheelParameters.DeltaScale` property does not reflect the mouse setting for **_Choose how many lines to scroll each time_**. My interpretation of the docs was that this API was the UWP equivalent of `SystemInformation.MouseWheelScrollLines` in .NET Framework, but I'm guessing that I'm just interpreting this incorrectly :) 

Is there any way for a UWP app to query this system setting so that the app can adjust how much to scroll given the user setting? If I've misinterpreted the `MouseWheelParameters.DeltaScale` - how is this intended to be used? Does it reflect any system setting, or is it for something else entirely? 

Thanks,

AJN 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dabbd70-9613-a2e5-bc65-0d11fe135120
* Version Independent ID: be71f9c4-d50a-4a68-38fb-a133490f2aac
* Content: [MouseWheelParameters Class (Windows.UI.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.mousewheelparameters)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.mousewheelparameters.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.mousewheelparameters.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @alexnesh - As the API description states "Gets or sets a value that indicates the change in **scale** associated with input from the wheel button of a mouse." It sounds like you might be looking for the https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.mousewheelparameters.chartranslation property.

**Comment by alexnesh** [comment]
Hi @Karl-Bridge-Microsoft - thanks for the response! The value you referenced, `CharTranslation`, also does not change when I update the mouse setting for **_Choose how many lines to scroll each time._**, even after restarting the app, so that doesn't give me a way to scroll more/less. In fact, it seems none of the `MouseWheelParameters` change when I update that setting. Is this a bug, or am I missing something?

**Comment by alexnesh** [comment]
@Karl-Bridge-Microsoft - happy to open a bug if these values indeed are intended to change with the aforementioned property, but some guidance on whether or not this is a bug would be great. Thanks.

**Comment by Karl-Bridge-Microsoft** [comment]
@alexnesh - In further reading the CharTranslation topic, the remarks specify: 

If the wheel button is set to scroll three lines at a time for each detent and the value of CharTranslation is set to (8,16), vertical scrolling is applied at 3 x 16 = 48 device-independent pixel (DIP) per detent. Horizontal scrolling through the mouse tilt wheel is applied at 3 x 8 = 24 device-independent pixel (DIP) per detent.

So, this property is a conversion factor that you can set. The control panel setting is just the input for this conversion to DIP.

**Comment by alexnesh** [comment]
Ok - so CharTranslation does not give me the setting that I'm looking for, namely, how many lines to scroll for each detent. 

What I'm looking for is the UWP equivalent of `SystemInformation.MouseWheelScrollLines` - does UWP expose such a property, or am I out of luck here?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @alexnesh, I spoke with the feature team and got this response (they also suggested a minor revision to the description in the topic):

the GestureRecognizer queries it internally, so the output should already be scaled relative to it. These knobs are just to control how the GR converts this already-scaled output to its final result.

So, if you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.

Hope this helps!
