### ISSUE TITLE
Incorrect enum

### ISSUE THREAD

**Issue by allan-ok** [MicrosoftDocs/winrt-api#1191]
Repeated values on enum

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183dd6c1-e193-116d-b1fd-536526af139e
* Version Independent ID: 40cb2e15-7d46-9054-be46-95cc65989c65
* Content: [FlyoutShowMode Enum (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutshowmode#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutshowmode.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutshowmode.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by mimisasouvanh** [comment]
@allan-ok Thank you for reporting this issue. We've opened an internal bug to track this issue while we investigate.

**Comment by jwmsft** [comment]
This issue has been fixed. Thanks.
