### ISSUE TITLE
Confusing docs for WebView.UnsafeContentWarningDisplaying

### ISSUE THREAD

**Issue by verelpode** [MicrosoftDocs/winrt-api#1193]
Hello, I'd be grateful if you could improve the documentation for [WebView.UnsafeContentWarningDisplaying](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.unsafecontentwarningdisplaying).  It has the following ambiguous statement:
> This event is not implemented on Windows Phone 8.1 and will never be raised.

What is that supposed to mean in regards to Windows versions before and after 8.1?  Is `UnsafeContentWarningDisplaying` still relevant in Windows 10 or is it obsolete?

Thanks very much for writing clear documentation whenever possible.  Clear unambiguous descriptions are very helpful when trying to write reliable software that uses Windows components.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff6b3698-2d4c-0d8a-fd73-2051a3a83e48
* Version Independent ID: 34068d8b-4833-2b69-32db-36c7aa529987
* Content: [WebView.UnsafeContentWarningDisplaying Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.unsafecontentwarningdisplaying?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.WebView.UnsafeContentWarningDisplaying)%3Bk(vs.objectbrowser)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%26rd%3Dtrue#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by marb2000** [comment]
@jevansaks could you assign this to @adambarlow who is driving WebView right now?

**Comment by jwmsft** [comment]
Sorry for the delayed response to this issue, and thanks for the feedback. The note applies only to Windows ***Phone*** 8.1. The event is still relevant on the PC (non-Phone) version of Windows 8.1, or any version of Windows 10.
