### ISSUE TITLE
AppMemoryUsageIncreased not firing

### ISSUE THREAD

**Issue by jnvbui** [MicrosoftDocs/winrt-api#1196]
This event is not firing for me even when memory increase causes app to eventually crash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa3f3d87-fbe0-cbba-9340-0782c8e7f83f
* Version Independent ID: e015d3be-efe3-e80e-af2b-5e081dd221ca
* Content: [MemoryManager.AppMemoryUsageIncreased Event (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.memorymanager.appmemoryusageincreased#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.memorymanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.memorymanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
