### ISSUE TITLE
It is hard to read the description column of the table.

### ISSUE THREAD

**Issue by zipswich** [MicrosoftDocs/winrt-api#1197]
I tried different browsers (Chrome, Edge, Firefox) on different monitors (including two 2560 x 1080 ultra-wide monitors),  I always have to go to the bottom of the table to use the scroll bar to view the description column of the table API table.  It is a nuisance.  Not sure why the API column needs so big width.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24e16883-46b8-2b26-d8f4-915e101a2b88
* Version Independent ID: 2b5d9934-4efe-d594-9819-a66e0455e305
* Content: [MediaStreamSource Class (Windows.Media.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediastreamsource#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediastreamsource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediastreamsource.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for reporting this issue. The formatting of the table has been updated.

**Comment by zipswich** [comment]
Thank you.  The current format is far better than the previous one on any of the monitors that I use.
