### ISSUE TITLE
See Also - Last Link not working.

### ISSUE THREAD

**Issue by robv8r** [MicrosoftDocs/winrt-api#1198]
The last link under "See Also" isn't working propertly.  It appears that markdown is incorrect.

Currently, all that is displayed is "Windows.UI.Xaml.RoutedEventArgs tedEventArgs](routedeventargs.md)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2081cd27-43ae-afd6-16ff-b1283aec94e1
* Version Independent ID: 3f5a5a29-2c22-a69a-5a32-fb68dc1647eb
* Content: [RoutedEvent Class (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.routedevent)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.routedevent.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.routedevent.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for bringing this to our attention. The link is fixed now.
