### ISSUE TITLE
It's not clear where members are added in specific Windows versions

### ISSUE THREAD

**Issue by peterfoot** [MicrosoftDocs/winrt-api#12]
For example GetDeviceSelectorForPairingStatus is new to Creators Update - but there is no way to tell this from the documentation. The BluetoothLEDevice page indicates support from 10.0.10240.

https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.devices.bluetooth/bluetoothledevice_getdeviceselectorfromconnectionstatus_401358086.md

**Comment by Neme12** [comment]
I'm having the exact same problem. There needs to be more information about which versions each API is available in. For me I found out that CoreDragOperation.AllowedOperations seems to be missing from 10240 but there's no mention of that and I can't find anything about when it was introduced.

**Comment by kevinyr** [comment]
We know this is an issue and it is something we're currently working to resolve.

**Comment by kevinyr** [comment]
This has been resolved. See [this page](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.dragdrop.core.coredragoperation#properties_) where AllowedOperations now has content that says it was introduced in 10.0.10586
