### ISSUE TITLE
Documentation for StreamSocket Close() method has important typo

### ISSUE THREAD

**Issue by madriani** [MicrosoftDocs/winrt-api#120]
[Here](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocket#Windows_Networking_Sockets_StreamSocket_Close), you find this text: "For apps written using the .NET Framework 4.5 in C# and VB.NET, the [Close](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocket#Windows_Networking_Sockets_StreamSocket_Close) method is exposed **as the method on** the [StreamSocket](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocket)."
It should be "For apps written using the .NET Framework 4.5 in C# and VB.NET, the [Close](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocket#Windows_Networking_Sockets_StreamSocket_Close) method is exposed **as the _[Dispose()](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Sockets.StreamSocket#Windows_Networking_Sockets_StreamSocket_Dispose)_ method on** the [StreamSocket](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.streamsocket)."

**Comment by msatranjr** [comment]
Thanks for spotting this issue and reaching out! This should be fixed in the docs branch now.
