### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by tbrummel** [MicrosoftDocs/winrt-api#1200]
First example is not for this topic - it has nothing to do with styles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b290bdb-24fa-8951-625e-e8cbe19ded49
* Version Independent ID: 8766e84a-f9ac-ebd5-224b-0ef888243cf7
* Content: [Style.TargetType Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.style.targettype?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Style.TargetType)%3Bk(VS.XamlEditor)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.style.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.style.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@tbrummel, thanks for letting us know about this error. I've updated the doc with the correct code example.
