### ISSUE TITLE
r6u56jfffffffffff3b  jvjn rose wood net work doble slop sink bag off adam rainbow snuff supper natureal

### ISSUE THREAD

**Issue by milkyway1** [MicrosoftDocs/winrt-api#1201]
[Enter feedback here]
r9 7hvuhru9n nfen vn0j28h3nen cubwdsvcyeh9ijfpoA\JC0NSX NFB V
0PJGHJREKHK=TJ[.=PY,--JAHXGFZADA
---XFGHRTJ64
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659e5dbe-7b95-fec7-3d22-275b55304c84
* Version Independent ID: 4a55f79d-7405-a58a-451b-85c0fce49fc6
* Content: [Windows.Security.Credentials.UI Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Security.Credentials.UI)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.credentials.ui.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.credentials.ui.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by hkhmsft** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so we have closed it.
