### ISSUE TITLE
Use Smart Card  in UWP 

### ISSUE THREAD

**Issue by Freeedy** [MicrosoftDocs/winrt-api#1205]
Is it  possible  to read smart card content or update  (using apdu commands ) it using those classes ?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 965bf547-3340-2128-d2c5-4f8932b079bc
* Version Independent ID: cf4b24ac-c1eb-8400-26ce-5fe0b6a61ffa
* Content: [SmartCardReader Class (Windows.Devices.SmartCards) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.smartcards.smartcardreader#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.smartcards.smartcardreader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.smartcards.smartcardreader.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by bobonline19** [comment]
Yes. See the Windows 10 samples [https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/Nfc](url). Should possibly add this to the see also

**Comment by stevewhims** [comment]
Hi, @Freeedy, and thanks for filing this issue. I've updated the topics to include a link to the related samples.

Thanks!
Steve
