### ISSUE TITLE
Broken reference links

### ISSUE THREAD

**Issue by indigogiant** [MicrosoftDocs/winrt-api#1207]
Hi, the reference links to the CustomHidDeviceAccess sample are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b9e899d-3104-dbbb-4b1e-ffa67d5c5173
* Version Independent ID: 36a131c5-cb84-08bb-12f8-ad6c1c37daf8
* Content: [HidDevice.CreateFeatureReport Method (Windows.Devices.HumanInterfaceDevice) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hiddevice.createfeaturereport#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting the broken link. This has been fixed.
