### ISSUE TITLE
Windows 10 Home

### ISSUE THREAD

**Issue by ajportz** [MicrosoftDocs/winrt-api#1208]
It looks like this namespace now works on Windows 10 Home version 1903.  It looks like it may have been updated in the 1809 release?
https://docs.microsoft.com/en-us/windows/uwp/whats-new/windows-10-build-17763-api-diff#windowsgraphics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42ef33c-6bc8-a64e-3f9b-07edab79db6d
* Version Independent ID: eca4edb7-7268-8ad7-075c-0d494d869609
* Content: [Windows.Graphics.Capture Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.capture.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.capture.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I have removed the note about the feature only being available for Pro and Enterprise. The change should be visible on the live site within 24 hours. Thanks for helping keep the documentation up to date and accurate!
