### ISSUE TITLE
IDisplayDeviceInterop?

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/winrt-api#1211]
It's mentioned here, but not documented. It seems like it might be the key to actually producing some content to display this way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf38282-9956-1582-e2eb-fd8ce15895af
* Version Independent ID: 9f558858-d309-e925-1ea1-63aa9bb4afc0
* Content: [DisplayFence Class (Windows.Devices.Display.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displayfence)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.display.core.displayfence.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.display.core.displayfence.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by stevewhims** [comment]
Hi, @rpavlik, and thanks for filing this issue. You're right, this is a gap in the documentation right now. I'm working with the feature team to get the missing APIs documented. I'll update this comment when I have more info.

Thanks again!
Steve

**Comment by stevewhims** [comment]
Hi, @rpavlik, the documentation that I mentioned earlier is now live here: https://docs.microsoft.com/windows/win32/api/windows.devices.display.core.interop/nn-windows-devices-display-core-interop-idisplaydeviceinterop.

I'll go ahead and close this issue now.

Thanks!
Steve
