### ISSUE TITLE
Trying to use in WPF but cannot.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#1212]
I'm quite new to WPF development so I may be missing something obvious in my workflow or logic.
If I create a reference in my WPF project to Windows.Foundation.UniversalApiContract, I thought that would allow me to use the CaptureElement in my XAML file, but when I add the namespace then the control, I get this message:

Error	XDG0008	The name "CaptureElement" does not exist in the namespace "clr-namespace:Windows.UI.Xaml.Controls;assembly=Windows.Foundation.UniversalApiContract"

Which obviously it does. Is this even possible, or should I look into a DirectShow implementation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb54ac5-27ea-249a-6134-871a3c8708c9
* Version Independent ID: f6438e11-b101-cd7b-03f4-842534eb0205
* Content: [CaptureElement Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CaptureElement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.captureelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.captureelement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
To use a UWP XAML element in your app you would need to use XAML Islands. Directly using the element in your WPF tree isn't supported.
