### ISSUE TITLE
Confirm whether location capability is really required

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-api#1213]
Is the location capability really required to construct a Geopoint? I don't want to access the user's location. I am interested only in reading/writing location info to a media file using the GeoTagHelper and possibly displaying or picking this location from a map. I tried it on my local PC and I seem to be able to construct a Geopoint fine without this capability (although I couldn't set the altitude in a file using the GeoTagHelper). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035d9ffe-58dd-9b46-8269-eae2d49941c6
* Version Independent ID: 978da836-50b9-21e7-bbe8-c36e855579ca
* Content: [Geopoint Constructor (Windows.Devices.Geolocation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.geopoint.-ctor#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.geopoint.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.geopoint.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. 

Though the scope of our feedback channel here on GitHub covers specific documentation bugs, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to technical questions about UWP development.

If you do create a thread over at Microsoft Q&A that answers your question, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
