### ISSUE TITLE
PathGeometry Figures does not accept moveAndDrawCommands

### ISSUE THREAD

**Issue by indigogiant** [MicrosoftDocs/winrt-api#1214]
Attempting to use the 'Figures="moveAndDrawCommands"' syntax doesn't work, instead an error is reported: 'The TypeConverter for "PathFigureCollection" does not support converting from a string.'

There are reports of this from 2015, so I assume that it's intended behaviour and the documentation is incorrect.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b218d7e-2b04-e906-4795-9ef2b2597dd3
* Version Independent ID: a18c0a1c-9d1b-31a5-4d05-7cf134e2bd0f
* Content: [PathGeometry.Figures Property (Windows.UI.Xaml.Media) - Windows UWP applications](https://docs.microsoft.com/en-au/uwp/api/windows.ui.xaml.media.pathgeometry.figures)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.pathgeometry.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.pathgeometry.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by HppZ** [comment]
same question for me

**Comment by jwmsft** [comment]
Thanks for pointing this out. The documentation has been corrected.
