### ISSUE TITLE
Missing Link To WiFiAvailableNetwork

### ISSUE THREAD

**Issue by Yamazaki93** [MicrosoftDocs/winrt-api#1218]
The link to page https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifi.wifiavailablenetwork is missing from property value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d31f1d8-199f-e1d7-52ae-8872f5637400
* Version Independent ID: 04724f66-aa82-8e9b-7ed9-a6edcd9e1b1c
* Content: [WiFiNetworkReport.AvailableNetworks Property (Windows.Devices.WiFi) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifi.wifinetworkreport.availablenetworks#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.wifi.wifinetworkreport.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.wifi.wifinetworkreport.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by stevewhims** [comment]
Hi, @Yamazaki93, thanks for filing this issue. I've updated the description of the property to include a link to the property's type. Longer-term, we're working on a systemic fix for generic types such as this one, where the text under the "Property value" heading is hyperlinked.

Thanks again!
Steve
