### ISSUE TITLE
GpioChangeCount

### ISSUE THREAD

**Issue by Sigis-Leal** [MicrosoftDocs/winrt-api#1220]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98303ab3-01fd-5039-f324-a4ae287050bf
* Version Independent ID: 0e926a94-752f-884c-c1f9-672c9c834814
* Content: [GpioChangeCount Struct (Windows.Devices.Gpio) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiochangecount#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiochangecount.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiochangecount.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by stevewhims** [comment]
Hi, @Sigis-Leal, I checked the topic, and I can't see anything that needs actioning. I'll go ahead and close this issue, but if you have a description of your feedback regarding the documentation, then feel free to re-open the issue.

Thanks!
Steve
