### ISSUE TITLE
Explain the difference between GetScaledImageAsThumbnailAsync() and GetThumbnailAsync()

### ISSUE THREAD

**Issue by lukeblevins** [MicrosoftDocs/winrt-api#1222]
It would benefit the community for there to be a documented explanation regarding the differences between these methods. Which is the most optimized for a scenario of rapidly accessing many StorageItemThumbnails in succession?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd2d53c0-d5ec-8ac2-df90-d309702a8631
* Version Independent ID: 0d925be3-9648-de78-6420-cf0c32daad43
* Content: [StorageFile.GetScaledImageAsThumbnailAsync Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getscaledimageasthumbnailasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by lukeblevins** [comment]
@lastnameholiu This was filed quite a long time ago, and still hasn't been addressed. Is there anything you can share about the differences between these two methods?

**Comment by lukeblevins** [comment]
@lastnameholiu Any update on this?

**Comment by lukeblevins** [comment]
@lastnameholiu @knicholasa Will this feedback item be addressed, or should I simply close it because it has been ignored?

**Comment by lukeblevins** [comment]
@lastnameholiu Can you please answer this, or assign it to someone else? This was opened in September

**Comment by hkhmsft** [comment]
Hi @duke7553 , apologize for the delayed response and thanks for following up on this. I've put a work item to get input from the feature folks. I'll circle back in this thread if there are any significant updates.

**Comment by lukeblevins** [comment]
@lastnameholiu Hi. Were you able to get any updates from them on this?

**Comment by lukeblevins** [comment]
@lastnameholiu Still waiting on the difference between GetScaledImageAsThumbnailAsync() and GetThumbnailAsync(). It's been over a year now.

**Comment by lukeblevins** [comment]
@lastnameholiu Still waiting. This is unacceptable.

**Comment by lukeblevins** [comment]
@knicholasa @lastnameholiu Is this repo still the right place to ask questions about WinRT APIs? It seems like this is something that should be clarified in the docs.

**Comment by hkhmsft** [comment]
Hi @duke7553 , I've currently bumped our internal thread to get an answer from our pool of SME's. I hope to have a solid answer hopefully by end of week. Thanks for following up.

**Comment by hkhmsft** [comment]
Hi @duke7553 , from what I'm gathering it seems that GetThumbnailAsync adheres to the max size supported by the thumbnail disk cache and GetScaledImageAsThumbnailAsync can extract thumbnails that are larger than what the thumbnail disk cache supports. To answer your original question, GetScaledImageAsThumbnailAsync provides optimal quality but can affect performance by not using the disk cache if the thumbnail size is too large.

I'm going to be opening a PR to add this note to the documentation and notify you when it's live.

**Comment by lukeblevins** [comment]
@lastnameholiu I really appreciate it. That answered my question! I'd love to see the PR opened just to make sure other developers won't mistake these two methods.

**Comment by hkhmsft** [comment]
The changes are now live. Thanks once again, @duke7553 . Closing this thread.
