### ISSUE TITLE
Mission information about Windows 8.x support

### ISSUE THREAD

**Issue by poizan42** [MicrosoftDocs/winrt-api#1223]
As Windows 8.1 Update is still supported until January 2023 the page should probably still list availability in Windows 8.1 (this isn't the only page where this is a problem, but it was the one I stumbled upon). The old and somewhat broken version of the page [here](https://msdn.microsoft.com/en-us/windows/desktop/windows.management.deployment.packagemanager) contains the following:

> ## Requirements (Windows 8.x and Windows Phone 8.x)
> | | |
> --- | ---
> Minimum supported client | Windows 8 [desktop apps only]
> Minimum supported server | Windows Server 2012 [desktop apps only]
> Minimum supported phone | None supported
> Namespace | Windows.Management.Deployment<br>Windows::Management::Deployment [C++]
> Metadata | Windows.winmd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adecb6c7-a20b-4e93-19c1-64c8ca0c0b0a
* Version Independent ID: ef12b24c-754e-27b6-19b6-85ec408e1890
* Content: [PackageManager Class (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response. 

As this page has been updated since you reported the issue, and the sheer volume of of feedback in this repo requires us to prioritize new issues, we're closing this one due to age and lack of activity.

If you think the issue still exists and should be addressed, please open a new issue with any details/suggestions you think might be helpful.
