### ISSUE TITLE
How can we access StreamSocket object underlying HttpClient?

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1224]
In case of HTTPS, we would like to access server certificate details. How can this be accomplished.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e82a1752-c86f-2764-bd85-45f8ca1ed6a3
* Version Independent ID: f2a6cfa3-b81f-bad3-6f05-486a83b30eb5
* Content: [HttpClient Class (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Adding @PeterSmithRedmond to see whether he knows the answer. If so, and if we need to document that details, then I'll do that.

**Comment by PeterSmithRedmond** [comment]
There's two ways. The simplest way is to look at the [TransportInformation](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httprequestmessage.transportinformation)  data that's attached to each individual HttpRequest. (It's on the HttpRequest and not the HttpResponse for the subtle reason that if the TLS/SSL connection fails, there won't be an HttpResponse).

You can also get it by specifying an a [base protocol filter](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.HttpBaseProtocolFilter)  when you make your HttpClient. On the base protocol filter there's a [Server Custom Validation](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.httpbaseprotocolfilter.servercustomvalidationrequested) event.

In all cases, please read [The Most Dangerous Code in the World](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.httpbaseprotocolfilter.servercustomvalidationrequested). It's very easy to almost validate your TLS/SSL connection correctly, but actually simply allow all connections.

**Comment by PeterSmithRedmond** [comment]
I just provided an answer; we already had reasonable docs for this.

**Comment by stevewhims** [comment]
Looks like we're resolved here. I'll go ahead and close, but feel free to reopen if you feel I've closed in error. ~Steve
