### ISSUE TITLE
IsGrasped and HoloLens 2

### ISSUE THREAD

**Issue by caseymeekhof** [MicrosoftDocs/winrt-api#1228]
For HoloLens 2, this property also triggers when pinching or closing your hand.  This is described in the developer guide here: https://docs.microsoft.com/en-us/windows/mixed-reality/hands-and-motion-controllers-in-directx#cross-device-input-properties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0667364-0d31-b547-8b6b-fc85b72a1872
* Version Independent ID: df41789d-bcb4-0e17-d761-ffaac27fa6e3
* Content: [SpatialInteractionSourceState.IsGrasped Property (Windows.UI.Input.Spatial) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.spatial.spatialinteractionsourcestate.isgrasped)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.spatial.spatialinteractionsourcestate.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.spatial.spatialinteractionsourcestate.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@caseymeekhof - Thanks for the feedback. I've updated the topic with more info.
