### ISSUE TITLE
Wrong url link

### ISSUE THREAD

**Issue by dani924** [MicrosoftDocs/winrt-api#1229]
In "An asynchronous operation that returns an AppRecordingResult object upon completion, which contains information about the status of the recording operation." AppRecordingResult  link is pointing to local address on disc instead of docs.microsoft.com address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed651da-16ea-7286-4ff6-70e24b6b11f6
* Version Independent ID: 0aa578c8-af81-8054-24ac-b4206eaf91be
* Content: [AppRecordingManager.StartRecordingToFileAsync(StorageFile) Method (Windows.Media.AppRecording) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.apprecording.apprecordingmanager.startrecordingtofileasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.apprecording.apprecordingmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.apprecording.apprecordingmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for reporting this issue! This link has been fixed.
