### ISSUE TITLE
More details about what is the "Menu" modifier key.

### ISSUE THREAD

**Issue by sbeaudoin** [MicrosoftDocs/winrt-api#1235]
All the other modifiers are evident, but what is the "Menu" modifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e30e65-537f-0c95-7b5d-e5c08f4c69ec
* Version Independent ID: ad8154d1-0d08-11f6-e6d5-03965203856c
* Content: [VirtualKeyModifiers Enum (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkeymodifiers)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkeymodifiers.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkeymodifiers.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The menu key is the context menu key included on many, but not all, Windows keyboards. For more information, see [Menu key](https://en.wikipedia.org/wiki/Menu_key)

**Comment by sbeaudoin** [comment]
How about including this information on the page?  I am sure I am not the only one who doesn't know what this key is.
