### ISSUE TITLE
Add the default key assigner to each virtual key.

### ISSUE THREAD

**Issue by sbeaudoin** [MicrosoftDocs/winrt-api#1236]
I would appreciate if you can details the default physical key assigned to each virtual key.  I suppose, without confirmation, the "Go Back" key is backspace?  I have no way to confirm that other than trying it with code.  Google details are sparse on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf98772b-2d62-70f3-9a17-0e6bf58a236a
* Version Independent ID: d32568d4-d904-46e3-254d-43a240d2a37f
* Content: [VirtualKey Enum (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkey)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkey.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkey.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The virtual "Go Back" key is mapped to the physical go back key. Note that many of the keys in this list are not included on US standard 104 key keyboard.

**Comment by sbeaudoin** [comment]
"Physical Go Back Key"?  You know the joke?  A user see the message "Press any key to continue" and ask himself "Where is the 'any' key?" ?  What is the "Go Back" key?  Seriously though.
