### ISSUE TITLE
Where is `HasKey` method?

### ISSUE THREAD

**Issue by jingkecn** [MicrosoftDocs/winrt-api#1239]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8737acc0-6999-b6b6-b2a0-0e60d1fbaced
* Version Independent ID: 674a4a42-6206-d73a-cc08-a27285694599
* Content: [CharacterGroupings.Lookup(String) Method (Windows.Globalization.Collation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.collation.charactergroupings.lookup#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.collation.charactergroupings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.collation.charactergroupings.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@jingkecn - thanks for raising this issue. The remark is incorrect. I've updated the topic with the correct detail provided by the feature team.

If successful, this method returns the label. Otherwise, it returns the input value.
