### ISSUE TITLE
Document Improvement

### ISSUE THREAD

**Issue by petercoin** [MicrosoftDocs/winrt-api#1242]
It is better to add a snippet for DeviceCapability in Package.appxmanifest. Besides, there should be a Remarks section for blocked usage pages by UWP such as mouse, keyboard...etc..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83152a6e-786e-58ea-7af9-71046fbdcce4
* Version Independent ID: f1ddf84f-a0a6-f20b-e7e2-c3842b24e69f
* Content: [HidDevice Class (Windows.Devices.HumanInterfaceDevice) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hiddevice#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I apologize for the delayed response. I am adding several links to the remarks and examples sections on this page that point to information about the manifest entries, usage limitations, and other background info/examples.
