### ISSUE TITLE
The same update is applicable on the subsequent paragraph (the color info isn't stripped from the bitmap if ShowAsMonochrome is false).

### ISSUE THREAD

**Issue by ws7789337** [MicrosoftDocs/winrt-api#1243]
The same update is applicable on the subsequent paragraph (the color info isn't stripped from the bitmap if ShowAsMonochrome is false).

_Originally posted by @MikeHillberg in https://github.com/MicrosoftDocs/winrt-api/pull/1079#issuecomment-490699858_

**Comment by jwmsft** [comment]
The doc has been updated.
