### ISSUE TITLE
Imprecisely documented.

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1245]
Experimenting based on experience writing (non-Windows) drivers strongly suggests this property is the amount of time the serial device (driver?) will wait for another byte to arrive before timing out and returning a partial buffer amount. A value of 0ms seems to be "infinite" -- meaning the device will never return a partial buffer because it will wait infinitely for another byte to arrive until the requested LoadAsync() amount is satisfied.

This seems to be confirmed in testing (using 9600,N,8,1). A 0ms setting causes LoadAsync() to only return when the entire requested amount has been loaded even if InputStreamOptions is Partial. A 1ms setting causes LoadAsync() to return with various different counts but never more than the requested amount. Increasing the value of this property starts to increase the tendency toward LoadAsync() returning larger amounts. Pauses between bursts of data being received tend to be reflected in LoadAsync() returning the burst increments without waiting for the full requested amount when this property is large enough to wait for a next byte, but small enough to not wait across the inter-burst time.

All this testing supports this property being the timeout value for how long the driver will wait for a next byte to arrive before giving up and returning a partial LoadAsync() amount, with 0ms indicating infinite wait. I suspect the docs authors can find confirmation of this in the specification for writing Windows serial drivers. There is likely a near 1:1 correspondence between this property and some value being given to serial drivers.

If somebody does look to clean up this docs page, including investigating the driver docs, it would be efficient to clean up the WriteTimeout page at the same time. The function of that value is likely also reflected in the driver docs.

[Later]

This WDK (Windows Driver Kit) page ([https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddser/ns-ntddser-_serial_timeouts]) likely has some relationship to ReadTimeout and WriteTimeout, but that's only an educated guess on my part. Somebody familiar with the .NET SerialDevice class implementation would need to confirm. That page also talks about a couple more properties which interact with timing out which do not seem to be reflected in the SerialDevice properties.

**Comment by tedhudek** [comment]
Hi @kburgoyne, sorry for the delay.  Could you please provide the link of the doc page about which you're commenting above?

**Comment by kburgoyne** [comment]
Woah... past life.  If memory serves, this should pertain (specifically) to:

https://docs.microsoft.com/en-us/uwp/api/windows.devices.serialcommunication.serialdevice.readtimeout

and

https://docs.microsoft.com/en-us/uwp/api/windows.devices.serialcommunication.serialdevice.writetimeout

Since posting this comment/issue, another issue I posted resulted in the addition of the purple(?) "Note" added to the SerialDevice.ReadTimeout property page (the first URL above).  That note referencing the SERIAL_TIMEOUTS struct documentation was about a 70% solution to providing some clarification for the ReadTimeout and WriteTimeout properties.

However if you use the link to SERIAL_TIMEOUTS in the Note block, you'll discover there is a lot more timeout config information than is reflected in just .NET's ReadTimeout and WriteTimeout.  So the developer is then still "left in the dark" about how the .NET properties are being mapped to the SERIAL_TIMEOUTS struct.

If the .NET docs for the ReadTimeout and WriteTimeout properties were to explain what values (for all fields) actually end up getting set in the SERIAL_TIMEOUTS struct, THEN the developer could go to the SERIAL_TIMEOUTS struct page and understand what those values end up meaning.

**Comment by stevewhims** [comment]
Hi, @kburgoyne. I've added more info to [SerialDevice.ReadTimeout](https://docs.microsoft.com/uwp/api/windows.devices.serialcommunication.serialdevice.readtimeout) and [SerialDevice.WriteTimeout](https://docs.microsoft.com/uwp/api/windows.devices.serialcommunication.serialdevice.writetimeout). Does that additional info look sufficient?

Thanks!
Steve

**Comment by kburgoyne** [comment]
Oh yes. GREAT job, Steve!  I love how you covered ulong.MaxValue for BOTH read and write -- since its value for read could easily lead a person left wondering about write.
