### ISSUE TITLE
Wrong hyper link

### ISSUE THREAD

**Issue by yac073** [MicrosoftDocs/winrt-api#1251]
In the Remarks section, there appears two "Custom video effects" where the second one links to Custom audio effects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10737767-7816-11c1-4794-e2d9bb5fe858
* Version Independent ID: 7abee57d-6ad6-95e1-c5be-691aac33fa4d
* Content: [Windows.Media.Effects Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.effects#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.effects.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.effects.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for reporting this issue. The text of the link to Custom audio effects has been updated.
