### ISSUE TITLE
SpeechRecognitionRestult points to the wrong URL

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#1254]
This page has an incorrect link for Result property, where SpeechRecognitionResult leads to this page https://docs.microsoft.com/en-us/uwp/windows.media.speech.recognition/speechrecognitionresult.md which does not exists, the correct link should be https://docs.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognitionresult 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c8424b-f04b-f93a-6c51-016d864fcd76
* Version Independent ID: 08370692-ec35-3977-bae4-2cd13e1b8882
* Content: [IVoiceCommandActivatedEventArgs Interface (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.ivoicecommandactivatedeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.ivoicecommandactivatedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.ivoicecommandactivatedeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. A fix has been submitted.
