### ISSUE TITLE
Winrt example missing

### ISSUE THREAD

**Issue by ergan89** [MicrosoftDocs/winrt-api#1257]
Trying to convert CX to winrt but there's no example for the winrt version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc08b11-963e-9299-c25a-34d2532e383d
* Version Independent ID: 64263e88-16ca-6893-d776-5a57bfd5fda7
* Content: [IDirect3DDevice Interface (Windows.Graphics.DirectX.Direct3D11) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.directx.direct3d11.idirect3ddevice#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.directx.direct3d11.idirect3ddevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.directx.direct3d11.idirect3ddevice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for filing the issue, @ergan89. I've added a C++/WinRT code example to the topic, and a link to another topic (Composition) that has a related code example. I'll go ahead and close this issue, but please reopen it if I've made a mistake. Thanks! ~Steve
