### ISSUE TITLE
Link to ShareOperation object docs under Remarks is broken

### ISSUE THREAD

**Issue by Huios** [MicrosoftDocs/winrt-api#1259]
The link to ShareOperation object docs under Remarks is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d812029c-9aa8-ad57-1580-1ee280735935
* Version Independent ID: dc8294d9-7a7d-8466-2708-8300d936033c
* Content: [ShareTargetActivatedEventArgs.ShareOperation Property (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.sharetargetactivatedeventargs.shareoperation#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.sharetargetactivatedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.sharetargetactivatedeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. A fix has been submitted.
