### ISSUE TITLE
How can I configure the wifi band to 5 GHz or 2.4 GHz?

### ISSUE THREAD

**Issue by q89123003** [MicrosoftDocs/winrt-api#1261]
I was trying to use Powershell script to set up windows 10 mobile hotspot (which is the function in "Settings" -> "Network & Internet" -> "Mobile hotspot"). I was able to turn it on through the following script:

```
[Windows.System.UserProfile.LockScreen,Windows.System.UserProfile,ContentType=WindowsRuntime] | Out-Null

# Define functions. Not important to this question
Add-Type -AssemblyName System.Runtime.WindowsRuntime
$asTaskGeneric = ([System.WindowsRuntimeSystemExtensions].GetMethods() | ? { $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and $_.GetParameters()[0].ParameterType.Name -eq 'IAsyncOperation`1' })[0]
Function Await($WinRtTask, $ResultType) {
    $asTask = $asTaskGeneric.MakeGenericMethod($ResultType)
    $netTask = $asTask.Invoke($null, @($WinRtTask))
    $netTask.Wait(-1) | Out-Null
    $netTask.Result
}
Function AwaitAction($WinRtAction) {
    $asTask = ([System.WindowsRuntimeSystemExtensions].GetMethods() | ? { $_.Name -eq 'AsTask' -and $_.GetParameters().Count -eq 1 -and !$_.IsGenericMethod })[0]
    $netTask = $asTask.Invoke($null, @($WinRtAction))
    $netTask.Wait(-1) | Out-Null
}

# Create tethering manager
$connectionProfile = [Windows.Networking.Connectivity.NetworkInformation,Windows.Networking.Connectivity,ContentType=WindowsRuntime]::GetInternetConnectionProfile()
$tetheringManager = [Windows.Networking.NetworkOperators.NetworkOperatorTetheringManager,Windows.Networking.NetworkOperators,ContentType=WindowsRuntime]::CreateFromConnectionProfile($connectionProfile)

# Create configuration
$configuration = new-object Windows.Networking.NetworkOperators.NetworkOperatorTetheringAccessPointConfiguration
$configuration.Ssid = "test"
$configuration.Passphrase = "12345678"

# ===================== My question is here =====================
[enum]::GetValues([Windows.Networking.NetworkOperators.TetheringWiFiBand])
$configuration | Get-Member 
# ===============================================================

# Check whether Mobile Hotspot is enabled
$tetheringManager.TetheringOperationalState

# Set Hotspot configuration
AwaitAction ($tetheringManager.ConfigureAccessPointAsync($configuration))


# Start Mobile Hotspot
Await ($tetheringManager.StartTetheringAsync()) ([Windows.Networking.NetworkOperators.NetworkOperatorTetheringOperationResult])
```
 but I could only set the SSID and the Passphrase of the network but not the network band which we can choose between '5 GHz', '2.4 GHz' or 'Any available' in the setting gui. 

I saw on this post (https://blogs.windows.com/windowsdeveloper/2019/09/10/windows-10-sdk-preview-build-18975-available-now/#DwOj8B0wPu5zd9hK.97) that it seems there is an enum 'TetheringWiFiBand' to set that starting from Windows 10 SDK, version 1903, build 18362 (it's exactly my windows version). However, as you can see, in the middle of my script, when I tried to access this enum, I got an error:

`Unable to find type [Windows.Networking.NetworkOperators.TetheringWiFiBand].`

Also, there is no such an enum when I print the member of `Windows.Networking.NetworkOperators.NetworkOperatorTetheringAccessPointConfiguration`

Does anyone have an idea of how to set the wifi band of the mobile hotspot based on this method? Thanks.

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
