### ISSUE TITLE
Add missing error code documentation

### ISSUE THREAD

**Issue by vgromfeld** [MicrosoftDocs/winrt-api#1262]
GetItemCountAsync() can return different error codes based on the queried folder.
There should be documented on this page. Querying an empty (video) library is now throwing `HRESULT_FROM_WIN32(ERROR_EMPTY)` instead of `E_FAIL`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 749013ed-4705-c7ed-3026-16108eeef434
* Version Independent ID: b098301a-3645-2f52-9f1e-ac6fbf50239c
* Content: [StorageFileQueryResult.GetItemCountAsync Method (Windows.Storage.Search) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.storagefilequeryresult.getitemcountasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.Search.StorageFileQueryResult.GetItemCountAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.storagefilequeryresult.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.storagefilequeryresult.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
