### ISSUE TITLE
Add missing precondition

### ISSUE THREAD

**Issue by vgromfeld** [MicrosoftDocs/winrt-api#1264]
This method is throwing if `FrameFormat` is not set to `SphericalVideoFrameFormat.Equirectangular`. This should be added in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b0a018-1e0e-785d-e2bd-820c1116a0f5
* Version Independent ID: 66b53899-c0c5-b914-3872-4e69d8ffa8ce
* Content: [MediaPlaybackSphericalVideoProjection.IsEnabled Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksphericalvideoprojection.isenabled)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksphericalvideoprojection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksphericalvideoprojection.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your feedback. I have added confirmed this behavior in the source code and added this information to the API reference page: https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksphericalvideoprojection.isenabled
