### ISSUE TITLE
Need a way to remove GPS information

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-api#1266]
This allows adding GPS information to a file, but I can't see a 'remove' function. There needs to be one in order to be able to 'undo' the action of adding the GPS info.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921ba20d-188b-b282-2327-edda13b6395f
* Version Independent ID: 24b2545a-a20b-ab17-e3b7-a4613e1801cb
* Content: [GeotagHelper Class (Windows.Storage.FileProperties) - Windows UWP applications](https://docs.microsoft.com/en-gb/uwp/api/windows.storage.fileproperties.geotaghelper)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.geotaghelper.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.geotaghelper.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.

**Comment by benstevens48** [comment]
Hi @lastnameholiu,
The UserVoice site for UWP is now closed - see https://wpdev.uservoice.com/forums/110705-universal-windows-platform. It suggests providing feedback in the Docs GitHub instead. Actually, it links to here - https://github.com/MicrosoftDocs/windows-uwp/issues. Should I move the feedback to there?
