### ISSUE TITLE
Please demonsrate this concept in code

### ISSUE THREAD

**Issue by fabfella** [MicrosoftDocs/winrt-api#1277]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a85f8021-b98e-7e96-5c5d-7808acc4e3d8
* Version Independent ID: 7cb14b25-e0d6-ea6e-b94b-9a83348c58b0
* Content: [Canvas.SetLeft(UIElement, Double) Method (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.canvas.setleft?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.Canvas.SetLeft)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Sorry, demonstrate what? Like how to call the static method?

```
Canvas.SetLeft(myElement, 5);
```

**Comment by jasoneales** [comment]
Demonstrate how to use Canvas.SetLeft. Is that no the point of the help wiki? 
This is code I have found from looking through a whole lot of third-party websites, instead of finding it here on the help wiki were one would expect to find it.

```
private void DrawRectangle()
        {
            Rectangle rect = new Rectangle();

            SolidColorBrush sb = new SolidColorBrush(Colors.Black);

            rect.Stroke = sb;

            rect.Height = 100;
            rect.Width = 100;

            Canvas.SetLeft(rect, 10);
            Canvas.SetTop(rect, 20);

            MyCanvas.Children.Add(rect);
        }
```
