### ISSUE TITLE
Getting numeric price from formatted price

### ISSUE THREAD

**Issue by aiiitm** [MicrosoftDocs/winrt-api#1280]
Is there any method which returns a number price instead of formatted price? Or any utility/library through which we can get the numeric value(eg. 4.99) instead of formatted string("$4.99")

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 977c9053-dd7b-c1b9-f02c-eaaee42f341d
* Version Independent ID: 7ca98b52-b44f-85b7-9afa-b04109c95d69
* Content: [StorePrice Class (Windows.Services.Store) - Windows UWP applications](https://docs.microsoft.com/en-gb/uwp/api/windows.services.store.storeprice#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storeprice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storeprice.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by aiiitm** [comment]
@hickeys 
Could you please revert back on this query?

**Comment by aiiitm** [comment]
@hickeys @lastnameholiu can one of you look into the query and revert back?

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
