### ISSUE TITLE
No link to ContextMenuOpeningEventHandler / Arguments

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1281]
This doc is a dead-end forcing me to go search again as I need to see the event args to this event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b4c634-0662-269b-cc98-eecdb3c5337b
* Version Independent ID: 9a22e4c7-9ce9-bf87-4b7d-8027e0a5b97e
* Content: [TextBox.ContextMenuOpening Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.contextmenuopening)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by michael-hawker** [comment]
I believe it should link to here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contextmenuopeningeventhandler

**Comment by jevansaks** [comment]
@mimisasouvanh seems like a doc system issue that there isn't a link to the delegate type.

**Comment by jwmsft** [comment]
Due to limitations of the doc system, a link was added to See Also.
