### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#1286]
Would love to see an example of extracting the raw midi data from the message in C++/winrt. Is it really going to be necessary to create a DataReader to interpret the DataBuffer? Seems expensive for real-time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7e67c6d-029e-9d8a-dc51-03e67e2292cc
* Version Independent ID: 7e9bd3b0-a180-7e09-c3b6-82bfb0fa3de7
* Content: [IMidiMessage.RawData Property (Windows.Devices.Midi) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.midi.imidimessage.rawdata#Windows_Devices_Midi_IMidiMessage_RawData)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.imidimessage.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.imidimessage.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @jevansAN, I'd recommend making this an ask of the [MIDI sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MIDI). It sounds like the ask is for a C++/WinRT version of the existing C# sample. You can file an issue against the samples repo if you follow that link.

-Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since there's no further action we can take here. Please reopen if I made a mistake in closing. ~Steve
