### ISSUE TITLE
Please add a reference to SetPreferredMinSize

### ISSUE THREAD

**Issue by adrientetar** [MicrosoftDocs/winrt-api#1289]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.preview.windowmanagementpreview.setpreferredminsize

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2862f896-0db5-9185-8803-38cd6b685e58
* Version Independent ID: 90ec076a-75b9-d59b-6335-66ba41924845
* Content: [AppWindow Class (Windows.UI.WindowManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.windowmanagement.appwindow.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.windowmanagement.appwindow.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Sorry for the delayed response, and thanks for the suggestion. This link has been added to the page.
