### ISSUE TITLE
Missing link to AutoSuggestBoxSuggestionChosenEventArgs page

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1290]
Missing a quick link to the `AutoSuggestBoxSuggestionChosenEventArgs` type page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f46791a-9ef2-5539-6906-22b683755287
* Version Independent ID: 6b389499-4cdd-c822-543f-df7d5edc572f
* Content: [AutoSuggestBox.SuggestionChosen Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.autosuggestbox.suggestionchosen)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.autosuggestbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.autosuggestbox.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by michael-hawker** [comment]
Should be here: https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.AutoSuggestBoxSuggestionChosenEventArgs

**Comment by jevansaks** [comment]
Event/delegate pages seem to not link to the types involved (like args and delegate). @mimisasouvanh is this being tracked?

**Comment by mimisasouvanh** [comment]
@jevansaks This looks like a content issue...Unless you are wanting the links to the type pages to be automated, which they aren't currently. Please assign to @lastnameholiu to add a link to the type page.

**Comment by jevansaks** [comment]
I'm hoping the links to the type pages can be automated, we have a lot of pages that are affected like this.

**Comment by jwmsft** [comment]
Resolved. These links are now added automatically in the doc build.
