### ISSUE TITLE
Sample typo

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-api#1291]
the sample on this page says "matrixes" but the correct spelling is "matrices"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ed89e22-716c-830e-d509-4246556f3aef
* Version Independent ID: 324465da-81fb-722b-a82c-e100466972b2
* Content: [Matrix3DProjection Class (Windows.UI.Xaml.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Matrix3DProjection#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.matrix3dprojection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.matrix3dprojection.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@asklar you can click the "edit" button on the page to help us fix typos. :)
