### ISSUE TITLE
How to quickly access status bytes?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#1293]
I've found that a keyboard that specifies a note-off by using zero-velocity combined with running status of 0x90 won't work here - the incoming message is identified as a MidiNoteOnMessage. So it's necessary to access the raw data of the MIDIMessage. But the docs above do not show an efficient way to accomplish that. In C++/winrt the implication is that we'd have to declare a DataReader to process the buffer returned by the message. For 2 or 3 bytes, in real time? Could the docs show a usage example for this situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 801dfe0f-6025-13a6-c857-ff3bffc4ca48
* Version Independent ID: 43ca66c2-d1bb-44b2-1622-9f75f69999db
* Content: [MidiNoteOnMessage.RawData Property (Windows.Devices.Midi) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.midi.midinoteonmessage.rawdata#Windows_Devices_Midi_MidiNoteOnMessage_RawData)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.midinoteonmessage.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.midi.midinoteonmessage.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @jevansAN, I'd recommend making this an ask of the [MIDI sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MIDI). It sounds like the ask is for a C++/WinRT version of the existing C# sample, together with your specific scenario. You can file an issue against the samples repo if you follow that link.

-Steve

**Comment by jevansAN** [comment]
Thanks, Steve - I found a workaround: since the NoteOnMessage has a Velocity property, one can check that for zero: if it's zero assume this  is really meant to be a note-off. That works and then it's not necessary to get into the raw data.

**Comment by hkhmsft** [comment]
Thanks Steve for the link to the repo and thanks jevansAN for following up with a workaround. Closing this Issue for now. If there is any other feedback you'd like to submit please do so through our [Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app).
