### ISSUE TITLE
WwwFormUrlDecoder constructor doc statement about unescaping is incorrect

### ISSUE THREAD

**Issue by docbugger** [MicrosoftDocs/winrt-api#1296]
The documentation states:
"_URL-encoded characters are not decoded, they are simply included in the name-value pairs._"

The opposite is true: percent-encoded values are unescaped, and the decoded string is returned when accessing the IWwwFormUrlDecoderEntry.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7daf627b-128d-a863-f066-4a20c3eaa5fd
* Version Independent ID: 09df0b1e-8136-1001-b637-201003f92b61
* Content: [WwwFormUrlDecoder(String) Constructor (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.wwwformurldecoder.-ctor#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.wwwformurldecoder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.wwwformurldecoder.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by benstevens48** [comment]
I can confirm this. It is essential that the docs are updated to be corrected. That is, the `Value` property has already had a function which unescapes percent-encoded characters applied to it, so it can be used directly without any further decoding.

**Comment by docbugger** [comment]
Hi @hickeys , this issue is more than a year old, and the doc is still incorrect.

**Comment by Karl-Bridge-Microsoft** [comment]
This topic has been updated with the suggested revision. Thanks!
