### ISSUE TITLE
What does it mean "For more info, see the section."

### ISSUE THREAD

**Issue by madmrmax** [MicrosoftDocs/winrt-api#1298]
In the Setting Source in Code the last sentence in the first paragraph has a weird statement" For more info, see the section." https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image.source#setting-source-in-code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfaef85-bd7a-c480-ca3d-7551ba4e421f
* Version Independent ID: 0b6dc7c7-cd22-c685-743d-4ffad6608ce3
* Content: [Image.Source Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image.source)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
I thought it might be a markdown rendering issue but there's just nothing there. I don't know which section it should go to. @jesbis?

**Comment by jesbis** [comment]
Not sure but I don't think it's necessary - opened a PR to remove it.
