### ISSUE TITLE
Provide Windows requirements

### ISSUE THREAD

**Issue by tim-weis** [MicrosoftDocs/winrt-api#1299]
This event was introduced in API contract v5, but that information is not present in this document. To find out, we would have to navigate to the [TextBoxBeforeTextChangingEventArgs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textboxbeforetextchangingeventargs) documentation, that's not even linked from this page.

Please incorporate the Windows requirements into this (and other) event documentation (and optionally add links to the respective argument types).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79700e3-57c4-f7be-7149-2fbf8a2e24cf
* Version Independent ID: 226ef2af-7a17-5461-6bf7-9ba7f612dd13
* Content: [TextBox.BeforeTextChanging Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.beforetextchanging#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@mimisasouvanh is this tracked by any work on the engineering side?

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @tim-weis!

I've added the cross-link you mentioned (and similar to a number of other TextBox event topics). The missing requirements info is being tracked as an engineering bug and should be fixed in the near future.
