### ISSUE TITLE
Edit link on this page does not work, generates a 404

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-api#13]
On [this page](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.EventRegistrationToken) the [second edit link](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.foundation/eventregistrationtoken_value.md) in the fields section leads me to a 404.

**Comment by mhopkins-msft** [comment]
This is an issue with the system. Thanks for reporting. You can edit the **Value** field by clicking the first [Edit](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.foundation/eventregistrationtoken.md) link at the top of the page.

**Comment by mcleblanc** [comment]
This issue has been fixed. Thank you for bringing this issue to our attention.
