### ISSUE TITLE
Requires confirmAppClose capability

### ISSUE THREAD

**Issue by yashrajborse** [MicrosoftDocs/winrt-api#1300]
This event is fired only if the app has “&lt;rescap:Capability Name="confirmAppClose"/&gt;” capability in the appxmanifest. 
Good to mention about this capability on this page and also link the app capability page in see also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b9e1ea-ce97-060d-ab07-6b67fb2a6198
* Version Independent ID: 5d8798ae-1c4c-bc48-0e1f-48522e988375
* Content: [AppWindow.CloseRequested Event (Windows.UI.WindowManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow.closerequested#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.windowmanagement.appwindow.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.windowmanagement.appwindow.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for pointing this out. The information has been added to the doc.
