### ISSUE TITLE
InkToolbarRulerButton vs InkToolbarStencilButton

### ISSUE THREAD

**Issue by Poopooracoocoo** [MicrosoftDocs/winrt-api#1301]
Remarks -&gt; "A second group of "toggle" buttons containing the built-in ruler (InkToolbarRulerButton ) button. Custom toggles (InkToolbarCustomToggleButton ) are added here."

When you go to the InkToolbarRulerButton page, in the remarks section, it is suggested that "Apps that target Windows Creators Update (SDK 15063) or later should use the InkToolbarStencilButton object instead of this object.". It's a good idea to change "InkToolbarRulerButton" on this page to "InkToolbarStencilButton". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1171fae9-fb2f-fd23-d490-1491dcb599be
* Version Independent ID: 8936a08a-1f16-de71-5395-8d858f6ad580
* Content: [InkToolbar Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.inktoolbar#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.inktoolbar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.inktoolbar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Sorry for the very delayed response. This topic (and others) has been updated with the suggested revision.

**Comment by Poopooracoocoo** [comment]
only a two year delay? that's pretty quick for microsoft
