### ISSUE TITLE
Incorrect type for winrt version for typedeventhandler object

### ISSUE THREAD

**Issue by ergan89** [MicrosoftDocs/winrt-api#1303]
winrt version uses IInspectable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97562317-0bd6-baa3-8d84-7321cbc423e2
* Version Independent ID: e9b1c180-5080-e1ae-d9b1-c62016fa91e2
* Content: [SpatialSurfaceObserver.ObservedSurfacesChanged Event (Windows.Perception.Spatial.Surfaces) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.surfaces.spatialsurfaceobserver.observedsurfaceschanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.surfaces.spatialsurfaceobserver.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.surfaces.spatialsurfaceobserver.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by stevewhims** [comment]
Hi, @ergan89, and apologies for the very long delay in responding to this issue.

I'm interpreting "winrt" as "C++/WinRT".

I looked over the syntax for the various language projections and they all look correct on the live site right now.

I'll go ahead and close the issue. If you're still seeing issues, please describe the issue in terms of *how* you repro the problem, what you *expect* to see, and what you *actually* see.

Many thanks!
Steve
