### ISSUE TITLE
Useless documentation

### ISSUE THREAD

**Issue by ClintBritt** [MicrosoftDocs/winrt-api#1308]
You don't even give a good clue how to use the IProvider parameter. This is a completely useless document page that tells you nothing more then what the metadata dump in VS gives you. Useless

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc5120ee-2ce4-715c-84a4-5a994dcfc8bf
* Version Independent ID: 7150f89e-c8a1-51c7-42c7-0927c1bdb478
* Content: [GpioController.GetControllersAsync(IGpioProvider) Method (Windows.Devices.Gpio) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiocontroller.getcontrollersasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiocontroller.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.gpio.gpiocontroller.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @ClintBritt. Thanks for filing this issue.

I've updated the topic to provide more info/clarification here. I'll leave the issue open for a while.

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Comment by ClintBritt** [comment]
Sorry for not responding. I have gotten use to venting and not getting a response. Thanks for taking care of this and thanks for understanding and responding to a clearly not well made email of mine. You have helped change my attitude for future communications. Good work. And yes, the documentation has been updated excellently. Thanks very much.
