### ISSUE TITLE
Is it possible to decapsulate the received packets for VpnNativeProfile? 

### ISSUE THREAD

**Issue by rsuwp** [MicrosoftDocs/winrt-api#1309]
As per my explorations so far it looks like, the packets can be captured only for the PluginProfile. Can we capture the received packets for native vpn profile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d6961af-24b7-6752-acfb-996a9d64b928
* Version Independent ID: 4817760c-452f-38be-dd6e-c580f4d1819f
* Content: [VpnNativeProfile Class (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnnativeprofile#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnnativeprofile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnnativeprofile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @rsuwp. Thanks for filing this issue.

I've reached out to the feature team for more info/clarification here, and in case we need to add more content.

Thanks again!
Steve

**Comment by rsuwp** [comment]
Any updates on this? Have another related question.
Will the background task be triggered for VpnNativeProfile.

**Comment by PeterSmithRedmond** [comment]
The Native profile doesn't trigger the background task and you can't capture packets using it. when you use the Native profile, it's roughly the same as if you had simply used the "Add a VPN connect" dialog box: you can fill in the server, and sign-in information, etc, and then Windows handles the VPN from there.

**Comment by stevewhims** [comment]
Thanks for the info, Peter. I've published an update to the topic, with this extra info added.

I'll go ahead and close the issue now.

Thanks!
Steve
