### ISSUE TITLE
Taskbar color

### ISSUE THREAD

**Issue by fenhl** [MicrosoftDocs/winrt-api#1310]
It would be useful if this page documented which of these is used by the taskbar, so that I can use a white or black notification area icon accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b6dd6e-725b-81c9-98a2-c2d5b714fb39
* Version Independent ID: aaf36ca8-3ac5-57b9-25de-467f513cb219
* Content: [UIColorType Enum (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uicolortype#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.uicolortype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.uicolortype.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response.
This enum and related APIs are used to get the user's system accent color and the variations of it. Whether that color is applied to the taskbar is a user option in the color settings, so there is no guarantee that the color returned is actually applied to the taskbar.

Whether the app icon in the notification area is light or dark depends on the system theme (light/dark), not the accent color. To have your app choose the appropriate icon, there is a setting in the appxmanifest file. In the Visual Studio app manifest editor, choose the Visual Assets tab, then check the "Apply color conversion for Windows Light Theme" option.

For more info about app icons, see [App icons and logos](https://docs.microsoft.com/windows/uwp/design/style/app-icons-and-logos) and [Shell light theme and unplated resources](https://docs.microsoft.com/windows/uwp/app-resources/tailor-resources-lang-scale-contrast#shell-light-theme-and-unplated-resources).
