### ISSUE TITLE
Provide more info on what impact this has on consumers of APIs that use it

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1312]
There are not many details here on how an Experimental API presents it self to a developer consuming the library that has exposed an Experimental attributed class.

Does it show up as a compiler warning like `Obsolete`? Does it have any indication in the XAML Editor with squiggles as a warning?

More details on the end-result of adding this attribute would be great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0ef05c4-8541-628b-7235-4127601deac8
* Version Independent ID: fa697368-1da5-67be-a793-a720f819c09f
* Content: [ExperimentalAttribute Class (Windows.Foundation.Metadata) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Metadata.ExperimentalAttribute)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.experimentalattribute.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.experimentalattribute.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for this issue. The answer you're looking for is [here](https://docs.microsoft.com/windows/uwp/whats-new/experimental-apis). I've also added a link to this page in the see also section of the ExperimentalAttribute class page so future experimenters will have a little more guidance.
