### ISSUE TITLE
Which Alphabet?

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1315]
It appears there can be different Base64 "alphabets" depending upon the transport protocol to be used. As such, it would be advisable to document which alphabet is in use and which standard (if any) it matches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf7e483-b740-8572-f7d0-57d7a09ad79a
* Version Independent ID: 58a76596-0e63-5347-1fd3-bedd3f6e5348
* Content: [CryptographicBuffer.EncodeToBase64String(IBuffer) Method (Windows.Security.Cryptography) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.cryptographicbuffer.encodetobase64string#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @kburgoyne , thanks for submitting your feedback. Appreciate you pointing this out. I'll pursue this suggestion and add in a work item to get it fixed. Look back for this thread for updates in the future once this is completed.

**Comment by krunch3r76** [comment]
This alphabet conforms to the IETF's requirements set forth in RFC4648, which acknowledges implementation variants. I personally am not surprised it doesn't make this explicit as I don't see any other standard definition and this implementation is complete with padding. You can also observe this yourself:
```
    const size_t bufferLength = 48;
    assert(bufferLength <= 48); // sequentially pack up to 64 6-bit values, from 0 to 63
    uint8_t buffer[bufferLength] = { 0 };   
    uint8_t* bufferBytePointer = &buffer[0];
    uint8_t shiftCount = 0, eightDivShiftCount=0;
    for (int quartile = 0; quartile < bufferLength*8/6; ++quartile) {
        for (int bitPosition = 5; bitPosition >= 0; --bitPosition) {
            (*bufferBytePointer) |= ((quartile >> bitPosition) & 1);
            eightDivShiftCount = ((++shiftCount % 8) == 0);
            bufferBytePointer = eightDivShiftCount ? bufferBytePointer + 1 : bufferBytePointer;
            (*bufferBytePointer) = !eightDivShiftCount ? (*bufferBytePointer) << 1 : (*bufferBytePointer);
        }
    }

    IOutputStream outputStream;
    auto dataWriter = DataWriter(outputStream);
    dataWriter.WriteBytes(buffer);
    auto bufferObj = dataWriter.DetachBuffer();
    auto s = CryptographicBuffer::EncodeToBase64String(bufferObj);
    std::wcout << s.c_str() << std::endl;
````
Nevertheless, a reference to the RFC4648 October 2006 publication at least in the headers wouldn't hurt.

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
