### ISSUE TITLE
Which Alphabet?

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1316]
It appears there can be different Base64 "alphabets" depending upon the transport protocol to be used. As such, it would be advisable to document which alphabet is in use and which standard (if any) it matches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d685c7f-67a9-6293-d1c8-d01080d72762
* Version Independent ID: 77fc3c98-d0a6-f508-215e-f16ae834ff19
* Content: [CryptographicBuffer.DecodeFromBase64String(String) Method (Windows.Security.Cryptography) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.cryptographicbuffer.decodefrombase64string)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Closing this thread as there is a duplicate one opened.
