### ISSUE TITLE
XAML code is invalid

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/winrt-api#1319]
ShowError="bool" should either be ShowError="True" or "False".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1ee8cca-c633-aa59-9602-e6b4a6e5e0e8
* Version Independent ID: 45391825-e86e-a791-da06-9b815e12fb39
* Content: [ProgressBar.ShowError Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.progressbar.showerror)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.progressbar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.progressbar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
I think the pattern for these sections is to show a declaration rather than example code, so it shows the type of the value. For example, [FrameworkElement.Width](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.FrameworkElement.Width) is a double type, so this section shows

```xaml
<frameworkElement MinWidth="double"/>
```
But it's confusing because in some cases it is example code, like [FrameworkElement.Style](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.FrameworkElement.Style):

```xaml
<frameworkElement Style="{StaticResource styleResourceKey}"/>
```

**Comment by jevansaks** [comment]
This is a systemic problem. I think the docs team should advise on how to fix.

**Comment by mijacobs** [comment]
There'a a few issues here. One seems to be using a placeholder value, "bool", in place of a literal value or a set of values.  Is it not clear that "bool" is a placeholder? The properties values section that follows on that page describes the possible bool values, True and False. 

We also have an optional xaml values section that will appear when the system moves to the new rendering engine. The xaml values is used when the possible values for a xaml attribute are more complex, like in the case of the Path shape.

**Comment by MikeHillberg** [comment]
Is the intent that this section be sometimes placeholder, sometimes example, sometimes both? Maybe indicate the placeholder case, for example italicize.

**Comment by jwmsft** [comment]
The intent is that it is a placeholder. Examples would be in the Examples section, not in the Syntax section. Italicizing is a good idea, but we can't do that because it's in a markdown code block.

**Comment by MikeHillberg** [comment]
Maybe brackets? I've found these sections confusing in the past too.

I see where people have made this section into example code too, like [FrameworkElement.Style](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.FrameworkElement.Style):
```
<frameworkElement Style="{StaticResource styleResourceKey}"/>
```
(Also, is there a reason why the "f" in <FrameworkElement> is lower case?)

**Comment by jwmsft** [comment]
We can test some different options like brackets and see if anything works well.

The lowercase "f" is to indicate that you'd be setting this property on something that inherits from FrameworkElement, but you would not be putting <FrameworkElement .../> in your XAML. 

The FrameworkElement.Style example you give isn't intended to look like a copy-and-paste example, but there's important contextual information that is currently not shown (even though it still exists in the markdown). We're working to fix this. This [archived version of the doc](https://web.archive.org/web/20140918030840/http://msdn.microsoft.com/en-us/library/windows/Apps/windows.ui.xaml.frameworkelement.style.aspx) shows what it's meant to look like. Notice the 'Syntax' header and the 'XAML Values' section.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response.

As this issue is a result of auto-generated global syntax from our publishing system, we've created an internal work item to triage and address across all WinRT API docs.
