### ISSUE TITLE
UWP Set ContainerEncodingProperties.Subtype to "MPEG2TS" causes exception (MPEG-DASH Video Live Stream)

### ISSUE THREAD

**Issue by SaschaIoT** [MicrosoftDocs/winrt-api#1323]
[ContainerEncodingProperties.Subtype](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.containerencodingproperties.subtype#Windows_Media_MediaProperties_ContainerEncodingProperties_Subtype) supports "MPEG2TS" video container.

Windows 10 and UWP Apps supports H.264 encoding with "MPEG2TS" video container. [Supported codecs - UWP](https://docs.microsoft.com/en-US/windows/uwp/audio-video-camera/supported-codecs)

Set ContainerEncodingProperties Subtype to "MPEG2TS" causes exception "Value does not fall within the expected range".

Set ContainerEncodingProperties Subtype directly to "MPEG2TS"-Guid ("e06d8023-db46-11cf-b4d1-00805f6cbbea") causes exception "No suitable transform was found to encode or decode the content".

Used versions:
UWP target SDK: "Windows 10, version 1903 (10; Build 18362)"
Windows 10: Version 1909 (Build 18363.476)

Without "MPEG2TS" encoding it is not possible to create a real MPEG-DASH video live stream from webcam with Windows IoT Core. My workaround [Video Live Stream like MJPEG](https://www.hackster.io/sascha/browser-webcam-live-stream-with-windows-iot-core-raspberry-3-1dc38b).

```csharp
var mediaCapture = new MediaCapture();
await mediaCapture.InitializeAsync();

var mediaEncodingProfile = MediaEncodingProfile.CreateMp4(VideoEncodingQuality.HD1080p);

var containerEncodingProperties = new ContainerEncodingProperties();
containerEncodingProperties.Subtype = "MPEG2TS";
// Throws System.ArgumentException: 'Value does not fall within the expected range.'

// containerEncodingProperties.Subtype = "e06d8023-db46-11cf-b4d1-00805f6cbbea";
// Throws System.Runtime.InteropServices.COMException: 'No suitable transform was found to encode or decode the content'

mediaEncodingProfile.Container = containerEncodingProperties;

var stream = new MemoryStream().AsRandomAccessStream();
await mediaCapture.StartRecordToStreamAsync(mediaEncodingProfile, stream);
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e9a35be-7a90-f36b-4278-d4d34a306319
* Version Independent ID: 5d07139d-4205-38fe-5195-026564b06816
* Content: [ContainerEncodingProperties.Subtype Property (Windows.Media.MediaProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.containerencodingproperties.subtype#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.containerencodingproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.containerencodingproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by johnsim** [comment]
could you elaborate on this statement: "Without "MPEG2TS" encoding it is not possible to create a real MPEG-DASH video live stream from webcam with Windows IoT Core." Most of the industry is using fragmented MP4 with MPEG-DASH, not MPEG2TS. Is there no way to use fMP4 in your application (which, btw, is pretty cool.)

**Comment by SaschaIoT** [comment]
@johnsim thanks for your comment, I'am not a video encoding expert. Yes it would be great, if it is possible to create fragmented MP4 within UWP apps, but I don't know how.

I use "H264" as video encoding (created from MediaEncodingProfile.CreateMp4). The default container encoding is "MPEG4". But this not creates fragmented video file. My idea was to use "MPEG2TS" as container encoding because this creates fragemented video. I tried also to use "MPEG4" as video encoding and "MPEG2TS" as container encoding, but is not working.

I builded a lot of robots with Windows IoT Core. In Windows IoT Core (not Enterprise versions) only UWP apps working. In the UWP app I implemented a HTTP-server (with StreamSocketListener) wich should provide fragmented video files. In the browser there is an MPEG-DASH player (like dash.js) who requesting the video fragments from the HTTP-server in the UWP app.

My target is to create a real video live stream from the webcam (to a browser) in an UWP app, that is running in Windows IoT Core.

Is there a way to create fMP4 within an UWP app?

**Comment by drewbatgit** [comment]
I have updated the [ContainerEncodingProperties.Subtype Property](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.containerencodingproperties.subtype#Windows_Media_MediaProperties_ContainerEncodingProperties_Subtype) page to reflect the correct list of supported subtypes.

**Comment by SaschaIoT** [comment]
@drewbatgit thanks for updating. ASF is the only supported container encoding that creates fragmented/streamable video files. But ASF is not streamable in any browser. Would be great if Microsoft adds "MPEG2TS" as container encoding, maybe with an argument for the duration of the video fragments.

**Comment by SaschaIoT** [comment]
The reason to make a real video live stream (MPEG-DASH) from webcam in an UWP app is, that only UWP apps runable on "Windows IoT Core".

Microsoft plans to create "Windows IoT Enterprise LTSC 2021" in 2021, wich contains the best of "Windows IoT Core" and "Windows IoT Enterprise". With "Windows IoT Enterprise LTSC 2021" it should be possible to make a real video live stream with audio (MPEG-DASH) from a webcam on small devices.

[Channel 9 video: Windows for IoT - A Roadmap update](https://channel9.msdn.com/Shows/Internet-of-Things-Show/Windows-for-IoT-A-Roadmap-update)
