### ISSUE TITLE
JavaScript sample instead of C# one

### ISSUE THREAD

**Issue by ad1Dima** [MicrosoftDocs/winrt-api#1324]
There is no C# sample for MediaProtectionManager 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19a9bf1c-92e5-fe47-2e79-da2615fe3490
* Version Independent ID: bdd21506-23d9-7c83-0fff-3397ffb1bb16
* Content: [MediaProtectionManager Class (Windows.Media.Protection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.protection.mediaprotectionmanager?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Media.Protection.MediaProtectionManager)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.protection.mediaprotectionmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.protection.mediaprotectionmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
A C# code snippet has been added to this article. Thank you for your feedback on the documentation!
