### ISSUE TITLE
HoloLens Gen 1 vs Gen 2 Support

### ISSUE THREAD

**Issue by AMollis** [MicrosoftDocs/winrt-api#1325]
This page (https://docs.microsoft.com/en-us/windows/mixed-reality/hands-and-motion-controllers-in-directx) mentions that these APIs should only be used with HoloLens Gen 1.   This page should be updated to reflect this as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786ece1c-3804-eda4-e7f5-cac06929590d
* Version Independent ID: 0ff895f1-c0ce-80e3-2fb9-18875a4f4e2e
* Content: [SpatialGestureRecognizer Class (Windows.UI.Input.Spatial) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Input.Spatial.SpatialGestureRecognizer?redirectedfrom=MSDN)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.spatial.spatialgesturerecognizer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.spatial.spatialgesturerecognizer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@AMollis - can you copy and paste the text you're quoting from the specified topic? Thanks!

**Comment by AMollis** [comment]
This is the line I'm referring to.  It indicates that this API should be used for the GGV pointer (i.e. gaze-and-commit input model), such as that used on HoloLens Gen 1.  It would be good to have this comment on this page as well (https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Input.Spatial.SpatialGestureRecognizer?redirectedfrom=MSDN), as there has been some confusion as to which APIs devs should use for HoloLens gen 2 hand gestures.

> For applications using the gaze-and-commit input model, particularly on HoloLens (first gen), the Spatial Input API provides an optional SpatialGestureRecognizer that can be used to to enable composite gestures built on top of the 'select' event.

**Comment by Karl-Bridge-Microsoft** [comment]
Ah, ok. Your OP stated "should only be used with", which is not what the doc states. Thanks for clarifying! I'll check with the feature team to see if the original needs to be revised and then added to the topic you suggest.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

I just pushed an update to this API topic that includes the (slightly revised) paragraph from the overview topic.
