### ISSUE TITLE
Main description is grammatically incorrect

### ISSUE THREAD

**Issue by SamPavezaMS** [MicrosoftDocs/winrt-api#1326]
"Represents an object that enables integrate with the system media transport controls and support for media commands."  Should either be "an object that enables integration with the system..." or "an object that integrates with the system..."  I like the latter because it seems unambiguous that the object supports the interface, but I will defer to the owner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfb1b206-14aa-abe0-67d3-5091ae486866
* Version Independent ID: f1cc0a50-2c54-581f-e4c3-7b0200828f7d
* Content: [SystemMediaTransportControls Class (Windows.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrols)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.systemmediatransportcontrols.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.systemmediatransportcontrols.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for identifying this typo. The phrase has been updated to "Represents an object that enables integration with the system media transport controls"
