### ISSUE TITLE
Document DataPackage.ShareCanceled API

### ISSUE THREAD

**Issue by saschanaz** [MicrosoftDocs/winrt-api#1327]
There is a documentation for [DataPackage.ShareCompleted](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackage.sharecompleted) but no official documentation for new [ShareCanceled](https://blogs.windows.com/windowsdeveloper/2019/08/13/windows-10-sdk-preview-build-18956-available-now/#ytKtWB3BLPFI2YVp.97) API yet. A documentation will be much helpful.

**Comment by saschanaz** [comment]
c06fb61efbbdc1828c1eb2f12de2c8002291d65b added the file but it doesn't appear in the site yet 🤔

**Comment by stevewhims** [comment]
Hi, @saschanaz, and thanks for filing this issue. This API is currently available only in SDK Preview Builds. The live documentation on docs.microsoft.com typically only documents the generally-available (GA) API surface. When pre-release APIs (such as this one) become generally-available, then the topic will appear on the live site.

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close the issue. You can still reply to a closed issue and/or re-open it, if necessary.

Thanks!
Steve

**Comment by saschanaz** [comment]
@stevewhims Hi Steve, it seems this API is available on build 19041.207 which will be GA soon, could you confirm?

**Comment by saschanaz** [comment]
I think this should be reopened as I found that SDK 10.0.19041.0 has ShareCanceled. @stevewhims I can't reopen this, could you do instead?

**Comment by stevewhims** [comment]
Hi, @saschanaz. Yes, this API is now generally available (GA), and it is documented here: https://docs.microsoft.com/uwp/api/windows.applicationmodel.datatransfer.datapackage.sharecanceled.

I've reopened the issue, but please let me know if there actually is still a problem.

Thanks!
Steve

**Comment by saschanaz** [comment]
Oh I missed it, thanks!
