### ISSUE TITLE
Path to Windows Kits is incorrect

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/winrt-api#1328]
In the first paragraph of https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.AppBar#control-style-and-template section, the path to the SDK is incorrectly suggesting it's the 64 bit programs folder.

"For design purposes, generic.xaml is available in the (Program Files)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP\ &lt;SDK version&gt;\Generic folder from a Windows Software Development Kit (SDK) installation. "

It is actually in the 32 bit folder: 

Program Files (x86)\Windows Kits

NOT
(Program Files)\Windows Kits\10\

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e19cf53-1136-11fc-ad60-ac54746a5e16
* Version Independent ID: eadefb56-bfcf-0027-bc8a-9966efda834f
* Content: [AppBar Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.AppBar)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.appbar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.appbar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@LanceMcCarthy I created a PR to fix this, but in the future: you can too! Instead of reporting the bug just go ahead and click "Edit" on the doc page and submit the proposal yourself.

**Comment by LanceMcCarthy** [comment]
I usually see this button (have opened several such fixes in the past), but it wasn't visible here. Not sure why, do I need to be signed in with a specific account (i.e. my MVP account?).

**Comment by LanceMcCarthy** [comment]
OH derp. You mean `Edit` here on GitHub :)

**Comment by jevansaks** [comment]
The docs page has an "Edit" button, e.g. [this page](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.AppBar) you reported has this near the top:

![image](https://user-images.githubusercontent.com/20667023/69274462-3ffd1180-0b8f-11ea-9357-9ce7ac1898a7.png)

You're right that many pages don't have it and that's usually because the page isn't backed by GitHub content. You shouldn't need to be signed in to docs to see the button vs not.
