### ISSUE TITLE
Broken link to CoreInputViewOcclusion

### ISSUE THREAD

**Issue by Mathos1432** [MicrosoftDocs/winrt-api#1332]
There's a link to CoreInputViewOcclusion on the page, when clicked on, it redirects to https://docs.microsoft.com/en-us/uwp/api/coreoccludinginputview instead of https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.core.coreinputviewocclusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beac5528-f779-0b41-318d-09e5bd70c09a
* Version Independent ID: 340083fe-0de0-7831-06de-6f53f0db23f5
* Content: [CoreInputViewOcclusionKind Enum (Windows.UI.ViewManagement.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.core.coreinputviewocclusionkind#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.core.coreinputviewocclusionkind.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.core.coreinputviewocclusionkind.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. I've submitted a fix for the link.

**Comment by Mathos1432** [comment]
Thank you! 😊
