### ISSUE TITLE
Where are cookies stored on the file system for desktop Win32 processes?

### ISSUE THREAD

**Issue by andy-schmidt** [MicrosoftDocs/winrt-api#1333]
The CookieManage used by Windows.Web.Http.Filters.HttpBaseProtocolFilter will store cookie with an expiration date beyond the lifetime of an individual process. Where are these cookies stored for traditional Win32 desktop processes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 487a5fb5-ce5a-0b2c-7461-fc72e527fb2b
* Version Independent ID: 3b3b2dd6-ab31-84ea-9789-d500a71d48bb
* Content: [HttpBaseProtocolFilter.CookieManager Property (Windows.Web.Http.Filters) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.httpbaseprotocolfilter.cookiemanager#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.filters.httpbaseprotocolfilter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.filters.httpbaseprotocolfilter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @andy-schmidt, thanks for filing this issue. I've reached out to the feature team for help here.
~Steve

**Comment by stevewhims** [comment]
UPDATE: I've pinged the feature team again.

-Steve

**Comment by stevewhims** [comment]
I sent another ping to the feature team.

**Comment by stevewhims** [comment]
Hi, @andy-schmidt, I have some info. So, there are security and privacy benefits for the Windows ecosystem in being able to be flexible with the location and format of the cookies storage for HttpClient. Consequently, that location and format is an implementation detail that doesn't necessarily remain fixed over time. It's for these reasons that we don't document these details.

I'm sorry it took me a long time to get back to you on this question, and that we couldn't provide the exact info you were looking for. I'll go ahead and close the issue now.

-Steve
