### ISSUE TITLE
Reference for ms-appdata:/// and ms-appx-web:/// needed.

### ISSUE THREAD

**Issue by KeiBontakun** [MicrosoftDocs/winrt-api#1334]
I saw some articles I have to add ms-appdata or ms-appx-web to uri when showing local resources. I want description about that or link to reference.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a70b1220-2661-69bf-6bb8-706bc919a19e
* Version Independent ID: f27af05d-12f7-1f0a-9554-17cf3c675f34
* Content: [IWebViewControl.Source Property (Windows.Web.UI) - Windows UWP applications](https://docs.microsoft.com/ja-jp/uwp/api/windows.web.ui.iwebviewcontrol.source#Windows_Web_UI_IWebViewControl_Source)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.iwebviewcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.iwebviewcontrol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. I've added a link to [URI schemes](https://docs.microsoft.com/windows/uwp/app-resources/uri-schemes) to this page for more information.

The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For potentially time-sensitive questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question.
