### ISSUE TITLE
Does this class work with traditional Windows desktop apps?

### ISSUE THREAD

**Issue by andy-schmidt** [MicrosoftDocs/winrt-api#1335]
This class, and the others in Windows::Data::Xml::Dom, work in my Visual Studio C++/WinRT desktop console app -- this is not a UWP app so it lacks a package identity. However, there is no DualApiPartitionAttribute listed. Are these classes designed to work with traditional desktop apps? I am assuming they are Windows Runtime IInspectable wrappers around MSXML COM interfaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbc460d-b88e-0261-5354-4eaa00aa9150
* Version Independent ID: 28bc0c28-4285-2156-6479-0fce0c811c15
* Content: [XmlDocument Class (Windows.Data.Xml.Dom) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.xml.dom.xmldocument)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.xml.dom.xmldocument.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.xml.dom.xmldocument.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. 

This and other Windows.Data.Xml.Dom classes are in our [list of WinRT classes that are supported only in apps that have package identity](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#apis-supported-only-in-apps-with-package-identity). Although it's possible that these may work in certain scenarios without package identity, this isn't supported.

I hope this helps.
