### ISSUE TITLE
Need to clarify about window focus

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/winrt-api#1340]
I think line:
&gt;UWP apps cannot receive input from an Xbox One Controller while the app is not in focus.

should be changed to something like:

&gt;Windows.Gaming.Input API cannot be used for apps without window (UWP and Win32). Also you cannot receive actual input from controllers while app window is not in focus.

See Chuck Walbourn answer here: https://stackoverflow.com/a/57794492/1795050

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c382eaa-aecb-0f26-ab0e-e752c9a36713
* Version Independent ID: 7b0c1235-3109-5b93-33c7-203426d2fad6
* Content: [Windows.Gaming.Input Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @DJm00n. The topic has been updated.
