### ISSUE TITLE
sample links go to sample homepage, not specific samples

### ISSUE THREAD

**Issue by miniksa** [MicrosoftDocs/winrt-api#1341]
`Reading and writing data sample` and `StreamSocket` sample both go to the samples homepage through a redirect. This should be fixed to go to the specific sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a0f782-9e01-d3b9-bcab-9abb054f0365
* Version Independent ID: cf43b5a9-2f0b-c807-ac6b-065cdc493840
* Content: [DataWriter Class (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datawriter#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datawriter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datawriter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @miniksa , thanks for bringing this to our attention. I went ahead and fixed the links; the changes should be live soon.
