### ISSUE TITLE
How to set traffic filters in TrafficFilterList?

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1344]
Currently, i do not see a way to set it into the TrafficFilterList member above as it is "get" only variable. How do we set the filter rules in it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b75cc71-f1a4-d870-90bf-eb914716f5a1
* Version Independent ID: b9f3d536-55c3-73cf-74bb-2af4bdf5ef89
* Content: [VpnTrafficFilterAssignment Class (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpntrafficfilterassignment)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpntrafficfilterassignment.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpntrafficfilterassignment.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @defaultshr, try something like this:

```csharp
var myVpnTrafficFilterAssignment = new VpnTrafficFilterAssignment();
myVpnTrafficFilterAssignment.TrafficFilterList.Add(...);
```

It's true that **TrafficFilterList** doesn't have a setter. But that doesn't prevent you from doing the above. It only prevents you from doing this:

```csharp
myVpnTrafficFilterAssignment.TrafficFilterList = <a collection object>;
```

-Steve

**Comment by defaultshr** [comment]
Thank you very much @stevewhims for your response. I shall try this. Somehow i was ignorant on this method you've suggested.

**Comment by stevewhims** [comment]
I'll go ahead and close the issue now.

Thanks!
Steve
