### ISSUE TITLE
"out" parameters aren't showing the "out"-ness

### ISSUE THREAD

**Issue by simeoncran** [MicrosoftDocs/winrt-api#1346]
For an example, see: https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionpropertyset.trygetcolor

The C# signature says: public CompositionGetValueStatus TryGetColor(String propertyName, Color value)
The actual signature should be: public CompositionGetValueStatus TryGetColor(String propertyName, **out** Color value)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aa1809e-236e-260b-7b4f-db9ad0a023d4
* Version Independent ID: 1fdb8447-eea0-7b3c-db14-48c853d9a7dd
* Content: [CompositionPropertySet.TryGetColor(String, Color) Method (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionpropertyset.trygetcolor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositionpropertyset.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositionpropertyset.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This issue has been fixed.
