### ISSUE TITLE
Unable to play a currently downloading media file through DownloadOperation

### ISSUE THREAD

**Issue by harvinders** [MicrosoftDocs/winrt-api#1348]
I have a background task which pre-fetch a media file using `DownloadOperation.StartAsync()`. If now I create a `MediaSource` using the same downloadOperation and set it to `MediaPlayer` using `MediaPlaybackItem`, `MediaFailed` event is raised by the mediaPlayer.

  | Name | Value | Type
-- | -- | -- | --
◢ | args | {Windows.Media.Playback.MediaPlayerFailedEventArgs} | Windows.Media.Playback.MediaPlayerFailedEventArgs
  | Error | SourceNotSupported | Windows.Media.Playback.MediaPlayerError
  | ErrorMessage | "" | string
  | ◢ ExtendedErrorCode | {"A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)"} | System.Exception {System.InvalidOperationException}
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2147483634 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "A method was called at an unexpected time. (Exception from HRESULT: 0x8000000E)" | string
  | Source | null | string
  | StackTrace | null | string
  | TargetSite | null | System.Reflection.MethodBase
  | ▶ Static members |   |  
  | ▶ Non-Public members |   |  

I suppose somewhere another call is made to the StartAsync() 

I am on Windows 10 1803.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ad19077-8730-71ab-d1b9-edd45a822c74
* Version Independent ID: 88971d10-a637-9c1a-8499-47a1de7a8f3a
* Content: [MediaSource.CreateFromDownloadOperation(DownloadOperation) Method (Windows.Media.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediasource.createfromdownloadoperation#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediasource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediasource.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by harvinders** [comment]
I got the answer [here](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-playback-with-mediasource#create-a-mediasource-from-a-downloadoperation). It would be great if the `CreateFromDownloadOperation` page include this information too.

**Comment by drewbatgit** [comment]
Thank you for providing feedback on the documentation. I'm glad you found the answer you were looking for. In general, we try not to duplicate the same content in multiple places because it becomes easy for the guidance to get out of sync. I was going to add a link to the topic that helped you from the reference page, but it appears that the page is already linked.
