### ISSUE TITLE
If zero groups are returned

### ISSUE THREAD

**Issue by dgough** [MicrosoftDocs/winrt-api#1354]
If MediaFrameSourceGroup.FindAllAsync() returns zero groups then make sure you request the Webcam capability in your Package.appxmanifest file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcc6c3a0-84f4-2c8d-cbb4-cfc7dd5032ff
* Version Independent ID: 3954dd9a-3753-c8db-3caa-c8e25e2a4cab
* Content: [MediaFrameSourceGroup.FindAllAsync Method (Windows.Media.Capture.Frames) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframesourcegroup.FindAllAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.frames.mediaframesourcegroup.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.frames.mediaframesourcegroup.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by hkhmsft** [comment]
Hi @dgough , thanks for the additional information. If I understand correctly, you'd like for this to be a remark added to this Method?

**Comment by dgough** [comment]
Yes, I think it can save people some time and frustration if the method description mentioned this. It took me awhile to figure out what I was missing when I was trying to use this method.

**Comment by hkhmsft** [comment]
Excellent, I will go ahead and append this to the reference page.

**Comment by hkhmsft** [comment]
The remark has been added and should appear live soon. Thanks, @dgough .
