### ISSUE TITLE
Should show an example of modifying an Attached Property

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1355]
There's no example here about how to reference an attached property that's part of a named object for a setter.

Like if you wanted to update a Grid Row on the element with the name 'MyGrid' it'd be `Target="MyGrid.(Grid.Row)"`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb748e04-6d4c-8626-d3c3-086e5b3aef79
* Version Independent ID: de8185a7-8b9b-5e28-c8d0-65dc0bccd270
* Content: [Setter Class (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.setter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.setter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.setter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the suggestion. The doc has been updated with an example of setting an attached property.
