### ISSUE TITLE
What is the format of Data?

### ISSUE THREAD

**Issue by Holo-Krzysztof** [MicrosoftDocs/winrt-api#1356]
Is there any documentation on how to use the data from this API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dee94bce-8754-9c3d-fb0b-9884910b0822
* Version Independent ID: eaa0d8ec-da85-52e9-353e-8a763ea666a5
* Content: [PerceptionMonitorDataReceivedEventArgs.Data Property (Windows.Perception.Automation.Monitoring) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.perception.automation.monitoring.perceptionmonitordatareceivedeventargs.data#Windows_Perception_Automation_Monitoring_PerceptionMonitorDataReceivedEventArgs_Data)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.automation.monitoring.perceptionmonitordatareceivedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.automation.monitoring.perceptionmonitordatareceivedeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Unfortunately, there is no documentation for this API beyond what you seem to have already found. The classes in this namespace are used in MR and HoloLens apps. I suggest reviewing the [HoloLens documentation](https://docs.microsoft.com/hololens/) for more information.
