### ISSUE TITLE
Sample code link is dead.

### ISSUE THREAD

**Issue by aruproy14** [MicrosoftDocs/winrt-api#1357]
In the following section, the link to the Windows Sample Gallery source code is dead:

    Examples
    The following example demonstrates how to configure and begin a basic download operation, and is based on the Background Transfer sample offered in the Windows Sample Gallery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fddc080-8c1c-643a-6c78-118df75048d5
* Version Independent ID: b856ffaa-2f52-c010-5202-a4fd752c0db3
* Content: [BackgroundDownloader Class (Windows.Networking.BackgroundTransfer) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgrounddownloader#examples)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloader.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @aruproy14, thanks for filing this issue. The correct url to this sample is https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackgroundTransfer. I'll close this issue when my updates have appeared on the live site.

-Steve

**Comment by stevewhims** [comment]
The topic is updated now.
