### ISSUE TITLE
HoloLens 2

### ISSUE THREAD

**Issue by philomathikus** [MicrosoftDocs/winrt-api#1358]
Cameron tried to use this API (https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6167) but it seems to not be implemented for HoloLens 2. Do you know when it might become available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12bbca17-9059-231d-bcfa-8f1aeeb5f968
* Version Independent ID: 58b3c13c-6413-aa21-98ed-d09703378c38
* Content: [InputPane.OccludedRect Property (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.inputpane.occludedrect#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.inputpane.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.inputpane.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you believe that the documentation in this topic is incorrect, or that info needed to succeed with a common scenario is missing.

For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question.
