### ISSUE TITLE
Hour range

### ISSUE THREAD

**Issue by sftblw** [MicrosoftDocs/winrt-api#1361]
When I get hour over 13, this API returns 1 and period is 2 (PM). I think range of Hour property is worth to be mentioned in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dd7ab3-7bfd-d97b-f637-deb850e17e60
* Version Independent ID: aa6e9886-6fe3-e297-ea43-d73e0e842fcf
* Content: [Calendar.Hour Property (Windows.Globalization) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.calendar.hour#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.calendar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.calendar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
The value returned by the Hour property is dependent on your Preferred language setting. If you are in a 24 hour clock region, one hour over 12 returns 13. I've added some detail to the topic.
