### ISSUE TITLE
This doesn't link to the flyoutshowmode enum

### ISSUE THREAD

**Issue by EriWong** [MicrosoftDocs/winrt-api#1363]
This page should link to the flyoutshowmode enum documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b3d474-5b2a-a7c5-b752-db08f2f99509
* Version Independent ID: d549e05b-29bd-98a9-97c8-2f188a6d08de
* Content: [FlyoutShowOptions.ShowMode Property (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutshowoptions.showmode#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutshowoptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutshowoptions.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This issue has been fixed.
