### ISSUE TITLE
The method does not return an IReadOnlyList

### ISSUE THREAD

**Issue by ptaffet** [MicrosoftDocs/winrt-api#1364]
The remarks for this method say it returns an IReadOnlyList, but it seems to only return a single ChatMessageStore object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8195dec-60bd-da86-8697-c9245b23c9e2
* Version Independent ID: 3bc73dea-9a00-5095-bc93-deab89c72e25
* Content: [ChatMessageManager.RequestStoreAsync Method (Windows.ApplicationModel.Chat) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.chat.chatmessagemanager.requeststoreasync#Windows_ApplicationModel_Chat_ChatMessageManager_RequestStoreAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.chat.chatmessagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.chat.chatmessagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for pointing this out @ptaffet . I went ahead and made changes to the remark section and it should be live soon.
