### ISSUE TITLE
Broken link to method overload

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1365]
This page represents both overloads of the CreateCopyFromSurfaceAsync method. In the section for the first overload there's a link to the second that doesn't work: [CreateCopyFromSurfaceAsync(IDirect3DSurface, BitmapAlphaMode)](https://docs.microsoft.com/en-us/uwp/api/softwarebitmap_createcopyfromsurfaceasync_876166343). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9e2556b-7368-562c-db41-9392788dfaec
* Version Independent ID: 78c5bdb4-19d0-e93a-9a6d-f728209e29ad
* Content: [SoftwareBitmap.CreateCopyFromSurfaceAsync Method (Windows.Graphics.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Imaging.SoftwareBitmap.CreateCopyFromSurfaceAsync?source=docs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for the feedback. This link has been fixed.
