### ISSUE TITLE
How is failure code returned from the void method?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1367]
The Remarks section states that method can return "failure code", but its return type is void. If it is meant that it will throw exceptions, the documentation should probably state that directly, rather than have API users guessing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dea899e9-6fe7-a482-1d81-372d394599d9
* Version Independent ID: 48f7ccfa-84a8-bec4-a718-3a3e1add6281
* Content: [ToastNotifier.AddToSchedule(ScheduledToastNotification) Method (Windows.UI.Notifications) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotifier.addtoschedule)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotifier.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotifier.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for opening this issue. I've updated the language to be more clear about how errors are raised from this method. IT will be published in the next docs publish.
