### ISSUE TITLE
Details about supported depth buffer formats

### ISSUE THREAD

**Issue by caseymeekhof** [MicrosoftDocs/winrt-api#1369]
It would be great to add more details about the types of depth buffers that are supported and the flags they need to be created with.  It would also be good to provide some sample code for how to convert from a ID3D11Texture2D interface to a IDirect3DSurface interface.  Right now the C++ Mixed Reality App templates provide a good working example but it would be helpful to get more information onto this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37813d14-1197-bf87-90b5-cef9b79c33fb
* Version Independent ID: 6f755e6a-c790-cf14-5b8b-85924994574a
* Content: [HolographicCameraRenderingParameters.CommitDirect3D11DepthBuffer(IDirect3DSurface) Method (Windows.Graphics.Holographic) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographiccamerarenderingparameters.commitdirect3d11depthbuffer#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographiccamerarenderingparameters.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographiccamerarenderingparameters.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
The page has been updated with a code sample from the template and the D3D11_BIND_SHADER_RESOURCE has been called out. Closing.
