### ISSUE TITLE
How are multiple deferrals handled?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1370]
Do deferrals created in, for example, several event handlers work independedly from one another, or does Completing either one of them declares the event handled and enables transition to the next state?
Common sense says it is likely the former, but then it also might be not until that is formally documented.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4baccd-ee9f-6dc3-f8ac-164ed64a4423
* Version Independent ID: 54a02657-41c0-bd3c-7b41-ff11884c76e1
* Content: [EnteredBackgroundEventArgs.GetDeferral Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-gb/uwp/api/windows.applicationmodel.enteredbackgroundeventargs.getdeferral)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.enteredbackgroundeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.enteredbackgroundeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers) offer timely answers to questions like this.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open thread for follow-ups. Thanks!
