### ISSUE TITLE
GetDeferral, but no deadline?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1371]
Is there not a way to obtain deadline, as with SuspendingOperation?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc07b0f-aa43-19a1-6384-abcb748d42c6
* Version Independent ID: 32b33275-7a37-fc3e-2464-814c4971920c
* Content: [EnteredBackgroundEventArgs Class (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-gb/uwp/api/windows.applicationmodel.enteredbackgroundeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.enteredbackgroundeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.enteredbackgroundeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers) offer timely answers to questions like this.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open thread for follow-ups. Thanks!
