### ISSUE TITLE
When this value can be null?

### ISSUE THREAD

**Issue by ad1Dima** [MicrosoftDocs/winrt-api#1372]
This is very strange for property that can be filled in xaml to ever be null. 
In which case it would be null?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 079275eb-db28-7256-b5ae-bc3ba4dd596c
* Version Independent ID: d7f9bd5c-1abf-14a5-0eeb-769d297a50e8
* Content: [MenuFlyout.Items Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.menuflyout.items?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.MenuFlyout.Items)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.menuflyout.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.menuflyout.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
You're right; it's a read-only property and can never be null. Thanks for reporting!

Fix pending: #1376.
