### ISSUE TITLE
Missing most common use case example

### ISSUE THREAD

**Issue by xyzzer** [MicrosoftDocs/winrt-api#1374]
In most cases, you'd want to extract user information from App::OnLaunched(LaunchActivatedEventArgs^)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d33fb73-90e3-05d4-d1d1-f68b89fc34f0
* Version Independent ID: 266bff02-4f2f-2d15-7b69-18f379fa1e97
* Content: [User Class (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.user#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.user.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.user.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for the comment. This page is the API reference, which simply lists classes and their members, and documents each method/property/etc. This is not where we'd generally include example code.

Please note that there is a link on the page to the User Information Sample, which demonstrates how to do exactly the things you're looking for.
