### ISSUE TITLE
CreateFromDeviceClassId can throw whereas undocumented

### ISSUE THREAD

**Issue by HunterB06** [MicrosoftDocs/winrt-api#1377]
### Description

The function `DeviceAccessInformation::CreateFromDeviceClassId` throws when it can't access the requested deviceClassId. However, this is not mentioned in the documentation page.

### How to reproduce

Create a registry key under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\DeviceAccess\Classes\` and let's call it "{00000001-0002-0003-0001-020304050607}" for example. Set all the Users permissions to "deny". Then try to access it with this line:

~~~C++
DeviceAccessInformation::CreateFromDeviceClassId(Guid(1, 2, 3, ref new Array<unsigned char>{'\0', '\1', '\2', '\3', '\4', '\5', '\6', '\7'}));
~~~

It will throw.

### Notes

The exception only appears when you don't have the permission to access the specified key. If this one does not exist, you will not get any exception, but `nullptr` will be returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2417467-f5a5-8902-648e-6b242c26c0da
* Version Independent ID: a49001cc-c695-24a0-78a4-519d563e8c40
* Content: [DeviceAccessInformation.CreateFromDeviceClassId(Guid) Method (Windows.Devices.Enumeration) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceaccessinformation.createfromdeviceclassid)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceaccessinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceaccessinformation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response.

WinRT APIs are designed such that exceptions are intended to provide feedback during app development and should not be caught at runtime. This is why our convention is not to document exceptions for WinRT APIs. The exception type and message should be sufficient to let you know the necessary changes in your code.
