### ISSUE TITLE
Incorrect note "see BitmapIcon in action"

### ISSUE THREAD

**Issue by dgellow** [MicrosoftDocs/winrt-api#1381]
Documentation on this page says:
&gt; If you have the XAML Controls Gallery app installed, click here to open the app and see the BitmapIcon in action.

But I don't see any element in XAML Controls Gallery using a `BitmapIcon`. Clicking on the link available on this page brings me to the "What's new" section within XAML Controls Gallery.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b12a439-32ae-b5c1-988b-2f593394ed1b
* Version Independent ID: 0ebae0f4-aa05-4833-c09f-54f56f169645
* Content: [BitmapIcon Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.BitmapIcon#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.bitmapicon.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.bitmapicon.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by ranjeshj** [comment]
This seems to be an issue with deep links in chromium based edge (Edge beta). The deep links work fine for me on chrome and Edge, but not consistently. works sometimes.

**Comment by dgellow** [comment]
For the records, I'm using Edge (not the beta version, so not chromium based). But you're right, that works from time to time, which is even weirder.
