### ISSUE TITLE
no sample

### ISSUE THREAD

**Issue by OrangeDogSoftware** [MicrosoftDocs/winrt-api#1382]
quite useless without a concrete sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de173073-a4d7-5a18-2b05-f66ada67322a
* Version Independent ID: 13ee0e6c-ef89-60ed-ca2f-cabafd6d10f2
* Content: [ListViewBase.ScrollIntoView Method (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.scrollintoview#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
It doesn't address this issue, but there's a complete sample of ScrollIntoView here:
https://github.com/microsoft/Windows-universal-samples/tree/v5.0.0/Samples/XamlListView/cs/Samples/ScrollIntoViewSample

**Comment by ranjeshj** [comment]
@anawishnoff , can we add a link to the sample above in the docs ?

**Comment by anawishnoff** [comment]
Just added a link in the examples section of this page, and opened a PR here: 
https://github.com/MicrosoftDocs/winrt-api/pull/1423
