### ISSUE TITLE
 I can’t seem to actually find the script “add app package sample"

### ISSUE THREAD

**Issue by yanniegao** [MicrosoftDocs/winrt-api#1385]
When I click the link and search for it. The information is: No results. Is there any scripts for it? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adecb6c7-a20b-4e93-19c1-64c8ca0c0b0a
* Version Independent ID: ef12b24c-754e-27b6-19b6-85ec408e1890
* Content: [PackageManager Class (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. We fixed the sample links. Please try again and let us know if you see any other issues!
