### ISSUE TITLE
Difference between this and GetAsyncKeyState

### ISSUE THREAD

**Issue by Mailosz** [MicrosoftDocs/winrt-api#1388]
What is the difference between GetKeyState and GetAsyncKeyState? Which one to use? Is one generally better, or does it depend on situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89b8a9b3-b25c-0059-d076-fa29e9717d25
* Version Independent ID: 239594c0-1c14-d40d-0dc7-81e5722fd32e
* Content: [CoreWindow.GetKeyState(VirtualKey) Method (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corewindow.getkeystate?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Core.CoreWindow.GetKeyState)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corewindow.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corewindow.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by StephenLPeters** [comment]
This blog post does a good job of explaining the difference: https://devblogs.microsoft.com/oldnewthing/20041130-00/?p=37173
