### ISSUE TITLE
Are there opaque icons too?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/winrt-api#1394]
Hi,

Is there a `Play`, `Stop` etc. icons filled, not just the outline?

Related: https://github.com/MicrosoftDocs/windows-uwp/issues/2165

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b122b1-0319-ec9a-2cad-6b31be0d6de6
* Version Independent ID: 16103a85-0a90-2580-6634-d4033e289eec
* Content: [Symbol Enum (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.symbol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.symbol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by ranjeshj** [comment]
Sorry no. The icons are all line based which seems consistent.

**Comment by weitzhandler** [comment]
Thanks for your reply!
