### ISSUE TITLE
Link protected / incorrect ?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1395]
Unable to open Official Country/Region List (https://globalready.azurewebsites.net/marketreadiness/OfficialCountryregion)
&gt;We're sorry, but email@host.com can't be found in the microsoft.sharepoint.com directory.
&gt;Issue Type: User not in directory.
What is globalready.azurewebsites.net anyway? Does not look like an official public resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65da88ab-4b48-5bb3-828a-a019814bebc9
* Version Independent ID: e58d064e-eda6-c11a-57bd-65f55f732c77
* Content: [GeographicRegion.Code Property (Windows.Globalization) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.geographicregion.code)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.geographicregion.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.geographicregion.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@avakhrushev - link has been revised. Thanks.
