### ISSUE TITLE
What is the default value?

### ISSUE THREAD

**Issue by JerryNixon** [MicrosoftDocs/winrt-api#1396]
Is GattSession.MaintainConnection true or false by default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b184dcd-24ac-d24b-6304-64fe0ff94ab9
* Version Independent ID: 67b7649c-324a-30b9-aecd-0a877b5029fd
* Content: [GattSession.MaintainConnection Property (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattsession.maintainconnection)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattsession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattsession.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @JerryNixon, it's `false` by default. I've published that info in the topic now.

Thanks for filing the issue!
-Steve
