### ISSUE TITLE
More clarity about how the suffix is used.

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1401]
This page does not give clarity about how DNS suffix is used. 
Is it when DNS suffix is used in domain name, the associated DNS servers of this entry are queried?

What i could notice was that if I query just "mymachine", then it gets suffixed with above entry and gets queried for DNS. E.g. if suffix is "domain.com", DNS query is done for "mymachine.domain.com". 

However, if the DNS query is already containing some suffix, I.e. "mymachine.something", there is no suffix attached and this entry is not used.
I would request you to add more details as how DomainName field is actually utilized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 644c3b89-b00c-9664-ab1b-294072aa42ac
* Version Independent ID: 9176dc97-478d-8aa3-8646-c4286d65fa34
* Content: [VpnDomainNameInfo.DomainName Property (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpndomainnameinfo.domainname)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpndomainnameinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpndomainnameinfo.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @defaultshr, thanks for filing this issue. I've reached out to the product team, and if I can get further info, then I'll be happy to add it to the documentation.

Thanks again!
Steve

**Comment by stevewhims** [comment]
**UPDATE**: I've sent a reminder to the product team. They already said they're planning to discuss it, but I thought a reminder would be good.

I'll report back here with any news.

Thanks!
Steve

**Comment by stevewhims** [comment]
Hi, @defaultshr, we believe that the issue you're seeing is that we handle domain name queries different for short names (in your example, “mymachine”) compared to regular names (in your example, “mymachine.something”). That’s in part because there’s a very long list of possible top-level names.

I've added more info to the topic, and those changes are now live.

-Steve

**Comment by stevewhims** [comment]
Hi, @defaultshr, does that info help unblock you?

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close the issue now, as it's been a while and it feels resolved and inactive.

Thanks!
Steve

**Comment by defaultshr** [comment]
Hi Steve, Thank you for the follow up on this issue. I am sorry for delay
in my response as I track this mail very infrequent. It is just some more
clarity I am requesting to be added in the documentation.
I think the functionality we are good with.

Best regards
