### ISSUE TITLE
More clarity about domain name type as "suffix"

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#1402]
This page does not give clarity about how name type suffix is used. 
Is it when DNS suffix is used in domain name, the associated DNS servers of this entry are queried? I.e. when i query mymachine.suffix.com (suffix.com is the suffix entry), the associated DNS servers of this entry get invoked?

What i could notice was that if I query just "mymachine", then it gets suffixed with DomainName entry and gets queried for DNS. E.g. if suffix DomainName is "domain.com", DNS query is done for "mymachine.domain.com". 

However, if the DNS query is already containing some suffix, I.e. "mymachine.something", there is no suffix attached and this entry is not used.
I would request you to add more details as how DomainName field is actually utilized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e2b7a2-9806-d00b-f3a0-b05904cf6409
* Version Independent ID: 17e721dd-b9d8-1429-cb6b-f5416b889987
* Content: [VpnDomainNameInfo.DomainNameType Property (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpndomainnameinfo.domainnametype)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpndomainnameinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpndomainnameinfo.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @defaultshr, this looks like the same issue as https://github.com/MicrosoftDocs/winrt-api/issues/1401. If they're the same, let's close this one.

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this one.
