### ISSUE TITLE
This parameter explanation is so amazing that it has blown my mind

### ISSUE THREAD

**Issue by IoniCStorM** [MicrosoftDocs/winrt-api#1403]
Can the comments be more useful?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a847fe27-6799-5b4b-8a35-6f6797b896d7
* Version Independent ID: 2cf3e71c-c509-04f3-8d8b-6dcdad9eab61
* Content: [AsymmetricKeyAlgorithmProvider.CreateKeyPairWithCurveParameters(Byte\[\]) Method (Windows.Security.Cryptography.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core.asymmetrickeyalgorithmprovider.createkeypairwithcurveparameters#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.asymmetrickeyalgorithmprovider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.asymmetrickeyalgorithmprovider.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @IoniCStorM , thanks for submitting your feedback. Is there anything in particular that you'd like for us to expand on in these descriptions?

**Comment by IoniCStorM** [comment]
I mean, this description is literally nothing.
The function prototype says this is a byte array, so please provide information on what kind of byte array are we expecting, what is the size constraints, what format, how should people construct such byte array. I mean people can create a zero array of 1 byte and pass it in, should it work? We dont know.
This description gives people no idea of what do they need to pass-in or how should they construct such array.

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback, and we apologize for the delayed response. I see that updates have not been made since your last comment two years ago, so I'm going to do some research to see what I can find out about this parameter. The timeline for this may vary, but I will circle back when I have more information.

**Comment by alvinashcraft** [comment]
Hi @IoniCStorM. 
Thanks again for submitting your feedback. I went ahead and created an internal work item to resolve this doc bug and today merged the changes today to add a little more explanation and code snippets in C# and C++. The changes should appear on the live site later today.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
