### ISSUE TITLE
Broken link to XAML SwapChainPanel DirectX interop sample

### ISSUE THREAD

**Issue by mgnslndh** [MicrosoftDocs/winrt-api#1404]
The link about "XAML SwapChainPanel DirectX interop sample" to https://go.microsoft.com/fwlink/p/?LinkID=309155 redirects to https://docs.microsoft.com/en-us/samples/browse/ but without showing the correct sample. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee9a5a88-6893-33e4-3875-b7c9d3ab54f2
* Version Independent ID: 56d8c4f4-c6b6-0369-f0aa-62a53117ae86
* Content: [SwapChainPanel Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swapchainpanel#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.swapchainpanel.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.swapchainpanel.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This link has been fixed. Thanks.
