### ISSUE TITLE
Link pointed to in "See XAML images sample for example code." needs to be updated

### ISSUE THREAD

**Issue by shalinijoshi19** [MicrosoftDocs/winrt-api#1414]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imagebrush.imagesource#setting-imagesource-in-code gets redirected to https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples now where we need to search for the Xaml sample explicitly. Would be nice to update the link here at this point. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7706f2c9-a534-18f1-dabe-aab8eba3f1bf
* Version Independent ID: 0dc8e443-0df8-021a-0b93-6d8dd1fc054b
* Content: [ImageBrush.ImageSource Property (Windows.UI.Xaml.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imagebrush.imagesource#setting-imagesource-in-code)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imagebrush.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imagebrush.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
This link has been fixed. Thanks.
