### ISSUE TITLE
Windows::Devices::Bluetooth includes

### ISSUE THREAD

**Issue by pneumus** [MicrosoftDocs/winrt-api#1415]
Hi there! What header files ( and other components ) do I need to be able to use the namespace "Windows::Devices::Bluetooth" ? Is there a very-very simple example for this? Also: If I am trying to compile a source code in JetBrains Clion... am I able to use Windows::Devices::Bluetooth ?

**Comment by stevewhims** [comment]
Hi, @sonus89, and thanks for filing this issue. You can use the namespace from a UWP application (using C#, for example). Or from a native application (using [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/)). I would recommend beginning by downloading and installing Visual Studio (https://visualstudio.microsoft.com/downloads/). To create a C# UWP application, you can create a new `Blank App (Universal Windows)` project within Visual Studio.

I'm not familiar with JetBrains CLion, and I can't find any references on the web to using it to call Windows Runtime APIs. To use standard C++ to call Windows Runtime APIs (such as the namespace in question), see [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/).

Thanks!
Steve
