### ISSUE TITLE
Platform / OS version applicability

### ISSUE THREAD

**Issue by jovton** [MicrosoftDocs/winrt-api#1418]
Hi. Will it be possible to include into the documentation which platforms / operating system versions this product documentation applies to? Such as Windows 7, 8, 10 etc. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6f8d4f-09bb-168c-170e-f07b9a9c5f26
* Version Independent ID: a6197377-f1dd-ce18-e775-d9eeca9e1079
* Content: [Windows.Devices.Portable Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.portable#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.portable.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.portable.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by Karl-Bridge-Microsoft** [comment]
I believe the detail you're requesting is now provided on each class and member topic in the Applies to section:

Applies to
Product	Versions
WinRT	Build 10240, Build 10586, Build 14383, Build 15063, Build 16299, Build 17134, Build 17763, Build 18362, Build 19041, Build 20348
