### ISSUE TITLE
Symbols in dark theme difficult to see

### ISSUE THREAD

**Issue by janjaali** [MicrosoftDocs/winrt-api#142]
Setting the dark-theme in the docs (https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbolicon) causes that the Symbols are difficult to see.

**Comment by mattwojo** [comment]
Thanks @janjaali -- I'm looking in to who could implement a change for this. 

*Looks like it may be the same issue filed in https://github.com/MicrosoftDocs/windows-uwp/issues/137 ... @mijacobs Were you able to make any progress on addressing this issue?

**Comment by mattwojo** [comment]
Closing so that it can be addressed in the original issue linked above.
