### ISSUE TITLE
~70 instances of broken bold usage in HTML tables need to be resolved.

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winrt-api#1420]
There are approximately 70 instances of the following in this documentation:

`<td>**words**</td>`

and they all need to be replaced with:

`<td><b>words</b></td>`

As the asterisk don't represent bold in the doc HTML tables.

Example of one such instance: #1419 visible @ https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.primitives.togglebutton.ischecked

---

You'll also notice an erroneous `[ ` in the Property column above, indicating link formatting was broken at some point.

The above should presumably appear as shown here: https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.primitives.togglebutton#remarks

Although perhaps the IsChecked links aren't supposed to exist when looking at the property page itself, as they'd just be self-referential.

**Comment by kcpitt** [comment]
This is likely a global repo issue. Suggest closing this issue and filing a bug.

**Comment by kmgallahan** [comment]
Filing a bug here or somewhere else?

If here, can this just be made a bug?

If somewhere else, where?

**Comment by kcpitt** [comment]
@kmgallahan Apologies, my comment was meant for @hickeys to follow up.

**Comment by GrantMeStrength** [comment]
Phew I fixed the <td>**something**<td> stuff, and also the italic ones for good measure. Should be published soon.
The { issue is definitely a tooling issue, and we'll take care of it.
Thanks for the feedback!

-john

**Comment by GrantMeStrength** [comment]
BTW, the content in the [    ] 's  are just the attributes for the type, reproduced in the syntax (the bracket/parenthesis stuff is syntax for attributes). They should really be hidden, so that task is now added to our list. thanks!
