### ISSUE TITLE
CheckUpdateAvailabilityAsync always return PackageUpdateAvailability.Unknown

### ISSUE THREAD

**Issue by ngducnghia** [MicrosoftDocs/winrt-api#1421]
I tried with several ways and both in debug and upload app to store, but the PackageUpdateAvailability is always return Unknown

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb69cc83-27fc-5cf4-fe69-98ab75c4d061
* Version Independent ID: 62dbf413-5f27-f370-b024-f4aa014109a5
* Content: [Package.CheckUpdateAvailabilityAsync Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.checkupdateavailabilityasync#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. It sounds like you're truing to use this method to check for updates for an app that you are publishing to the Store. This method is not intended to be used for Store-published apps; instead, it is designed to be used to check for updates for an app that was deployed using App Installer, bypassing the Store (this is a popular enterprise scenario). 

To check for updates for an app that was published to the Store, use the Windows.Services.Store APIs discussed in [this article](https://docs.microsoft.com/windows/uwp/packaging/self-install-package-updates).

I hope this helps.
