### ISSUE TITLE
Linking to delegate types

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1422]
Would it be possible to automatically link to delegate types on event pages?

For example, on the [`ListViewBase.ItemClick` page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.itemclick), I would love a link to [`ItemClickEventHandler `](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemclickeventhandler)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1af0f1-5e90-39ad-0cb1-3dc015880eaf
* Version Independent ID: 30cca0ac-4c05-2566-b3c0-733c0c58762c
* Content: [ListViewBase.ItemClick Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.itemclick)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **GrantMeStrength**
* Microsoft Alias: **jken**

**Comment by jwmsft** [comment]
The doc build now automatically includes links to delegate types from event pages.
