### ISSUE TITLE
DateTaken please precise and fix typo

### ISSUE THREAD

**Issue by Ponant** [MicrosoftDocs/winrt-api#1424]
DateTaken is a DateTimeOffset, so it cannot be compared to 0.
Also, could you please be more accurate on the difference between this and `System.Photo.DateTaken` since File explorer shows some differences when using AQS syntax?
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 607552f4-9f8f-d0dc-ecf1-2351f61d0cb8
* Version Independent ID: fce8eefa-10a0-1360-d642-98387a385ccf
* Content: [ImageProperties.DateTaken Property (Windows.Storage.FileProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.imageproperties.datetaken)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.imageproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.imageproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by MatchaMatch** [comment]
Thanks for bringing this to our attention! I've submitted an update that more accurately and precisely describes the default behavior of this property - you should see these changes published soon.
