### ISSUE TITLE
Member type shown as 'long' for C++

### ISSUE THREAD

**Issue by dunhor** [MicrosoftDocs/winrt-api#1425]
Member type is shown as 'long' for both C++/WinRT and C++/CX, which is incorrect. First off, using long is ambiguous at best (its size is not guaranteed), and if we're talking MSVC behavior, it's just straight up incorrect. It's a 64-bit integer value, so I'd expect either 'int64_t' (preferred) or 'long long' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279b4600-a80e-3c2f-90fe-0b5310cff339
* Version Independent ID: be7644a2-8e38-14d2-f0c0-2cf1eb065d28
* Content: [TimeSpan.Duration Field (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.timespan.duration)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.timespan.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.timespan.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. It looks as if a note was subsequently added to this docs page noting that the field is not used in C++/WinRT. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
