### ISSUE TITLE
applicationThemeMemberName should be an actual example

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-api#1426]
applicationThemeMemberName should be replaced in the sample with "light" or "dark"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f25f17-cfcb-c9e5-4ba1-9fcf681290be
* Version Independent ID: 1ac80111-7675-3a55-10d2-f8b6eb038db8
* Content: [Application.RequestedTheme Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.requestedtheme)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the suggestion, and sorry this reply has taken so long. The code you're referring to is actually the XAML Sytax block, and is not inteneded to be an actual code example. For enumeration values, we use the format 'enumerationNameMemberName' as a placeholder value. In this case, there are only two values, so it would be easy to use Light/Dark, but many enumerations have many more values. To be consistent accross the docs, we use the placeholder.
