### ISSUE TITLE
Descriptions of Transpose and Transverse the wrong way around

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-api#1427]
I believe that the descriptions of Transpose and Transverse are the wrong way around. Look for the description of orientation in the EXIF standard here - http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3022d42d-bc04-3e02-cf71-1872b529d9cf
* Version Independent ID: 6141e74d-e76a-5ba3-009b-17f22464d572
* Content: [PhotoOrientation Enum (Windows.Storage.FileProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.photoorientation#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.photoorientation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.photoorientation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @benstevens48 , thanks for bringing this to our attention. The descriptions are indeed the wrong way around. I went ahead and made the changes and they should be live soon. Be well.
