### ISSUE TITLE
See also links are broken

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1429]
Not sure what happened to the formatting here? Is this a tooling issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86d44be9-4d5a-8a06-703a-e81c686fbabd
* Version Independent ID: 0dec26a6-4a62-0001-e8b8-cf6188eba916
* Content: [FlyoutBase Class (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Primitives.FlyoutBase)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutbase.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@michael-hawker, thanks for reporting this. There was some old markdown there that the current doc build system didn't like. It's fixed now.
