### ISSUE TITLE
"Creating a EXE component with C++" sample doesn't exist

### ISSUE THREAD

**Issue by Psychlist1972** [MicrosoftDocs/winrt-api#1430]
Was hoping to look at the code for this sample, but the link just redirects to the generic "browse code samples" page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b6876d-e068-8082-59ac-3e88d60eee7b
* Version Independent ID: 53b299cb-ed79-4ace-0e8f-fe4a003acf12
* Content: [IGetActivationFactory Interface (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.IGetActivationFactory#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.igetactivationfactory.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.igetactivationfactory.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
The link on this page now navigates to a specific code sample on GitHub about creating an EXE. It's a very old sample, but it matches the link. Sorry for the lengthy delay. I just re-assigned a bunch of old issues to myself a few weeks ago.
