### ISSUE TITLE
Exposing gyrometer and accelerometer

### ISSUE THREAD

**Issue by Miksel12** [MicrosoftDocs/winrt-api#1433]
Many modern controllers have gyrometers and accelerometers, is it possible to expose these in Windows.Gaming.Input?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c382eaa-aecb-0f26-ab0e-e752c9a36713
* Version Independent ID: 7b0c1235-3109-5b93-33c7-203426d2fad6
* Content: [Windows.Gaming.Input Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Miksel12 - This feedback is not specifically about the documentation, the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
