### ISSUE TITLE
Unexpected Method Call... why

### ISSUE THREAD

**Issue by jhwheuer** [MicrosoftDocs/winrt-api#1435]
In a multi-threaded environment, I am getting an exception "Unexpected Method Call...., the previous call has not been completed" when I am trying to access multiple StorageFiles from multiple threads under load (one thread, one file)... If I throttle access by using a Semaphore so that this call is only made once across all threads (the other ones are waiting in front of the Semaphore), this error does not occur..
Is there some kind of "static" behavior that discourages multi-threaded/concurrent use of this method that I am not aware of?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bd09af9-13d3-f3b3-496a-f6b751d6ec16
* Version Independent ID: 3938e25a-d6b6-9564-086e-939e33f9ccec
* Content: [FileInformation.GetBasicPropertiesAsync Method (Windows.Storage.BulkAccess) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.bulkaccess.fileinformation.getbasicpropertiesasync?source=docs#Windows_Storage_BulkAccess_FileInformation_GetBasicPropertiesAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.bulkaccess.fileinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.bulkaccess.fileinformation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @jhwheuer , I'm currently working to see if I can an answer to your question. Should there be any answers, I will circle back and possibly update our documentation to clarify. Many thanks for bringing this to our attention.
