### ISSUE TITLE
This event is static and not marked as static

### ISSUE THREAD

**Issue by hamalawi** [MicrosoftDocs/winrt-api#1451]
This event should be marked as static as the actual event is static.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 424e88cb-e457-ff6d-35ce-274d4008b6de
* Version Independent ID: a67c5f11-193a-502d-582c-93a0a8940188
* Content: [HolographicSpace.IsAvailableChanged Event (Windows.Graphics.Holographic) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicspace.isavailablechanged#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicspace.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicspace.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
This was an documentation engineering issue that has been fixed. The syntax block now includes the static keyword.
