### ISSUE TITLE
Dispatcher Question

### ISSUE THREAD

**Issue by ad1Dima** [MicrosoftDocs/winrt-api#1457]
Is CoreApplicationView.Dispatcher the same as CoreApplicationView.CoreWindow.Dispatcher ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c519824-a689-9d12-5429-e55cf4acb1a6
* Version Independent ID: 09129cc7-a6e7-9b92-7043-75a3d4ecdded
* Content: [CoreApplicationView.Dispatcher Property (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.coreapplicationview.dispatcher?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.ApplicationModel.Core.CoreApplicationView.Dispatcher)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplicationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplicationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mikben**
* Microsoft Alias: **mikben**

**Comment by MikeHillberg** [comment]
Yes. There a bunch of other classes that have the same Dispatcher property as well. There's only one CoreDispatcher per thread, so any object on that thread will return the same one.

**Comment by ad1Dima** [comment]
@MikeHillberg I think this should be clarified in the docs.

**Comment by MatchaMatch** [comment]
Clarifications have been made to the docs [[PR](https://github.com/MicrosoftDocs/winrt-api/pull/1504)]. Thanks @ad1Dima for your suggestion - the updates should be live soon.
