### ISSUE TITLE
Broken link: Official Country/Region List 

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/winrt-api#1461]
Under remarks (https://docs.microsoft.com/en-us/uwp/api/Windows.Globalization.GeographicRegion#remarks), the Official Country/Region List points to a non-working location (https://globalready.azurewebsites.net/marketreadiness/OfficialCountryregion)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a17fcc4-cf77-a397-604d-659e0b9244d7
* Version Independent ID: 91d3daeb-7964-91d9-e49d-46a66165ca2c
* Content: [GeographicRegion Class (Windows.Globalization) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Globalization.GeographicRegion#remarks)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.geographicregion.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.geographicregion.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
THanks @riverar. I've revised the link (and similar in other topics).

**Comment by riverar** [comment]
@Karl-Bridge-Microsoft While that works its way up the chain, can you provide the new link?

**Comment by Karl-Bridge-Microsoft** [comment]
https://docs.microsoft.com/en-us/windows/uwp/publish/supported-languages
