### ISSUE TITLE
Using Font Icons

### ISSUE THREAD

**Issue by groovykool** [MicrosoftDocs/winrt-api#1462]
"Then, use the format "&#x/(UNICODE);" in XAML, or the format "\u/(UNICODE)" in code, where (UNICODE) is the value of the glyph that indicates the location in the font file."

The above does not work....

This Does work........
`<winui:NavigationViewItem.Icon>
                    <FontIcon FontFamily="Segoe MDL2 Assets" Glyph="&#xE7FC;"/>
</winui:NavigationViewItem.Icon>`

**Comment by jwmsft** [comment]
@groovykool , thanks for letting us know about this. The doc has been fixed.
