### ISSUE TITLE
Missing C# code

### ISSUE THREAD

**Issue by gsantopaolo** [MicrosoftDocs/winrt-api#1469]
Hi there, the example provided in this document is missing the CalligraphicPen C# implementation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b528830f-60eb-338d-26d0-c0ea33736895
* Version Independent ID: 7c384a26-0696-9659-6269-704296a65a47
* Content: [InkToolbarPenConfigurationControl Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.inktoolbarpenconfigurationcontrol)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.inktoolbarpenconfigurationcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.inktoolbarpenconfigurationcontrol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. This is just a basic example. The see also has a link to a more robust topic: https://docs.microsoft.com/en-us/windows/apps/design/input/ink-toolbar.
