### ISSUE TITLE
'Access Denied` exception when trying to delete a folder when the folder is retrieved with FolderPicker or the KnownFolders API.

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/winrt-api#1473]
It would be good to add a note on this page that if a StorageFolder is retrieved with FolderPicker or the KnownFolders API. If you call DeleteAsync() on a folder in this scenario, the WinRT runtime throws the following exception:

Exception thrown at 0x00007FFB7639A839 (KernelBase.dll) in RuntimeBroker.exe: WinRT originate error - 0x80070005 : 'Cannot delete or rename the specified folder (New folder). If the folder was acquired using the File Picker or the KnownFolders API, it cannot be deleted or renamed. Additionally, the folder cannot be deleted if it resides in a filtered location, such as the Documents library or removable devices.'.

 And this exception does not propogate to the managed System.UnauthorizedAccessException, which simply says 'Access Denied'. 

Although the WinRT exception does show in the application Output pane during debugging, it is easy to miss as it shows up well before the managed exception in the output  and that managed exception is not as informative, making it a bit difficult to understand why the access is denied. 

So I suggest adding a note on the docs page indicating that you will get an exception if you call DeleteAsync on a StorageFolder acquired by one of the above noted mechanisms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04061719-8b57-32dd-ee2a-92d303d0fd94
* Version Independent ID: 6a1c5dbc-4ec0-a1f3-f62f-4b4de8bd4b28
* Content: [StorageFolder.DeleteAsync Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.deleteasync#Windows_Storage_StorageFolder_DeleteAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for the suggestion, @jgold6 ! I'll work to include this. Once this is done, I will circle back to notify you that it's live.

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
