### ISSUE TITLE
Quickstart links to html/javascript documentation

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/winrt-api#1474]
"Quickstart: Reading and writing a file" links to html / javascript documentation on Windows 8. It should link to more a more recent quickstart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b109100-bcd9-bf8e-b1bb-2f191b9a7c40
* Version Independent ID: aa58ff16-a56c-0e4f-0c93-284d007a2460
* Content: [IRandomAccessStream Interface (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.irandomaccessstream#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.irandomaccessstream.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.irandomaccessstream.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @wldevries , and thanks for bringing this to our attention. I went ahead and updated the quickstart link to point to our most updated one [here](https://docs.microsoft.com/windows/uwp/files/quickstart-reading-and-writing-files). Thanks for your contribution and be well.
