### ISSUE TITLE
link to UIElement.BringIntoViewRequested is broken

### ISSUE THREAD

**Issue by stevenbrix** [MicrosoftDocs/winrt-api#1487]
title says it all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbcab7a-b3f3-1271-a546-553ad3e2ca66
* Version Independent ID: ce56e137-77ad-cd42-0b35-9d6711ec3e2b
* Content: [BringIntoViewRequestedEventArgs Class (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.bringintoviewrequestedeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.bringintoviewrequestedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.bringintoviewrequestedeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@stevenbrix , thanks for letting us know about this. The link is fixed now.
