### ISSUE TITLE
The index out parameter is incorrect for C++/CX

### ISSUE THREAD

**Issue by marmphco** [MicrosoftDocs/winrt-api#1488]
The signature should be:

```c++
public : Platform::Boolean IndexOf(Platform::Object^ value, unsigned int* index);
```

...instead of:

```c++
public : Platform::Boolean IndexOf(Platform::Object value, unsigned int index);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e4a65cc-0478-b715-919c-d806c9bed9c6
* Version Independent ID: 6797d5d3-acb5-2ace-fc19-74e436327603
* Content: [IBindableVector.IndexOf(Object, UInt32) Method (Windows.UI.Xaml.Interop) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.interop.ibindablevector.indexof#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.interop.ibindablevector.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.interop.ibindablevector.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Thanks, @marmphco, and apologies for the very long delay in responding to this issue. It looks like the signature is correct on the live site now, so I'll go ahead and close the issue.

-Steve
