### ISSUE TITLE
Incomplete Examples

### ISSUE THREAD

**Issue by sometowngeek** [MicrosoftDocs/winrt-api#149]
I feel some document has some classes provide incomplete examples...

For example, take a look at [GridView Class](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.gridview). With the code:

    <GridView ItemsSource="{Binding Source={StaticResource cvsProjects}}"
    

I don't see the `cvsProjects` class anywhere in the example, so I cannot copy / paste the examples to play around with it in order to understand how it works.

It would be nice if the `cvsProjects` or an example class was shown so we could use it with the rest of the examples.

**Comment by sometowngeek** [comment]
Maybe to illustrate the issue better...

I understand that it's possible to get to:
![Image of GridView example](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls/images/controls/gridviewbasic.png)

But how do we get there? The provided example doesn't help me because it doesn't work without the **cvsProject** class or the class the image used.

**Comment by mattwojo** [comment]
Thanks for bringing this to our attention @sometowngeek. 
Assigning to @jwmsft -- do you own this page content? Could you help with this code example or do you have an idea of who should be assigned?  Thank you!

**Comment by sometowngeek** [comment]
@mattwojo, I think @msatranjr owns the content.

**Comment by mattwojo** [comment]
Thanks @sometowngeek -- @msatranjr coordinated the migration of much of this content so has his alias associated with a lot of it, even though he is not the content owner... adds some confusion, but we're still getting some of the aspects of the auto-generated API ref figured out. 

That said, I just connected with @jwmsft and he confirmed that he is investigating your issue. Thanks again for filing it. ~Matt

**Comment by sometowngeek** [comment]
Just piping in to see how things are going with this...

Any updates so far, @mattwojo?

**Comment by jwmsft** [comment]
Hi @sometowngeek, @mattwojo  - Sorry for the delay in getting back to you. The article that has the complete code for this example was not migrated from the Windows 8 docs to the Windows 10 docs. While we work on fixing this, and adding the links back, you can see the complete code in the Windows 8 doc archive, here: https://msdn.microsoft.com/library/windows/apps/xaml/hh780627.aspx
