### ISSUE TITLE
InstalledDate is not correct for packages deployed directly from Visual Studio

### ISSUE THREAD

**Issue by axodox** [MicrosoftDocs/winrt-api#1490]
When a UWP package is deployed first from Visual Studio to a device, its InstalledDate will be correct, but further updates will not update this date. This can problematic for development builds, where the package version might be meaningless, since it is not centrally managed. Uninstalling and redeploying will update the value once again.

Please add a note about this behavior or make Visual Studio update this value properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2672d1de-2424-b178-8907-b731ca68a86f
* Version Independent ID: 431c0f1d-cd59-7466-24f5-561fe503a6e9
* Content: [Package.InstalledDate Property (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.installeddate)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mikben**
* Microsoft Alias: **mikben**

**Comment by MatchaMatch** [comment]
Thanks for your suggestion, @axodox. A clarification has been made to the docs and should be visible soon.
