### ISSUE TITLE
Inheritance chain incorrect

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1491]
In C#, IBindableObservableVector inherits from IList. So this:

```
IList -&gt; IEnumerable -&gt; IBindableObservableVector
```

should be this:

```
IBindableObservableVector -&gt; IList -&gt; IEnumerable
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aae2fa96-10e8-9b16-8b8f-a6f00167fcbd
* Version Independent ID: 24e07c30-b1fc-d107-6bcf-6f572559cf14
* Content: [IBindableObservableVector Interface (Windows.UI.Xaml.Interop) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.interop.ibindableobservablevector#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.interop.ibindableobservablevector.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.interop.ibindableobservablevector.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by QuinnRadich** [comment]
I think this issue arose from automatic formatting in the API ref docs. I believe it has been fixed since this issue was reported, as I no longer see it.

If there's still a related problem on this page, please open a new issue detailing it. Thank you.
