### ISSUE TITLE
"This class is not agile" ?

### ISSUE THREAD

**Issue by SergeyADoroshenko** [MicrosoftDocs/winrt-api#1493]
this code:
```
            var info = typeof(Windows.UI.Input.Inking.InkStroke);
            var isAgile  = info
                .CustomAttributes
                .First(x => x.AttributeType == typeof(Windows.Foundation.Metadata.MarshalingBehaviorAttribute))
                .ConstructorArguments[0].Value.Equals((int)Windows.Foundation.Metadata.MarshalingType.Agile);

```

sets variable `isAgile` to `true`. Why does the documentation claim the InkStroke class is not agile?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca24d88b-0b49-a097-1038-911984f5e570
* Version Independent ID: 65dc525d-1033-32ac-5b86-c826ab943799
* Content: [InkStroke Class (Windows.UI.Input.Inking) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Input.Inking.InkStroke#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.inking.inkstroke.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.inking.inkstroke.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for spotting this @SergeyADoroshenko. I updated the topic (along with a few others that had the same issue).
