### ISSUE TITLE
Description is incomplete/strongly misleading

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1510]
The description provided of how the value for this property is calculated is incomplete and suggests that the list will be empty if none of the languages preferred by the user intersect with localizations declared by application, which is not the case. Instead, if none of the users languages match, whatever language happens to be listed first in the apps localizations is returned, which directly contradicts the statement in the Remarks section - "best current runtime language value(s) preferred by the user" it is not. Not when returned value is not even in the list of languages known to the user.   The guidelines article surprisingly is more thorough https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/manage-language-and-region#app-runtime-language-list , this piece of the official API reference should at very least link to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db59e0e-98c9-833b-742b-4ef3c5d9f9b9
* Version Independent ID: 041fcb3f-c585-23aa-d7cb-1b6837e0aeae
* Content: [ApplicationLanguages.Languages Property (Windows.Globalization) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.applicationlanguages.languages)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.applicationlanguages.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.applicationlanguages.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been updated with detail from overview.
