### ISSUE TITLE
The example is wrong

### ISSUE THREAD

**Issue by lanatmwan** [MicrosoftDocs/winrt-api#1511]
UsbDeviceClass does not have a constructor that takes UsbDeviceClasses as an arg.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f471b6b-acfd-dd58-e359-b95e9903bf95
* Version Independent ID: b0f9e780-61b6-8e1e-8f5c-7fd76bb44661
* Content: [UsbDeviceClasses Class (Windows.Devices.Usb) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.usb.usbdeviceclasses#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.usb.usbdeviceclasses.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.usb.usbdeviceclasses.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by lanatmwan** [comment]
This works:
			var myDevices = 
				await Windows.Devices.Enumeration.DeviceInformation.FindAllAsync(
					  UsbDevice.GetDeviceClassSelector(
						  new UsbDeviceClass() 
						  { 
							  ProtocolCode = UsbDeviceClasses.CdcControl.ProtocolCode, 
							  ClassCode = UsbDeviceClasses.CdcControl.ClassCode, 
							  SubclassCode = UsbDeviceClasses.CdcControl.SubclassCode
						  }));

**Comment by stevewhims** [comment]
Hi, @lanatmwan, and thanks for spotting this error and letting us know.

The API's descriptions and the code were, as you say, incorrect, so I've published fixes to those (which are now live).

Thanks again!
Steve
