### ISSUE TITLE
IIterable with size

### ISSUE THREAD

**Issue by peledins** [MicrosoftDocs/winrt-api#1512]
Is there IIterable with size?
it seems that in most cases there is size available, it would be great to have such.
Otherwise you have to iterate through to find whether the size is not too large.
e.g.: 
void FuncCanHandleLessthan5(IIterable) 
needs to loop 5 times to see if it can handle the input, which is a bit wasteful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9224dec3-c62b-8333-2ff9-3a15b95d74fc
* Version Independent ID: eacbe3ce-3afe-3592-f228-2b6e4cfad265
* Content: [IIterable&lt;T&gt; Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Collections.IIterable_T_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.iiterable_t_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.iiterable_t_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by MikeHillberg** [comment]
To add size and indexing you can use [IVector<T>](https://docs.microsoft.com/uwp/api/Windows.Foundation.Collections.IVector_T_).

**Comment by hickeys** [comment]
As @MikeHillberg said, you can use the IVector interface for that. Size does not belong in the IIterable interface as it's perfectly reasonable to iterate over something of an unknown size.
