### ISSUE TITLE
How to get camera view transform on Hololens2

### ISSUE THREAD

**Issue by jianchong-chen** [MicrosoftDocs/winrt-api#1514]
I open the camera and get MediaFrameReference, then I want to get the camera view transformation matrix. 
I used the GUID(0x4E251FA4, 0x830F, 0x4770, 0x85, 0x9A, 0x4B, 0x8D, 0x99, 0xAA, 0x80, 0x9B)
to find the matrix from the MediaFrameReference.Properties,
It works well on Hololens1, but always failed on Hololens2.
I tried many ways to find how to get this matrix, but always failed , 
could you help me to fix the problem? Thank you very much!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bef07a03-4fbb-f4ef-ca3c-359cb9776848
* Version Independent ID: 0fd3c7d1-2ab9-677b-a0c9-2e30f65322dd
* Content: [MediaFrameReference Class (Windows.Media.Capture.Frames) - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.media.capture.frames.mediaframereference)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.frames.mediaframereference.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.frames.mediaframereference.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by jianchong-chen** [comment]
The code is as below:
```
XTERN_GUID(MFSampleExtension_Spatial_CameraViewTransform, 0x4E251FA4, 0x830F, 0x4770, 0x85, 0x9A, 0x4B, 0x8D, 0x99, 0xAA, 0x80, 0x9B);
IPropertyValue^ cameraViewIPropertyValue = 
(Windows::Foundation::IPropertyValue^)frame->Properties->Lookup(MFSampleExtension_Spatial_CameraViewTransform);
```

**Comment by drewbatgit** [comment]
Hello, this feedback channel is intended to be used exclusively for documentation issues, rather than general developer support, but I reached out to the feature team and received this guidance:

Those attributes are deprecated n HoloLens 2. They are replaced by:

https://docs.microsoft.com/en-us/windows/win32/medfound/mfsampleextension-cameraextrinsics
https://docs.microsoft.com/en-us/windows/win32/medfound/mfsampleextension-pinholecameraintrinsics

Those attributes can be referenced directly by application code using the older COM-based MF APIs, i.e. IMFSample et al. We have code samples that demonstrate how to assemble the raw data to relate a camera frame to an existing SpatialCoordinateSystem tracked by the HMD; see below for the canonical example.

The ”golden path” is to use the Windows.Media.Capture.Frames WinRT API, which does all the integration below for you, and is accessible from C# (modulo normal Unity UWP constraints). Specifically, the extrinsics and intrinsics are exposed via the following properties:
https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframereference.coordinatesystem
https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.videomediaframe.cameraintrinsics

```
#include <winrt/windows.perception.spatial.preview.h>
#include <mfapi.h>
#include <mfidl.h>
 
using namespace winrt::Windows::Foundation;
using namespace winrt::Windows::Foundation::Numerics;
using namespace winrt::Windows::Perception;
using namespace winrt::Windows::Perception::Spatial;
using namespace winrt::Windows::Perception::Spatial::Preview;
 
class CameraFrameLocator
{
public:
    struct CameraFrameLocation
    {
        SpatialCoordinateSystem CoordinateSystem;
        float4x4 CameraViewToCoordinateSytemTransform;
        MFPinholeCameraIntrinsics Intrinsics;
    };
 
    std::optional<CameraFrameLocation> TryLocateCameraFrame(IMFSample* pSample)
    {
        MFCameraExtrinsics cameraExtrinsics;
        MFPinholeCameraIntrinsics cameraIntrinsics;
        UINT32 sizeCameraExtrinsics = 0;
        UINT32 sizeCameraIntrinsics = 0;
        UINT64 sampleTimeQpc = 0;
 
        // query sample for calibration and validate
        if (FAILED(pSample->GetUINT64(MFSampleExtension_DeviceTimestamp, &sampleTimeQpc)) ||
            FAILED(pSample->GetBlob(MFSampleExtension_CameraExtrinsics, (UINT8*)& cameraExtrinsics, sizeof(cameraExtrinsics), &sizeCameraExtrinsics)) ||
            FAILED(pSample->GetBlob(MFSampleExtension_PinholeCameraIntrinsics, (UINT8*)& cameraIntrinsics, sizeof(cameraIntrinsics), &sizeCameraIntrinsics)) ||
            (sizeCameraExtrinsics != sizeof(cameraExtrinsics)) ||
            (sizeCameraIntrinsics != sizeof(cameraIntrinsics)) ||
            (cameraExtrinsics.TransformCount == 0))
        {
            return std::nullopt;
        }
 
        // compute extrinsic transform
        const auto& calibratedTransform = cameraExtrinsics.CalibratedTransforms[0];
        const GUID& dynamicNodeId = calibratedTransform.CalibrationId;
        const float4x4 cameraToDynamicNode =
            make_float4x4_from_quaternion(quaternion{ calibratedTransform.Orientation.x, calibratedTransform.Orientation.y, calibratedTransform.Orientation.z, calibratedTransform.Orientation.w }) *
            make_float4x4_translation(calibratedTransform.Position.x, calibratedTransform.Position.y, calibratedTransform.Position.z);
 
        // update locator cache for dynamic node
        if (dynamicNodeId != m_currentDynamicNodeId || !m_locator)
        {
            m_locator = SpatialGraphInteropPreview::CreateLocatorForNode(dynamicNodeId);
            if (!m_locator)
            {
                return std::nullopt;
            }
 
            m_frameOfReference = m_locator.CreateAttachedFrameOfReferenceAtCurrentHeading();
            m_currentDynamicNodeId = dynamicNodeId;
        }
 
        // locate dynamic node
        auto timestamp = PerceptionTimestampHelper::FromSystemRelativeTargetTime(TimeSpanFrodmQpcTicks(sampleTimeQpc));
        auto coordinateSystem = m_frameOfReference.GetStationaryCoordinateSystemAtTimestamp(timestamp);
        auto location = m_locator.TryLocateAtTimestamp(timestamp, coordinateSystem);
        if (!location)
        {
            return std::nullopt;
        }
 
        const float4x4 dynamicNodeToCoordinateSystem = make_float4x4_from_quaternion(location.Orientation()) * make_float4x4_translation(location.Position());
 
        return CameraFrameLocation{ coordinateSystem, cameraToDynamicNode * dynamicNodeToCoordinateSystem, cameraIntrinsics };
    }
 
private:
    GUID m_currentDynamicNodeId{ GUID_NULL };
    SpatialLocator m_locator{ nullptr };
    SpatialLocatorAttachedFrameOfReference m_frameOfReference{ nullptr };
 
    // Convert a duration value from a source tick frequency to a destination tick frequency.
    static inline int64_t SourceDurationTicksToDestDurationTicks(int64_t sourceDurationInTicks, int64_t sourceTicksPerSecond, int64_t destTicksPerSecond)
    {
        int64_t whole = (sourceDurationInTicks / sourceTicksPerSecond) * destTicksPerSecond;                          // 'whole' is rounded down in the target time units.
        int64_t part = (sourceDurationInTicks % sourceTicksPerSecond) * destTicksPerSecond / sourceTicksPerSecond;    // 'part' is the remainder in the target time units.
        return whole + part;
    }
 
    static inline TimeSpan TimeSpanFromQpcTicks(int64_t qpcTicks)
    {
        static const int64_t qpcFrequency = []
        {
            LARGE_INTEGER frequency;
            QueryPerformanceFrequency(&frequency);
            return frequency.QuadPart;
        }();
 
        return TimeSpan{ SourceDurationTicksToDestDurationTicks(qpcTicks, qpcFrequency, winrt::clock::period::den) / winrt::clock::period::num };
    }
}; 
```

**Comment by jianchong-chen** [comment]
Thanks so much for your help!

**Comment by HoloEnjoyer** [comment]
hello @drewbatgit,
How can this be done in Unity C# as there's no such type as CameraExtrinsics? Could you provide more sources or snippets to understand how to achieve this in Unity?
