### ISSUE TITLE
Remarks second paragraph seems missing some words

### ISSUE THREAD

**Issue by vmoroz** [MicrosoftDocs/winrt-api#1521]
It seems that names of C# types are not showing up. E.g. 'developers should use the interface' and '.NET code can use the APIs of instead'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0989466e-1959-f241-51f1-6ce699d3d5cb
* Version Independent ID: e9e825b8-db76-0e50-7608-bac0f53b22a5
* Content: [IVectorView&lt;T&gt; Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Collections.IVectorView_T_#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivectorview_t_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.ivectorview_t_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. It looks like this issue may have been corrected in the interim. The remarks paragraph looks correct to me now and does list the types. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
