### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by keparanj** [MicrosoftDocs/winrt-api#1556]
The link [Touch interaction design](https://msdn.microsoft.com/library/9ba7f613-e5d1-40d4-920b-143094209e3a) is broken.

![image](https://user-images.githubusercontent.com/59984314/77569422-6c9b9f80-6e87-11ea-8cf5-daf1ae0204d3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64baae30-6057-c654-ba55-98f1c2f222d1
* Version Independent ID: fc234674-9fe8-e06c-3dcd-01e03f418433
* Content: [UIElement.Tapped Event (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.tapped)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
link has been updated. Thanks.
