### ISSUE TITLE
Cursor graphics for each CoreCursorType

### ISSUE THREAD

**Issue by r2d2rigo** [MicrosoftDocs/winrt-api#1557]
It would be very helpful to display an image of the cursor for each CoreCursorType value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da15f38-4a63-3242-6714-042d5742dee4
* Version Independent ID: 20fe3e6d-634d-77b0-bf93-d88f10aa7fdc
* Content: [CoreCursorType Enum (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corecursortype#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecursortype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecursortype.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by lukeblevins** [comment]
I agree! Here's a PR
