### ISSUE TITLE
How do you do the reverse transformation: National Digits -> Latin? 

### ISSUE THREAD

**Issue by Paul-Dempsey** [MicrosoftDocs/winrt-api#1558]
This class as documented appears to support only Latin -&gt; National Digits. When an Arabic keyboard is used to input text to a TextBox, it produces national digits, and there is apparently no way to transform these to Latin digits, or configure the keyboard to provide Latin digits. (using Latin digits is critical for many business applications).

What class or API provides the National-&gt;Latin digit transform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1b31f4-12ca-e597-8cad-2ca43da7e55f
* Version Independent ID: 1392eb1e-af45-c0cd-043a-bc4545486116
* Content: [NumeralSystemTranslator Class (Windows.Globalization.NumberFormatting) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.numberformatting.numeralsystemtranslator)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.numberformatting.numeralsystemtranslator.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.numberformatting.numeralsystemtranslator.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
This appears to be the extent of the functionality supported by the platform and is not a doc issue. If you'd like to provide feedback to the product team, please use the Product Feedback link at the bottom of the topic.
