### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by iamart** [MicrosoftDocs/winrt-api#1561]
After introducing winrt-uwp definitions/reference to my project I begun receiving following errors:

> Property 'ApplicationViewMode' does not exist on type 'typeof ViewManagement'. Did you mean 'ApplicationViewState'?ts(2551)
> Property 'tryEnterViewModeAsync' does not exist on type 'ApplicationView'.ts(2339)

Until it's fixed I have to stick to declaring windows namespace to alleviate errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10f72c5b-1c14-e2bb-b6b3-abf43cf7e254
* Version Independent ID: df9a2db8-9988-47d8-d5e2-0ab18c996ab7
* Content: [ApplicationViewMode Enum (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationviewmode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.applicationviewmode.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.applicationviewmode.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
This doesn't appear to be a doc issue.
