### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by radev8** [MicrosoftDocs/winrt-api#1572]
How do you select the default?  It would be useful to explain it or have a link to where it is explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c6db8f-4fb1-a138-f4be-525cd5392e2b
* Version Independent ID: e9cb8206-2d06-3f5f-31fe-4c5232c30f47
* Content: [QueryOptions.FileTypeFilter Property (Windows.Storage.Search) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.queryoptions.filetypefilter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.queryoptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.queryoptions.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
