### ISSUE TITLE
None of these classes exist?

### ISSUE THREAD

**Issue by dovholuknf** [MicrosoftDocs/winrt-api#1573]
&gt;This object can be a Windows.Networking.StreamSocket, a Windows.Networking.WebStreamSocket, or a Windows.NetworkingDatagramSocket

I cannot find any of these classes. I expect that:
- Windows.Networking.StreamSocket --&gt; Windows.Networking.Sockets.StreamSocket
- Windows.NetworkingDatagramSocket --&gt; Windows.Networking.Sockets.DatagramSocket
- Windows.Networking.WebStreamSocket --&gt; Windows.Networking.Sockets.StreamWebSocket 

Is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dfc8f2c-fc91-a4c2-7706-c50f3c96d4d6
* Version Independent ID: fb7bc7b7-aa5f-e645-1364-5939a2a22ec4
* Content: [VpnChannel.StartWithMainTransport(IVectorView&lt;HostName&gt;, IVectorView&lt;HostName&gt;, VpnInterfaceId, VpnRouteAssignment, VpnDomainNameAssignment, UInt32, UInt32, Boolean, Object) Method (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnchannel.startwithmaintransport)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnchannel.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnchannel.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @dovholuknf, and thanks for filing this issue. You're absolutely correct about the types that we should be listing and linking to here. The fix to the topic is now live, and I fixed several other topics (that had the same problem) also. So I'll go ahead and close the issue.

Thanks again!
Steve
