### ISSUE TITLE
links outdated

### ISSUE THREAD

**Issue by kb5ylg** [MicrosoftDocs/winrt-api#1576]
links are outdated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70fd385-ba68-efdb-f97e-4bfad385ff47
* Version Independent ID: d2fc5e69-77a3-9e97-0869-d2ea54be8e70
* Content: [SmartCard Class (Windows.Devices.SmartCards) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.smartcards.smartcard#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.smartcards.smartcard.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.smartcards.smartcard.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kb5ylg, and thanks for filing this issue. The link to the Smartcard sample application had a (case-sensitivity) typo in its url. I've published a fix to that (here and in several other topics), so I'll go ahead and close this issue.

Thanks again!
-Steve
