### ISSUE TITLE
the link for "Input sample" is obsolete

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/winrt-api#1577]
the link for "Input sample" is obsolete

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45c75856-4819-ab0e-3737-3cd1debe29b5
* Version Independent ID: fe05fdc6-38e0-6877-5332-45c84221e9ce
* Content: [Application.Suspending Event (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.suspending)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winui**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by QuinnRadich** [comment]
Thanks for your patience on this issue. I've removed the link to this Windows 8.1-era sample, and the page should be updated shortly.
