### ISSUE TITLE
Remarks are incorrect for Absolute mapping mode

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1581]
The remarks on this EllipseCenter, EllipseRadius, and GradientOriginOffset describe the property behavior when [CompositionGradientBrush.MappingMode](https://docs.microsoft.com/uwp/api/Windows.UI.Composition.CompositionGradientBrush.MappingMode) is set to [CompositionMappingMode.Relative](https://docs.microsoft.com/uwp/api/Windows.UI.Composition.CompositionMappingMode#fields). But if it's set to Absolute, the numbers change to be pixels rather than a ratio, and relative to the size of the brush.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a993e0fa-7216-87da-7bba-5b6496b4a206
* Version Independent ID: ba9c57f3-522a-1315-fb98-d7caa0dbf2dd
* Content: [CompositionRadialGradientBrush.EllipseCenter Property (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Composition.CompositionRadialGradientBrush.EllipseCenter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositionradialgradientbrush.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositionradialgradientbrush.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for pointing this out. The doc has been updated.
