### ISSUE TITLE
FindOrRegisterInstanceForKey throws an exception

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/winrt-api#1583]
The API doesn't even work.

```
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            var instance = AppInstance.FindOrRegisterInstanceForKey("mainApp");
```

That throws

```
System.Exception: 'The group or resource is not in the correct state to perform the requested operation.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03fa640c-506a-e67c-36c6-8e4307769dcf
* Version Independent ID: f58aa8e6-544c-75d8-465a-efdd2a4020c7
* Content: [AppInstance.FindOrRegisterInstanceForKey(String) Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appinstance.findorregisterinstanceforkey#Windows_ApplicationModel_AppInstance_FindOrRegisterInstanceForKey_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.appinstance.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.appinstance.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mikben**
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Closing this issue, as a fix for this was implemented before WinAppSDK 1.0 shipped.
