### ISSUE TITLE
Confusing naming, uncler purpose, can use more clarification

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1584]
This feature I feel is a significant part of the API and deserves a bit more than a single-liner for a description. As it is now it leaves reader guessing about what in the world is "VideoSurface" in "CopyFrameToVideoSurface", why it takes 3DSurface for "VideoSurface", and does not in fact take a simplier and more obtainable kind of container, which would make processing on the frames more available. Which appears to be the one reason anyone would ever want to copy the frames anywhere.
People online do apply CopyFrameToVideoSurface for getting frame bitmaps for their in-memory handling, but it demands an instance of Direct3DSurface, even if copied frames are never meant to be displayed, which for one, mixes up 3D concerns into media playback and two, means CopyFrameToVideoSurface is not intended for anything but preprocessing on the frames before they are displayed through tse same standard means.
Which then raises a question of _what would be_ the intended way for getting the video frames as software bitmaps for other purposes? There doesn't appear to be another suitable API in the MediaPlayer. There is MediaFrameSource but in the Capture namespace and there is no way to use it with Playback MediaSources. There is GetThumbnailAsync in the Editing namespace, and it also ends up horribly misused by confused programmers.
It can be understood if frame decoding _requires_ that they are put through the hardware, which is represented by 3DSurface, but I expect this to be communicated in the documentation. It is depressing and wrong that we users of the API are left to guess about things like this and figure them out on our own through trial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786d4005-31c4-c3db-254f-ca3d73f6e6b8
* Version Independent ID: 5ab659d7-e58c-11fa-3659-646b5f812500
* Content: [MediaPlayer.CopyFrameToVideoSurface Method (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.copyframetovideosurface)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Sorry for the delayed response. The scenario that CopyFrameToVideoSurface was designed to enable is using pixel shaders to modify video frames before they are displayed, as described in [Use MediaPlayer in frame server mode](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer#use-mediaplayer-in-frame-server-mode). I've added a link to this page from the CopyFrameToVideoSurface reference page. Software manipulation of video frames isn't performant enough for real-time playback scenarios, and therefore is not the intended use of this API. If you just want to get the frames as SoftwareBitmaps, I believe you could use [SoftwareBitmap.CreateCopyFromSurfaceAsync Method](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.softwarebitmap.createcopyfromsurfaceasync?view=winrt-20348).

For further questions, I recommend the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.
