### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1587]
"If the data is stored in a software bitmap, you can access it using the Direct3DSurface property" seem to be incorrect. Direct3DSurface and SoftwareBitmap appear to be the two separate ways of storing frame data that are not interchangeable. Bitmap is accessed with SoftwareBitmap when available, and surface is accesses with Direct3DSurface when available.
If that is not the case, and the bitmap really should also be obtainable through Direct3DSurface property, the article should probably just state that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff49d9c4-7b6e-6429-751b-be1aa5dda1f3
* Version Independent ID: 975c78f9-1c85-7246-f3dc-7ebed468fe60
* Content: [VideoFrame.SoftwareBitmap Property (Windows.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.videoframe.softwarebitmap#Windows_Media_VideoFrame_SoftwareBitmap)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.videoframe.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.videoframe.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for reporting this error. It appears this was a copy and paste error from the parallel Direct3DSurface property. The text has been updated: "If the data is stored in a Direct3D surface, you can access it using the Direct3DSurface property of the VideoFrame."
