### ISSUE TITLE
What is the session lifecycle?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1588]
Does the session instance associated with the player ever gets replaced? If it does, how does one handle that correctly? How do I know when the old instance is being replaced, so I install event handlers on the new one?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0d38525-a1b7-8147-93ab-e53bde9338df
* Version Independent ID: 7b3980eb-ad6e-8e81-fc1d-aba588e12c65
* Content: [MediaPlayer.PlaybackSession Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.playbacksession)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your question and sorry for the delayed response. I confirmed with the feature team that this is the behavior:

The PlaybackSession is created once inside the MediaPlayer’s RuntimeClassInitialize and it is the same for the life of the MediaPlayer object.
