### ISSUE TITLE
Necessary to release the instance before LockBuffer used again? Not mentioned.

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1589]
It is not immediately obvious that the BitmapBuffer instance represents a lock being held on a SoftwareBitmap buffer. It is worth at least mentioning that a reference should not be held indefinitely.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ef7195-34c0-a39c-80a1-2083247e0b24
* Version Independent ID: 707d9db5-c67b-9968-ecea-dbbb8866b5bc
* Content: [BitmapBuffer Class (Windows.Graphics.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.bitmapbuffer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.bitmapbuffer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.bitmapbuffer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for providing helpful feedback for the docs! I have added a callout that clients should not maintain a reference indefinitely: "Because the BitmapBuffer represents an exclusive lock on the associated bitmap, apps should not keep the reference to it indefinitely."
