### ISSUE TITLE
ContentIndexer class description is misleading

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-api#1592]
The class description of the ContentIndexer states that it enables adding content to the Windows index. However that sound a bit like it can be used by the Windows 10 search, which is not the case.

More context: https://github.com/microsoft/Xaml-Controls-Gallery/issues/395

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3027454-362b-b00b-e01d-bb21352b1cc0
* Version Independent ID: 55b263d6-95ce-1664-8fbd-78e1b3a6efe3
* Content: [ContentIndexer Class (Windows.Storage.Search) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.contentindexer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.contentindexer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.contentindexer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
