### ISSUE TITLE
How precise the seeking on a paused player supposed to be?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1595]
Is seeking subject to the same remark on accuracy? Should StepForward be used after Position is set while the player is paused, would it do any good? Something else that should be done?
I can't seem to seek to the very beginning for some of the videos. SeekCompleted event is fired as always, but the Position seem to be at one or two frames past 0. It is not clear if that is the intended behavior or a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a96fc0f6-3226-9c44-d5ff-b869d0f4b441
* Version Independent ID: b144f7b7-e19f-c924-323c-03b59a52a540
* Content: [MediaPlaybackSession.Position Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksession.position)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplaybacksession.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. I received the following response to your questions from the feature team:

Seeks are frame accurate, however, while scrubbing we will snap to key frames until the slider is released, then we finish with a frame accurate seek.

There is no need to call StepForward after setting the Position.  

Regarding the position not at 0…   With the MediaPlayer, after we seek to the desired position we display the frame and the clock advances by the duration of the frame.  It’s an artifact of getting data through MF’s pipeline and rendered.  I personally don’t like it, but MF was designed like that.

If you have further questions on this issue, the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.
