### ISSUE TITLE
URI is not linked to Windows.Foundation.Uri

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1596]
The URI type (and the related page) are not linking properly on this page. They are just text, not links to https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Uri.

These should be linked to Windows.Foundation.Uri for easy access.

I don't know if this issue is unique to this page or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d82229-84ce-fb8f-cdc1-87bcd01354dd
* Version Independent ID: 3e9fc2f0-d888-3438-ecfb-7a986d437276
* Content: [ProtocolActivatedEventArgs.Uri Property (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.protocolactivatedeventargs.uri#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.protocolactivatedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.protocolactivatedeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **mikben**
* Microsoft Alias: **mikben**

**Comment by MatchaMatch** [comment]
Thanks for the heads up, Ben. This has been fixed.
