### ISSUE TITLE
Purpose, behavor, intended usage unclear

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1598]
What is _the purpose_ of the frame server mode in the API? It sounds like an internal mode switch that would only have meaning to someone familiar with MedaiPlayer's inner function.
Is it the only thing the article mentions - to disable rendering of the content? Would not it be more logical to not bind the mediaplayer to a visual control in the first place when it is used as a frame server, rather than bind it and then disable the rendering?
Is CopyFrameToVideoSurface not intended to be used without frameserver enabled? Its documentation page makes no mention of any such dependency, and in my experiments I am able to copy the frames either way.
What are the details of the VideoFrameAvailable event operation? Are frames served at the rate they can be processed, or at the normal playback rate, or held back until after the one served is consumed?
What counts as "video content" that won't be rendered in a frameserver mode? Is audio a content of the video here, or only the visual frames? If the audio is to render, would it be played back in real time, or would it sync to the corresponding frames? At the moments they are served? At the moments they are copied?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b657ae4-1a89-0c77-8f1d-376928336991
* Version Independent ID: b0ad5a2f-2c4b-8648-a5fe-df295f705a3b
* Content: [MediaPlayer.IsVideoFrameServerEnabled Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.isvideoframeserverenabled)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, sorry for the delayed response to this issue. The core scenario for frame server mode is to allow apps to use pixel shaders to process video frames. It is not specifically disallowed to call CopyFrameToSurface without frameserver mode enabled, but it's an unsupported scenario and the behavior may be unpredictable. The VideoFrameAvailable function call just tells the caller if there is a frame available for the TransferVideoFrame. Once the TransferVideoFrame method is called then the VideoFrameAvailable will return false. Audio part is rendered on the audio device and the video frame that is available is A/V sync to that audio. If a video frame is not consumed by time a new frame is available then it is dropped.
