### ISSUE TITLE
Calling it will get an error: the request is not supported (exception from HResult: 0x80070032).

### ISSUE THREAD

**Issue by SuperDcer** [MicrosoftDocs/winrt-api#1601]
I can send the command to the controller through GipGameControllerProvider.SendMessage(GipMessageClass.Command, 0x09, buffer), but I get an error when I call GipGameControllerProvider.SendReceiveMessage: the request is not supported (exception from HResult: 0x80070032).

In addition, I noticed the [remark](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.custom?view=winrt-18362#remarks): "infact, no app should ever call these APIs directly", So how do I get the response message of Xbox one controller? 

This is the relevant link on Q&A: [How to communicate with Xbox one controller in uwp?](https://docs.microsoft.com/answers/questions/12731/how-to-communicate-with-xbox-one-controller-in-uwp.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6ee193b-04b0-743a-e996-e444f3a908d9
* Version Independent ID: a3a7558e-8287-d518-ad69-672325745a49
* Content: [GipGameControllerProvider.SendReceiveMessage(GipMessageClass, Byte, Byte\[\], Byte\[\]) Method (Windows.Gaming.Input.Custom) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.custom.gipgamecontrollerprovider.sendreceivemessage?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Gaming.Input.Custom/GipGameControllerProvider.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.Input.Custom/GipGameControllerProvider.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hkhmsft** [comment]
Hi @SuperDcer , thanks so much for submitting your feedback through Q&A. Unfortunately, product feedback and questions are not within our team's scope. If you find a solution through Q&A that you believe will be a useful addition to our documentation, please file a Pull Request or submit a new Issue to address it. Thanks and be well.
