### ISSUE TITLE
RC4 is a stream cipher algorithm, not a block cipher algorithm.

### ISSUE THREAD

**Issue by scottdsanders** [MicrosoftDocs/winrt-api#1602]
RC4 is a stream cipher algorithm, not a block cipher algorithm. Text needs update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddab69b8-4400-3816-2517-c100eb3bc4cd
* Version Independent ID: e453fece-d6fa-a358-1969-a69836d7cbed
* Content: [SymmetricAlgorithmNames.Rc4 Property (Windows.Security.Cryptography.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core.symmetricalgorithmnames.rc4?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.Security.Cryptography.Core/SymmetricAlgorithmNames.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Cryptography.Core/SymmetricAlgorithmNames.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
