### ISSUE TITLE
What zero means

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1604]
Based on empirical testing:

ReadTimeout = 0ms means "Wait forever for ALL bytes requested on a read operation".  It does not mean "Return immediately if no bytes available" as developers may be expecting/guessing/hoping.

If developers want a quick partial return of bytes, use ReadTimeout = 1ms.

HOWEVER... read calls always wait forever for the FIRST byte. The timeout only applies to any subsequent bytes. In my testing, trying to use a CancellationTokenSource with a timeout "works", but can leave the SerialDevice object in a dysfunctional state. My approach was to create a derived class that buffers data into a circular buffer using a background task. This allows the background task to block when waiting for the first byte without blocking other tasks. The class then has its own read methods which are serviced from the circular buffer.

While TimeSpan lets the caller specify fractions of milliseconds (ms), the underlying Windows calls only have millisecond resolution. So don't bother specifying a TimeSpan with fractions of milliseconds and expect it to have any meaning.

Since ReadTimeout questions often lead to WriteTimeout questions, I have not seem an empirical difference between WriteTimeout = 0ms and WriteTimeout = 1ms. However my application doesn't come anywhere near close to filling the write buffer before it starts waiting for read responses.  

Based on ReadTimeout, my guess would be WriteTimeout = 0ms means a write operation should wait forever for sufficient space in the driver's output buffer if it is full. WriteTimeout  = 1ms probably means to return promptly (after 1ms) if the driver's output buffer is full and cannot accept all the data from the write operation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64cd1f0e-b9f9-78b4-936f-7239ae21128a
* Version Independent ID: 32b282e1-0525-12d3-da26-cd666a5a41b5
* Content: [SerialDevice.ReadTimeout Property (Windows.Devices.SerialCommunication) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.serialcommunication.serialdevice.readtimeout?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Devices.SerialCommunication/SerialDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.SerialCommunication/SerialDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @kburgoyne, and thanks for filing this issue. I've updated the topic with more info, and that change is live now.

Thanks again!
Steve

**Comment by stevewhims** [comment]
@kburgoyne, FYI, I've added a link from this topic to content that describes the timeout value meanings in detail.

Thanks!
Steve

**Comment by kburgoyne** [comment]
@stevewhims, great add. Thanks!  Your approach is probably the quickest way to provide the information.

Having been a C++ embedded developer in the past with driver experience, I did at one point find my way to that WDK struct's doc and used it as a basis for my understanding. However, unfortunately there remains two magic pieces to the puzzle which could pretty much clear everything up completely.

The first is, which struct field is the .NET property mapping to?  There are three "read" timeout influencing fields in the struct. While developers can certainly try to make an assumption, an assumption is not knowing for sure and assumptions turn into "unknown variables" when something isn't working right.  ("Maybe I guessed wrong.")

The second magic puzzle piece would be how .NET sets/leaves the other two "read" fields.  One can "assume" perhaps they're left to default, but here again that's an "assumption" with the above mentioned pitfall.

I don't know if you're referencing the .NET code and can easily provide these answers. Just documenting which fields and what values are set is probably "good enough" for the .NET documentation.  Leaving the details of what those values mean to the WDK documentation.

I'm not overly familiar with which parts of which versions of the .NET API are open-source and available for examining on GitHub.  Is the source for this property available on GitHub for one or more of the .NET API variants? .NET Core?

**Comment by stevewhims** [comment]
Hi, @kburgoyne, the source for this property isn't available publicly. Note that this is a Windows Runtime API. While Windows Runtime APIs do enjoy being projected into the C# language, Windows Runtime APIs aren't .NET nor .NET Core APIs. The source code for Windows Runtime APIs isn't open sourced. I'll try and find answers to your other questions above, though!

**Comment by kburgoyne** [comment]
Ah, okay.  You have added to my education. :-)  Thanks.

**Comment by stevewhims** [comment]
I'll go ahead and close the now that it's resolved.

Thanks!
Steve
