### ISSUE TITLE
Confusing error handling procedures

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1606]
It says "will return an error" about ReadAsync, and WriteAsync. How would a method returning IAsyncOperationWithProgress return an "error"? What is "error" here? Its own documentation page makes no mention of any such thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 040dfa24-c42c-4492-7dad-b74bc874155f
* Version Independent ID: d2b3274a-9888-d8c8-0342-bda6371f4af0
* Content: [IRandomAccessStream.Seek(UInt64) Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.irandomaccessstream.seek?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Storage.Streams/IRandomAccessStream.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Streams/IRandomAccessStream.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
