### ISSUE TITLE
Fix hyperlink

### ISSUE THREAD

**Issue by keparanj** [MicrosoftDocs/winrt-api#1609]
The existing link to [ScopeOwner](https://docs.microsoft.com/en-us/uwp/api/keyboardaccelerator_scopeowner?view=winrt-18362) at the bottom of the page throws a 404. It may be replaced with https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.keyboardaccelerator.scopeowner?view=winrt-18362 (if that was the intended target)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5276572e-ea22-46ff-62a9-72833f552805
* Version Independent ID: d457bacd-7d32-fcee-ff17-d14271df40cf
* Content: [UIElement.KeyboardAccelerators Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.keyboardaccelerators?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been revised. Thanks!

**Comment by keparanj** [comment]
Is it? Still seeing the same link and the same 404
