### ISSUE TITLE
Docs inaccessible via Help Viewer?

### ISSUE THREAD

**Issue by ChristopherDrum** [MicrosoftDocs/winrt-api#161]
I've been searching and searching and cannot find a definitive answer to this issue. It is not specifically a winrt-api issue, but it is my inability to view these docs in the offline Help Viewer that raises the larger question. As I understand, MicrosoftDocs here on GitHub.com is the new hotness, but Help Viewer doesn't seem to understand this, because the list of "online resources" is quite short and non-comprehensive, nor does it seem to offer any method for connecting to the GitHub repo to subscribe to documentation sets.

I am brand new to Windows development (coming from macOS/iOS development on Xcode), wanting to start with the latest technology as my baseline moving forward (I have no legacy platform development needs). As I understand, Windows UWP app development via C# and the WinRT APIs is the Redmond-recommended platform moving forward. And yet, Visual Studio 2017 Help Viewer cannot provide the documentation contained in this repo.

Am I missing something? Is there a piece to this puzzle that connects Visual Studio offline documentation to these GitHub repos? Is Help Viewer deprecated in favor of these and a Markdown extension within VS2017? How can API lookups in VS2017 connect to their GitHub doc explanations?

**Comment by mattwojo** [comment]
Thanks for pointing this out @ChristopherDrum. It's a known issue and I'm going to try to connect with @mcleblanc to better understand the issue and try to provide an update here.

**Comment by mattwojo** [comment]
I know this is not at all an ideal temporary solution, but in the meantime you could click the "Download PDF" button the left side of the API Ref page (under the TOC) to use offline as a reference. Using "find" or the TOC to navigate the HUGE amount of pages.  I'll get an update back as soon as I can.

**Comment by ChristopherDrum** [comment]
I appreciate the response and look forward to seeing how things move from here. In the meantime, I'll do as you recommend, when I get a more robust internet connection at home (very soon).

**Comment by mcleblanc** [comment]
The UWP docs have been made available for offline download in Visual Studio Help Viewer.
