### ISSUE TITLE
Link to XAML User Input events sample is no longer valid

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1610]
This link `Input: XAML user input events sample` to https://go.microsoft.com/fwlink/p/?linkid=226855 is no longer valid and just dumps us to the search page. ☹

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 558306cf-3156-4a8d-e27b-b62f9541599c
* Version Independent ID: 6a866c18-3969-7df8-218f-377cf8eeebd5
* Content: [InputInjector.InjectKeyboardInput(IEnumerable&lt;InjectedInputKeyboardInfo&gt;) Method (Windows.UI.Input.Preview.Injection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.inputinjector.injectkeyboardinput?view=winrt-18362#Windows_UI_Input_Preview_Injection_InputInjector_InjectKeyboardInput_Windows_Foundation_Collections_IIterable_Windows_UI_Input_Preview_Injection_InjectedInputKeyboardInfo__)
* Content Source: [winrt-api-build/xml/Windows.UI.Input.Preview.Injection/InputInjector.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Input.Preview.Injection/InputInjector.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Links updated. Thanks.
