### ISSUE TITLE
Broken link on RawGameController Class page

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/winrt-api#1611]
Seems link generator is broken. 

From [text](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.gaming.input/rawgamecontroller.md):

```
You'll need to create these arrays yourself, and then populate them using [RawGameController.GetCurrentReading](rawgamecontroller_getcurrentreading_123740519.md) to determine the states of the buttons, switches, and axes. See that function's documentation for more information.
```

We [seeing](https://docs.microsoft.com/uwp/api/windows.gaming.input.rawgamecontroller):

```
You'll need to create these arrays yourself, and then populate them using @Windows.Gaming.Input.RawGameController.GetCurrentReading(System.Boolean[],Windows.Gaming.Input.GameControllerSwitchPosition[],System.Double[])?text=RawGameController.GetCurrentReading to determine the states of the buttons, switches, and axes. See that function's documentation for more information.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f5e496c-c0a9-afc7-52b4-d09e9c455bbc
* Version Independent ID: e3f9f626-343c-3c4a-7e06-f3cbd7dd6a5c
* Content: [RawGameController Class (Windows.Gaming.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.rawgamecontroller?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Gaming.Input/RawGameController.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.Input/RawGameController.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Topic has been revised. Thanks.

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft,  Link is still broken on that page:
![image](https://user-images.githubusercontent.com/1285934/82763223-badd0880-9e0e-11ea-8d0d-b4fcf13f3867.png)

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft issue with broken link is still present.

**Comment by Karl-Bridge-Microsoft** [comment]
@DJm00n - our engineering team identified a bug in our markdown rendering. A fix is underway and should correct this issue across many topics.
