### ISSUE TITLE
Windows.Devices.Printers

### ISSUE THREAD

**Issue by fielcabral** [MicrosoftDocs/winrt-api#1613]
Is there a namespace for ordinary laser/inkjet printers?
3D printers are niche while laser/inkjet printers are ubiquitous. Why did this top-level namespace go to 3D printers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81bb1c6b-edef-af2f-c815-9f7b092916e0
* Version Independent ID: f867068e-ec69-bd90-5660-c58233679113
* Content: [Windows.Devices.Printers Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.printers?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/ns-Windows.Devices.Printers.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Devices.Printers.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Printing-related types for printing from a UWP app to a traditional printer are in the Windows.Graphics.Printing and Windows.UI.Xaml.Printing namespaces. For more information, see [this article](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/print-from-your-app) and the other articles in this section.

I have passed your feedback on the naming of the Windows.Devices.Printers namespace (and its current use exclusively for 3D printing scenarios) to the product team.
