### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by JBradon** [MicrosoftDocs/winrt-api#1615]
I think the formatting of this page has gone wrong in two places. I think you meant to start a new paragraph at "An endpoint consists of two elements:" and at "An endpoint pair consists of two elements:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de852b2f-4035-a726-614c-31f670b6a803
* Version Independent ID: 0c4637c6-dc5d-4d91-b8f4-ac5f036dd403
* Content: [EndpointPair Class (Windows.Networking) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.endpointpair?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Networking/EndpointPair.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking/EndpointPair.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @JBradon, thanks for letting us know about this. This is now fixed, so I'll go ahead and close the issue.

-Steve
