### ISSUE TITLE
How do you use this property?

### ISSUE THREAD

**Issue by jandrewb** [MicrosoftDocs/winrt-api#1617]
The description for this field is ambiguous. What siblings is it talking about: folders? shell? I tried creating sync roots with the same provider ID, but it didn't put the other roots in as groups. 

When this property is true, it is not clear what to put in the Path property. Enabling this field seems to add a shell folder named after the root path's parent folder. This behavior does not appear to be documented. Can files be synced to this root along with the groups, or are only other sync roots supposed to be shown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ce3047-55b5-701a-fc1b-a08ee301e775
* Version Independent ID: e763d5bd-49a7-6a38-08c3-43d1654ceeea
* Content: [StorageProviderSyncRootInfo.ShowSiblingsAsGroup Property (Windows.Storage.Provider) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.storageprovidersyncrootinfo.showsiblingsasgroup?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.Storage.Provider/StorageProviderSyncRootInfo.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Provider/StorageProviderSyncRootInfo.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.

**Comment by kaidelorenzo** [comment]
My best guess about how this works is that it's a little bit of a hack. Essentially this is useful if there is a folder that contains sync roots. Then when registering all of those sync roots if you set ShowSiblingsAsGroup to true then they will be grouped together in file explorer. But I think it becomes buggy if the other sibling folders aren't sync roots or if there are random files in there too.

https://github.com/owncloud/client/issues/9821
