### ISSUE TITLE
See also section contains a duplicate link to ItemTemplateSelector

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1618]
There's a duplicate link in the See also list for the ItemTemplateSelector doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86cbc84f-1578-5874-584f-c70bc5a12db2
* Version Independent ID: a4782a0f-fe7d-dcec-7ac6-ecd9d0d8359d
* Content: [DataTemplateSelector Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.datatemplateselector?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.DataTemplateSelector);k(TargetFrameworkMoniker-.NETCore,Version%3Dv5.0);k(DevLang-csharp)%26rd%3Dtrue&view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/DataTemplateSelector.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/DataTemplateSelector.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. A fix has been submitted.
