### ISSUE TITLE
*Only* Windows 8.x Phone Apps?

### ISSUE THREAD

**Issue by druske** [MicrosoftDocs/winrt-api#1620]
There's a note on the Canceled event that says "For Windows Phone 8.x app, if the device becomes low on memory, background tasks may be terminated without any warning and without raising the OnCanceled event."

Does this apply *only* to Windows Phone 8.x, or might it apply to other Windows 10 IoT Core devices as well? It is unclear if this note was not updated as IoT Core became a platform for something other than a Windows Phone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9ee658-0c0e-eeea-ac8b-6e0d4966ef43
* Version Independent ID: b501247f-9017-2ab8-b206-c582a6ffcfb0
* Content: [IBackgroundTaskInstance Interface (Windows.ApplicationModel.Background) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.ibackgroundtaskinstance?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Background/IBackgroundTaskInstance.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Background/IBackgroundTaskInstance.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by MatchaMatch** [comment]
Hi! Thanks for submitting this issue. It does indeed apply only to Windows Phone; the docs have been updated with this clarification and should be live soon. Thanks again.
