### ISSUE TITLE
Broken link to: path

### ISSUE THREAD

**Issue by jandrewb** [MicrosoftDocs/winrt-api#1621]
The link to more info on 'path' is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87a82b5-133d-b6df-fc51-98a2f77a0d50
* Version Independent ID: d9b312de-c845-cb25-ff25-9c36a5d307dd
* Content: [StorageProviderSyncRootManager.Register(StorageProviderSyncRootInfo) Method (Windows.Storage.Provider) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.storageprovidersyncrootmanager.register?view=winrt-18362#Windows_Storage_Provider_StorageProviderSyncRootManager_Register_Windows_Storage_Provider_StorageProviderSyncRootInfo_)
* Content Source: [winrt-api-build/xml/Windows.Storage.Provider/StorageProviderSyncRootManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Provider/StorageProviderSyncRootManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks @jandrewb for pointing this out. The link has been fixed and the changes should be live within 24 hours.
