### ISSUE TITLE
C++/WinRT sample code

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/winrt-api#1623]
Would be nice if all the pieces of sample code changed to C++/WinRT when I select that in the language dropdown.

Currently all the samples remain in C#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4709c156-9a4d-80f0-4465-8061636a018d
* Version Independent ID: 30f6eda3-e38a-628d-e1ac-995879b33019
* Content: [TextBox Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/TextBox.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/TextBox.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @fman028, and thanks for filing this issue. You're right that choosing C++/WinRT from the filter works only if there actually are C++/WinRT versions of the code in the content (this is a case where there aren't). What I've tried to do is, whenever there was C++/CX but not C++/WinRT, to add a C++/WinRT version (over 500 of those). We haven't yet gotten around to adding C++/WinRT where there was (for example) only C#, but we are aware that that's the situation for a lot of topics. It's on our radar.

Thanks!
Steve

**Comment by fman028** [comment]
Makes sense.  Thanks for following up!
