### ISSUE TITLE
Append() seems like it should be Add()

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1624]
I'm using Windows.UI.Xaml.Media.PointCollection and Add() is for adding points.  VS is showing Append() as the System.Linq extension mention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4269af9e-0119-f07c-2dca-69429d2f97c2
* Version Independent ID: dcfe54ef-7b2b-c077-f344-5e7da77cf2a3
* Content: [PointCollection Class (Windows.UI.Xaml.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.pointcollection?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Media.PointCollection)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Media/PointCollection.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Media/PointCollection.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
There's a difference between the raw WinRT API and the .Net projection which the doc page doesn't explain. The WinRT API is Append, which comes from IVector&lt;T&gt;. But IVector&lt;T&gt; projects into C# as IList&lt;T&gt; (which derives from ICollection&lt;T&gt;), and so what C# sees on PointCollection is Add. Then coincidentally it also picks up an Append extension method from Enumerable.

**Comment by kburgoyne** [comment]
Thanks. That all makes sense. The docs page should still be adjusted in relation to .NET. I don't know how much of these docs pages are auto-generated.  In most cases, the more the better I assume.  I can see where auto-generated might periodically slip stuff through like this.

**Comment by drewbatgit** [comment]
Yes, the syntax blocks and parameter names for these APIs are auto-generated. We understand that some of these projection issues can be confusing (see also: Dispose/Close). Thanks for your feedback. This is currently a limitation of our publishing system, but we will certainly keep the confusion this issue causes in mind as we look to improve the doc experience.
