### ISSUE TITLE
Link to file picker sample is broken

### ISSUE THREAD

**Issue by kenrick95** [MicrosoftDocs/winrt-api#1626]
The [link to File Picker Sample](https://go.microsoft.com/fwlink/p/?linkid=234890) is set as `https://go.microsoft.com/fwlink/p/?linkid=234890` which just redirects to the main page of [Microsoft Docs Code Samples Browse page](https://docs.microsoft.com/en-us/samples/browse/?redirectedfrom=MSDN-samples). I believe one should update that go.microsoft.com redirection target to the [correct URL](https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/filepicker/). Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3098bacc-b9eb-3d19-047d-63b385fb8a42
* Version Independent ID: 60c88ad7-f216-256f-8d16-6e096a480770
* Content: [FolderPicker.PickSingleFolderAsync Method (Windows.Storage.Pickers) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker.picksinglefolderasync?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers/FolderPicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers/FolderPicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by metathinker** [comment]
I don't think the statement with the broken link is even relevant anymore. Here is the current version (the "File picker sample" link is still broken in the way you describe):

>  **Warning**
>
>If you try to show the file picker while your app is snapped the file picker will not be shown and an exception will be thrown. You can avoid this by making sure your app is not snapped or by unsnapping it before you call the file picker. The [FolderPicker](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker?view=winrt-18362) code examples and the [File picker sample](http://code.msdn.microsoft.com/windowsapps/File-picker-sample-9f294cba) show you how.

However, the whole concept of "snapping" an app was specific to Windows 8 and 8.1, and even the [oldest Windows 10 version of the file picker sample](https://github.com/microsoft/Windows-universal-samples/tree/714722f53c3ae270f634f54cb2740411f6b11032/Samples/FilePicker) (that I could find) lacks any code to handle the snapping problem.

Hence, it might be better to just delete the Warning statement entirely, or at least remove the links and make clear that the advice is for older versions.

**Comment by hkhmsft** [comment]
Thanks @kenrick95 for pointing this out and @metathinker for the note on snapping being specific to Windows 8 and 8.2. The remark section has been updated to specify this. Since snapping no longer applies, the links to the samples were removed from the remark.

The changes should be live within 24 hours. If there are any additional remarks you'd like for us to consider, feel free to re-open this thread!
