### ISSUE TITLE
ContentLink hyperlink throws 404

### ISSUE THREAD

**Issue by Kumara-Krishnan** [MicrosoftDocs/winrt-api#1627]
https://docs.microsoft.com/en-us/uwp/api/contentlink?view=winrt-18362 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88dfd57-d88d-f71f-493e-7effb3a7dde3
* Version Independent ID: eff9f4ba-a0a0-87cf-f0ec-bd150d75fb0c
* Content: [RichEditBox.ContentLinkProviders Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.richeditbox.contentlinkproviders?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/RichEditBox.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/RichEditBox.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The links have been fixed.
