### ISSUE TITLE
CoreDispatcher.RunAsync(CoreDispatcherPriority, DispatchedHandler) Method has CX not WinRT Examples

### ISSUE THREAD

**Issue by JosephMart** [MicrosoftDocs/winrt-api#1629]
Even though this page ends with the following support with `view=winrt-18362`

```
Applies to
WinRT
Build 18362 Build 17763 Build 17134 Build 16299 Build 15063 Build 14383 Build 10586 Build 10240
```
All the C++ sample code is C++/CX and not applicable to C++/WinRT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331adaef-1035-fd88-0d7b-ca4ff97ee761
* Version Independent ID: 173e41e3-b747-cf7b-9b43-3d678f21eacb
* Content: [CoreDispatcher.RunAsync(CoreDispatcherPriority, DispatchedHandler) Method (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.runasync?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Core/CoreDispatcher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Core/CoreDispatcher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @JosephMart, and thanks for filing this issue. If you scroll to the top of a reference topic, and look over to the right, there are Language, Bookmark, Feedback, Share affordances. Choose a language from the Language affordance. This particular topic has C++/WinRT and C++/CX (and C#) code examples.

Thanks!
Steve

**Comment by JosephMart** [comment]
My comment was more around how in the example, even with `C++/WinRT` selected, the `C++` example looks to be actually `C++/CX`
