### ISSUE TITLE
Web page is showing markdown instead of HTML

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1637]
![image](https://user-images.githubusercontent.com/18429489/80770385-06004600-8b05-11ea-8c0a-a6783f859b8f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0377d6ea-d3ca-628e-ba62-1b25e90449bb
* Version Independent ID: 281e9377-7c98-7163-31e2-995423d3217e
* Content: [Compositor.CreateEffectFactory Method (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Composition.Compositor.CreateEffectFactory?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/Compositor.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/Compositor.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This issue has been fixed. Thanks for reporting it.
