### ISSUE TITLE
It is unclear what a "vertical scroll rail" is

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1641]
I am reading about ScrollViewers and struggling to understand what `IsVerticalRailEnabled` does. What is "the vertical scroll rail"? What is the difference between this and `VerticalScrollBarVisibility`? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1ca63f-30ea-33d9-dc6f-01e5f9857a90
* Version Independent ID: f09eaad3-ecf9-62a2-b005-9cb94e67cd05
* Content: [ScrollViewer.IsVerticalRailEnabled Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer.isverticalrailenabled?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ScrollViewer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ScrollViewer.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@citelao, thanks for the feedback. This page has been updated with additional information that we hope will be helpful.

**Comment by citelao** [comment]
It is! Thanks!
