### ISSUE TITLE
IPropertySet threading requirements

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-api#1644]
Is IPropertySet thread-safe? Can it be queried/modified from different threads than the one it was created from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bced5e05-7272-b118-4fc0-584219f4e321
* Version Independent ID: 3ad00be0-7d2b-afb9-6b97-176b83dcc947
* Content: [IPropertySet Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Collections.IPropertySet?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IPropertySet.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IPropertySet.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by ChrisGuzak** [comment]
Yes, but one thing you will need to be aware of. Enumeration, given multi-thread use is unreliable as the enumerator will be invalidated by writers and generate **spurious** exceptions. `E_CHANGED_STATE` `0x8000000C`. IObservableMap::MapChanged has a similar problem and can't be used given multi-threaded use.

**Comment by hickeys** [comment]
Closing since this question has been answered
