### ISSUE TITLE
Size limit on InkCanvas

### ISSUE THREAD

**Issue by daljit97** [MicrosoftDocs/winrt-api#1646]
In the sample app Complex Ink (look here https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/ComplexInk/cpp/Scenario1_CustomDry.xaml.cpp), it is mentioned that: "InkCanvas has a limit for the content width/height to be no more than 2^21 physical pixels.". However, this is nowwhere to be seen in the documentation of this component. Can you please clarify what that comment mean and document the size limitations of InkCanvas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c7ad0c-5df6-0677-083c-fd15ed7fc3cf
* Version Independent ID: 38d461fa-136c-5eee-bd1c-6eec26d5ed16
* Content: [InkCanvas Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.inkcanvas?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/InkCanvas.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/InkCanvas.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
I've added this detail to the InkCanvas reference topic.
