### ISSUE TITLE
Search fails when both case and word provided

### ISSUE THREAD

**Issue by soumyamahunt** [MicrosoftDocs/winrt-api#1647]
FindOptions.Word | FindOptions.Case fails with 'Value does not fall within the expected range.' exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2472f33-5f76-46a3-8393-700aaebd4471
* Version Independent ID: 694a6386-e20c-be23-909b-78bd9181970f
* Content: [FindOptions Enum (Windows.UI.Text) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.findoptions?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Text/FindOptions.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Text/FindOptions.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @soumyamahunt, thanks for the feedback. As this is product feedback and not documentation feedback, I suggest you revisit the page and submit your feedback using the "This product" button. Your feedback should then be routed to the feature team for consideration.
