### ISSUE TITLE
BarcodeScanner with camera 

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-api#1648]
Does the BarcodeScanner require a physical barcode scanner device or can it be used with any regular webcam/camera?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3583b55-4a0a-ca81-f90e-1da3a81d0020
* Version Independent ID: eab8e968-e6b6-0daf-8141-661663879213
* Content: [BarcodeScanner Class (Windows.Devices.PointOfService) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.PointOfService.BarcodeScanner?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.Devices.PointOfService/BarcodeScanner.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.PointOfService/BarcodeScanner.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @asklar, I'm currently investigating to see whether there's a content opportunity. I've copied you in on the thread.

-Steve

**Comment by asklar** [comment]
@stevewhims thanks a bunch!

**Comment by stevewhims** [comment]
So, after an internal discussion, there was no ask for the content to be updated, although it looks like putting Alex in touch with the feature team will bear some good fruit there. So I'll go ahead and close out here. You can always respond to (or even re-open) a closed issue.

Thanks again!
Steve

**Comment by asklar** [comment]
Thanks a lot Steve!

Thanks,
-Alex
Want to debug CMD scripts? Now you can<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fosgwiki.com%2Fwiki%2FDebugging_CMD_batch_scripts&data=02%7C01%7Casklar%40microsoft.com%7C63a4d82b2ed84da97fe308d79a0bb4db%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637147247374602630&sdata=GLXAVzgBgrLin8INpPyNJc%2FrffITtXUPx34Ww8Uhi5k%3D&reserved=0>
