### ISSUE TITLE
Missing Exceptions

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1649]
Method presumably throws at least FileNotFoundException as well as other exceptions as GetFileFromPathAsync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e45b36a-c1e8-a517-e1f5-e23df745ca41
* Version Independent ID: 3ee24c0f-5e80-4bd6-f100-f6c17a4a2fce
* Content: [StorageFile.GetFileFromApplicationUriAsync(Uri) Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefromapplicationuriasync?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
