### ISSUE TITLE
Please be more explicit about how adding items to the list affects file access permission via paths

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-api#1651]
It is clear from the above that you can access files and folders added to the FutureAccessList by storing the token obtained/used when adding to the list, then calling `FutureAccessList.GetItemAsync(token)` to retrieve the storage item. However, it is not clear from the above how this affects the functions for retrieving storage items by path, i.e. `StorageFile.GetFileFromPathAsync(path)` and `StorageFolder.GetFolderFromPathAsync(path)`. According to my testing, if the storage item or one of its ancestor folders has been added to the FutureAccessList, then you can use these methods to retrieve the storage item from the path. Please can you clarify in the docs whether this is guaranteed behavior that you can rely on. I think it is because the error message you get when you try to access an item by a path that you don't have access to suggests that the error can be cured by adding the item to your FutureAccessList. It would be very helpful to know this for sure as it would be a significant simplification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1ef7e7c-2f41-624f-95bb-f6ad569fd83a
* Version Independent ID: 4a619d60-9419-38af-9704-392b83c419d2
* Content: [StorageItemAccessList Class (Windows.Storage.AccessCache) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.Storage.AccessCache/StorageItemAccessList.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.AccessCache/StorageItemAccessList.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
