### ISSUE TITLE
StorageFile.ContentType always return L"" in C++

### ISSUE THREAD

**Issue by giregk** [MicrosoftDocs/winrt-api#1652]
I am building a drag&drop drop element that must get jpg or png files only.

I get the StorageItem and convert it to StorageFile. If I debug my code, I see the StorageFile contains a ContentType equal to "image/jpeg" but when I try to access it, it always returns L"".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d4f50c-97b5-f2e8-47d2-d83016a4b069
* Version Independent ID: e9e1dd0d-6e2a-553c-19d9-7fa6b4066e52
* Content: [StorageFile.ContentType Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.contenttype?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @giregk , thanks for submitting your feedback. Could you post this in [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or through our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required)?

If you are able to get answers from there, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
