### ISSUE TITLE
What is BadgeNumericNotificationContent?

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/winrt-api#1655]
In the last C# sample the `BadgeNumericNotificationContent` type is used.  What is it?  I can't seem to find it documented anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45fa180-f2ae-0685-2368-6c1abc669313
* Version Independent ID: a797b1c2-2815-2446-5844-2a6255264942
* Content: [SecondaryTile Class (Windows.UI.StartScreen) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.startscreen.secondarytile?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.StartScreen/SecondaryTile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.StartScreen/SecondaryTile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@fman028, @hickeys, it looks like this is out of date. `BadgeNumericNotificationContent` is part of the [NotificationExtensions](https://docs.microsoft.com/en-us/previous-versions/windows/apps/dn642158(v=win.10)) library. A copy of the Windows 8 sample that is referred to in the NotificationsExtension article can be found at [App tiles and badges sample](https://github.com/microsoft/VCSamples/tree/master/VC2012Samples/Windows%208%20samples/C%2B%2B/Windows%208%20app%20samples/App%20tiles%20and%20badges%20sample%20(Windows%208)/C%23%2CC%2B%2B).

**Comment by fman028** [comment]
Ah I see, thanks for the fast response!

**Comment by hkhmsft** [comment]
Thanks @jwmsft for the speedy reply. @fman028 if you find anything else that might help improve our documentation, please come back and let us know.
