### ISSUE TITLE
Are endpoints of the returned ranges valid seeking positions?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1658]
It says seeking is allowed "in" the range. Is seeking to the Start (to 0) legal? Is seeking to the End value legal? The End is described as span from the beginning and technically its value is supposedly just past the end of a range (and past the end of playable data if it is the last range).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbb9a5f6-c965-24f3-b99b-1d0e590ee3ac
* Version Independent ID: 2893a429-df68-2251-5d21-c4dd4cdbd4c7
* Content: [MediaPlaybackSession.GetSeekableRanges Method (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacksession.getseekableranges?view=winrt-19041#Windows_Media_Playback_MediaPlaybackSession_GetSeekableRanges)
* Content Source: [winrt-api-build/xml/Windows.Media.Playback/MediaPlaybackSession.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Playback/MediaPlaybackSession.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Yes, seeking to the start and end of the seekable range is supported.

**Comment by avakhrushev** [comment]
Thanks. Will the page be updated too?
