### ISSUE TITLE
codeUnitCount or bytes?

### ISSUE THREAD

**Issue by pkar70** [MicrosoftDocs/winrt-api#1659]
"codeunit" in name of parameter suggest that it is code point (in UTF-8, it is anything from 1 to 6 bytes). But sample
`https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.Streams.DataReader?view=winrt-19041`
shows that this is not code points, but simple bytes. Could you correct (make clear) this documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9861a159-18c6-18c3-01b2-20ea67041fe4
* Version Independent ID: cc7c591a-88e4-780d-a10c-18b081502f7a
* Content: [DataReader.ReadString(UInt32) Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader.readstring?view=winrt-19041&source=docs#feedback)
* Content Source: [winrt-api-build/xml/Windows.Storage.Streams/DataReader.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Streams/DataReader.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
