### ISSUE TITLE
When to use API

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/winrt-api#1660]
What is the difference between this API and the GetThumbnailAsync() API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffbcc3f-1520-91b0-9551-9f0dfc6f9798
* Version Independent ID: 9cf8a05c-3bd6-1ea4-35a1-864d165ec285
* Content: [DeviceInformation.GetGlyphThumbnailAsync Method (Windows.Devices.Enumeration) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation.getglyphthumbnailasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I'm not an expert on this API, but based on some testing it appears that GetGlyphThumbnailAsync gets the built-in vector image for a given device, whereas GetThumbnailAsync displays the built-in bitmap image for the device. 

The [DeviceEnumerationAndPairing](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/DeviceEnumerationAndPairing) sample provides a good place to see this in action. If you run Scenario 1 in the app and select a device, the GetGlyphThumbnailAsync call in [this helper method](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/DeviceEnumerationAndPairing/cs/DisplayHelpers.cs#L281-L288) displays the glyph for the device. If you modify this call to GetThumbnailAsync instead, you can observe how the displayed image is different.

I hope this helps!
