### ISSUE TITLE
Windows.Media.Capture

### ISSUE THREAD

**Issue by aras61** [MicrosoftDocs/winrt-api#1661]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0ee7d59-98a5-f835-749d-12f9a0a24e98
* Version Independent ID: 27299429-b6cb-18a5-ec69-86aac4d53d57
* Content: [AdvancedCapturedPhoto Class (Windows.Media.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.advancedcapturedphoto?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Media.Capture/AdvancedCapturedPhoto.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Capture/AdvancedCapturedPhoto.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
No comment was supplied by the user. Closing.
