### ISSUE TITLE
The XamlDirect code sample is incorrect in #3

### ISSUE THREAD

**Issue by alvinashcraft** [MicrosoftDocs/winrt-api#1663]
The following XamlDirect API calls required an instance of XamlDirect. They are not static members.

XamlDirect.CreateInstance
XamlDirect.SetColorProperty
XamlDirect.SetXamlDirectObjectProperty
XamlDirect.SetDoubleProperty
XamlDirect.GetObject

You can create an instance at the beginning of the snippet like this:

XamlDirect xamlDirect = XamlDirect.GetDefault();

and then use the xamlDirect instance in those places in the rest of the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a339aa2b-8aa4-a87a-17f8-e48cff9c0011
* Version Independent ID: 8fa430de-7a18-f834-7335-99be7c789ad8
* Content: [Windows.UI.Xaml.Core.Direct Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.core.direct?view=winrt-19041&source=docs#feedback)
* Content Source: [winrt-api-build/xml/ns-Windows.UI.Xaml.Core.Direct.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.UI.Xaml.Core.Direct.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@alvinashcraft, thanks for letting us know about this. The code has been fixed.
