### ISSUE TITLE
Redundant links to TryFocusAsync

### ISSUE THREAD

**Issue by turekhe** [MicrosoftDocs/winrt-api#1664]
Under See also section, looks like below are redundant entries.

TryFocusAsync(DependencyObject, FocusState)
TryFocusAsync(DependencyObject, FocusState)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1c7085a-dd87-e518-0e5e-6035466bb4b8
* Version Independent ID: 9c8df148-d9a3-329a-dd18-2ccd0e851d34
* Content: [FocusMovementResult Class (Windows.UI.Xaml.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.focusmovementresult?view=winrt-19041#feedback)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Input/FocusMovementResult.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Input/FocusMovementResult.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @turekhe. The topic has been fixed.
