### ISSUE TITLE
Various broken links

### ISSUE THREAD

**Issue by cbialorucki** [MicrosoftDocs/winrt-api#1666]
Every code sample link on this page is broken, including:
-UI contrast and settings sample
-High contrast sample
-XAML requested theme sample
-Control and app styling in XAML sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c35d366c-df11-4893-f077-86683a841591
* Version Independent ID: 3b50b268-ebff-f4fb-f09f-cfca05ae6f78
* Content: [ResourceDictionary.ThemeDictionaries Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.resourcedictionary.themedictionaries?view=winrt-18362#feedback)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/ResourceDictionary.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/ResourceDictionary.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. These sample links were all fixed last year, and they should be working now in the article.
