### ISSUE TITLE
How to do negative changes using ColorAnimation.By?

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/winrt-api#1667]
`ColorAnimation` has a `By` field which allows you to configure animations in terms of changes rather than a fixed target color. However, `Color` has unsigned field, so I can't specify negative changes, only positive. What should I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00b867f-628d-e448-a7af-5e7f120fe50e
* Version Independent ID: 94839d35-9555-91c9-8d25-58710668483e
* Content: [ColorAnimation.By Property (Windows.UI.Xaml.Media.Animation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.animation.coloranimation.by?view=winrt-18362)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Media.Animation/ColorAnimation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Media.Animation/ColorAnimation.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by hkhmsft** [comment]
Hi @sylveon ! Could you submit your question on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or on our [forums](https://social.msdn.microsoft.com/Forums/newthreadcategory=windowsapps&forum=wpdevelop&prof=required)? The community of experts and Microsoft Engineers there will have answers to your question. If you do receive support through those channels, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

Feel free to re-open this thread or respond below for any follow-ups.
