### ISSUE TITLE
What should be returned for invalid URIs?

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/winrt-api#1668]
What should be returned for invalid URIs?
Strategies for handling unexpected URIs, and returning various objects including null should be discussed, if the documentation is to be called complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f098a39-16e2-68bf-bd12-edcd255da119
* Version Independent ID: aec4f68b-b364-36b4-2233-8ec24a4bed01
* Content: [IUriToStreamResolver.UriToStreamAsync(Uri) Method (Windows.Web) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.iuritostreamresolver.uritostreamasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Web/IUriToStreamResolver.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Web/IUriToStreamResolver.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @avakhrushev, and thanks for filing this issue. I'll check with the feature team about the recommendations for error conditions when implementing (and consuming) this interface. I'll report back here with results.

Thanks again!
Steve

**Comment by stevewhims** [comment]
UPDATE: I already reached out to some potential feature team contacts. I've pinged that thread again, asking for info.

-Steve

**Comment by stevewhims** [comment]
I have an update to the topic in the publishing pipeline. It's not live yet (as I write this comment), but here's the additional info that will appear in the topic when it's published (I'll keep an eye on it until it goes live):

## -returns

An asynchronous operation object from which, on successful completion, you can retrieve the content stream. If the *uri* argument is invalid, then the content stream is set to `null`.

**Comment by stevewhims** [comment]
That update is now live, so I'll go ahead and close the issue.
