### ISSUE TITLE
See also shows garbled characters

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-api#1671]
The See also section on this page shows garbled characters
![image](https://user-images.githubusercontent.com/22989529/83319899-22bc9600-a1f7-11ea-8dba-c2c6441dc964.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e51c4d4-3b95-4490-8d41-a3dd3af3495d
* Version Independent ID: f418d4da-3c97-3584-91b0-6b2b974bad7b
* Content: [XamlDirect.CreateInstance(XamlTypeIndex) Method (Windows.UI.Xaml.Core.Direct) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.core.direct.xamldirect.createinstance?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Core.Direct/XamlDirect.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Core.Direct/XamlDirect.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by asklar** [comment]
@jwmsft I see the source content is correct and has 2 links under See also, but the actual doc page has garbage data... How can I fix this?

**Comment by jwmsft** [comment]
@asklar, the build system for reference docs applies its own formatting for See Also links, so in the markdown it just wants a comma separated list of links, like this:

`[XamlDirect](xamldirect.md), [XamlDirect.GetDefault](xamldirect_getdefault_846721868.md)`

The markdown was formatted as a bulleted list, which was breaking the formatting in the build system. I've submitted an update for the markdown on this page.
