### ISSUE TITLE
Windows.Data.Json not found

### ISSUE THREAD

**Issue by klong15** [MicrosoftDocs/winrt-api#1672]
I try to use this namespace, and Visual Studio tells me that "Windows::Data has no member Json"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684c2bb8-b08e-27a5-633a-f553e29b3045
* Version Independent ID: a60e9ab7-fa31-45d6-13d2-1c67c960ce13
* Content: [JsonObject.GetNamedBoolean Method (Windows.Data.Json) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonobject.getnamedboolean?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Data.Json/JsonObject.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Data.Json/JsonObject.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Are you trying to use this namespace in a C++/WinRT project? If so, you'll need to add the following line to the pch.h file in your project (or whatever other header file contains all the WinRT header includes):

`#include <winrt/Windows.Data.Json.h>`

For more details, see the [C++/WinRT quick start](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started#a-cwinrt-quick-start). 

If this did not address the issue you're encountering, please reopen this issue with more details. Thanks!
