### ISSUE TITLE
 Should that be "AES_GCM"?

### ISSUE THREAD

**Issue by rlaf99** [MicrosoftDocs/winrt-api#1676]
[Enter feedback here]

Regarding 

> Retrieves a string that contains "AES_CCM".

Should that be "AES_GCM"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d74ecf-81e8-957f-4112-c25b619ce264
* Version Independent ID: f9ef2708-ac9e-3075-d67e-dc6c7954b726
* Content: [SymmetricAlgorithmNames.AesGcm Property (Windows.Security.Cryptography.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core.symmetricalgorithmnames.aesgcm?view=winrt-19041#Windows_Security_Cryptography_Core_SymmetricAlgorithmNames_AesGcm)
* Content Source: [winrt-api-build/xml/Windows.Security.Cryptography.Core/SymmetricAlgorithmNames.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Cryptography.Core/SymmetricAlgorithmNames.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
