### ISSUE TITLE
CardType Needs an Explanation for what the uint Value Represents

### ISSUE THREAD

**Issue by jtbrower** [MicrosoftDocs/winrt-api#1681]
I am curious what the CardType value maps to.  There are a lot of assumptions that could be made here, for example; Card Brand like Visa, MasterCard, Amex or PrePaid vs Ebt and etc.  I would  like to know what each of the uint values represents or maybe an ISO or spec that the CardType represents so I can visit that spec to get the valid values.   

Thank you,

Jason

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8addb98d-0adf-26df-8dfc-eb0f499d32bb
* Version Independent ID: f59678b4-30e0-6650-56ac-274e976af745
* Content: [MagneticStripeReaderReport.CardType Property (Windows.Devices.PointOfService) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.magneticstripereaderreport.cardtype?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.PointOfService/MagneticStripeReaderReport.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.PointOfService/MagneticStripeReaderReport.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @jtbrower, I've reached out to the product team for info and advice. I'll report progress here.

Thanks!
Steve

**Comment by jtbrower** [comment]
@stevewhims thank you for the prompt response!

**Comment by stevewhims** [comment]
I've added some info to the topic (to the description in the "Property value" section). That change is now live.

-Steve

**Comment by jtbrower** [comment]
Thanks.  I read it as follows "The CardType property value indicates whether the card's type is American Association of Motor Vehicle Administrators (AAMVA), Bank, ExtendedBase (vendor-specific), or is not known."  This is good information.  Now I am still curious how those types map to a value.  Since the CardType is an unsigned int, it will start counting at 0.  What I am looking for is how the integer value maps to the types you provided.  For example, does the value of "0" map to AAMVA and 1 to Bank and 2 to ExtendedBase?  I make that assumption because when I run a bank card against the API, I get a CardType value of 1.

**Comment by stevewhims** [comment]
Hi, @jtbrower! The four properties of the **MagneticStripeReaderCardTypes** class each returns a unique unsigned int value. As I understand it, the value of the **CardType** property will match the value returned by one of those properties.

-Steve

**Comment by jtbrower** [comment]
@stevewhims  ok, thank you.  I am guessing they avoided using an enumeration in an attempt to leave the implementation loosely coupled.  Thanks for the update.

**Comment by stevewhims** [comment]
Yes, I don't know why the CardType property isn't an enum; that'd be the standard pattern. :) Thanks, I'll go ahead and close the issue.

Thanks!
Steve
