### ISSUE TITLE
Need to handle Close App event in c++winrt

### ISSUE THREAD

**Issue by kmelligeri** [MicrosoftDocs/winrt-api#1682]
Need help on how to use CloseRequested in C++/Winrt program. Any pointers to working example would be really helpful.

Regards,
Kuldeep
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd653644-7246-93a2-5fb1-035c487d548b
* Version Independent ID: 0bc615cc-1401-a197-2454-e35bf1d256e0
* Content: [SystemNavigationManagerPreview.CloseRequested Event (Windows.UI.Core.Preview) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.preview.systemnavigationmanagerpreview.closerequested?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Core.Preview/SystemNavigationManagerPreview.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Core.Preview/SystemNavigationManagerPreview.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by stevewhims** [comment]
Thanks, @kuldeepmelligeri, and sorry about the long delay in responding.

For this, I'd suggest taking a look at [Handle events by using delegates in C++/WinRT](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events).

If you have this working in C# and want to port it to C++/WinRT, then we have resources such as the [C++/WinRT](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/) content in general, and then the [Porting the Clipboard sample to C++/WinRT from C#—a case study](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp) and [Move to C++/WinRT from C#](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp) topics in particular.

So I'll close this issue for now.

-Steve
