### ISSUE TITLE
Missing Closing Tag in Example

### ISSUE THREAD

**Issue by h45h74x** [MicrosoftDocs/winrt-api#1683]
Missing closing tag for <TreeView.ItemTemplate> in the XAML Codeblock in 'Examples'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9904e8f2-4d99-d0f6-9d86-637fbf280de6
* Version Independent ID: f8931355-6c5f-188e-d2aa-00f6475b2865
* Content: [TreeView.ItemTemplate Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.itemtemplate?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/TreeView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/TreeView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The sample is fixed.
