### ISSUE TITLE
2nd paragraph contains raw HTML

### ISSUE THREAD

**Issue by artemious7** [MicrosoftDocs/winrt-api#1687]
2nd paragraph says: 

`This enumeration has a <a href="https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute">FlagsAttribute</a> attribute that allows a bitwise combination of its member values.`

it should not use HTML code for link to "FlagsAttribute" page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71e30e65-537f-0c95-7b5d-e5c08f4c69ec
* Version Independent ID: ad8154d1-0d08-11f6-e6d5-03965203856c
* Content: [VirtualKeyModifiers Enum (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkeymodifiers?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System/VirtualKeyModifiers.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/VirtualKeyModifiers.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
This issue seems to have been resolved between the time you opened this issue and now. Since everything seems correct, I'm going to close this issue. If there is still a problem on this page, please reopen with a comment, or log a new issue.

Thanks,
Shawn
