### ISSUE TITLE
XAML Navigation Sample Link Broken

### ISSUE THREAD

**Issue by kevinguo305** [MicrosoftDocs/winrt-api#1688]
When I click XAML Navigation Sample link (located both in the "see also" section as well as the paragraph right under three large code chunks), it takes me to a broken page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ab8deaa-aa73-acd1-2c7f-014117432620
* Version Independent ID: 06fe8724-00a9-ff83-ceed-4969dc9f88e0
* Content: [Frame Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame?view=winrt-19041#see-also)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Frame.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Frame.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this issue. The link has been fixed.
