### ISSUE TITLE
Closed caption font size

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/winrt-api#1691]
Currently `Windows.Media.ClosedCaptioning` returns a enum called `ClosedCaptionSize`, which has a few enums.
![image](https://user-images.githubusercontent.com/14960168/84479513-a7aeb180-acc5-11ea-85f0-5d4cdcf81706.png)

But how to know the final rendered font size, we are creating a second CC, the same font size to systems.

Is there any documents related?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819b1afb-adee-ccf8-f124-5986fe96f76d
* Version Independent ID: 3bcb0824-cd6c-9f83-216b-25c936e2cffe
* Content: [ClosedCaptionSize Enum (Windows.Media.ClosedCaptioning) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.closedcaptioning.closedcaptionsize?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Media.ClosedCaptioning/ClosedCaptionSize.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.ClosedCaptioning/ClosedCaptionSize.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your question. I was able to get this information around the render size of closed captions:

The percentage closed caption size is relative to default size.
The default size is decoded from the closed caption stream, the unit is pixel or percentage of screen.  
If the original closed caption stream does not specify closed caption default size, the render will set the height to 5% of the screen (each line).

**Comment by hupo376787** [comment]
Hi @drewbatgit , in the second condition, if screen resolution is 1920 x 1080, then the line height is 1080 * 5% = 54.
Is there any formula that can convert 54 to font size?
Thx.
