### ISSUE TITLE
CompositionScopedBatch points to page that has no info about them for more information

### ISSUE THREAD

**Issue by arcadiogarcia** [MicrosoftDocs/winrt-api#1694]
This page says 

> See Composition Animations Overview for more information on composition batches.

However, that page (https://docs.microsoft.com/en-us/windows/uwp/composition/composition-animation) doesn't mention composition batches at all. The composition animation page should mention composition batches or the link should point somewhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f045c6a-0545-69ed-33cb-37d4081645c8
* Version Independent ID: 71e340bc-53dd-4b01-863e-18c0b852b528
* Content: [CompositionScopedBatch Class (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionscopedbatch?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/CompositionScopedBatch.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/CompositionScopedBatch.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@arcadiogarcia, thanks for this feedback. The Composition Animation Overview was re-written some time ago, and as you noticed, the scoped batch information was removed. I've opened a work item to add the missing information to the CompositionScopedBatch class in place of the link. In the meantime, you can see the scoped batch information in the old version of the article in the GitHub repo: https://github.com/MicrosoftDocs/windows-uwp/blob/a3c1d555e95992666974de5d62b0d5ff440030e7/windows-apps-src/composition/composition-animation.md
