### ISSUE TITLE
Link to Touch injection sample is broken

### ISSUE THREAD

**Issue by jevansaks** [MicrosoftDocs/winrt-api#1695]
It redirects to some samples root page but doesn't deep link to the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 004b0f01-9864-050a-ad6b-ebdd77784430
* Version Independent ID: b3363423-4779-139c-0369-d5428f0692fb
* Content: [InjectedInputPointerInfo Struct (Windows.UI.Input.Preview.Injection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.injectedinputpointerinfo?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Input.Preview.Injection/InjectedInputPointerInfo.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Input.Preview.Injection/InjectedInputPointerInfo.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @jevansaks - there's a PR already underway to fix this: https://cpubwin.visualstudio.com/windows-uwp/_git/winrt-api/pullrequest/16614?_a=files&path=%2Fwindows.ui.input.preview.injection%2Finjectedinputpointerinfo.md
