### ISSUE TITLE
LauncherOptions.TargetApplicationPackageFamily isn't always optional

### ISSUE THREAD

**Issue by jbrianceau** [MicrosoftDocs/winrt-api#1696]
Doc states that `LauncherOptions.TargetApplicationPackageFamily` is optional, which is not entirely true.

`LauncherOptions.TargetApplicationPackageFamily` seems to be mandatory when using [LaunchUriAsync(Uri, LauncherOptions, ValueSet)](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher.launchuriasync?view=winrt-19041#Windows_System_Launcher_LaunchUriAsync_Windows_Foundation_Uri_Windows_System_LauncherOptions_Windows_Foundation_Collections_ValueSet_) method with input data.

Here's the behavior that I can see:
- the following code snippet without input data and without PFN works fine:
```
Uri^ uri = ref new Uri(L"protocol://uri");
auto launcherOptions = ref new Windows::System::LauncherOptions();
Windows::System::Launcher::LaunchUriAsync(uri, launcherOptions);
```
- the following code snippet with input data but without PFN throws `Platform::InvalidArgumentException^ (HRESULT:0x80070057 The parameter is incorrect. WinRT information : options.TargetApplicationPackageFamilyName)`:
```
Uri^ uri = ref new Uri(L"protocol://uri");
auto launcherOptions = ref new Windows::System::LauncherOptions();
auto valueSet = ref new Windows::Foundation::Collections::ValueSet();
valueSet->Insert(L"SomeData", L"SomeValue");
Windows::System::Launcher::LaunchUriAsync(uri, launcherOptions, valueSet);
```
- the following code snippet with both input data and PFN works fine:
```
Uri^ uri = ref new Uri(L"protocol://uri");
auto launcherOptions = ref new Windows::System::LauncherOptions();
launcherOptions->TargetApplicationPackageFamilyName = L"<a_valid_PFN>";
auto valueSet = ref new Windows::Foundation::Collections::ValueSet();
valueSet->Insert(L"SomeData", L"SomeValue");
Windows::System::Launcher::LaunchUriAsync(uri, launcherOptions, valueSet);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ff12cee-d588-9e46-2d5e-844dbe6f711a
* Version Independent ID: 2f14a1b3-c1f5-6dbd-4675-aceff296cfa0
* Content: [LauncherOptions.TargetApplicationPackageFamilyName Property (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcheroptions.targetapplicationpackagefamilyname?view=winrt-19041#Windows_System_LauncherOptions_TargetApplicationPackageFamilyName)
* Content Source: [winrt-api-build/xml/Windows.System/LauncherOptions.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/LauncherOptions.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal PR to incorporate your suggestions. The changes have been merged and should be live soon, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
