### ISSUE TITLE
ApplicationView.GetForCurrentView crashes if called in app's constructor

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/winrt-api#1698]
We should add a note that this can only be called after the `CoreWindow` has been constructed, which seems to happen _after_ the App object gets constructed, so it is not safe to call `ApplicationView.GetForCurrentView` in an app's constructor. Instead the call should be deferred until `Application.OnLaunched`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3efb4687-7b0e-5315-a943-73c1b7863525
* Version Independent ID: 3a23814d-3277-c86e-5071-bb0b2b45b31d
* Content: [ApplicationView.GetForCurrentView Method (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.getforcurrentview?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.ViewManagement/ApplicationView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.ViewManagement/ApplicationView.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by jwmsft** [comment]
Thanks for pointing this out. The doc has been updated with a caution note about this.
