### ISSUE TITLE
Inherited Members section is an overwhelming unstructured list

### ISSUE THREAD

**Issue by peterfoot** [MicrosoftDocs/winrt-api#17]
![docs-inherited-members](https://cloud.githubusercontent.com/assets/3985053/23330503/21e6cbc4-fb47-11e6-9b20-d51311511095.png)

The attached screenshot shows the inherited members for the Windows.UI.Xaml.Controls.Button class. It's impossible to work with because it's just an unstructured list. It's missing information on which class in the hierarchy each member comes from.
The old style documentation listed all members within fields, properties, methods and events and showed "Inherited from UIElement" for example and the hyperlinks went through to the correct type.

**Comment by kevinyr** [comment]
Hi Peter, we're working to get the inherited members to display as they did in the past. No firm ETA yet, but  we are working on this change.

**Comment by kevinyr** [comment]
This is still being worked on and we hope to resolve it soon.

**Comment by kevinyr** [comment]
Progress is being made on resolving this issue. We should the improvement rolled out in the next 30 days.

**Comment by mattwojo** [comment]
Hey @kevinyr - is this issue resolution still in the works? 
>> https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button

**Comment by kgoyena** [comment]
We thought we would have a fix a couple months ago, but that fix did not work as expected so we're still working to improve the rendering of inherited members.

**Comment by kevinyr** [comment]
This was resolved some time ago. See https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button today.
