### ISSUE TITLE
<StackPanel Spacing="double"/> return error

### ISSUE THREAD

**Issue by Tom60chat** [MicrosoftDocs/winrt-api#1703]
Using this:
<StackPanel Spacing="double"/>
on
<StackPanel x:Name="NavigationList" HorizontalAlignment="Left" Width="450" Padding="50,50,50,50" Spacing="double" >
Return error (invalide property for "Spacing" : "double")

UWP project

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7b3f1503-301b-c711-0164-3285ea966ab1
* Version Independent ID: d0d852ae-e725-d699-def2-17a67280fd59
* Content: [StackPanel.Spacing Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/fr-fr/uwp/api/windows.ui.xaml.controls.stackpanel.spacing?view=winrt-19041#Windows_UI_Xaml_Controls_StackPanel_Spacing)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/StackPanel.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/StackPanel.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
In the syntax block, _"double"_ is a placeholder for a value of type [Double](https://docs.microsoft.com/en-us/dotnet/api/system.double). You need to enter a Double value in your XAML, like `Spacing="100.00"`.
