### ISSUE TITLE
AppCapability.Create: No explanation of valid capabilityName string values

### ISSUE THREAD

**Issue by kasumman** [MicrosoftDocs/winrt-api#1705]
AppCapability.Create(String) Method
should have link to https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations and explanation to use these capability names as string values to create AppCapability object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a9ffe3-3b6a-f087-080d-b06c9e24435d
* Version Independent ID: 67c5b36b-1c84-af6c-0489-ffe496f78192
* Content: [AppCapability.Create(String) Method (Windows.Security.Authorization.AppCapabilityAccess) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.authorization.appcapabilityaccess.appcapability.create?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Security.Authorization.AppCapabilityAccess/AppCapability.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Authorization.AppCapabilityAccess/AppCapability.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by alvinjiooo** [comment]
Have the same question here, it will be great to have more clear instructions on how to specify `capabilityName`

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
