### ISSUE TITLE
See also link on DataTemplate.RecycleElement page is not working

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-api#1707]
See screenshot:
![image](https://user-images.githubusercontent.com/16122379/85706995-0f5ff600-b6e3-11ea-98ff-62692299cd01.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45c20d66-c39f-10f1-7760-81de361b8e72
* Version Independent ID: 870de29e-d3af-f4bf-7dd9-855b4a660909
* Content: [DataTemplate.RecycleElement(ElementFactoryRecycleArgs) Method (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.datatemplate.recycleelement?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/DataTemplate.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/DataTemplate.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. The see also links are fixed now.
