### ISSUE TITLE
AccountSettingsPane does document its interop interface, IAccountsSettingsPaneInterop

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-api#1709]
Win32 applications, and AppWindow based UWA applications, need to use the interop interface to use this API. But sadly it is not mentioned in the [AccountSettingsPane docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.applicationsettings.accountssettingspane?view=winrt-19041).

This interop interface is defined in `accountssettingspaneinterop.h` and follows the same pattern as other already documented interop interfaces like [IInputPaneInterop](https://docs.microsoft.com/en-us/windows/win32/api/inputpaneinterop/nn-inputpaneinterop-iinputpaneinterop) and [IWebAuthenticationCoreManagerInterop](https://docs.microsoft.com/en-us/windows/win32/api/webauthenticationcoremanagerinterop/nn-webauthenticationcoremanagerinterop-iwebauthenticationcoremanagerinterop).

At a minimum we should mention this so readers know where to start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81e13d93-c630-7320-d940-62feff9341e0
* Version Independent ID: ee61a773-9a36-9fdc-c916-015a126c9e13
* Content: [AccountsSettingsPane Class (Windows.UI.ApplicationSettings) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.applicationsettings.accountssettingspane?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.ApplicationSettings/AccountsSettingsPane.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.ApplicationSettings/AccountsSettingsPane.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
This issue was resolved with an update to https://learn.microsoft.com/en-us/uwp/api/windows.ui.applicationsettings.accountssettingspane that mentions the interop requirements.
