### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by matthew25187** [MicrosoftDocs/winrt-api#1711]
Why is there no mention on this page of the following properties?
MenuItemsSource, IsExpanded, IsChildSelected, HasUnrealizedChildren, MenuItems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3dc936-1d10-43cf-1503-d8661817ed7d
* Version Independent ID: cd1f2c7c-190e-1e03-3c2f-09492cb1bf26
* Content: [NavigationViewItem Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationviewitem?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/NavigationViewItem.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/NavigationViewItem.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@matthew25187, the latest updates to NavigationView are being made only in the [WinUI](https://docs.microsoft.com/windows/apps/winui/winui2/) version of the control. You will find these new properties in the [WinUI API reference](https://docs.microsoft.com/uwp/api/microsoft.ui.xaml.controls.navigationviewitem). We'll update the docs to make that more clear. Thanks for the feedback.
