### ISSUE TITLE
Does OpenAsync throws an exception?

### ISSUE THREAD

**Issue by LokiMidgard** [MicrosoftDocs/winrt-api#1714]
I would  assume that `OpenAsync` throws an exception if the File is already locked. It would be nice to document it. And if it does not throw an exception the behavior should be described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0697177-bf2e-c80c-6429-14bb7fa766ae
* Version Independent ID: 44281fdb-8458-77a5-3b97-880abe067806
* Content: [StorageFile.OpenAsync Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.openasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.StorageFile.OpenAsync);k(TargetFrameworkMoniker-.NETCore,Version%3Dv5.0);k(DevLang-csharp)%26rd%3Dtrue&view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
