### ISSUE TITLE
IMap<>::Lookup should return E_BOUNDS when the value is not found

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-api#1719]
This should be documented. Some implementations get this wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b0d5b5-7c9e-831a-5a88-d1947cc09b70
* Version Independent ID: 33b08792-7c66-6ea7-e2fa-ccaa44f3b4e3
* Content: [IMap&lt;K,V&gt;.Lookup(K) Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.imap-2.lookup?view=winrt-19041&source=docs)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IMap`2.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IMap`2.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Just merged this change in. It should publish in the next few hours.
