### ISSUE TITLE
Size property appears to be Count in C#

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#1721]
Size property appears to be Count in C#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df933017-c173-028d-4818-f720ef50805d
* Version Independent ID: 6e49eef9-aa31-539b-b486-4d86ede8a1a9
* Content: [MediaPlaybackAudioTrackList Class (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybackaudiotracklist?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Media.Playback.MediaPlaybackAudioTrackList)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=winrt-19041#properties)
* Content Source: [winrt-api-build/xml/Windows.Media.Playback/MediaPlaybackAudioTrackList.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Playback/MediaPlaybackAudioTrackList.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by MikeHillberg** [comment]
All the WinRT classes that implement IIterable, IVector, etc, need to have their generated sections updated to honor the language setting.  On this page it also says that the class implements IReadOnlyCollection in the c++/winrt view, but really it only implements that interface in the c# projection, in the c++/winrt projection it implements IVectorView.
