### ISSUE TITLE
No documentation about the argument for TryChangePlaybackPositionAsync

### ISSUE THREAD

**Issue by laishiekai** [MicrosoftDocs/winrt-api#1725]
[Enter feedback here]

There is no documentation about what unit is the argument. Seconds? Milliseconds? Also, right now whenever I call this function for Movies & TV app, it will go back to the beginning for me. For Spotify app, it does nothing. (But still return true)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb9125e3-1cbe-ead0-c0bc-ae69d2475319
* Version Independent ID: 8fcd8ae4-0e1c-e1f5-6194-1591235db307
* Content: [GlobalSystemMediaTransportControlsSession.TryChangePlaybackPositionAsync(Int64) Method (Windows.Media.Control) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssession.trychangeplaybackpositionasync?view=winrt-19041#Windows_Media_Control_GlobalSystemMediaTransportControlsSession_TryChangePlaybackPositionAsync_System_Int64_)
* Content Source: [winrt-api-build/xml/Windows.Media.Control/GlobalSystemMediaTransportControlsSession.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Control/GlobalSystemMediaTransportControlsSession.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by ShankarBUS** [comment]
Yes please!

The same happens to me too!
It returns true every single time but the position is unchanged sometimes or goes back to 0 sometimes.

@laishiekai,

Did you find any workarounds?
I haven't found anything useful after about 4 months of searching.

Please notify me if you find or know the solution 🙏.

**Comment by prakharb5** [comment]
This issue really needs to be looked upon and be fixed.

**Comment by laishiekai** [comment]
> Yes please!
> 
> The same happens to me too!
> It returns true every single time but the position is unchanged sometimes or goes back to 0 sometimes.
> 
> @laishiekai,
> 
> Did you find any workarounds?
> I haven't found anything useful after about 4 months of searching.
> 
> Please notify me if you find or know the solution 🙏.

No, I didn't. Currently we are not using this function.

**Comment by ShankarBUS** [comment]
> No, I didn't. Currently we are not using this function.

That's sad 😢.

I will inform you once/iff I find any workarounds for this issue.

**Comment by ShankarBUS** [comment]
Found the solution!

It works fine if you pass the ticks.

https://www.kapwing.com/videos/5fdbc6fe7a1b37003e7d5e1e

**Comment by MikeHillberg** [comment]
This is typed as an Int64, but I believe it's really a TimeSpan (which is really just an Int64), and corresponds to the [SystemMediaTransportControls.PlaybackPositionChangeRequested](https://docs.microsoft.com/uwp/api/Windows.Media.SystemMediaTransportControls.PlaybackPositionChangeRequested) event, which provides the TimeSpan in its args.

**Comment by ShankarBUS** [comment]
@MikeHillberg,

Did you see the video mate?

We have to pass in a `TimeSpan`'s `Ticks` property!

I demonstrated the functioning of the API using my app.

Please take a look at it.

https://www.kapwing.com/videos/5fdbc6fe7a1b37003e7d5e1e

The API have no problems. It works all right.

You just need to update the documentation to denote that the method accepts playback position in **"ticks"**.

**Comment by drewbatgit** [comment]
Thanks for helping to make our docs more complete and accurate. I made a test app and confirmed that the value should be specified in ticks, and I updated the article to specify that the units are ticks.

**Comment by ShankarBUS** [comment]
Thanks a lot @drewbatgit!

I am happy that we helped each other!

Is the updated document out yet?
