### ISSUE TITLE
PointerPointProperties HasUsage table is not displayed

### ISSUE THREAD

**Issue by vladfratila** [MicrosoftDocs/winrt-api#173]
The HID usages table from https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.input/pointerpointproperties_hasusage_907430020.md#-remarks is not rendered correctly. See screenshot from https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerpointproperties#Windows_UI_Input_PointerPointProperties_HasUsage_System_UInt32_System_UInt32_:
![capture](https://user-images.githubusercontent.com/4214981/30849878-79fa9c70-a2ac-11e7-8a8b-e18c91489959.PNG)

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for notifying us of this issue. I'll push an update as soon as possible.
