### ISSUE TITLE
InjectedInputMouseInfo is very confusing when it comes to injecting mouse wheel events.

### ISSUE THREAD

**Issue by brianpeiris** [MicrosoftDocs/winrt-api#1735]
The page implies that DeltaX and DeltaY can be applied to mouse wheel event injections, but that doesn't actually seem to be the case, even if you set MouseOptions to Wheel. 

Also, MouseData does seem to apply to mouse wheel events, however it is a `uint`, so it cannot be set to a negative value to simulate a mouse wheel event in the opposite direction, despite the documentation saying so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c01a16a-f79e-3da6-4ff2-0eb7c0b21e46
* Version Independent ID: 960a269e-65d1-9c04-7ba1-53a13e11c3ec
* Content: [InjectedInputMouseInfo Class (Windows.UI.Input.Preview.Injection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection.injectedinputmouseinfo?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Input.Preview.Injection/InjectedInputMouseInfo.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Input.Preview.Injection/InjectedInputMouseInfo.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by james-s-w-clark** [comment]
I think the documentation could definitely be improved. I'm trying to move my mouse to a fixed point and then click, but it's just clicking at the top-left corner. I've spent an hour or two on this, and it should be super simple.

As the first post says too, it's a bit confusing that docs refer to mousewheel when the wheel is just one option to inject with the mouse.
```
   var pos = new InjectedInputMouseInfo
            {
                MouseOptions = InjectedInputMouseOptions.Absolute, 
                DeltaX = 500,
                DeltaY = 500
            };

            var down = new InjectedInputMouseInfo
            {
                MouseOptions = InjectedInputMouseOptions.LeftDown,
            };

            var up = new InjectedInputMouseInfo
            {
                MouseOptions = InjectedInputMouseOptions.LeftUp,
            };

            var infos = new[] { pos, down, up };

            InputInjector inputInjector = InputInjector.TryCreate();
            inputInjector.InjectMouseInput(infos);

```

**Comment by Karl-Bridge-Microsoft** [comment]
Mouse input injection topics have been updated. Thanks for providing this feedback.
