### ISSUE TITLE
Duplicate Link in 'See Also' section?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1737]
The 'Speech Interactions' and 'Speech Design Guidelines' links go to the same topic. Should there only be one, or is a link missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7ea4c38-86da-f856-9eb6-1ac9edc5c2d2
* Version Independent ID: 19bb8f0f-eb2a-28d4-32df-9e8a982b53f0
* Content: [SpeechRecognizer Class (Windows.Media.SpeechRecognition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.SpeechRecognition.SpeechRecognizer?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Media.SpeechRecognition/SpeechRecognizer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.SpeechRecognition/SpeechRecognizer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @michael-hawker, this should be fixed in next publish cycle.
