### ISSUE TITLE
Example not ideal WRT SizeChanged event

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/winrt-api#1738]
The example on the page uses the SizeChanged event to detect changes in Tablet mode.
However, if the window is maximized then no SizeChanged event is raised when switching to/from tablet mode.
I have not yet found a better trigger event.
Best, Lars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 333bde8d-7b85-7b21-b37d-d05bcc7b6f18
* Version Independent ID: 6167298e-f6ba-2c3f-8cfe-b799c4517bc2
* Content: [UIViewSettings Class (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.ViewManagement.UIViewSettings?view=winrt-19041#Windows_UI_ViewManagement_UIViewSettings_UserInteractionMode)
* Content Source: [winrt-api-build/xml/Windows.UI.ViewManagement/UIViewSettings.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.ViewManagement/UIViewSettings.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @chrisgull, thanks for letting us know about this issue. I replaced the snippet with code from the latest related sample and added a link to that sample. Hope this helps.

**Comment by chrisgull** [comment]
Awesome!
