### ISSUE TITLE
FocusVisualMargin doc remarks are inaccurate

### ISSUE THREAD

**Issue by joshkoon** [MicrosoftDocs/winrt-api#1756]
The remarks on this page note:
> FocusVisualMargin values greater than 0 apply space outside the ActualWidth and ActualHeight of the object.
Negative values for margin dimensions are permitted, but should be used with caution. Negative margins can cause the content of the object to be clipped.

This is reversed from the actual behavior, which is that negative margins push the border away from the center of the object, while positive values push the border towards the center of the object. In addition, many default control templates use negative margins for FocusVisualMargin, and furthermore, it does not appear to clip the content of the object.

The correct behavior is detailed at https://docs.microsoft.com/en-us/windows/uwp/design/input/guidelines-for-visualfeedback#color-branding--customizing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd38573d-6c40-aeaf-ee11-5d515ca5529d
* Version Independent ID: 7e67a773-3d6d-b01a-28be-5abd375db845
* Content: [FrameworkElement.FocusVisualMargin Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.focusvisualmargin?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/FrameworkElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/FrameworkElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@joshkoon, thanks for catching this error. I've corrected the doc and added some links to more information.
