### ISSUE TITLE
Documentation is incorrect?

### ISSUE THREAD

**Issue by AdrianGarside** [MicrosoftDocs/winrt-api#1767]
It says that the Format() method takes a System.DateTimeOffset but it takes a Windows.Foundation.DateTime:
    HRESULT Format(
        [in] Windows.Foundation.DateTime value,
        [out, retval] HSTRING* result);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5e8342-d0f1-2e2f-6458-e1cd8f09d901
* Version Independent ID: 15c7ce82-4791-4529-d657-24ebfec741b7
* Content: [DateTimeFormatter.Format Method (Windows.Globalization.DateTimeFormatting) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.datetimeformatting.datetimeformatter.format?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Globalization.DateTimeFormatting/DateTimeFormatter.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Globalization.DateTimeFormatting/DateTimeFormatter.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@AdrianGarside - This topic appears to have been updated as it doesn't mention System.DateTimeOffset. Please open a  new issue with updated description if there is still incorrect/misleading/missing details in the topic. Thanks.
