### ISSUE TITLE
DragEventArgs.AcceptedOperation (and related documentation) should be interlinked

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1768]
Hello!

I was reading about UWP Drag and Drop and ended up on [DragEventArgs.AcceptedOperation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.drageventargs.acceptedoperation?view=winrt-19041). I noticed that it was a dead-end page and was missing some very important links:

* [DataPackageOperation enum](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackageoperation?view=winrt-19041) (this answers the question, "what are the operations?")
* [Drag and drop](https://docs.microsoft.com/en-us/windows/uwp/design/input/drag-and-drop) overview (this helps users who stumble upon this page contextualize this information)

I imagine there are other low-level Drag and Drop pages that would greatly benefit from a link back up to the Drag and drop overview, too.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f189855f-da53-7f3b-145b-5253d6565566
* Version Independent ID: 6493427e-b396-2a30-e0c7-5b73b65e66e2
* Content: [DragEventArgs.AcceptedOperation Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.drageventargs.acceptedoperation?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/DragEventArgs.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/DragEventArgs.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@citelao, thanks for the feedback. I've submitted a PR that adds a link to the overview for each drag-and-drop API.

The link to the DataPackageOperation enum should be in the Property Value section of doc, but there appears to be a build/rendering problem that's causing that section to be empty for all properties in the WinRT docs. We're investigating that issue.

**Comment by jwmsft** [comment]
The missing property value section is fixed.
