### ISSUE TITLE
Example Xaml for Matrix won't build

### ISSUE THREAD

**Issue by groovykool** [MicrosoftDocs/winrt-api#1770]
This won't Build due to Matrix tag.
XAML Matrix type cannot be constructed. In order to be constructed in XAML, a type cannot be abstract, interface, nested, generic or a struct, and must have a public default constructo

<Rectangle Width="60" Height="60" Fill="Blue">
  <Rectangle.RenderTransform>
    <MatrixTransform>
      <MatrixTransform.Matrix >
        
        <Matrix OffsetX="30" OffsetY="100" M12="0.5" />
      </MatrixTransform.Matrix>
    </MatrixTransform>
  </Rectangle.RenderTransform>
</Rectangle>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a53e7f8-7838-4899-17a0-0747ad1e63b5
* Version Independent ID: 9a2143eb-240d-77c6-27aa-10df0bb479be
* Content: [UIElement.RenderTransform Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.rendertransform?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@groovykool, thanks for pointing this out. I've opened a work item to correct this example as soon as possible. The matrix should be set in XAML like this:

```
        <Rectangle Width="60" Height="60" Fill="Blue">
            <Rectangle.RenderTransform>
                <MatrixTransform Matrix="1,0.5,0,1,100,100"/>
            </Rectangle.RenderTransform>
        </Rectangle>
```

See the [Matrix](https://docs.microsoft.com/uwp/api/windows.ui.xaml.media.matrix) struct for more information.
