### ISSUE TITLE
DnssdServiceInstance not working for mDNS

### ISSUE THREAD

**Issue by FredeJ** [MicrosoftDocs/winrt-api#1781]
After attempting for a couple of days to make this work, I have concluded that this does not work for registering an mDNS service.

If that is the case, could you update the documentation to reflect that and potentially guide me towards how to register such a service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8c3eba-2488-5fc4-fb87-f3f2f6fdfca3
* Version Independent ID: fbeea8e4-6b13-47c7-adca-994667231a2d
* Content: [DnssdServiceInstance Class (Windows.Networking.ServiceDiscovery.Dnssd) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd.dnssdserviceinstance?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.ServiceDiscovery.Dnssd/DnssdServiceInstance.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.ServiceDiscovery.Dnssd/DnssdServiceInstance.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @FredeJ, and thanks for filing this issue. I've reached out to the feature team for info, and we'll update the content if that becomes necessary. I'll close the issue, but update if it/when the docs change.

Thanks again!
Steve
