### ISSUE TITLE
What's the difference between Click and Tapped?

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1787]
It seems like "Tapped" is the correct event for many UIElements *except* Buttons, which should use Click.

Is this the case? Can relevant docs pages (like this one) make this distinction clear? Other potential updates:

* Click event documentation
* Button documentation
* Tap event documentation
* UWP pointer events overview

Here is a discussion with a lot of confused folks and no/few citations of MSDN: https://stackoverflow.com/questions/13318569/are-click-tapped-and-pointerpressed-synonymous-in-winrt-xaml#:~:text=An%20important%20differences%20between%20Click%20and%20Tapped%2C%20is,tapped%20is%20only%20fired%20on%20TAP%20without%20dragging.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e138cb-ad34-327c-4484-19e39d584102
* Version Independent ID: 290dc734-db22-7ffc-1ab6-b363fdbe8885
* Content: [ButtonBase.Click Event (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.buttonbase.click?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls.Primitives/ButtonBase.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls.Primitives/ButtonBase.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @citelao. Aside from the naming conventions used in the APIs, we try to write around them as customers interact with products using different input methods: keyboard, mouse, touch, voice, and more. So we try to use generic verbs that work with any input method. We try not to use input-specific verbs, such as click or swipe, in the documentation. 

This documentation is in need of a refresh and will be under review during the transition to WinUI. I have a work item to address this.

**Comment by citelao** [comment]
@Karl-Bridge-Microsoft, can we reopen this? The documentation is still unclear on this point.
