### ISSUE TITLE
reference for namespace to work

### ISSUE THREAD

**Issue by ffcplay** [MicrosoftDocs/winrt-api#1792]
Please provide info on what reference a project would need to use this namespace.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec6dc8a-165a-b58e-a43a-246c0abb8a25
* Version Independent ID: d29e78e9-5af1-3f1a-fb3d-c1e29acc90f2
* Content: [Windows.Data.Pdf Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.pdf?view=winrt-19041)
* Content Source: [winrt-api-build/xml/ns-Windows.Data.Pdf.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Data.Pdf.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
If you're writing code in one of the [UWP project types](https://docs.microsoft.com/en-us/windows/apps/desktop/visual-studio-templates#uwp-templates) available in Visual Studio, your project should already have all the necessary references to access this namespace. If you're using a .NET or C++ Windows Desktop Application project type, you'll need to use one of the options described in [this article](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance) to configure your project so it can use WinRT namespaces such as this one. 

I hope this helps.
