### ISSUE TITLE
What is the "menu" key?

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1795]
It is not clear to me what "menu key" means in the context of this event handler.

Is this the context menu key, the alt key, or something else? Does it vary by platform?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a583f7b-36b2-b642-23ef-263cf1a400a7
* Version Independent ID: 254bfe21-f0bb-9d8b-ba33-9e59dbf01bf5
* Content: [CorePhysicalKeyStatus.IsMenuKeyDown Field (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corephysicalkeystatus.ismenukeydown?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Core/CorePhysicalKeyStatus.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Core/CorePhysicalKeyStatus.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by citelao** [comment]
This is clarified on the [Keyboard events](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events) overview:

> The Alt key is represented by the **VirtualKey.Menu** value.

But I think it makes sense to document it here as well, or link to this documentation page.

**Comment by Karl-Bridge-Microsoft** [comment]
API topic has been updated with the suggested detail. Thanks!
