### ISSUE TITLE
Broken link for getTicketAsync within the description for ApplicationId property

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#1796]
The link set for the getTicketAsync method (which should be properly capitalized) points to an incomplete link causing the link to be broken.

Current target is:
https://docs.microsoft.com/en-us/uwp/api/onlineidsystemauthenticatorforuser_getticketasync?view=winrt-19041

Expected target should be:
https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.onlineid.onlineidsystemauthenticatorforuser.getticketasync?view=winrt-19041

namespace portion (windows.security.authentication.onlineid.) is missing from the link URL
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a6d96d-1adb-f15e-e73c-6c35b607a60d
* Version Independent ID: 1f24689f-ef74-8ab8-7966-82628716025e
* Content: [OnlineIdSystemAuthenticatorForUser Class (Windows.Security.Authentication.OnlineId) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.onlineid.onlineidsystemauthenticatorforuser?view=winrt-19041&source=docs)
* Content Source: [winrt-api-build/xml/Windows.Security.Authentication.OnlineId/OnlineIdSystemAuthenticatorForUser.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Authentication.OnlineId/OnlineIdSystemAuthenticatorForUser.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for pointing this out @JuanMejiaVelez , I've fixed the link as well as the capitalization. Change should be live within a day or two.
