### ISSUE TITLE
Trueplay documentation link dead/completely gone from GameMonitor page

### ISSUE THREAD

**Issue by superusercode** [MicrosoftDocs/winrt-api#1797]
Was the TruePlay page at the very least archived?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8abdf70b-8568-97f0-77fc-bd5ef85972d4
* Version Independent ID: aaf55f91-80e6-cb98-c50e-ed22890313fd
* Content: [GameMonitor Class (Windows.Gaming.UI) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.ui.gamemonitor?view=winrt-17134)
* Content Source: [winrt-api-build/xml/Windows.Gaming.UI/GameMonitor.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.UI/GameMonitor.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @superusercode, I'm afraid that the TruePlay topic isn't present in the archive. I searched in the two repos that it would have been in had it been archived and it's not there.

Note that TruePlay is removed from Windows as of Windows 10, version 1809 (10.0; Build 17763), and the GameMonitor class is deprecated as of that version, too.

I'll go ahead and close the issue, but you can still comment.

-Steve
