### ISSUE TITLE
IIterator<>::GetMany() is incomplete, the C++ WinRT version is wrong

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-api#1801]
Choose the "C++ WinRT" language, notice...

std::Array<> is not a thing, in C++ WinRT this is winrt::array_view<>. The other languages seem to have issues too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cdf9b35-2563-ca23-bffc-20f83828bbd8
* Version Independent ID: d33e833a-4188-2595-98e2-9c0f1c230055
* Content: [IIterator&lt;T&gt;.GetMany(T\[\]) Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.iiterator-1.getmany?view=winrt-19041&source=docs#Windows_Foundation_Collections_IIterator_1_GetMany__0___)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IIterator`1.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IIterator`1.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by stevewhims** [comment]
We're tracking this internally via 296915 [meriwether] C++/WinRT: for IIterator<T>.GetMany, the syntax block is not showing the correct types (originally filed 9/4/2020).

Recommend closing this issue.

-Steve

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that a comment was added about the issue in our system. I'll follow up to check the state of the internal request. We are moving to a new feedback system and tracking remaining issues in our internal system.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
