### ISSUE TITLE
How to set PackageUpdateAvailabilityResult.Required?

### ISSUE THREAD

**Issue by thommelutten** [MicrosoftDocs/winrt-api#1803]
I am trying to implement the CheckUpdateAvailabilityAsync method into my UWP app to check periodic for updates to the .appinstaller file. However, despite releasing new packages with both minor and major version changes
 (i.e., example 1 from 1.0.0 -> 1.1.0 and example 2 from 1.0.0 -> 2.0.0), every change only results in PackageUpdateAvailabilityResult.Available. 

While I know it might not be directly relevant to the docs, I am unable to figure out where to post my question. How do I create an update, so that the PackageUpdateAvailabilityResult.Required flag gets set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef274e8d-35aa-a486-f11b-f3573c8c1cb4
* Version Independent ID: 4ae4387a-a985-968e-69f4-30619ca5cbf5
* Content: [PackageUpdateAvailabilityResult Class (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageupdateavailabilityresult?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel/PackageUpdateAvailabilityResult.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel/PackageUpdateAvailabilityResult.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by thommelutten** [comment]
Bump. I am still unable to figure out how to set the .Required flag.

**Comment by scout208** [comment]
Are you using the new version of App Installer? Can you share what your app installer file looks like?

**Comment by thommelutten** [comment]
I was unable to print it directly in to the comment, so I made a GIST: https://gist.github.com/thommelutten/d1a47b846940f3c7563fd565cd63e756

When I am creating the Package, I am unable to see any flag that should set it to .Required (Through Visual Studio "Publish" -> "Create App Packages.." -> Sideloading)

**Comment by scout208** [comment]
Can you try changing the section in your .appinstall file: 

`xmlns="http://schemas.microsoft.com/appx/appinstaller/2017/2"`

to 

`xmlns="http://schemas.microsoft.com/appx/appinstaller/2018"`

If you do that, you can change your update settings to 

`<OnLaunch HoursBetweenUpdateChecks="0" ShowPrompt="true" UpdateBlocksActivation="true" />`

which will block the app from activating unless the user installs the update. Let me know if any of that helps.

**Comment by thommelutten** [comment]
We have decided to go in another direction when trying to update. So I'll close the issue. Thanks a lot for the help though, the steps you show definitely seems like those we missed.
