### ISSUE TITLE
HR codes listed as the exceptions thrown for SendRequestAsync

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#1806]
[Enter feedback here]
From the perspective of a UWP Developer, the documentation is not clear when enumerating the exceptions that Windows.Web.Http.HttpClient.SendRequestAsync can throw, as this page lists the possible HR values from the exceptions that this call could cause.

Mapping HR values to Exceptions would be an additional step that a developer would have to make, making this documentation not complete for that matter, instead of resolving the need of the persona that came to this reference.

I would suggest to enumerate the actual exception classes that this method call can throw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91f4439a-6da7-8b02-9a94-72bb12e9baa4
* Version Independent ID: e7518638-221a-003b-0497-78369631fafb
* Content: [HttpClient.SendRequestAsync Method (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient.sendrequestasync?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk%28Windows.Web.Http.HttpClient.SendRequestAsync%29%3Bk%28TargetFrameworkMoniker-.NETCore%2CVersion%253Dv5.0%29%3Bk%28DevLang-csharp%29%26rd%3Dtrue&view=winrt-19041&source=docs)
* Content Source: [winrt-api-build/xml/Windows.Web.Http/HttpClient.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Web.Http/HttpClient.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @JuanMejiaVelez, and thanks for filing this issue. I'll start a thread with yourself and the PM and we'll see what we can do to improve the topic.

I'll close this meanwhile, and we'll track the work internally.

Thanks!
Steve
