### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by heroboy** [MicrosoftDocs/winrt-api#1807]
This link in the page is 404.

[RSS reader end-to-end (JavaScript) sample (Windows 10)](https://go.microsoft.com/fwlink/p/?LinkId=620542)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5fd3fdc-d800-4237-7c1f-d7c2f376c4a3
* Version Independent ID: deebb508-4afc-e36e-6043-d48251f93e65
* Content: [SyndicationClient Class (Windows.Web.Syndication) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.syndication.syndicationclient?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(WINDOWS.WEB.SYNDICATION.2%252Fwinrt%253A%253AWindows%253A%253AWeb%253A%253ASyndication%253A%253ASyndicationClient);k(winrt%253A%253AWindows%253A%253AWeb%253A%253ASyndication%253A%253ASyndicationClient);k(SyndicationClient);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue&view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Web.Syndication/SyndicationClient.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Web.Syndication/SyndicationClient.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, and thanks for filing this issue. I have a fix going through the publishing pipeline now. I've changed the link text and the url to link to the [RssReader sample](/samples/microsoft/windows-appsample-rssreader/rssreader-sample/).

I'll go ahead and close the issue, and meanwhile I'll keep an eye on the fix and confirm that it goes live.

Thanks again!
-Steve
