### ISSUE TITLE
Alternate languages please

### ISSUE THREAD

**Issue by SteveMinard** [MicrosoftDocs/winrt-api#1809]
[Enter feedback here]The example is in c++ and unless you are very well versed is not easily translated to VB.  Please provide the example in all of the .NET languages.  Thank-you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a6f16-4abc-e0eb-8095-b575a7d94972
* Version Independent ID: 01196e83-0095-1cb3-c6e5-5da7a377ac87
* Content: [Gamepad Class (Windows.Gaming.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepad?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Gaming.Input/Gamepad.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.Input/Gamepad.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @SteveMinard. This is an ongoing effort throughout our developer docs, but does require significant resources. We'll try to address this as soon as possible.

**Comment by SteveMinard** [comment]
> Thanks for the feedback, @SteveMinard. This is an ongoing effort throughout our developer docs, but does require significant resources. We'll try to address this as soon as possible.

Thank-you
