### ISSUE TITLE
See also section is garbled.

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/winrt-api#1812]
[Enter feedback here]

The see also section on the page is garbled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adecb6c7-a20b-4e93-19c1-64c8ca0c0b0a
* Version Independent ID: ef12b24c-754e-27b6-19b6-85ec408e1890
* Content: [PackageManager Class (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Management.Deployment/PackageManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Management.Deployment/PackageManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The see also links are fixed now.
