### ISSUE TITLE
Broken link to DesiredLiveOffset on AdaptiveMediaSource_MinLiveOffset page

### ISSUE THREAD

**Issue by AndrewRH** [MicrosoftDocs/winrt-api#1816]
The link to DesiredLiveOffset in the Remarks section is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9272b4d8-952e-a5f3-463c-4cd878aa8405
* Version Independent ID: 06dd4f7d-daeb-edf6-2cdc-f92b00853b4a
* Content: [AdaptiveMediaSource.MinLiveOffset Property (Windows.Media.Streaming.Adaptive) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.streaming.adaptive.adaptivemediasource.minliveoffset?view=winrt-19041#Windows_Media_Streaming_Adaptive_AdaptiveMediaSource_MinLiveOffset)
* Content Source: [winrt-api-build/xml/Windows.Media.Streaming.Adaptive/AdaptiveMediaSource.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Streaming.Adaptive/AdaptiveMediaSource.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reporting this! The link has been fixed.
