### ISSUE TITLE
C++/WinRT and C++/CX doc cause confusion by referring to .NET types

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/winrt-api#1821]
The UWP reference documentation seems to have been taken over by C#/.NET types. Viewing the C++/WinRT docs for [Windows.Foundation.Uri](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.uri?view=winrt-19041), I see this:

> Inheritance [Object](https://docs.microsoft.com/en-us/dotnet/api/system.object) -> Uri

The Object link points to .NET's System.Object. This is wrong, and it should refer to [IInspectable](https://docs.microsoft.com/en-us/windows/win32/api/inspectable/nn-inspectable-iinspectable) instead. ([Platform::Object](https://docs.microsoft.com/en-us/cpp/cppcx/platform-object-class?view=vs-2019) for C++/CX)

These problems go beyond runtimeclasses:

- [Windows.Foundation.Rect](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.rect?view=winrt-19041) incorrectly says it inherits from .NET's [System.ValueType](https://docs.microsoft.com/en-us/dotnet/api/system.valuetype). C++/WinRT structs should not have any base class. C++/CX structs should probably inherit from [Platform::ValueType](https://docs.microsoft.com/en-us/cpp/cppcx/platform-valuetype-class?view=vs-2019).

- [Windows.Foundation.PropertyType](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.propertytype?view=winrt-19041) (an enum) incorrectly says it inherits form .NET's [System.Enum](https://docs.microsoft.com/en-us/dotnet/api/system.enum). C++/WinRT enums should not have any base type. C++/CX enums should probably inherit from [Platform::Enum](https://docs.microsoft.com/en-us/cpp/cppcx/platform-enum-class?view=vs-2019).

- String properties like [Windows.Foundation.Uri.AbsoluteCanonicalUri](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.uri.absolutecanonicaluri?view=winrt-19041) say the return type is [System.String](https://docs.microsoft.com/en-us/dotnet/api/system.string). The actual type is [HSTRING](https://docs.microsoft.com/en-us/windows/win32/WinRT/hstring), and the HSTRING page states that it is projected in C# as System.String, in C++/WinRT as [winrt::hstring](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/hstring), and in C++/CX as [Platform::String](https://docs.microsoft.com/en-us/cpp/cppcx/platform-string-class?view=vs-2019).

- Bool properties like [Windows.Foundation.Uri.Suspicious](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.uri.suspicious?view=winrt-19041) say they return [System.Boolean](https://docs.microsoft.com/en-us/dotnet/api/system.boolean). C++/WinRT uses the C++ built-in [bool](https://docs.microsoft.com/en-us/cpp/cpp/bool-cpp?view=vs-2019). C++/CX uses [Platform::Boolean](https://docs.microsoft.com/en-us/cpp/cppcx/platform-boolean-value-class?view=vs-2019).

- [Rect.Height](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.rect.height?view=winrt-19041) says it is of type [System.Single](https://docs.microsoft.com/en-us/dotnet/api/system.single). C++/WinRT uses the C++ built-in [float](https://docs.microsoft.com/en-us/cpp/cpp/fundamental-types-cpp?view=vs-2019#floating-point-types) type. Similarly, C++ doesn't use System.Double, but uses the C++ built-in double.

- [TimeSpan.Duration](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.timespan.duration?view=winrt-19041) is flagged as a [System.Int64](https://docs.microsoft.com/en-us/dotnet/api/system.int64). C++/WinRT uses the standard library type int64_t. Same goes for other integral types.

- Delegates in C++ don't inherit from [System.Delegate](https://docs.microsoft.com/en-us/dotnet/api/system.delegate). In C++/CX, I believe they inherit from [Platform::Delegate](https://docs.microsoft.com/en-us/cpp/cppcx/platform-delegate-class?view=vs-2019).

- References to [Windows.Foundation.IClosable](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iclosable?view=winrt-19041) have been coerced into [System.Closable]. See [Windows.Foundation.MemoryBuffer.Close](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.memorybuffer.close?view=winrt-19041) for an example. C++/WinRT should leave the original as Windows.Foundation.IClosable. C++/CX should use [Platform::IDisposable](https://docs.microsoft.com/en-us/cpp/cppcx/platform-idisposable-interface?view=vs-2019).

- References to Guids ([example](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.guidhelper.createnewguid?view=winrt-19041#Windows_Foundation_GuidHelper_CreateNewGuid)) have been coerced into System.Guid. C++/WinRT uses winrt::guid. C++/CX uses [Platform::Guid](https://docs.microsoft.com/en-us/cpp/cppcx/platform-guid-value-class?view=vs-2019).

This list is a good starting place, but probably isn't complete.

**Comment by arkrumbe** [comment]
[Windows.UI.Composition.CompositionObject ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionobject?view=winrt-19041) incorrectly states that it derives from [System.Object ](https://docs.microsoft.com/en-us/dotnet/api/system.object?view=netcore-3.1). Composition is a weird API, and doesn't follow the example of many other APIs, but it should probably derive from IInspectable.

**Comment by stevewhims** [comment]
Hi, @DefaultRyan, I've just sent you an email internally. Let's work there and talk about potential remedies for these issues. As I say in the email, lots of related things are already underway. I'll go ahead and close this, and we'll work internally.

Thanks!
Steve

**Comment by arkrumbe** [comment]
Hey Steve, would you mind adding me to that thread?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
