### ISSUE TITLE
 AesGcm 	  Retrieves a string that contains "AES_CCM".

### ISSUE THREAD

**Issue by rlaf99** [MicrosoftDocs/winrt-api#1826]
[Enter feedback here]

Shouldn't AesGcm return "AES_GCM"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2c157e-c89d-5fb5-0ecc-ac456363ee70
* Version Independent ID: ee6e2d0e-0264-bd20-bd29-c5b88b7b57de
* Content: [SymmetricAlgorithmNames Class (Windows.Security.Cryptography.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core.symmetricalgorithmnames?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Security.Cryptography.Core/SymmetricAlgorithmNames.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Cryptography.Core/SymmetricAlgorithmNames.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
