### ISSUE TITLE
Link on UWP Image.Stretch property contains a link to a page that requires permissions. 

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#1828]
While on https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image.stretch?view=winrt-19041&source=docs
there is a link in **Image sources and scaling** before the Note that reads "UX guidelines for layout and scaling" that links to the document https://developer.microsoft.com/en-us/windows/apps/design which in turn returns an access restricted message.

> **Access restricted**
>We're sorry, you don’t have permission to access this page. For assistance, contact your account administrator.

This should not be the case in the public documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4303538-0757-5ee4-927b-52390f782f22
* Version Independent ID: 87855c05-4b5c-a0fc-15ed-c778ecee70fa
* Content: [Image.Stretch Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image.stretch?view=winrt-19041&source=docs)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Image.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Image.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for pointing this out. That page no longer exists, so I've submitted an update to link to a current design page instead.
