### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/winrt-api#1832]
DisplayPath got put inside itself:

> set more of your DisplDisplayPathayPath properties 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394d3647-8744-59bf-3fad-a31dff571fe6
* Version Independent ID: 2cddb094-856d-2811-eb09-488db8ca9441
* Content: [DisplayState.TryFunctionalize(DisplayStateFunctionalizeOptions) Method (Windows.Devices.Display.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaystate.tryfunctionalize?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Display.Core/DisplayState.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Display.Core/DisplayState.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @rpavlik, I have a fix making its way through the publishing pipeline now. Should be live over the next 24 hours or so.

Thanks again!
Steve
