### ISSUE TITLE
Proposal: Add language switch to sample code

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/winrt-api#1834]
I remember from earlier renderings of the Microsoft online documentation (.NET documentation in particular), that code samples always had a (session cookie based) language switch, so the reader was able to read and extract samples in their preferred computer language.

This language switch seems to have been removed in the current edition of Microsoft online documentation.

Now, `F#` and `VB.NET` programmers won't be able to extract sample code in their preferred language.

Plus, I noticed that a number of code samples are [given three times](https://docs.microsoft.com/en-us/windows/uwp/composition/using-the-visual-layer-with-xaml): Once in `C#` then again in `C++/WinRT` and `C++`.

Last but not least, it looks like `JavaScript` is also supported by WinRT somehow.

I believe it's confusing to find some of the samples in another language (particularly when it comes to exclusive `JavaScript` samples for WinRT). So, I'd like to propose to return to the old fashion of having code samples rendered in "all" applicable computer languages and have the user select their preferred computer language by clicking the corresponding language tab (which will set a session cookie and immediately switch over all other code samples on the same page):

![NET languages](https://user-images.githubusercontent.com/9283914/94498093-8a144200-01f9-11eb-91f0-cda7d49ec86f.png)
<br/>

#### I suspect that all different computer language variants can be auto-generated most of the time, so they don't have to be actually written

An empty computer language specifier could indicate to the MS documentation markdown compiler to auto-generate the corresponding code from the first language:

~~~md
```csharp
// Here is an example code.
```
```vb
```
```fsharp
```
~~~

Resulting in:

![Languages 1](https://user-images.githubusercontent.com/9283914/94499684-9ef2d480-01fd-11eb-991e-6dd8316d9992.png)
<br/>

While samples not able of being auto-generated may be explicitly added:

~~~md
```csharp
// Here is an example code.
```
```vb
' Here is a deviating example code.
```
```fsharp
```
~~~

Resulting in:

![Languages 2](https://user-images.githubusercontent.com/9283914/94499703-afa34a80-01fd-11eb-9a4f-bba683531d93.png)
<br/>

**Clicking the Download PDF button on the left navigation panel should present a simple computer language selection dropdown list to have samples being output for the desired computer language only in the PDF file (using the first of the available computer languages alternatively when a particular sample isn't provided in the desired computer language).**

**Comment by GrantMeStrength** [comment]
Thank you for taking the time to provide this feedback. I'm going to take note of it, as we are always looking at improving our documentation and we're aware that the current situation which hides alternatively languages behind tabs is not as discoverable as we originally hoped. There is a team dedicated to improving the developer experience, and I will forward your comments as they work on the next iteration. Again, thanks for taking the time! 

-john

**Comment by SetTrend** [comment]
Thank you, @GrantMeStrength, for taking the time.

From what I understood from your reply, let me just clarify two final points:
<br/>

The current situation is exactly the opposite: It's _not_ "hiding alternatively languages behind tabs". It's rather ...

   1. writing out loads of example code, making it cumbersome to skip to the next informative section, thereby fostering [WMSD](https://www.ccohs.ca/oshanswers/diseases/rmirsi.html).

   1. omitting a number of .NET languages in the documentation
<br/>

Here's a comparison of the current and the desired situation:

![MS documentation](https://user-images.githubusercontent.com/9283914/96115391-266f6180-0ee7-11eb-96a4-2c3fcd5ba988.png)
