### ISSUE TITLE
windows.applicationmodel.lockscreen for third parties

### ISSUE THREAD

**Issue by 6ziv** [MicrosoftDocs/winrt-api#1836]
Sorry to bother, but [issue #726 in Windows-universal-samples](https://github.com/microsoft/Windows-universal-samples/issues/726) indicates that this feature is protected and cannot be used by 3rd parties developers. I would be really grateful if you could check for this and update the doc (for if that repo maintainer was true, then the do is really misleading…by saying 'you can create an app that acts as the lock screen, allowing greater user personalization'…)
Many thanks.

**Comment by GrantMeStrength** [comment]
I'm afraid Raymond is the authority, and if he says this feature is not available to third party developers, then that is the situation. I apologize the documentation was not updated in a timely manner, and I've taken care of that now. Thank you for the reminder!
