### ISSUE TITLE
The documented behavior is not the current API behavior

### ISSUE THREAD

**Issue by vgromfeld** [MicrosoftDocs/winrt-api#1837]
The `MediaPlayer.Volume` property states:

> Values outside of this range will be clamped.

This is not what is happening. All the values outside the [0, 1] range are ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f1a2290-1c59-0a16-e70e-abf6e0222803
* Version Independent ID: a18520e9-609f-21f5-e29e-cac7faf00820
* Content: [MediaPlayer.Volume Property (Windows.Media.Playback) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.volume?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Media.Playback.MediaPlayer.Volume);k(SolutionItemsProject);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETCore,Version%253Dv5.0);k(DevLang-csharp)%26rd%3Dtrue&view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Media.Playback/MediaPlayer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Playback/MediaPlayer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hi, thanks for catching this. I verified that the behavior you describe is correct and have updated the page to reflect this. You should see the page updated within ~24 hours. Thanks again for helping to improve the documentation.
