### ISSUE TITLE
SwapChainPanel.Background throws because it's an unsupported property

### ISSUE THREAD

**Issue by gegao18** [MicrosoftDocs/winrt-api#1842]
SwapChainPanel inherits Background because it derives from Panel, but we don't actually allow apps to set it. We throw an "unsupported property" error when an app tries to set it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee9a5a88-6893-33e4-3875-b7c9d3ab54f2
* Version Independent ID: 56d8c4f4-c6b6-0369-f0aa-62a53117ae86
* Content: [SwapChainPanel Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swapchainpanel?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/SwapChainPanel.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/SwapChainPanel.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@gegao18, thanks for the information. I've submitted an update to add this to the docs.
