### ISSUE TITLE
GetProviderNetworkUsageAsync does not support granularity, but mentions a restriction with it.

### ISSUE THREAD

**Issue by endpointmanager** [MicrosoftDocs/winrt-api#1843]
GetProviderNetworkUsageAsync -> startTime -> **If the specified granularity** ...
This method does not support the input parameter "granularity"!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e93554fe-bafd-ad29-d0cc-4b2b07d1f85f
* Version Independent ID: 2c029284-92f1-e856-98df-9699bb3085b9
* Content: [ConnectionProfile.GetProviderNetworkUsageAsync(DateTimeOffset, DateTimeOffset, NetworkUsageStates) Method (Windows.Networking.Connectivity) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.connectivity.connectionprofile.getprovidernetworkusageasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.Connectivity/ConnectionProfile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.Connectivity/ConnectionProfile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @endpointmanager. Yes, it looks like that sentence was copy-pasted from GetNetworkUsageAsync. The fix is now live.

-Steve
