### ISSUE TITLE
Request for details on event usage

### ISSUE THREAD

**Issue by OllyMcBrideOB** [MicrosoftDocs/winrt-api#1844]
It would be useful for this page to include some remarks about the usage of this 'BLE ConnectionStatusChanged 'event. 

For example:

- How do we determine whether the event handler was triggered due to a 'connect' or a 'disconnect' event
- For cppwinrt, what parameters are passed to the event handler (it appears to be a copy of a BLE device object & an IInspectable, but no detail is given)

This event doesn't seem to be used within the UWP samples, so there is very little information available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dc8a170-5eff-c7b3-a954-c986a635e49e
* Version Independent ID: eeea1c65-b002-ce77-8535-c9d26db71c00
* Content: [BluetoothLEDevice.ConnectionStatusChanged Event (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.connectionstatuschanged?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @OllyMcBrideOB. In your handler for this event, check the ConnectionStatus property on the BluetoothLEDevice that's passed as a parameter. I've published an update to the topic with this info.

To handle this event in C++/WinRT, use code along the lines of this:

```cppwinrt
    void MainPage::foo(Windows::Devices::Bluetooth::BluetoothLEDevice const& a)
    {
        a.ConnectionStatusChanged({ this, &MainPage::ConnectionStatusChangedHandler });
    }

    void MainPage::ConnectionStatusChangedHandler(
        Windows::Devices::Bluetooth::BluetoothLEDevice const& sender,
        winrt::Windows::Foundation::IInspectable const& args)
    {
    }
```

-Steve
