### ISSUE TITLE
Incorrect MapElement3D dependency property pages

### ISSUE THREAD

**Issue by tonyhallett** [MicrosoftDocs/winrt-api#1852]
https://github.com/MicrosoftDocs/winrt-api/blob/docs//windows.ui.xaml.controls.maps/mapelement3d_scaleproperty.md

Links to Roll instead of Scale

https://github.com/MicrosoftDocs/winrt-api/blob/docs//windows.ui.xaml.controls.maps/mapelement3d_rollproperty.md

Links to Pitch instead of Roll

https://github.com/MicrosoftDocs/winrt-api/blob/docs//windows.ui.xaml.controls.maps/mapelement3d_locationproperty.md

Should be "Identifies the Location dependency property" and not "Identifies the LocationProperty dependency property"

**Comment by stevewhims** [comment]
Hi, @tonyhallett, and apologies for the very long delay in responding to this issue.

I've just submitted a fix for these topics, and I expect those fixes to be visible on the live site within 24 hours. In any case, I'll monitor them and I'll make sure they go live. You can leave that with me, so I'll go ahead and close this issue now.

Thanks again!
Steve
