### ISSUE TITLE
AcceleratorKeyEventArgs.VirtualKey Property does not always contain a VirtualKey

### ISSUE THREAD

**Issue by jbrianceau** [MicrosoftDocs/winrt-api#1854]
Documentation should explicitly mention that `AcceleratorKeyEventArgs.VirtualKey` property does not always contain a value from the `VirtualKey` enum.

When `AcceleratorKeyEventArgs.EventType` property is `CoreAcceleratorKeyEventType.Character` for instance, the `AcceleratorKeyEventArgs.VirtualKey` value should not be considered as a `VirtualKey` enum.

As an example, if you execute the following code:
```
        public MainPage()
        {
            InitializeComponent();

            CoreWindow.GetForCurrentThread().Dispatcher.AcceleratorKeyActivated += OnAcceleratorKeyActivated;
        }

        private void OnAcceleratorKeyActivated(CoreDispatcher sender, AcceleratorKeyEventArgs args)
        {
            if (args.VirtualKey == Windows.System.VirtualKey.F7)
            {
                Debug.WriteLine($"This event is related to the F7 key - args.EventType = {args.EventType}");
            }
        }
```
Typing on the F7 function key will output:
```
This event is related to the F7 key - args.EventType = KeyDown
This event is related to the F7 key - args.EventType = KeyUp
```

Typing on the v key (lowercase) will unexpectedly output:
```
This event is related to the F7 key - args.EventType = Character
```
In that case, it seems that `AcceleratorKeyEventArgs.VirtualKey` contains an ASCII or Unicode value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91368897-a0a1-beb5-6c5b-8f28eb396569
* Version Independent ID: 8be42f12-5b6a-a583-47d2-9ab4313b783b
* Content: [AcceleratorKeyEventArgs.VirtualKey Property (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.acceleratorkeyeventargs.virtualkey?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Core/AcceleratorKeyEventArgs.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Core/AcceleratorKeyEventArgs.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
The following code shows that 'v' is identified as a value from the VirtualKey enum. Closing issue, but please reopen with more info if you disagree. Thanks!

Debug.WriteLine($"args.EventType = {args.EventType}");
Debug.WriteLine($"args.VirtualKey = {args.VirtualKey}");

output:
args.EventType = KeyDown
args.VirtualKey = V
args.EventType = Character
args.VirtualKey = F7
args.EventType = KeyUp
args.VirtualKey = V

**Comment by jbrianceau** [comment]
> The following code shows that 'v' is identified as a value from the VirtualKey enum.

That's exactly my point. The documentation states that the `AcceleratorKeyEventArgs.VirtualKey` property contains "_the **virtual key code** of the key that was pressed_", which is incorrect when the `AcceleratorKeyEventArgs.EventType` = `Character`.
As a matter of fact, it seems that the `AcceleratorKeyEventArgs.VirtualKey` property contains an ASCII code and **not** a virtual key code in this case (at least).

To me, the developer shouldn't have to guess this information, and the documentation should be explicit about it instead.

**Comment by Karl-Bridge-Microsoft** [comment]
Handled in private PR.
