### ISSUE TITLE
FlushAsync needs to explain why you might, or might not want to use it.

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-api#1856]
The FlushAsync method improves, but does not guarantee durable and coherent storage of data and it introduces latencies. It's generally recommended to avoid this method to achieve good performance but it should be used if coherency is desired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bf5a70-6962-f6a6-ecfc-3ad2123573cc
* Version Independent ID: 122e3975-8d37-d648-f989-351243d3b420
* Content: [IOutputStream.FlushAsync Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.ioutputstream.flushasync?view=winrt-19041#remarks)
* Content Source: [winrt-api-build/xml/Windows.Storage.Streams/IOutputStream.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Streams/IOutputStream.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for raising this. I went ahead and updated the remarks with your suggestion: https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.storage.streams/ioutputstream_flushasync_491532439.md. In the future, you can also directly edit the file and open a PR for our review. This way, you have the flexibility of adjusting the docs to your liking. Thanks once again, Chris!
