### ISSUE TITLE
List of pattern interfaces has multiple entries with "Introduced in ."

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-api#1857]
Some entries in the list of patter interfaces start the description with "Introduced in .":
![Image showing a snippet of the table of interfaces](https://user-images.githubusercontent.com/16122379/96911865-b9893800-14a1-11eb-8d18-a2f663657f03.png)

Not sure what the . is referring to here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 727e7518-9b6d-7366-9b3f-8c47d6ffbcc1
* Version Independent ID: 532dd243-3acc-bb24-adca-381326fdf790
* Content: [PatternInterface Enum (Windows.UI.Xaml.Automation.Peers) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.peers.patterninterface?view=winrt-19041#feedback)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Automation.Peers/PatternInterface.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Automation.Peers/PatternInterface.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. These incomplete strings have been deleted.
