### ISSUE TITLE
List of Error codes and Error messages

### ISSUE THREAD

**Issue by Ad1tyaV** [MicrosoftDocs/winrt-api#1858]
The below link redirects to a link and claims it has a list of ErrorCodes
`'The error message. See WebProviderError.ErrorCode Property for a list of error codes.`

The is the link it redirects to - >
https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.core.webprovidererror.errorcode?view=winrt-19041#Windows_Security_Authentication_Web_Core_WebProviderError_ErrorCode

Even here I don't see a list of issues and descriptions, could you share/ point out where there are list of existing ErrorCodes and corresponding Error Messages

For the application that I'm working on, I'm getting **3399548929** as response code on using WAM for Auth and states ' _need user interaction to continue_'

How do I fix this issue ?

https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.core.webprovidererror.errormessage?view=winrt-19041#Windows_Security_Authentication_Web_Core_WebProviderError_ErrorMessage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1858e1ac-14a3-b953-0c01-63015dd3576d
* Version Independent ID: c9b86f96-d644-4fd7-1c11-669596059a4c
* Content: [WebProviderError.ErrorMessage Property (Windows.Security.Authentication.Web.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.core.webprovidererror.errormessage?view=winrt-19041#Windows_Security_Authentication_Web_Core_WebProviderError_ErrorMessage)
* Content Source: [winrt-api-build/xml/Windows.Security.Authentication.Web.Core/WebProviderError.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Authentication.Web.Core/WebProviderError.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
