### ISSUE TITLE
Throws System.Exception: 'Incorrect function. (Execption from HRESULT: 0x80070001)'

### ISSUE THREAD

**Issue by mneitzke** [MicrosoftDocs/winrt-api#1861]
Throws System.Exception: 'Incorrect function. (Execption from HRESULT: 0x80070001)' every time it is called on a Windows.Devices.PointOfService.BarcodeScanner object.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24eb4d4d-e215-bf50-a204-8be78925e555
* Version Independent ID: 400c5080-7d97-97c2-afd3-3c12ec81a034
* Content: [BarcodeScanner.GetSupportedProfiles Method (Windows.Devices.PointOfService) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.barcodescanner.getsupportedprofiles?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.PointOfService/BarcodeScanner.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.PointOfService/BarcodeScanner.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @mneitzke, I've reached out to my contacts for info about any possible exceptions that we'd want to document here.

Thanks!
Steve

**Comment by stevewhims** [comment]
Hi, @mneitzke. It turns out that this topic was missing important info about it being deprecated (or, at least, limited to certain Builds of the Windows Mobile device family). I'm sure that accounts for why the API wasn't behaving for you as expected. I've added the specifics of the deprecation notice to the topic.

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close the issue now that it's resolved.

Thanks again!
Steve
