### ISSUE TITLE
C++ Resource Manager showing errors and Javascript code

### ISSUE THREAD

**Issue by cwebb95** [MicrosoftDocs/winrt-api#1862]
This page as well as many others in this section of the reference appear to be broken. They are showing errors and Javascript code instead of the expected C++ code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2da2e4c0-a36f-36aa-250d-957cba167b6a
* Version Independent ID: 90a666be-3e58-cfb8-86a4-6a5df1b57a6d
* Content: [ResourceManager Class (Windows.ApplicationModel.Resources.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.core.resourcemanager?branch=live&view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Resources.Core/ResourceManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Resources.Core/ResourceManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Hi @cwebb95. Thanks for bringing this issue to our attention, and I apologize for the delayed response. I replaced the JavaScript sample in this page with C# and C++ samples from the referenced GitHub repository. I am also creating an internal work item to review the other files in this section to fix them as well. The changes to this file were just merged to our internal repo and should be visible on the live site later today.
