### ISSUE TITLE
Drag reordering will only fire the DragItemsCompleted and DragItemsStarting events if CanDragItems is enabled

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1865]
It is undocumented, but DragItemsStarting and DragItemsCompleted will not fire unless CanDragItems is set to true on the ListView.

We should update the documentation to indicate that!

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e57ae263-5f40-7ebb-a38e-10b826ef1577
* Version Independent ID: aa49ee6c-013e-c639-4bbc-1e1620c0bf1b
* Content: [ListViewBase.CanReorderItems Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.canreorderitems?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ListViewBase.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ListViewBase.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by citelao** [comment]
I filed [a question on StackOverflow](https://stackoverflow.com/questions/64580413/why-do-i-not-get-dragitemscompleted-and-dragitemsstarting-events-when-canreorder/64580414#64580414), too.

**Comment by jwmsft** [comment]
Thanks, @citelao. I've updated the API docs with this information.
