### ISSUE TITLE
INotifyCollectionChanged links to the wrong NotifyCollectionChangedEventArgs 

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#1866]
This page links to https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedeventhandler, but it should link to https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.interop.notifycollectionchangedeventhandler?view=winrt-19041.

Right now it goes to the .NET type, but it should go to the WinRT type. This might be a wider issue for Xaml.Interop types, which is why I'm not fixing the bug myself.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b5a3b0c-b2fd-dfd9-44e3-1761d0f0deb8
* Version Independent ID: ed8d202c-82b3-ad8f-3bfb-9268620df044
* Content: [INotifyCollectionChanged.CollectionChanged Event (Windows.UI.Xaml.Interop) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.interop.inotifycollectionchanged.collectionchanged?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Interop/INotifyCollectionChanged.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Interop/INotifyCollectionChanged.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, these links are working as expected. They are auto-generated by the doc build, and depend on the language selector at the top of the page. If the selected language is C# or VB, the links go to the .NET event handler, but if the selected language is C++/WinRT, the links go to the WinRT event handler.

**Comment by citelao** [comment]
Woah, that’s really cool! Thanks for clarifying.
