### ISSUE TITLE
Arrays are wrongly rendered in C++/WinRT mode

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/winrt-api#1870]
Arrays are wrongly rendered in C++/WinRT mode:
```cpp
uint64_t GetCurrentReading(std::Array <bool> const & buttonArray, std::Array <GameControllerSwitchPosition> const & switchArray, std::Array <double> const & axisArray);
```
but should be rendered as `winrt::array_view<type>`. Also `const` is not needed because its out params. Should be like this:
```cpp
uint64_t GetCurrentReading(winrt::array_view<bool>& buttonArray, winrt::array_view<GameControllerSwitchPosition>& switchArray, winrt::array_view<double>& axisArray);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010c28ba-ca95-3878-b3b7-8a31aed9ca21
* Version Independent ID: 07d4cab6-e3e3-a86a-0e14-f33d967a75e6
* Content: [RawGameController.GetCurrentReading(Boolean\[\], GameControllerSwitchPosition\[\], Double\[\]) Method (Windows.Gaming.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.rawgamecontroller.getcurrentreading?view=winrt-19041#feedback)
* Content Source: [winrt-api-build/xml/Windows.Gaming.Input/RawGameController.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.Input/RawGameController.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by stevewhims** [comment]
Hi, @DJm00n, and thanks for filing this issue. The syntax block is something that's generated by the content build system, so I've created (and socialized) a bug on our content engineers. I'll go ahead and track that internally. I have a list of such issues to track, so the progress of this issue will be monitored internally. In light of that, and so as not to track the work in two places, I'll go ahead and close this issue.

Thanks again!
Steve
