### ISSUE TITLE
Xbox Elite Paddles not separately bindable

### ISSUE THREAD

**Issue by dciborow** [MicrosoftDocs/winrt-api#1871]
With the release of controller support for World of Warcraft, it would be create to use the Xbox elite controller, with the pandles. Sadly, these are not detected differently then the buttons... Despite the documentation claiming they should be. 
Currently, it requires an additional program like "rewasd" to bind all the controller keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82b16a1a-f418-2396-ae11-b8512f0d9617
* Version Independent ID: a5d4ce79-edf9-abec-4ae9-4957fdce2a2e
* Content: [GamepadButtons Enum (Windows.Gaming.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepadbuttons?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Gaming.Input/GamepadButtons.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Gaming.Input/GamepadButtons.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @dciborow - closing this issue as we're addressing internally.
