### ISSUE TITLE
IStorageProviderItemPropertySource

### ISSUE THREAD

**Issue by Dmitriyverkhov** [MicrosoftDocs/winrt-api#1880]
Hi!
There is no documentation about how to use IStorageProviderItemPropertySource and it's GetItemProperties.
Can it be registered as Type (using RegAsm for example) and be used by operating system or explorer, for example.
Thanks!

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
