### ISSUE TITLE
Update 'this page' Generic access profile URL

### ISSUE THREAD

**Issue by andrefonte** [MicrosoftDocs/winrt-api#1881]
"Any non-standard type not reserved by the system, as shown in the list below. For more information on non-standard types, see **this page** from the Bluetooth specification."

From: https://www.bluetooth.org/specification/assigned-numbers/generic-access-profile/
To: https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 793209bf-2551-957f-78e5-b41c6c4bf0b3
* Version Independent ID: 34becb26-c1c9-68ef-d4d3-4d3742cecdd3
* Content: [BluetoothLEAdvertisementPublisher Class (Windows.Devices.Bluetooth.Advertisement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementpublisher?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisementPublisher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisementPublisher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @andrefonte, and thanks for filing this issue. The fix for this, and the other topic with the same issue, is now live. I'll close the issue.

Thanks!
Steve
