### ISSUE TITLE
MediaBinder.Binding - case of multiple handlers?

### ISSUE THREAD

**Issue by Shadolio** [MicrosoftDocs/winrt-api#1884]
If multiple handlers are subscribed to the `Binding` event of MediaBinder, each of them can set the source differently. For example, when the first handler is invoked, it uses `SetUri(uri)` to set a Uri media source; then, the second handler sets another Uri or MediaStreamSource.

**Is that scenario possible, or is it prevented?
If not prevented, which source is finally used?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7707e1f-e9cf-a735-2152-66e779207969
* Version Independent ID: 5ea38cd5-527d-4fbb-7353-f2a41eaa03d5
* Content: [MediaBinder.Binding Event (Windows.Media.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediabinder.binding?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Media.Core/MediaBinder.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Core/MediaBinder.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
