### ISSUE TITLE
No syntax for UserDataPaths constructor

### ISSUE THREAD

**Issue by jjlee9** [MicrosoftDocs/winrt-api#1886]
There is no syntax for UserDataPaths constructor. I don't know how to construct an object of this class to get current user data path for multiple user machines.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c4c60a8-769b-d2e2-d056-a0e59690354b
* Version Independent ID: 2976cc41-1e81-db36-8471-d8cf6bb004b0
* Content: [UserDataPaths Class (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.userdatapaths?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage/UserDataPaths.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/UserDataPaths.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
