### ISSUE TITLE
Cannot set wallpaper aspect ratio.

### ISSUE THREAD

**Issue by K07H** [MicrosoftDocs/winrt-api#1888]
Since registry operations for current user are not possible with UWP I'm not able to set wallpaper image ratio to "Adjust" (instead of "Fill"which is the default).
We need an optional parameter to specify aspect ratio in [UserProfilePersonalizationSettings.TrySetWallpaperImageAsync(StorageFile)](https://docs.microsoft.com/en-us/uwp/api/windows.system.userprofile.userprofilepersonalizationsettings.trysetwallpaperimageasync) method.
This optional parameter could take the same values offered in Windows 10 wallpaper settings. For recall:
- Fill (Default)
- Adjust
- Stretch
- Tile
- Center
- Extended

Thank you

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the product. I don't have any additional content for your scenario, over and above what's in the documentation. So it might be worth your pursuing this as a question/feedback about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback. Thanks!
