### ISSUE TITLE
Example code is in wrong language for DeviceInformationUpdate Class

### ISSUE THREAD

**Issue by jaraymsft** [MicrosoftDocs/winrt-api#1893]
The example code for this page seems to be in JavaScript, no matter what language is selected in the dropdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579fad5f-6ee2-2c43-ffdf-78d6098bfab0
* Version Independent ID: dbb26cf0-299d-0bf4-842a-9400019a917d
* Content: [DeviceInformationUpdate Class (Windows.Devices.Enumeration) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformationupdate?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformationUpdate.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformationUpdate.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. This is an obsolete code example, and I just replaced it in the article with a link to the full [Device enumeration and pairing sample](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/DeviceEnumerationAndPairing) on GitHub. This change should be on the live site in the next day or so.
