### ISSUE TITLE
Explanation of the symbol * is missing

### ISSUE THREAD

**Issue by tossnet** [MicrosoftDocs/winrt-api#1894]
On this Page, the explanation of the symbol * is missing.

**Add by example :** 

- **Fixed value**  :  To assign a fixed size of logical units (1/96 inch)
- **Auto** : It will take only as much space as is required for the controls in that specific row/column.
-  **Star (*)** : It will take the remaining space when Auto and fixed sized are filled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c7ae1a6-663f-7df1-e799-551bf9ac6589
* Version Independent ID: fef2e049-755a-1d18-3616-3ff41b5d4510
* Content: [Grid.RowDefinitions Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.grid.rowdefinitions?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Grid.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Grid.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Fixed in PR #1895
