### ISSUE TITLE
C++/WinRT syntax blocks missing 'static' keyword for properties/events

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/winrt-api#1896]
C++/WinRT syntax blocks for static methods include the `static` keyword, but it's missing for static properties and static events.

An example of a working static method is [`Windows.Foundation.PropertyValue.CreateBoolean`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.propertyvalue.createboolean?view=winrt-19041). The C++/WinRT syntax block clearly shows the `static` keyword.

Now look at a static property, [`Windows.Foundation.GuidHelper.Empty`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.guidhelper.empty?view=winrt-19041). The C++/WinRT syntax block shows
```c++
winrt::guid Empty();
```
instead of 
```c++
static winrt::guid Empty();
```
(C# syntax block appears to be correct).

Same situation appears for static events, such as [`Windows.Foundation.Diagnostics.AsyncCausalityTracer.TracingStatusChanged`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.diagnostics.asynccausalitytracer.tracingstatuschanged?view=winrt-19041).

**Comment by stevewhims** [comment]
I've turned this into a work item for the content engineers. https://ceapex.visualstudio.com/Engineering/_workitems/edit/344649. I'll go ahead and close this issue, since we'll use that work item for tracking.

-Steve
