### ISSUE TITLE
Methods on Windows.Foundation.GuidHelper are missing C++/WinRT language option.

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/winrt-api#1898]
Look at [`Windows.Foundation.GuidHelper.CreateNewGuid`](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.guidhelper.createnewguid?view=winrt-19041#Windows_Foundation_GuidHelper_CreateNewGuid). There is no option for C++/WinRT. Why is this?

**Comment by stevewhims** [comment]
I've turned this into a work item for the content engineers. https://ceapex.visualstudio.com/Engineering/_workitems/edit/344653. I'll go ahead and close this issue, since we'll use that work item for tracking. Please feel free to make any necessary edits to that work item.

-Steve
