### ISSUE TITLE
Link in Bindings page is broken

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/winrt-api#1899]
The first link in this page is broken

```
<xref:Windows.UI.Xaml.Data.BindingOperations.SetBinding(Windows.UI.Xaml.DependencyObject%2cWindows.UI.Xaml.Dependency
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1313ed23-758b-d84f-b3ea-38df54a695b6
* Version Independent ID: 8b62eee5-b2d8-dd6a-f7ef-ba3d155c7418
* Content: [Binding Class (Windows.UI.Xaml.Data) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.binding?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Data/Binding.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Data/Binding.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Link was fixed on Dec 9.
