### ISSUE TITLE
FolderPicker is not availiabel in C++/winRT

### ISSUE THREAD

**Issue by PerArneS68** [MicrosoftDocs/winrt-api#1904]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c5cc11e-e82c-8b6d-31ce-338d205ab93e
* Version Independent ID: c8644184-a498-397f-62b9-a1304280c2ad
* Content: [FileOpenPickerUI Class (Windows.Storage.Pickers.Provider) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.provider.fileopenpickerui?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers.Provider/FileOpenPickerUI.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers.Provider/FileOpenPickerUI.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by stevewhims** [comment]
Hi, @PerArneS68.

You *can* definitely use the **FolderPicker** class with C++/WinRT.

But the topic you link to is **FileOpenPickerUI**.

* Is this issue about having trouble using the **FileOpenPickerUI** class with C++/WinRT?
* Or is it about the [File picker provider sample](https://github.com/microsoft/windows-universal-samples/tree/main/Samples/FilePickerContracts) being available in C# but not in C++/WinRT?

Thanks!
Steve

**Comment by stevewhims** [comment]
Closing.
