### ISSUE TITLE
Missing C++/WinRT example  for UIElement.AddHandler

### ISSUE THREAD

**Issue by rectified95** [MicrosoftDocs/winrt-api#1909]
Without a C++/WinRT example it is rather difficult to know how to use `UIElement.AddHandler()` when needing to handle already-handled events - the signature is a little different from regular handler registration.
The key missing bit is how to pass the handler instance when an `IInspectable` is required.

Here's a snippet that worked for me:
```cpp
this->AddHandler(
    winrt::Windows::UI::Xaml::UIElement::PointerPressedEvent(),
    winrt::box_value(winrt::Windows::UI::Xaml::Input::PointerEventHandler(
      [=](auto &&, winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs const &args) {
      // ...
    })),
    true);
```

I can create a PR if you can point me to the right file - I thought this would be the right file -uielement_addhandler_2121467075.md - but it is a little different from what's hosted here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.addhandler?view=winrt-19041

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10d8e20c-b546-b3de-5613-3979758db96b
* Version Independent ID: 4b782f24-ef1f-3f1a-3d24-7492a37a899e
* Content: [UIElement.AddHandler(RoutedEvent, Object, Boolean) Method (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.addhandler?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@stevewhims, can you take a look at this issue? Thanks

**Comment by stevewhims** [comment]
Thanks, @rectified95! I've emailed you, so we'll try and get this updated as per that.

Thanks again!
Steve

**Comment by asklar** [comment]
@stevewhims @rectified95 @jwmsft  Also need to update https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/events-and-routed-events-overview, possibly other related docs.

The examples on the page Igor linked are coming from a C++/CX project in this repo, see https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.xaml/code/BaseElementEvents/cpp/BasicPage.xaml.cpp#SnippetAddHandler
So we might need to port the CX project to cppwinrt if we don't have a better way or a ready-made sample that shows this

**Comment by stevewhims** [comment]
Thanks, @asklar. I've put that on my backlog, and I'll try and find cycles for it.

-Steve

**Comment by stevewhims** [comment]
So, since I have a work item for this in my backlog, rather than double-track it I'll go ahead and close this issue. My backlog work item has a link back to this issue, so I can come back here and update this when I'm done. Meanwhile, I'll close.

Thanks!
Steve
