### ISSUE TITLE
Documents Library capability

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/winrt-api#1913]
Please either provide the syntax, or a link to the syntax to add the Documents Library capability.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa4a639-050b-93b9-fb7e-36f5e872fcac
* Version Independent ID: 39953358-fb65-af0a-91f4-671547650b30
* Content: [KnownFolders.DocumentsLibrary Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.knownfolders.documentslibrary?view=winrt-19041#Windows_Storage_KnownFolders_DocumentsLibrary)
* Content Source: [winrt-api-build/xml/Windows.Storage/KnownFolders.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/KnownFolders.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
"To work with the Documents library and its contents, call the methods and properties of the [StorageFolder](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder?view=winrt-19041) class."

Is this not enough information? If not, please re-open with a little more details and we'll take a look. 

Thanks - John
