### ISSUE TITLE
GetFileFromPathForUserAsync doesn't list possible exceptions

### ISSUE THREAD

**Issue by Zofware** [MicrosoftDocs/winrt-api#1915]
The doc page for `GetFileFromPathForUserAsync` doesn't list the possible exceptions that it could throw. The example catches some exceptions but they are normally listed explicitly in the documentation. For example, the doc page for [`GetFileFromPathAsync`](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefrompathasync?view=winrt-19041) lists the possible exceptions that could be thrown. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df1cf6ee-4e1e-26d8-2724-f8cde062bf48
* Version Independent ID: af6d83e3-911a-a2f9-75eb-51a81b8af54f
* Content: [StorageFile.GetFileFromPathForUserAsync(User, String) Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefrompathforuserasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
