### ISSUE TITLE
KeyCredentialManager and friends should have more detailed documentation

### ISSUE THREAD

**Issue by Phyxius** [MicrosoftDocs/winrt-api#1918]
I've been trying to develop an application that uses `KeyCredentialManager` and friends and have had difficulty finding information about the output and format of the relevant APIs. In particular, it was difficult to find information about the generated keys, signatures, and attestation information. Questions I had that were (IMO) unnecessarily difficult to answer included:

- What kind of keys are these? (RSA 2048-bit).
- What format is the signature? (PKCS #1 RSA PSS with SHA256)
- How do I export and parse the parameters of the public key so I can verify it using an arbitrary server language/platform? (I used the BCrypt output and hand-parsed it based on available headers; is there a better way, like a managed implementation of a public key blob parser?).
- What form is the attestation data? (Eventually I figured it out by Googling some of the hex constants in the attestation data, but this was as far as I could tell not answered by any Microsoft documentation).
- How do I verify it? (ditto).

The sample for these APIs answers some of these questions, but not all of them and not directly. Notably, there is no discussion or sample for validating the attestation data, which would have been very helpful. 

I would have liked to see questions like these directly answered in the relevant documentation sections (e.g., the output format in the documentation for `RequestSignAsync()`).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 480928db-e6fc-eafd-95fe-066d1d2502dd
* Version Independent ID: 586271d0-b0ab-5aa4-34e5-ca634897c5f1
* Content: [KeyCredentialManager Class (Windows.Security.Credentials) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.keycredentialmanager?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Security.Credentials/KeyCredentialManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Credentials/KeyCredentialManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by zjbpku** [comment]
any updates？

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

The organization is moving to a new feedback system, so I want to make sure to capture my open issues before the Issues functionality is turned off for this repo.
