### ISSUE TITLE
Missing details: VoipCallCoordinator.SetupNewAcceptedCall

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#192]
Affected API: [`Windows.ApplicationModel.Calls.VoipCallCoordinator.SetupNewAcceptedCall`](https://github.com/MicrosoftDocs/winrt-api/blob/ffb3416cdcfa9b10b7483fe818072ab43d8aa47c/windows.applicationmodel.calls/voipcallcoordinator_setupnewacceptedcall_475235632.md)

The documentation for this API is missing some details. Under what scenarios would I want to use this API? How does this API compare to `RequestNewIncomingCall`?

Adam Comella
Microsoft Corp.

**Comment by mattwojo** [comment]
Thanks for bringing this to our attention @rigdern. 

@duncanmacmichael @EliotSeattle -- Can either of you help with this?

**Comment by duncanmacmichael** [comment]
I wish I could, but I'm not familiar with this API or its brethren. I believe UWP API reference falls under @GrantMeStrength's territory, though I can't guide you to an individual owner, sorry.

**Comment by muhsinking** [comment]
Hey Adam, thanks for opening this issue--it looks like the difference between **SetupNewAcceptedCall** and **RequestNewIncomingCall** is that latter requires the use of push/toast notifications. **SetupNewAcceptedCall** was added later to allow users to accept calls directly within an app's UI. I'll be making some changes in the documentation to reflect this.

**Comment by rigdern** [comment]
@muhsinking Thanks for fixing this. Where can I see the updated doc?

**Comment by muhsinking** [comment]
[The commit has been merged](https://github.com/MicrosoftDocs/winrt-api/commit/52bc5aadac1ceb95a236bec27610538d093d3132), but it's not quite live. I had a chat with the dev team about this method, so the changes are a bit different than I originally stated
