### ISSUE TITLE
DateTimeOffset cannot be zero

### ISSUE THREAD

**Issue by under3415** [MicrosoftDocs/winrt-api#1920]
Can you explain what is returned when the value is missing?
Documention currently says zero is returned which doesn't make sense as the return type `DateTimeOffset` cannot be 0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8112159-53e8-edff-bb8a-c2bbf312e2c1
* Version Independent ID: f1b985d9-5ccf-b2f8-69fc-85e0aa48027b
* Content: [StorageFile.DateCreated Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.datecreated?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by alvinashcraft** [comment]
The wording for this is incorrect. The Offset value of the returned DateTimeOffset will be 0. The DateTime value will be DateTimeOffset.MinValue. These are the defaults for a DateTimeOffset struct that has not been set. I will update the docs to reflect this.

**Comment by alvinashcraft** [comment]
I have updated the guidance on this page about the default value, so it matches the guidance on the System.DateTimeOffset page. The changes have been merged and should be available on the live docs page soon. Thank you for raising this issue!
