### ISSUE TITLE
StorageLibraryChangeReader not working on Windows 10 Multi Session

### ISSUE THREAD

**Issue by AliveDevil** [MicrosoftDocs/winrt-api#1927]
On two Windows 10 Enterprise Multi Session VMs on Azure I am not getting any result using `StorageLibraryChangeTracker.ReadChangesAsync()` - with latest 20H2 image.
On Windows 10 Pro and Windows 10 Enterprise this does work without any issues.

Why is a Windows Runtime API, available since ages, not working on Windows 10 Enterprise Multi Session?

As a developer this does not make any sense.
Unzip the attached `x64_debug.zip`-file ([alirgh_1.0.0.0_x64_Debug.zip](https://github.com/MicrosoftDocs/winrt-api/files/5849133/alirgh_1.0.0.0_x64_Debug.zip))
 and run
```
Add-AppxPackage -Register -Path AppxManifest.xml
```
inside a PowerShell window.
Run the now installed "alirgh"-App. Copy some files to the Documents-folder, observe that there is no output whatsoever. There should be a list of all changes being registered through `StorageLibraryChangeReader` printed. There is no indication that this should not work in the Microsoft documentation about this API:
* [storagelibrarychangetracker](https://docs.microsoft.com/uwp/api/windows.storage.storagelibrarychangetracker)
* [storagelibrarychangereader](https://docs.microsoft.com/uwp/api/windows.storage.storagelibrarychangereader) 

The sample project: [ConsoleApplication2.zip](https://github.com/MicrosoftDocs/winrt-api/files/5849132/ConsoleApplication2.zip)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 92eb895d-1520-9400-3574-debf943009a9
* Version Independent ID: 59280650-4614-3274-0fe6-a404ee4a2c85
* Content: [StorageLibraryChangeReader Class (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/de-de/uwp/api/windows.storage.storagelibrarychangereader?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageLibraryChangeReader.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageLibraryChangeReader.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
