### ISSUE TITLE
CompositionDebugSettings::TryGetSettings behavior if developer mode is not enabled is documented incorrectly

### ISSUE THREAD

**Issue by scott-moore-ms** [MicrosoftDocs/winrt-api#1929]
The documentation says

A call to TryGetSettings will fail with an exception if developer mode is not enabled.

That would be a perfectly logical and reasonable behavior, but sadly not what the implementation actually does - If developer mode is not enabled, TryGetSettings will return a null CompositionDebugSettings object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddddabd6-dfef-6f00-4f4a-6e5c1b7ffeba
* Version Independent ID: 61cf137d-7d90-837b-77d8-35766eb2b191
* Content: [CompositionDebugSettings.TryGetSettings(Compositor) Method (Windows.UI.Composition.Diagnostics) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.diagnostics.compositiondebugsettings.trygetsettings?view=winrt-19041#Windows_UI_Composition_Diagnostics_CompositionDebugSettings_TryGetSettings_Windows_UI_Composition_Compositor_)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition.Diagnostics/CompositionDebugSettings.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition.Diagnostics/CompositionDebugSettings.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this error. I've corrected the doc and it should be live shortly.
