### ISSUE TITLE
Missing details: VoipCallCoordinator.ReserveCallResourcesAsync

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#193]
Affected API: [Windows.ApplicationModel.Calls.VoipCallCoordinator.ReserveCallResourcesAsync](https://github.com/MicrosoftDocs/winrt-api/blob/ffb3416cdcfa9b10b7483fe818072ab43d8aa47c/windows.applicationmodel.calls/voipcallcoordinator_reservecallresourcesasync_2108134884.md#L0)

The only thing the documentation says about this API is "Reserves the resources necessary for a VoIP call.". It doesn't answer questions such as:
  - When/why do I need to call this?
  - If my app is handling 2 VoIP calls simultaneously, do I have to invoke this API once per VoIP call?
  - What kind of resources is it reserving?
  - Do I need to free them? When? How?
  - What exceptions is this expected to throw? Looking at [the VoIP sample](https://github.com/Microsoft/Windows-universal-samples/blob/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/VoIP/cs/VoipTasks/Helpers/VccCallHelper.cs#L69), it appears that it's okay for `ReserveCallResourcesAsync` to throw an `Exception` with `HRESULT -2147024713`.

Adam Comella
Microsoft Corp.

**Comment by muhsinking** [comment]
Hey Adam, thanks for opening this issue, and sorry for the delay. These are all very good questions, and I'll be working with the dev team to answer them in the documentation ASAP.

**Comment by muhsinking** [comment]
Added some remarks to the docs that should answer most of your questions--they'll be live tomorrow. I'll reiterate the answers here:

**When/why:** use this method when your VoIP application receives an incoming call notification, or before creating an outgoing VoIP call.

**For multiple calls:** each call requires separate resources. To handle multiple VoIP calls simultaneously, you must invoke this method once for each call.

**Type of resources:** CPU and memory

**Freeing resources**: resources are freed automatically when a call is completed.

**Comment by rigdern** [comment]
@muhsinking Thanks! Do you also plan to add details for my last bullet point about exceptions the method could throw?

**Comment by muhsinking** [comment]
@rigdern, I've asked the team if they can provide more details on exceptions, I'll let you know if any further updates come through

**Comment by rigdern** [comment]
@muhsinking Thanks. Should we open a new bug or reactivate this one so we don't forget about it?
