### ISSUE TITLE
Canvas.ZIndex is documented as being -1 by default, but it appears to be zero.

### ISSUE THREAD

**Issue by ptorr-msft** [MicrosoftDocs/winrt-api#1933]
If you query the value from a random element, it returns zero. E.G. within `MainPage.xaml.cs` of a default project:

```
var x = Canvas.GetZIndex(this);
```

`x` will be zero.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d504d09f-0104-e46f-6135-99b147603621
* Version Independent ID: 8eee6397-da9a-839a-d25e-33ea5f60c07e
* Content: [Canvas Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.canvas?view=winrt-19041&source=docs#xaml-attached-properties)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Canvas.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Canvas.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for pointing this out. The doc has been updated with the correct default value.
