### ISSUE TITLE
ToggleSwitch C++ /WinRT Example

### ISSUE THREAD

**Issue by Acurisu** [MicrosoftDocs/winrt-api#1935]
For the sake of completness it would be nice to have a C++ /WinRT version of the C# ToggleSwitch_Toggled example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d14dcd8-b107-5018-dcec-8fb61397b65e
* Version Independent ID: 87b58bbc-d684-9b48-646e-d0bd9f0d5d25
* Content: [ToggleSwitch Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.toggleswitch?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ToggleSwitch.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ToggleSwitch.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @Acurisu. I've updated the topic, and that should be live soon. Meanwhile, here's the C++/WinRT version.

```cppwinrt
using namespace winrt::Windows::UI::Xaml::Controls;
void MainPage::ToggleSwitch_Toggled(IInspectable const& sender, RoutedEventArgs const& /* args */)
{
    ToggleSwitch toggleSwitch = sender.as<ToggleSwitch>();
    if (toggleSwitch)
    {
        if (toggleSwitch.IsOn())
        {
            progress1().IsActive(true);
            progress1().Visibility(Visibility::Visible);
        }
        else
        {
            progress1().IsActive(false);
            progress1().Visibility(Visibility::Collapsed);
        }
    }
}
```

Thanks!
Steve
