### ISSUE TITLE
This page lists the wrong default value

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/winrt-api#1936]
This page lists the default value of `TreeView.CanReorderItems` as **false**, but the default value is **true**!

[Source code link showing the default value as true](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/TreeView/TreeView.idl#L152).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06c0c492-ce18-e8bd-a4f5-656d64b72c34
* Version Independent ID: ca967de7-c2fb-3daf-698e-1e7571ad0454
* Content: [TreeView.CanReorderItems Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.canreorderitems?view=winrt-19041#Windows_UI_Xaml_Controls_TreeView_CanReorderItems)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/TreeView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/TreeView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. The page has been corrected.

**Comment by mrlacey** [comment]
> Thanks for reporting this. The page has been corrected.

When will the change be visible?
