### ISSUE TITLE
This page lists the wrong default value

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/winrt-api#1937]
This page lists the default value of `TreeView.CanDragItems` as **false**, but the default value is **true**!

[Source code link showing the default value as true](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/TreeView/TreeView.idl#L150).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6969cac2-d385-ca17-0da2-b6d2be006b91
* Version Independent ID: 3acdb444-f8e8-a044-23b7-b22b9ee794e1
* Content: [TreeView.CanDragItems Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.candragitems?view=winrt-19041#Windows_UI_Xaml_Controls_TreeView_CanDragItems)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/TreeView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/TreeView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. The page has been corrected.
