### ISSUE TITLE
Error in GetAppListEntriesAsync

### ISSUE THREAD

**Issue by softworkz** [MicrosoftDocs/winrt-api#194]
winrt-api/windows.applicationmodel/package_getapplistentriesasync_364802562.md

Text states:
`Enumerates the packaged apps on the device. Only packaged apps that are registered to the current user are returned.`
This is incorrect. Actually only apps included within the current package are enumerated.

**Comment by laurenhughes** [comment]
Thanks for pointing this out! I'll make sure this gets updated on the page.
