### ISSUE TITLE
Instantiate an DeviceInformationUpdate object

### ISSUE THREAD

**Issue by zhit-microsoft** [MicrosoftDocs/winrt-api#1940]
Documentation states that you can instantiate an DeviceInformationUpdate object, but I have not found any ways to do it.

> You can also instantiate a DeviceInformationUpdate object to pass to Update.

Exiting discussion seems to indicate that this is not achievable. See: https://social.msdn.microsoft.com/Forums/en-US/38791a17-1973-4bea-a204-64dad4bb43a1/does-deviceinformationupdate-update

If it is actually possible, can someone provide an example of how we can instantiate this object?

Joe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579fad5f-6ee2-2c43-ffdf-78d6098bfab0
* Version Independent ID: dbb26cf0-299d-0bf4-842a-9400019a917d
* Content: [DeviceInformationUpdate Class (Windows.Devices.Enumeration) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformationupdate?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformationUpdate.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Enumeration/DeviceInformationUpdate.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue to us. To the best of my understanding, there is indeed no way to instantiate this object yourself and/or update its properties. Instead, a DeviceInformationUpdate object intended to be passed to handlers of the DeviceWatcher.Update event, and then you can pass this object to the DeviceInformation.Update method, as described in [this section](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/enumerate-devices#enumerate-and-watch-devices). I am updating the remarks for this page to capture this info.
