### ISSUE TITLE
What is this exactly?

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/winrt-api#1943]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a8e4b1-1e06-5b81-a901-186da0f5a166
* Version Independent ID: dc7fa85f-2b13-b14f-3cf5-69a1c3723990
* Content: [SystemMediaTransportControlsDisplayUpdater.AppMediaId Property (Windows.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.systemmediatransportcontrolsdisplayupdater.appmediaid?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Media/SystemMediaTransportControlsDisplayUpdater.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media/SystemMediaTransportControlsDisplayUpdater.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I did some investigation and it appears that this property is just an app-defined value that could potentially be used for engagement tracking. It is not currently used by the system.
