### ISSUE TITLE
c# video and audio frame reader

### ISSUE THREAD

**Issue by yahyaakbayrak** [MicrosoftDocs/winrt-api#1947]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e439fc3c-b26a-13df-a91a-5b7a62387275
* Version Independent ID: 869091ab-325e-d0c4-c72c-53a076c646bd
* Content: [AudioMediaFrame Class (Windows.Media.Capture.Frames) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.audiomediaframe?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Media.Capture.Frames/AudioMediaFrame.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Capture.Frames/AudioMediaFrame.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
You haven't provided any details of your issue, but I noticed that the links in the See Also section were incorrectly formatted. I've updated that. If you opened this issue for some other reason, please reopen the issue and provide some details of your issues.
