### ISSUE TITLE
Attached properties of ScrollViewer is not listed in an individual section

### ISSUE THREAD

**Issue by oldoldman** [MicrosoftDocs/winrt-api#1950]
ScrollViewer has many properties which both dependent and attached, I can just find the attached properties from the method section. Maybe lists all the attached properties in one section (just like other controls) is more convenient. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b04b95-dab3-a46a-0aef-6012c351b443
* Version Independent ID: aa6e4ef8-5027-f0b8-6521-d15054ad022c
* Content: [ScrollViewer Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ScrollViewer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ScrollViewer.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
The doc system only supports listing properties in the table of contents as 'Properties' or 'AttachedProperty', but not both. The ScrollViewer attached properties are listed in a separate section of the Remarks:
https://learn.microsoft.com/uwp/api/windows.ui.xaml.controls.scrollviewer?view=winrt-19041#scrollviewer-xaml-attached-properties
