### ISSUE TITLE
No C++/Winrt sample

### ISSUE THREAD

**Issue by clarkezone** [MicrosoftDocs/winrt-api#1952]
Please add C++/WinRT samples for all windows APIs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02e7e7b-b93d-43d1-9512-7431409c787f
* Version Independent ID: 3dd4d69e-034a-5684-5037-593e78a21dbc
* Content: [DispatcherQueue.CreateTimer Method (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue.createtimer?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueue.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueue.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I appreciate the idea behind this request, but samples are added based on resource availability and expected benefit to the community. We add samples for as many article/language combinations as we can, but we can't do all of them. If there are specific APIs you would like to see samples for, please let me know and I can pass along the request.
