### ISSUE TITLE
Inaccessible PointCollection Methods??

### ISSUE THREAD

**Issue by groovykool** [MicrosoftDocs/winrt-api#1954]
These methods in the PointCollection Class are inaccessible due to protection level. 
 GetAt();
 GetMany();
 GetView();
 InsertAt();
 RemoveAtEnd();
 ReplaceAll();
 SetAt();

Is this a bug or a documentation issue???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4269af9e-0119-f07c-2dca-69429d2f97c2
* Version Independent ID: dcfe54ef-7b2b-c077-f344-5e7da77cf2a3
* Content: [PointCollection Class (Windows.UI.Xaml.Media) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.PointCollection?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Media/PointCollection.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Media/PointCollection.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jaigak** [comment]
These methods are part of the Windows.Foundation.Collections.IVector COM interface which .NET hides and instead implements IList on the projected class. When using from .NET, you can call similar IList methods on PointCollection. Those methods you mentioned are only for C++. I think the C# version of the documentation is incorrect.
