### ISSUE TITLE
Big header gap inherited from Windows 8 for the WebAuthenticatorBroker 

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/winrt-api#1956]
The developer forgot to change the height of the WebAuthenticatorBroker header when they moved from Windows 8 to Windows 10. It's very ugly. See screenshot

![image](https://user-images.githubusercontent.com/1608424/109740800-dd6c3100-7b99-11eb-835b-f5db7f648177.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c758cb2-ad03-f28e-6947-21337462753a
* Version Independent ID: 3e818dc7-e032-c92b-80ba-0c0773391fec
* Content: [WebAuthenticationBroker Class (Windows.Security.Authentication.Web) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Security.Authentication.Web.WebAuthenticationBroker?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Security.Authentication.Web/WebAuthenticationBroker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Authentication.Web/WebAuthenticationBroker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. The scope of our feedback channel here on GitHub covers specific documentation fixes, but I can help redirect you to the right support channel to provide ypour feedback. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. Hope your issue can get more visibility there.
