### ISSUE TITLE
Давно код проверяли ? он не компилируется

### ISSUE THREAD

**Issue by gorbukov** [MicrosoftDocs/winrt-api#1958]
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a14c83f0-f3d9-3475-7256-731c639ea111
* Version Independent ID: adacee2f-db0a-e5f6-4bf1-ca379041b917
* Content: [ApplicationViewTitleBar Class (Windows.UI.ViewManagement) - Windows UWP applications](https://docs.microsoft.com/ru-ru/uwp/api/windows.ui.viewmanagement.applicationviewtitlebar?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.ViewManagement/ApplicationViewTitleBar.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.ViewManagement/ApplicationViewTitleBar.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
No issue reported.
