### ISSUE TITLE
Windows.Storage: The GetFilesAsync method don't work in UWP application build for ARM 64.

### ISSUE THREAD

**Issue by Antonio-Iliev** [MicrosoftDocs/winrt-api#1959]
Setup:
UWP Visual Studio template.
Target version 1903, Build 18362.
HoloLens 2 device build for ARM64

The GetFilesAsync method returns an empty collection without considering the presence of files in the specified 'KnownFolders' directory. When the method GetFileAsync() was used to load an existing file in the same 'KnownFolders' directory the result was correct.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9dd15ed-b41c-a906-6768-3b818dca73b6
* Version Independent ID: f04d7b02-e96b-419f-e2a6-897bedae311e
* Content: [StorageFolder.GetFilesAsync Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.getfilesasync?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFolder.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFolder.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hey @Antonio-Iliev , could you file this over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html)? Unfortunately, this feedback channel covers specific doc fixes. Hoping you can get an answer over at Q&A.

**Comment by Antonio-Iliev** [comment]
Thank you for the reply. I'm sorry for posting in the wrong place.
Have a nice day.
