### ISSUE TITLE
C++/WinRT documentation shows the type as std::array for array instead of winrt::array_view

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#1962]
In the C++/WinRT version, it shows the last argument as std::array<T> instead of winrt::array_view<T>. std::array<T> won't work here as std::array also takes the size as a template parameter and array_view should be used instead but the documentation has this mistake. The signature should be array_view<T> instead. Also, I noticed that in C++/WinRT it's written Platform::Array<T>^ instead of Platform::WriteOnlyArray<T>^ which also should be corrected.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76fe852-187b-447c-85a1-086c93470641
* Version Independent ID: 1cd40649-d1e2-b05f-fdf7-4221575d4248
* Content: [IVector&lt;T&gt;.GetMany(UInt32, T\[\]) Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivector-1.getmany?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IVector`1.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IVector`1.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. In the current version of this doc, it looks like the C++/WInRT version definition lists std::array_view and there are some remarks about this type too. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
