### ISSUE TITLE
No description

### ISSUE THREAD

**Issue by Karl-Bridge-Microsoft** [MicrosoftDocs/winrt-api#1963]
No description provided for this struct. Topic is a stub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7691b1d2-f6f6-49d3-970f-773e61bcff0d
* Version Independent ID: c8ea2712-5c22-cbda-3ffe-7178c773d0e3
* Content: [FullTrustAppContract Struct (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.fulltrustappcontract?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel/FullTrustAppContract.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel/FullTrustAppContract.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Closing this issue as Contract topics like this one are now being filtered out.
