### ISSUE TITLE
Confusing Default Value for HorizontalAlignmentRatio

### ISSUE THREAD

**Issue by hawkerm** [MicrosoftDocs/winrt-api#1965]
Not sure if it's the comment on the code or where Visual Studio is getting this text (as I don't see it in the doc):

![image](https://user-images.githubusercontent.com/8959496/111687096-21407680-87e7-11eb-824e-9b8d77ae1721.png)

However, in the opening paragraph it says the default is 0.0f, but in the return value it says its 0.5f...

Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71ef9c03-bdee-d73d-0a88-c8a850ab081e
* Version Independent ID: 19481190-ce4a-a8a6-8a66-805752b86b90
* Content: [CompositionSurfaceBrush.HorizontalAlignmentRatio Property (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionsurfacebrush.horizontalalignmentratio?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Composition.CompositionSurfaceBrush.HorizontalAlignmentRatio);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/CompositionSurfaceBrush.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/CompositionSurfaceBrush.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Per this commit, the doc is correct, but IntelliSense is out-of-date. IntelliSense updates should happen on the VS side.
[remove contradicting info](https://github.com/MicrosoftDocs/winrt-api/commit/f69fb1ccf8ad86e6f16b231f3f50bc6daa688e10)
