### ISSUE TITLE
DispatcherQueueTimer Interval default not specified

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#1967]
The default time for the Interval property is not specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de717875-912f-6404-1f6e-f25048f74ac2
* Version Independent ID: f25562b6-df93-b31b-b362-54533fe5be73
* Content: [DispatcherQueueTimer Class (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueuetimer?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The default is 0. Zero everything - days, hours, minutes, seconds, milliseconds. I added this to the docs. Should be published shortly.
