### ISSUE TITLE
Add a note to caution use of this API on a background thread

### ISSUE THREAD

**Issue by xadxura** [MicrosoftDocs/winrt-api#1969]
This API returns the currently active input method for thread with keyboard input focus. Calling this on a background thread may not return the expected results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48b1086b-5632-7db1-de6d-115ac96d2cc8
* Version Independent ID: da1aceeb-2fef-155d-6170-5a167e007cba
* Content: [Language.CurrentInputMethodLanguageTag Property (Windows.Globalization) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.language.currentinputmethodlanguagetag?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Globalization/Language.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Globalization/Language.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @xadxura - Andrew, this property returns a string. Would the following be suitable?

This property returns a value for the currently active input method on the thread with keyboard input focus. Calling this on a background thread may not return the expected results.

**Comment by Karl-Bridge-Microsoft** [comment]
I've merged my suggested remark into the topic. I'll close this issue, but please respond if you have any other feedback.
