### ISSUE TITLE
Missing details: AppServiceConnection

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#197]
Relevant API: [Windows.ApplicationModel.AppService.AppServiceConnection](https://github.com/MicrosoftDocs/winrt-api/blob/d7a815fa73e3a4c33dc60ee91f3584eddfcf7211/windows.applicationmodel.appservice/appserviceconnection.md#L0)

After reading the documentation for this class, I have the following questions which I think the documentation should answer:
  - Delivery contract. If I send a message with `SendMessageAsync`, is it guaranteed to be delivered to the recipient? Or are there cases where delivery can fail (e.g. the `AppServiceConnection` closes, the app gets suspended, the app terminates/crashes)? If a message fails to be delivered, how is this communicated to the sender?
  - Event ordering contract. When multiple messages are sent, is `RequestReceived` expected to fire in the same order that the messages were sent? Is it possible for me to get a `RequestReceived` after `ServiceClosed` fires? These answers seem uncertain to me because all I know about `AppServiceConnection's` event contract is that the events fire on thread pool threads. Consequently, it seems plausible to me that different `AppServiceConnection` events could happen to run on different thread pool threads and so the ordering of the event handlers running could depend on the scheduling of the threads. So I'm wondering if `AppServiceConnection's` implementation guarantees an ordering for the running of event handlers.

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thanks @rigdern for bringing this to our attention.

@TylerMSFT can you address this?

**Comment by TylerMSFT** [comment]
Taking up with rigdern offline.

**Comment by TylerMSFT** [comment]
I takled to the devs about this and updated the documentation remarks to read:

Message delivery is not guaranteed. The AppServiceResponseStatus tells you whether delivery succeeded or not.
When multiple messages are sent, RequestReceived is not guaranteed to fire in the same order that the messages were sent. This method is asynchronous, meaning that it will return when the work that needs to be done is complete. No ordering is enforced.
