### ISSUE TITLE
C++/WinRT non standard abstract keyword in class declaration

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#1971]
In the C++ declaration for CryptographicBuffer, it has abstract which is not a standard C++ keyword. Please remove it from the declaration.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a44fcec-c34f-2a72-b4c6-e0fe5d6ac9fb
* Version Independent ID: 2210b862-9250-a6a3-9642-9024aa588452
* Content: [CryptographicBuffer Class (Windows.Security.Cryptography) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.cryptographicbuffer?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Security.Cryptography/CryptographicBuffer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Cryptography/CryptographicBuffer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by stevewhims** [comment]
Hi, @Jaiganeshkumaran, and thanks for filing this issue. The `abstract` keyword appears in the syntax block only when C++/CX is selected (not C++/WinRT). And it is in fact a valid keyword for C++/CX and C++/CLI. I'll go ahead and close the issue.

Thanks!
Steve
