### ISSUE TITLE
404 link error???

### ISSUE THREAD

**Issue by ztarby** [MicrosoftDocs/winrt-api#1973]
Equivalent WinUI constructor: **Microsoft.UI.Xaml.Controls.CaptureElement.CaptureElement.**

when i enter in the link go to a 404 page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a41ab8-e5b2-9f32-a0d7-153a1cc96de2
* Version Independent ID: 12fa1a0c-1b8c-416a-575b-27b6a007bf18
* Content: [CaptureElement Constructor (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.captureelement.-ctor?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/CaptureElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/CaptureElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The link should not have been there and has been removed.
