### ISSUE TITLE
CheckUpdateAvailabilityAsync returns error on 1809 (but it works fine on 1909)

### ISSUE THREAD

**Issue by michalk-gc** [MicrosoftDocs/winrt-api#1974]
When checking the update for the WPF app packaged into MSIX, CheckUpdateAvailabilityAsync method returns result with Extended error: "The .appinstaller file is invalid. (Exception from HRESULT: 0x8008020C)" for machines with Win 10 1809. For other machines which are running 1909, the update is successfully found.
Attaching my appinstaller file (it's default one generated from VS "publish").
[GainCapital.PricingGUI.QAT.Debug_x64.appinstaller.zip](https://github.com/MicrosoftDocs/winrt-api/files/6227730/GainCapital.PricingGUI.QAT.Debug_x64.appinstaller.zip)
I'm using code from example:
```            
_currentPackage = _pm.FindPackageForUser(string.Empty, Package.Current.Id.FullName);
 var result = await _currentPackage.CheckUpdateAvailabilityAsync();
```
 Package.Current.Id.FullName is successfully recognized on both 1809 and 1909. The only difference is for CheckUpdateAvailabilityAsync call. What does this error code mean?

**Comment by Karl-Bridge-Microsoft** [comment]
@mcleanbyron - MSIX reference

**Comment by mcleanbyron** [comment]
I'm sorry you're encountering this problem. Unfortunately, this repo isn't intended to be used for support requests. I recommend that you post this question to the [MSIX discussion forums](https://techcommunity.microsoft.com/t5/msix/ct-p/MSIX). Those forums are managed by members of the product team that develops MSIX-related features, and are visited by many other developers that use MSIX for their application deployments. 

If you are unable to receive help via that forum, the [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
