### ISSUE TITLE
No C++/WinRT example

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/winrt-api#1976]
When this page is in C++/WinRT mode, a C# and C++/CX example is shown, but not a C++/WinRT one. This is against recommendations, which prefer using C++/WinRT for new code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1e0293-4dd3-9057-4e47-da7861c86151
* Version Independent ID: 4b19dea0-4b17-614b-d13d-d7b5556d5012
* Content: [IValueConverter Interface (Windows.UI.Xaml.Data) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Data.IValueConverter?redirectedfrom=MSDN&view=winrt-19041#Windows_UI_Xaml_Data_IValueConverter_Convert_System_Object_Windows_UI_Xaml_Interop_TypeName_System_Object_System_String_)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Data/IValueConverter.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Data/IValueConverter.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Thanks, @sylveon, I've published a C++/WinRT snippet in the topic.

-Steve
