### ISSUE TITLE
little error

### ISSUE THREAD

**Issue by thiagao0860** [MicrosoftDocs/winrt-api#1977]
there is an error in "Set the media source" area, the second code box has c++ code (not XAML).
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b8bdb23-8a5d-4421-dab8-d78f52b95a19
* Version Independent ID: 4c739d1d-a8ba-9b09-71cc-0fd6b04095cf
* Content: [MediaPlayerElement Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.MediaPlayerElement?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaPlayerElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaPlayerElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. The doc has been updated.
