### ISSUE TITLE
ArgumentException in StorageFolder.GetFilesAsync()

### ISSUE THREAD

**Issue by taoyouh** [MicrosoftDocs/winrt-api#198]
The document of [StorageFolder.GetFilesAsync()](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.storage/storagefolder_getfilesasync_819750470.md/#systemunauthorizedaccessexception) says that it only throws UnauthorizedAccessException. But it also throws ArgumentException (while there are no arguments) without meaningful message. 

Sample code:
```
        private async void GetFiles()
        {
            var storageItems = await Clipboard.GetContent().GetStorageItemsAsync();
            foreach(var item in storageItems)
            {
                if (item is StorageFolder folder)
                {
                    await folder.GetFilesAsync();
                }
            }
        }
```
Exception

> System.ArgumentException:“Value does not fall within the expected range.”

OS version: Windows 10 16299.19
Target version: Windows 10 build 15063
Minimum version: Windows 10 build 15063
Microsoft.NETCore.UniversalWindowsPlatform package version: 5.4.0/5.4.1/6.0.1

**Comment by ginami** [comment]
Thanks @taoyouh for bringing this to our attention.

@laurenhughes can you address this?

**Comment by laurenhughes** [comment]
Thanks for the feedback! I'll investigate this with the dev team and get any other common exceptions documented for the GetFilesAsync methods.
