### ISSUE TITLE
Use in unpackaged Win32 app returns same ID for all such apps

### ISSUE THREAD

**Issue by RonaldAi** [MicrosoftDocs/winrt-api#1980]
This API uses the publisher ID of the app package and mixes it with a firmware/hardware derived identifier. If there is no app package associated with the app, as it would be the case for unpackaged Win32 apps, the generated ID is the same for all such apps. This is expected behavior.
The website should mention this behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46d46e32-c340-3552-868d-b32b606ce5d9
* Version Independent ID: 439329b8-8135-a92d-c05c-555a408064bd
* Content: [SystemIdentification Class (Windows.System.Profile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.System.Profile/SystemIdentification.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.Profile/SystemIdentification.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Just made these updates, they should publish shortly.
