### ISSUE TITLE
Filter Description could be more specific

### ISSUE THREAD

**Issue by Steffel** [MicrosoftDocs/winrt-api#1983]
I do not completely understand how a filter works. In my test i receive advertisements with "Local Names". Adding a filter with a given Serice Guid results in receiving only those ads, but without the Local Name. Does the filter affect not only which advertisements i get, but also filters the content of an advertisement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2196a4e7-6c78-7f0b-4951-bf9bf04c32ee
* Version Independent ID: 697f9ae0-5d80-3867-902f-c84b4c5d0eb0
* Content: [BluetoothLEAdvertisementWatcher Class (Windows.Devices.Bluetooth.Advertisement) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisementWatcher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.Advertisement/BluetoothLEAdvertisementWatcher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Steffel. I've contacted the feature team to see whether this is a case where we need to add more info to the docs. If so, then I'll add more content about how filters work.

-Steve

**Comment by stevewhims** [comment]
Hi, @Steffel, I've added the following paragraph to the Remarks section of the [BluetoothLEAdvertisementFilter class](https://docs.microsoft.com/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementfilter) topic.

A Bluetooth LE advertisement filter is applied to an advertisement event packet, and not to the device/source of the advertisement as a whole. The same device can broadcast advertisement packets with different payloads at the same time. For example, it's common for the local name to be in a different advertisement packet from the packet containing the service UUID. So, with a filter set to service UUID, the packet with local name won't be available (only packets with both service UUID and local name will be available in that case).

-Steve

**Comment by stevewhims** [comment]
I'll go ahead and close; looks like this issue is resolved.

Thanks!
Steve
