### ISSUE TITLE
Explain how to set CalendarView blackout dates

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#1989]
The Xaml [CalendarView](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.CalendarView) control supports blackout dates; dates that the user can't select. You can configure the color of those dates using the [CalendarView.BlackoutForeground](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.CalendarView.BlackoutForeground) property. But the documentation doesn't explain how to make a day a blackout date.

The process is to listen to the [CalendarView.CalendarViewDayItemChanging](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.CalendarView.CalendarViewDayItemChanging) event, and in the event args set the [CalendarViewDayItem.IsBlackout](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.CalendarViewDayItem.IsBlackout) property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f49ec47-cba4-18b6-ad8a-8b6987639681
* Version Independent ID: ffbccdff-b1da-ef61-69ce-80918831bec2
* Content: [CalendarView.BlackoutForeground Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CalendarView.BlackoutForeground?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/CalendarView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/CalendarView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This is talked about and shown in the examples on the [CalendarView](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.calendarview#updating-calendar-day-items) class page and the [design guidance page](https://docs.microsoft.com/windows/uwp/design/controls-and-patterns/calendar-view#updating-calendar-day-items). It's also mentioned on the [CalendarViewDayItem](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.calendarviewdayitem#remarks) class page.

**Comment by oldnewthing** [comment]
I think a cross-reference from the BlackoutForegroundBrush properties would help people find the sample code.

> ## Remarks
>
> To mark a date as not selectable, set the `IsBlackout` property to True. For more information, see [Updating calendar day items](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendarview?view=winrt-19041#updating-calendar-day-items).

**Comment by jwmsft** [comment]
Added links between relevant docs as suggested.
