### ISSUE TITLE
The Windows Web App example for the manifest does not comply with the xml schema

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#199]
Referring to winrt-api/windows.applicationmodel/startuptask.md 

It says there is no "StartupPage" attribute declared under \<uap5:StartupTask\> tag when compiling confirmed here: https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-startuptask

Shouldn't the "StartupPage" actually be the "StartPage" attribute under \<uap5:Extension\> tag?

Like this:

        <uap5:Extension Category="windows.startupTask" StartPage="EntryPage">
          <uap5:StartupTask
            TaskId="MyStartupId"
            DisplayName="Test startup"  />            
        </uap5:Extension>

**Comment by TylerMSFT** [comment]
Hi,
Thank you for catching that. The fix to the topic will be live Monday or Tues. (12/11, 12/12)
