### ISSUE TITLE
VpnSystemHealth.StatementOfHealth: Which RFC?

### ISSUE THREAD

**Issue by Onkelborg** [MicrosoftDocs/winrt-api#1991]
For VpnSystemHealth.StatementOfHealth, it mentions that it returns a "RFC compliant blob" - but what RFC(s)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69b05e65-3119-7504-6329-f49c520834f7
* Version Independent ID: 0c447886-7d2d-099e-51a2-4311ea1c115e
* Content: [VpnSystemHealth.StatementOfHealth Property (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnsystemhealth.statementofhealth?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Networking.Vpn/VpnSystemHealth.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.Vpn/VpnSystemHealth.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Onkelborg, I've reached out to the feature team for more info.

-Steve

**Comment by stevewhims** [comment]
Hi, @Onkelborg, we're still investigating the exact relation between the blob and any RCF/standard; meanwhile we've removed the content that describes the blob as RFC-compliant. If I hear more info about the blob in future I'll add it to the topic.

Thanks!
Steve
