### ISSUE TITLE
AppointmentStore.StoreChanged Event Fires More than once when adding Appointment

### ISSUE THREAD

**Issue by TheJoeFin** [MicrosoftDocs/winrt-api#1992]
When an Appointment is added to the AppointmentStore the Changed event fires 4 times. First for AppointmentCreated event then three more times for "AppointmentModified"

Why might this be happening? Is there a way to improve my usage of AppointmentStore to get a single AppointmentCreated when adding a single Appointment to a calendar?

I have created an AppointmentService to keep a single instance of the AppointmentStore in my app, but I still get multiple events when adding a single Appointment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce1a6979-e383-430b-d0f5-ab99e109a2ed
* Version Independent ID: 1a7b955a-70e9-d017-32a1-75d85d36f33b
* Content: [AppointmentStore.StoreChanged Event (Windows.ApplicationModel.Appointments) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appointments.appointmentstore.storechanged?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Appointments/AppointmentStore.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Appointments/AppointmentStore.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. Could you ask this over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html)? I'm thinking you could get a faster answer there. Unfortunately, our scope in this channel covers specific documentation fixes. Hope you can get an answer there.
