### ISSUE TITLE
Rgba16 R16B16G16A16 Typo?

### ISSUE THREAD

**Issue by fitdev** [MicrosoftDocs/winrt-api#1996]
Shouldn't: 
`Rgba16 	12 	The pixel format is R16B16G16A16 unsigned integer.` be
`Rgba16 	12 	The pixel format is R16G16B16A16 unsigned integer.` instead?
This also applies to intellisense comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61471287-99cb-ab13-5d3a-23055b440978
* Version Independent ID: 02be283a-386d-bb4e-7395-a22b383f9d48
* Content: [BitmapPixelFormat Enum (Windows.Graphics.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.bitmappixelformat?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Imaging/BitmapPixelFormat.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Imaging/BitmapPixelFormat.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching this. This has been updated in the source and should be updated on the live site later today.
