### ISSUE TITLE
EasingDoubleKeyFrame docs should mention the default easing function

### ISSUE THREAD

**Issue by bschoepke** [MicrosoftDocs/winrt-api#200]
I noticed that in a XAML app, if you create an animation with an EasingDoubleKeyFrame but don't specify an easing function via the EasingFunction property, the system applies a default Bezier curve. This was unexpected since you would expect a linear ease in this case.

Please document what the default easing function will be if you do not supply one.

**Comment by ginami** [comment]
Thank you @bschoepke for bringing this to our attention.

@jwmsft can you please respond?

**Comment by jevansaks** [comment]
@stmoy can you help update the docs?

**Comment by stmoy** [comment]
I've updated the [EasingDoubleKeyFrame doc](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Animation.EasingDoubleKeyFrame).
