### ISSUE TITLE
C++/WinRT Doc of BitmapTypedValue inaccurate?

### ISSUE THREAD

**Issue by creambyemute** [MicrosoftDocs/winrt-api#2000]
I have tried all the ways I know of to initialize a value/call a function/constructor for BitmapTypedValue and none of them seems to work. 

If I missed one, let me know, I'm pretty new to C++.

* `new BitmapTypedValue(1.0, PropertyType::Single)` keyword doesn't work
* `BitmapTypedValue::BitmapTypedValue(1.0, PropertyType::Single)` doesn't work
* `BitmapTypedValue(1.0, PropertyType::Single)` doesn't work
* Tried various `BitmapTypedValue myValue{ ... }` notations, doesn't work
* `BitmapTypedValue.BitmapTypedValue(1.0, PropertyType::Single)`

I have given up trying to set a BitmapPropertySet for my BitmapEncoder as I don't know how this BitmapTypedValue can be created/initialized without one of the following compiler errors:

* `error C2664: 'winrt::Windows::Graphics::Imaging::BitmapTypedValue::BitmapTypedValue(void *,winrt::take_ownership_from_abi_t) noexcept': cannot convert argument 1 from 'float' to 'void *'`
* `error C2665: 'winrt::Windows::Graphics::Imaging::BitmapTypedValue::BitmapTypedValue': none of the 5 overloads could convert all the argument types`
* `error C2440: 'initializing': cannot convert from 'initializer list' to 'winrt::Windows::Graphics::Imaging::BitmapTypedValue'`

Any chance of adding an example there? It's the only class I've yet failed to initialize a value from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aa4c50d-de75-4633-f932-daec8ee482f6
* Version Independent ID: f9500efb-a6e8-3a12-6eca-b55e1cf0bfc6
* Content: [BitmapTypedValue Class (Windows.Graphics.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.bitmaptypedvalue?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Imaging/BitmapTypedValue.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Imaging/BitmapTypedValue.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, I was able to new up this class using the following code:
```
auto btv = BitmapTypedValue(box_value(1.0), winrt::Windows::Foundation::PropertyType::Single);
```
For more information on boxing and unboxing primitive types, see [Boxing and unboxing values to IInspectable with C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/boxing)
