### ISSUE TITLE
What is wrong with you people?

### ISSUE THREAD

**Issue by barrettd** [MicrosoftDocs/winrt-api#2004]
Get some C++ WinRT documentation in here please.
For example: Windows::Storage::AccessCache is undefined, but 
C# Windows.Storage.AccessCache is in your examples.

Developers waste most of our time with your bad docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00d969e2-4e21-aedb-2b52-8e1515c530df
* Version Independent ID: 4e660224-7319-066e-15b5-7c02b2a05dd0
* Content: [StorageApplicationPermissions.FutureAccessList Property (Windows.Storage.AccessCache) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageapplicationpermissions.futureaccesslist?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Storage.AccessCache/StorageApplicationPermissions.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.AccessCache/StorageApplicationPermissions.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by stevewhims** [comment]
Hi, @barrettd, and apologies for the delay in acknowledging this issue.

I found four topics in this namespace that have C# code snippets in them, so I added C++/WinRT versions of those snippets. Those new snippets should appear on the live site soon. I'll come back here and update this comment when they're live.

**UPDATE**: The new snippets are now live.

-Steve
