### ISSUE TITLE
missing await letter in doc

### ISSUE THREAD

**Issue by ghost1372** [MicrosoftDocs/winrt-api#2007]
The letter **a** is missing in `await`

https://github.com/MicrosoftDocs/winrt-api/blob/docs//windows.system/launcher_launchfileasync_1594978114.md

https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher.launchfileasync?view=winrt-20348

![Untitled](https://user-images.githubusercontent.com/9213496/119780685-5fd96800-bedf-11eb-93c6-12104a992238.png)

**Comment by GrantMeStrength** [comment]
The MD file looks like it's correct. Investigating.

**Comment by GrantMeStrength** [comment]
Correction is now live, thanks!
