### ISSUE TITLE
The remarks on DesiredResolution need clarification

### ISSUE THREAD

**Issue by simon-knuth** [MicrosoftDocs/winrt-api#2009]
The remarks on DesiredResolution seem a little imprecise to me and I'm not sure whether my English skills are to blame here. Currently, the text looks like this:

> ### Remarks
> This property value can be [MinResolution](https://docs.microsoft.com/en-us/uwp/api/windows.devices.scanners.imagescannerflatbedconfiguration.minresolution?view=winrt-20348#Windows_Devices_Scanners_ImageScannerFlatbedConfiguration_MinResolution), [MaxResolution](https://docs.microsoft.com/en-us/uwp/api/windows.devices.scanners.imagescannerflatbedconfiguration.maxresolution?view=winrt-20348#Windows_Devices_Scanners_ImageScannerFlatbedConfiguration_MaxResolution), or [OpticalResolution](https://docs.microsoft.com/en-us/uwp/api/windows.devices.scanners.imagescannerflatbedconfiguration.opticalresolution?view=winrt-20348#Windows_Devices_Scanners_ImageScannerFlatbedConfiguration_OpticalResolution). But, if your app sets this value to other resolutions, this property will choose the closest resolution values. See [ActualResolution](https://docs.microsoft.com/en-us/uwp/api/windows.devices.scanners.imagescannerflatbedconfiguration.actualresolution?view=winrt-20348#Windows_Devices_Scanners_ImageScannerFlatbedConfiguration_ActualResolution) property.

This led me to believe that setting the DesiredResolution to an arbitrary ImageScannerResolution using `config.DesiredResolution = new ImageScannerResolution { DpiX = 123, DpiY = 456 };` would result in the scanner using the closest value out of MinResolution, MaxResolution, and OpticalResolution. But in reality, the resulting resolution can apparently be **none of those three** constants, which is then reflected in ActualResolution.
For instance, these three constants are 150, 600 and 600 for my scanner's flatbed. But when I set DesiredResolution to a value in [250, 449] the scanner will scan with a DPI setting of 300, which is also reflected in ActualResolution.

In my opinion, these remarks should be clarified. Additionally, the page on ActualResolution could also be improved with a better summary of its function. This entire confusion caused a lot of frustration for the users of my application since I only offered a subset of the available DPI options, so perhaps a change might help others in the future.

**Please note:** I submitted this feedback for ImageScannerFlatbedConfiguration, but the same applies to ImageScannerFeederConfiguration. If changes were to be made, they'd be required twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22958dda-b30b-38e2-96ab-e47b708aeffd
* Version Independent ID: 292feb15-21d0-30a2-53f5-cf5becce15b1
* Content: [ImageScannerFlatbedConfiguration.DesiredResolution Property (Windows.Devices.Scanners) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.scanners.imagescannerflatbedconfiguration.desiredresolution?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Devices.Scanners/ImageScannerFlatbedConfiguration.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Scanners/ImageScannerFlatbedConfiguration.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @simon-knuth, and thanks for filing this issue. Yes, that content does look like it could use some clarification. I've created a work item for myself internally, and I'll get to that when I can. Meanwhile (so that we're not tracking work twice) I'll close this issue, and I'll reopen when I begin to work on it. Then when the updates are live I'll resolve it.

Thanks again!
Steve

**Comment by stevewhims** [comment]
**UPDATE**: I've pinged the feature team for more info.

**Comment by stevewhims** [comment]
The improvements are now live. I made changes to the DesiredResolution and ActualResolution properties for both configuration types. I'll leave this open for a while in case you want to comment.

-Steve

**Comment by stevewhims** [comment]
I'll go ahead and close. Thank you!

Steve
