### ISSUE TITLE
Language interface section isn't rendering properly

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#201]
The documentation shows method declarations in each supported language and has sections labeled `C++`, `C#`, `VB`, and `JavaScript`.

I would expect each declaration to appear under the section for the appropriate language.

Instead, all of the declarations appear under the `JavaScript` section.

Additionally, the "Copy" buttons don't appear to work. When I click the "Copy" button for `C++` this is what is copied to my clipboard: `// You can use this method in JavaScript.`.

Here's an example screenshot from [Windows.ApplicationModel.AppService.AppServiceConnection](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appservice.appserviceconnection#Windows_ApplicationModel_AppService_AppServiceConnection_OpenRemoteAsync_Windows_System_RemoteSystems_RemoteSystemConnectionRequest_):

![image](https://user-images.githubusercontent.com/199935/31919508-cfaadaf6-b817-11e7-9018-8b9aa470146d.png)

Adam Comella
Microsoft Corp.

**Comment by mcleblanc** [comment]
Thank you for raising this issue. The root cause has been addressed and the documentation is again exhibiting the correct language selection and Copy behaviors.
