### ISSUE TITLE
Operations such as copy, move, and rename

### ISSUE THREAD

**Issue by JPTGamesAndApps** [MicrosoftDocs/winrt-api#2017]
Hello,

The documentation states that FolderInformation class lets the app perform operations such as copy, move, and rename. However, it only has rename method and no copy or move method.

"Provides synchronous access to the properties exposed off StorageFolder and lets an app perform asynchronous management operations such as **copy, delete,** move, and rename."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e817ee-0eae-20e6-89bd-e3869defba2b
* Version Independent ID: 712f5344-a7a3-e1e8-6098-a42228451c1c
* Content: [FolderInformation Class (Windows.Storage.BulkAccess) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.bulkaccess.folderinformation?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Storage.BulkAccess/FolderInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.BulkAccess/FolderInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for pointing this out. A fix has been made and the changes should be live soon. Thanks once again!
