### ISSUE TITLE
Are there any commercial cameras out there that support these Camera Manual Control capabilities?

### ISSUE THREAD

**Issue by Tam66662** [MicrosoftDocs/winrt-api#2021]
I have tried to get this Microsoft "[CameraManualControls](https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/cameramanualcontrols/)" UWP sample app to work with my built-in Lenovo Thinkpad T490 integrated camera, and even an external USB Logitech C930e webcam.  I even tried a proprietary camera that another company is working on.  But none of these devices show that they support any of the VideoDeviceController capabilities (Exposure, White Balance, Focus, ISO, Zoom, etc.).  I have checked the code, and it complies with the Remark from this section to ensure that the preview has started before checking, but it doesn't seem to ever detect support.

Are there any cameras out there that do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94963b1f-9bfd-d42c-62a8-8645436985ff
* Version Independent ID: e7ab86cc-aec2-8468-1b24-9db6f86aff58
* Content: [MediaCapture.VideoDeviceController Property (Windows.Media.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture.videodevicecontroller?view=winrt-20348#Windows_Media_Capture_MediaCapture_VideoDeviceController)
* Content Source: [winrt-api-build/xml/Windows.Media.Capture/MediaCapture.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Capture/MediaCapture.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by Tam66662** [comment]
@drewbatgit , I'm still hoping to get an answer on this.  I just want one example of a camera that this works on, so that I can buy it and test it.  There is no information in this documentation that points to identifying possible hardware that supports these camera capabilities that Microsoft exposes.

**Comment by drewbatgit** [comment]
@Tam66662 Sorry for the delay on this! I have reached out to the camera team and will let you know what I find out.

**Comment by drewbatgit** [comment]
So, unfortunately it doesn't seem like there is a lot of support for these controls now Windows is no longer creating mobile devices. So far it's been suggested that Surface Laptop 3 supports some of the advanced controls – WhiteBalanceControl and ExposureControl. And some web cams may support the tap-to-focus functionality of the focus control.

**Comment by Tam66662** [comment]
@drewbatgit This is surprising to me considering this is a UWP camera sample app, which I thought had many more applicable usages than just for mobile devices.  But regardless, thank you for the response.  I consider this query of mine to be closed now.
