### ISSUE TITLE
C++/WinRT version of CoreDispatcher page suggests using C#-only types.

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/winrt-api#2024]
When I open this page with C++/WinRT selected at the top right, I still get suggested to use TaskCompletionSource in the remarks, which is a C#-only API which I cannot use, and you also get directed towards an extension method that's C#-only. The documentation should suggest a C++ API, and also use a C++ snippet in the remarks, not a C# snippet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331adaef-1035-fd88-0d7b-ca4ff97ee761
* Version Independent ID: 173e41e3-b747-cf7b-9b43-3d678f21eacb
* Content: [CoreDispatcher.RunAsync(CoreDispatcherPriority, DispatchedHandler) Method (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.runasync?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.UI.Core/CoreDispatcher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Core/CoreDispatcher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@stevewhims, can you take a look at this? Thanks

**Comment by stevewhims** [comment]
Hi, @sylveon. There is a way to implement a completion source type in C++/WinRT. Kenny Kerr has an implementation of one here: https://gist.github.com/kennykerr/2a5b5995d0b2d9a0b646218d6a6cecb7.

It's just a sample, so it's been only lightly tested. And it doesn't include cancelation nor error propagation. But it might be useful in its current form.

I've created a backlog work item for myself to write up that completion_source type in the C++/WinRT docs. When I get around to that, I'll come back here and update this topic to point to the new content, and to make it clear which parts of the topic apply to which language projections. That work item has a link to this GitHub issue, so I can come back here.

So as not to track the work in two places, I'll go ahead and close this for now, but I'll update it in future.

Thanks!
Steve

**Comment by stevewhims** [comment]
Ok, I've fixed the topic (I believe). Please let me know if that looks correct.

Thanks!
Steve

**Comment by sylveon** [comment]
Yep, looks good to me.
