### ISSUE TITLE
Confusing content on this UWP control page indicating that there is an Equivalent control in WinUI.

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#2025]
At the top of this page and many other control pages within UWP reference there is a mention that the control is an equivalent of a counterpart control in WinUI. Which entering into that link I find that it refers to WinUI 3 which is still in pre-release version.

Documentation should be clear in that as it is confusing in the current state of things, where WinUI 2.6 was just release with updates on styles for many controls including those that are not yet part of WinUI 2.6. Please add a clarifying notes that those equivalent notices only applies to WinUI 3, or remove them and don't mixed pre-release SDK content with release documentation, this is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a184d49-6889-2082-f5ea-5c651f40e429
* Version Independent ID: f220e171-6cbb-aca9-6324-0c7ae55bc3aa
* Content: [ListView Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listview?view=winrt-20348&source=docs)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ListView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ListView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. @Karl-Bridge-Microsoft is working on this issue, and we hope to have these notes updated soon.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks! These links should now be cleaned up across the UWP docs. Please open a new issue if not.
