### ISSUE TITLE
It exists and that's it

### ISSUE THREAD

**Issue by tmcmi** [MicrosoftDocs/winrt-api#2026]
Like so many recent APIs, there is effectively no documentation beyond their existence.
How about an example of two for a start.
The entire library lacks any documentation on using with WinForms, leaving users to wade through the usual mass of dysfunctional open source stuff, and unanswered forum posts about it not working.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d36ab5-5fb1-ad6b-f757-0e40eccf8f3a
* Version Independent ID: a723dd3e-72ea-3d04-2291-084d528c6b38
* Content: [OcrLine Class (Windows.Media.Ocr) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr.ocrline?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Media.Ocr/OcrLine.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Ocr/OcrLine.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your comment, we will add the request for more documentation for this feature to our list of potential future work. In the mean time, there's some information on the [windows.media.ocr](https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr) namespace page:

For sample code illustrating the usage of these APIs, check out the Windows Universal Sample:
https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/OCR

For information on using OCR in Windows Forms:

APIs in the Windows.Media.Ocr namespace are only supported for desktop apps with package identity. This means that the app is installed and run from an MSIX package. For more information, see [Features that require package identity](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-packaged-apps). For information about calling these APIs from a desktop app, see [Call Windows Runtime APIs in desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance).

**Comment by tmcmi** [comment]
Hi,

Thanks for the link to a 404 page. That confirmed my suspicions about the quality of the documentation.
I have coaxed it into life, but it really should have taken a lot less time.

Best regards
Tim Irons

**Comment by drewbatgit** [comment]
Very sorry for the copy/paste error. This is the correct link: https://docs.microsoft.com/en-us/uwp/api/windows.media.ocr?view=winrt-20348
