### ISSUE TITLE
Wish.com

### ISSUE THREAD

**Issue by Midenight07** [MicrosoftDocs/winrt-api#2028]
#1488 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ca863cb-9069-f28a-2245-11ac7edeb5a4
* Version Independent ID: a43b508e-197a-dce9-97ae-620c08fde1e8
* Content: [EccCurveNames.Curve25519 Property (Windows.Security.Cryptography.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core.ecccurvenames.curve25519?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Security.Cryptography.Core/EccCurveNames.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Cryptography.Core/EccCurveNames.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by mqudsi** [comment]
Spam
