### ISSUE TITLE
I want my operating system's user preference format for datetime, numbers, etc.

### ISSUE THREAD

**Issue by Alemvik** [MicrosoftDocs/winrt-api#2038]
I want my OS/user preference format

**Comment by GrantMeStrength** [comment]
Hi! This is the feedback mechanism for dealing with issue related to Windows developer documentation. 
Do you have a specific request related to the docs?
Would the Q&A Forum be a better location to ask your question? https://docs.microsoft.com/en-us/answers/index.html
I will close this now, but if you have a specific doc issue feel free to re-open.
thanks!
-John
