### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#2039]
Missing 'd' in the following:

Factors inclue the traffic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedb9559-6da0-2e91-eaef-12d9e9bfff4f
* Version Independent ID: cf9ff409-0028-5b6c-b77e-3987ad23671d
* Content: [BluetoothLEDevice.FromBluetoothAddressAsync Method (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync?view=winrt-20348#Windows_Devices_Bluetooth_BluetoothLEDevice_FromBluetoothAddressAsync_System_UInt64_)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @olivier-basille, I have a fix for this on its way. It should be live soon but I'll keep an eye on it.

-Steve
