### ISSUE TITLE
ContentDialog doesn't work in non-XAML application

### ISSUE THREAD

**Issue by dfields-msft** [MicrosoftDocs/winrt-api#2046]
I tried using this API in my non-XAML UWP application given the note on the MessageDialog API which indicates that this API is preferred for new applications. However, the constructor throws an "invalid thread" exception even though I'm calling it on my application's UI thread. Presumably this is because XAML isn't initialized? However, the documentation does not mention this caveat, or explain how an application could successfully use the API if it's not a fully-XAML app in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16c14008-04b3-438b-5fae-3577cf233ab9
* Version Independent ID: 52f2f07b-034e-1d24-1b48-b4de7585e71a
* Content: [ContentDialog Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ContentDialog.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ContentDialog.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for raising this issue. Because ContentDialog is a XAML control, it only works in a XAML app. I've updated the note on MessageDialog to say that ContentDialog is preferred for apps that use XAML.
