### ISSUE TITLE
MessageDialog docs should mention that IInitializeWithWindow (for C++) and WinRT.Interop.InitializeWithWindow (for C#) can be used in Win32 and WinUI desktop apps

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/winrt-api#2047]
Currently, this API is hardly discoverable (the only mention is [a note in the docs of IInitializeWithWindow itself](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-iinitializewithwindow#when-to-use) and some blog posts from MS employees) and makes users confused, especially when porting from existing UWP code (because it used to just work). I recommend documenting this better, even if ContentDialog is preferred now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98917bf5-5779-c5f2-24d2-685fd146da03
* Version Independent ID: 4248371e-a3b0-d130-9c1e-310b88ab8d91
* Content: [MessageDialog Class (Windows.UI.Popups) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Popups.MessageDialog?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.UI.Popups/MessageDialog.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Popups/MessageDialog.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by mcleanbyron** [comment]
Thanks for opening this issue. We have made several improvements:

- The [MessageDialog remarks](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Popups.MessageDialog?view=winrt-20348#remarks) now has a note about the IInitializeWithWindow usage in desktop apps.
- We added new [general guidance about the IInitializeWithWindow pattern](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#classes-that-use-iinitializewithwindow).
