### ISSUE TITLE
Need code examples

### ISSUE THREAD

**Issue by verakot** [MicrosoftDocs/winrt-api#2048]
Need C# code examples for this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a05df98-9097-754c-4f8e-0a3b277ed5a7
* Version Independent ID: 405cca73-bc63-ce19-69ec-8a460156857a
* Content: [BluetoothLEDevice Class (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @verakot, and thanks for filing this issue.

For sample apps, see [Bluetooth Low Energy sample](https://docs.microsoft.com//samples/microsoft/windows-universal-samples/bluetoothle/) and [Device enumeration and pairing sample](https://docs.microsoft.com//samples/microsoft/windows-universal-samples/deviceenumerationandpairing/).

I'm in the process of adding that info to the topic. That change should be live shortly, but leave it with me and I'll make sure it goes live.

Thanks!
Steve
