### ISSUE TITLE
About Direct3D11CaptureFramePool：Does it capture only one process at a time?

### ISSUE THREAD

**Issue by Lookforworld** [MicrosoftDocs/winrt-api#2049]
### **I need to capture multiple programs at the same time,is there any way to do this?Thanks!**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4a51697-abc4-136a-aa3a-b16738c81be1
* Version Independent ID: 88990055-3a59-4914-94fc-36228aee488c
* Content: [Direct3D11CaptureFramePool Class (Windows.Graphics.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.direct3d11captureframepool?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Capture/Direct3D11CaptureFramePool.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Capture/Direct3D11CaptureFramePool.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello! There's nothing built into the API to allow you to capture multiple windows at once, but you should be able to have multiple captures going at once by implementing your code to create multiple capture sessions. The developer I spoke to noted that there was a bug in previous releases where only one could effectively be active, but that should be fixed as of spring of 2020.
