### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by softwareschreiber** [MicrosoftDocs/winrt-api#2050]
Ein kurzes Code Beispiel ist 1000 mal besser als ein Link auf ein GitHub Repository. Wer hat denn noch die Zeit, das ganze Projekt herunter zu laden und zu durchsuchen. Das war mal deutlich besser.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 52c1aeee-9b21-dd0b-8766-57f4beb51fbe
* Version Independent ID: b8830c41-14ab-89d6-bc52-92001727ef7c
* Content: [StorageFolder Klasse (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/de-de/uwp/api/windows.storage.storagefolder?view=winrt-20348)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build.de-DE?path=/winrt-api-build/xml/Windows.Storage/StorageFolder.xml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build.de-DE?path=/winrt-api-build/xml/Windows.Storage/StorageFolder.xml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **lastnameholiu**
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Thank you for your feedback. We are currently planning on adding more sample code, not just links, to the docs wherever we can. -John
