### ISSUE TITLE
in-use description needs updating for MulticaseOnly

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/winrt-api#2061]
The note about exclusive use is obsolete. Win10 added Control.MulticastOnly which allows ports to be opened by more than one app (for multicast).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044e6b1c-5647-9732-d25a-31da179662a1
* Version Independent ID: ec9c39da-104b-c7f9-c514-574bbff2d9a0
* Content: [DatagramSocket.BindEndpointAsync(HostName, String) Method (Windows.Networking.Sockets) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.datagramsocket.bindendpointasync?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Networking.Sockets/DatagramSocket.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.Sockets/DatagramSocket.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @amp64, the fix is now live.

-Steve
