### ISSUE TITLE
FrameInputNodeQuantumStartedEventArgs::RequiredSamples() actually returns the required frames

### ISSUE THREAD

**Issue by tom-huntington** [MicrosoftDocs/winrt-api#2062]
`FrameInputNodeQuantumStartedEventArgs::RequiredSamples()` actually returns the required frames (for stereo audio each frame has two samples). 
 
Maybe this should be mentioned in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8c0685-eb23-d381-ddf9-94f0eb4a1e71
* Version Independent ID: 0dab0daf-8035-5c47-9e6a-da607a6dbeab
* Content: [FrameInputNodeQuantumStartedEventArgs Class (Windows.Media.Audio) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Audio.FrameInputNodeQuantumStartedEventArgs?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Media.Audio/FrameInputNodeQuantumStartedEventArgs.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Audio/FrameInputNodeQuantumStartedEventArgs.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for catching this. The documentation has been updated to reflect this.
