### ISSUE TITLE
Link to "Haptic Usage Page" is not working

### ISSUE THREAD

**Issue by gabrielsanbrito** [MicrosoftDocs/winrt-api#2063]
Hi,

The link for the "Haptics Usage Page" in all KnownSimpleHapticsControllerWaveforms properties pages seems to be broken ([BuzzContinuous](https://docs.microsoft.com/en-us/uwp/api/windows.devices.haptics.knownsimplehapticscontrollerwaveforms.buzzcontinuous?view=winrt-20348), [Click](https://docs.microsoft.com/en-us/uwp/api/windows.devices.haptics.knownsimplehapticscontrollerwaveforms.click?view=winrt-20348), [Press](https://docs.microsoft.com/en-us/uwp/api/windows.devices.haptics.knownsimplehapticscontrollerwaveforms.press?view=winrt-20348), [Release](https://docs.microsoft.com/en-us/uwp/api/windows.devices.haptics.knownsimplehapticscontrollerwaveforms.release?view=winrt-20348), and [RumbleContinuous](https://docs.microsoft.com/en-us/uwp/api/windows.devices.haptics.knownsimplehapticscontrollerwaveforms.rumblecontinuous?view=winrt-20348)). Is this the correct one? https://www.usb.org/developers/hidpage/HUTRR63b_-_Haptics_Page_Redline.pdf

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946c2e57-0f20-a2d1-4a15-54935bb3035e
* Version Independent ID: 0aa9e8df-ed5d-af5b-bd87-bf132b7e6222
* Content: [KnownSimpleHapticsControllerWaveforms.Press Property (Windows.Devices.Haptics) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.haptics.knownsimplehapticscontrollerwaveforms.press?view=winrt-20348#Windows_Devices_Haptics_KnownSimpleHapticsControllerWaveforms_Press)
* Content Source: [winrt-api-build/xml/Windows.Devices.Haptics/KnownSimpleHapticsControllerWaveforms.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Haptics/KnownSimpleHapticsControllerWaveforms.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for reporting this. The links seem to be working now.
