### ISSUE TITLE
Suggest specifying whether alpha value in the color parameter is applied or not.  My test reveals it doesn't.

### ISSUE THREAD

**Issue by ClintMayers** [MicrosoftDocs/winrt-api#2065]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 264ae508-c404-1dc0-d2f2-26e81978d7d6
* Version Independent ID: 89d390e2-e6e6-12ba-1371-d1a50c231353
* Content: [MediaClip.CreateFromColor(Color, TimeSpan) Method (Windows.Media.Editing) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.editing.mediaclip.createfromcolor?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Media.Editing.MediaClip.CreateFromColor);k(TargetFrameworkMoniker-.NETCore,Version%253Dv5.0);k(DevLang-csharp)%26rd%3Dtrue&view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Media.Editing/MediaClip.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Editing/MediaClip.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reporting this! I tested this myself and verified that the alpha component isn't used. I've updated the documentation with a remark noting this behavior.
