### ISSUE TITLE
Wrong implements class name for Close

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#2067]
In docs pages for derived classes that implement IClosable like this page, the Close method's page shows that it implements System.IDisposable.Close which is incorrect. It should say Windows.Foundation.IClosable.Close instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33cd3440-09dc-ba8d-6dc9-5a9617a4e447
* Version Independent ID: 39a632f3-7ac4-b65f-189f-a15390c00643
* Content: [DataWriter.Close Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datawriter.close?view=winrt-20348#Windows_Storage_Streams_DataWriter_Close)
* Content Source: [winrt-api-build/xml/Windows.Storage.Streams/DataWriter.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Streams/DataWriter.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Steve - would you mind taking a look to see if this bug is something we can fix? Thank you.

**Comment by stevewhims** [comment]
Thanks, @JaiganeshKumaran!

> the Close method's page shows that it implements System.IDisposable.Close which is incorrect.

It says `System.IDisposable.Close` only if the language selected in the language picker is C#. And in that case it's arguably correct.

> It should say Windows.Foundation.IClosable.Close instead.

It says `Windows.Foundation.IClosable.Close` if the language selected in the language picker is C++/WinRT.

I think that what we have now is good. I'll go ahead and optimistically close this issue, but please let me know if you disagree.

Thanks!
-Steve

**Comment by jaigak** [comment]
> Thanks, @JaiganeshKumaran!
> 
> > the Close method's page shows that it implements System.IDisposable.Close which is incorrect.
> 
> It says `System.IDisposable.Close` only if the language selected in the language picker is C#. And in that case it's arguably correct.
> 
It's not correct; it's System.IDisposable.**Dispose** not Close. Dispose is already shown as a separate method.
<img width="394" alt="Screenshot 2024-04-23 at 00 17 00" src="https://github.com/MicrosoftDocs/winrt-api/assets/45227503/e263107f-dbcc-4223-a6d1-9b2d1929f355">
