### ISSUE TITLE
BitmapPlaneDescription::Stride does not state whether it is measured in pixels or bytes

### ISSUE THREAD

**Issue by dmachaj** [MicrosoftDocs/winrt-api#2068]
This is a very important detail when it comes to copying bitmap memory around.  Is the stride measured in pixels or bytes?  Misunderstanding of this will result in 2x, 4x, or 8x memory overflow or underflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a468ca4c-bfae-18b3-da04-7cc0f8546430
* Version Independent ID: 65a451b0-705b-965e-f3e3-9af61055d873
* Content: [BitmapPlaneDescription.Stride Field (Windows.Graphics.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.bitmapplanedescription.stride?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Imaging/BitmapPlaneDescription.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Imaging/BitmapPlaneDescription.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for calling out this ambiguity in the docs. I checked with the developers and they confirmed that the stride is measured in bytes. I have updated the documentation with this info. Thanks again for your help.
