### ISSUE TITLE
The documentation for the DatePicker is out of date

### ISSUE THREAD

**Issue by abmaddox** [MicrosoftDocs/winrt-api#2069]
When attempting to use the DatePicker properties "Header" and "SelectedDate" the error message "The property 'Header' was not found in type DatePicker" and "The property 'SelectedDate' was not found in type DatePicker" appear. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac373245-2d3e-e9aa-4848-98534b5a0213
* Version Independent ID: 5d9e90eb-988c-6b44-743b-4b423a60e8d0
* Content: [DatePicker Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.datepicker?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/DatePicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/DatePicker.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for contacting us. I'm not sure why you would get this error, but I have confirmed that both the Header and SelectedDate properties currently exist on the UWP DatePicker control that this documentation applies to.
