### ISSUE TITLE
Duplicate Content in UWP AutomationProperties documentation

### ISSUE THREAD

**Issue by agniuks** [MicrosoftDocs/winrt-api#2070]
There are two separate "Attached Properties" sections -- nearly identical. One of them does not have a respective link under "In this Article" which makes me think having both was not intentional. Made reading the page slightly confusing. 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b19312-d5aa-8024-9009-d56f43898596
* Version Independent ID: 4f9ea65e-5c52-3d3c-75c9-596c175dca13
* Content: [AutomationProperties Class (Windows.UI.Xaml.Automation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Automation.AutomationProperties?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Automation/AutomationProperties.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Automation/AutomationProperties.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for pointing this out. I've updated the topic to address this.
