### ISSUE TITLE
More details would be nice

### ISSUE THREAD

**Issue by etvorun** [MicrosoftDocs/winrt-api#2071]
Please provide explanation why this event fires. For example is it possible to get into an endless loop of trying to restart graphics capture session when handling such event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d678d91-34c6-b06c-4cd5-f8911877f7f8
* Version Independent ID: c0cf6cab-3791-c6be-c7fe-bd51b738482f
* Content: [GraphicsCaptureItem.Closed Event (Windows.Graphics.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureitem.closed?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Capture/GraphicsCaptureItem.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Capture/GraphicsCaptureItem.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@etvorun  It sounds like the case you are considering is if there is a failure in the API that causes the capture to close and that reinitiating capture from the Closed event might result in a loop? This event fires when the *target* of the capture closes. I.e. when the user closes the window that's being captured. So, it would not be possible to get stuck in a loop as the target of the capture would not exist to initialize a new capture. Does this answer your question?

**Comment by etvorun** [comment]
_This event fires when the _target_ of the capture closes. I.e. when the user closes the window that's being captured_

That would be a good info to include into documentation. Also that sounds like if HWND is alive and well then Closed event should not fire, right? Then following must be a bug:
1. Start VS 2019.
2. Use any app to capture VS window, e.g. https://github.com/robmikh/Win32CaptureSample
3. Go to VS and open an existing solution.
**Expected**: capture continues
**Actual**: capture stops (and Closed event fires)

**Comment by drewbatgit** [comment]
I have confirmed with the PM of this feature that the behavior you are experiencing is likely due to VS actually replacing the window with a new window when you open a new solution, but doing so in a seamless way that makes it seem like it's the same window. Apparently there are several older apps that are known to do this, e.g. Windows Media Player. I've added a remark to the page for the Closed event noting that this scenario is possible.

**Comment by etvorun** [comment]
> likely due to VS actually replacing the window with a new window

That is incorrect. I know if for sure because we had to add a workaround for Graphics Capture closing session on us. Also see attached gif
![VsHwnd](https://user-images.githubusercontent.com/48451158/131754681-591ad7dc-ebb8-4a8a-bd6c-b229f2f21321.gif)

**Comment by robmikh** [comment]
Interesting, I'm able to reproduce what you're seeing with the Closed event and Visual Studio. The close event is provided to us by the shell, so Visual Studio is doing _something_ that makes the shell think the window has closed. I'll debug this to figure out what's going on and file the appropriate bug.

**Comment by etvorun** [comment]
@robmikh, thanks for looking into it:). 
@drewbatgit, main point of filing this issue is to provide a better documentation on when this event is supposed to fire; that would help avoiding some guess work:).
