### ISSUE TITLE
Links in HTML tables are broken?

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#2073]
The HTML table with links to other doc pages is broken, showing things like `@"Windows.UI.Composition.Visual?text=Visual"` instead of a link with the text `Visual`:

![animatable properties table in StartAnimation remarks with malformed text](https://user-images.githubusercontent.com/432939/132386639-20d45246-8279-40ce-b20c-357afab08d56.png)

The table itself looks fine in HTML:

```md
<table>
   <tr><th>Object</th><th>Property Name</th><th>Property Type</th></tr>
   <tr><td>[Visual](visual.md)</td><td>[AnchorPoint](visual_anchorpoint.md)</td><td>Vector2</td></tr>
   <tr><td /><td>[CenterPoint](visual_centerpoint.md)</td><td>Vector3</td></tr>
   <tr><td /><td>[Offset](visual_offset.md)</td><td>Vector3</td></tr>
   <tr><td /><td>[Opacity](visual_opacity.md)</td><td>Scalar</td></tr>
   <tr><td /><td>[Orientation](visual_orientation.md)</td><td>Vector4</td></tr>
   <tr><td /><td>[RotationAngle](visual_rotationangle.md)</td><td>Scalar</td></tr>
   <tr><td /><td>[RotationAxis](visual_rotationaxis.md)</td><td>Vector3</td></tr>
   <tr><td /><td>[Size](visual_size.md)</td><td>Vector2</td></tr>
   <tr><td /><td>[TransformMatrix](visual_transformmatrix.md)</td><td>Matrix4x4</td></tr>
   <tr><td>[InsetClip](insetclip.md)</td><td>[BottomInset](insetclip_bottominset.md)</td><td>Scalar</td></tr>
   <tr><td /><td>[LeftInset](insetclip_leftinset.md)</td><td>Scalar</td></tr>
   <tr><td /><td>[RightInset](insetclip_rightinset.md)</td><td>Scalar</td></tr>
   <tr><td /><td>[TopInset](insetclip_topinset.md)</td><td>Scalar</td></tr>
   <tr><td>[CompositionColorBrush](compositioncolorbrush.md)</td><td>[Color](compositioncolorbrush_color.md)</td><td>Windows.UI.Color</td></tr>
   <tr><td>[CompositionPropertySet](compositionpropertyset.md)</td><td>Set of properties specified by the developer.</td><td /></tr>
</table>
```

Is it because the table is not fully markdown?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2519b437-ce5b-9a13-4d2c-1b6e68baad52
* Version Independent ID: d70b432c-92a4-7332-b43d-4532f58d0dc3
* Content: [CompositionObject.StartAnimation(String, CompositionAnimation) Method (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionobject.startanimation?view=winrt-20348#Windows_UI_Composition_CompositionObject_StartAnimation_System_String_Windows_UI_Composition_CompositionAnimation_)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/CompositionObject.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/CompositionObject.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this. Due to a change in the doc build, markdown is no longer supported in HTML tables. A PR has been submitted to fix all the HTML tables that had broken links or formatting.
