### ISSUE TITLE
[ListViewBase.SelectionMode] Remarks section has faulty formatting

### ISSUE THREAD

**Issue by marcelwgn** [MicrosoftDocs/winrt-api#2077]
The first column of the remarks section contains entries like `@"Windows.UI.Xaml.Controls.ListViewSelectionMode?text=None"` which is not ideal.

Note: I would like to work on this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ec8eef0-6d32-dbc6-a7e8-f426f5a0ea73
* Version Independent ID: e2b4994e-536c-3953-e3aa-9d237a8df951
* Content: [ListViewBase.SelectionMode Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.selectionmode?view=winrt-20348#Windows_UI_Xaml_Controls_ListViewBase_SelectionMode)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ListViewBase.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ListViewBase.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by ryan-weil** [comment]
Something is still screwed up, the Remarks links go to 404's

**Comment by jwmsft** [comment]
> Something is still screwed up, the Remarks links go to 404's

Thanks for reporting this. The links should work now.
