### ISSUE TITLE
StorageProviderSyncRootManager UnauthorizedAccessException

### ISSUE THREAD

**Issue by hellojayjay** [MicrosoftDocs/winrt-api#2080]
When I call `StorageProviderSyncRootManager.IsSupported()`, Then throw the error: 

![image](https://user-images.githubusercontent.com/42774792/133392832-5975aac8-e54b-4d3d-b503-3f04678bf031.png)

What's permission should I allow for my project? or, how can I fix it?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e26efdb0-9752-40c9-db15-d3e379c6bf50
* Version Independent ID: 0eb81f35-af64-663d-fae1-2bfba4607db8
* Content: [StorageProviderSyncRootManager.IsSupported Method (Windows.Storage.Provider) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.storageprovidersyncrootmanager.issupported?view=winrt-20348#Windows_Storage_Provider_StorageProviderSyncRootManager_IsSupported)
* Content Source: [winrt-api-build/xml/Windows.Storage.Provider/StorageProviderSyncRootManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Provider/StorageProviderSyncRootManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by lukeblevins** [comment]
Please upvote the relevant feedback hub issue for this bug: https://aka.ms/AAb0u1t

**Comment by hkhmsft** [comment]
Thanks, the feedback hub is the right place for this feedback.
