### ISSUE TITLE
Possibly incorrect docs for `Control.VerticalContentAlignment`

### ISSUE THREAD

**Issue by Youssef1313** [MicrosoftDocs/winrt-api#2085]
```csharp
        public class C : Control
        {
        }
```

Do `new CC().VerticalContentAlignment` returns `Center`. The docs say:

> The default is Top.

If this is correct, wouldn't the above code return `Top`?

---

> Also, the apparent "default value" of each individual control used in UI can be different. For example, a Button control starts with the value Center.

It seems that **all** controls have default value of `Center`, so button isn't an exception.

Anything I'm missing?

Same goes to HorizontalContentAlignment as well

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886f9354-7ad6-1ed2-93ed-01dbebe2f68f
* Version Independent ID: 57a4468a-f0c6-e339-7372-236f851b2408
* Content: [Control.VerticalContentAlignment Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.verticalcontentalignment?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Control.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Control.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. This documentation has been updated to reflect the current default values.
