### ISSUE TITLE
CreateRectangleClip arguments are vaguely specified

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#2086]
There are 2 factory functions for RectangleClips in Compositor that have the arguments `left`, `top`, `right`, and `bottom`.

These are all described as `The length of the [left] edge`, which is unhelpful and unclear since rectangles only really have two lengths, not 4.

It seems that the proper description for each would be:

> The inset of the [left] edge from the [left] of the visual.

In other words, it appears that RectangleClip is functionally identical to InsetClip (https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor.createinsetclip?view=winrt-20348).

I also can't seem to edit this page, as the `md` files don't appear in GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18bc4014-c8ad-d3da-4341-5c7fd3f153d9
* Version Independent ID: 330e5556-625f-8845-bced-ad8481399638
* Content: [Compositor.CreateRectangleClip Method (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor.createrectangleclip?view=winrt-insider&source=docs#Windows_UI_Composition_Compositor_CreateRectangleClip_System_Single_System_Single_System_Single_System_Single_)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/Compositor.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/Compositor.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for raising this issue. The descriptions have been updated in all the appropriate docs.
