### ISSUE TITLE
Documentation for WebView::InvokeScriptAsync() should clarify that if the result of the JavaScript is not a string, it returns an empty string rather than converting the result to a string

### ISSUE THREAD

**Issue by binarynate** [MicrosoftDocs/winrt-api#2087]
The documentation for [WebView:: InvokeScriptAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.invokescriptasync?view=winrt-19041#Windows_UI_Xaml_Controls_WebView_InvokeScriptAsync_System_String_Windows_Foundation_Collections_IIterable_System_String__) indicates the following:

> The invoked script can return only string values.

I had assumed after reading this that non-string values are converted to strings, but that's not the case. Instead InvokeScriptAsync() returns a blank string if the JavaScript's result is a non-string, such as a number. After digging around, I found that this limitation is listed on [this page of known issues](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview-known-issues), but it would be helpful if this were made clear in the method documentation itself or if a warning were logged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15b50e95-d8c9-71f5-2f3c-d2e3d5504000
* Version Independent ID: 90579498-c001-9031-4362-d5ce7dc1a911
* Content: [WebView.InvokeScriptAsync(String, IEnumerable&lt;String&gt;) Method (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.invokescriptasync?view=winrt-19041#Windows_UI_Xaml_Controls_WebView_InvokeScriptAsync_System_String_Windows_Foundation_Collections_IIterable_System_String__)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/WebView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/WebView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for this suggestion. The documentation has been updated.
