### ISSUE TITLE
C++/WinRT example on Windows.Devices.Radios.Radio.StateChanged

### ISSUE THREAD

**Issue by priyankajigalur** [MicrosoftDocs/winrt-api#2088]
Wanted to call Radio.StateChanged whenever radio state is changed via windows setting using C++/WinRT

**Comment by stevewhims** [comment]
Hi, @priyankajigalur, it's not that your app calls [Radio.StateChanged](https://docs.microsoft.com/uwp/api/windows.devices.radios.radio.statechanged). Rather, your app will register a delegate to handle that event. For more details, see [Handle events by using delegates in C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events).

If you have feedback about the content within a specific API or conceptual topic on docs.microsoft.com (if it's incomplete or incorrect), then you can visit that topic, scroll to the bottom, and click "Submit and view feedback for This page".

Thanks!
Steve
