### ISSUE TITLE
Schedule update example and confusing message on `Current`

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/winrt-api#2089]
The first example about checking for an update uses `Package.Current` but in the remarks it says 
"
If you try to use this method on the Package object returned by the Current property, this method will fail with an "Access denied" error. This is a known issue that may be fixed in a future release. The example on this page demonstrates how to retrieve update information about the current app's package.
"

So is `Current` ok or not?

Some information on what scenarios `Unknown` is returned would be useful.  It happens in one of our environments, but not others, so diagnosing steps are .... unknown.

The "From inside the app, the developer wants to check for updates and start the update process if updates are available." includes references to methods that are not shown, that look like they would actually do the "start the update process".  As these methods are not shown the example does not fit the description and really offers nothing more than the first example.  The naming of the methods, e.g. `LaunchTargetApp`  seems to indicate that the check and update need to be done from another exe.  Some clarification on that would be useful, e.g. can both the exes be part of the same appinstall?  Its confusing how to get a working self updating appinstaller installation.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb69cc83-27fc-5cf4-fe69-98ab75c4d061
* Version Independent ID: 62dbf413-5f27-f370-b024-f4aa014109a5
* Content: [Package.CheckUpdateAvailabilityAsync Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.checkupdateavailabilityasync?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel/Package.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel/Package.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Hi @yowl. Regarding your first question, the CheckUpdateAvailabilityAsync method cannot be used with the value directly returned by the Package.Current property. In the example, it is not using Package.Current to get the package reference directly. It uses Package.Current to get the package name. It then fetches the package with FindPackageForUser() using that name.

I will look further into your other two questions/concerns and get back to you shortly.

**Comment by alvinashcraft** [comment]
Hi @yowl. I have been in touch with one of the product teams about your questions. They're working on updating an MSIX sample and were wondering if this info helps clarify anything for you: https://github.com/microsoft/MSIX-Labs/blob/master/docs/index.md#exercise-15-embedded-appinstaller

**Comment by alvinashcraft** [comment]
Hi @yowl, I'm just checking back in to see if you've had a chance to review the MSIX-Labs repo example from my last comment? Does the example code there answer your questions? Do you think anything there should be incorporated into the docs for CheckUpdateAvailabilityAsync or does it make more sense to reference it as part of a more comprehensive example? Thanks!

**Comment by yowl** [comment]
@alvinashcraft Thanks, they repo is useful and answers the questions here.  Interesting that it checks for an update manually rather than `CheckUpdateAvailabilityAsync`

**Comment by alvinashcraft** [comment]
Thanks for letting me know, @yowl. I'm going to add a note to the docs for this method about the examples in that repo to help others who may have similar questions. Those changes should be live later today, so I will go ahead and close this. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
