### ISSUE TITLE
Remarks?

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/winrt-api#2090]
The Definition section says (emphasis added),

>The font weight expressed as a numeric value. **See Remarks.**

But there isn't any Remarks section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1616ba4-6cd2-5eb5-05f7-f72e8ba48af8
* Version Independent ID: a57b8e29-dc76-8a97-aa81-1b34d9dd5128
* Content: [FontWeight.Weight Field (Windows.UI.Text) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.fontweight.weight?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.UI.Text/FontWeight.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Text/FontWeight.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@PeterCon - thanks for pointing this out. I've revised the topic. It should be live in a few days.
