### ISSUE TITLE
BluetoothLEDevice.FromBluetoothAddressAsync() can return null?

### ISSUE THREAD

**Issue by dlech** [MicrosoftDocs/winrt-api#2092]
It seems like BluetoothLEDevice.FromBluetoothAddressAsync() can return null. This is not documented. What does it mean when it returns null? Is there a way to get an error code for more information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedb9559-6da0-2e91-eaef-12d9e9bfff4f
* Version Independent ID: cf9ff409-0028-5b6c-b77e-3987ad23671d
* Content: [BluetoothLEDevice.FromBluetoothAddressAsync Method (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by dlech** [comment]
Here is some more info on this from someone who helped design the API: https://github.com/microsoft/Windows-universal-samples/issues/1089#issuecomment-487586755

**Comment by stevewhims** [comment]
I've reached out to the feature team to enquire what info to add to the docs.

Thanks!
Steve

**Comment by stevewhims** [comment]
I've updated the topic to include more info in the **Returns** section describing when `null` is returned, and how to deal with that.

Thanks!
Steve

**Comment by dlech** [comment]
Super!
