### ISSUE TITLE
FromBluetoothAddressAsync() does not work without a scan first

### ISSUE THREAD

**Issue by nigelgp** [MicrosoftDocs/winrt-api#2093]
Hi,

It looks like FromBluetoothAddressAsync() is relying on some internally cached WinRT data to allow it to successfully open the BluetoothLEDevice. If I switch on my PC from cold and try and call FromBluetoothAddressAsync() with an address of a device that I know is advertising it will return a null BluetoothLEDevice. If I do a scan (using BluetoothLEAdvertisementWatcher) which sees the device and then try FromBluetoothAddressAsync() it will succeed (non-null BluetoothLEDevice). Then I can restart my app and call FromBluetoothAddressAsync() without doing a scan and it will still succeed.

This implies that WinRT is caching information from the scan process that is then used during the FromBluetoothAddressAsync() to allow it to work. This is okay but if it is doing this it needs to be documented.

Currently to avoid having to do a scan for a device when the address is already known I'm thinking I'll need to attempt to do a FromBluetoothAddressAsync() if the returned BluetoothLEDevice is null, do a scan for the device and if found retry the call to FromBluetoothAddressAsync(). It would have been nice if this was encapsulated within the call to FromBluetoothAddressAsync() rather than it only using cached scan data, or at least an option for it to actually look for the device (or a new method for doing this).

Either way improving the documentation to indicate what prerequisites are required by this method would help reduce wasted time finding out these 'features'.

Thanks

Nigel  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedb9559-6da0-2e91-eaef-12d9e9bfff4f
* Version Independent ID: cf9ff409-0028-5b6c-b77e-3987ad23671d
* Content: [BluetoothLEDevice.FromBluetoothAddressAsync Method (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync?view=winrt-20348)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothLEDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
I've reached out to the feature team to enquire what info to add to the docs.

Thanks!
Steve

**Comment by stevewhims** [comment]
I've updated the topic to include more info in the **Returns** section describing when `null` is returned, and how to deal with that.

Thanks!
Steve
