### ISSUE TITLE
Byte-unit of the upper limit of size of each setting

### ISSUE THREAD

**Issue by emoacht** [MicrosoftDocs/winrt-api#2097]
In this page, the upper limit of size of each setting is described as __8K byes__ and that of total settings is __64K__ bytes. There is ambiguity in this explanation on whether this __8K bytes__ actually means 8,000 bytes or 8,192 bytes. I bet it means the latter but it is desirable to clearly write the correct size.

> Each setting can be up to 8K bytes in size and each composite setting can be up to 64K bytes in size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 543175bb-6100-6c56-75fb-9b4ad4e036b1
* Version Independent ID: c5b7ab68-e8dd-7970-8782-ee35cc3ac2e0
* Content: [ApplicationData.LocalSettings Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.localsettings?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Storage/ApplicationData.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/ApplicationData.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
Hello. We apologize for the delay in resolving this issue. As we transition to a new feedback system, we are closing all outstanding issues. Any issues that can be addressed will be tracked using a different internal tool, and we regret that we won't be able to provide further updates on this particular matter. We value your input and assure you that all feedback is reviewed. We recommend visiting the Microsoft Q&A site, where your issue may have already been discussed.
