### ISSUE TITLE
Wrong link for all the Composition Effects

### ISSUE THREAD

**Issue by HO-COOH** [MicrosoftDocs/winrt-api#2100]
Wrong link for all the effects.
I found the working link in [Win2D doc](https://microsoft.github.io/Win2D/html/Introduction.htm). For example the `ArithmeticCompositeEffect` link should be [this](https://microsoft.github.io/Win2D/WinUI2/html/T_Microsoft_Graphics_Canvas_Effects_ArithmeticCompositeEffect.htm)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0377d6ea-d3ca-628e-ba62-1b25e90449bb
* Version Independent ID: 281e9377-7c98-7163-31e2-995423d3217e
* Content: [Compositor.CreateEffectFactory Method (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor.createeffectfactory?view=winrt-22000#Windows_UI_Composition_Compositor_CreateEffectFactory_Windows_Graphics_Effects_IGraphicsEffect_)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/Compositor.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/Compositor.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for pointing this out. The links have been updated.
