### ISSUE TITLE
Insufficent typo?  Should it be Insufficient (c-i-ent)?

### ISSUE THREAD

**Issue by sp-stuart-harrison** [MicrosoftDocs/winrt-api#2101]
Reading through your documentation I noticed what could be a typo..  Should it read `Insufficient(Quantity)` (with two i), or is the code itself wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88a7a071-12ac-8654-428b-79b1e516d611
* Version Independent ID: 18cd3de1-d3c7-2334-fe04-52f3e4fbc5a8
* Content: [StoreConsumableStatus Enum (Windows.Services.Store) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storeconsumablestatus?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Services.Store/StoreConsumableStatus.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Services.Store/StoreConsumableStatus.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jaigak** [comment]
Looks like it's spelt wrong in the actual API itself.

**Comment by alvinashcraft** [comment]
Yes, this is incorrect in the API itself. Unfortunately, we'll have to leave this as-is. Thanks for reporting the issue, and I apologize for the lengthy delay in response.
