### ISSUE TITLE
Important note in remarks isn't rendered/formatted properly

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#2102]
It's missing it's colored box making it hard to miss/realize it's important:

![image](https://user-images.githubusercontent.com/24302614/138065435-e4c04ed0-02d0-4302-ba22-93d416e04f95.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979114d8-fd14-1fca-f9a2-51820464f456
* Version Independent ID: 0e567737-32bb-18e5-65ae-1469e1db0aa5
* Content: [MediaElement Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.MediaElement?view=winrt-22000#remarks)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Fixed.
