### ISSUE TITLE
No information about mandatory using UI thread to invoke this method

### ISSUE THREAD

**Issue by arkuzo** [MicrosoftDocs/winrt-api#2103]
I've spent nearly a day trying to realize why I get `winrt::hresult_wrong_thread` on `PickSingleItemAsync` method, haven't senn a word in docs using UI thread is mandatory (page: https://docs.microsoft.com/ru-ru/uwp/api/windows.graphics.capture.graphicscapturepicker.picksingleitemasync?view=winrt-22000#Windows_Graphics_Capture_GraphicsCapturePicker_PickSingleItemAsync)

There is an issue with promise to update docs from 2018, but docs still incomplete. (https://docs.microsoft.com/ru-ru/uwp/api/windows.graphics.capture.graphicscapturepicker.picksingleitemasync?view=winrt-22000#Windows_Graphics_Capture_GraphicsCapturePicker_PickSingleItemAsync)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 68469560-45df-1c12-3b12-8a12eeb23739
* Version Independent ID: 9eedfc35-4c9a-326d-cd93-e4fe24bb3b86
* Content: [GraphicsCapturePicker.PickSingleItemAsync Method (Windows.Graphics.Capture) - Windows UWP applications](https://docs.microsoft.com/ru-ru/uwp/api/windows.graphics.capture.graphicscapturepicker.picksingleitemasync?view=winrt-22000#Windows_Graphics_Capture_GraphicsCapturePicker_PickSingleItemAsync)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Capture/GraphicsCapturePicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Capture/GraphicsCapturePicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Sorry for the long delay on resolving this issue. The page has been updated to state that it must be called on the UI thread and linking to [CoreDispatcher.RunAsync ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.runasync).
