### ISSUE TITLE
Uri doc has error?

### ISSUE THREAD

**Issue by jiaxin-lin** [MicrosoftDocs/winrt-api#211]
https://docs.microsoft.com/en-us/uwp/api/windows.foundation.uri

at the "Extension" section it says that dot is not included, however when I test it with this url: 
https://scontent.xx.fbcdn.net/v/t31.0-8/337554_209649659128630_1763982397_o.jpg?oh=2d3876f819bd76bffee7e7131e45b4ad&oe=5A6599

The extension it returns me is ".jpg", which does have the dot (.)

**Comment by ginami** [comment]
Thank you @JLLLinn for bringing this to our attention.

@Xansky can you respond to this?

**Comment by mhopkins-msft** [comment]
Thanks for the feedback, @JLLLinn. I've updated the source for the page. The fix should be published tomorrow.
