### ISSUE TITLE
ApplicationDataContainer.Containers returns IMapView from UWP and not IReadOnlyDictionary from .Net

### ISSUE THREAD

**Issue by rajendrasp** [MicrosoftDocs/winrt-api#2110]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bced63e-025d-08d8-e1b8-182a140fe6ac
* Version Independent ID: f4dcd922-b961-bc16-c1cb-c3170bdffee9
* Content: [ApplicationDataContainer.Containers Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdatacontainer.containers?view=winrt-22000#Windows_Storage_ApplicationDataContainer_Containers)
* Content Source: [winrt-api-build/xml/Windows.Storage/ApplicationDataContainer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/ApplicationDataContainer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by jaigak** [comment]
When using a .NET language, IMapView is implicitly projected as IReadOnlyDictionary. If you're using C++, please change the language for the docs from the dropdown to see the right documentation.

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

I tested this property in a UWP project targeting SDK Min version "Windows 10, version 1809 (build 17763)" and found that the `ApplicationDataContainer.Containers` property does return `IReadOnlyDictionary<string, ApplicationDataContainer>`. In my test, I used some sample code from the [ApplicationDataContainer Class](https://docs.microsoft.com/uwp/api/windows.storage.applicationdatacontainer#examples) page to test the property.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
