### ISSUE TITLE
Update example link

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/winrt-api#2117]
The example where it says:

> For more examples, see the XAML Responsive Techniques sample.

Is pointing to a page that is redirecting, and redirecting multiple times. Please update link to actual sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58e278f-7e7e-dc67-ba2f-4461723b216a
* Version Independent ID: e98a6aca-970b-b5ef-f2ad-450772e1cc50
* Content: [AdaptiveTrigger Class (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.AdaptiveTrigger?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/AdaptiveTrigger.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/AdaptiveTrigger.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for letting us know about this. The link has been updated.
