### ISSUE TITLE
missing link of Microsoft.UI.ColorHelper.ToDisplayName. Is it removed?

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/winrt-api#2120]
at the Definition section,
"Equivalent WinUI method: Microsoft.UI.ColorHelper.ToDisplayName."
Hyperlink target of "Microsoft.UI.ColorHelper.ToDisplayName" is missing.
And, Refer to WinUI Project's Error, "Microsoft.UI.ColorHelper" seems not include "ToDisplayName" method. Can I mix Windows.UI and Microsoft.UI? Around Color class, I oftenly get errors like CS0029 "Cannot implicitly convert typw 'Windows.UI.Color' to 'Microsoft.UI.Colors'".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8991e0ba-31be-ecb9-0246-a11bc33abb8d
* Version Independent ID: 278c2c5e-6874-f320-ae42-7c8b88dfbcba
* Content: [ColorHelper.ToDisplayName(Color) Method (Windows.UI) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.colorhelper.todisplayname?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI/ColorHelper.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI/ColorHelper.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jaigak** [comment]
You can still use Windows.UI.ColorHelper in a WinUI 3 app.

**Comment by jwmsft** [comment]
Microsoft.UI.ColorHelper does not include ToDisplayName. The incorrect links have been cleaned up.

**Comment by michael-hawker** [comment]
@jwmsft this is a UWP api that we need to understand how to map to the Windows App SDK / WinUI 3... I think that's the root issue. Don't think this is resolved?

**Comment by michael-hawker** [comment]
Filed https://github.com/microsoft/microsoft-ui-xaml/issues/8287 to ask explicitly about what the replacement is supposed to be here.

@JaiganeshKumaran I get red squiggles trying to use the Windows.UI version explicitly `Windows.UI.ColorHelper.ToDisplayName(color)`:

![image](https://user-images.githubusercontent.com/24302614/225461601-5c46ce38-5729-4de6-85f5-fcf573470d4e.png)

**Comment by jaigak** [comment]
@michael-hawker Okay, C#/WinRT doesn't project some Windows.UI* and all Windows.UI.Xaml* types.
