### ISSUE TITLE
Inadequate description. No detail or usage about this property.

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/winrt-api#2123]
[Enter feedback here]
To use this property requires the developer to use trial and error to determine its usage and value. A couple sentences and a data example would save many minutes of experimentation.
FolderPicker.SuggestedStartLocation ??
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577a55a9-0d4b-d002-1a77-ea1dbf211e43
* Version Independent ID: 12240525-cee1-5aa5-811a-c7c646b53067
* Content: [FolderPicker.SuggestedStartLocation Property (Windows.Storage.Pickers) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker.suggestedstartlocation?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers/FolderPicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers/FolderPicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Agreed. I've added a link to a sample, and some code that hopefully makes this clearer. Will be updated on the topic page soon. Thank you for the feedback!
