### ISSUE TITLE
ItemCollection.Size is actually private

### ISSUE THREAD

**Issue by jess-rod** [MicrosoftDocs/winrt-api#2128]
The documentation says `ItemCollection.Size` is public. It's private though. Please fix the implementation to make it public.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae615264-37fa-aa92-a328-d03e06ca9e98
* Version Independent ID: 4a476629-92a0-2410-230c-150aa94b581e
* Content: [ItemCollection.Size Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemcollection.size?view=winrt-19041#Windows_UI_Xaml_Controls_ItemCollection_Size)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ItemCollection.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ItemCollection.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jaigak** [comment]
In C# or Visual Basic, you need to use the Count property instead of the Size property.
