### ISSUE TITLE
PickerSingleItemAsync() not showing display preview in Windows 11.

### ISSUE THREAD

**Issue by cgolasnh** [MicrosoftDocs/winrt-api#2129]
I've created a simple Windows application which utilizes the CapturePicker API.  This works, and has worked fine on Windows 10.    When I upgraded my PC to Windows 11, and select "Share yourDisplay" instead of "Share your Window", the previews are all black.  
Is this a known issue?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68469560-45df-1c12-3b12-8a12eeb23739
* Version Independent ID: 9eedfc35-4c9a-326d-cd93-e4fe24bb3b86
* Content: [GraphicsCapturePicker.PickSingleItemAsync Method (Windows.Graphics.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturepicker.picksingleitemasync?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Capture/GraphicsCapturePicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Capture/GraphicsCapturePicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, I consulted with the feature team and this is a known issue. A fix for this has been made, but it didn't make it in time for the latest release, so the issue should be fixed in the next release.

**Comment by cgolasnh** [comment]
Thank you for your prompt response.


***@***.***

Christopher Golas
Senior Software Engineer
603-918-6246
***@***.******@***.***>
www.visionable.com<http://www.visionable.com>


***@***.***<https://visionable.com/mdts/>
***@***.***<https://www.linkedin.com/company/visionable-global> I  ***@***.*** <https://twitter.com/VisionableG>

Head Office:
The Old Winery
Lamberhurst Vineyard
Lamberhurst
Kent TN3 8ER

London Office:
1 Long Lane
London SE1 4PG

**Comment by cgolasnh** [comment]
Just to be clear, are you talking about the next release of Windows 11?  Or an API upgrade?
Thanks


***@***.***

Christopher Golas
Senior Software Engineer
603-918-6246
***@***.******@***.***>
www.visionable.com<http://www.visionable.com>


***@***.***<https://visionable.com/mdts/>
***@***.***<https://www.linkedin.com/company/visionable-global> I  ***@***.*** <https://twitter.com/VisionableG>

Head Office:
The Old Winery
Lamberhurst Vineyard
Lamberhurst
Kent TN3 8ER

London Office:
1 Long Lane
London SE1 4PG
