### ISSUE TITLE
Wrong statement that background triggers do not work when device is battery mode

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#213]
In TimeTrigger class documention you claim that: "TimeTriggers, and other background triggers, do not work when the device is in battery saver mode."

This is not true for all triggers, as at least ToastNotificationHistoryChangedTrigger and ToastNotificationActionTrigger do work even when device is in battery saver mode.

**Comment by TylerMSFT** [comment]
Hi Viktor,
I'm looking into it.

**Comment by TylerMSFT** [comment]
Removed the generalized statement.
