### ISSUE TITLE
Windows.ApplicationModel.Resources.* APIs point to broken Windows App SDK equiv. links

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/winrt-api#2130]
Doesn't appear the links were updated post Preview 1. For example, the [ResourceLoader page](https://github.com/MicrosoftDocs/winrt-api/blob/docs//windows.applicationmodel.resources/resourceloader.md) points to https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows/winui/api/microsoft.applicationmodel.resources.resourceloader.

The correct link is https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources.resourceloader.

**Comment by riverar** [comment]
Heads up @andrewleader

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @riverar - the UWP -> winui links have been updated for the Windows.ApplicationModel.Resources.ResourceLoader namespace docs (where applicable).
