### ISSUE TITLE
Minimal documentation is minimally helpful

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/winrt-api#2137]
In the topic [NetworkOperatorTetheringManager.CreateFromNetworkAccountId(String) method](https://docs.microsoft.com/uwp/api/windows.networking.networkoperators.networkoperatortetheringmanager.createfromnetworkaccountid) ...

This is really unhelpful:

> Creates an instance of NetworkOperatorTetheringManager for a specific network account using the provided network account ID for the mobile broadband device.

"Hmmm, I wonder what they mean by "network account". There are so many different kinds of credentials/accounts...  User Principal Name? Down-Level Logon Name? Domain Credentials? Generic Credentials? SSID and WPA key?  Let's see what the parameter description says..."

> Parameters
>
> networkAccountId    String     The network account ID.

(heavy sigh)

At this point I'm faced with searching github source for hints/examples, or maybe someone will have explained what this is on StackOverflow. Unless I have a really compelling reason to believe I need to use this method, I'll probably just move on. If I did that for every under-documented method/property/etc, I'd never get anything done.

Just a single short example, e.g. `DOMAIN\username` would have made all the difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7c49f3f-cae7-d748-f83e-d55172cac076
* Version Independent ID: b1559ab1-29fb-1068-4962-c22b53e88af7
* Content: [NetworkOperatorTetheringAccessPointConfiguration.Ssid Property (Windows.Networking.NetworkOperators) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.networkoperators.networkoperatortetheringaccesspointconfiguration.ssid?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Networking.NetworkOperators/NetworkOperatorTetheringAccessPointConfiguration.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.NetworkOperators/NetworkOperatorTetheringAccessPointConfiguration.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, and thanks for filing this issue. As with the other, I've pinged the feature team to see whether there's more info they'd like to be added to the docs.

-Steve

**Comment by stevewhims** [comment]
Hi, @mr-intj.

Since the [NetworkOperatorTetheringManager.CreateFromNetworkAccountId(String) method](https://docs.microsoft.com/uwp/api/windows.networking.networkoperators.networkoperatortetheringmanager.createfromnetworkaccountid) topic contains the content "Creates an instance of NetworkOperatorTetheringManager for [...]", I added more info to that topic describing what a network account is, and how to obtain a list of them and their IDs.

Thanks!
-Steve
