### ISSUE TITLE
Incorrect links in AutomationProperties doc

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#214]
It seems that there are many links in the [AutomationProperties doc](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties) which should navigate to another page but instead don't navigate anywhere.

Let's take `Windows.UI.Xaml.Automation.AutomationProperties.AccessibilityViewProperty` as an example:
  - [MSDN doc](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties#Windows_UI_Xaml_Automation_AutomationProperties_AccessibilityViewProperty)
  - [GitHub source](https://github.com/MicrosoftDocs/winrt-api/blob/cdb74ed4bb196238f7e4dc5ef8b1a7ad6929facc/windows.ui.xaml.automation/automationproperties_accessibilityviewproperty.md#L0)

The beginning of the documentation for that property starts with "Identifies the AutomationProperties.AccessibilityView...". The last word, "AutomationProperties.AccessibilityView", is a link which brings me to the exact same part of the documentation I was looking at. However, I believe that link should have brought me [here](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.automation.automationproperties.accessibilityview.aspx) instead.

It seems this kind of mistake is made all over the [AutomationProperties documentation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties)

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you @rigdern for bringing this to our attention.

@Xansky can you respond to this?

**Comment by mhopkins-msft** [comment]
Hi Adam,

I apologize for the delayed response. I did some research and learned that we are aware of this problem and it is being tracked by an internal work item. Therefore, I'm closing this thread on GitHub. Thank you for taking the time to let us know about this.

 - Mark
