### ISSUE TITLE
variable rename / undefined in example : picturesFolder vs picturesLibrary

### ISSUE THREAD

**Issue by marksrasmussen** [MicrosoftDocs/winrt-api#2143]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c387216b-8854-2737-0447-ff29c34230d9
* Version Independent ID: 1f8a3039-e496-d3a1-3902-bc37149ccabe
* Content: [StorageFolderQueryResult Class (Windows.Storage.Search) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.storagefolderqueryresult?view=winrt-22000#feedback)
* Content Source: [winrt-api-build/xml/Windows.Storage.Search/StorageFolderQueryResult.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Search/StorageFolderQueryResult.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by stevewhims** [comment]
Thanks, @marksrasmussen, and apologies for the delay in responding. I've published a fix to that code example now.

Many thanks!
-Steve
