### ISSUE TITLE
Add more details to the documentation to make it clear

### ISSUE THREAD

**Issue by xris1658** [MicrosoftDocs/winrt-api#2150]
Could you please add more useful details to the documentation?  
For instance,Windows.Storage.Storage.File.FileType returns the file name extension, but according to [the documentation](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.filetype?view=winrt-22000#Windows_Storage_StorageFile_FileType), I can't figure out whether the return value starts from the first dot in the file name (`.tar.gz`) or starts from the last dot (`.gz`). Also, I found that the return value contains the dot character (`.jpg` instead of `jpg`), but the relevant information is not written clearly, so I have to write some code to check that.  
I think [this description](https://doc.qt.io/qt-5.15/qfileinfo.html#suffix) did a good job by making the key information simple yet clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deac9654-b121-adde-8a9b-0d981d7dd960
* Version Independent ID: 722b13b0-b9ae-7af7-81c9-6f17b8670427
* Content: [StorageFile.FileType Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.filetype?view=winrt-22000#Windows_Storage_StorageFile_FileType)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by alvinashcraft** [comment]
Thank you for raising this issue. The example you provided on the Qt Core docs does make it clear what text is part of the suffix property.

In this case, the FileType includes everything from the last '.', including the '.'. So, for your ".tar.gz" example, the FileType property would return ".gz". We will expand on the Remarks for the FileType docs to make it clearer.

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I create an internal issue for this, and the changes are now live. I think the remarks are now clearer about what to expect from the FileType property.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
