### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by agentbarti** [MicrosoftDocs/winrt-api#2151]
[Wprowadź tutaj swoją opinię]

Hello i'm trying to use this method (Clipboard.ClearHistory()) and it's not working. I also have windows 22000.376 build
---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 09a0ddeb-467c-4516-133c-bd0c710408f7
* Version Independent ID: 234d1ef0-7a9a-be22-6572-51faf742031e
* Content: [Clipboard.ClearHistory Method (Windows.ApplicationModel.DataTransfer) - Windows UWP applications](https://docs.microsoft.com/pl-pl/uwp/api/windows.applicationmodel.datatransfer.clipboard.clearhistory?view=winrt-22000#Windows_ApplicationModel_DataTransfer_Clipboard_ClearHistory)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a question, or feedback, about the product. I don't have any additional content for your scenario, over and above what's in the documentation. I have tested this method with Windows v22000 as the target version in a UWP app, and this appears to be working as documented. So, if you are still having issues, it might be worth your pursuing this as a question/feedback about the product. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback.
