### ISSUE TITLE
The Links to the Equivalent WinUI Class All Lead to 404s

### ISSUE THREAD

**Issue by scout208** [MicrosoftDocs/winrt-api#2152]
I'm looking for the equivalent WinUI 3 class to use for `Windows.System.DispatcherQueue` in UWP. Unfortunately, all the links pointing to the WinUI class `Microsoft.System.DisptcherQueue` on this page lead to 404s. It seems like the equivalent class has been changed at some point and this page not updated. Could we update the links to point to the correct page now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b94349-5f9a-6e3b-1a9d-0caac14c7ad4
* Version Independent ID: ae431481-75ec-99e6-25e6-dfa6006e85c5
* Content: [DispatcherQueue Class (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueue.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueue.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for reporting this. We recently completed a scrub of the Windows.xx API ref to remove dead links to the WinUI/Win App SDK APIs. This was one of the revised topics. Please open a new issue if you find any remaining dead links in other topics.
