### ISSUE TITLE
Link to open XAML Control Gallery sample for MediaElement doesn't navigate to sample (since it was removed)

### ISSUE THREAD

**Issue by adrastogi** [MicrosoftDocs/winrt-api#2154]
There's a link to launch the XAML Control Gallery app to view the MediaElement sample [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaelement?view=winrt-22000#examples). However, at least in the version of the app installed on my device (1.2.22.0), the [link](xamlcontrolsgallery:/item/MediaElement) takes me to the "What's New" page in the app. I saw that the sample was removed some time ago via the change [here](https://github.com/microsoft/Xaml-Controls-Gallery/pull/205), so the doc likely needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 979114d8-fd14-1fca-f9a2-51820464f456
* Version Independent ID: 0e567737-32bb-18e5-65ae-1469e1db0aa5
* Content: [MediaElement Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.MediaElement?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for opening this issue. The link to the Control Gallery app has been removed from MediaElement.
