### ISSUE TITLE
The API reference labels should be renamed to prevent discombobulation

### ISSUE THREAD

**Issue by kmgallahan** [MicrosoftDocs/winrt-api#2155]
Are per the title, the API reference links currently look like this:

![Screenshot 2022-01-10 133124](https://user-images.githubusercontent.com/5379488/148820093-4ab8a8bc-70d6-4405-86c5-5df66ef95888.jpg)

"Windows SDK API" should likely read "Windows UWP & Classic API", with the first link under there reading "WinRT UWP API" instead of "WinRT API".

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback. This terminology is current standard. Windows SDK WinRT APIs are not required to support UWP, so that is not an option.
