### ISSUE TITLE
 i m not clear on how to build my own controller

### ISSUE THREAD

**Issue by Notblup** [MicrosoftDocs/winrt-api#2157]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c382eaa-aecb-0f26-ab0e-e752c9a36713
* Version Independent ID: 7b0c1235-3109-5b93-33c7-203426d2fad6
* Content: [Windows.Gaming.Input Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input?view=winrt-22000)
* Content Source: [winrt-api-build/xml/ns-Windows.Gaming.Input.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Gaming.Input.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
No doc issue reported.
