### ISSUE TITLE
Default Media Stream Property

### ISSUE THREAD

**Issue by fortminors** [MicrosoftDocs/winrt-api#2158]
Hello! It is not very clear in what order the properties are returned, but what I am more interested in is whether the first property is the default one for each camera?

My goal is to find the native aspect ratio that the camera operates in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db57898-8715-f7ae-103e-f2179cb2d3ac
* Version Independent ID: b1a463ef-936e-74d2-75dc-ee15ca116377
* Content: [VideoDeviceController.GetAvailableMediaStreamProperties(MediaStreamType) Method (Windows.Media.Devices) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.videodevicecontroller.getavailablemediastreamproperties?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Media.Devices/VideoDeviceController.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Devices/VideoDeviceController.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@fortminors Hello, I've heard back from the camera team and, unfortunately, there isn't a mechanism for determining the native aspect ratio for the camera at this time.
