### ISSUE TITLE
Windows Phone

### ISSUE THREAD

**Issue by DWFan124** [MicrosoftDocs/winrt-api#2159]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed90a4b0-8082-6445-0b89-192741783975
* Version Independent ID: 531f65ce-bef8-1272-4f3b-f6fb67893e2d
* Content: [VibrationDevice Class (Windows.Phone.Devices.Notification) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.phone.devices.notification.vibrationdevice?view=winrt-15063)
* Content Source: [winrt-api-build/xml/Windows.Phone.Devices.Notification/VibrationDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Phone.Devices.Notification/VibrationDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Since there is no description, I'm closing this issue. If you have found a problem with the documentation, please open a new issue and provide a description.
