### ISSUE TITLE
My app launched by a file returns 'Launch' but not 'file'

### ISSUE THREAD

**Issue by siazon** [MicrosoftDocs/winrt-api#2161]
[Enter feedback here]
In App.xaml.cs override OnLaunched(args)  args.UWPLaunchActivatedEventArgs.Kind aways was 'Launch'.
When I open a file with my App also returns the 'Launch' but not the document that says the 'File'.
My App is a WinUI .net 6 application. It runs in Win11 insider preview.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce9b7ae-7634-baf1-8b7c-4b59a8452795
* Version Independent ID: 3c4d5a74-71fe-d78b-9c77-e830e449acca
* Content: [ActivationKind Enum (Windows.ApplicationModel.Activation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.activationkind?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Activation/ActivationKind.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Activation/ActivationKind.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by siazon** [comment]
```
Microsoft.Windows.AppLifecycle.AppInstance appInstance = Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent();
var kind = appInstance.GetActivatedEventArgs().Kind;
```
This kind is correct. 
Problem solved。

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Hi @siazon. Is your WinUI project Packaged or Unpackaged? If you look at [this page](https://docs.microsoft.com/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation) about activation with Windows App SDK, unpackaged apps should be referencing the four activation kinds from [ExtendedActivationKind](https://docs.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.extendedactivationkind). Only packaged apps can use the 44 ActivationKind values defined for UWP at this time.

The scope of this feedback channel covers specific documentation fixes. If the page I referenced above doesn't answer your question, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
