### ISSUE TITLE
Using "webView2" variable in Spartan WebView doc is confusing

### ISSUE THREAD

**Issue by krschau** [MicrosoftDocs/winrt-api#2167]
Now that we have MUX WebView2 on Anaheim Edge, we might want to change the sample code here from "webView1" and "webView2" to webViewA and WebViewB or something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1e6f48-d57c-65c1-9f05-1d76db94294f
* Version Independent ID: d69a866b-7f25-5543-6fa2-fbf9b830548b
* Content: [WebView Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.WebView?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/WebView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/WebView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the suggestion. This update was completed some time ago, but this issue didn't get closed. Closing it now.
