### ISSUE TITLE
Play back media server 192.168.100.12

### ISSUE THREAD

**Issue by MalikArish005** [MicrosoftDocs/winrt-api#2169]
### ****
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e4cefdb-11fe-03fc-1b4d-c7eb2524752e
* Version Independent ID: 19e4e4c4-e05f-db3a-0015-8ea4876b9b32
* Content: [CameraCaptureUI.CaptureFileAsync(CameraCaptureUIMode) Method (Windows.Media.Capture) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.cameracaptureui.capturefileasync?view=winrt-22000#windows-media-capture-cameracaptureui-capturefileasync(windows-media-capture-cameracaptureuimode))
* Content Source: [winrt-api-build/xml/Windows.Media.Capture/CameraCaptureUI.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Capture/CameraCaptureUI.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
There is no actionable feedback in this github issue. If this is in regards to an error in the documentation, please open a new issue and provide a description of the problem.
