### ISSUE TITLE
Does AUMID change?

### ISSUE THREAD

**Issue by sanjayssk** [MicrosoftDocs/winrt-api#2170]
[Enter feedback here]
I'm a store app developer and want to know if I can depend on AUMID not to change unless I update the version number of the app. Something about when does it change and what are its dependencies would be useful.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2890431f-0b9c-a844-8e68-ff0dc07b0ca7
* Version Independent ID: 14915a32-613a-e632-01d1-e27f6ea21547
* Content: [AppListEntry.AppUserModelId Property (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.applistentry.appusermodelid?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Core/AppListEntry.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Core/AppListEntry.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by DrusTheAxe** [comment]
>I'm a store app developer and want to know if I can depend on AUMID not to change unless I update the version number of the app

No.

App identity in MSIX is an Application User Model ID (aka AUMID), which is based on Package Family Name + Package Relative Application ID (aka PRAID).

* PackageFamilyName = Name + Publisher (per your package's `<Identity>` element in `appxmanifest.xml`)
* PRAID = the `Id` property of your application in your package's `appxmanifest.xml` (e.g. `<Application Id="Foo"...>`)

Neither of these contain any version information thus AUMID is version-independent.

ByDesign :-)

P.S. Application identity is equally independent of package architecture (and resource id). Unless you change your package Name or Publisher, or you change your PRAID in your manifest, your app in your package v1 x86 and v2 x64 have the same AUMID.

**Comment by alvinashcraft** [comment]
Thanks for the clarification, @DrusTheAxe. I'm adding some of this info to the docs topic to help other folks in the future.

Thanks @sanjayssk for submitting your feedback and we apologize for the delayed response. The timeline for reviewing the publishing the changes may vary (but it should be within a couple of days), so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
