### ISSUE TITLE
Page has incorrect documentation for PlayReady key system string.

### ISSUE THREAD

**Issue by swenkeratmicrosoft** [MicrosoftDocs/winrt-api#2172]
I am the PlayReady architect at Microsoft.  The following page is wrong.  Hard stop.

https://docs.microsoft.com/en-us/uwp/api/windows.media.protection.protectioncapabilities.istypesupported?view=winrt-22000

It NEEDS to be updated ASAP to use the current key system string.

Specifically, replace:
com.microsoft.playready.hardware -> com.microsoft.playready.recommendation.3000
com.microsoft.playready.software -> com.microsoft.playready.recommendation.2000
com.microsoft.playready -> com.microsoft.playready.recommendation

My github username matches my alias in the internal GAL, so you can contact me directly if you need more information.

Please fix this IMMEDIATELY.  Any customer using this documentation is going to have serious problems otherwise.

-Sam Wenker, Microsoft PlayReady Architect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36c83a0-901e-e58e-3cc4-70a0327a7cce
* Version Independent ID: 773ce5d3-d844-41ad-68c4-a2de3475b806
* Content: [ProtectionCapabilities.IsTypeSupported(String, String) Method (Windows.Media.Protection) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.protection.protectioncapabilities.istypesupported?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Media.Protection/ProtectionCapabilities.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Protection/ProtectionCapabilities.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@swenkeratmicrosoft This change has been made and published live. Please review the content on the live site and confirm that these URLs are now correct. I'll leave the github issue open until you verify that the content is correct.

**Comment by swenkeratmicrosoft** [comment]
Wow, fast turnaround!  Thanks so much!  I've verified it's correct on the live sight and am closing this issue.  :)
