### ISSUE TITLE
how to get edim eid in a uwp app?

### ISSUE THREAD

**Issue by liangchaoqin** [MicrosoftDocs/winrt-api#2175]
I am developing a UWP app，while i use this [api doc](https://docs.microsoft.com/en-us/uwp/api/windows.networking.networkoperators.esim.eid?view=winrt-22000) to get eid，it always get null object.
 1. How to get ESIM eid in  a UWP App? 
 2. How to register a mobile operator apps and UWP app?
 3. How to be a mobile network operators?

**Comment by stevewhims** [comment]
Hi, @liangchaoqin.

Yes, the API won't work unless you declare the appropriate custom capability, and you've requested special approval to use it.

At the top of the [ESim.Eid property](https://docs.microsoft.com/uwp/api/windows.networking.networkoperators.esim.eid) topic is a link to info about [Custom capabilities](https://docs.microsoft.com/windows/uwp/packaging/app-capability-declarations#custom-capabilities).

As that info say, the "Restricted capabilities" section above "describes the same capability approval process that you can use to request approval to use a custom capability". It also says that if you have a Windows Technical Account Manager (TAM), then you can work with your TAM to request access.

Hope that helps!
-Steve
