### ISSUE TITLE
SystemManufacturer return empty string problem

### ISSUE THREAD

**Issue by SunnyRuan** [MicrosoftDocs/winrt-api#2176]
[Enter feedback here]
Hi,
My UWP app cannot get SystemManufacturer value via this API. But check windows system info Manufacturer has value. And according to this document, it said "SystemManufacturer is retrieved from the Windows Registry. If the Registry can't be read for any reason, then SystemManufacturer is returned as an empty string." .
So, the question is where is the Windows Registry key path SystemManufacturer retrieved  I can check? Or it's another problem cause UWP can't get SystemManufacturer value via this API? 
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85cb0baf-5593-6211-8be6-a67dce28c137
* Version Independent ID: bc42e39e-c0b6-ea40-84bd-d985d2615b3e
* Content: [EasClientDeviceInformation.SystemManufacturer Property (Windows.Security.ExchangeActiveSyncProvisioning) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.exchangeactivesyncprovisioning.easclientdeviceinformation.systemmanufacturer?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Security.ExchangeActiveSyncProvisioning/EasClientDeviceInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.ExchangeActiveSyncProvisioning/EasClientDeviceInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by alvinashcraft** [comment]
Hi. Could I get some more info about the version of Windows you're using and which Target and Minimum versions you're setting in your UWP app?
I just tried using this API in a new UWP blank app and was able to display the SystemManufacturer value in a TextBlock:

```
var deviceInfo = new Windows.Security.ExchangeActiveSyncProvisioning.EasClientDeviceInformation();
string mfg = deviceInfo.SystemManufacturer;
MfgTextBlock.Text = mfg;
```
Thanks!

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The SystemManufacturer property appears to be working in a UWP project when I tested it. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
#please-close

**Comment by SunnyRuan** [comment]
Hi!
Problem is solved and root cause is BIOS problem. Thanks you!
