### ISSUE TITLE
Examples section of FrameworkElement.Height page has a wrong Markdown snippet

### ISSUE THREAD

**Issue by masaru-iritani** [MicrosoftDocs/winrt-api#2177]
[Examples section of FrameworkElement.Height page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.height?view=winrt-22000#examples) shows a strange snippet. However, [the original Markdown file](https://github.com/MicrosoftDocs/winrt-api/blob/docs//windows.ui.xaml/frameworkelement_height.md#-examples) is correctly rendered on GitHub. The snippet seems generated by a Markdown parser error.

```
(@"Windows.UI.Xaml.[Control](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control?view=winrt-22000)s.Control.Background?text=Background" is actually a Control property, not defined by [FrameworkElement](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement?view=winrt-22000).)
```

![A screenshot of FrameworkElement.Height page showing a strange snippet](https://user-images.githubusercontent.com/25241373/155061824-39d3a93b-4caf-4a0b-a6db-8ad86ece781a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecfef675-7914-63ee-4ca9-ce518c8b644c
* Version Independent ID: fc5ca90c-ddf3-9522-6025-2f17a4965015
* Content: [FrameworkElement.Height Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.height?view=winrt-22000#windows-ui-xaml-frameworkelement-height)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/FrameworkElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/FrameworkElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This rendering issue appears to be resolved.
