### ISSUE TITLE
Switching to C++ mode won't change the 2nd part to C++. It keeps on remaining on C# code

### ISSUE THREAD

**Issue by DMNight6** [MicrosoftDocs/winrt-api#2184]
There's something wrong with the documentation. Switching to C++ mode still lets the other code remains on C#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f25f17-cfcb-c9e5-4ba1-9fcf681290be
* Version Independent ID: 1ac80111-7675-3a55-10d2-f8b6eb038db8
* Content: [Application.RequestedTheme Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.requestedtheme?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/Application.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/Application.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
There are currently no C++ examples for this topic. The universal selector doesn't automatically update per page.
