### ISSUE TITLE
ContentPropertyAttribute C++/WinRT

### ISSUE THREAD

**Issue by odyright** [MicrosoftDocs/winrt-api#2185]
[ContentPropertyAttribute]

What is equivalent `C++/WinRT` of contentproperty attribute?
```c#
[ContentProperty(Name = "Children")]
public class Panel : FrameworkElement 
{ ...}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926fa0d3-053b-3a02-a40d-6766146d2c19
* Version Independent ID: dc33a838-41db-7810-93a0-bf150dad9b97
* Content: [ContentPropertyAttribute Class (Windows.UI.Xaml.Markup) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.contentpropertyattribute?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Markup/ContentPropertyAttribute.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Markup/ContentPropertyAttribute.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @odyright. You add the attribute to the MIDL 3.0 declaration in your .idl file. Here's an example:

```idl
// BgLabelControl.idl
namespace BgLabelControlApp
{
    [contentproperty("Content")]
    runtimeclass BgLabelControl : Windows.UI.Xaml.Controls.Control
    {
        BgLabelControl();
        static Windows.UI.Xaml.DependencyProperty LabelProperty{ get; };
        String Label;
        static Windows.UI.Xaml.DependencyProperty ContentProperty{ get; };
        IInspectable Content;
    }
}
```

I've update the topic with a link to the content for that attribute.

Thanks!
-Steve

**Comment by odyright** [comment]
Hi @stevewhims! Thank you!

**Comment by odyright** [comment]
Hi, @stevewhims. According to the doc [midl-3](https://docs.microsoft.com/en-us/uwp/midl-3/intro), it's said:

> MIDL 3.0 supports three additional type categories.
    - **single-dimensional array** types,
    - **nullable value** types, and
    - the **Object** type.

and

> Finally, MIDL 3.0 supports the **Object type**, which maps to the Windows Runtime [IInspectable](https://docs.microsoft.com/en-us/windows/win32/api/inspectable/nn-inspectable-iinspectable) interface. The interface and runtimeclass reference types conceptually derive from the **Object type**; delegate does not.

So : `IInspectable Content;` shouldn't have to be `Object Content;` ?
