### ISSUE TITLE
[C++/WinRT] Gets the display name of the package

### ISSUE THREAD

**Issue by odyright** [MicrosoftDocs/winrt-api#2192]
[more explanations needed]
i want to get the `DisplayName` of the package in `C++/WinRT`.

As describe in this C# example:
```xml
<TextBlock x:Name="AppTitle"
                       Text="{x:Bind GetAppTitleFromSystem()}"
                       VerticalAlignment="Center"
                       Style="{StaticResource CaptionTextBlockStyle}" />
```

```c#
namespace AppUIBasics
{
    public sealed partial class NavigationRootPage : Page
    {
        public string GetAppTitleFromSystem()
        {
            return Windows.ApplicationModel.Package.Current.DisplayName;
        }
    }
}
```
i tried to :
```c++
// .xaml.h file
struct MainWindow : MainWindowT<MainWindow>
{
        MainWindow();
        winrt::hstring GetAppTitleFromSystem();
}
...
```
```c++
// .xaml.cpp file
...
MainWindow::MainWindow()
{
        InitializeComponent();        
}
hstring MainWindow::GetAppTitleFromSystem()
{
        Package package = Package::Current();
        return package.DisplayName();
}
...
```
```
// .idl
namespace Example
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        //String GetAppTitleFromSystem{ get; };
        Windows.ApplicationModel GetAppTitleFromSystem{ get; };
    }
}
```

i got error like:
1. `error MIDL2011: [msg]unresolved type declaration [context]: Windows.ApplicationModel [ Property 'GetAppTitleFromSystem' ( RuntimeClass 'TD2_WinUI3.MainWindow' ) ]`
2. `Error XLS0525 Method 'GetAppTitleFromSystem' not found in type 'MainWindow. Example	C:\Users\{..}\MainWindow.xaml 72`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6450edb-63ec-91c5-bca9-4df72bf2e6b7
* Version Independent ID: 88e2b44c-fb64-8724-0031-6c63a8c39a12
* Content: [Package.DisplayName Property (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.displayname?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel/Package.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel/Package.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @mikben
* Microsoft Alias: **mikben**

**Comment by alvinashcraft** [comment]
Hi. Could you please provide some additional information? Are you working with a C++ UWP project or a C++ WinUI 3 project? From your code snippet, I am assuming it is WinUI (working with MainWindow not MainPage). The note on the doc page indicates that the property is only supported in UWP apps.

I would like to try and reproduce the errors you're seeing here with the same project type. Thanks!

**Comment by odyright** [comment]
Hi, i am working with WinUI 3 project.

**Comment by alvinashcraft** [comment]
Thanks for the information.

When I update the .idl file to this, it works:
```
namespace WinUiCppApp1
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        String GetAppTitleFromSystem{ get; };
        //Windows.ApplicationModel GetAppTitleFromSystem{ get; };
    }
}
```
I tested it by modifying the default generated app to populate the Button's Content with the result from GetAppTitleFromSystem() in .xaml.cpp:
```
    void MainWindow::myButton_Click(IInspectable const&, RoutedEventArgs const&)
    {
        myButton().Content(box_value(GetAppTitleFromSystem()));
    }
    hstring MainWindow::GetAppTitleFromSystem()
    {
        Package package = Package::Current();
        return package.DisplayName();
    }
```

Let me know if this works for you. I will talk to the team about the best place to add some C# and C++ sample code for using Package properties in a WinUI 3 project.

**Comment by odyright** [comment]
Right! so, `Windows.ApplicationModel` is a namespace, i put it inside `xaml.cpp` , the `error MIDL2011` is gone. 
1.But i'm still facing the: `Error XLS0525:	Method 'GetAppTitleFromSystem' not found in type 'MainWindow`.
When i remove the `()` from **GetAppTitleFromSystem** inside the xaml file, it seems to work.
2. handle an event like you did, works too.
