### ISSUE TITLE
How one find the built in states and styles ?

### ISSUE THREAD

**Issue by KWodarczyk** [MicrosoftDocs/winrt-api#2197]
"This example creates a VisualStateGroup in the ControlTemplate of a Button called "CommonStates" and adds VisualState objects for the states, "Normal", "Pressed", and "PointerOver". The Button also defines a state called "Disabled" that is in the "CommonStates" named VisualStateGroup, but the example omits it for brevity."

It's nice that you say Button already has built in states but why you don't mention how to find them ? and what about other ten's of other controls ? There should be a file on GitHub or somewhere we we can easy access the built in styles so we know what attach to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbbb0238-31a8-16e4-12b8-ff3739473d7b
* Version Independent ID: a14a6c7f-bc58-5832-9e38-72737f662aa6
* Content: [VisualState Class (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.VisualState?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/VisualState.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/VisualState.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Where to find the default template for a control depends on which version of the control you are using. The reference page for each control class has a section called "Control style and template" that indicates where to find the default template, either on GitHub or in the SDK. For example, [Button](https://learn.microsoft.com/uwp/api/windows.ui.xaml.controls.button?view=winrt-22000#control-style-and-template).
