### ISSUE TITLE
Migration to Azure App Service

### ISSUE THREAD

**Issue by pkar70** [MicrosoftDocs/winrt-api#2199]
Can you provide simple tutorial, how to convert code like this:
`Windows.Storage.ApplicationData.Current.LocalSettings.Values(valueName) = value`
to Azure App Service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebfd899-c97f-fdb8-1778-8b5165d42bac
* Version Independent ID: 2f7b0b36-e540-1e51-5de2-0ebdf0aad1df
* Content: [ApplicationData.RoamingSettings Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.roamingsettings?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Storage/ApplicationData.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/ApplicationData.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
That is an excellent idea, thanks. I'll add that to our project backlog.

**Comment by GrantMeStrength** [comment]
Tracked internally as USER STORY 711960

**Comment by GrantMeStrength** [comment]
In the meantime, does this help? 

https://learn.microsoft.com/en-us/azure/azure-app-configuration/

And this: The usage should be the same with App SDK apps

https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-core-app?tabs=windowscommandprompt

**Comment by pkar70** [comment]
Strange... Seems like it is not completed - there is no sample how to convert UWP app settings to Azure App Service. At least, there is no step by step, detailed "how-to" accessible.
