### ISSUE TITLE
Attached properties

### ISSUE THREAD

**Issue by mattwojo** [MicrosoftDocs/winrt-api#22]
When a user requests markdown updates for new files, the service should create new stubs provided by the build/transform service and create new files into the target repo & branch.

**Comment by kevinyr** [comment]
Matt, we do this already. Let me know if you're seeing some different behavior.

**Comment by kevinyr** [comment]
@mattwojo the issue title and comment don't seem to go together. Can you please clarify?

**Comment by mattwojo** [comment]
This is resolved -- thanks Kevin!
