### ISSUE TITLE
Specify what CoreWindow.Bounds and Window.Bounds are relative to

### ISSUE THREAD

**Issue by bencaratms** [MicrosoftDocs/winrt-api#2201]
It would be useful to specify in the documentation what CoreWindow.Bounds and Window.Bounds are relative to (the window, the screen, a virtual desktop, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1807c0-4265-5ca0-8a97-1e8fee3fc3c5
* Version Independent ID: ae4926a1-d944-0aaf-187e-81247947cde1
* Content: [CoreWindow.Bounds Property (Windows.UI.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core.CoreWindow.Bounds?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.UI.Core/CoreWindow.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Core/CoreWindow.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. This documentation has been updated.
