### ISSUE TITLE
Summary for NetworkUsed33To50Percent incorrect.

### ISSUE THREAD

**Issue by mm1nIPOVdDsu** [MicrosoftDocs/winrt-api#2202]
The summary for "NetworkUsed33To50Percent" reads "335 to 50% utilized." where it should be "33% to 50% utilized."...stupid shift key. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a7a15ed-6ed3-5b29-ad2f-6325ee7b9e8e
* Version Independent ID: 0d713d88-c9aa-6fec-73d3-a32abac06b7e
* Content: [BluetoothMinorClass Enum (Windows.Devices.Bluetooth) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothminorclass?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothMinorClass.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth/BluetoothMinorClass.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @mm1nIPOVdDsu, I've fixed that.
