### ISSUE TITLE
C++/WinRT Signature of IFrameworkView.Load method in documentation does not match what is being produced by cppwinrt.exe

### ISSUE THREAD

**Issue by JayDeezus** [MicrosoftDocs/winrt-api#2214]
Reference: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.iframeworkview.load?view=winrt-22000#windows-applicationmodel-core-iframeworkview-load(system-string)

Docs describe the method signature as:

`public void Load(string entryPoint);`

(with the `string` listed in the subsequent parameter list linking to `System.String` in the .NET 6 framework which doesn't seem right)

but the generated file is producing the signature:

`auto Load(param::hstring const& entryPoint) const;`

Shouldn't these match?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9715424b-a27d-97b5-1a42-8413334c161e
* Version Independent ID: 29cf14f7-6f4a-da19-e019-1cc7341e9178
* Content: [IFrameworkView.Load(String) Method (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.iframeworkview.load?view=winrt-22000#windows-applicationmodel-core-iframeworkview-load(system-string))
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Core/IFrameworkView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Core/IFrameworkView.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
When I have the language selected as C# on that page, I see this signature:

`public void Load(string entryPoint);`

If I change the language selection on the page to C++/WinRT, the signature in the docs changes to:

`void Load(winrt::hstring const& entryPoint);`

I think this is correct. Let me know if you see the same.

**Comment by JayDeezus** [comment]
I get the same result. My mistake then, I guess I just need to learn how to use the docs website. I didn't even see that language selector.

**Comment by alvinashcraft** [comment]
No problem! Thanks for reaching out about this.
