### ISSUE TITLE
what is the max length for serviceData in Advertisement? (GattServiceProviderAdvertisingParameters) 

### ISSUE THREAD

**Issue by 13xiaobang** [MicrosoftDocs/winrt-api#2219]
[Enter feedback here]
I want to send as much serviceData as possible in ble advertisement , but when I set it into ServiceData, if data length is more than 18bytes, it did not send out any serviceData, and noting wrong occured, I am puzzled. 
I can not find any infomation from MircosoftDocs for  max length for serviceData, is there any notice ？

code demo:

auto advParameters = ref new Bluetooth::GenericAttributeProfile::GattServiceProviderAdvertisingParameters();
advParameters->IsConnectable = true;
advParameters->IsDiscoverable = true;
auto writer = ref new Windows::Storage::Streams::DataWriter();
writer->WriteString("123456789012345678"); // success
//writer->WriteString("12345678901234567890"); // fail to send out servicedata, but noting wrong occured
advParameters->ServiceData = writer->DetachBuffer();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d50b391-047d-e4da-bb6d-d42fa08974ee
* Version Independent ID: d148fdf1-f738-74c5-131e-ff62da31a705
* Content: [GattServiceProviderAdvertisingParameters.ServiceData Property (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattserviceprovideradvertisingparameters.servicedata?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattServiceProviderAdvertisingParameters.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattServiceProviderAdvertisingParameters.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @13xiaobang.

I've added the following info to the Remarks section of GattServiceProviderAdvertisingParameters.ServiceData:

The maximum size of the **ServiceData** section depends on the availability on the platform. But if the platform supports extended advertisement, and that's what's being requested, then the maximum theoretical size will be much larger. The actual value might be less than the theoretical value, depending on what's being shared on the system. The [GattServiceProviderAdvertisementStatus.StartedWithoutAllAdvertisementData](https://docs.microsoft.com/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattserviceprovideradvertisementstatus) status indicates that the system was successfully able to issue the advertisement request, but not all of the requested data could be included in the advertisement.

-Steve
