### ISSUE TITLE
error C2039: "Close": is not a member of  "Windows::Devices::Bluetooth::GenericAttributeProfile::GattSession" ?

### ISSUE THREAD

**Issue by 13xiaobang** [MicrosoftDocs/winrt-api#2222]
[Enter feedback here]
I want to close session from BLE Peripheral, and get that error when build? But in Docs, close() is a member function of GattSession for sure.
Then how to close connection with BLE Central as a BLE Peripheral?  

demo code:
// the session is from notifyChangedHandler of SubscribedClients
notifyChangedHandler(Bluetooth::GenericAttributeProfile::GattLocalCharacteristic^ characteristic, Platform::Object^ args) {
 ...
auto session = characteristic->SubscribedClients->GetAt(0)->Session;
Session->Close(); // build error with below log
....
}

error log:

_C:\Users\Admin\proj\WinBLEClientDemo\WinBLEDemo\BLEServer.cpp(221,43): error C2039: 'Close': is not a member of 'Windows::Devices::Bluetooth::GenericAttributeProfile::GattSession'_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9210ffe-7129-8c51-a138-c299d3e2abfd
* Version Independent ID: 40f99c49-7a65-de67-6467-e88162c07159
* Content: [GattServiceProvider.AdvertisementStatusChanged Event (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattserviceprovider.advertisementstatuschanged?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattServiceProvider.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattServiceProvider.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @13xiaobang,

The code example you give is C++/CX, and the [IClosable interface](https://docs.microsoft.com/uwp/api/windows.foundation.iclosable) appears in C++/CX as Platform::IDisposable.

We recommend that you use C++/WinRT instead of C++/CX. Here's some info about using IClosable::Close with C++/WinRT: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/faq#do-i-need-to-call-iclosable--close-on-runtime-classes-that-i-consume-.

-Steve
