### ISSUE TITLE
The link broken and this page should explain the where is  PROPERTYKEY values defined

### ISSUE THREAD

**Issue by harveylv** [MicrosoftDocs/winrt-api#2223]
[Enter feedback here]

This link is broken:
https://docs.microsoft.com/en-us/windows/desktop/api/wtypes/ns-wtypes-_tagpropertykey

And users normally don't know what is PROPERTYKEY value?
This page should link to the header file of  
https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/shared/sensorsdef.h
All sensor-related PROPERTYKEYs are defined here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a97ad2d-4e14-933c-3cd2-d15441a48f63
* Version Independent ID: cbc75381-3c78-bbba-0bf4-21c3ef057fdc
* Content: [Windows.Devices.Sensors.Custom Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.custom?view=winrt-22000)
* Content Source: [winrt-api-build/xml/ns-Windows.Devices.Sensors.Custom.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Devices.Sensors.Custom.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @harveylv - the topic has been updated and should be live soon.
