### ISSUE TITLE
Incorrect parameter description for Windows.UI.Xaml.Data.CurrentChangingEventArgs constructor

### ISSUE THREAD

**Issue by ti82** [MicrosoftDocs/winrt-api#2226]
The parameter description is inverse of the parameter name. The parameter name "isCancelable" would suggest that a value of `true` would enable cancellation. The description says
> isCancelable:
>   **true** to disable the ability to cancel 
Either the description is incorrect, or the parameter name is incorrect.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5534b881-f5d9-0a86-0245-7991e87bb6ef
* Version Independent ID: 9f493fb0-99bf-4e72-db3a-e173b860b242
* Content: [CurrentChangingEventArgs Constructor (Windows.UI.Xaml.Data) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.currentchangingeventargs.-ctor?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Data/CurrentChangingEventArgs.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Data/CurrentChangingEventArgs.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for catching this error. The `isCancelable` parameter in the constructor should have the same description as the `IsCancelable` property. The documentation has been corrected.
