### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mvermef-foreflight** [MicrosoftDocs/winrt-api#2229]
[Enter feedback here]

https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.itemscontrol.itemtemplateselector
BROKEN LINK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b70433c-8766-611e-bcfa-cc2035368b33
* Version Independent ID: 64694eb5-0e1b-3e43-3596-41075ecb8edc
* Content: [ItemsControl.ItemTemplateSelector Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemscontrol.itemtemplateselector?view=winrt-17763)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ItemsControl.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ItemsControl.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Links were fixed in June, but we didn't get this issue closed. Links should be good now.
