### ISSUE TITLE
Link to Microsoft.UI.Composition.Compositor. is broken

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/winrt-api#2232]
When clicking on the [Microsoft.UI.Composition.Compositor](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.composition.compositor) link, this is the result.

<img width="701" alt="image" src="https://user-images.githubusercontent.com/608876/172807324-4dac5071-8091-4092-8e46-58c62a649c64.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 724827cf-15a5-d5d6-5679-b4712d2c03ee
* Version Independent ID: cc05a8ff-4afb-bf61-fb81-fe02bf1bb7a0
* Content: [Compositor Class (Windows.UI.Composition) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/Compositor.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/Compositor.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. This issue appears to be resolved.
