### ISSUE TITLE
IVector<T> page contains merge conflict markup

### ISSUE THREAD

**Issue by Lexikos** [MicrosoftDocs/winrt-api#2233]
This page appears to contain markup from a merge conflict; i.e.
```
<<<<<<< HEAD IVector inherits ...
...
>>>>>>> cd84458f70e29e2fa6b720ec78056581fa3bce0b
```
(The last part renders as a sequence of nested blockquotes.)

Side note: The "Content Source" link below doesn't render correctly (here on GitHub) due to the backtick in the interface name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1897ffed-ceed-72d1-9fba-82541ac877af
* Version Independent ID: 247436b5-6c34-da61-fd01-87597be694e7
* Content: [IVector&lt;T&gt; Interface (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.ivector-1?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/IVector`1.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/IVector`1.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
It looks like somebody else has resolved this problem without closing the issue. This feels resolved, so I'm going to close this issue.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
