### ISSUE TITLE
ApplicationData.RoamingFolder Property

### ISSUE THREAD

**Issue by ppoirier1** [MicrosoftDocs/winrt-api#2236]
Wording is unclear on the warning section "allows non-Microsoft developers..."  I'm writing a UWP app for (only) Windows and need to sync some data on other Windows devices also running the UWP app.  I don't need to access it from non-Windows devices.  I can't tell from the description whether or not that will work in the future.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af89d63-fbd1-3c97-f842-abd73b15b92b
* Version Independent ID: 6041257a-2ab5-c90e-be97-13a22d637e34
* Content: [ApplicationData.RoamingFolder Property (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.roamingfolder?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage/ApplicationData.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/ApplicationData.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi. The roaming storage is no longer supported in Windows 11. We will be updating these warnings that use roaming data to be more explicit, like the one on [this page](https://docs.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#roaming-data). I will close this issue after the wording on the RoamingFolder topic is clarified.

**Comment by alvinashcraft** [comment]
The changes have been merged and should appear on the live site soon. Thanks again for pointing out this issue.
