### ISSUE TITLE
Unclear what intended usage is for `void IBuffer::Length(uint32_t) const`.

### ISSUE THREAD

**Issue by JayDeezus** [MicrosoftDocs/winrt-api#2237]
I'm looking at this page from the C++/WinRT perspective.

What is the intended function for the second form of the Length property? Docs mention "getting" the number of bytes used in the buffer, and nothing about setting the value nor what setting this property should do to the deriving class.

Does this have a setter-like method because the C# version has a set method for the Length property? What is setting the length here supposed to even mean? Is the implementing class supposed to be able to change the buffer length if this is set?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9361bb5c-c2a4-0cea-5bf8-1a0aef9a6d2f
* Version Independent ID: f6a5326a-e275-7e8f-a9bb-46606d46aeec
* Content: [IBuffer Interface (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.ibuffer?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage.Streams/IBuffer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Streams/IBuffer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by jaigak** [comment]
It's for resizing the buffer while preserving the contents. If your class implementing IBuffer does not/need not support resizing, you can simply throw hresult_not_implemented{};

**Comment by alvinashcraft** [comment]
Thanks, @JayDeezus and @Jaiganeshkumaran. I will create an internal work item to see how I can improve the docs for this page and track the work. I'm going to close this issue, but I will circle back and update it when the docs are updated. Feel free to continue leaving comments here with any additional feedback.
