### ISSUE TITLE
Links to WinUI 2 API broken

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftDocs/winrt-api#2240]
The link referenced by "Equivalent WinUI 2 API for UWP" is 404 - page not found:
https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.contentcontrol 

With many other UWP controls document pages referencing WinUI 2, the link is broken, e.g.
AppBar, AppBarButton, AppBarClosedDisplayMode - just the first three ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5dce85-ad5d-2ad2-b3f9-95837d19177e
* Version Independent ID: 6120a91c-158e-768e-d4a6-39b575938a10
* Content: [ContentControl Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.ContentControl?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ContentControl.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ContentControl.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for reporting this @christiannagel. We just decoupled WinUI 2 ref from WinUI in the Windows App SDK (WinUI 3) and these links were created to point to WinUI 3 APIs in the previously shared reference repo. As there is no equivalent WinUI 2 API, I'll delete the broken links as soon as I get a broken link report.

**Comment by christiannagel** [comment]
After just using the WinUI 3 Gallery app - I think it would be great if redirects for the old links would be added. The WinUI 2 Gallery app and the WinUI 3 Gallery app contains links to the WinUI documentation which are all broken now.

**Comment by Karl-Bridge-Microsoft** [comment]
@christiannagel - there is a PR to fix this. 

@gregwoo-microsoft - any updates on this?

**Comment by gregwoo-microsoft** [comment]
Yes, we are pushing out a Store update of the WinUI 3 Gallery this afternoon.

**Comment by gregwoo-microsoft** [comment]
The update is out in the Store now :)

**Comment by Karl-Bridge-Microsoft** [comment]
Tested a few controls in the gallery and the links to Win App SDK API ref appear to be working again. Closing issue.

**Comment by riverar** [comment]
Continues to be broken all over the place, e.g. https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data

@Karl-Bridge-Microsoft

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @riverar - for the most part, these were in two namespaces (per the latest broken link report). All have been deleted. I'll check the next run of the broken link report for lingering issues (when available).
