### ISSUE TITLE
FlyoutBase.ShouldConstrainToRootBounds doesn't always default to false

### ISSUE THREAD

**Issue by JesseCol** [MicrosoftDocs/winrt-api#2245]
The doc says "The default is false."

I believe that depends on the concrete type -- for a MenuFlyout it's false, but for a Flyout it's true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1b416b-01ee-2b61-fc36-879e9d2f0557
* Version Independent ID: 47549116-6ee7-27f2-1d77-9042d4f041ea
* Content: [FlyoutBase.ShouldConstrainToRootBounds Property (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutbase.shouldconstraintorootbounds?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls.Primitives/FlyoutBase.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls.Primitives/FlyoutBase.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for catching that. The documentation has been updated.

**Comment by JesseCol** [comment]
> Thanks for catching that. The documentation has been updated.

Terrific!  Thanks!
