### ISSUE TITLE
`System.Char` type should be shown as `char16_t` in "C++/WinRT" page language

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/winrt-api#2251]
Right now `System.Char` is rendered as `char` but should be `char16_t` in "C++/WinRT" page language

For example:

![image](https://user-images.githubusercontent.com/1285934/176787209-84049545-a95b-404f-bcb7-aef323e8e7ce.png)

Property value for `char16_t` could link to this page: https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/strings (or maybe you can find something better, C# uses this link for example: https://docs.microsoft.com/dotnet/api/system.char).

Please fix this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fb0813d-e2c8-4c1a-f8af-a651fe37908e
* Version Independent ID: 15989b82-56fe-dd9d-e421-2efdad547652
* Content: [CharacterReceivedRoutedEventArgs.Character Property (Windows.UI.Xaml.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.characterreceivedroutedeventargs.character?view=winrt-22621#windows-ui-xaml-input-characterreceivedroutedeventargs-character)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Input/CharacterReceivedRoutedEventArgs.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Input/CharacterReceivedRoutedEventArgs.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft hey! can you please take a look at this issue?

**Comment by Karl-Bridge-Microsoft** [comment]
This is a doc build issue and not something that supports an authored fix. I've notified our engineering team and hope to have a fix in place soon. Currently no ETA.

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft Thank you!

**Comment by jaigak** [comment]
I believe it's actually char16_t and not wchar_t. While both encode an USC-2 character on Windows, the types are distinct.

**Comment by DJm00n** [comment]
@Jaiganeshkumaran I have looked at what cppwinrt actually emits. It’s ‘wchar_t’.

Also, UCS-2 is deprecated encoding. AFAIK Windows wide strings are UTF-16.

**Comment by jaigak** [comment]
> Also, UCS-8 is deprecated encoding. AFAIK Windows wide strings are UTF-16.

That's right for a wide string, but a single wide character can't store all UTF-16 code points (UTF-16 is variable length).

**Comment by DJm00n** [comment]
>in single wide character can't store all UTF-16 code points 

yes. In cases where this is needed Windows provides multiple wchars. For example you’re receive multiple WM_CHAR events for non-BMP chars (so called surrogate pairs)

**Comment by stevewhims** [comment]
Yes, it looks like the projection returns a `char16_t`.

```cppwinrt
    template <typename D> auto consume_Windows_UI_Xaml_Input_ICharacterReceivedRoutedEventArgs<D>::Character() const
    {
        char16_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::Windows::UI::Xaml::Input::ICharacterReceivedRoutedEventArgs)->get_Character(&value));
        return value;
    }
```

**Comment by DJm00n** [comment]
@kennykerr can you please comment on this?

**Comment by kennykerr** [comment]
@stevewhims is correct that it is `char16_t` - in earlier version of cppwinrt it was `wchar_t`.

https://github.com/microsoft/cppwinrt/blob/master/cppwinrt/type_writers.h#L475

**Comment by Karl-Bridge-Microsoft** [comment]
Our doc build system has been updated to address this issue. A link is not possible, but the type is now correct.
