### ISSUE TITLE
 Is IgnorableServerCertificateErrors a property or a function?

### ISSUE THREAD

**Issue by gangli66** [MicrosoftDocs/winrt-api#2254]
When I used HttpBaseProtocalFilter to add some ChainValidationResults, it throwed an error that IgnorableServerCertificateErrors can only be used to call function. So is IgnorableServerCertificateErrors a property or a function?
I used it in my project that builded by react-native-windows.
[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7f978696-1f8c-f5ce-f89b-09ffe9076d52
* Version Independent ID: d6df24c1-79d6-67e7-b72b-6368dbb55dc2
* Content: [HttpBaseProtocolFilter.IgnorableServerCertificateErrors 属性 (Windows.Web.Http.Filters) - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.web.http.filters.httpbaseprotocolfilter.ignorableservercertificateerrors?view=winrt-22000#windows-web-http-filters-httpbaseprotocolfilter-ignorableservercertificateerrors)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build.zh-CN?path=/winrt-api-build/xml/Windows.Web.Http.Filters/HttpBaseProtocolFilter.xml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build.zh-CN?path=/winrt-api-build/xml/Windows.Web.Http.Filters/HttpBaseProtocolFilter.xml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @gangli66, HttpBaseProtocolFilter.IgnorableServerCertificateErrors is a property. The title of the topic in en-us is "HttpBaseProtocolFilter.IgnorableServerCertificateErrors property".

In C#, you'd use it like `var a = myHttpBaseProtocolFilterObject.IgnorableServerCertificateErrors;`. But in C++/WinRT you'd use it like `auto a = myHttpBaseProtocolFilterObject.IgnorableServerCertificateErrors();`. So in some languages, it looks like a function call.

Hope that helps,
-Steve
