### ISSUE TITLE
Wrong default value

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/winrt-api#2256]
It states that the default value for AutoPlay is true, but when checking this, it is in fact false.
![image](https://user-images.githubusercontent.com/1378165/178091677-8f5ca225-7a18-4af8-b002-db8dc7699cf3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6bdb34-ca2d-81f1-e2bf-72840de34db8
* Version Independent ID: 027b815e-e322-746b-fd33-aa82a904c26e
* Content: [MediaPlayerElement.AutoPlay Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaplayerelement.autoplay?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaPlayerElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/MediaPlayerElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for catching this. The default for MediaElement is `true`, but for MediaPlayerElement, it's `false`. The documentation has been corrected.
