### ISSUE TITLE
UWP.C++.SimpleOrientationSensor.DeviceId gets Invalid Value  

### ISSUE THREAD

**Issue by PACALA-BA** [MicrosoftDocs/winrt-api#2257]
[
SimpleOrientationSensor.DeviceId ...SEEMS TO BE WRONG ID, Microsoft BUG ? 
0x07284088 L"**SDO\SOFTWARE_SERVICE"**   <---- **THIS IS +NOT+ VALID DEVICE ID** 

_accelerometer->DeviceId.....OK, WORKING WELL 0x018e8960 L"\\?\ACPI#QCOM2495#2&daba3ff&0#{c2fb0f5f-e2d2-4c78-bcd0-352a9582819d}\{63F7694C-8884-4790-B44A-6242C728EDD3}" <------- THIS IS VALID, OK
[SEE THIS THREAD ..](https://stackoverflow.com/questions/72929330/uwp-c-simpleorientationsensor-deviceid)
]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ba2c8f8-bdcf-913b-9f53-c0adb91e5587
* Version Independent ID: 481af7ee-9b87-66b3-e635-eb74f289d087
* Content: [SimpleOrientationSensor.DeviceId Property (Windows.Devices.Sensors) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.simpleorientationsensor.deviceid?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Devices.Sensors/SimpleOrientationSensor.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Sensors/SimpleOrientationSensor.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No doc bug reported.
