### ISSUE TITLE
No Add method on the page?

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/winrt-api#2258]
Looked real hard for it, came up empty. Am using Add method ib code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443ccf75-dd01-17c0-c05e-8b4b8168e6f4
* Version Independent ID: 1f4a6591-f626-c33b-b0b9-ff4af7a258db
* Content: [ValueSet.Clear Method (Windows.Foundation.Collections) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.valueset.clear?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Collections/ValueSet.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Collections/ValueSet.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by jwmsft** [comment]
Thanks for the feedback, and sorry for the late reply. This is a limitation of the doc system's ability to handle projections to different languages. Depending on your development language, you'll use either Add or Insert, but a doc is only generated for Insert. The [Insert](https://learn.microsoft.com/uwp/api/windows.foundation.collections.valueset.insert) method includes this note:
"Some functionality in this class is restricted to specific development languages. ... For functionality similar to this member, see [Add(String,Object)](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2.add?view=dotnet-uwp-10.0&preserve-view=true)."

**Comment by kcovert** [comment]
Thanks for the reply,
Kirk

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
