### ISSUE TITLE
Broken Link for 3D Model Repair service/details

### ISSUE THREAD

**Issue by connorturlan** [MicrosoftDocs/winrt-api#2260]
[3D Model Repair service](https://aka.ms/modelrepair) at the base of the page is a broken link to a blank Bing homepage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc84aee-0b27-e776-d54e-7693cbf06e6b
* Version Independent ID: 85887857-d411-9e16-5022-c3897c877030
* Content: [Windows.Graphics.Printing3D Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Printing3D?redirectedfrom=MSDN&view=winrt-22621)
* Content Source: [winrt-api-build/xml/ns-Windows.Graphics.Printing3D.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Graphics.Printing3D.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reporting this. It appears that the Microsoft's online 3D model repair tool has been retired:

https://tools3d.azurewebsites.net/

So, rather than update the link, I've removed the entire sentence. The change should appear on the live site within a few hours.
