### ISSUE TITLE
Microsoft Myanmar

### ISSUE THREAD

**Issue by MrHtetNaingSoe** [MicrosoftDocs/winrt-api#2264]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67ebcd9-f641-9876-4777-9dd096c7fe35
* Version Independent ID: bfe0376c-6e80-bc84-a865-09723dc8475c
* Content: [Windows.ApplicationModel.Appointments.DataProvider Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appointments.dataprovider?view=winrt-22621)
* Content Source: [winrt-api-build/xml/ns-Windows.ApplicationModel.Appointments.DataProvider.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.ApplicationModel.Appointments.DataProvider.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
It looks like there's no actionable feedback here, so I'll go ahead and close the issue. Please open a new issue if you have feedback about the documentation that you'd like us to address.
