### ISSUE TITLE
PhoneCallManager_CallStateChanged c++

### ISSUE THREAD

**Issue by PACALA-BA** [MicrosoftDocs/winrt-api#2269]
[Enter feedback here]
Hi, missing example for C++, OR how can i change this to c++ syntax ? Thanks..

PhoneCallManager.CallStateChanged += PhoneCallManager_CallStateChanged;
private async void PhoneCallManager_CallStateChanged(object sender, object e)
{
    if (callCame&&(!PhoneCallManager.IsCallActive))
    {
        //do something
    }
    if (PhoneCallManager.IsCallIncoming)
    {
        callCame = true;
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef0dbd6-0e45-6afd-18db-9d93e0f7e7a0
* Version Independent ID: c537f6aa-792f-30db-9753-7f16f14390ac
* Content: [PhoneCallManager.CallStateChanged Event (Windows.ApplicationModel.Calls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.phonecallmanager.callstatechanged?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Calls/PhoneCallManager.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Calls/PhoneCallManager.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp and C++.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
