### ISSUE TITLE
GetActivatedEventArgs keeps returning the initial protocol event even on subsequent calls

### ISSUE THREAD

**Issue by yowl** [MicrosoftDocs/winrt-api#2271]
This sentence doesn't seem right for WPF apps that register a scheme for protocol activation through a manifest

"This method only returns arguments on its first call. Subsequent calls return null."

If in the App class you override:
```
protected override void OnActivated(EventArgs e)
{
    base.OnActivated(e);
    var activationArgs = AppInstance.GetActivatedEventArgs();
    if (activationArgs != null)
    {
        switch (activationArgs.Kind)
        {
            case ActivationKind.Protocol:
                var protocolArgs = (IProtocolActivatedEventArgs)activationArgs;
                MessageBox.Show(protocolArgs.Uri.ToString());
                break;
        }
    }
}
```

and activate the app from another program with something like:

```
var uri = new Uri("theregisteredscheme://something");
Launcher.LaunchUriAsync(uri);
```

The message box will popup.  However if you close it and click the main window in the app with the registered scheme, the popup will appear again, for every click made to activate the window.   I.e. `GetActivatedEventArgs` does not return null on subsequent calls.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8620059a-551a-ba5d-9ae4-54e9ef51f1d0
* Version Independent ID: 3ddb9fa0-f2ff-7700-635c-55e5ce97dac8
* Content: [AppInstance.GetActivatedEventArgs Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.appinstance.getactivatedeventargs?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel/AppInstance.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel/AppInstance.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @yowl. This may be one of those cases where the behavior is different for desktop apps, depending on whether they have package identity. Is your WPF app packaged with MSIX? Are you able to reproduce this in a UWP app or other packaged app?

**Comment by yowl** [comment]
I think I was using an appx for this testing, but let me double check.

**Comment by alvinashcraft** [comment]
Any update on your WPF app for this issue? If there's a difference in behavior based on package identity, I can add a note to the docs.

**Comment by alvinashcraft** [comment]
Hi @yowl. I'm creating an internal work item to update the docs to indicate the difference in behavior between packaged and unpackaged apps. I am closing this work item now, but I will circle back when the updates are complete. Thanks for your feedback!
