### ISSUE TITLE
Provide reference on how to use this API in a Desktop app

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#2275]
I'm not sure if this should go in remarks or see also or some other place, but it should have a link to information on how to use this API outside of UWP: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c219be13-bd93-5764-00c0-0fdb8e382e58
* Version Independent ID: 9a524a3d-bfe3-1f17-e0dc-5c8594fa9121
* Content: [FileOpenPicker Class (Windows.Storage.Pickers) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers/FileOpenPicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers/FileOpenPicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks, Mike. That's a good callout. I'll add a note to the Remarks section.

**Comment by alvinashcraft** [comment]
Hi @MikeHillberg. I created a PR in the internal repo to add this link and added you as a reviewer. I'm going to close this but let me know if you feel additional changes are needed anywhere. Thanks again for the suggestion.

**Comment by alvinashcraft** [comment]
The page has been updated with info and a link for using the API from desktop apps: https://docs.microsoft.com/uwp/api/windows.storage.pickers.fileopenpicker

Let me know if you have any other suggestions, @MikeHillberg
