### ISSUE TITLE
Documentation is unclear about parameter TypeName

### ISSUE THREAD

**Issue by nikolayvpavlov** [MicrosoftDocs/winrt-api#2277]
The documentation is very unclear about parameter `TypeName`.  

First it says: 

> The page to navigate to, specified as a type reference to its partial class type. 

This somewhat implies that the type must be [Page](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Page?view=winrt-22621), but this is not explicitly mentioned.  

Then the second overload states:

> Causes the [Frame](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame?view=winrt-22621) to load content represented by the specified [Page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.page?view=winrt-22621), also passing a parameter to be interpreted by the target of the navigation.

Which is clearer, but leaves the user wonder if the first overload has different capabilities.

Finally, the documentation of [Page](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Page?view=winrt-22621) mentions:

> Represents content that a [Frame](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame?view=winrt-22621) control can navigate to.

Which in turn implies that Frame can navigate only to pages.

The documentation of Frame must explicitly state that parameter **TypeName**" must be of type Page, and that otherwise it will give a run-time error.  

The documentation also misses information what exceptions can the method throw and when.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94604fa8-98f6-6ea7-de33-e2edeb2408fa
* Version Independent ID: 6b2b3b55-7b4f-0a58-1dbf-2979bfd3f0eb
* Content: [Frame.Navigate Method (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame.navigate?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Frame.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Frame.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jaigak** [comment]
Currently it just throws NullReferenceException: https://github.com/microsoft/microsoft-ui-xaml/issues/6007.

**Comment by jwmsft** [comment]
Thanks for the feedback. This documentation has been updated.
