### ISSUE TITLE
not a single reference to what input scope values are. Terrible page.

### ISSUE THREAD

**Issue by madmrmax** [MicrosoftDocs/winrt-api#2280]
There should be an easy link to valid values for input scope. How hard is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f5e1527-a47a-2b01-79ef-cfa2ece46c52
* Version Independent ID: 75ae818a-39b3-3343-54d9-51efdeac4bd9
* Content: [TextBox.InputScope Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.inputscope?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/TextBox.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/TextBox.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. The source markdown file does contain a link to the InputScopeNameValue enum in the -xaml-values section, but that is not being rendered on the page due to a bug in the publishing pipeline. I've updated the page to include the link in the Remarks and See also sections.
