### ISSUE TITLE
If a NULL object is passed in, the system turns on auto-brightness.

### ISSUE THREAD

**Issue by PACALA-BA** [MicrosoftDocs/winrt-api#2281]
If a **NULL object** is passed in, the system turns on auto-brightness......
Hi, where is an **EXAMPLE of NULL object** for Windows.Graphics.Display.BrightnessOverride  in CPP or CS?
Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a12e8955-1751-1c60-2e78-13a6975cc297
* Version Independent ID: 72ce360f-cfd7-1233-133b-632a4effe716
* Content: [BrightnessOverride.SaveForSystemAsync(BrightnessOverride) Method (Windows.Graphics.Display) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.brightnessoverride.saveforsystemasync?view=winrt-22621#windows-graphics-display-brightnessoverride-saveforsystemasync(windows-graphics-display-brightnessoverride))
* Content Source: [winrt-api-build/xml/Windows.Graphics.Display/BrightnessOverride.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Display/BrightnessOverride.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @PACALA-BA.

I think this was just a case of poor wording in the content. This is the only topic that uses the phrase "NULL object". In the docs, we talk about simply "null". In this case, we'd mean calling the method like `BrightnessOverride.SaveForSystemAsync(null);` for C#. C++ folks will know to pass `nullptr` instead.

I've published a fix to the topic.

Thanks!
-Steve
