### ISSUE TITLE
AvailabilityChanged event invoked when I lock screen

### ISSUE THREAD

**Issue by hongjiapeng** [MicrosoftDocs/winrt-api#2283]
[Enter feedback here]

This issue can be copied on some computers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7b0b78-d6ab-ca3f-f622-a21acc8f6978
* Version Independent ID: 25afbb3f-2b80-9f8c-72a4-70cdf6d20ed9
* Content: [Windows.ApplicationModel.ConversationalAgent Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.conversationalagent?view=winrt-22621)
* Content Source: [winrt-api-build/xml/ns-Windows.ApplicationModel.ConversationalAgent.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.ApplicationModel.ConversationalAgent.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Closing. No doc issue reported.
