### ISSUE TITLE
Improve documentation about XamlRoot property

### ISSUE THREAD

**Issue by JesseCol** [MicrosoftDocs/winrt-api#2286]
It sometimes surprises folks that UIElement.XamlRoot returns null when it's queried before the element is added to a live tree of XAML.  Maybe we could add more info about that here?

Example: When a UIElement is first created, XamlRoot returns null.  After it's parented to a live XAML object, it will return the same XamlRoot object as its parent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4437660c-c9b0-4f4e-ce20-3d62787c5b76
* Version Independent ID: fddaa5db-2fa7-fde7-a6d3-f776b5e131fb
* Content: [UIElement.XamlRoot Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.xamlroot?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/UIElement.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by pratikone** [comment]
I would add that the most frequent scenario of null xamlroot would be calling Xamlroot from constructor of the app.

**Comment by jwmsft** [comment]
Thanks for the suggestion; the documentation has been updated.
