### ISSUE TITLE
DisplayTask.SetSignal has no parameter for fence value

### ISSUE THREAD

**Issue by rpavlik** [MicrosoftDocs/winrt-api#2289]
I'm looking at this newer API, and I notice it has no parameter to specify what value to signal on the fence. I was pretty sure only Vulkan had binary sync primitives in the GPU stuff, and that the D3D fences were all ones with increasing values (what Vulkan calls "timeline semaphores"). But, it's not clear what value I should wait for on the fence passed to SetSignal.  Is this an API bug or is there some binary-fence wait I'm not aware of?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48a525af-5b61-fc0d-fde2-a40b3b758023
* Version Independent ID: 95a06a48-fdb8-bd35-6f02-939aeb0db3c6
* Content: [DisplayTask.SetSignal(DisplayTaskSignalKind, DisplayFence) Method (Windows.Devices.Display.Core) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaytask.setsignal?view=winrt-22621#windows-devices-display-core-displaytask-setsignal(windows-devices-display-core-displaytasksignalkind-windows-devices-display-core-displayfence))
* Content Source: [winrt-api-build/xml/Windows.Devices.Display.Core/DisplayTask.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Display.Core/DisplayTask.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @rpavlik! I'm investigating.

-Steve

**Comment by stevewhims** [comment]
I've just published an update to the topic with more info. The links function in the updated topic, but here's a copy of the info I added:

The fence value that is signaled is the value that's returned from **DisplayTaskPool.TryExecuteTask** in the **DisplayTaskResult.PresentId** property (it's very probable that it will increase by 1 with each Present).

Thanks!
-Steve
