### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by ultracodez** [MicrosoftDocs/winrt-api#2290]
Typo :)
![image](https://user-images.githubusercontent.com/80412399/192661077-be632444-4b0d-4370-a81a-90d81c1a236b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce88b8b-ad32-bcc7-bb9c-834d3cc487e8
* Version Independent ID: eef88d4b-6051-95fe-b180-868dd8ff4db7
* Content: [FileSavePicker Class (Windows.Storage.Pickers) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.filesavepicker?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers/FileSavePicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers/FileSavePicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for submitting a PR to fix this issue, @ultracodez. I just merged it, so you should see the change on the live site later today.
