### ISSUE TITLE
Bad sample code for Dispatcher.RunAsync

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#2293]
The 'Await a UI task ...' section correctly describes the problem with awaiting on a RunAsync call. Unfortunately the only sample code it shows is what _not_ to do, it doesn't have any sample on what the right code is. I believe the correct code is:

```
var taskCompletionSource = new TaskCompletionSource();

dispatcherQueue.TryEnqueue(new DispatcherQueueHandler(() =>
{
    ... whatever you want to do ...
    taskCompletionSource.SetResult();
}));

await taskCompletionSource.Task;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 331adaef-1035-fd88-0d7b-ca4ff97ee761
* Version Independent ID: 173e41e3-b747-cf7b-9b43-3d678f21eacb
* Content: [CoreDispatcher.RunAsync(CoreDispatcherPriority, DispatchedHandler) Method (Windows.UI.Core) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/Windows.UI.Core.CoreDispatcher.RunAsync?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Core/CoreDispatcher.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Core/CoreDispatcher.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@MikeHillberg, thanks for the feedback. The RunAsync doc has been updated with a TaskCompletionSource example.
