### ISSUE TITLE
Undocumented exception can be thrown by GetItemCountAsync

### ISSUE THREAD

**Issue by HunterB06** [MicrosoftDocs/winrt-api#2294]
Hello,

`GetItemCountAsync` does throw an exception when the library definition is empty. This behaviour is not documented.

Here are the details of the exception:
`System.Exception: "La bibliothèque, le lecteur ou le pool de média sont vides. (Exception from HRESULT: 0x800710D2)"`

Please document this part as it can break some applications using this API.

Regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5dd3546a-33af-823f-c2a1-7da0e0a253a7
* Version Independent ID: 2fe51c53-bc64-9f90-419f-5b82de543999
* Content: [StorageItemQueryResult.GetItemCountAsync Méthode (Windows.Storage.Search) - Windows UWP applications](https://learn.microsoft.com/fr-fr/uwp/api/windows.storage.search.storageitemqueryresult.getitemcountasync?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage.Search/StorageItemQueryResult.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Search/StorageItemQueryResult.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thank you for submitting this issue. I will try the API myself and add a note to the docs with the exception information. I will circle back here when the changes are ready.

**Comment by alvinashcraft** [comment]
Hi @HunterB06. I updated the remarks section with information about exceptions in this scenario. I didn't add a specific error message because the message and error type I received was different than yours. I hope this helps! Please reach out if you have any questions.
