### ISSUE TITLE
Typographic error caused by escaping character backslash

### ISSUE THREAD

**Issue by dexblack** [MicrosoftDocs/winrt-api#2299]
`backslash ''`  should be `backslash '\'`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dda398ee-1825-762b-d93d-cf3ec4d34872
* Version Independent ID: a1917c3f-a853-d461-4aa9-a5d633baa1f2
* Content: [HttpCookie.Value Property (Windows.Web.Http) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.web.http.httpcookie.value?view=winrt-22621#windows-web-http-httpcookie-value)
* Content Source: [winrt-api-build/xml/Windows.Web.Http/HttpCookie.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Web.Http/HttpCookie.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @dexblack! I fixed that (and many other similar instances across the docs).

-Steve
