### ISSUE TITLE
Documentation Link Leads to Bing.com

### ISSUE THREAD

**Issue by jmc718** [MicrosoftDocs/winrt-api#2303]
Trying to use the Windows service API to perform repairs on a 3D model using the function found [here](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.printing3d.printing3dmodel.repairasync?view=winrt-22621#applies-to).

There appears to be some information missing on how to execute some crucial tasks, such as what sorts of inputs and outputs the function expects. 

Under the remarks section, it reads:

> To learn more about the 3D model repair algorithm and test it out quickly, go to the [3D Model Repair service](https://aka.ms/modelrepair).

However, this redirects to the Bing Homepage. I would really like to be able to use this so any help would be appreciated.

**Comment by GrantMeStrength** [comment]
Hello - I'm sorry, the online service is no longer available:

https://3mf.io/blog/2022/04/microsoft-is-sunsetting-the-3mf-service/

But there is a standalone tool available from that page which might help.

I will update the doc to reflect that.
