### ISSUE TITLE
How/where do I get a UIContext to pass to this method?

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/winrt-api#2307]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ffdf484-104f-846a-47cc-49d2e7c003b9
* Version Independent ID: 180e21e4-c12f-54b0-7a1c-bd723756b56e
* Content: [ResourceLoader.GetForUIContext(UIContext) Method (Windows.ApplicationModel.Resources) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.resourceloader.getforuicontext?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Resources/ResourceLoader.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Resources/ResourceLoader.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @amp64. You can get UIContext from an AppWindow (https://learn.microsoft.com/uwp/api/windows.ui.windowmanagement.appwindow.uicontext) or any UIElement (https://learn.microsoft.com/uwp/api/windows.ui.xaml.uielement.uicontext).

I hope this helps. If you think it would be useful, I could add those two links to a See Also section on the GetForUIContext docs.

**Comment by alvinashcraft** [comment]
I am closing this issue for now, but feel free to continue the conversation if you have any questions. I just merged a PR to add See Also links on this page for the two UIContext topics in my previous comment. Those Docs changes should be live later today.

If you have additional questions about using the APIs, the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp. If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Thanks!
