### ISSUE TITLE
DispatcherQueueTimer for UWP only shows up in Search Results and not easy to find WindowsAppSDK version

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#2309]
Now that the Windows App SDK has been out for a while, when searching for 'DispatcherQueueTimer' or 'DispatcherQueueTimer WindowsAppSDK' the UWP page still comes up first, but the Windows App SDK one is in a different namespace:

https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.dispatching.dispatcherqueuetimer

This makes it confusing to find, and the UWP page here doesn't have the normal info on it calling out the new location if using the WindowsAppSDK like the control docs do.

This page should be updated with that notice near the top to clarify that this is the UWP doc and for the WinUI 3 / WindowsAppSDK usage to go to the new page above.

FYI @gabbybilka @bpulliam

Also note, VS doesn't detect this as properly available in multi-targeted projects (both UWP and WindowsAppSDK targets) because of the different namespaces, see discussion on that here and confusion on availability of this API because of it: https://github.com/CommunityToolkit/Labs-Windows/pull/307#discussion_r1019426250

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de717875-912f-6404-1f6e-f25048f74ac2
* Version Independent ID: f25562b6-df93-b31b-b362-54533fe5be73
* Content: [DispatcherQueueTimer Class (Windows.System) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueuetimer?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It's fixed now. It was temporarily broken as part of a phased move operation. Thanks for reporting it
