### ISSUE TITLE
Incorrect description for the field LteAdvanced

### ISSUE THREAD

**Issue by aberus** [MicrosoftDocs/winrt-api#2315]
The description is following:

LteAdvanced | 32 | The device supports the HSDPA Lite data service implemented by GSM providers.
-- | -- | --

It should be something like this:
The device supports the LTE/LTE Advance data service implemented by GSM providers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19222db5-bf38-5273-d921-62d54efc7611
* Version Independent ID: db4908ef-77b6-f8aa-be81-e8cb385efbcb
* Content: [DataClasses Enum (Windows.Networking.NetworkOperators) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.networking.networkoperators.dataclasses?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Networking.NetworkOperators.DataClasses.Custom)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%253Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Networking.NetworkOperators/DataClasses.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.NetworkOperators/DataClasses.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @aberus! I've fixed that.

-Steve
