### ISSUE TITLE
Initial Focus is to Lowest Numerical TabIndex not the Highest TabIndex

### ISSUE THREAD

**Issue by StevenEdwardWood** [MicrosoftDocs/winrt-api#2317]
The Remarks section says, "For UWP apps, initial focus is set to the element with the highest TabIndex that can receive focus." But the actual "initial focus is set to the element with the lowest numerical TabIndex which can receive focus."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e735758-11d3-7725-8090-f8a8ff587c01
* Version Independent ID: ec1072dc-7d79-4b13-ceb3-bf4364df16bc
* Content: [Control.TabIndex Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.tabindex?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/Control.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/Control.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks fo the suggestion. In fact, this topic is correct as the default (MaxValue) is the case when a control has not been assigned a tab index. Tab order follows any actual declared order and then returns to those controls without a declared tab index.

**Comment by StevenEdwardWood** [comment]
The initial focus in a current UWP application is set to the element with the lowest TabIndex which has been assigned a tab index. According to your statement the initial focus is set to an element that has not been assigned a TabIndex which is wrong. What would be the point of assigning an element a TabIndex at all if elements without a TabIndex are going to receive focus first?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @StevenEdwardWood - you're correct, I misunderstood your issue and commented on a different aspect of the property. Topic has been updated. Thanks!
