### ISSUE TITLE
Need example code

### ISSUE THREAD

**Issue by zeltrax00** [MicrosoftDocs/winrt-api#2319]
I think C++/WinRT need example for this event handling. I don't know what to do with many overloaded function in C++ version

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2032645-d33a-15cf-7e74-3f855c9b0765
* Version Independent ID: b8bfa848-6fea-5ed9-1787-66834bc7e225
* Content: [ToastNotification.Activated Event (Windows.UI.Notifications) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification.activated?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Notifications/ToastNotification.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Notifications/ToastNotification.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
There are several links in the page to sample apps, quickstarts, and snippets. We create code samples based on a variety of performance data. Unfortunately I can't say when we might create this sample, or guarantee we ever will. In the meantime, I hope the links on the page can help you find what you're looking for.
