### ISSUE TITLE
User::NonRoamableId missing details.

### ISSUE THREAD

**Issue by jjakubovic** [MicrosoftDocs/winrt-api#232]
Hi,

Description of User::NonRoamableId [here](https://docs.microsoft.com/en-us/uwp/api/windows.system.user) would use some details.

Like when it's guaranteed to stay the same and when not. From my observations:
- It's different for the same user on different machines (that's understandable, it's nonroamable). 
- It seems to be different, when the same user logs in locally and remotely. 
- It seems to stay the same after the restart. 
- It seems to be different in each app for the same user on the same machine but.

Or if it's guaranteed to be different for two local users (i.e. not domain users) on different machines.

I was not sure whether I can use it to reliably identify the user or not, so I had to do all this tests myself.

Thanks,
J.

**Comment by ginami** [comment]
Thank you @jjakubovic for your feedback. @jwmsft, can you address this?

Thank you!

**Comment by jwmsft** [comment]
Thanks @jjakubovic, @ginami. I've updated the doc with more information and some example code.

**Comment by jjakubovic** [comment]
Thanks!
