### ISSUE TITLE
No exception is thrown when more than 20 credentials are created

### ISSUE THREAD

**Issue by ackh** [MicrosoftDocs/winrt-api#2330]
The **Remarks** section for `PasswordVault.Add(PasswordCredential)` states the following:

> You can only store up to 20 credentials per app in the Credential Locker. If you try to store more than 20 credentials, you will encounter an [Exception](https://learn.microsoft.com/en-us/dotnet/api/system.exception?view=dotnet-uwp-10.0&preserve-view=true).

However, the below test code does not cause any exceptions to be thrown on Windows 10 (19045.2486) even though it creates 200 credentials. It is C# code (.NET Framework 4.7.2) and accesses the API via [Microsoft.Windows.SDK.Contracts](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts) NuGet package so the mentioned limitation _should_ apply.

````csharp
public void PasswordVaultTest()
{
   int credentialCount = 200;

   for (var i = 0; i < credentialCount; i++)
   {
      passwordVault.Add(new PasswordCredential($"TestAccount.{i}", "MyAccount", "MyPassword"));
   }

   for (var i = 0; i < credentialCount; i++)
   {
      passwordVault.Remove(new PasswordCredential($"TestAccount.{i}", "MyAccount", "MyPassword"));
   }
}
````

This behavior contradicts the quoted statement. Is this a bug in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63001b53-c7d5-2890-0e31-38b6827efcd0
* Version Independent ID: 670486a9-a969-3761-8ef2-d34049e24aab
* Content: [PasswordVault.Add(PasswordCredential) Method (Windows.Security.Credentials) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.security.credentials.passwordvault.add?view=winrt-22621#windows-security-credentials-passwordvault-add(windows-security-credentials-passwordcredential))
* Content Source: [winrt-api-build/xml/Windows.Security.Credentials/PasswordVault.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Security.Credentials/PasswordVault.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @ackh. Thanks for reaching out about this API. I found an old document with some information about PasswordVault, but it didn't indicate what the upper limit was for adding entries. I've reached out to someone in engineering, and I'm hoping they can help determine if there is (or ever was) a limit. I'll let you know when I find out anything.

**Comment by alvinashcraft** [comment]
Hello again, @ackh. I got a response from the team, and the limit in the docs only applies to apps running in an app container (UWP apps). If you call it from a desktop app like you are, the limit will not apply. I'll be adding a note to the docs about it. For now, I'm going to close this issue, but I'll circle back to let you know when the PR with this change has been merged.

**Comment by alvinashcraft** [comment]
The PR to add a note was just merged and should be live later today.

**Comment by ackh** [comment]
@alvinashcraft Great, that explains the behavior I'm seeing. Thanks for your quick response and for the update of the documentation!
