### ISSUE TITLE
richeditmathml@microsoft.com not reachable

### ISSUE THREAD

**Issue by HuHe86** [MicrosoftDocs/winrt-api#2340]
richeditmathml@microsoft.com is not reachable from outside @microsoft.com.

**Comment by GrantMeStrength** [comment]
hi!

I tested this email address, and yes, there is an error message about it not being delivered. However, the mail does get through. 

The team is now aware and will hopefully stop the error. if you haven't heard back, it would be worth re-sending your email.

thank you!
