### ISSUE TITLE
FileTypeChoices example

### ISSUE THREAD

**Issue by jtallsmith** [MicrosoftDocs/winrt-api#2341]
//Need to set the first type to the required file type
            //to get the correct file extension.

            if (radioButtonWav.IsChecked == true)
            {
                picker.FileTypeChoices.Add("wav", new List<string>() { ".wav" });
                picker.FileTypeChoices.Add("mp3", new List<string>() { ".mp3" });
                picker.FileTypeChoices.Add("flac", new List<string>() { ".flac" });
            }
            else if (radioButtonFlac.IsChecked == true)
            {
                picker.FileTypeChoices.Add("flac", new List<string>() { ".flac" });
                picker.FileTypeChoices.Add("wav", new List<string>() { ".wav" });
                picker.FileTypeChoices.Add("mp3", new List<string>() { ".mp3" });
            }
            else if (radioButtonMP3.IsChecked == true)
            {
                picker.FileTypeChoices.Add("mp3", new List<string>() { ".mp3" });
                picker.FileTypeChoices.Add("flac", new List<string>() { ".flac" });
                picker.FileTypeChoices.Add("wav", new List<string>() { ".wav" });
            }
            else
            {
                picker.FileTypeChoices.Add("wav", new List<string>() { ".wav" });
                picker.FileTypeChoices.Add("mp3", new List<string>() { ".mp3" });
                picker.FileTypeChoices.Add("flac", new List<string>() { ".flac" });
            }

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bb9699c6-355f-aee4-dff3-f621c0014ed9
* Version Independent ID: bbbdebf2-1840-de44-5eed-6f0b8afe4768
* Content: [FileSavePicker.DefaultFileExtension Property (Windows.Storage.Pickers) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.filesavepicker.defaultfileextension?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers/FileSavePicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers/FileSavePicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to resolve this doc issue by expanding the example when it comes to multiple file types. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!

**Comment by alvinashcraft** [comment]
The changes are now [live](https://learn.microsoft.com/uwp/api/windows.storage.pickers.filesavepicker.filetypechoices). There's an additional sample, similar to the one you provided above.
