### ISSUE TITLE
Sample referring to the wrong name in the XAML code.

### ISSUE THREAD

**Issue by dvroegop** [MicrosoftDocs/winrt-api#2344]
The first sample creates an InkCanvas named MyInkcanvas in the XAML, yet in de code behind it is referred to as "inkCanvas".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 943aa0a4-0430-314c-9598-f33d22d5defa
* Version Independent ID: bc9d39ff-709e-23b8-98c7-91f2d15b0d2d
* Content: [InkPresenter Class (Windows.UI.Input.Inking) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.input.inking.inkpresenter?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Input.Inking/InkPresenter.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Input.Inking/InkPresenter.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks. A fix has been pushed and should be live soon.
