### ISSUE TITLE
Documentation has bad type link and is inconsistent in documentation

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/winrt-api#2345]
While reviewing this document I found some issues with the documentation I believe.

- Under `Exceptions` the link to `CommonFileQuery` is the doctag `xref` instead of an actual link.
- Under `Exceptions` it says that the exception occurs if you specify a value other than `DefaultQuery` for a folder that is not a library folder. By my understanding then library folders must use `DefaultQuery`. But the example that follows it uses `PicturesLibrary` and `OrderByDate` which would seem to go against what the documentation says since, I believe, `PicturesLibrary` is a library.
- Under `Remarks` the bullet list talks about shallow query but it reads like either there is stuff missing between the bullet points or the `or-` stuff shouldn't be in bullets. It just reads and looks really confusing.
- Under `Remarks` it talks about a shallow query occurring in the following cases and one of the cases is using a value other than `DefaultQuery` on a library folder. But the earlier exception documentation says that an exception will occur.
- Under `Remarks \ Tip` it clarifies that only some `CommonFileQuery` options are allowed with library folders. But then it says besides `DefaultQuery` you can use `OrderByName` and `OrderBySearchRank`. But that also goes against what the exception documentation said earlier. Furthermore the example that follows the exception documentation is using `OrderByDate` which isn't in this list either.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d3c973b-4f55-24ed-6570-25928d05a0ec
* Version Independent ID: ee06cd98-dde0-5ff1-6980-7e8cc53d4855
* Content: [StorageFolder.CreateFileQueryWithOptions(QueryOptions) Method (Windows.Storage) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.createfilequerywithoptions?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFolder.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFolder.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @CoolDadTx. Thanks for the detailed feedback. I'm creating an internal work item to incorporate this into the docs for this API. It looks like it hasn't been updated in a couple of years. I'm closing this issue now, but I will follow up when the changes have been merged. Treat it like an open issue with any additional feedback about this page. Cheers!

**Comment by alvinashcraft** [comment]
I just published some updates to this page. Let me know if this helps clarify the information. I didn't change the wording of the exception because that's how it's actually worded. Instead, I added some clarification to the 'Tip' in the Remarks section.

**Comment by CoolDadTx** [comment]
@alvinashcraft The documentation looks better now, thank you.
