### ISSUE TITLE
Under what circumstances can this call throw an exception?

### ISSUE THREAD

**Issue by mc0re** [MicrosoftDocs/winrt-api#2348]
I've got the following crash information:
```
System.Exception: Element not found. (Exception from HRESULT: 0x80070490)
```

Call stack ends with:
```
System.Runtime.InteropServices
McgMarshal.ThrowOnExternalCallFailed (Int32, RuntimeTypeHandle)
__Interop
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32, Int32, Void*)
Windows.Media.Devices.IMediaDeviceStatics__Impl
Stubs.GetDefaultAudioRenderId (__ComObject, AudioDeviceRole)
```

The call in question looks as following:
```csharp
var defaultId = MediaDevice.GetDefaultAudioRenderId(AudioDeviceRole.Default);
```

The function documentation is missing a description of this exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 621d13d5-dcde-43aa-5b04-7d2d73b24a4f
* Version Independent ID: b267aeaf-4a28-53f1-d335-22ae3a4b8348
* Content: [MediaDevice.GetDefaultAudioRenderId(AudioDeviceRole) Method (Windows.Media.Devices) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.media.devices.mediadevice.getdefaultaudiorenderid?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Media.Devices/MediaDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Media.Devices/MediaDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
@mc0re - Hello, I reached out to the feature team and they state that this API should not throw an exception under normal operating conditions. Even if there is no endpoint, the API should return an empty string and not return an error. So, it sounds like there may be something going on with your particular environment that is causing this to throw. Unfortunately, git issues in this repo are specifically for documentation issues and we are not able to provide direct developer support here. I recommend that you open an issue on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) site.
