### ISSUE TITLE
NavigationFailed Documentation missing

### ISSUE THREAD

**Issue by DesertYew** [MicrosoftDocs/winrt-api#2353]
NavigationFailed only documents use in Web app, but it appears in other app types as well in the App.g.i.cs file. No help in creating a handler in a windows app.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3aa9ec9-c364-ce77-8839-d4750b763394
* Version Independent ID: 0808dffa-b9ee-22ae-a7b0-4717e8e34c06
* Content: [WebView.NavigationFailed Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.navigationfailed?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NavigationFailed)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/WebView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/WebView.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
`WebView.NavigationFailed` was deprecated in Windows 8.1. [NavigationCompleted](https://learn.microsoft.com/uwp/api/windows.ui.xaml.controls.webview.navigationcompleted) should be used instead.
