### ISSUE TITLE
Vfs global 

### ISSUE THREAD

**Issue by Govher8711** [MicrosoftDocs/winrt-api#2356]
Vfs global polonya randevu 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a8fa547-bb89-eb9c-1706-6e1395394883
* Version Independent ID: 7bcb8915-df97-9dc8-18ac-a6887fde761c
* Content: [ApiInformation.IsTypePresent(String) Method (Windows.Foundation.Metadata) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.metadata.apiinformation.istypepresent?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Metadata/ApiInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Metadata/ApiInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
It looks like there's no actionable feedback here, so I'll go ahead and close the issue. Please open a new issue if you have feedback about the documentation that you'd like us to address.
