### ISSUE TITLE
Bad example reference for Data/HeaderTemplateSelector

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#2365]
In this paragraph:

> For example XAML that references a custom DataTemplateSelector as the [HeaderTemplateSelector](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.groupstyle.headertemplateselector?view=winrt-22621#windows-ui-xaml-controls-groupstyle-headertemplateselector) value, and example code that shows the overrides for [HeaderTemplateSelector](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.groupstyle.headertemplateselector?view=winrt-22621#windows-ui-xaml-controls-groupstyle-headertemplateselector) methods, see [How to group items in a list or grid](https://learn.microsoft.com/en-us/previous-versions/windows/apps/hh780627(v=win.10)).

The referenced sample code doesn't actually have example of Data/HeaderTemplateSelector.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86cbc84f-1578-5874-584f-c70bc5a12db2
* Version Independent ID: a4782a0f-fe7d-dcec-7ac6-ecd9d0d8359d
* Content: [DataTemplateSelector Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.datatemplateselector?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/DataTemplateSelector.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/DataTemplateSelector.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. This documentation has been updated.
