### ISSUE TITLE
Rename this page to Windows Runtime namespaces

### ISSUE THREAD

**Issue by jaigak** [MicrosoftDocs/winrt-api#2367]
While some namespaces are specifically for UWP apps, most namespaces and APIs are for all Windows apps using the Windows Runtime.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc5c129-5729-4529-90da-919c8ad43916
* Version Independent ID: ae5b67ee-cb90-c54a-1a96-e3a6a7e74da6
* Content: [Windows UWP Namespaces - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/?redirectedfrom=MSDN)
* Content Source: [winrt-api-build/index.md](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/index.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Done! Thank you.
