### ISSUE TITLE
Clarify BitmapPlaneDescription.StartIndex

### ISSUE THREAD

**Issue by robunoki-microsoft** [MicrosoftDocs/winrt-api#2369]
The description of BitmapPlaneDescription.StartIndex should be clarified to indicate that it is a byte offset in the buffer for the start pixel.  Saying it is the "index of the start pixel" is ambiguous since it doesn't specify the units of the index.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f60c4a87-8c43-068a-58ee-870fcdef12b9
* Version Independent ID: dd2e720f-d60e-47f6-2918-79864577f002
* Content: [BitmapPlaneDescription Struct (Windows.Graphics.Imaging) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.imaging.bitmapplanedescription?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Imaging/BitmapPlaneDescription.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Imaging/BitmapPlaneDescription.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for identifying this issue. I've updated the description to "The byte offset to the start of the pixel data within the plane."

**Comment by robunoki-microsoft** [comment]
Thank you Drew :)
