### ISSUE TITLE
What is an "immersive environment"

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/winrt-api#2374]
"immersive environment" could mean lots of things.
Can this be made clearer? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd4a6b76-b5ac-d343-f20b-1841380fbc99
* Version Independent ID: 59b6019f-3cf0-6fb7-fc46-f714bb877a6c
* Content: [DisplayInformation.ResolutionScale Property (Windows.Graphics.Display) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.resolutionscale?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Graphics.Display/DisplayInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Graphics.Display/DisplayInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks! I'm investigating.

-Steve

**Comment by stevewhims** [comment]
UPDATE: I'm changing the term to "app window".

'Immersive environment" is now out of date. It refers to Windows 8 where "immersive" apps ran in a different environment from the desktop. The immersive environment and the desktop environment each had their own scale factor.

-Steve
