### ISSUE TITLE
samples don't show the desired visual effect

### ISSUE THREAD

**Issue by stevenbrix** [MicrosoftDocs/winrt-api#2377]
the sample code looks interesting, but we have no idea what the end-result is

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39f83ef6-e41e-61cb-f21b-5ee194e28acd
* Version Independent ID: edbf1ca6-620b-6072-9c0a-44912471e85b
* Content: [LayerVisual Class (Windows.UI.Composition) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.composition.layervisual?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Composition/LayerVisual.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Composition/LayerVisual.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. This documentation has been updated.
