### ISSUE TITLE
How to edit JS code examples?

### ISSUE THREAD

**Issue by arturmiz** [MicrosoftDocs/winrt-api#238]
I came across [SystemNavigationManager](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.systemnavigationmanager) doc page and tried to use JS example presented there, however, it turned out that it has a flaw in event naming convention. 

The example says it's `backRequested` but it doesn't work because all events names in WinRT JS API are lowercased so I tried with `backrequested` and it works.

I wanted to edit the doc page but I noticed that its [file](https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.core/systemnavigationmanager_backrequested.md/) doesn't contain code samples. Is it possible to fix it or they are somehow magically generated from the C# API?

**Comment by ginami** [comment]
Thank you @arturmiz for your feedback. @jwmsft, can you address this question?

Thank you!

**Comment by jwmsft** [comment]
These are auto generated, and JS is no longer shown in the docs.
