### ISSUE TITLE
More clarity on file extensions would be helpful

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/winrt-api#2380]
I was running into a typically useless and obscure Microsoft exception -- "The parameter is incorrect" (really? how nice of you to notice, and how stupid of you to not give any hint as to >>which<< parameter is incorrect) -- because I was specifying file type extensions without the leading "."

Please either make it clear that leading period is required. Or, better yet, have the people maintaining the code base update the exception message to actually be >>helpful<<. Or, best of all, have them check for the leading period and, if it's missing, add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28945089-32b1-c441-1d5a-166421ad1e4d
* Version Independent ID: 74739713-33de-0a45-b47a-a60b30a0d24c
* Content: [FileOpenPicker.FileTypeFilter Property (Windows.Storage.Pickers) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.filetypefilter?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers/FileOpenPicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers/FileOpenPicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi. Thank you for your feedback. I've added some additional information to the parameter description to clarify that the dot is required when adding a file extension. If you would like to send feedback to the product team about making the exception more helpful, you can click the "This product" button at the bottom of the documentation page where is says "Submit and view feedback for". The docs changes should be merged and live later today.
