### ISSUE TITLE
No c# examples for GetTextAsync()?

### ISSUE THREAD

**Issue by tuggernuts** [MicrosoftDocs/winrt-api#2381]
Even when c# is selected as the language, the examples for GetTextAsync() are in javascript.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21019a72-7fb7-fb88-1436-350ea5d6d40f
* Version Independent ID: 30315c92-b801-9328-342f-ddacecec42f1
* Content: [DataPackageView.GetTextAsync Method (Windows.ApplicationModel.DataTransfer) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackageview.gettextasync?view=winrt-22621#windows-applicationmodel-datatransfer-datapackageview-gettextasync)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/DataPackageView.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/DataPackageView.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for submitting this issue. It looks like the JS example was accidentally duplicated instead of having both C# and JS. So, I replaced the first JS block with a C# example. The changes should be merged and live later today.
