### ISSUE TITLE
Why and where SetDisplayStatus() persist the status I set?

### ISSUE THREAD

**Issue by TishSerg** [MicrosoftDocs/winrt-api#2382]
This page doesn't contain any info about status string persistence (between application restart).

---
#### Відомості про документ

⚠ *Не змінюйте цей розділ. Він необхідний, щоб пов’язувати сторінки learn.microsoft.com і проблеми на GitHub.*

* ID: 6441d45e-89dd-c9a3-8f02-6788e65883eb
* Version Independent ID: bf2d2605-9965-17a2-0423-1d5e96e7dc84
* Content: [DevicePicker.SetDisplayStatus Method (Windows.Devices.Enumeration) - Windows UWP applications](https://learn.microsoft.com/uk-ua/uwp/api/windows.devices.enumeration.devicepicker.setdisplaystatus?view=winrt-19041)
* Content Source: [winrt-api-build/xml/Windows.Devices.Enumeration/DevicePicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Enumeration/DevicePicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @TishSerg. I'm investigating.

-Steve

**Comment by stevewhims** [comment]
Sorry for the delay. I've added this info to the topic: "The state of the picker UI typically persists until the operating system (OS) is restarted."

Thanks!
-Steve
