### ISSUE TITLE
Setting MinZoomFactor to value lower than 0.1 throws

### ISSUE THREAD

**Issue by HunterB06** [MicrosoftDocs/winrt-api#2384]
Hello,

The minimum zoom factor that can be set in ScrollViewer can't be lower than 0.1, otherwise it will throw an exception.
However, this behaviour is not documented whereas it should.

Please state on the documentation page that the MinZoomFactor must be greater or equal to 0.1. And what would be the reason for that minimal value?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 805d5762-63dd-1355-2b79-ff3d4883aa2c
* Version Independent ID: bb6cc8da-cb2f-c3f2-b59d-735f8cca762f
* Content: [ScrollViewer.MinZoomFactor Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer.minzoomfactor?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/ScrollViewer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/ScrollViewer.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for raising this issue. The documentation has been updated.
