### ISSUE TITLE
DispatcherQueueTimer IsRepeating does not list default value

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#2386]
The default value should be called out here in the docs, it is not.

It's also not called out on the WASDK/WinUI 3 version of this API either: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.dispatching.dispatcherqueuetimer.isrepeating

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bea8359b-295c-ab6e-b82c-d8076e7e64b4
* Version Independent ID: 870f066d-9286-37ae-620c-d9f2f46c9421
* Content: [DispatcherQueueTimer.IsRepeating Property (Windows.System) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueuetimer.isrepeating?view=winrt-22621#windows-system-dispatcherqueuetimer-isrepeating)
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueueTimer.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
When I test the property in an app, it defaults to `true` for UWP and WASDK projects. I'll update the docs for this page. @jwmsft owns the WASDK page. I'll see if he wants to make that update. Otherwise, I'll create a PR there too. Thanks for the heads-up, @michael-hawker.

**Comment by alvinashcraft** [comment]
The default value has been documented in the UWP/WinRT topic, and the changes should be merged to the live site soon. The same change is also going to be made to the WASDK topic.

Thanks again for submitting this issue!
