### ISSUE TITLE
Buffer size of StorageLibraryChangeTracker is too small

### ISSUE THREAD

**Issue by strong-nguyen** [MicrosoftDocs/winrt-api#2387]
I am using StorageLibraryChangeTracker to track a folder in the background. Basically, it works fine.
However, when I made many changes to that folders, say copy a folder with 1000 files to the tracking folder, the API say that track is lost because buffer is full.

Could you support an API to set the buffer size or have option to not limit it ?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38f48339-e839-2d61-d16a-7344253ed698
* Version Independent ID: bb09d843-ffa6-cf74-026a-4c7f3f3c53a0
* Content: [StorageLibraryChangeTracker Class (Windows.Storage) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.storagelibrarychangetracker?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageLibraryChangeTracker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageLibraryChangeTracker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
