### ISSUE TITLE
Wrong Build mentioned

### ISSUE THREAD

**Issue by helgefylla** [MicrosoftDocs/winrt-api#2390]
14383 should be replaced with 14393, right ?

![Screenshot_20230721_130437_Chrome](https://github.com/MicrosoftDocs/winrt-api/assets/52319441/66ce2a5d-e208-477f-8db9-4c8a01ba0f57)

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen learn.microsoft.com ➟ GitHub-problem.*

* ID: 14f17975-a2c0-1efc-926d-9b23d934fa40
* Version Independent ID: 9fa8f7cc-ec55-0a6b-983a-be708047d31e
* Content: [ApiInformation Class (Windows.Foundation.Metadata) - Windows UWP applications](https://learn.microsoft.com/nb-no/uwp/api/windows.foundation.metadata.apiinformation?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Foundation.Metadata/ApiInformation.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Foundation.Metadata/ApiInformation.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for reaching out about the documentation experience. The docs platform is open source, and we partner with many teams to publish content. The build numbers listed in the article are generated by the content build system. I will notify the appropriate engineering team, but this is not something that we can change in the documentation source. Thanks for your feedback, and I will follow up here if I hear anything relevant about this issue.
