### ISSUE TITLE
PhoneLineTransportDevice.RegisterAPP Registration failed

### ISSUE THREAD

**Issue by engineerLuffy** [MicrosoftDocs/winrt-api#2393]
[在此处输入反馈]

When I call this function in the WinUI framework, I can successfully register, but when I call this function in the WPF framework, it fails.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7b9fbd15-8b10-6aa7-59d7-eeac19ee7754
* Version Independent ID: e437eb05-285f-8085-03bb-716333285425
* Content: [PhoneLineTransportDevice.RegisterApp 方法 (Windows.ApplicationModel.Calls) - Windows UWP applications](https://learn.microsoft.com/zh-cn/uwp/api/windows.applicationmodel.calls.phonelinetransportdevice.registerapp?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.Calls/PhoneLineTransportDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.Calls/PhoneLineTransportDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @engineerLuffy. Is your WPF app packaged with MSIX? Many of the WinRT APIs require package identity to function properly.

We sincerely apologize for the delayed response. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding the WinRT APIs. They can guide you to ensure that your application is configured to consume WinRT APIs that require package identity. We also have some documentation about modernizing WPF apps, packaging them, and how package identity works with desktop apps. You can start with this packaging topic: https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
