### ISSUE TITLE
Can't find the source code for WebAuthenticationCoreManager

### ISSUE THREAD

**Issue by artemiusgreat** [MicrosoftDocs/winrt-api#2396]
I need to replicate functionality using `WebAuthenticationCoreManager` but for the web app, specifically, ASP MVC. 
Unfortunately, this class is available only for native apps, like Xamarin or UWP. 
Could somebody point me to the implementation of this class?

**Comment by alvinashcraft** [comment]
Hi @artemiusgreat. The scope of this feedback channel covers specific documentation fixes, but I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding the WinRT API documentation. Unfortunately, the WinRT APIs are not open source, so you would be able to access the source code for this class, but the folks in the Q&A forums may have some other suggestions for you.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
