### ISSUE TITLE
Devlang primitive type translation

### ISSUE THREAD

**Issue by mattwojo** [MicrosoftDocs/winrt-api#24]
Primitive types differ by devlang. Our docs need to reflect the differences.

C++
https://msdn.microsoft.com/en-us/library/windows/apps/hh710417.aspx

https://msdn.microsoft.com/en-us/library/windows/apps/hh699871.aspx

VB.Net
http://www.dotnetheaven.com/article/data-types-in-vb.net1

(Task 11010772)

**Comment by kevinyr** [comment]
We are working on resolving this issue.

**Comment by kevinyr** [comment]
Work still in progress.

**Comment by kevinyr** [comment]
This issue has been resolved.
