### ISSUE TITLE
GattDeviceService shows both 'Dispose' and 'Close' being availble functions

### ISSUE THREAD

**Issue by dunhor** [MicrosoftDocs/winrt-api#2401]
From what I can gather, the `GattDeviceService` type implements the `IClosable` interface, which is where the `Close` function comes from. In .NET this is projected as `IDisposable`, which is where the `Dispose` function comes from. The issue:
* The documentation shows _both_ functions regardless of which language is selected. I.e. it'll show `Close` even if the language is selected as C# and it will show `Dispose` even if the language is selected as C++/WinRT. There's also no flavor text to indicate that they are the same function and which one is available in which language(s)
* The description for both functions is different, despite being the same function

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e9f95f6-e225-7604-ee10-36f317c6a627
* Version Independent ID: f7627757-567f-c5dd-3693-c3d6cfd4d8c5
* Content: [GattDeviceService Class (Windows.Devices.Bluetooth.GenericAttributeProfile) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattdeviceservice?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattDeviceService.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.Bluetooth.GenericAttributeProfile/GattDeviceService.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @dunhor, and sorry for my delay in responding.

> The documentation shows both functions regardless of which language is selected.

The language picker affects only the topic on which it's being used. The language picker doesn't ever affect what's listed in the table-of-contents tree on the left hand side. On the Close topic, I can choose from 5 different languages to see what the declaration syntax is for Close for the selected language. That's the only thing that picker does. On the Dispose topic, I can choose from 3 different languages. Again, the only thing that choice affects is the syntax block.

> There's also no flavor text to indicate that they are the same function

To the best of my understanding, they're not the same method (although behind the scenes one might call the other). See [Should I implement Windows::Foundation::IClosable and, if so, how?](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/faq#should-i-implement-windows--foundation--iclosable-and--if-so--how-) and [Do I need to call IClosable::Close on runtime classes that I consume?](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/faq#do-i-need-to-call-iclosable--close-on-runtime-classes-that-i-consume-).

> and which one is available in which language(s)

The languages that are listed in the language picker indicate that.

> The description for both functions is different, despite being the same function

See above, about them not being the same method.

Thanks!
-Steve

**Comment by dunhor** [comment]
@stevewhims I'm not sure I follow. `Windows.Foundation.IClosable` is projected in .NET as `IDisposable`. They ARE the same thing from the perspective of WinRT. The implementation of `GattDeviceService` DOES NOT implement `IDisposable`, as that is not a WinRT type. When you call `Dispose` on a `GattDeviceService` object in a language like C#, this will call the `IClosable::Close` function. The language projection (such as C#/WinRT) does this behind the scenes.

**Comment by dunhor** [comment]
See the notes in the documentation for the `IClosable` interface: https://learn.microsoft.com/en-us/uwp/api/windows.foundation.iclosable?view=winrt-22621

> .NET This interface appears as [System.IDisposable](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable?view=dotnet-uwp-10.0&preserve-view=true).

**Comment by dunhor** [comment]
> The language picker doesn't ever affect what's listed in the table-of-contents tree on the left hand side

I think that's a mistake as it's easy to get confused, but at the very minimum, the description should contain a note. Something along the lines of `"This method is only available in .NET and C++/CX"` for the `Dispose` function and `"This method is not available in .NET and C++/CX"` for the `Close` function. Additionally, the descriptions _should_ be the same because they _are_ the same. Calling `Dispose` in C# _will_ call the `Close` function on the object.

**Comment by stevewhims** [comment]
I see: I thought that for a type that needs to release unmanaged resources, it was pretty vital to call Dispose when using an instance of that type in C# (otherwise you'd leak). Whereas when using that same type in C++/WinRT, you know that the destructor will take care of releasing those resources when the instance goes out of scope (which, with modern C++, would happen at a predictable place in the code). And that the destructor will call Close for you. "In general, you don't need to call IClosable::Close from C++/WinRT". Whereas you always need to call Dispose from C#. However, you *can* opt to call Close from C++/WinRT if you want to release those resources early.

In any case, whether they're the same or different methods, when I visit the Dispose topic I don't see C++/WinRT in the language picker. So that tells me I can't use Dispose from that language (which is correct). When I visit the Close topic, and I pick C# from the language picker, then the syntax block says "This member is not implemented in C#". And that's correct, too.

As for the descriptions, let me make enquiries, and see whether I can establish that the two methods really are doing exactly the same thing. :)

-Steve

**Comment by dunhor** [comment]
FWIW if you [search for IClosable in the CsWinRT repo](https://github.com/search?q=repo%3Amicrosoft%2FCsWinRT+IClosable&type=code) you can see a number of places where this mapping of types is going on.

**Comment by stevewhims** [comment]
Sorry for the delay, So, yes, I was wrong: the two methods (Close and Dispose) are indeed one and the same. As you say, IClosable is simply projected into .NET languages as IDispose. This was the last detail left unresolved in this thread.

I've updated this class's Close method with a little more info that might help readers. The GattDeviceService.Dispose topic seems to be picking up a generic description of Dispose from the .NET docs. I think it's ok for that description to remain generic. We have info in the C++ and WinRT docs about calling Close; and info in the .NET docs about calling Dispose. So the fact that they're the same implementation shouldn't affect the above practices.

I'll go ahead and close.
