### ISSUE TITLE
Bug in LockScreen.SetImageFileAsync(IStorageFile) Method when using Desktop Bridge

### ISSUE THREAD

**Issue by Skorpjun161** [MicrosoftDocs/winrt-api#2402]
There is a bug in the desktop bridge that causes the SetImageFileAsync method not to work. It only seems to works on X64 architectures (where both the app and the system are X64).
See:
https://github.com/MicrosoftDocs/winrt-api/issues/2148
https://stackoverflow.com/questions/56935486/cached-image-not-being-updated-with-lockscreen-setimagefileasyncfile

This bug is still not fixed after YEARS! Unbelievable.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68bece6b-32da-533b-6963-b9d92ebf34c2
* Version Independent ID: 987d9f45-d64c-4d8d-2b84-8ea7bac608d6
* Content: [LockScreen.SetImageFileAsync(IStorageFile) Method (Windows.System.UserProfile) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.system.userprofile.lockscreen.setimagefileasync?view=winrt-22000)
* Content Source: [winrt-api-build/xml/Windows.System.UserProfile/LockScreen.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System.UserProfile/LockScreen.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Have you reported this bug over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html)? That's the best place to raise concerns about bugs like this in the APIs.

If you do create (or have already created) a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. I'd like to call out the issue in the documentation if there is an official response provided about the problem. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. I'll be continuing to monitor it. Thanks!
