### ISSUE TITLE
Examples in the C++ docs are for C#

### ISSUE THREAD

**Issue by minfrin** [MicrosoftDocs/winrt-api#2406]
In the C++ docs, the examples are for C#.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c8db3fc6-e90c-175b-fe68-e7ac8fa314ca
* Version Independent ID: dca31f22-5a40-3de0-2845-3b6afbd8af84
* Content: [DispatcherQueue.TryEnqueue Method (Windows.System) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.system.dispatcherqueue.tryenqueue?view=winrt-22621#windows-system-dispatcherqueue-tryenqueue(windows-system-dispatcherqueuehandler))
* Content Source: [winrt-api-build/xml/Windows.System/DispatcherQueue.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.System/DispatcherQueue.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by stevewhims** [comment]
Thanks, @minfrin. The language drop-down on API reference topics controls only the language used in the syntax block. And in this case it's functioning correctly. That picker isn't meant to pick between languages for Examples sections. Most topics have only C# code examples, and this is one of them.

To determine the C++ equivalent code in this case, you could have a look at the [C++/WinRT docs](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/), especially [Move to C++/WinRT from C#](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp).

Thanks!
-Steve
