### ISSUE TITLE
Missing premultiplied info regarding pixel image format for the retrieved rendered RenderTargetBitmap image

### ISSUE THREAD

**Issue by acouvert-msft** [MicrosoftDocs/winrt-api#2409]
The documentation mentioned that the pixel image format for the retrieved rendered `RenderTargetBitmap `image is `BGRA8` format, without specifying that it's an alpha `premultiplied` pixel format.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5302d8d-2aa2-099c-65db-de71a5ae3d79
* Version Independent ID: fc7e3eba-01c7-7c6b-6825-31d0aab64cf2
* Content: [RenderTargetBitmap.GetPixelsAsync Method (Windows.UI.Xaml.Media.Imaging) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.rendertargetbitmap.getpixelsasync?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Media.Imaging/RenderTargetBitmap.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Media.Imaging/RenderTargetBitmap.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for the feedback. This documentation has been updated.
