### ISSUE TITLE
Is this still a PUBLIC API? I couldn't find any code examples for it.

### ISSUE THREAD

**Issue by ruchibatra-microsoft** [MicrosoftDocs/winrt-api#2411]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe26737-0637-fb38-9f6b-5a52a41d6ba9
* Version Independent ID: 4af8788f-bdfe-5a0b-d82a-c8c6adc9789c
* Content: [Windows.Security.Authentication.Identity.Core Namespace - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.security.authentication.identity.core?view=winrt-22621)
* Content Source: [winrt-api-build/xml/ns-Windows.Security.Authentication.Identity.Core.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/ns-Windows.Security.Authentication.Identity.Core.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hello. Thanks for your question. These are still active APIs in the SDK, but they are all documented as `This API is for internal use only and should not be used in your code.`, so you should not try to use them.
