### ISSUE TITLE
How to apply the function in javascript ???

### ISSUE THREAD

**Issue by AlmTalal** [MicrosoftDocs/winrt-api#2413]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b710f75e-23bc-f89c-216f-c923cebc6438
* Version Independent ID: 9fe7ad36-4f1a-0944-5bfe-c4c7aae74c41
* Content: [SerialDevice.Close Method (Windows.Devices.SerialCommunication) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.devices.serialcommunication.serialdevice.close?view=winrt-22621#windows-devices-serialcommunication-serialdevice-close)
* Content Source: [winrt-api-build/xml/Windows.Devices.SerialCommunication/SerialDevice.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Devices.SerialCommunication/SerialDevice.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
You can choose "JavaScript" from the language picker in the upper-right of the webpage to see the syntax for the function (at least). I believe the syntax would be `myObject.close();`, but JavaScript (for UWP apps) isn't a language that the docs invest in as highly these days as they once did.

-Steve

**Comment by AlmTalal** [comment]
I think that I just found it, you have to use Foundation namespace to be
able to use it. I’m new in UWP app, but I have a project with react native
for windows and one of the principal features uses WinRT APIs
