### ISSUE TITLE
Incorrect exception links on StorageFile.GetFileFromPath page

### ISSUE THREAD

**Issue by Psychlist1972** [MicrosoftDocs/winrt-api#2414]
Under "Exceptions" the page links to .net exceptions, not to winrt exceptions. 

I'm using C++/WinRT in my case.

Many other pages in this section don't describe which exceptions they throw, which seems incorrect.

The CopyASync page has the same problem of pointing to .net exceptions.

There are also issues on some pages for StorageFile under the "Implements" sections. For example, see RenameAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1a0b142-3819-3929-bc93-c4d8e0598978
* Version Independent ID: 932a8fe2-dc4e-ade9-e67d-45897840c037
* Content: [StorageFile.GetFileFromPathAsync(String) Method (Windows.Storage) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefrompathasync?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage/StorageFile.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage/StorageFile.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hey @Psychlist1972. Thanks for the heads up about this. I'm trying to track down someone on the product team who can help me get the right info for C++ and .NET exceptions in these APIs.

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I went ahead and created an internal work item to incorporate your suggestions. I sent you an email with the internal info.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
