### ISSUE TITLE
var stream = await localPackage.SaveAsync() while using this api i am getting "Catastrophic failure" exception with the HRESULT 0x8000FFFF exception how to fix this?

### ISSUE THREAD

**Issue by vikashintech** [MicrosoftDocs/winrt-api#2418]

**Comment by vikashintech** [comment]
var stream = await localPackage.SaveAsync() while using this api i am getting "Catastrophic failure" exception with the HRESULT 0x8000FFFF exception how to fix this?

**Comment by GrantMeStrength** [comment]
Hi - unfortunately this is not a documentation issue as far as I can tell.
Please consider asking this question on the Microsoft Q&A Forums: https://learn.microsoft.com/en-us/answers/questions/
