### ISSUE TITLE
Link to theme keys is broken

### ISSUE THREAD

**Issue by Inrego** [MicrosoftDocs/winrt-api#2426]
The link to `AutoSuggestBox_themeresources.xaml` is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b41db05-99ab-089d-9ad5-80f0cbaa7e91
* Version Independent ID: 260bdcdc-1752-f856-c1a4-915b6f383117
* Content: [AutoSuggestBox Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.autosuggestbox?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml.Controls/AutoSuggestBox.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml.Controls/AutoSuggestBox.xml)
* Product: **uwp**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Thanks for reporting this issue. The content has been updated.
