### ISSUE TITLE
remarks are incorrect

### ISSUE THREAD

**Issue by stevenbrix** [MicrosoftDocs/winrt-api#2441]
Remarks say this is equivalent to the `AutomaticBackgroundTask` which can't be right

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac743372-2335-68b9-b56f-9deecf1e9dd7
* Version Independent ID: 6c53da0d-d665-0a63-0e20-8397332c92bc
* Content: [AppInstallerInfo.DependencyPackageUris Property (Windows.ApplicationModel) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.appinstallerinfo.dependencypackageuris?view=winrt-22621#windows-applicationmodel-appinstallerinfo-dependencypackageuris)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel/AppInstallerInfo.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel/AppInstallerInfo.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for pointing this out. I updated the page to point to the Dependencies schema element. The change should be live later today.
