### ISSUE TITLE
ClearHistory - incomplete

### ISSUE THREAD

**Issue by HarmlessDave** [MicrosoftDocs/winrt-api#2443]
Remarks addition needed: ClearHistory does not clear pinned items from the history.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09a0ddeb-467c-4516-133c-bd0c710408f7
* Version Independent ID: 234d1ef0-7a9a-be22-6572-51faf742031e
* Content: [Clipboard.ClearHistory Method (Windows.ApplicationModel.DataTransfer) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.clipboard.clearhistory?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.ApplicationModel.DataTransfer/Clipboard.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thank you for the suggestion. I have incorporated it into the remarks section for this page. The changes should be live later today. Cheers!
