### ISSUE TITLE
Does FileOpenPicker.PickMultipleFilesAsync still throw an exception when the app is snapped?

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/winrt-api#2444]
On Windows 11 (10.0.22621.3007) I can snap my app's window and FileOpenPicker.PickMultipleFilesAsync works as expected with no exception being thrown.  So the warning in this doc doesn't seem to apply.  Maybe call out which version of Windows fixed this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdb35675-9c35-60f3-c377-3c8e016d39f6
* Version Independent ID: 08fc1da1-8e26-e3dc-6ba6-886619d56155
* Content: [FileOpenPicker.PickMultipleFilesAsync Method (Windows.Storage.Pickers) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.pickmultiplefilesasync?view=winrt-22621&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.Pickers.FileOpenPicker.PickMultipleFilesAsync)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.7.1)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [winrt-api-build/xml/Windows.Storage.Pickers/FileOpenPicker.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.Pickers/FileOpenPicker.xml)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by jaigak** [comment]
I presume this only applies to Windows 8, where the file picker shows up as a full-screen popup over a Metro-style app's window.

**Comment by KevinKennedy** [comment]
Makes sense.  I've long forgotten about that 🙂

**Comment by alvinashcraft** [comment]
Thanks for the PR to clarify the message, @JaiganeshKumaran. The change has been merged and should be reflected in the live docs soon.
