### ISSUE TITLE
"ConstrainedInternetAccess" is confusing.

### ISSUE THREAD

**Issue by JeffMill** [MicrosoftDocs/winrt-api#2448]
"ConstrainedInternetAccess	2	Limited internet access. This value indicates captive portal connectivity,"

However, the same page reads: “This doesn't guarantee detection of a captive portal. ”

This should be clarified, e.g. "It’s an indication that the connection *might* be constrained due to a captive portal, but that isn't the only reason.  It might be due to a proxy between the client and the Internet for example, that’s modifying the HTTP header in some unknown way.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4782948-bfbd-3282-8c17-dfe40a9d96a4
* Version Independent ID: 6fc52e65-09b7-a465-22c7-b20f49914f49
* Content: [NetworkConnectivityLevel Enum (Windows.Networking.Connectivity) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.networking.connectivity.networkconnectivitylevel?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Networking.Connectivity/NetworkConnectivityLevel.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Networking.Connectivity/NetworkConnectivityLevel.xml)
* Service: **uwp**
* Sub-service: **winrt-reference**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @JeffMill. That fix is published now.

-Steve
