### ISSUE TITLE
Missing C++/winrt sample

### ISSUE THREAD

**Issue by HunterB06** [MicrosoftDocs/winrt-api#2450]
Hello,

When selecting C++/winrt on the language select box, the samples displayed on the page are still C#.

They should be in C++/winrt.

Regards, 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efdbf325-cfae-54ca-9f32-0d6dbce462cc
* Version Independent ID: e9476192-6dde-b261-d24f-7862d3b7934b
* Content: [DependencyObject.RegisterPropertyChangedCallback Method (Windows.UI.Xaml) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback?view=winrt-22621#windows-ui-xaml-dependencyobject-registerpropertychangedcallback(windows-ui-xaml-dependencyproperty-windows-ui-xaml-dependencypropertychangedcallback))
* Content Source: [winrt-api-build/xml/Windows.UI.Xaml/DependencyObject.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.UI.Xaml/DependencyObject.xml)
* Service: **uwp**
* Sub-service: **winrt-reference**
* Technology: **winui**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Yes, in fact on API reference topics like this one, that language picker affects only the "Syntax" section. It doesn't affect the code examples that exist in the topic.

Providing code examples in C# is the first priority. Then, usually if the scenario would especially benefit from it, we try to provide a C++/WinRT version also. For example, the [Win2D "Hello, World!" quickstart](https://learn.microsoft.com/windows/apps/develop/win2d/hellowin2dworld) does have a C++/WinRT version.

However, that wouldn't be good ROI for every code example. Many of them are quite mechanical to port to C++. So for those cases, we have resources such as the [C++/WinRT](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/) content in general, and then the [Porting the Clipboard sample to C++/WinRT from C#—a case study](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp) and [Move to C++/WinRT from C#](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-csharp) topics in particular.

So I'll close this issue for now.

-Steve
