### ISSUE TITLE
StorageItemContentProperties sample is not a sample

### ISSUE THREAD

**Issue by SamHobbsOrg** [MicrosoftDocs/winrt-api#2451]
The sample code in the page is not a code sample of `StorageItemContentProperties`, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4672134c-30c9-f848-71ff-b7f1d78e8f19
* Version Independent ID: cf34c717-8bdd-c949-3eba-8dc612a8689b
* Content: [StorageItemContentProperties Class (Windows.Storage.FileProperties) - Windows UWP applications](https://learn.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.storageitemcontentproperties?view=winrt-22621)
* Content Source: [winrt-api-build/xml/Windows.Storage.FileProperties/StorageItemContentProperties.xml](https://github.com/MicrosoftDocs/winrt-api/blob/docs/winrt-api-build/xml/Windows.Storage.FileProperties/StorageItemContentProperties.xml)
* Service: **uwp**
* Sub-service: **winrt-reference**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @SamHobbsOrg. The `StorageItemContentProperties` class is being used in the sample on this page. The `Properties` object on this line is of that type:

```
IDictionary<string, object> extraProperties = await file.Properties.RetrievePropertiesAsync(propertiesName);
```

Is there some other use of the type that you were looking for? You can try the sample yourself at the link provided on that page.
https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/FileAccess/cs

If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!

**Comment by SamHobbsOrg** [comment]
I am sure that what you say makes sense to you but it definitely does not make sense to me. I do not understand how the `StorageItemContentProperties` class is relevant. When I look at the definition of `RetrievePropertiesAsync` I see:

	public IAsyncOperation<IDictionary<string, object>> RetrievePropertiesAsync(IEnumerable<string> propertiesToRetrieve)
	{
		return IStorageItemExtraPropertiesMethods.RetrievePropertiesAsync(_objRef_global__Windows_Storage_FileProperties_IStorageItemExtraProperties, propertiesToRetrieve);
	}

I see no use of the `StorageItemContentProperties` class. I think the documentation should explain how the sample uses the class.
