### ISSUE TITLE
DeviceClass details is missing some words

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#247]
[Source](https://github.com/MicrosoftDocs/winrt-api/blob/5368cfd5b81ba146de8cc278817b969d39bdb755/windows.devices.enumeration/deviceclass.md#L0)

A couple of field descriptions of this enum start with "Introduced in ." Notice the blank between "in" and the period. It seems like there's a missing word there.

![image](https://user-images.githubusercontent.com/199935/34847701-212a4a4a-f6d1-11e7-9cf4-314c1a7bea62.png)

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you @rigdern for this feedback.

@msatranjr, can you follow up on this? Thank you!

**Comment by muhsinking** [comment]
Fix is committed, I'll close this issue when it's live. Thanks for bringing this up Adam!
