### ISSUE TITLE
Does custom capability from Microsoft needs extra approval for sccd file?

### ISSUE THREAD

**Issue by awrff** [MicrosoftDocs/winrt-api#2479]
hi, team

i'm currently developing a feature related to Esim. I use api from namespace Windows.Networking.NetworkOperators to facilitate Esim information. Documentation says this api requires custom capability Microsoft.eSIMManagement_8wekyb3d8bbwe. I add this capability and create a demo sccd file to pass the local test and everything works fine.

I know this capability needs approval before publish to the store. And I want to know that since it's a custom capability from Microsoft, do I need special approval for this sccd file? If needed, who should i contact with?

Thanks!

**Comment by stevewhims** [comment]
I would recommend looking at the section [Custom capabilities](https://learn.microsoft.com/windows/uwp/packaging/app-capability-declarations#custom-capabilities). That links to a previous section in the same topic with more details.

HTH!
-Steve
