### ISSUE TITLE
Both MediaPlayerState and MediaPlaybackState enums are marked as deprecated

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#249]
Relevant pages:
  - [`MediaPlaybackState`](https://github.com/MicrosoftDocs/winrt-api/blob/738ae75b9ff8fc30adf3268a6006ca837531849b/windows.media.playback/mediaplaybackstate.md#L0)
  - [`MediaPlayerState`](https://github.com/MicrosoftDocs/winrt-api/blob/738ae75b9ff8fc30adf3268a6006ca837531849b/windows.media.playback/mediaplayerstate.md#L0)

[`MediaPlaybackState`](https://github.com/MicrosoftDocs/winrt-api/blob/738ae75b9ff8fc30adf3268a6006ca837531849b/windows.media.playback/mediaplaybackstate.md#L0) has a note which says it may no longer be available after `1607` and `MediaPlayerState` should be used instead.

![image](https://user-images.githubusercontent.com/199935/35174136-15074486-fd23-11e7-9834-cc957eac1cfc.png)

However, [`MediaPlayerState`](https://github.com/MicrosoftDocs/winrt-api/blob/738ae75b9ff8fc30adf3268a6006ca837531849b/windows.media.playback/mediaplayerstate.md#L0) has an attribute which says it's deprecated.

![image](https://user-images.githubusercontent.com/199935/35174184-4ac3c388-fd23-11e7-8d2a-fea5db5c405e.png)

So both enums are marked as deprecated. Is this a mistake?

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you for the question, @rigdern.

@drewbatgit, can you answer? Thanks!

**Comment by drewbatgit** [comment]
@rigdern - Thank you for catching this, I checked the source code and it is indeed MediaPlayerState that is deprecated (that DeprecatedAttribute tag is dynamically extracted from the source code). The Note was indeed placed in the wrong enumeration by mistake. I have fixed this in the source and merged it into the master branch. It should show up on the live site tomorrow. Thanks again!
