### ISSUE TITLE
Why can't you Microsoft people add a "Watermark" Property to TextBlock and ComboBoxs?

### ISSUE THREAD

**Issue by bubba9999** [MicrosoftDocs/winrt-api#251]
Why can't you Microsoft people add a "Watermark" Property to TextBlock and ComboBoxs that adds a watermark label to left or inside and above the content for telling people what the TextBox or ComboBox is for?? I hate writing garage templates to do the same thing.  It should be built into the component in my opinion. Example:

<TextBox WaterMark="rate" Text="1.0"/>

The Effect this Achieves without all the garbage:

            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="auto"/>
                    <ColumnDefinition Width="*"/>
                </Grid.ColumnDefinitions>
                <Grid.RowDefinitions>
                    <RowDefinition Height="auto"/>
                </Grid.RowDefinitions>
                <TextBlock Grid.Row="0" Grid.Column="0" Text="Rate" FontSize="10" Padding="3,0,0,0"/>
                <TextBox Grid.Row="0" Grid.Column="0" Padding="0,10,0,0" Margin="0" Text="1.0" FontSize="12"/>
            </Grid>

**Comment by ginami** [comment]
Thanks @bubba9999 for your comment. The best place to raise this issue is the Windows Platform UserVoice (https://wpdev.uservoice.com/) --adding it there will get your request in front of the right team.
Thank you!
