### ISSUE TITLE
Provide summary document of all logging options and recommendations

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#252]
I wanted to pick a logging solution for my C# UWP app and found the number of options to be overwhelming:
  - `System.Diagnostics.Debug`
  - `System.Diagnostics.Trace`
  - `System.Diagnostics.Tracing`
  - `Windows.Foundation.Diagnostics.LoggingChannel`

I couldn't find any document which describes the relationship between all of these APIs. What are the trade offs between these APIs? Which ones are recommended for which use cases?

I want to pick the right logging API up front so that my team doesn't end up having to rewrite all of our logging code later after we learn what the right option would have been the hard way through experience.

Picking a logging API is a problem that every serious UWP app team has to do. It would be nice to have a document that summarizes the UWP logging options, their relationships, their trade offs, and makes some recommendations. This is nicer than the current state of each app team having to study each logging API and try to guess at the relationships and trade offs between all of the options.

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you @rigdern for this feedback.

@Xansky, can you respond? Thanks!

**Comment by mhopkins-msft** [comment]
Hi Adam,

I'll contact you via email to discuss how we can assist.

Thanks,
 - Mark
