### ISSUE TITLE
Application events don't state their threading contracts

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#258]
Relevant documents (not exhaustive):
  - [Resuming](https://github.com/MicrosoftDocs/winrt-api/blob/493ab1302d0238ab181b7fbc65c6437500f1ce45/windows.ui.xaml/application_resuming.md)
  - [Suspending](https://github.com/MicrosoftDocs/winrt-api/blob/493ab1302d0238ab181b7fbc65c6437500f1ce45/windows.ui.xaml/application_suspending.md#L0)
  - [EnteredBackground](https://github.com/MicrosoftDocs/winrt-api/blob/493ab1302d0238ab181b7fbc65c6437500f1ce45/windows.ui.xaml/application_enteredbackground.md#L0)
  - [LeavingBackground](https://github.com/MicrosoftDocs/winrt-api/blob/493ab1302d0238ab181b7fbc65c6437500f1ce45/windows.ui.xaml/application_leavingbackground.md#L0)

For example, the [`Resuming`](https://github.com/MicrosoftDocs/winrt-api/blob/493ab1302d0238ab181b7fbc65c6437500f1ce45/windows.ui.xaml/application_resuming.md) reference documentation doesn't state which thread it can be raised from but the ["Handle app resume"](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/resume-an-app#refresh-displayed-content-and-reacquire-resources) document states:

> Note Because the Resuming event is not raised from the UI thread, a dispatcher must be used in your handler to dispatch any calls to your UI.

However, in practice, I see that `Resuming` is usually called on the dispatcher.

So here's my feedback:
  - It would be great if the reference documentation for `Resuming` and `Application's` other events documented which thread their handlers run on.
  - ["Handle app resume's"](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/resume-an-app#refresh-displayed-content-and-reacquire-resources) note should be updated to say that "the `Resuming` event is sometimes raised by a thread other than the UI thread" -- from my experiments, this is more accurate than saying it's not raised from the UI thread. 

Adam Comella
Microsoft Corp.

**Comment by TylerMSFT** [comment]
Thanks Adam.  I'll follow up with you internally.

**Comment by TylerMSFT** [comment]
@rigdern  - per my last thread on this with you internally, I don't think we reached consensus with dev about documenting this. Please take it up on that thread if you wish to pursue further.

**Comment by TylerMSFT** [comment]
Adam is internal. After speaking with dev he proposes we document where Xaml.Application.Start runs its callback (on the main view) and where the Resuming, Suspending, EnteredBackground, and LeavingBackground event handlers run (the same apartment in which they were registered).

**Comment by hkhmsft** [comment]
Closing this Issue as it's been solved in the following PR:

https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api/pullrequest/15648?_a=files

Thanks @rigdern and @TylerMSFT for the work.
