### ISSUE TITLE
Calling IBackgroundTaskInstance.GetDeferral multiple times

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#262]
Relevant document: [`Windows.ApplicationModel.Background.IBackgroundTaskInstance.GetDeferral`](https://github.com/MicrosoftDocs/winrt-api/blob/bcace4df459f70f3ad3ba5bdc230ff678d8b3507/windows.applicationmodel.background/ibackgroundtaskinstance_getdeferral_254836512.md#L0)

What happens if I have two calls to `GetDeferral()`? Does the background task complete as soon as I call `Complete()` on one deferral? Or do I need to call `Complete()` on all of the deferrals I take in order for the background task to end?

**Comment by TylerMSFT** [comment]
Handling offline with rigdern.
