### ISSUE TITLE
Missing details in `Contacts.*.ReadBatchAsync` documentation

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#266]
Relevant documentation pages in the `Windows.ApplicationModel.Contacts` namespace:
  - [ContactReader.ReadBatchAsync](https://github.com/MicrosoftDocs/winrt-api/blob/33243819df32bb29e17fde25364787e7b304a3ac/windows.applicationmodel.contacts/contactreader_readbatchasync_888788553.md#L0)
  - [ContactChangeReader.ReadBatchAsync](https://github.com/MicrosoftDocs/winrt-api/blob/33243819df32bb29e17fde25364787e7b304a3ac/windows.applicationmodel.contacts/contactchangereader_readbatchasync_888788553.md#L0)

After reading the documentation for those APIs, I have the following questions:
  - Am I expected to call `ReadBatchAsync` just once or multiple times?
  - If I'm expected to call it multiple times, how do I know when I should stop calling it?

Regarding `ContactReader.ReadBatchAsync`, we can infer some answers by looking at the [official contacts sample](https://github.com/Microsoft/Windows-universal-samples/blob/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/PhoneCall/cs/ViewModels/ContactsViewModel.cs#L176). However, it would be great if the documentation provided official answers to those questions.

### Additional Issue: No sample code for `ContactChangeReader.ReadBatchAsync`

(also filed as Microsoft/Windows-universal-samples#846)

Regarding `ContactChangeReader.ReadBatchAsync`, **there is no official sample** to look at. However, I was able to find a useful snippet that was [pasted into a GitHub issue](https://github.com/Microsoft/Windows-universal-samples/issues/78#issuecomment-126550721). It would be great if that snippet was validated and turned into an official sample.

Adam Comella
Microsoft Corp.

**Comment by normesta** [comment]
Thanks Adam - following up offline.

**Comment by normesta** [comment]
Hi Adam - OK I've created a pull request for this issue and the other one that you raised against the docs. I've added you as a reviewer. Can you pls take a look? Thx!

**Comment by normesta** [comment]
Ok. Thanks for the review Adam. Also had a great resource from the product team review it as well so I think we are clean. PR has been merged.
