### ISSUE TITLE
Contacts: Contract for handling `ContactChangeType.ChangeTrackingLost`?

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#267]
Relevant documentation pages:
  - [Windows.ApplicationModel.Contacts.ContactChangeType](https://github.com/MicrosoftDocs/winrt-api/blob/33243819df32bb29e17fde25364787e7b304a3ac/windows.applicationmodel.contacts/contactchangetype.md#L0)
  - [Windows.ApplicationModel.Contacts.ContactChangeTracker.Reset](https://github.com/MicrosoftDocs/winrt-api/blob/33243819df32bb29e17fde25364787e7b304a3ac/windows.applicationmodel.contacts/contactchangetracker_reset_1636126115.md#L0)

After reading the documentation for `ContactChangeType.ChangeTrackingLost`, I'm not sure how exactly I should handle this case. The documentation is vague and just says to call `Reset`. Why do I need to call `Reset`? What does `Reset` do? The [`Reset` documentation](https://github.com/MicrosoftDocs/winrt-api/blob/33243819df32bb29e17fde25364787e7b304a3ac/windows.applicationmodel.contacts/contactchangetracker_reset_1636126115.md#L0) doesn't help -- it just says to call it when `ChangeTrackingLost` is received.

Somebody pasted [a snippet into a GitHub comment](https://github.com/Microsoft/Windows-universal-samples/issues/78#issuecomment-126550721) which provides some enlightenment. The snippet says a couple of things:
  - Upon receiving `ChangeTrackingLost`, you must reread all of the contacts.
  - You should call `Reset` before reading all of the contacts.

Details like this, assuming they are correct, should be added to the official documentation.

Adam Comella
Microsoft Corp.

**Comment by normesta** [comment]
Thx Adam - following up offline

**Comment by normesta** [comment]
Hi Adam - OK I've created a pull request for this issue and the other one that you raised against the docs. I've added you as a reviewer. Can you pls take a look? Thx!

**Comment by normesta** [comment]
Ok. Thanks for the review Adam. Also had a great resource from the product team review it as well so I think we are clean. PR has been merged.
