### ISSUE TITLE
MediaPlayer: Unclear how to obtain multiple surfaces

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#268]
Relevant documentation page: [Windows.Media.Playback.MediaPlayer.GetSurface](https://github.com/MicrosoftDocs/winrt-api/blob/33243819df32bb29e17fde25364787e7b304a3ac/windows.media.playback/mediaplayer_getsurface_812026623.md#L0)

The documentation says:

> You can obtain multiple surfaces from a single MediaPlayer instance by calling MediaPlayer multiple times.

It seems like a typo when it mentions "calling MediaPlayer multiple times". `MediaPlayer` is a class, not a method.

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you @rigdern for pointing this out! @drewbatgit, can you follow up on this?

**Comment by drewbatgit** [comment]
Thanks for your feedback. This was a typo that has been corrected. It now reads "calling GetSurface multiple times".
