### ISSUE TITLE
VideoChat should be E13B in https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol

### ISSUE THREAD

**Issue by fgenolini** [MicrosoftDocs/winrt-api#275]
in https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol
VideoChat is listed as having the value E138 in the documentation comment

this is a typo, the value is E13B

**Comment by ginami** [comment]
Thanks @fgenolini for bringing this to our attention! @jwmsft can you respond?

**Comment by jevansaks** [comment]
Appears to be fixed now.
