### ISSUE TITLE
ApplicationView Class links in several places to a non-published (or non-existant) "Snap Sample"

### ISSUE THREAD

**Issue by theREALjdeck** [MicrosoftDocs/winrt-api#276]
in the See Also section of several sub-headings in the ApplicationView article (found here: https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview ) link to a "Snap Sample", however whenever I attempt to reach this sample, I am redirected to a page that displays the following error message:

> This item is not yet published.
> If you are the owner of this project, please sign in with the appropriate account. 

An example of this is found in the See Also section of the TryUnsnap() method on the Application View page linked above.

The link in question directs here: https://code.msdn.microsoft.com/windowsapps/Snap-Sample-2dc21ee3

We need to either publish that sample, or stop pretending it's available to the public.

**Comment by ginami** [comment]
Thanks @theREALjdeck for bringing this to our attention. @jwmsft can you please respond?

**Comment by jwmsft** [comment]
These links have been removed.
