### ISSUE TITLE
Projection types for return types and parameters

### ISSUE THREAD

**Issue by mattwojo** [MicrosoftDocs/winrt-api#28]
Projected types need to be translated based on syntax. 

https://msdn.microsoft.com/en-us/library/hh694558(v=vs.110).aspx

https://github.com/dotnet/coreclr/blob/master/src/inc/winrtprojectedtypes.h

**Comment by kevinyr** [comment]
We are working on this issue.

**Comment by kevinyr** [comment]
Development work is done. We are verifying the changes and expect to rollout the change very soon.

**Comment by kevinyr** [comment]
Changes have been deployed to fix this issue.
