### ISSUE TITLE
Docs always show sample code for all languages

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#281]
For example, I went to https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacaptureinitializationsettings and saw code samples for C# and JavaScript:

![image](https://user-images.githubusercontent.com/199935/37012140-030bc45c-20a8-11e8-8cd5-697fd9ab4fe3.png)

I would expect to only see sample code for C# because that's the language I currently have selected:

![image](https://user-images.githubusercontent.com/199935/37012165-1850c33a-20a8-11e8-9ee1-f2313a0d12d4.png)

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you for your feedback, @rigdern. @mcleblanc can you please respond?

**Comment by drewbatgit** [comment]
These code snippets are injected into the content using a different pipeline than normal snippets and so the language filter doesn't affect these snippets. This is not ideal, but is expected behavior.
