### ISSUE TITLE
Incomplete sentence in winrt-api/windows.ui.xaml/style.md 

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#285]
In the document https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.ui.xaml/style.md#defining-a-style-as-a-xaml-resource towards the end of this section there is an incomplete sentence. Currently it reads

> A Style that's defined this way uses its TargetType property value as the implicit key and is known as an .

The sentence is not completed. But no idea what part is missing, known as a what?

**Comment by ginami** [comment]
Thank you @JuanMejiaVelez for letting us know. @jwmsft can you please respond?
