### ISSUE TITLE
Parameters for API attributes are not listed

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#286]
For example, if you look at the doc page for [`BackgroundTaskDeferral`](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.backgroundtaskdeferral) you can see that it has the `ContractVersionAttribute`, the `MarshallingBehaviorAttribute`, and the `ThreadingAttribute`:

![image](https://user-images.githubusercontent.com/199935/37238427-f3740726-23da-11e8-9585-2a6d8ef928ca.png)

However, it doesn't tell you what parameters are passed to the attributes. It doesn't tell you that the marshalling behavior is "standard" or that the threading model is "MTA".

It would be helpful if the attribute parameters were listed across the documentation.

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thanks @rigdern for your feedback. @mcleblanc can you please respond?

**Comment by TylerMSFT** [comment]
Taking this up with rigdern offline.

**Comment by TylerMSFT** [comment]
@rigdern  - Hi, our automation doesn't build out the parameters for the Attributes block.
