### ISSUE TITLE
BackgroundTaskDeferral: Document proper usage with respect to threading & marshaling contracts

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#287]
Relevant doc page: [Windows.ApplicationModel.Background.BackgroundTaskDeferral](https://github.com/MicrosoftDocs/winrt-api/blob/0de82970bc970828fe36c532692294ebe3936aee/windows.applicationmodel.background/backgroundtaskdeferral.md#L0)

The doc states that `BackgroundTaskDeferral` is not agile so you must consider its threading model and marshaling behavior. Here's my feedback:
  1. The threading model and the marshaling behavior of `BackgroundTaskDeferral` are not mentioned on the page. I had to use Visual Studio to figure out that they are "MTA" and "standard", respectively. I opened #286 to track this systemic issue.
  2. I looked at the [.NET](https://msdn.microsoft.com/en-us/library/windows/apps/jj157115.aspx) and [C++/CX](https://docs.microsoft.com/en-us/cpp/cppcx/threading-and-marshaling-c-cx) threading/marshaling docs that the "remarks" section links to but neither helped me understand what the combination of "MTA" threading and "standard" marshaling means. How can I make sure I'm using the `BackgroundTaskDeferral` properly?
  3. The [.NET threading/marshaling doc](https://msdn.microsoft.com/en-us/library/windows/apps/jj157115.aspx) isn't hosted on the new documentation website.

The biggest issue is (2). I think it's especially important that developers understand how to properly use `BackgroundTaskDeferral` with respect to threading and marshaling because it's likely they'll want to use it across multiple threads. Here's an example scenario:
  - You take a deferral in `OnBackgroundActivated`. In my app, I'm seeing `OnBackgroundActivated` being executed on the dispatcher. When you take a deferral, you have to take it synchronously so, in this case, I take it on the dispatcher.
  - When my background work is done, I complete the deferral. In this example, do I have to return to the dispatcher to do that?
  - If the OS cancels my background task, I believe I have to complete the deferral synchronously in the task cancellation handler otherwise I'll be at risk of being terminated. I'm not sure what thread the task cancellation handler runs on or whether it's actually safe to complete the deferral there.

Adam Comella
Microsoft Corp.

**Comment by ginami** [comment]
Thank you @rigdern for your feedback. @TylerMSFT can you please respond?

**Comment by TylerMSFT** [comment]
Taking this up with rigdern offline.

**Comment by TylerMSFT** [comment]
Rigdern is internal. Will follow up with him.
