### ISSUE TITLE
Provide UI for linking to subsections of doc pages

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#290]
Suppose I'm looking at a doc page like [`Windows.UI.Xaml.Application`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application) and I want to link somebody to a particular method on it like `OnBackgroundActivated`. Currently, the only way I know how to create a link to that part of the page is to view the source and craft the link by hand (example of the [handcrafted link to the `OnBackgroundActivated` method](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application#Windows_UI_Xaml_Application_OnBackgroundActivated_)).

Instead, the UI should surface this ability to create links to particular parts of the page.

GitHub has UI like this so you can create a link to any section of a markdown file. When you hover over a section title, a button appears which links to that title. Notice the icon next to "Prerequisites":

![image](https://user-images.githubusercontent.com/199935/37633622-54d2617a-2bb0-11e8-89a0-64e275be9ebc.png)

Clicking that appends `#prerequisites` to your URL: https://github.com/Microsoft/reactxp/blob/c86fe2fa69a06062aa00a6a7355f28b02a7972a7/README.md#prerequisites

Adam Comella
Microsoft Corp.

**Comment by GrantMeStrength** [comment]
We're about to address that issue.. Please check back in a few weeks.
