### ISSUE TITLE
ShareOperation.ReportError: Docs say error is shown to the user but I don't see it

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#292]
Relevant doc page: [`Windows.ApplicationModel.DataTransfer.ShareTarget.ShareOperation.ReportError`](https://github.com/MicrosoftDocs/winrt-api/blob/67ee1c2952e79d53404a07c895d9ecc40ebddd1a/windows.applicationmodel.datatransfer.sharetarget/shareoperation_reporterror_1034694985.md#L0)

The documentation says "The system displays this message to the user.". Is this true? If so, where is the error message shown to the user? My team has experimented with the API and we haven't seen the error message displayed anywhere.

Adam Comella
Microsoft Corp.

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. This GitHub repo is specifically for reporting documentation bugs. For product questions like this, please see the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).

I'm marking this issue as closed now, but please feel free to reopen it if you have more information that indicates a real doc bug here. Thanks again!
