### ISSUE TITLE
SpeechRecognitionConstraintProbability enum described wrong?

### ISSUE THREAD

**Issue by AtosNicoS** [MicrosoftDocs/winrt-api#299]
Hello,
I am referring to this doc:
https://docs.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognitionconstraintprobability
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.media.speechrecognition/speechrecognitionconstraintprobability.md/#L0

It looks that the description of "default" and "min" is swapped:
```
## -enum-fields
### -field Default:0
The constraint has a low weighted value.

### -field Min:1
The constraint has a medium weighted value.

### -field Max:2
The constraint has a high weighted value.
```

I guess the correct version would be:
```
## -enum-fields
### -field Default:0
The constraint has a medium weighted value.

### -field Min:1
The constraint has a low weighted value.

### -field Max:2
The constraint has a high weighted value.
```

Please correct me if I am wrong.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback and suggestions! I confirmed with the feature team devs that the values and descriptions are correct as they are currently listed. There are no plans to revise this due to the number of existing apps that it would affect.
