### ISSUE TITLE
 More Info Needed for ExetendedExecutionSession.PercentProgress

### ISSUE THREAD

**Issue by taoyouh** [MicrosoftDocs/winrt-api#30]
It says this property is "A value to show progress in the shell", but don't know where it actually shows. If currently it doesn't actually show a progress in the shell, the doc should inform API users of this.

File directory:
winrt-api/windows.applicationmodel.extendedexecution/extendedexecutionsession_percentprogress.md

**Comment by mattwojo** [comment]
Hey @awkoren - Looks like this API property belongs to you -- could you work on getting this updated? Here's the page: https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.applicationmodel.extendedexecution/extendedexecutionsession_percentprogress.md

**Comment by awkoren** [comment]
@mcleblanc

**Comment by drewbatgit** [comment]
Thank you for identifying this issue. The shell UI to display this property and the Description property were never implemented in the OS. I have updated the docs to state "This property is not used in the current release."
