### ISSUE TITLE
Is this up to date?

### ISSUE THREAD

**Issue by Tamer-Gamal** [MicrosoftDocs/winrt-api#300]
is that information is up to date ?
if so , when it will be supported regarding the System-internal or on-chassis serial ports

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e79afb68-4107-5766-a8ee-da81b31c5c0d
* Version Independent ID: e8fb40ec-0774-30a9-47bb-69fca4df39b0
* Content: [Windows.Devices.SerialCommunication Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.serialcommunication)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.serialcommunication.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.serialcommunication.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by gmgallo** [comment]
For onboard and X86 there is a  System.IO.Ports.SerialPort() that you can use. Unfortunately this only looks for COMx ports and rejects any UARTx port name that forces to have two versions of the app depending on the target platform. I use a wrapper class that hides this dual personality of the serial port to the rest of the application.

**Comment by QuinnRadich** [comment]
Apologies for a long-delayed response here.

As this is API reference content, it's kept up to date with the APIs available in the Windows SDK. If there's still nothing in this area that provides the functionality you want, I'd suggest providing product feedback. Thank you.

**Comment by Tamer-Gamal** [comment]
Sorry i didn't see the alert for this issue, Yes the problem is still the same that "System-internal or on-chassis serial ports may be enumerated by DeviceInformation.FindAllAsync(), but cannot be opened by SerialDevice.FromIdAsync() because they currently are not supported. However, serial ports connected over USB, such as on USB-to-Serial cables are supported."
