### ISSUE TITLE
Include links to other Landmarks pages

### ISSUE THREAD

**Issue by citelao** [MicrosoftDocs/winrt-api#301]
When I search "landmarks xaml" in Bing, this is the first result I get, and there are no other relevant results on the first page. Unfortunately, this page is a dead end.

I would love a cross-link to [the UWP landmarks & headings guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/landmarks-and-headings) or the [corresponding `AutomationProperties` entry](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties.landmarktypeproperty#Windows_UI_Xaml_Automation_AutomationProperties_LandmarkTypeProperty).

Is that relevant here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b993b1a-3a2f-b4c6-404a-a9bce51fe917
* Version Independent ID: 125d81a9-9503-ba09-f57d-c72c8692651d
* Content: [AutomationLandmarkType Enum (Windows.UI.Xaml.Automation.Peers) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.peers.automationlandmarktype)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.peers.automationlandmarktype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.peers.automationlandmarktype.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
I believe this was addressed by PR #302
