### ISSUE TITLE
Not works at all

### ISSUE THREAD

**Issue by mmppeegg** [MicrosoftDocs/winrt-api#304]
Don't find any HID device by leveraging this API under RS3 1709. Please release Windows hotfix ASAP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce94a24d-94a3-af51-e314-768ebe748022
* Version Independent ID: 55936e57-44bb-eef7-70cc-7889986b663c
* Content: [HidDevice.GetDeviceSelector Method (Windows.Devices.HumanInterfaceDevice) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hiddevice.getdeviceselector)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi, can you provide more detail on your issue? Code would be helpful. Thanks.

**Comment by Karl-Bridge-Microsoft** [comment]
Hey Gina,

I have to send a status mail out and John has asked me to include a bunch of data points.

One I’d like to include is a count (and maybe details report) for all customer requests like this that have been assigned to John’s team. Is that possible?

Karl

**Comment by Karl-Bridge-Microsoft** [comment]
Hi, I've updated the topic with a bit more info and revised code snippet.
