### ISSUE TITLE
"Unknown" for desktop

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/winrt-api#305]
I'm getting "Unknown" for DeviceForm on Windows 1709 :/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac66f1e-bbaa-47e5-3e61-901a7348a05e
* Version Independent ID: c4572b16-b474-24bb-eaf3-fed3818d0bc4
* Content: [AnalyticsInfo.DeviceForm Property (Windows.System.Profile) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.analyticsinfo.deviceform#Windows_System_Profile_AnalyticsInfo_DeviceForm)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.analyticsinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.analyticsinfo.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Hi fman028, "Unknown" is a valid return value. Is there something you'd like updated in the docs?

**Comment by mhopkins-msft** [comment]
It's been two weeks with no response so I'm going to close this issue. Please reopen if you have any further input. Thanks!

**Comment by AbhinavSharma96** [comment]
This code is working fine for laptops. They have battery but for desktop system there is no battery. so when power supply goes off  it does't show any response. How can get a response  from UPS (Uninterruptible Power Supply) when power supply off Using C#.
