### ISSUE TITLE
No example or link to example in MarkupExtension document.

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#306]
This feature is missing an example or link to the example from is doc page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78089b5-5304-8c53-1149-cf4a8c7d02d8
* Version Independent ID: 149dae95-568e-85aa-1799-c413458cb826
* Content: [MarkupExtension Class (Windows.UI.Xaml.Markup) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.markupextension)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.markup.markupextension.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.markup.markupextension.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
You can find an example [here](https://github.com/michael-hawker/UWPCommunityToolkit/blob/mhawker/uniformgrid-as-grid/Microsoft.Toolkit.Uwp.UI/Extensions/Markup/NullableBool.cs) that I've been working on for the Toolkit.

**Comment by pedrolamas** [comment]
Adding my own example:
https://www.pedrolamas.com/2019/03/31/making-the-case-for-xaml-markup-extensions/

**Comment by weitzhandler** [comment]
Is there any way to access property bindings in MarkupExtensions?

Here are a couple of usage examples:

```xaml
<TextBox IsEnabled="{Binding IsBusy, Converter={ex:MyNegator}}" />

<!-- or -->

<TextBox IsEnabled="{ex:Negator Value={Binding IsBusy}}" />
```

How can I access the bound value in the extension, is there any way to access it or resolve a binding? The `ProvideValue` method doesn't come with a `serviceProvider` parameter or anything. Any hack for this?

Related: https://github.com/microsoft/microsoft-ui-xaml/issues/741

**Comment by evelynwu-msft** [comment]
@weitzhandler, by "access the bound value", are you referring to the Binding Source, i.e. the value of the data context's `IsBusy` property? 

If that is the case, then your second example should work today, as your `Negator` custom markup extension's `Value` property is the Target of the Binding.

For your first example, I would recommend foregoing the custom markup extension and just author a standard [`IValueConverter`](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Data.IValueConverter) implementation.

**Comment by jwmsft** [comment]
Added link to Windows Community Toolkit examples.
