### ISSUE TITLE
Needs more detail and improvement due to inaccuracy

### ISSUE THREAD

**Issue by alexmarshall132** [MicrosoftDocs/winrt-api#307]
This documentation does not reflect the fact that ApplicationTrigger only triggers out-of-process background tasks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa12c93d-0fec-a4e4-b1f1-cff570587850
* Version Independent ID: 022c028f-ca6c-9531-f85d-3ca794525a07
* Content: [ApplicationTrigger Class (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.applicationtrigger)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.applicationtrigger.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.applicationtrigger.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by TylerMSFT** [comment]
Hi Alex,
In-proc background tasks didn't exist when that content was written. I'll add the clarification.

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
