### ISSUE TITLE
About how to set timesFromStart parameter

### ISSUE THREAD

**Issue by ChrisShaoMeng** [MicrosoftDocs/winrt-api#309]
When I initialized timesFromStart parameter, I add 4s, 8s, 12s in it. But with the result of vector view, All the ImageStream are the view of 4s. Please could someone help me to set the timesFromStart correctly, or is there a sample code? Thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9bf69aa-9f83-5806-4572-79bd12549822
* Version Independent ID: 14fce80a-7ef0-2955-f196-36ff7e2b019b
* Content: [MediaComposition.GetThumbnailsAsync(IIterable<TimeSpan>, Int32, Int32, VideoFramePrecision) Method (Windows.Media.Editing) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.editing.mediacomposition.getthumbnailsasync#Windows_Media_Editing_MediaComposition_GetThumbnailsAsync_Windows_Foundation_Collections_IIterable_Windows_Foundation_TimeSpan__System_Int32_System_Int32_Windows_Media_Editing_VideoFramePrecision_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.editing.mediacomposition.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.editing.mediacomposition.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by michaelhutchful** [comment]
Did you ever figure out the issue? What I found is if you set VideoFramePrecision.NearestKeyFrame you might get this behavior. Try VideoFramePrecision.NearestFrame

**Comment by StevenEdwardWood** [comment]
I'm getting the same problem with NearestFrame.  No matter how many TimeSpans are in the IIterable<TimeSpan> for the first parameter images returned are alternately the 1st image followed by a blank image.
Also, the heading of this page indicates that the first parameter is an IIterable<TimeSpan> while the code definition and parameter list declares it as IEnumerable<TimeSpan>.
I'm using a List<System.TimeSpan> for the first parameter which implements IEnumerable but according to the implement list for a List it does not directly implement IIterable.  There needs to be clarification on this and if the parameter does not implement the required interface then an exception should be thrown.

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. 

I created a quick sample app and I'm unable to reproduce your issue. The following code results in thumbnails from different times in the video:

```
composition = new MediaComposition();
await PickFileAndAddClip();

var streams = await composition.GetThumbnailsAsync(new List<TimeSpan>() { TimeSpan.FromSeconds(.5f), TimeSpan.FromSeconds(3.5f), TimeSpan.FromSeconds(7.5f) }, 320, 240, VideoFramePrecision.NearestFrame);
var idx = 0;
foreach(var s in streams)
{
    var img = new Windows.UI.Xaml.Controls.Image();
    img.Width = 320;
    img.Height = 240;
    var bmp = new BitmapImage();
    await bmp.SetSourceAsync(s);
    img.Source = bmp;
    Windows.UI.Xaml.Controls.TextBlock text = new TextBlock();
    text.Text = "IMG: " + idx;

    stackPanel.Children.Add(text);
    stackPanel.Children.Add(img);
    idx++;
}
```
```
private async Task PickFileAndAddClip()
{
    var picker = new Windows.Storage.Pickers.FileOpenPicker();
    picker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.VideosLibrary;
    picker.FileTypeFilter.Add(".mp4");
    Windows.Storage.StorageFile pickedFile = await picker.PickSingleFileAsync();
    if (pickedFile == null)
    {
        //ShowErrorMessage("File picking cancelled");
        return;
    }

    // These files could be picked from a location that we won't have access to later
    var storageItemAccessList = Windows.Storage.AccessCache.StorageApplicationPermissions.FutureAccessList;
    storageItemAccessList.Add(pickedFile);

    var clip = await MediaClip.CreateFromFileAsync(pickedFile);
    composition.Clips.Add(clip);

}
```

Since, for now, this doesn't appear to be a documentation issue, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
