### ISSUE TITLE
Missing link to GamepadButtons

### ISSUE THREAD

**Issue by 1wizkid** [MicrosoftDocs/winrt-api#311]
This article indicates the Buttons is a field type of GamepadButtons but gives no link to GamepadButtons so you still can't tell what "Buttons" actually is. Please show GamepadButtons as a link to: https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepadbuttons

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34c25a6-d911-9736-c136-b8b812acffb1
* Version Independent ID: a88619b0-85fe-954c-c753-48ebe80bf3ca
* Content: [Input.Buttons Field (Windows.Gaming.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.gamepadreading.buttons)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.gamepadreading.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.gamepadreading.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Hi @1wizkid, thanks for your feedback. I've added a link to the doc per your suggestion. The change should go live within the next few weeks.
