### ISSUE TITLE
Sample out of date?

### ISSUE THREAD

**Issue by mvujovic** [MicrosoftDocs/winrt-api#314]
"For example code of handling Rendering, see shooting game sample." -- This statement in the doc might be out of date. I downloaded the sample and didn't find any App::OnRendering method or Rendering event handling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1694b7-b07b-d125-d80b-d1644f8526f3
* Version Independent ID: 0f39fb01-1b90-7860-21bf-042ccb669ffc
* Content: [Media.Rendering Event (Windows.UI.Xaml.Media) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.compositiontarget.rendering)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.compositiontarget.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.compositiontarget.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
@stmoy is this your area?
