### ISSUE TITLE
GetPreviewFrameAsync(previewFrame) issue

### ISSUE THREAD

**Issue by rrvenki** [MicrosoftDocs/winrt-api#315]
In an UWP app, i use as below
Using previewFrame As VideoFrame = New VideoFrame(InputPixelFormat, CType(videoProperties.Width, Integer), CType(videoProperties.Height, Integer))
                Await capManager.GetPreviewFrameAsync(previewFrame)
                If FaceDetector.IsBitmapPixelFormatSupported(previewFrame.SoftwareBitmap.BitmapPixelFormat) Then
                    fcs = Await fcTracker.ProcessNextFrameAsync(previewFrame)
...

In this fcs.count gives the count of faces in the video frame.
But this code is inside a ThreadPoolTimer and everytime this code is invoked the faces count becomes zero alternatively.'

For example if there are 2 people in the frame, it detects count as 2 in first iteration.  In subsequent iteration which triggers based on the threadpooltimer interval, the count becomes zero.  That means for every alternative iteration the actual count is shown and inbetween it keeps setting to zero.

So the subroutine becomes irrelevant to count the faces in the frame.

Is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35486802-4632-23d9-e2d1-1089dade42a7
* Version Independent ID: 968a2126-fca1-0ab7-3d6b-3509156b0396
* Content: [MediaCapture.GetPreviewFrameAsync Method (Windows.Media.Capture) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture.getpreviewframeasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapture.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapture.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
I presented your question to the feature team and their recommendation is that you put the FaceDetectionEffect in the camera stream and then subscribe to the FaceDetected event to receive notifications when a detection has been made. This pattern is demonstrated in the CameraFaceDetection SDK sample (https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraFaceDetection) and described in the scene analysis for MediaCapture article in the developer documentation (https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/scene-analysis-for-media-capture#face-detection-effect). If your app scenario requires you to use the pattern you describe, then you will run into this issue if your polling thread is running faster than the face detection thread. In particular, if your thread is twice as fast as the capture rate, it will cause the alternating counts you are seeing.
