### ISSUE TITLE
Need better example and links for TargetApplicationPackageFamilyName on LauncherOptions

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#316]
The JS example just sets the property to itself.  It should have an example package family name so that a developer knows they have something that looks right in their own app.  There should also be a link to info about what the Application Package Family Name is and how to get one for an app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ff12cee-d588-9e46-2d5e-844dbe6f711a
* Version Independent ID: 2f14a1b3-c1f5-6dbd-4675-aceff296cfa0
* Content: [LauncherOptions.TargetApplicationPackageFamilyName Property (Windows.System) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcheroptions.targetapplicationpackagefamilyname#Windows_System_LauncherOptions_TargetApplicationPackageFamilyName)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.launcheroptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.launcheroptions.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by MatrixRonny** [comment]
If you are using Visual Studio, you can view the package family name if you open "Package.appxmanifest" in Designer (by default) and go to Packaging tab. If not, you can use PowerShell together with Get-AppxPackage command to view this information for installed applications.

The TargetApplicationPackageFamilyName should only be used when multiple applications target the same protocol (for example mailto). It cannot be used to launch an application that does not register to handle that specific protocol. See [Handle URI Activation](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-uri-activation) for more information.

An example of a package family name is the following: **Contoso.URIApp_8wknc82po1e**. The **Contoso.URIApp** part is the package name and the **8wknc82po1e** part is the publisher id.

**Comment by hickeys** [comment]
I've made some changes to the article, they should show up shortly.
