### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by CodySalyer** [MicrosoftDocs/winrt-api#318]
When no option is specified, how exactly does load async behave?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5456a3-63db-ae0a-93d2-ebe83380c408
* Version Independent ID: 2f25706e-c5e4-f4f4-cde5-5147755e5891
* Content: [InputStreamOptions Enum (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.inputstreamoptions)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.inputstreamoptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.inputstreamoptions.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by toxsedyshev** [comment]
Are there any clarifications on that question?

**Comment by rubberduck203** [comment]
I'd love to know too.

**Comment by ArchieCoder** [comment]
Waiting for an answer too!

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I apologize for the delayed response. However, what I can do to help is redirect you to the appropriate feedback channel to get an answer to your question. 

Our team covers the scope of specific documentation fixes, but the community of experts and Microsoft engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this Issue as an open thread for follow-ups. Thanks!
