### ISSUE TITLE
dead links

### ISSUE THREAD

**Issue by adrianstephens** [MicrosoftDocs/winrt-api#320]
all the allseenalliance links on this page appear to be dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f70bd54-5a54-5a5a-4757-494f3c916759
* Version Independent ID: bc92f8ff-2c76-77b2-3d97-2ddd828f0054
* Content: [Windows.Devices.AllJoyn Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.AllJoyn)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.alljoyn.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.alljoyn.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
I've pushed a fix for this issue, which should be live soon.
