### ISSUE TITLE
Language Not Switching From JavaScript to C#

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/winrt-api#321]
The language choice is not respected for the code sample, it's stuck in JavaScript.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12adc391-5fd6-1386-50aa-610f08acaca6
* Version Independent ID: 8439f5a6-b263-eb22-b6b8-86c24ce285b6
* Content: [PointerDevice Class (Windows.Devices.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Input.PointerDevice)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.input.pointerdevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.input.pointerdevice.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for letting us know about this issue. I've updated the JS snippet and added C# and C++ versions.
