### ISSUE TITLE
Installing Updates on an IoT Core Headless Device

### ISSUE THREAD

**Issue by greyghostbrewery** [MicrosoftDocs/winrt-api#322]
How do you install updates on a headless device?  This method requires user interaction via the UI on the device.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b544b90-f939-603e-5ee3-cbc034a9db17
* Version Independent ID: 08083f5a-4127-d1dd-6b45-ca3a06de9ed3
* Content: [StoreContext.RequestDownloadAndInstallStorePackageUpdatesAsync(IIterable<StorePackageUpdate>) Method (Windows.Services.Store) - UWP app developer](https://docs.microsoft.com/en-au/uwp/api/windows.services.store.storecontext.requestdownloadandinstallstorepackageupdatesasync#Windows_Services_Store_StoreContext_RequestDownloadAndInstallStorePackageUpdatesAsync_Windows_Foundation_Collections_IIterable_Windows_Services_Store_StorePackageUpdate__)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storecontext.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storecontext.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for reaching out with your question. For installing UWP app updates from the Store without user interaction on a headless device, we now provide the [TrySilentDownloadAndInstallStorePackageUpdatesAsync](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.trysilentdownloadandinstallstorepackageupdatesasync) method. However, note that this method will not work on a metered network and it does require Windows 10, version 1803 or later (it was first introduced in Windows 10 Insider Preview build v10.0.17110.0).
