### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#323]
See also section should say "Task<TResult>", not "Task &lt;TResult&gt;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbfaabda-7b03-c053-c527-b583a82aeafd
* Version Independent ID: a0419a42-9f60-8f5a-bf2d-ca9ba57c99db
* Content: [IAsyncOperation<TResult> Interface (Windows.Foundation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.IAsyncOperation_TResult_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncoperation_tresult_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncoperation_tresult_.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Thank you Mike. I've updated the topic source file. We will publish it as soon as we can.

**Comment by MikeHillberg** [comment]
Thanks!
________________________________

**Comment by mhopkins-msft** [comment]
Ready to publish.
