### ISSUE TITLE
Update link for Windows authentication broker sample 

### ISSUE THREAD

**Issue by AdamBraden** [MicrosoftDocs/winrt-api#324]
current link points to old Win8 sample, should point to UWP GitHub sample repo - https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WebAuthenticationBroker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda936b8-a85b-a6b1-b3b6-d2d845e31ffe
* Version Independent ID: 0d5dc733-9377-8a09-ae60-a922db2d8627
* Content: [WebAuthenticationOptions Enum (Windows.Security.Authentication.Web) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Security.Authentication.Web.WebAuthenticationOptions#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.webauthenticationoptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.webauthenticationoptions.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
This link has been fixed, and this change should be published to the live docs site within several days. Thanks for your feedback, and I apologize it took so long to address your issue.
