### ISSUE TITLE
Are any of these functions supposed to affect BluetoothLEDevice.ConnectionStatus?

### ISSUE THREAD

**Issue by MeitalBK** [MicrosoftDocs/winrt-api#325]
In which way does it show that these functions "initiates a connection"?
(after using FromBluetoothAddressAsync(UInt64) on an address of a disconnected BLE device, device's connection-status remains disconnected...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cedb9559-6da0-2e91-eaef-12d9e9bfff4f
* Version Independent ID: cf9ff409-0028-5b6c-b77e-3987ad23671d
* Content: [BluetoothLEDevice.FromBluetoothAddressAsync Method (Windows.Devices.Bluetooth) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync#Windows_Devices_Bluetooth_BluetoothLEDevice_FromBluetoothAddressAsync_System_UInt64_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by asanfilov** [comment]
The author of the above comment is right. Please remove these confusing words "and initiates a connection" from the method's description. `FromBluetoothAddressAsync` does not establish a connection to the device, and the device keeps advertising and remains in a non-connected state.

See a quick demo that explains how to connect:
https://github.com/aprobinda/bluetooth-le-demo/

**Comment by stevewhims** [comment]
Hi, @MeitalBK. Thanks for filing this issue, and my apologies for the delay in responding.

I've updated the **FromBluetoothAddressAsync** and **FromIdAsync** topics with more details about connections.

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now. ~Steve
