### ISSUE TITLE
Documentation needs to be a lot more comprehensive and not simply repeating self explanatory information

### ISSUE THREAD

**Issue by derzorngottes** [MicrosoftDocs/winrt-api#326]
It would be really nice to have some kind of description or link to what 'hosted' means. "Gets the value that indicates whether this app view is hosted or not" - this is self explanatory by the name of the property. I come to the documentation to learn more about what the terminology means and how it functions as part of building the application. Most of the UWP documentation is simply a slightly longer sentence repeating what is already evident in the property or event name and it's not at all helpful. More code examples would also be very welcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e51cb8b-df29-177b-58b9-e1746a6aef77
* Version Independent ID: ee82d333-9130-97fc-c4e2-1e25aca9ab02
* Content: [CoreApplicationView.IsHosted Property (Windows.ApplicationModel.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.coreapplicationview.ishosted#Windows_ApplicationModel_Core_CoreApplicationView_IsHosted)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplicationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplicationview.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hi Amy, 

I’m am following up on this issue as it was recently reassigned to me. Thank you for taking the time to leave your honest feedback and I will follow up to see if we can clarify the explanation here. 

Nick

**Comment by knicholasa** [comment]
I've added clarifying language that will appear in the remarks section shortly.
