### ISSUE TITLE
The switch statement contains multiple cases with the label value '21'.

### ISSUE THREAD

**Issue by emyfreya** [MicrosoftDocs/winrt-api#327]
Hi, with the switch snippet, I got this error (in the title). The value 25 is also a duplicate. I was wondering if this was an error or normal ? Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf98772b-2d62-70f3-9a17-0e6bf58a236a
* Version Independent ID: d32568d4-d904-46e3-254d-43a240d2a37f
* Content: [VirtualKey Enum (Windows.System) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.virtualkey)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkey.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.virtualkey.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @JeremyFerreira - There is no snippet in the specified topic. Please reopen issue with valid link. Thanks.
