### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/winrt-api#328]
1- At the end of the Example paragraph words are missing and the link too.

2- It is great that the InputProcessor is demonstrated, but the usage is missing. I just noticed that the class is incompleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43ea939-a0e1-4e8b-9361-f650c7c803b2
* Version Independent ID: 2c4e8df2-b4eb-d8ea-6237-424160fa33d7
* Content: [GestureRecognizer Class (Windows.UI.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.gesturerecognizer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.gesturerecognizer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.gesturerecognizer.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! I've updated the topic with missing link, updated C# snippet, and link to related sample on GitHub.
