### ISSUE TITLE
Missing Link

### ISSUE THREAD

**Issue by 1wizkid** [MicrosoftDocs/winrt-api#331]
Text returns a Platform::String and I'd like to be able to click on that return type and read about it but it is not a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c270593-e21a-fe79-8d6d-e4a9ea5a3402
* Version Independent ID: 93f55bb2-1704-27f9-2276-85052a714a4b
* Content: [TextBox.Text Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.text#Windows_UI_Xaml_Controls_TextBox_Text)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
@mijacobs this seems like a doc system issue -- If you choose C++/CX then you see Platform::String. But this API isn't special. I'm not convinced that hyperlinking primitive types is right, but you guys should take a  look.

**Comment by mijacobs** [comment]
The property value type doesn't change to match the type of the currently selected language (it still says "string" when it's on C++/CX).

**Comment by mimisasouvanh** [comment]
This is related to the other GitHub issue:  https://github.com/MicrosoftDocs/winrt-api/issues/1084. I've created an [internal bug](https://ceapex.visualstudio.com/Engineering/_queries/edit/111640/?triage=true) to track. @mijacobs please close the issue.
