### ISSUE TITLE
GridUnitType link is broken

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#332]
Link goes to https://docs.microsoft.com/en-us/uwp/api/gridlength_gridunittype, which returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f021912e-813f-dff3-ed06-0ebfc17dbfa5
* Version Independent ID: a4ad2849-206a-28df-b2f8-e7b41f82993b
* Content: [GridLength Struct (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.GridLength)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.gridlength.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.gridlength.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
This link appears to be fixed.
