### ISSUE TITLE
BackgroundDownloader 4GB limit.

### ISSUE THREAD

**Issue by cattura** [MicrosoftDocs/winrt-api#333]
There is a 4GB limit issue the both for FAT and NTFS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c118de4-72f1-a3c9-1c9d-e3bb84e67a84
* Version Independent ID: fb4eae57-c653-1308-21a8-8311d16dfb2f
* Content: [BackgroundDownloader.CreateDownload Method (Windows.Networking.BackgroundTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgrounddownloader.createdownload#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloader.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @cattura, my apologies for the long delay in responding. I've reached out to the product team for info here and I'll report back and/or fix the topic when I get info. ~Steve

**Comment by stevewhims** [comment]
Hi, @cattura, I now have info from the product team. The 4GB limit is with the FAT, but not the NTFS, file systems. So, I've added a "Note" panel to the CreateDownload and CreateDownloadAsync methods to that effect. I'll go ahead and close this issue now. Please reopen if necessary, and thank you for the heads up on this omission from the docs! ~Steve
