### ISSUE TITLE
What are the available attribute names?

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/winrt-api#334]
A list of attributes we can request would be helpful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48708a58-0131-20fa-9a31-543f20d6a210
* Version Independent ID: f48d9fb3-d786-c5fe-abb5-2cf8d459a3e0
* Content: [AnalyticsInfo.GetSystemPropertiesAsync(IIterable<String>) Method (Windows.System.Profile) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.analyticsinfo.getsystempropertiesasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.analyticsinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.analyticsinfo.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Hi Morten, I currently have a request out to the dev team and will update the topic as soon as I have the info. Thanks!

**Comment by mhopkins-msft** [comment]
Supported values for the _attrbituesNames_ parameter are potentially endless. There are many providers that hook in and can expose arbitrary values. There a handful of known attributes that are likely to be supported. In most cases, these are case sensitive:  

App  
AppVer  
DeviceFamily  
FlightRing  
OSVersionFull  

The intention of this method is to use this information only for analytics and not rely on a particular value on the client. Support for these values will change over time.

**Comment by dotMorten** [comment]
@Xansky That's great, but how am I supported to discover these then? Is there an API that returns the ones that are available?

**Comment by mhopkins-msft** [comment]
Hi Morten, thanks for the feedback, I’ve forwarded your input to the feature team. We’ll consider making these attributes more discoverable in the future.

**Comment by rosero42** [comment]
Is there updated documentation for this API? I have found through guesswork that "DeviceId" returns a GUID value, but can't find anywhere what this Id is referring to, if it is unique among devices, if it changes based on user/publisher, etc.

It is not listed anywhere among the [documentation that I was able to find ](https://learn.microsoft.com/en-us/uwp/api/windows.system.profile.analyticsinfo.getsystempropertiesasync?view=winrt-22621)
