### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by PatrickFarley** [MicrosoftDocs/winrt-api#337]
in Remarks, it should be VisualElements.DisplayText. I assume that the VisualElements instance must then be set as a property of the UserActivity. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0c63ac-9941-e3ea-01ab-eaf4035980b8
* Version Independent ID: fc2a7eeb-469c-611a-3fb4-525b21c3821d
* Content: [UserActivity.SaveAsync Method (Windows.ApplicationModel.UserActivities) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.useractivities.useractivity.saveasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.useractivities.useractivity.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.useractivities.useractivity.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by TylerMSFT** [comment]
Fixed. Thanks for the heads-up.
