### ISSUE TITLE
Document BluetoothCacheMode

### ISSUE THREAD

**Issue by xmedeko** [MicrosoftDocs/winrt-api#339]
How are things cached? E.g. `BluetoothLEDevice.GetGattServicesAsync()` - is it cached per `BluetoothLEDevice` instance, per process or some kind of system cache per device? When the cache is flushed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ef1a204-e7f5-2424-d0d5-a3331de022dc
* Version Independent ID: 73aa1eba-bd66-d4fd-ac78-a3ac1d9f00fb
* Content: [BluetoothCacheMode Enum (Windows.Devices.Bluetooth) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothcachemode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothcachemode.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothcachemode.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jhp518** [comment]
Is anyone ever going to respond?

**Comment by stevewhims** [comment]
Hi, @xmedeko. Thanks for filing this issue, and my apologies for the long delay in responding.

I've updated the topic, and added info about caching behavior in **Remarks**.

Thanks again!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now. ~Steve

**Comment by xmedeko** [comment]
The Remark is perfect, @stevewhims thanks.

**Comment by stevewhims** [comment]
Great, thanks for confirming! :)
