### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by chcurlet-msft** [MicrosoftDocs/winrt-api#342]
Looks like the image of "Example background activity user prompt" is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a3bf8c-631d-e6fb-d3c2-d5cd8846d426
* Version Independent ID: 1a513aee-4103-b8c8-ed69-f573dcbcf7d2
* Content: [BackgroundExecutionManager.RequestAccessKindAsync(BackgroundAccessRequestKind, String) Method (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.backgroundexecutionmanager.requestaccesskindasync#Windows_ApplicationModel_Background_BackgroundExecutionManager_RequestAccessKindAsync_Windows_ApplicationModel_Background_BackgroundAccessRequestKind_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.backgroundexecutionmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.backgroundexecutionmanager.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by TylerMSFT** [comment]
Thanks for pointing that out. Fixed. 
The fix will go live around 5/9 or so (we are in freeze for Build 2018)
