### ISSUE TITLE
Add code example

### ISSUE THREAD

**Issue by nguyen-tam** [MicrosoftDocs/winrt-api#344]
Can you please add code example ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68d4eea1-7a60-70e4-d141-8cee4c14f061
* Version Independent ID: 264acc55-9b01-2a2c-e061-abafcf8e49c4
* Content: [CustomSystemEventTrigger Class (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.customsystemeventtrigger#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.customsystemeventtrigger.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.customsystemeventtrigger.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. What I can do is create an internal request for content and see if we can get a code example published in the article. The timeline for this may vary, so I will go ahead and close this and circle back with any updates. Please feel free to follow-up below with any additional feedback. Many thanks.
