### ISSUE TITLE
Clarification on loading ApplicationTheme from local storage

### ISSUE THREAD

**Issue by Ponant** [MicrosoftDocs/winrt-api#345]
The docs show briefly

"If you give the user an option to pick a theme that's part of app UI, you must save the setting in the app data and apply it when the app is restarted."

Any of my attempts to access local storage in the ctor of App.cs will crash the app with a message saying it is impossible to activate the store app as soon as I try to read or write using FileIO ReadtextAsync (or write). Could you please provide some hint? I used Getawaiter().GetResult() (will crash), and if I ConfigureAwait to false on those async methods the theme is ignored because the ctor does not wait obviously. Please advise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f25f17-cfcb-c9e5-4ba1-9fcf681290be
* Version Independent ID: 1ac80111-7675-3a55-10d2-f8b6eb038db8
* Content: [Application.RequestedTheme Property (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.requestedtheme#Windows_UI_Xaml_Application_RequestedTheme)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
Checkout how Windows Template Studio does it with their [ThemeService](https://github.com/Microsoft/WindowsTemplateStudio/blob/master/templates/Uwp/Features/ThemeSelection/Services/ThemeSelectorService.cs).  If you start a new blank template with just this service, you can see how they wired it in.

**Comment by jevansaks** [comment]
If the APIs don't work in the app constructor then we should recommend a better place to do it (e.g. OnLaunched). We'll try to clarify in the docs.

**Comment by chigy** [comment]
Assigning to Kiki since she is looking at theme and styles, etc.

**Comment by jwmsft** [comment]
Settings should be saved/retrieved using [ApplicationData.LocalSettings](https://docs.microsoft.com/uwp/api/windows.storage.applicationdata.localsettings), not FileIO. An example has been added to the doc.
