### ISSUE TITLE
DNS-SD is defined in RFC 6763, not 2782

### ISSUE THREAD

**Issue by wifiprintguy** [MicrosoftDocs/winrt-api#347]
DNS-SD is defined in RFC 6763 "DNS-Based Service Discovery", not RFC 2782 ("A DNS RR for specifying the location of services (DNS SRV)"). There is more to DNS-SD than just SRV records.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29b979a3-3057-4ba9-67db-22d7c6e340b5
* Version Independent ID: 64043af5-220c-bd65-e1d1-dd2950137706
* Content: [Windows.Networking.ServiceDiscovery.Dnssd Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.servicediscovery.dnssd.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.servicediscovery.dnssd.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Thanks, Smith! I've made that correction to the topic and I expect the update to go live within the next 24 hours. Please feel free to close this issue if you approve of the change. Thanks again, and sorry for the error! ~Steve

**Comment by wifiprintguy** [comment]
Thanks for addressing this!
