### ISSUE TITLE
Explanation of XAML grammar missing

### ISSUE THREAD

**Issue by BennyBread** [MicrosoftDocs/winrt-api#348]
Hi, the XAML grammar explanation how the StrokeDashArray works is missing. I only found it in the silverlight documentation. Can you import it to the current docu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3932022-b192-a26d-bcbf-22b65777ea84
* Version Independent ID: 184044b8-7637-ba11-713b-b96589a661ee
* Content: [Shape.StrokeDashArray Property (Windows.UI.Xaml.Shapes) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.shape.strokedasharray)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.shapes.shape.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.shapes.shape.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jesbis** [comment]
This was addressed by ade0226
