### ISSUE TITLE
Need documentation on the exceptions it could throw.

### ISSUE THREAD

**Issue by samsnowy** [MicrosoftDocs/winrt-api#349]
I was using this method with a SizeInt32 that has smaller width and height than INT32_MAX. However it failed with an exception "Exception thrown: 'System.ArgumentException' in ..., Value does not fall within the expected range.".
The actual size limit is more like 2^24 for CompositionVirtualDrawingSurfaces. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2b23322-1629-3ca2-672a-450f2b42c28e
* Version Independent ID: 3368317a-3d9f-58b1-c71a-843b46adb7b9
* Content: [CompositionGraphicsDevice.CreateVirtualDrawingSurface(SizeInt32, DirectXPixelFormat, DirectXAlphaMode) Method (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositiongraphicsdevice.createvirtualdrawingsurface)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositiongraphicsdevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositiongraphicsdevice.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by GrantMeStrength** [comment]
Sorry for the delay in getting to this. WinRT APIs are designed such that exceptions are intended to provide feedback during app development and should not be caught at runtime. This is why our convention is not to document exceptions for WinRT APIs. The exception type and message should be sufficient to let you know the necessary changes in your code.
