### ISSUE TITLE
Queries regarding the app focus and mouse pointer

### ISSUE THREAD

**Issue by prateekchandan** [MicrosoftDocs/winrt-api#353]
I have two questions before calling this method

1. Does the app which is calling this method needs to have foreground focus always ?
2. Since this is not coupled to mouse events, can we start drag operation from any place in the code no matter what the mouse position is ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee90c1fd-6ae2-694e-7131-b01fb369c8e4
* Version Independent ID: 923eab6c-56d0-0fc7-7aab-5f7d602e209c
* Content: [CoreDragOperation.StartAsync Method (Windows.ApplicationModel.DataTransfer.DragDrop.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.dragdrop.core.coredragoperation.startasync#Windows_ApplicationModel_DataTransfer_DragDrop_Core_CoreDragOperation_StartAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.dragdrop.core.coredragoperation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.dragdrop.core.coredragoperation.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. This GitHub repo is specifically for reporting documentation bugs. For product questions like this, please see the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).

I'm marking this issue as closed now, but please feel free to reopen it if you have more information that indicates a real doc bug here. Thanks again!
