### ISSUE TITLE
ToastNotification.Group property setter has undocumented maximum lengths

### ISSUE THREAD

**Issue by cgual206** [MicrosoftDocs/winrt-api#354]
There is a maximum length for strings assigned to the ToastNotification.Group which is undocumented.  On RS1 this is a 16 character maximum length.  Above RS1 it is 64 characters.  Calling the setter with a string that is too long will result in an exception. 

This should be documented.

See: [https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/8629408-max-length-of-toast-tag-not-enough-for-a-simple-gu](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/8629408-max-length-of-toast-tag-not-enough-for-a-simple-gu)

[ToastNotification.Group](https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification.group#Windows_UI_Notifications_ToastNotification_Group)

**Comment by hickeys** [comment]
This is documented in the Remarks section of the page.
