### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by hunkydoryrepair** [MicrosoftDocs/winrt-api#355]
Need information on how the content passes a string to the app. The "more info" link goes to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5e5f03-b5af-c5d5-aeb6-5048627754f7
* Version Independent ID: bbef25a3-6e9d-f557-5185-76318c7703fb
* Content: [WebViewControl.ScriptNotify Event (Windows.Web.UI.Interop) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.web.ui.interop.webviewcontrol.scriptnotify)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by erikadoyle** [comment]
Also added more details and another "see also" link per @hunkydoryrepair's helpful suggestion.
