### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by timkeo** [MicrosoftDocs/winrt-api#356]
First off, the property name is awful; it doesn't accurately indicate the data being returned. 

It returns the size of the numeric control's value, within the Data buffer of the HID report, in BITS (not bytes). It corresponds to the HIDP_VALUE_CAPS::BitSize field from the Win32 API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 419dbe97-5347-8054-fed9-af10692acf3e
* Version Independent ID: aaacd1ee-69c7-745b-bc68-b49a26c35bc3
* Content: [HidNumericControlDescription.ReportSize Property (Windows.Devices.HumanInterfaceDevice) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hidnumericcontroldescription.reportsize#Windows_Devices_HumanInterfaceDevice_HidNumericControlDescription_ReportSize)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hidnumericcontroldescription.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hidnumericcontroldescription.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! Again, I can't address the API name, but I was able to update numerous API topics.
