### ISSUE TITLE
API doesn't function as documented

### ISSUE THREAD

**Issue by timkeo** [MicrosoftDocs/winrt-api#357]
Cannot set this Property; returns ERROR_INVALID_DATA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0076e41-c587-5f48-216e-f2b98a09a03f
* Version Independent ID: f3168623-2507-b84a-f8e5-a3ae6736d5c4
* Content: [HidBooleanControl.IsActive Property (Windows.Devices.HumanInterfaceDevice) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hidbooleancontrol.isactive#Windows_Devices_HumanInterfaceDevice_HidBooleanControl_IsActive)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hidbooleancontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hidbooleancontrol.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback. THe description specifed "Retrieves", but I revised all property descriptions to "Gets".
