### ISSUE TITLE
Breaking change with Windows Mobile 1709 and MapControl

### ISSUE THREAD

**Issue by lolluslollus** [MicrosoftDocs/winrt-api#358]
I used to have an older version and it worked fine with a MapPolyline with over 10K points, overlayed to the MapControl. That wa smy tracking history. Now, after installing the update 1709 for Windows Phone, the app keeps crashing on start. The error goes way if I reset that polyline.

You must mention this sort of breaking changes in your docu. Better would be not to have them at all, but I understand the b est developers have long left for other companies.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e00175-951b-ebab-ec6f-f870f2ed4525
* Version Independent ID: e402b470-bb92-c372-fc2c-da83780d9ab9
* Content: [MapControl Class (Windows.UI.Xaml.Controls.Maps) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Maps.MapControl#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapcontrol.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by normesta** [comment]
Thank you for reaching out to us.  I've reached out to our engineers and have been told that there has been no changes to polyline handling an any recent Windows update. That said, there is a crashing issue related to startup that they are tracking and will likely be addressed in a servicing release for phone shortly. This might help with the issue that you are experiencing. Thank you for reporting.
