### ISSUE TITLE
Undocumented behavior

### ISSUE THREAD

**Issue by timkeo** [MicrosoftDocs/winrt-api#360]
Passing in a 0 for usagePage or usageId acts as a "wildcard" and will return any matching controls; passing in 0 for both parameters returns all controls.

Aside from being an obtuse design, which should instead be exposed through a separate API, this behavior isn't documented but yet is critical for most implementations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31cfbc96-b49d-8909-d10e-1bbbb9141025
* Version Independent ID: 33d4486d-7c2e-74ac-e8d0-97ab2eaf900a
* Content: [HidDevice.GetBooleanControlDescriptions(HidReportType, UInt16, UInt16) Method (Windows.Devices.HumanInterfaceDevice) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hiddevice.getbooleancontroldescriptions?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Devices.HumanInterfaceDevice.HidDevice.GetBooleanControlDescriptions)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! While I can't do anything about the API design, I have updated the relevant docs for the GetNumeric and GetBooleanControlDescriptions methods.
