### ISSUE TITLE
Undocumented behavior

### ISSUE THREAD

**Issue by timkeo** [MicrosoftDocs/winrt-api#361]
Passing in a 0 for usagePage or usageId acts as a "wildcard" and will return any matching controls; passing in 0 for both parameters returns all controls.

Aside from being an obtuse design, which should instead be exposed through a separate API, this behavior isn't documented but yet is critical for most implementations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69ae80d3-bd52-a6bb-90b7-b51c0e8b63f7
* Version Independent ID: 38fe55f5-f4e9-4044-cf09-cbb6206c8edc
* Content: [HidDevice.GetNumericControlDescriptions(HidReportType, UInt16, UInt16) Method (Windows.Devices.HumanInterfaceDevice) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hiddevice.getnumericcontroldescriptions)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! While I can't do anything about the API design, I have updated the relevant docs for the GetNumeric and GetBooleanControlDescriptions methods.
