### ISSUE TITLE
AppDiagnosticInfo link is broken

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/winrt-api#362]
Click the AppDiagnosticInfo link in the sentence: "Gets one or more AppDiagnosticInfo objects if the IsPackaged property is true."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfc5851d-2f34-e5ae-00f8-e3c20f4b077f
* Version Independent ID: aea55cae-b8e2-02c9-dcfb-124c1db53f2e
* Content: [ProcessDiagnosticInfo.GetAppDiagnosticInfos Method (Windows.System.Diagnostics) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.diagnostics.processdiagnosticinfo.getappdiagnosticinfos#Windows_System_Diagnostics_ProcessDiagnosticInfo_GetAppDiagnosticInfos)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.diagnostics.processdiagnosticinfo.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.diagnostics.processdiagnosticinfo.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Thanks for pointing this out. The link is fixed and will be republished ASAP.
