### ISSUE TITLE
UnauthorizedAccess inside subfolder which I have created in usb 

### ISSUE THREAD

**Issue by huiwenliuge** [MicrosoftDocs/winrt-api#363]
After pick a usb device by FolderPicker, and I create a folder(CreateFolderAsync) named xxx inside usb. I can only create file have the file types declared in xxx. It's a cool feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a933ac3d-5294-c291-1d73-3211fe1b3dac
* Version Independent ID: 71eaf3a6-3e0f-8c45-d724-1e73fde8b063
* Content: [KnownFolders.RemovableDevices Property (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.knownfolders.removabledevices#Windows_Storage_KnownFolders_RemovableDevices)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.knownfolders.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.knownfolders.yml&version=GBlive&_a=contents)
* Service: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
