### ISSUE TITLE
The link to the 'XAML GridView grouping and SemanticZoom sample' is outdated

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/winrt-api#365]
It was updated last in 2013 and it was built for WinRT. Can you update the link to point to the UWP sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9416308-b75a-5dd3-8ae3-dd3353ec0716
* Version Independent ID: 400dc357-919a-d177-3061-5778d34eae0d
* Content: [CollectionViewSource Class (Windows.UI.Xaml.Data) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Data.CollectionViewSource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.collectionviewsource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.collectionviewsource.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
This link has been updated to a newer sample. Thanks.
