### ISSUE TITLE
What is the valid range for the FreshnessTime

### ISSUE THREAD

**Issue by psivaram** [MicrosoftDocs/winrt-api#366]
What is the valid range for the FreshnessTime. What are the minimum and maximum value this can be set to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc8d4f5a-8a04-d2b2-965d-8addd1d46170
* Version Independent ID: 41a31739-d87f-82a1-67cf-e741fd882540
* Content: [MaintenanceTrigger.FreshnessTime Property (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.maintenancetrigger.freshnesstime#Windows_ApplicationModel_Background_MaintenanceTrigger_FreshnessTime)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.maintenancetrigger.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.maintenancetrigger.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by urjapatel** [comment]
Why this issue has not been answered yet ? 
For my Application, I need to know maximum Freshness Time .
In my application, when i Set Freshness Time to 43,200 Minutes(i.e 30days * 24hours* 60minutes) it throws exception, 

System.ArgumentException: Value does not fall within the expected range.
   at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()

How do i Solve this? I want to know the maximum time limit as soon as possible.

**Comment by TylerMSFT** [comment]
@urjapatel - sorry this is taking so long. I left the Windows team some time ago and am looking for the new owner for this issue.

**Comment by knicholasa** [comment]
I've added clarifying language to the document. Changes should be visible in a day or two.
