### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by brabebhin** [MicrosoftDocs/winrt-api#368]
This page would be a lot more useful if we saw a sample of each color. I really don't think it is that hard to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8443d66a-2f59-9d31-5d6f-ca1f3e8438c7
* Version Independent ID: bcb2374c-572b-ecb4-d989-0cd1f300e3cf
* Content: [Colors Class (Windows.UI) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.colors)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.colors.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.colors.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Color sample image was added to this page.
