### ISSUE TITLE
Print complete document in UWP HTML5 app

### ISSUE THREAD

**Issue by Shailu4u** [MicrosoftDocs/winrt-api#37]
MSApp.getHtmlPrintDocumentSourceAsync(document).then(function (source) {          
      args.setSource(source);  
});

The above code is not working for printing the complete document if document content is more than one page.

**Comment by mattwojo** [comment]
Hmm -- thanks for bringing this to our attention @Shailu4u. Could you please help me to better understand the context of where you are finding this guidance? Is there a documentation page you could share the URL for? 

Have you looked at this guidance for printing from UWP apps on Windows 10? https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/print-from-your-app

**Comment by mattwojo** [comment]
Ahh, just found this: 
"getHtmlPrintDocumentSource is a synchronous deprecated API in Windows 10 apps."

For a more recent code sample on how to print, check out https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing/js

This comes from [StackOverflow](http://stackoverflow.com/questions/33575686/how-do-you-use-gethtmlprintdocumentsourceasync-to-print-in-html-javascript-windo/33636254#33636254), which shares a code sample, as well as a sample that can be found in this older [GH issue](https://github.com/Microsoft/Windows-universal-samples/issues/201).  Please let me know if this addresses your issue... and also, if you found that depricated code in any of our currently live documentation, please let me know and I'll find someone to update it. Thanks again @Shailu4u

**Comment by mattwojo** [comment]
Haven't heard anything further, so closing this issue out.
