### ISSUE TITLE
InvokedItem is not consistent 

### ISSUE THREAD

**Issue by NicolasG3** [MicrosoftDocs/winrt-api#371]
InvokedItem is initialized with NavigationViewItem for settings or NavigationViewItem.Content string otherwise.
Content is supposed to be localized and this can't be reliable to code navigation logic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb5d73f1-f61b-6d23-f178-1a0058764d98
* Version Independent ID: 3fdd8311-597d-7e1a-b2f5-1bdb177ecb3a
* Content: [NavigationViewItemInvokedEventArgs Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationviewiteminvokedeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewiteminvokedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewiteminvokedeventargs.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by devmikew** [comment]
I agree. Or at least the inconsistent action should be clearly documented.

Better would be to always return the item actually clicked on, the NavigationViewItem itself and not its content which could be any thing whatsoever, not only a string.

**Comment by tenerion** [comment]
Same here, i can reproduce it. 
As an quick work around, i give the "NavigationViewItem" an x:Name="test" then we can use FocusState to check
If Not test.FocusState = FocusState.Unfocused Then ContentFrame.Navigate(GetType(test))

**Comment by jevansaks** [comment]
Yes, this was a mistake in the API. In 1809 (17763) we added the InvokedItemContainer property to let you get the container to read more state from the clicked item (e.g. Tag) for navigation. Please give that a try?
