### ISSUE TITLE
Replace link to msdn (and Windows 8.x description) with link to Win 10 docs page.

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/winrt-api#372]
In the "Remarks" section, in the sentence "To learn about using the FutureAccessList and MostRecentlyUsedList, see How to track recently used files and folders.", the hyperlink "How to track recently used files and folders." opens a page on msdn with description based on Windows 8.x. (The actual link is: http://msdn.microsoft.com/library/7062d754-877e-4e59-a1ff-be0603020e6c)

Proposed change:
Replace the hyperlink with "https://docs.microsoft.com/en-us/windows/uwp/files/how-to-track-recently-used-files-and-folders" which points to the correct description for Windows 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e7379a-623f-ad01-9a39-cd417f8fe985
* Version Independent ID: 4b209cc6-7a16-252c-9830-e2effc336c84
* Content: [StorageApplicationPermissions Class (Windows.Storage.AccessCache) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageapplicationpermissions)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageapplicationpermissions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageapplicationpermissions.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by laurenhughes** [comment]
@Felix-Dev, thanks for letting us know! The updated links will be live tomorrow.

**Comment by adrientetar** [comment]
@ginami @laurenhughes The link still points to Windows 8 documentation, please reopen this ticket.
