### ISSUE TITLE
Is it necessary to mention Windows 8.x API specifics in the UWP FileOpenPicker API documentation?

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/winrt-api#373]
While this might easily be a discussion point for the whole UWP API documentation, I want to address the FileOpenPicker UWP API documentation specifically.

In the "Remarks" section, we have the sentence "To learn about using file pickers in Windows Phone 8.x app, see How to continue your Windows Phone app after calling a file picker." followed by an "Important" section which focuses entirely on Windows 8.x and how to use the FileOpenPicker API on such devices. 

I don't see why this infomation should be mentioned in the FileOpenPicker UWP API documentation, as an UWP app will never deploy on Windows 8.x devices, therefore rendering these remarks useless for UWP developers. 
I could imagine cases where it might makes sense to highlight differences between the UWP API and Windows 8.x APIs, but I don't see why this should be the case here. In fact, the remarks section reads "Therefore, if your app will deploy only on Windows 8.1, you can ignore the EnsureUnsnapped function and calls to it in this topic's example code." which is of absolute no concern to UWP developers.

Therefore, I propose to cut the Windows (Phone) 8.x specific information in the "Remarks" section entirely to remove unnecessary information for the intended audience - UWP developers.

I'm looking forward to hearing from the docs teams about their opinions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c219be13-bd93-5764-00c0-0fdb8e382e58
* Version Independent ID: 9a524a3d-bfe3-1f17-e0dc-5c8594fa9121
* Content: [FileOpenPicker Class (Windows.Storage.Pickers) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.fileopenpicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.fileopenpicker.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for implementing the changes! It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
