### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by davefxy** [MicrosoftDocs/winrt-api#374]
A number of the links to sample code are deprecated because they refer to older unsupported windows versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd775516-0dbb-737e-02f3-ea1312439f3e
* Version Independent ID: fa11347c-63e6-f970-d3af-7483a79b185a
* Content: [Image Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Image)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by julienshepherd** [comment]
Setting the image source through code by setting the Uri keeps the file opened, at least when you use a ms-appdata uri like ms-appdata:///local/myImage.png. If the file is opened, you cannot replace it, even in another page. I think it would be helpful to mention this detail in the docs.

**Comment by jevansaks** [comment]
This issue is old so this may have been fixed, but can you be more specific? I chased a bunch of the links to samples and they all worked for me.
