### ISSUE TITLE
[Question] how to fill svg with any color when using SvgImageSource in xaml? 

### ISSUE THREAD

**Issue by HppZ** [MicrosoftDocs/winrt-api#375]
I don't want to have two same shaped svg files with different colors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599d6bb6-58f6-b711-8053-197daed6e639
* Version Independent ID: 8c42983d-6ecc-116c-58c9-dfb0abedc73f
* Content: [SvgImageSource Class (Windows.UI.Xaml.Media.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.svgimagesource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.svgimagesource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.svgimagesource.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stefangavrilasengage** [comment]
Also interested in an answer.

**Comment by jesbis** [comment]
SvgImageSource doesn't support dynamically changing colors. You would need to create different files, or you could potentially load the file into an in-memory stream and update its contents before loading it into an SvgImageSource.

This seems like a reasonable idea for a new feature: please feel free to open a new feature suggestion for the Xaml platform in the Windows UI Library repo:  
https://github.com/microsoft/microsoft-ui-xaml
