### ISSUE TITLE
There is an error in the example

### ISSUE THREAD

**Issue by JuniperPhoton** [MicrosoftDocs/winrt-api#376]
The "cubicBezier” created by compositor is never used, which should be passed in "InsertKeyFrame" as the third param.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89d252bc-e777-2d95-c89a-9294822698e9
* Version Independent ID: 15a4426c-0447-4b93-8d82-f4daa5a0b0f0
* Content: [CubicBezierEasingFunction Class (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.cubicbeziereasingfunction)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.cubicbeziereasingfunction.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.cubicbeziereasingfunction.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for pointing this out. It's fixed.
