### ISSUE TITLE
This is not correct

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#379]
The sample app sets some md file which is not an image: https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/UserActivity/cs/Scenario2_AdvancedUserActivity.xaml.cs

Setting image URI whether local or web does nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56987970-924d-14df-0dc3-c18c318366c2
* Version Independent ID: af1b552c-41c7-d430-c3db-bb888b57affa
* Content: [UserActivity.ContentUri Property (Windows.ApplicationModel.UserActivities) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.useractivities.useractivity.contenturi#Windows_ApplicationModel_UserActivities_UserActivity_ContentUri)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.useractivities.useractivity.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.useractivities.useractivity.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hi Ivan,

I’m am following up on this issue as it was recently reassigned to me. I'll pass along your feedback to the team that maintains the code.

Nick

**Comment by sphenry** [comment]
@ivanicin what were you expecting to happen when you set the ContentUri to an image URI?

If you want an image to show up in, e.g. Timeline, you have to set it in the VisualElements.Content property. Check our scenario 3 in the same sample.

**Comment by ghost** [comment]
@sphenry personally I don’t expect anything. You need to ask the author of the documentation linked above what where his expectations when he wrote that as I can hardly assume and speak for him.

**Comment by sphenry** [comment]
@ivanicin the contentUri is used to specify a URI to the document that backs the activity. This is used, for example, if there is an alternate handler for a document when the activity it resumed. In sample code linked, this would be if the UserActivity is resumed on machine where the sample app was not installed, but there was a handler for .md files. 

I think the documentation is correct.

**Comment by ghost** [comment]
This issue is attached to this document: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.useractivities.useractivity.contenturi#Windows_ApplicationModel_UserActivities_UserActivity_ContentUri and if you look what it says it is quite contrary to what you say.

**Comment by sphenry** [comment]
Ah, thanks @ivanicin , I've created a PR to update the docs you linked.

https://github.com/MicrosoftDocs/winrt-api/pull/851
