### ISSUE TITLE
What do you mean by 'restarted'? 

### ISSUE THREAD

**Issue by mdmozibur** [MicrosoftDocs/winrt-api#380]
Say I have a timer of interval 200 millisecond, I started it and then stopped it after 150 millisecond. If I again start it, does it give the next tick after 50 millisecond or 200 millisecond?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2268034-f5b5-3453-4c82-7e3f4cdfe4a7
* Version Independent ID: 983e7e95-56d3-baaf-16e4-1af075d7af4f
* Content: [DispatcherTimer.Start Method (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dispatchertimer.start#Windows_UI_Xaml_DispatcherTimer_Start)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.dispatchertimer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.dispatchertimer.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
@MuziburRahman,  restarted means it starts at the beginning again. In your example, the next tick would happen after 200 milliseconds.
