### ISSUE TITLE
Clicking "InputInjector" above the sample code results in 404

### ISSUE THREAD

**Issue by ryzngard** [MicrosoftDocs/winrt-api#381]
"First, we call TryCreate to instantiate the InputInjector object." 

"InputInjector" is a link to https://docs.microsoft.com/api/windows.ui.input.preview.injection.inputinjector, which is a 404 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e90ec2f6-ac5a-76ec-39bb-2d533e8c2368
* Version Independent ID: fd21148a-bb8a-a6ec-6cef-400067eacea8
* Content: [Windows.UI.Input.Preview.Injection Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.preview.injection#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.preview.injection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.preview.injection.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the head's up! I've corrected the broken link and published the update.
