### ISSUE TITLE
Several entries here say "See Remarks" - but there is no remarks section.

### ISSUE THREAD

**Issue by ShawnSteele** [MicrosoftDocs/winrt-api#382]
Several entries here say "See Remarks" - but there is no remarks section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f534c09-9d09-53a2-6dff-d0e5a1676b84
* Version Independent ID: f2007185-dd9a-931d-63ec-97651bc8fd49
* Content: [Calendar Constructor (Windows.Globalization) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.calendar.-ctor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.calendar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.calendar.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Thanks for the report, Shawn. I've just checked in a fix, I expect it to show up on the live site within 24 hours. Please close this issue once you're ready. Thanks! ~Steve

**Comment by stevewhims** [comment]
@ShawnSteele, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Comment by ShawnSteele** [comment]
I think “remarks” should be the highlighted link.  If I scroll up to the “calendar” entry, there’s nothing under “calendar” that says “remarks” – I actually have to click on the calendar.  Clearly I missed all that before.

**Comment by stevewhims** [comment]
Ok, cool, and I've also just pushed a change to link directly to the "Remarks" bookmark on the page. I think that's better than it was before. I'll leave this open for a while and come back and close it later. ~Steve

**Comment by stevewhims** [comment]
Well, that change that I pushed actually caused the link to stop working. I had been hoping to link directly to the Remarks bookmark, but in the end I reverted back to just linking to the parent topic and asking the reader to look at the Remarks section. That seems to work well. I'll close this now, but please reopen if necessary. Thanks again for the heads up with this issue! ~Steve
