### ISSUE TITLE
SpeechRecognizer.Constraints

### ISSUE THREAD

**Issue by tcorbet** [MicrosoftDocs/winrt-api#383]
Either the documentation is defective or the implementation of Constraints is defective.
The documentation indicates that this Property may be used to get an IList of the ISpeechRecognitionConstraints "associated with" [I take that to mean" currently-added to"] the SpeechRecognizer.  The PropertyValue paragraph goes on to describe the four specific types of Constraints, but when one obtains the aforesaid list, there is no item for a SpeechRecognitionTopicConstraint, even when one has been added and compiled without any report of failure.

Every ISpeechRecognitionConstraint has an IsEnabled Property which may be set.  How can the IsEnabled Property of the SpeechRecognitionTopicConstraint item be reset if it cannot be fetched from the SpeechRecognizer.

I suspect that this problem is what the tech writer had in mind by stating that only List and GammarFile types of constraints "can be mixed in the same collection," but if that is what is meant, the documentation and/or the implementation are in need of a redesign/fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13822e12-78f0-4145-d97c-13209ec97b98
* Version Independent ID: f9e69660-6543-f751-8303-035326f8e217
* Content: [SpeechRecognizer.Constraints Property (Windows.Media.SpeechRecognition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognizer.constraints)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechrecognition.speechrecognizer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechrecognition.speechrecognizer.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! I've updated the topic with more detail from a related conceptual topic we updated last year.
