### ISSUE TITLE
I got a value 5 as MediaFrameSourceKind.

### ISSUE THREAD

**Issue by gaotian1710** [MicrosoftDocs/winrt-api#384]
I executed the following codes in a classic desktop app with C++/WinRT.
	winrt::Windows::Foundation::Collections::IVectorView<MediaFrameSourceGroup> mfsgs = MediaFrameSourceGroup::FindAllAsync().get();
	for (MediaFrameSourceGroup mfsg : mfsgs)
	{
		for (MediaFrameSourceInfo sourceInfo : mfsg.SourceInfos())
		{
			int32_t st = (int32_t)sourceInfo.MediaStreamType();
			int32_t sk = (int32_t)sourceInfo.SourceKind();
			wprintf(L"%ws,%d,%d\n", sourceInfo.Id().c_str(), st, sk);
		}
	}

I got the results as follows.
Source#0@\\?\USB#VID_04F2&PID_B477&MI_00#6&acf2fb5&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global,1,1
Source#1@\\?\USB#VID_04F2&PID_B477&MI_00#6&acf2fb5&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global,3,5
Source#0@\\?\USB#VID_058F&PID_3841&MI_00#7&f92ef9&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global,1,1
Source#1@\\?\USB#VID_058F&PID_3841&MI_00#7&f92ef9&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global,3,5
Source#0@\\?\USB#VID_058F&PID_3841&MI_00#7&29da485b&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global,1,1
Source#1@\\?\USB#VID_058F&PID_3841&MI_00#7&29da485b&0&0000#{e5323777-f976-4f5b-9b55-b94699c46e44}\global,3,5

The right most numbers are MediaFrameSourceKind. Value 5s conflict to the description in this page. What were wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39dbb56a-9c90-2380-460e-8903c7553226
* Version Independent ID: 09689490-907d-39c7-fadd-37dcfe48f000
* Content: [MediaFrameSourceKind Enum (Windows.Media.Capture.Frames) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframesourcekind)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.frames.mediaframesourcekind.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.frames.mediaframesourcekind.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
The value of 5 was added to the enumeration in the latest release. This value indicates that the frame contains image data. The reference documentation has been updated with this information. Thank you for your feedback.
