### ISSUE TITLE
DownloadsFolder docs need improvements/more details/examples

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/winrt-api#386]
This issue is created by @michael-hawker from https://github.com/MicrosoftDocs/feedback/issues/260

Any files created will always be put in a subfolder for the specific app, but this behavior isn't specified anywhere in the docs. This is apparently to avoid collisions with other apps...
There's also no examples of using the Create*ForUser functions (and the User documentation doesn't have any examples of how to get the current user (e.g. from the App OnLaunched event) or otherwise) or that passing null in will act as the current user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f2d3f7-4957-8516-7c08-6de419513d61
* Version Independent ID: 96b643e0-8d68-751a-d01e-2cbda06ac2fc
* Content: [DownloadsFolder Class (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.downloadsfolder)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.downloadsfolder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.downloadsfolder.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
@laurenhughes @Powerhelmsman any update on this issue?

**Comment by hkhmsft** [comment]
Hi @michael-hawker and @Powerhelmsman , I'm currently assigned to this Issue and wanted to follow-up with the progress of these updates. Is this still needed? Let me know and I can create a work item to drive this to completion. Many thanks.

**Comment by michael-hawker** [comment]
Thanks @lastnameholiu, I think it'd be good for the docs to be a bit clearer here and provide a bit more detail. If there are already existing samples somewhere, just linking to them would be great.

**Comment by ptorr-msft** [comment]
The basic problem is that there should be a `downloadsFolder` capability that grants access to the real folder for browsers and such, but for whatever reason it never got implemented. The current solution is designed to enable apps to occasionally download things without specific prompts etc.

**Comment by GrantMeStrength** [comment]
Adding this item to our team backlog.

https://dev.azure.com/ceapex/Windows%20Dev%20Content/_workitems/edit/400618

**Comment by michael-hawker** [comment]
@GrantMeStrength I understand some teams have internal boards, but there's been no movement on that issue. It'd be good to leave the GitHub issue open until the doc has been updated. Otherwise it's hard for others to know when the issue has been resolved and discover the existing issue when looking at the existing content.
