### ISSUE TITLE
I could not link the program when I used properties, Denominator() and Numerator() in C++ classic desktop with C++/WinRT

### ISSUE THREAD

**Issue by gaotian1710** [MicrosoftDocs/winrt-api#388]
I created the project with the template, "Windows Console Application (C++/WinRT)".
I successfully compiled the program with Denominator() and Numerator() but could not linked because of unresolved external. Which library should I link? I confirmed "WindowsApp.lib" in linker input.
I could successfully got MediaFrameFormat::MajorType(), MediaFrameFormat::SubType(), MediaFrameFormat::FrameRate(), etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7847cc32-ec9c-98b1-3211-655a166b0e9f
* Version Independent ID: 8f4b94a9-97eb-6c8f-4489-e743aa16dad9
* Content: [MediaRatio Class (Windows.Media.MediaProperties) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.mediaratio)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.mediaratio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.mediaratio.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Hello, I reached out to the developers for this feature and they have provided the following response:

Winrt uses headers to figure our how to call into com if you are missing an include you will get a link error.  Validated code works with the following includes, likely highlighted one was missing.

#include <winrt\Windows.Media.h>
#include <winrt\Windows.Media.MediaProperties.h>
#include <winrt\Windows.Media.Core.h>
#include <winrt\Windows.Media.Capture.h>
#include <winrt\Windows.Media.Capture.Frames.h>
