### ISSUE TITLE
Setting the image source through code with a URI keeps the source file opened.

### ISSUE THREAD

**Issue by julienshepherd** [MicrosoftDocs/winrt-api#389]
Setting the image source through code by setting the Uri keeps the file opened, at least when you use a ms-appdata uri like ms-appdata:///local/myImage.png. If the file is opened, you cannot replace it, even in another page. You get a FileLoadException telling you the file is used by another process. I think it would be helpful to mention this detail in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd775516-0dbb-737e-02f3-ea1312439f3e
* Version Independent ID: fa11347c-63e6-f970-d3af-7483a79b185a
* Content: [Image Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Image#setting-imagesource-using-code)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.image.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by jesbis** [comment]
This appears to be a bug - opened an issue to track it here:  
Microsoft/microsoft-ui-xaml/issues/633
