### ISSUE TITLE
Examples and Exceptions

### ISSUE THREAD

**Issue by TobiVanHelsinki** [MicrosoftDocs/winrt-api#392]
I am stuck with this method. It throws an UnauthorizedAccessException with no further Information. Please provide a complete description of Exceptions here. Also some examples and Remarks of how the Text should be formated and what the TextSetOptions means in Detail would be very nice. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f50d12fd-e218-5172-c08a-74d052011c05
* Version Independent ID: cb5f38c3-0f85-e2f0-df50-72c0903d3f5a
* Content: [ITextDocument.SetText(TextSetOptions, String) Method (Windows.UI.Text) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.text.itextdocument.settext#Windows_UI_Text_ITextDocument_SetText_Windows_UI_Text_TextSetOptions_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.text.itextdocument.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.text.itextdocument.yml&version=GBlive&_a=contents)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @wdg-dev-content
* Microsoft Alias: **wdg-dev-content**

**Comment by GrantMeStrength** [comment]
Sorry for the delay in getting to this. WinRT APIs are designed such that exceptions are intended to provide feedback during app development and should not be caught at runtime. This is why our convention is not to document exceptions for WinRT APIs. The exception type and message should be sufficient to let you know the necessary changes in your code.
