### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by ChimeraScorn** [MicrosoftDocs/winrt-api#395]
What units is delay in?  ms?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f26acd85-4f70-4bca-d1c0-0524e2f4cbd9
* Version Independent ID: 8235b8ad-1bd1-514f-5b3c-9ed425911c61
* Content: [EchoEffectDefinition.Delay Property (Windows.Media.Audio) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.audio.echoeffectdefinition.delay)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.echoeffectdefinition.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.echoeffectdefinition.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Yes, this value is in milliseconds. The API reference page for this property has been updated to include this information. Thank you for your feedback!
