### ISSUE TITLE
`BackgroundExecutionManager.RequestAccessAsync`: What does "Package Relative Application ID" mean?

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#396]
Here are some questions that the documentation for the `BackgroundExecutionManager.RequestAccessAsync(String applicationId)` API should answer:
  1. The `applicationId` parameter is described as the "Package Relative Application ID". What is a "Package Relative Application ID"? After **a lot** of searching I found out from [this page](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-application#attributes) that it is the value of the `Id` attribute of the `Application` element in the `Package.appxmanifest`. The doc for this page should make it easier to jump to documentation on "Package Relative Application ID".
  2. If I call this API from a PPLE because I want to register a background task to be run in my PPLE, what value should I pass for `applicationId`?

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87a7208c-98b2-9368-578d-8d7108416447
* Version Independent ID: d2e8925a-af0b-0793-cba7-2438b8cc9684
* Content: [BackgroundExecutionManager.RequestAccessAsync Method (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.backgroundexecutionmanager.requestaccessasync#Windows_ApplicationModel_Background_BackgroundExecutionManager_RequestAccessAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.backgroundexecutionmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.backgroundexecutionmanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Thanks for the issue, @rigdern. My fix for #1 should be live on Monday morning. Now that I've made contact with you internally, let's work on #2 in-house over email and I'll fix the docs if/when I get that info. Meanwhile, I'll close this issue.

Thanks!
Steve
