### ISSUE TITLE
Not clear exactly what the purpose of this method is

### ISSUE THREAD

**Issue by butaud** [MicrosoftDocs/winrt-api#397]
It seems likely based on the sample code that it calls the output stream's FlushAsync() but I'm not 100% sure of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc07c8a-2e30-7709-58ef-b1551b860877
* Version Independent ID: c456d59f-3c1b-3c58-02ab-906848e780cb
* Content: [DataWriter.FlushAsync Method (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datawriter.flushasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datawriter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datawriter.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
