### ISSUE TITLE
Interaction with Size

### ISSUE THREAD

**Issue by jason-ha** [MicrosoftDocs/winrt-api#398]
Effective size of Visual is found by add Size and RelativeSizeAdustment combined with Parent Visual's effective size.
  Effective_Size = Size + (RelativeSizeAdjustment * Parent.Effective_Size)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16915ef7-ddc3-05a9-1ca3-5caec13ece08
* Version Independent ID: 0c3d52ac-2294-e634-e915-fc96599351b9
* Content: [Visual.RelativeSizeAdjustment Property (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.visual.relativesizeadjustment)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.visual.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.visual.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks. This information has been added to the docs.
