### ISSUE TITLE
It's impossible to tell which one is the default

### ISSUE THREAD

**Issue by ktschau** [MicrosoftDocs/winrt-api#399]
A user would probably assume "Default" is the default, but that's not true anymore. Can we point that out? It's quite confusing otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ae5afc1-3e8e-8921-bd7b-1644eec4736f
* Version Independent ID: 89575f7e-d002-9dd3-d397-bbb1f2bf14a1
* Content: [TextReadingOrder Enum (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.textreadingorder#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.textreadingorder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.textreadingorder.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
Agree, this is very confusing because TextBlock.TextReadingOrder's default is not TextReadingOrder.Default. We should probably make it clear in the docs that Default shouldn't be used anymore.

**Comment by marb2000** [comment]
Agree. Adding some clarifications and sending a PR.

**Comment by jwmsft** [comment]
Documentation has been updated.
