### ISSUE TITLE
One more column with color sample required 

### ISSUE THREAD

**Issue by ArtjomP** [MicrosoftDocs/winrt-api#401]
I would like to see color sample for every color in the table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8443d66a-2f59-9d31-5d6f-ca1f3e8438c7
* Version Independent ID: bcb2374c-572b-ecb4-d989-0cd1f300e3cf
* Content: [Colors Class (Windows.UI) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.colors)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.colors.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.colors.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Color sample image was added to this page.
