### ISSUE TITLE
Request to add header file info

### ISSUE THREAD

**Issue by raghatns** [MicrosoftDocs/winrt-api#405]
Please add header and library file info to use AddProfileFromXmlAsync().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87f985ff-f01d-6aea-4c10-e97a1332e6a2
* Version Independent ID: 249fc7a4-5f86-87e0-a4f6-293510012e37
* Content: [VpnManagementAgent.AddProfileFromXmlAsync(String) Method (Windows.Networking.Vpn) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.vpnmanagementagent.addprofilefromxmlasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnmanagementagent.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.vpnmanagementagent.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @raghatns, thanks for filing this issue! If you're using C++/WinRT, then whenever you want to use a type from a Windows namespaces, include the corresponding C++/WinRT Windows namespace header file. In this case that'd be #include <winrt/Windows.Networking.Vpn.h>. Then you'd access the winrt::Windows::Networking::Vpn::VpnManagementAgent type. You can of course use using namespace directives to save you fully-qualifying. For more info, see https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started. If you're using C++/CX, then you don't need to include any header files. Static-link libs are not something you need to think about with C++/WinRT (nor C++/CX). I hope this resolves the issue. If so, please close the issue when you're ready. Thanks! ~Steve

**Comment by raghatns** [comment]
Hi Steve,
Thank you. 
What is the minimum visual studio version requirement to use "VpnManagementAgent.AddProfileFromXml" c++/CX ?  we are using visual studio 14.0
Thanks,
Raghavendra

**Comment by stevewhims** [comment]
Hi, @raghatns, Visual Studio 14, or "Dev14" (its product name is Visual Studio 2015) supports Windows 10 (Universal Windows Platform) development, which includes writing UWP apps with C++/CX. The VpnManagementAgent type was added with the first release of Windows 10. So I would expect you to be able to access that type from C++/CX using your toolchain. For more info on using VS 2015 with Win10, please see https://msdn.microsoft.com/en-us/library/dn975273.aspx. ~Steve

**Comment by stevewhims** [comment]
@raghatns, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
