### ISSUE TITLE
XAML code examples are invisible

### ISSUE THREAD

**Issue by ThomasKramer** [MicrosoftDocs/winrt-api#41]
On many pages the `XAML` code examples are invisible. They exist in the source code of the page, but they have the `hidden` attribute applied.

<img width="796" alt="bug" src="https://cloud.githubusercontent.com/assets/2312745/24064435/c04c91ae-0b64-11e7-857a-eeda1a838e6a.png">

See for example:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.flipview#examples
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.grid#examples

I suspect this affects all samples that are embedded using `[!code-xml]` syntax.

Samples using ` ```xaml` are unaffected.

**Comment by mattwojo** [comment]
Thanks @ThomasKramer. I just checked in with our engineering team -- they are aware of this issue and working to resolve it. Should be fixed soon. (Bug 941611)  Thanks again for bringing this to our attention and please continue to file issues if you find anything further.

**Comment by mattwojo** [comment]
*Kevin - assigning this to you and keeping it open until the team has it resolved. Thanks!

**Comment by kevinyr** [comment]
This issue should now be resolved.
