### ISSUE TITLE
Id property description

### ISSUE THREAD

**Issue by chrisn** [MicrosoftDocs/winrt-api#410]
The `Id` property is currently described as "for the timed metadata track"; should this not be "of the cue"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 955367d8-ceaa-d9f1-960b-27b77a7f1d0f
* Version Independent ID: 507e73f5-e6b1-2e23-d966-635dafb7c917
* Content: [DataCue.Id Property (Windows.Media.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.datacue.id)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.datacue.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.datacue.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
This typo has been corrected. Thank you for bringing this issue to our attention.
