### ISSUE TITLE
What is the return value if the container is not found?

### ISSUE THREAD

**Issue by kliffy542** [MicrosoftDocs/winrt-api#411]
It would be nice to know what the return value is when the container is not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc7d1b9-d40f-3f4e-11ce-8dd040da095e
* Version Independent ID: 127f5081-0f4e-01b4-a3e8-07a0de678c93
* Content: [IItemContainerMapping.IndexFromContainer(DependencyObject) Method (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iitemcontainermapping.indexfromcontainer#Windows_UI_Xaml_Controls_IItemContainerMapping_IndexFromContainer_Windows_UI_Xaml_DependencyObject_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.iitemcontainermapping.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.iitemcontainermapping.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The docs have been updated with this information. (Returns -1 if container is not found.)
