### ISSUE TITLE
Unable to find definition for ITappedRoutedEventArgs

### ISSUE THREAD

**Issue by RobMeyer** [MicrosoftDocs/winrt-api#414]
TappedRoutedEventArgs seems to inherit from ITappedRoutedEventArgs, but there's no documentation on ITappedRoutedEventArgs. None of the methods or properties on this type seem to be inherited from that interface either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2547151f-9111-8919-d869-aaca409da70b
* Version Independent ID: 62db4d2e-42ac-b630-6a6d-0f0f64c65bfe
* Content: [TappedRoutedEventArgs Class (Windows.UI.Xaml.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.tappedroutedeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.tappedroutedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.tappedroutedeventargs.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi RobMeyer, ITappedRoutedEventArgs is not a public interface.

The TappedRoutedEventArgs Class inherits from both ITappedRoutedEventArgs and RoutedEventArgs. Only the OriginalSource property is inherited from RoutedEventArgs. All other members are inherited from ITappedRoutedEventArgs.
