### ISSUE TITLE
More information (e.g. hyperlinks) needed about "the resources system."

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/winrt-api#419]
This article ends with this sentence: "If you want to use different FontSize values for different scalings, you can do this using the resources system." but it provides no further information about "the resources system" or how you would adjust the font size for scalings with it.  Is there other documentation or examples about this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3bb443-de6b-4685-d7d2-1a05ddbdc651
* Version Independent ID: a4423b12-411a-7c35-5af1-d61a1bdf53c5
* Content: [Control.FontSize Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.fontsize#Windows_UI_Xaml_Controls_Control_FontSize)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The doc has been updated with links to more information.
