### ISSUE TITLE
The link for "UX guidelines for layout and scaling" just takes you to a generic design overview page

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/winrt-api#420]
It seems like it was intended to take you to a specific page about guidelines for layout and scaling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb3bb443-de6b-4685-d7d2-1a05ddbdc651
* Version Independent ID: a4423b12-411a-7c35-5af1-d61a1bdf53c5
* Content: [Control.FontSize Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.fontsize#Windows_UI_Xaml_Controls_Control_FontSize)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
Agreed, maybe this meant to go to https://docs.microsoft.com/en-us/windows/uwp/design/layout/?

**Comment by YuliKl** [comment]
Thank you for reporting, we've updated the links.
