### ISSUE TITLE
Registering a delegate to handle an event (BluetoothLE)

### ISSUE THREAD

**Issue by robson31** [MicrosoftDocs/winrt-api#421]
This question is regarding [this event](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher.received). I would appreciate any help, since I can't get it to work.

I'm having trouble registering a delegate to handle an event. I'm new to this type of programming and I'm completely lost. I have a C# code working with no problem, but when it comes to C++/WinRT it's completely different. First, I'm starting an advertisement watcher, and setting a scanning mode to active:
```
BluetoothLEAdvertisementWatcher watcher = BluetoothLEAdvertisementWatcher();
watcher.ScanningMode(BluetoothLEScanningMode::Active);
```
This is working, since I've checked the ScanningMode, etc. Then I try to register:
`watcher.Received({ this, &Handlers::OnAdvertisementReceivedAsync });`

This is probably not the way to do it, but like I mentioned, I have no clue how to proceed from this point.

[BluetoothLEAdvertisementWatcher Class](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher#events)

Edit: Forgot to add a `OnAdvertisementReceivedAsync` function:
`void Handlers::OnAdvertisementReceivedAsync(BluetoothLEAdvertisementWatcher const& watcher, BluetoothLEAdvertisementReceivedEventArgs const& eventArgs)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba75b9f7-4350-2d8c-00fd-e19898cbf3d5
* Version Independent ID: 32aa5fca-05e2-2e00-0f9a-501f92012960
* Content: [TypedEventHandler&lt;TSender,TResult&gt; Delegate (Windows.Foundation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.typedeventhandler)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.typedeventhandler.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.typedeventhandler.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by harikvpy** [comment]
Are you sure your `watcher` object is still available while the program is waiting to receive advert packets? I'm asking because in your code above it's stack allocated which would get destroyed when the method where it's declared returns. If your program uses the WinRT GUI and therefore employs framework classes, you might want to declare it as member variable of App class, which ensures that it's available as long as the program is running.

Here's my code:

```
using namespace Windows;
using namespace Windows::ApplicationModel::Core;
using namespace Windows::Foundation::Numerics;
using namespace Windows::UI;
using namespace Windows::UI::Core;
using namespace Windows::UI::Composition;
using namespace Windows::Devices::Bluetooth::Advertisement;

struct App : implements<App, IFrameworkViewSource, IFrameworkView>
{
    CompositionTarget m_target{ nullptr };
    VisualCollection m_visuals{ nullptr };
    Visual m_selected{ nullptr };
    float2 m_offset{};

	BluetoothLEAdvertisementWatcher m_watcher;

    IFrameworkView CreateView()
    {
        return *this;
    }

    void Initialize(CoreApplicationView const &)
    {
    }

    void Load(hstring const&)
    {
		OutputDebugString(L"App::Load\n");

		auto filter = BluetoothLEAdvertisementFilter();
		auto advert = BluetoothLEAdvertisement();
		//advert.LocalName(hstring(L"Greeny"));
		filter.Advertisement(advert);
		m_watcher.AdvertisementFilter(filter);
		m_watcher.ScanningMode(BluetoothLEScanningMode::Active);

		// setup event handlers
		m_watcher.Received({ this, &App::OnAdvertisementRecieved });
		m_watcher.Stopped({ this, &App::OnAdvertisementStopped });

		m_watcher.Start();

    }

	void OnAdvertisementRecieved(BluetoothLEAdvertisementWatcher const& watcher, BluetoothLEAdvertisementReceivedEventArgs const& args)
	{
		watcher;
		args;
		OutputDebugString(L"Bluetooth advertisement received!\n");
	}

	void OnAdvertisementStopped(Windows::Devices::Bluetooth::Advertisement::BluetoothLEAdvertisementWatcher const & watcher, Windows::Devices::Bluetooth::Advertisement::BluetoothLEAdvertisementWatcherStoppedEventArgs const & args)
	{
		watcher;
		args;
		OutputDebugString(L"Advertising stopped\n");
	}

	void Unload()
	{
		if (m_watcher.Status() == BluetoothLEAdvertisementWatcherStatus::Started)
		{
			m_watcher.Stop();
		}
	}

```
(sorry about the formatting)

Your handler setup looks correct. Compiler would raise errors if there were issues with it anyway (isn't C++ beautiful?)

Finally remember to include Bluetooth in the app manifest file (Package.appxmanifest) capabilities section like this:

```
  <Capabilities>
    <DeviceCapability Name="bluetooth" />
  </Capabilities>
```

HTH

**Comment by harikvpy** [comment]
BTW, this forum is specifically for documentation related issues and not for help with coding issues. You're more likely to get timely assistance from stackoverflow if the question is posted with the appropriate tags.

**Comment by robson31** [comment]
Thank you, I appreciate your help. It turned out that my code was different in structure and did not work the way I wrote it. Again, thank you.
