### ISSUE TITLE
Bad Javascript example

### ISSUE THREAD

**Issue by EionRobb** [MicrosoftDocs/winrt-api#423]
The Javascript property to check should be `keyboardPresent` not `KeyboardPresent`
`document.getElementById("keyboardPresent").innerHTML = keyboardCapabilities.keyboardPresent;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2f66f9-ede8-7c79-3d4b-7867e1451492
* Version Independent ID: b6f846bf-5cbb-d665-9717-bfc8106f09c3
* Content: [KeyboardCapabilities Class (Windows.Devices.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.input.keyboardcapabilities)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.input.keyboardcapabilities.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.input.keyboardcapabilities.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for catching this. Code snippet has been updated.
