### ISSUE TITLE
When will the SpatialEntityStore become active on the HoloLens?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#425]
This documentation says, that the SpatialAnchorTransferManager is being deprecated and the SpatialEntityStore will take its place.
When will that happen and when the SpatialEntityStore can be used for the HoloLens?
Right now, if I want to use the SpatialEntityStore it crashes (and SpatialEntityStore.IsSupported returns false).
I'm used to transfer anchors between HoloLenses by the SpatialAnchorTransferManager, but for the next projects I would like to use the newer technology and not one, which is already marked as being deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf1dba3f-d697-6a3f-9722-ec0295816672
* Version Independent ID: 00b6e97a-6177-e114-1dfc-63e07bfd02b2
* Content: [SpatialAnchorTransferManager Class (Windows.Perception.Spatial) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.spatialanchortransfermanager)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.spatialanchortransfermanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.spatialanchortransfermanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Hi @Nicole426, good question--I'll take this to the feature team and get back to you.

**Comment by jessemcculloch** [comment]
@nicole426 - were you running this on RS4 or RS5 builds, or on the old Rs1 build?  I have not tested yet, but I believe this should be available on RS4 and later builds

**Comment by ghost** [comment]
Hi @jessemcculloch,
I'm actually pretty sure that I'm running this on RS4 (Build 17134) and it is not available yet (or I'm wrong somewhere). I'm gonna check it again and update, if necessary

**Comment by thetuvix** [comment]
Apologies for the delay in responding here!

There is no current plan to enable the `SpatialEntityStore` API.  For new projects, the recommended path for anchor sharing is to use [Azure Spatial Anchors](https://docs.microsoft.com/azure/spatial-anchors).
