### ISSUE TITLE
Adding a StorageItem (e.g. a file) from  a Zipped Folder to a FutureAccessList results in an exception 'Value does not fall within the expected range.'

### ISSUE THREAD

**Issue by abhaykochar1** [MicrosoftDocs/winrt-api#426]
Adding a StorageItem (e.g. a file) from  a Zipped Folder to a FutureAccessList results in an exception 'Value does not fall within the expected range.' This is not documented above and is not clear whether it is something the calling app should handle as an expected exception for this case.

Test Code:
In Windows Universal Samples, in the Share Target example, add below lines in OnNavigatedTo function:
                    if (this.sharedStorageItems != null)
                    {
                         ...
                        // BUG BUG: Causes a CRASH when adding an item from a Zipped Folder to the FutureAccessList
                        var futureAccessList = StorageApplicationPermissions.FutureAccessList;
                        futureAccessList.CheckAccess(sharedStorageItems[0]);
                    }

Repro steps:
Open a zipped folder directly but don't extract contents. Drag a file from this or click share and select the ShareTarget App deployed with changes mentioned above. Results in a crash.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31b1f64a-0b75-e2f9-4024-b4613204bb02
* Version Independent ID: 71c989f1-ce43-ca52-3e95-118c840d0b74
* Content: [StorageItemAccessList.Add Method (Windows.Storage.AccessCache) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist.add)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks so much for submitting this thorough feedback and fix. It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
