### ISSUE TITLE
The purpose of `CoreDispatcher.TryRunAsync` is unclear

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#431]
The doc should be updated to answer these questions:
  - Why does `TryRunAsync` exist? When would I use it instead of `RunAsync`?
  - What does the `bool` return value mean?

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dfc15ea-3151-c20a-0377-007d07f3300d
* Version Independent ID: 2ab27cc1-7ff3-f0e7-850e-0487deef8786
* Content: [CoreDispatcher.TryRunAsync(CoreDispatcherPriority, DispatchedHandler) Method (Windows.UI.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.tryrunasync#Windows_UI_Core_CoreDispatcher_TryRunAsync_Windows_UI_Core_CoreDispatcherPriority_Windows_UI_Core_DispatchedHandler_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coredispatcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coredispatcher.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hartez** [comment]
According to the docs for RunAsync, TryRunAsync allows you to detect the case where the method is successful but the callback won't run because the CoreDispatcher is shutting down. So TryRunAsync lets you detect that edge case:

https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.runasync?view=winrt-18362#remarks

**Comment by rigdern** [comment]
Thanks, the docs are clearer now than when I filed this.

While inspecting the new docs for these methods, I found and filed #1639.
