### ISSUE TITLE
Cannot Render to file when I create a MediaClip from a surface. 

### ISSUE THREAD

**Issue by CristianKica** [MicrosoftDocs/winrt-api#433]
It throws
System.Runtime.InteropServices.COMException Stream is not in a state to handle the request.

            RenderTargetBitmap renderTargetBitmap = new RenderTargetBitmap();
            await renderTargetBitmap.RenderAsync(RenderedGrid, width, height);

            IBuffer pixels = await renderTargetBitmap.GetPixelsAsync();

            var soft = SoftwareBitmap.CreateCopyFromBuffer(pixels, BitmapPixelFormat.Bgra8, renderTargetBitmap.PixelWidth, renderTargetBitmap.PixelHeight, BitmapAlphaMode.Ignore);
            CanvasBitmap canvas = CanvasBitmap.CreateFromSoftwareBitmap(myWidget, soft);
            StorageFile video3 = await storageFolder.CreateFileAsync("video3" + ".mp4", CreationCollisionOption.ReplaceExisting);
            MediaClip m = MediaClip.CreateFromSurface(canvas, DateTime.Now - previousFrame + new TimeSpan(100));

            videoClip.Clips.Add(m);
            await videoClip.RenderToFileAsync(video3);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c30c9600-6bcd-ca4b-c53b-0534a0e0f9fe
* Version Independent ID: cb867600-9683-7d2c-c608-c3c2f03ba082
* Content: [MediaComposition Class (Windows.Media.Editing) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.editing.mediacomposition#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.editing.mediacomposition.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.editing.mediacomposition.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by CristianKica** [comment]
I forgot I had opened an issue. Please see this issue here too. https://github.com/MicrosoftDocs/winrt-api/issues/443  Perhaps it will give you more information

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
