### ISSUE TITLE
Would be super-useful to hint at the "next step" in my app

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/winrt-api#435]
Once I call StartSoftwareTrigger, what actually happen? It's a signal for the scanner to start scanning -- but when a match is found, what gets called? How do I provide a callback? It would have been great if you had included here a hint to look at the events (I think) that I need to connect to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48cc4bcc-4f34-0a2b-934c-de9d5e38b388
* Version Independent ID: 554ead03-972a-6d5a-a50d-f25d03b96fcf
* Content: [ClaimedBarcodeScanner.StartSoftwareTriggerAsync Method (Windows.Devices.PointOfService) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.claimedbarcodescanner.startsoftwaretriggerasync#Windows_Devices_PointOfService_ClaimedBarcodeScanner_StartSoftwareTriggerAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.claimedbarcodescanner.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.claimedbarcodescanner.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @PeterSmithRedmond, and thanks for filing this issue. I've reached out to find a contact in the feature team to help me field this question, and I'll report back here with what I discover.

Thanks!
Steve

**Comment by yentsanglee** [comment]
There is a barcode scanner sample in [Windows UWP Sample github](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BarcodeScanner).

You register an event [DataReceived](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.claimedbarcodescanner.datareceived) which is triggered when a barcode data is received.

**Comment by TerryWarwick** [comment]
The process that @yentsanglee is referring to is also in our conceptual documentation for [Use a software trigger](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-barcodescanner-software-trigger).

**Comment by stevewhims** [comment]
Thanks for the info, everyone! I've added that info to the topic.

I'll go ahead and close this issue now.

-Steve
