### ISSUE TITLE
an IBuffer is not a stream

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/winrt-api#436]
Would be nice if there was a mini-example right here of how to convert the IBuffer into something useful, like a string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f34dfb0-0477-4742-d1f2-ad5246df29a9
* Version Independent ID: 62e18c26-cca4-e9f6-2a42-85761b86b30c
* Content: [BarcodeScannerReport.ScanDataLabel Property (Windows.Devices.PointOfService) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.barcodescannerreport.scandatalabel#Windows_Devices_PointOfService_BarcodeScannerReport_ScanDataLabel)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescannerreport.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescannerreport.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @PeterSmithRedmond, and thanks for filing this issue. I've published a fix, adding a code example to the IBuffer topic, and then linking to that topic from here.

I'll go ahead and close this issue now. You can always respond to it, even when closed, and re-open it if necessary.

Thanks!
Steve
