### ISSUE TITLE
"Raw data stream"

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/winrt-api#437]
This property is only useful if it includes an explanation of what the format of the "raw data" is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c38c3c65-e3b7-bbe4-1e29-ea1917c7c65b
* Version Independent ID: 35d8d4a4-ba24-d2ab-18d3-ab818100b4c8
* Content: [BarcodeScannerReport.ScanData Property (Windows.Devices.PointOfService) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.barcodescannerreport.scandata#Windows_Devices_PointOfService_BarcodeScannerReport_ScanData)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescannerreport.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.barcodescannerreport.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @PeterSmithRedmond, and thanks for filing this issue. In the topic, I've published a link to a specification that describes the content and format of the raw data.

I'll go ahead and close this issue, but you can still respond to it, and even re-open it if necessary.

Thanks!
Steve
