### ISSUE TITLE
The description column appears out-dated

### ISSUE THREAD

**Issue by AE-MS** [MicrosoftDocs/winrt-api#438]
For instance, the "Scale150Percent" row has a description that says "Applies to Windows Phone 8."  While that may be true, it also applies elsewhere (for instance, my Surface Pro 3 is 150% scale by default) and that comment makes it sound like it _only_ applies to WP8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149dc3f7-4344-d8bb-a4a0-dd9231fb6def
* Version Independent ID: 9c03798c-e893-e4de-d9f3-ab019d9d208e
* Content: [ResolutionScale Enum (Windows.Graphics.Display) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Display.ResolutionScale)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.resolutionscale.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.resolutionscale.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @AE-MS, and apologies for the very long delay in responding to this issue. You're right about Scale150Percent, and I have a fix in the publishing pipeline, and I'll keep checking that to make sure it goes live. Meanwhile, I'll go ahead and close this issue now.

Thanks again!
Steve
