### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by pfischer54** [MicrosoftDocs/winrt-api#439]
The link to GetDeviceSelector is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb227cd6-7c71-1e7e-8ea3-14f188ac8bb3
* Version Independent ID: fcfc983b-22e2-174a-1457-18ab3885f1c5
* Content: [DeviceInformation.FindAllAsync Method (Windows.Devices.Enumeration) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation.findallasync#Windows_Devices_Enumeration_DeviceInformation_FindAllAsync_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceinformation.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
