### ISSUE TITLE
BluetoothLEDevice.GetDeviceSelector Method Update Needed

### ISSUE THREAD

**Issue by robson31** [MicrosoftDocs/winrt-api#440]
Description needs to get updated, links do not work.

[Create Watcher Link](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation.createwatcher), [FindAllAsync Link](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation.findallasync).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a726b8-09fb-8e00-1ea7-ccfef8f8d852
* Version Independent ID: 3e3d120d-89c0-5340-db5e-0816f3294fcf
* Content: [BluetoothLEDevice.GetDeviceSelector Method (Windows.Devices.Bluetooth) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.getdeviceselector#Windows_Devices_Bluetooth_BluetoothLEDevice_GetDeviceSelector)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.bluetoothledevice.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @robson31. Thanks for filing this issue, and my apologies for the long delay in responding. It looks like in the interim the broken links have been fixed. I just tested them, and all links on the page work.

Thanks again!
Steve
