### ISSUE TITLE
SelectedNodes property is not updated in single-selection mode

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#441]
The **SelectedNodes property** cannot be used to determine which tree node is selected in *single-selection mode*.
I have to handle the ItemInvoked event and manually keep track of the selected node.
In single-selection mode, the SelectedNodes property should *always* contain 0 or 1 item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d36b7a-f029-3033-ed1e-4b82f75d6a21
* Version Independent ID: 6a43492e-b7c3-9ed2-cec2-ee0f5558f8b0
* Content: [TreeView.SelectedNodes Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview.selectednodes)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by EddieLotter** [comment]
I have created an entry in User Voice for this.
Please vote on it if you agree it needs to be done.
See: [https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/37249801-the-selectednodes-property-for-single-select-treev](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/37249801-the-selectednodes-property-for-single-select-treev)

**Comment by jevansaks** [comment]
Thanks, we are tracking this as a product bug is Microsoft/microsoft-ui-xaml#124.
