### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by MadafakinRio** [MicrosoftDocs/winrt-api#445]
DisplayMode is marked as read only, both in these docs, and in the SDK. Not sure if that's intentional. Whatever the case may be, if it's read only then you can't set the DisplayMode in XAML as shown in the docs XAML snippet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d87ec88-b95d-6330-bb16-14c61ab5cce5
* Version Independent ID: 49b2d169-a5d8-8d96-60cd-e44e75c1704f
* Content: [NavigationView.DisplayMode Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.displaymode#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by SylvesterLi** [comment]
Same trouble I met, it's not still solved. Really hope your team could be more quick to fix these mistakes

**Comment by sannnyu** [comment]
@MadafakinRio hey there , I got know how to solve this problem. After you import nuget package "Microsoft.UI.Xaml" you should add
```  XAML
<Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/> 
</Application.Resources>
```

to `<Application></Application>` in your "app.xaml"

then in the MainPage.xaml (or some other pages)

you should add
`
xmlns:controls="using:Microsoft.UI.Xaml.Controls"
`
in the `<Page></Page>`

and add `using MUXC = Microsoft.UI.Xaml.Controls;` in your backend code (mainpage.xaml.cs)

ok, now we can set Display Mode
But !
You can't just write `<NavigationView>` , this indecates you are using old version controls which is not allowed to set Display Mode.

You should write `<controls:NavigationView />`,in this way you can easily find your problem soloved !
Just like this:
[Sylvester Li Github Repos](https://github.com/SylvesterLi/SANGToolkit/blob/master/MainPage.xaml)

**Comment by YuliKl** [comment]
@MadafakinRio - DisplayMode is indeed read-only and we'll fix the documentation. You can use [PaneDisplayMode](https://docs.microsoft.com/uwp/api/microsoft.ui.xaml.controls.navigationview.panedisplaymode) instead.
