### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#446]
In the remarks section, the link "**How to track recently used files and folders**" links to outdated information.
Consider linking to: **https://docs.microsoft.com/en-us/windows/uwp/files/how-to-track-recently-used-files-and-folders**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1ef7e7c-2f41-624f-95bb-f6ad569fd83a
* Version Independent ID: 4a619d60-9419-38af-9704-392b83c419d2
* Content: [StorageItemAccessList Class (Windows.Storage.AccessCache) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.accesscache.storageitemaccesslist#remarks)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.accesscache.storageitemaccesslist.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by laurenhughes** [comment]
@EddieLotter Thanks for the heads up! I fixed the link, updates will be live tomorrow.
