### ISSUE TITLE
Sample Script to use Segoe MDL2 Icons

### ISSUE THREAD

**Issue by dvanurag1308** [MicrosoftDocs/winrt-api#447]
It would be really helpful if there is a sample XAML on how to use Segoe MDL2 Icons 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee341f6-e3c0-26fc-084b-5ab12c81d282
* Version Independent ID: 496e9201-a524-33b8-d3be-e1cb6b9cd53f
* Content: [NavigationViewItem.Icon Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationviewitem.icon)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewitem.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewitem.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
We should just cross-link to this doc: https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font

**Comment by YuliKl** [comment]
This document has been updated.
