### ISSUE TITLE
Link to samples? guides? blog post?

### ISSUE THREAD

**Issue by kwiqniss** [MicrosoftDocs/winrt-api#449]
Can we post related content links?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a47d2c-61a3-01b3-d0dc-73a4b7d5117f
* Version Independent ID: 4c713fb3-f086-5319-cf44-33346a7a14b7
* Content: [Windows.Networking.Vpn Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Vpn)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
@kwiqniss, my sincere apologies for the delay. I'm still making enquiries internally to see what info I can gather to help resolve this issue, as well as #448. ~Steve

**Comment by stevewhims** [comment]
Hi, @kwiqniss, again, apologies for the delay. I've been in touch with internal folks now and so far nothing has sprung to mind that we could link to in terms of related content. If that changes in the future then I'll immediately update the topic with links.

**Comment by stevewhims** [comment]
@kwiqniss, I'll go ahead and close this issue now since there's nothing further we can do in the immediate term to entirely resolve it. Please reopen if I made a mistake in closing. ~Steve
