### ISSUE TITLE
Link to IWebViewControl is broken

### ISSUE THREAD

**Issue by rjmurillo** [MicrosoftDocs/winrt-api#450]
Link to IWebViewControl is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e4110c-1dc8-e7cf-afc1-0ab84cb92189
* Version Independent ID: 49407ea7-7d3f-5aa3-ea5f-c0b9073897b5
* Content: [WebViewControl.WebResourceRequested Event (Windows.Web.UI.Interop) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.web.ui.interop.webviewcontrol.webresourcerequested)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by erikadoyle** [comment]
Fixed now.
