### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by HerrickSpencer** [MicrosoftDocs/winrt-api#451]
Link for "User.FindAllAsync" should be https://docs.microsoft.com/en-us/uwp/api/windows.system.user.findallasync#Windows_System_User_FindAllAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 542b81b8-1415-533c-dee4-d4aa66856798
* Version Independent ID: daa221ed-1467-b11b-9d2c-2e56cf9c248d
* Content: [UserWatcher Class (Windows.System) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.userwatcher)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.userwatcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.userwatcher.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by laurenhughes** [comment]
@HerrickSpencer, thank you for the catch! Updated links will be live tomorrow.
