### ISSUE TITLE
Constructor links lead to 404s

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#452]
A couple of constructors for `Thickness` are mentioned on this page but their links lead to 404s:
  -  [`Thickness(Double)`](https://docs.microsoft.com/en-us/uwp/api/thickness_thickness_1)
  - [`Thickness(Double,Double,Double,Double)`](https://docs.microsoft.com/en-us/uwp/api/thickness_thickness_2)

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9654762b-f3d4-6259-2b8e-874d9185be19
* Version Independent ID: 52145687-0078-79c2-2235-b24d9c5822c1
* Content: [Thickness Struct (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.thickness)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.thickness.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.thickness.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
@jwmsft can you fix the links for these constructors? Maybe, like enums, there's no way to hyperlink to a specific constructor?

**Comment by jwmsft** [comment]
These links are fixed.
