### ISSUE TITLE
Is this api supported on Windows IoT Core?

### ISSUE THREAD

**Issue by luyaok** [MicrosoftDocs/winrt-api#455]
When I use this API on the desktop, I get system id from registry and it keep the same after reboot. But same from registry, on Windows IoT Core(Raspberry Pi 3), the system id changes after reboot! And there is an issue report from the customer that on Dragonboard running Windows IoT Core, the system id not persistent across power cycles. (https://social.msdn.microsoft.com/Forums/en-US/0862e413-7d20-437d-8f43-b6e9eeb60694/systemidentificationgetsystemidforpublisher-changes-on-power-cycle-dragonboard?forum=WindowsIoT&prof=required)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad3fc16a-35bc-b377-8319-c180ffbb4405
* Version Independent ID: b1b98ced-7a11-adef-51c7-cc09284a33c2
* Content: [SystemIdentification.GetSystemIdForPublisher Method (Windows.System.Profile) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.profile.systemidentification.getsystemidforpublisher#Windows_System_Profile_SystemIdentification_GetSystemIdForPublisher)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.systemidentification.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.profile.systemidentification.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
It sounds like you are able to call this API on your IoT device. I cannot speak to the inconsistent results you're getting. You may want to try contacting support or posting your question in the Windows IoT forum here: https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT

Please let us know here is you have feedback on the documentation.
