### ISSUE TITLE
Class not registered

### ISSUE THREAD

**Issue by CristianKica** [MicrosoftDocs/winrt-api#456]
I get **System.Exception Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))** for this piece of code in **Hololens**
```
 var picker = new GraphicsCapturePicker();
GraphicsCaptureItem item = await picker.PickSingleItemAsync();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68469560-45df-1c12-3b12-8a12eeb23739
* Version Independent ID: 9eedfc35-4c9a-326d-cd93-e4fe24bb3b86
* Content: [GraphicsCapturePicker.PickSingleItemAsync Method (Windows.Graphics.Capture) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturepicker.picksingleitemasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.capture.graphicscapturepicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.capture.graphicscapturepicker.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Hi @CristianKica, are you using Unity for your HoloLens development?

**Comment by CristianKica** [comment]
@eliotcowley No, I am creating a uwp app, from VS.

**Comment by eliotcowley** [comment]
Did you add the capability for **Graphics Capture**? See [Screen capture](https://docs.microsoft.com/windows/uwp/audio-video-camera/screen-capture#add-the-screen-capture-capability) for details.

**Comment by CristianKica** [comment]
@eliotcowley  Yes, i did. It works with PC, but not hololens

**Comment by eliotcowley** [comment]
According to the dev, screen capture only works on desktop (including Windows Mixed Reality immersive headsets that are hooked up to the desktop). HoloLens is not supported. I will add this to the documentation.

You can check if it's supported with the [GraphicsCaptureSession.IsSupported Method](https://docs.microsoft.com/uwp/api/windows.graphics.capture.graphicscapturesession.issupported).
