### ISSUE TITLE
Wrong description on AlignmentRatio

### ISSUE THREAD

**Issue by ad1Dima** [MicrosoftDocs/winrt-api#458]
HorizontalAlignmentRatio and VerticalAlignmentRatio has wrong descripton

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cbcab7a-b3f3-1271-a546-553ad3e2ca66
* Version Independent ID: ce56e137-77ad-cd42-0b35-9d6711ec3e2b
* Content: [BringIntoViewRequestedEventArgs Class (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.bringintoviewrequestedeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.bringintoviewrequestedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.bringintoviewrequestedeventargs.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by micahl** [comment]
@jwmsft, is there any way to have this issue auto-close once the updated docs go live?  I don't have perms to close this issue.
