### ISSUE TITLE
Mark deprecated API

### ISSUE THREAD

**Issue by xmedeko** [MicrosoftDocs/winrt-api#459]
I would welcome to see in the doc which properties and methods are deprecated and from which version are deprecated.
E.g. `GattDeviceService` contains some deprecated methods and properties and none of them is in the doc.

**Comment by stevewhims** [comment]
Hi, @xmedeko, and thanks for filing this issue. For GattDeviceService, and several other types in the same or related namespace, I've updated topics with deprecation notices.

You can use the feedback mechanism on individual API topics if you find any others that you know are deprecated.

Thanks!
Steve
