### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by maluoi** [MicrosoftDocs/winrt-api#460]
What unit is the interval in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1361236b-6ae3-b990-92e8-01a9a6195e25
* Version Independent ID: 4b63b6eb-36b9-0ecd-41f7-da541ae60556
* Content: [LightSensor.MinimumReportInterval Property (Windows.Devices.Sensors) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.lightsensor.minimumreportinterval)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.sensors.lightsensor.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.sensors.lightsensor.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @maluoi. All MinimumReportInterval topics have been updated to include this detail.
