### ISSUE TITLE
Does it matter what UI thread is used?

### ISSUE THREAD

**Issue by fman028** [MicrosoftDocs/winrt-api#461]
The documentation states:  "You can only access the clipboard when the calling application is in focus on the UI thread"

Our app has secondary windows and hence multiple UI threads.  If one of our windows is in focus (activated), does it matter which UI thread the static Clipboard methods are called from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 100fb5ed-12d9-c09f-1820-02521ec76f8b
* Version Independent ID: 57d08ba1-0df1-1345-8009-641f40f9713a
* Content: [Clipboard Class (Windows.ApplicationModel.DataTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.DataTransfer.Clipboard)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.clipboard.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.clipboard.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. This GitHub repo is specifically for reporting documentation bugs. For technical questions like this, please see the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).

I'm marking this issue as closed now, but please feel free to reopen it if you have more information that indicates a real doc bug here. Thanks again!
