### ISSUE TITLE
Requires contract version 5

### ISSUE THREAD

**Issue by adamhewitt627** [MicrosoftDocs/winrt-api#462]
This API is only on Fall Creator's Update and newer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96be3d78-a61d-9661-d3a9-8b648b3654bd
* Version Independent ID: 1eba5642-80b6-16ac-d726-ca280abdb0b8
* Content: [DownloadOperation.RangesDownloaded Event (Windows.Networking.BackgroundTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.downloadoperation.rangesdownloaded)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.downloadoperation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.downloadoperation.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @adamhewitt627, and thank your for bringing this omission to my attention! I've just merged a fix into master, and I expect that change to appear on the live site within 24 hours. May I also extend appreciation for bringing Olive Tree to the Windows platform. ~Steve

**Comment by stevewhims** [comment]
@adamhewitt627, I'll go ahead and close this issue now that the formerly missing info is present on the live topic. Please reopen if I made a mistake in closing. ~Steve
