### ISSUE TITLE
Which method to use?

### ISSUE THREAD

**Issue by BajaPaul** [MicrosoftDocs/winrt-api#463]
I have an UWP encryption/Decryption app.  Is there a reason to use this CryptographicBuffer.CreateFromByteArray(byteArrayIV);
versus
byteArrayIV.AsBuffer();
Both return same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3191bfe1-8acf-3387-5138-b06918f78c3d
* Version Independent ID: e89e0601-a957-18c3-10ab-738ea96e0076
* Content: [CryptographicBuffer.CreateFromByteArray(Byte\[\]) Method (Windows.Security.Cryptography) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.cryptographicbuffer.createfrombytearray#Windows_Security_Cryptography_CryptographicBuffer_CreateFromByteArray_System_Byte___)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by tipa** [comment]
I'd like to know that as well

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question if it is still something you're interested in getting an answer to. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
