### ISSUE TITLE
Images are incorrect.

### ISSUE THREAD

**Issue by ihgreenman** [MicrosoftDocs/winrt-api#465]
The images are showing the results of a skew transform, not a scale transform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bac8ecd-77c5-9742-534f-ca20d5b0b79e
* Version Independent ID: f243232d-0e62-6ddc-715d-7d474fba8448
* Content: [ScaleTransform Class (Windows.UI.Xaml.Media) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.scaletransform)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.scaletransform.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.scaletransform.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
And the SkewTransform doc has no images.

**Comment by jesbis** [comment]
Thanks for reporting this! The skew and scale transform images and examples have been updated and the changes should appear on the docs site soon.
