### ISSUE TITLE
"404 - Page not found"  from clicking FindAllAsync

### ISSUE THREAD

**Issue by andrew7webb** [MicrosoftDocs/winrt-api#466]
If I click on 
"You can retrieve certificates from the certificate store using the FindAllAsync method.", I am referred to 
https://docs.microsoft.com/en-us/uwp/api/certificatestores_findallasync  
which brings a 404 error.  Please fix, and by the way put the C++ version in too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02ceb297-96b0-6ba1-1ba3-2e3594f1e393
* Version Independent ID: cb6c9a22-f471-b9e4-a4f4-9323572e7f17
* Content: [CertificateStore Class (Windows.Security.Cryptography.Certificates) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.certificates.certificatestore)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.certificates.certificatestore.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.certificates.certificatestore.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Closing this Issue as this has been resolved and the link is working. Appreciate your contributions!
