### ISSUE TITLE
VoIP docs should include some overview pages that focus on architecture and scenarios

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#467]
By VoIP docs, I'm referring to the stuff in [Windows.ApplicationModel.Calls](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.voipcallcoordinator)

Looking at the VoIP docs, I imagine developers new to UWP would have a hard time figuring out how to construct their VoIP apps. Imagine being a developer unfamiliar with the UWP VoIP APIs. What page should act as the entry point and how should they find it? The existing pages I see are the API reference docs and the VoIP samples. None of these things seems like a great starting point because they don't offer enough of an overview or introduction.

Below are some docs that I think would be useful to have.

### Scenario-focused overview page

The number of VoIP APIs for starting a call is growing and it's hard to understand when to use each one. For example, there is:
  - `RequestNewAppInitiatedCall`
  - `RequestNewIncomingCall`
  - `SetupNewAcceptedCall`

I know each API reference doc briefly mentions the purpose but it's not elaborate enough for developers new to UWP VoIP. You have to infer the pattern yourself that these are the 3 APIs for new calls -- the docs don't call it out for you.

It'd be great to have an overview page that describes the VoIP scenarios and which APIs are relevant to each scenario. For example, you might mention the general scenario of the user getting an incoming call. When this happens, your app might want to handle this in different ways. You might want to show an OS toast notification. Alternatively, the app might want to render its own notification inside of the app's UI (it might also be useful to give guidance on when you might want to show a toast vs render the notification inside of the app). Lastly, you might want to have the app automatically answer the call. It's important to mention which APIs are appropriate for each scenario.

This might be a good place to explain the relationship between `NotifyCallAccepted` and the other VoIP APIs. From looking at when the APIs were introduced and the reference docs, my suspicion is it's only intended to be used with `RequestNewAppInitiatedCall` but I'm not 100% sure.

You might also want to mention how the Windows Quiet Hours feature interacts with these APIs.

The point is that it's a **scenario-focused overview**.

### Architectural overview page

UWP VoIP apps are pretty sophisticated. It would be helpful to have an architectural overview page for UWP VoIP apps similar to this one for [Windows Phone 8 VoIP apps](https://msdn.microsoft.com/en-us/library/windows/apps/jj206983(v=vs.105).aspx).

### Overview of VoIP learning resources

The entry point doc should contain links to all of the educational VoIP resources:
  - Reference docs
  - Other overview docs (e.g. architectural, scenarios)
  - Relevant //BUILD presentations
  - All samples (e.g. basic VoIP sample, ChatterBox)

Adam Comella
Microsoft Corp.

**Comment by MatchaMatch** [comment]
Hi Adam - Thanks for taking the time to let us know about this. Due to the sheer volume of feedback in our repo, we're currently prioritizing new issues. I'm going to close this but if it's still impacting you or others, feel free to leave a comment and we can keep it open and dig in. Alternatively, you can submit a new issue or pull request with the latest details. Thanks so much and apologies for the delayed communication here.
