### ISSUE TITLE
RegisterStreamSocketListenerAsync issues

### ISSUE THREAD

**Issue by matthew-a-thomas** [MicrosoftDocs/winrt-api#470]
This method doesn't include `A` or `AAAA` DNS records with the initial service announcement. I can tell this by either looking at Wireshark or by noticing that "System.Devices.IpAddress" and "System.Devices.Aep.DeviceAddress" both come back null for `DeviceWatcher` queries on other machines.

Neither does it rename the service when the same name is already taken on the link-local network.

Both of these behaviors are different than [Apple's Bonjour / the `dns-sd` command](https://developer.apple.com/download/more/?=Bonjour%20SDK%20for%20Windows).

The first behavior means I must use another mechanism for resolving DNS-SD service names to IP addresses, because while a `DeviceWatcher` query will give me the IP addresses for anything registered with Bonjour, it won't give me the IP addresses for anything registered with this function.

That's interesting because [this example application from Microsoft](https://github.com/Microsoft/Windows-appsample-networkhelper/blob/master/NetworkHelper/DnssdParticipant.cs#L188) expects the "System.Devices.IpAddress" property to be populated with something. That seems to suggest there is a bug with this function.

This is also confusing, because what other mechanism am I supposed to use? Should I expect for [the Dns class](https://msdn.microsoft.com/en-us/library/system.net.dns(v=vs.110).aspx) to be able to resolve host names via mDNS?

Unless I'm doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f659ee1-7687-1f27-9953-c3cf8d601a1f
* Version Independent ID: c101a9db-3d3f-3484-5bc7-b360ad280e30
* Content: [DnssdServiceInstance.RegisterStreamSocketListenerAsync Method (Windows.Networking.ServiceDiscovery.Dnssd) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.servicediscovery.dnssd.dnssdserviceinstance.registerstreamsocketlistenerasync#Windows_Networking_ServiceDiscovery_Dnssd_DnssdServiceInstance_RegisterStreamSocketListenerAsync_Windows_Networking_Sockets_StreamSocketListener_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.servicediscovery.dnssd.dnssdserviceinstance.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.servicediscovery.dnssd.dnssdserviceinstance.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by matthew-a-thomas** [comment]
An update: `DeviceWatcher` queries are now returning IP addresses in the "System.Devices.IpAddress" and "System.Devices.Aep.DeviceAddress" properties. I'm not sure what changed, except that I did perform a DNS lookup for the host name using the `Dns` class.

Overall I'm rather confused. So I won't be surprised if whoever works on this will be, too. So let me know if you'd like a minimal reproduction.

**Comment by stevewhims** [comment]
Hi, @matthew-a-thomas! For problems/errors/omissions with the actual documentation, this is the right forum to raise those. But the Windows developer feedback site (https://wpdev.uservoice.com/) is the right place to file a product bug. For issues, or suspected product bugs, there's Microsoft Support (https://support.microsoft.com/contactus/); a support engineer will look at the repro and see whether the issue is a product bug or something else. Thanks! ~Steve

**Comment by matthew-a-thomas** [comment]
@stevewhims Thanks!

**Comment by matthew-a-thomas** [comment]
I opened this bug:
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/34826236-dns-sd-registration-does-not-respond-to-queries-wi

For anyone else coming along, please vote for the bug in that link.
