### ISSUE TITLE
C++ Documentation?

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#471]
Where is the C++ documentation for SoftwareBitmap. We really need examples, there seems to be differences between the CX and WinRT. For instance .. Where is IBufferByteAccess ? Which is required for the CX examples as far as I can tell, but it doesn't seem to exist in WinRT, If I have it correct we are meant to include robuffer.h, but <winrt/robuffer.h> doesn't work. The only mention I can find of IBufferByteAccess is here ..

https://docs.microsoft.com/en-us/windows/uwp/xbox-live/storage-platform/connected-storage/connected-storage-using-buffers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eec6e5e4-d6fa-50e5-d197-5e0555df4214
* Version Independent ID: 6ef061aa-fe44-add2-efe6-f0c02b18e5c6
* Content: [SoftwareBitmap Class (Windows.Graphics.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Imaging.SoftwareBitmap)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by lmadhavan** [comment]
The documentation for WriteableBitmap.PixelBuffer has some details on how to access the byte buffer from C++/CX and C++/WinRT: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.writeablebitmap.pixelbuffer

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams, and thanks for filing this issue. You're right, there wasn't a clear link between the various topics here. I have fixes on the way to add more links to both the overall SoftwareBitmap topic and to that class's CopyToBuffer and CopyFromBuffer method topics. The links take you to the code example in https://docs.microsoft.com/uwp/api/windows.ui.xaml.media.imaging.writeablebitmap.pixelbuffer, as @lmadhavan mentions.

I'll monitor the live site for those changes going live.

Thanks!
Steve

**Comment by stevewhims** [comment]
**UPDATE**: So my updates are now live. I'll go ahead and close the issue.

Thanks again!
Steve
