### ISSUE TITLE
C++ Documentation

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#472]
Where is Windows.Graphics.Imaging for C++, I only see DirectX, Display & Effects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b77de385-3b43-1403-940a-fa39c9ef3f4f
* Version Independent ID: 646e5e8b-dc55-368b-0a44-f2b401fb5ae1
* Content: [Windows.Graphics.Imaging Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams, and thanks for filing this issue.

To use C++/WinRT to consume the types in the Windows.Graphics.Imaging Windows Runtime namespace, you'll need to `#include <winrt/Windows.Graphics.Imaging.h>` (probably in your pch.h).

See https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/get-started for more details.

Thanks!
-Steve
