### ISSUE TITLE
Why are the size and data separated with different interfaces. 

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#474]
Why is it so convoluted to simply created and edit a bitmap. Why not just have a Bitmap class that gives me everything I need. I've got SoftwareBitmaps, BitmapBuffers, IMemoryBufferReferences, IMemoryBufferByteReferences, unsigned char pointers and I still don't know how to edit a bitmap, it's just crazy. Why do C++ engineers struggle to understand how Bitmaps are conceptualized and used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef8cff0f-a838-d28f-0909-9f7efffffd00
* Version Independent ID: 35c0661d-a0f0-a576-c3d2-69a5a3d6a326
* Content: [IMemoryBufferReference Interface (Windows.Foundation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.imemorybufferreference)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.imemorybufferreference.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.imemorybufferreference.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Hi Gavin,

Thank you for you feedback. This tool is where you can submit feedback specifically on the documentation. It sounds like you have feedback for the product team regarding the design of the APIs. Please use the **Product feedback** link to submit your input to the Windows feature team. Please use the **Content feedback** link if you have input that will help improve the documentation.

Thank you,
 _Mark_
