### ISSUE TITLE
What is the point of this method?

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#476]
This method returns the object itself. What's the point of this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecabecb6-6d97-d9f5-02c5-0921cd16337b
* Version Independent ID: 8d2bd51a-4606-8e06-5c77-9fc77d8be9a5
* Content: [SoftwareBitmap.GetReadOnlyView Method (Windows.Graphics.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.softwarebitmap.getreadonlyview)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
For graphics and imaging APIs, sometimes the system can optimize performance if it knows that the memory associated with an image or texture only needs read access. For further questions, the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.
