### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/winrt-api#477]
The following links are returning 404s.

- Grid.Column: https://docs.microsoft.com/en-us/uwp/api/grid_column
- Grid.Column.Span: https://docs.microsoft.com/en-us/uwp/api/grid_columnspan
- Grid.Row: https://docs.microsoft.com/en-us/uwp/api/grid_row
- Grid.RowSpan: https://docs.microsoft.com/en-us/uwp/api/grid_rowspan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beef116a-75c0-8f7c-24e9-30010f2fa9f7
* Version Independent ID: 464670d2-f758-0816-5868-4452f40ed8d7
* Content: [Grid Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Grid)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.grid.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.grid.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Links are fixed.
