### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by jason-ha** [MicrosoftDocs/winrt-api#479]
Link for "Add" in "C# or Microsoft Visual Basic, see Add." is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dff5c77-60c2-2f5e-b316-a1ac937ab4a3
* Version Independent ID: b19e8428-0e5a-3c5c-b2bd-5c2af974c190
* Content: [UIElementCollection.Append(UIElement) Method (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.uielementcollection.append#Windows_UI_Xaml_Controls_UIElementCollection_Append_Windows_UI_Xaml_UIElement_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.uielementcollection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.uielementcollection.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
Add is a .NET only projection thing and I don't know the right way to fix the hyperlink to it. @jwmsft can you help?

**Comment by jwmsft** [comment]
Links to .NET projected members have been updated.
