### ISSUE TITLE
SoftwareBitmap properties are incorrect.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#481]
SoftwareBitmap width and height are byte, they should be int.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d1d34d-0c30-2810-1bee-f1509b590b38
* Version Independent ID: 0384b554-c858-97ba-8fc7-dad95ec15974
* Content: [SoftwareBitmap Constructor (Windows.Graphics.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.softwarebitmap.-ctor#Windows_Graphics_Imaging_SoftwareBitmap__ctor_Windows_Graphics_Imaging_BitmapPixelFormat_System_Int32_System_Int32_Windows_Graphics_Imaging_BitmapAlphaMode_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
This issue appears to have been resolved. The data types show as int in the current documentation.
