### ISSUE TITLE
Should mention that this only works when called from the UI thread

### ISSUE THREAD

**Issue by KevinKennedy** [MicrosoftDocs/winrt-api#483]
Should mention that this only works when called from the UI thread

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57a6c1d7-76d8-320e-be0e-db83257a4bd3
* Version Independent ID: 2954912e-f045-38cc-4fa8-7e1d706bcf5c
* Content: [BrightnessOverride.GetForCurrentView Method (Windows.Graphics.Display) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.brightnessoverride.getforcurrentview)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Thanks, @KevinKennedy, I have an update in the publishing pipeline right now, and I'll make sure it makes its way to the live site.

Meanwhile I'll close this issue.

Thanks again,
Steve
