### ISSUE TITLE
Update link

### ISSUE THREAD

**Issue by Jace-Samsung** [MicrosoftDocs/winrt-api#485]
The links to PickSingleFileAsync method should probably be updated to point to:
https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.picksinglefileasync#Windows_Storage_Pickers_FileOpenPicker_PickSingleFileAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4cb107-8295-b904-c1ca-728848351fe0
* Version Independent ID: 0e8b60c5-e4ae-a743-b5aa-f97b22fb78e0
* Content: [StorageFile Class (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageFile#Windows_Storage_StorageFile_GetFileFromPathAsync_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Jace-Samsung** [comment]
Also, a few other links that point to URLs beginning with "https://docs.microsoft.com/en-us/uwp/api/storagefile_", such as GetFileFromPathAsync and GetFileFromApplicationUriAsync, should probably be updated to the appropriate URLs beginning with "https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile."

**Comment by hkhmsft** [comment]
Closing this Issue as the links have since been fixed. Appreciate your contribution, @Jace-Samsung !
