### ISSUE TITLE
confusing sentence

### ISSUE THREAD

**Issue by seanmcd-msft** [MicrosoftDocs/winrt-api#487]
doc currently says:
--
It also assumes that the data in the buffer is contiguous, meaning that no IBuffer implicitly has the same format/width/height/color-space/alpha-mode/dpi. 
--
is the word 'no' supposed to be 'the' ?  if not, then this doesn't make sense to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9f01038-7c63-4b60-a8a8-c6f71965427e
* Version Independent ID: 6d9dc954-45ab-8530-2671-7e4084e1b6c9
* Content: [SoftwareBitmap.CopyFromBuffer(IBuffer) Method (Windows.Graphics.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.softwarebitmap.copyfrombuffer#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Sincere apologies for the long delay in addressing this issue. It appears that the sentence in question was a superfluous restatement of the first sentence in the paragraph, so it has been removed. You should see the change live on the site tomorrow. Thanks for helping to improve the documentation.
