### ISSUE TITLE
How to choose which display to record?

### ISSUE THREAD

**Issue by AdamSzofran** [MicrosoftDocs/winrt-api#488]
I'm writing a UWP app that uses the ProjectionManager API to open a secondary page of my app on another monitor. Using the Windows UI (Win+Alt+R) I can record the contents of the projector display. However, using AppRecordingManager.StartRecordingToFileAsync I can only record the display on which my app originally launched, not the projector display. How do I record the projector display in code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fed651da-16ea-7286-4ff6-70e24b6b11f6
* Version Independent ID: 0aa578c8-af81-8054-24ac-b4206eaf91be
* Content: [AppRecordingManager.StartRecordingToFileAsync(StorageFile) Method (Windows.Media.AppRecording) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.apprecording.apprecordingmanager.startrecordingtofileasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.apprecording.apprecordingmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.apprecording.apprecordingmanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by Zofware** [comment]
Hi Drew,

I was able to satisfy my requirements by using [Windows.Graphics.Capture](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture?view=winrt-19041).

Thanks,
Adam
