### ISSUE TITLE
Why isn't Guid linked to its doc page?

### ISSUE THREAD

**Issue by cctile** [MicrosoftDocs/winrt-api#489]
Why isn't Guid linked to its doc page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 475a9bf2-9772-540b-0ccf-dbc2408c85c6
* Version Independent ID: a2cc6a86-505b-0a9a-f1f8-1afad2dc5eb8
* Content: [BluetoothLEAdvertisement.ServiceUuids Property (Windows.Devices.Bluetooth.Advertisement) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement.serviceuuids#Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisement_ServiceUuids)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisement.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @cctile. Thanks for filing this issue, and my apologies for the delay in responding.

This is a good idea, so I've gone ahead and published an update to the topic to add a link to [GUID](https://docs.microsoft.com/windows/win32/api/guiddef/ns-guiddef-guid). I've done the same across the documentation each time GUID is mentioned.

I'll go ahead and close the issue now.

Thanks!
Steve
