### ISSUE TITLE
Why isn't List linked to its doc page?

### ISSUE THREAD

**Issue by cctile** [MicrosoftDocs/winrt-api#490]
Why isn't List linked to its doc page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 475a9bf2-9772-540b-0ccf-dbc2408c85c6
* Version Independent ID: a2cc6a86-505b-0a9a-f1f8-1afad2dc5eb8
* Content: [BluetoothLEAdvertisement.ServiceUuids Property (Windows.Devices.Bluetooth.Advertisement) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement.serviceuuids#Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisement_ServiceUuids)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.advertisement.bluetoothleadvertisement.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @cctile. Thanks for filing this issue, and my apologies for the delay in responding.

This is a good idea. The actual Windows Runtime type is IVector (which is IList when projected into a .NET language). So I've published an update to the topic to link to IVector (which then sends .NET developers to IList, so I think linking just to IVector will cover all languages). I'll go ahead and close this issue.

Thanks again!
Steve
