### ISSUE TITLE
Can this be linked to backgroundtransferstatus?

### ISSUE THREAD

**Issue by PeterSmithRedmond** [MicrosoftDocs/winrt-api#493]
It would be quicker to navigate if this topic had a "see also" (or similar) to the BackgroundTransferStatus enum docs (e.g., at https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgroundtransferstatus )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d74020d-8373-8ffc-c8ac-6a55913fb45d
* Version Independent ID: 107d8719-4594-2c4a-8c71-4b683bd20e2d
* Content: [BackgroundDownloadProgress.Status Field (Windows.Networking.BackgroundTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgrounddownloadprogress.status)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloadprogress.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.backgrounddownloadprogress.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Good idea, I've merged in a fix; expect it to be live tomorrow am.

**Comment by stevewhims** [comment]
I'll close: the link is live now, inline in the API description. ~Steve
