### ISSUE TITLE
HolographicQuadLayerUpdateParameters.AcquireBufferToUpdateContent - More information required to use returned surface

### ISSUE THREAD

**Issue by jjhegedus** [MicrosoftDocs/winrt-api#494]
[Enter feedback here]
According to the documentation, HolographicQuadLayerUpdateParameters.AcquireBufferToUpdateContent returns IDirect3DSurface.  It is possible to retrieve what appears to be valid HolograhpicQuadLayerUpdateParameters by calling GetQuadLayerUpdateParameters on an active and properly rendering HolographicFrame.  And calling AcquireBufferToUpdateContent returns what appears to be a valid IDirect3dSurface.

```
HolographicQuadLayerUpdateParameters quadLayerUpdateParameters = holographicFrame.GetQuadLayerUpdateParameters(textBillboard.quadLayer);
quadLayerUpdateParameters.UpdateExtents(winrt::Windows::Foundation::Numerics::float2(96, 96));
quadLayerUpdateParameters.UpdateLocationWithDisplayRelativeMode(float3{0.f, 0.f, 0.f}, quaternion::identity());

IDirect3DSurface direct3DSurface = quadLayerUpdateParameters.AcquireBufferToUpdateContent();
```

However, it does not seem possible to get a valid ID3D11Resource using GetDXGIInterface or GetDXGIInterfaceFromObject from <windows.graphics.directx.direct3d11.interop.h> below is some example code.

```
winrt::com_ptr<ID3D11Resource> resource;
HRESULT hr = GetDXGIInterfaceFromObject(direct3DSurface, IID_PPV_ARGS(resource.put()));
winrt::check_hresult(hr);
```

This GetDXGIInterfaceFromObject returns "E_NOINTERFACE No such interface supported."

It does appear possible to get a valid IDXGISurface using the following code

```
winrt::com_ptr<IDXGISurface> dxgiSurface;
HRESULT hr = GetDXGIInterface<IDXGISurface>(direct3DSurface, dxgiSurface.put());
```

Unfortunately it does not seem possible to get a valid ID3D11Texture2D from this.  The QueryInterface below also returns "E_NOINTERFACE No such interface supported."

```
winrt::com_ptr<ID3D11Texture2D> tex2d = nullptr;
hr = dxgiSurface->QueryInterface(IID_ID3D11Texture2D, tex2d.put_void());
```

It also does not seem possible to get a usable Direct2D render target from the IDXGISurface.

```
D2D1_RENDER_TARGET_PROPERTIES props = D2D1::RenderTargetProperties(
    D2D1_RENDER_TARGET_TYPE_DEFAULT,
    D2D1::PixelFormat(DXGI_FORMAT_UNKNOWN, D2D1_ALPHA_MODE_PREMULTIPLIED),
    96,
    96
);

winrt::com_ptr<ID2D1RenderTarget>           d2dRenderTarget = nullptr;
hr = appState.d2dFactory->CreateDxgiSurfaceRenderTarget(dxgiSurface.get(), &props, d2dRenderTarget.put());
```

This code results in an exception and the following error from the D2D Debug Layer

D2D DEBUG ERROR - The DXGI format passed into this API is not supported by Direct2D.
ndtechHolo.exe has triggered a breakpoint.

It is not clear how the IDirect3DSurface returned from HolographicQuadLayerUpdateParameters.AcquireBufferToUpdateContent is intended to be used to update the content rendered by the HolographicQuadLayer.  More description is needed and an example would be preferred since this code does not appear to be in use anywhere accessible via the world wide web, or at least not searchable via Bing or Google.

In addition to the problems identified above, there are even more basic problems in that when nothing is done with the HolographicQuadLayer except to Append it to the holographicCamera QuadLayers list, as in the code below.

```
HolographicQuadLayer quadLayer{winrt::Windows::Foundation::Size(96, 96), winrt::Windows::Graphics::DirectX::DirectXPixelFormat::R8G8B8A8IntNormalized};
HolographicQuadLayerUpdateParameters quadLayerUpdateParameters = holographicFrame.GetQuadLayerUpdateParameters(quadLayer);
quadLayerUpdateParameters.UpdateExtents(winrt::Windows::Foundation::Size(96, 96));
quadLayerUpdateParameters.UpdateLocationWithDisplayRelativeMode(float3{ 0.f, 0.f, 0.f }, quaternion::identity());

holographicCamera.QuadLayers().Append(quadLayer);
```

The next call to holographicSpace.CreateNextFrame() throws an error

Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x0343CA70.

This indicates that the HolographicQuadLayer supplied is invalid.  Unfortunately the error message itself does not indicate the nature of the invalid data and the documentation says nothing about the required data format or the potential errors that may occur.

In order for HolographicQuadLayer to be used, the documentation will need to be significantly updated to allow developers to understand the data requirements of the HolographicQuadLayer, the potential errors and their causes and how to use the IDirect3DSurface returned from HolographicQuadLayerUpdateParameters.AcquireBufferToUpdateContent.

Thanks,
Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2849f070-8ae6-b539-4e24-f7b5aec5edef
* Version Independent ID: 9d2d1c11-53d8-16f3-e8cc-4299f36779bb
* Content: [HolographicQuadLayerUpdateParameters.AcquireBufferToUpdateContent Method (Windows.Graphics.Holographic) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicquadlayerupdateparameters.acquirebuffertoupdatecontent)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicquadlayerupdateparameters.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicquadlayerupdateparameters.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by GrantMeStrength** [comment]
Hoping Alex could take a look.

**Comment by fieldsJacksonG** [comment]
Note that UpdateExtents takes inputs as meters (not pixels) and UpdateLocationWithDisplayRelativeMode takes a position relative to the camera, so the zero vector will be at the head location, and won't be seen.

You may get an error if you attempt to create a new frame before the quad buffer has been presented.  If you are presenting with HolographicFramePresentWaitBehavior::DoNotWaitForFrameToFinish, be sure to call holographicSpace.WaitForNextFrameReady(); before creating your next frame.

some sample code showing how to copy a texture into the quad layer's surface:

Note that this sample code clears and re-adds the quad layers every frame.  You can improve performance by only updating the quad layers when their position has changed.

Setup:
```
struct QuadLayer
{
public:
	QuadLayer(HolographicQuadLayer quadLayer)
		: quadLayer(quadLayer)
	{ }

	ID3D11Texture2D* texture;
	HolographicQuadLayer quadLayer;
};

std::vector<QuadLayer> quadLayers;

void AddQuadLayer(ID3D11Texture2D* quadLayerTexture)
{
	D3D11_TEXTURE2D_DESC desc;
	quadLayerTexture->GetDesc(&desc);

	HolographicQuadLayer quadLayer = HolographicQuadLayer(winrt::Windows::Foundation::Size((float)desc.Width, (float)desc.Height), DirectXPixelFormat::B8G8R8A8UIntNormalized);

	QuadLayer layer(quadLayer);
	layer.texture = quadLayerTexture;

	quadLayers.push_back(layer);
}
```

Render:
```
holographicCamera.QuadLayers().Clear();

for (QuadLayer layer : quadLayers)
{
	holographicCamera.QuadLayers().Append(layer.quadLayer);

	auto quadLayerUpdateParams = holographicFrame.GetQuadLayerUpdateParameters(layer.quadLayer);

	IDirect3DSurface surface = quadLayerUpdateParams.AcquireBufferToUpdateContent();

	ComPtr<IDXGISurface2> quadLayerBackBufferSurface;
	winrt::check_hresult(
		surface.as<::Windows::Graphics::DirectX::Direct3D11::IDirect3DDxgiInterfaceAccess>()->GetInterface(
			IID_PPV_ARGS(&quadLayerBackBufferSurface)));

	UINT32 subresourceIndex = 0;
	ComPtr<ID3D11Texture2D> quadLayerBackBuffer;
	winrt::check_hresult(quadLayerBackBufferSurface->GetResource(IID_PPV_ARGS(&quadLayerBackBuffer), &subresourceIndex));

	context->CopyResource(
		quadLayerBackBuffer.Get(),
		layer.texture);

	quadLayerUpdateParams.UpdateExtents({ 1, 1 });
	quadLayerUpdateParams.UpdateLocationWithDisplayRelativeMode(float3{ 0.f, 0.f, -2.f }, quaternion::identity());
}
```

**Comment by drewbatgit** [comment]
@jjhegedus This channel is intended for issues specific to the documentation and not general support requests, but I was able to get some example code from a dev that illustrates the correct way to get from an IDirect3DSurface to an ID3D11Texture2D. From the developer "There is one extra step here which might not be obvious to developers – you need to acquire the subresource from the texture’s DXGI surface interface."

```cpp
auto quadLayerUpdateParams = holographicFrame.GetQuadLayerUpdateParameters(quadLayer);

IDirect3DSurface surface = quadLayerUpdateParams.AcquireBufferToUpdateContent();

ComPtr<IDXGISurface2> quadLayerBackBufferSurface;
winrt::check_hresult(
    surface.as<::Windows::Graphics::DirectX::Direct3D11::IDirect3DDxgiInterfaceAccess>()->GetInterface(
        IID_PPV_ARGS(&quadLayerBackBufferSurface)));

UINT32 subresourceIndex = 0;
ComPtr<ID3D11Texture2D> quadLayerBackBuffer;
winrt::check_hresult(quadLayerBackBufferSurface->GetResource(IID_PPV_ARGS(&quadLayerBackBuffer), &subresourceIndex));

ComPtr<ID3D11RenderTargetView> spQuadLayerRenderTargetView;
winrt::check_hresult(
    m_deviceResources->GetD3DDevice()->CreateRenderTargetView(
        quadLayerBackBuffer.Get(),
        nullptr,
        &spQuadLayerRenderTargetView));

m_deviceResources->GetD3DDeviceContext()->ClearRenderTargetView(
    spQuadLayerRenderTargetView.Get(),
    DirectX::Colors::Tomato);
```

For further support on this issue. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.

**Comment by jjhegedus** [comment]
Thanks Drew.  That definitely helps.  Is there any way we could update the example on this page - https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicquadlayerupdateparameters.acquirebuffertoupdatecontent?source=docs.  I could edit everything except the example here https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.graphics.holographic/holographicquadlayerupdateparameters_acquirebuffertoupdatecontent_748006292.md/#L0.  I would have submitted a pull request but I couldn't figure out how to update the example which I what I think is most important.

**Comment by drewbatgit** [comment]
@jjhegedus As a result of the issue you raised and some others, we are working on adding more samples throughout the HoloLens docs for issues like these, but the effort is still in the planning phase. I just didn't want you to have to wait for the docs to be updated.

**Comment by jjhegedus** [comment]
Thanks Drew.  I appreciate the early update.
