### ISSUE TITLE
Purpose of SoftwareBitmap

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#495]
I'm finding it impossible to work out how to use SoftwareBitmap, it can't be consumed directly by UI::Composition that I can see, and so can't be used in CoreApp's. It begs the question, if this doesn't worth with CoreApp's, then what's it for? XamlApp has Writeable Bitmap already which is fine for reasonably performant software rendering. So what is the purpose of SoftwareBitmap. Am I missing something to be able to use this thing easily?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eec6e5e4-d6fa-50e5-d197-5e0555df4214
* Version Independent ID: 6ef061aa-fe44-add2-efe6-f0c02b18e5c6
* Content: [SoftwareBitmap Class (Windows.Graphics.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Graphics.Imaging.SoftwareBitmap)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.softwarebitmap.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by lmadhavan** [comment]
The classes in this namespace (Windows.Graphics.Imaging) are basically wrappers around the native WIC APIs, which is primarily used for low-level bitmap encoding, decoding and metadata access. SoftwareBitmap isn't really meant to be used directly with XAML, however it does provide DirectX interop and you can use use the Win2D library to load a SoftwareBitmap into a CanvasBitmap and display it on a XAML CanvasControl.

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
