### ISSUE TITLE
maxLevel wrong name for this API

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#499]
Why is this API has a parameter named "max" if the actual meaning is the "minimum" this is confusing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41f1ffd2-0d16-738d-078d-4d2885aca170
* Version Independent ID: 54af467a-903b-dc07-b68d-ea2527c68afb
* Content: [FileLoggingSession.AddLoggingChannel Method (Windows.Foundation.Diagnostics) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.diagnostics.fileloggingsession.addloggingchannel?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Foundation.Diagnostics.FileLoggingSession.AddLoggingChannel)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.diagnostics.fileloggingsession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.diagnostics.fileloggingsession.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Hi Juan,

Thank you for pointing this out. I checked the code and the name is accurate. It is an unfortunate name for that parameter, but the documentation is correct. If you'd like to comment to the product team and recommend that they change the name, please use the **Product feedback** link, as opposed to the **Documentation feedback** link.

Thanks!
 - Mark
