### ISSUE TITLE
What is the limit of RoamingSettings?

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/winrt-api#500]
What is the limit of RoamingSettings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ebfd899-c97f-fdb8-1778-8b5165d42bac
* Version Independent ID: 2f7b0b36-e540-1e51-5de2-0ebdf0aad1df
* Content: [ApplicationData.RoamingSettings Property (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.roamingsettings#Windows_Storage_ApplicationData_RoamingSettings)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdata.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdata.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by tqk2811** [comment]
[100kb](https://stackoverflow.com/questions/35385645/uwp-is-the-size-of-roaming-applicationdata-the-file-actual-size-or-size-on-disk) 

[RoamingStorageQuota](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data) that example say 100kb

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
