### ISSUE TITLE
Dead Links

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/winrt-api#505]
Link references to **RegisterPropertyChangedCallback** and **UnregisterPropertyChangedCallback** on this page return HTTP 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d24233-2ab0-4243-9590-bbb5609ee6d0
* Version Independent ID: 6b7bbda7-915c-9fdd-52f6-e8ab6d00120a
* Content: [DependencyPropertyChangedCallback Delegate (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencypropertychangedcallback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.dependencypropertychangedcallback.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.dependencypropertychangedcallback.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
