### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by luisfelipesv** [MicrosoftDocs/winrt-api#506]
Isn't TextBlock supposed to inherit from Control and not directly from FrameworkElement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ad25f2-d06e-135c-240c-99c8a0cfa728
* Version Independent ID: eccc6b3a-5607-158c-2ed6-949293923f2d
* Content: [TextBlock Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textblock#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textblock.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textblock.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by MikeHillberg** [comment]
TextBlock does derive directly from FrameworkElement.  TextBox derives from Control.
