### ISSUE TITLE
1232123

### ISSUE THREAD

**Issue by 958877748** [MicrosoftDocs/winrt-api#507]
function selectNESFile() {
    let picker = new Windows.Storage.Pickers.FileOpenPicker();
    picker.ViewMode = Windows.Storage.Pickers.PickerViewMode.Thumbnail;
    picker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.PicturesLibrary;
    picker.fileTypeFilter.push(".nes");
    picker.pickSingleFileAsync().then(function (file) {
        if (file != null) {
            //文件拿到
            Windows.Storage.FileIO.readBufferAsync(file).then(
                function (buffer) {
                    //let dataReader = Windows.Storage.Streams.DataReader.fromBuffer(buffer);
                    //let count = buffer.length/8;
                    //dataReader.unicodeEncoding = Windows.Storage.Streams.UnicodeEncoding.utf16BE;
                    //let str = dataReader.readString(count);

                    let str = buffer;
                    nes.loadROM(str);

                    
                }
            );
        }
        else {
            //文件没拿到,再拿
            selectNESFile();
        }
    });
}
selectNESFile();
写了上边这么多 还是报错,搞不懂
读一个文件转成字符串,困难重重,人家用node.js 这么简单就完了
const fs = require('fs');
var romData = fs.readFileSync('../rom/game.nes', { encoding: 'binary' });

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9361bb5c-c2a4-0cea-5bf8-1a0aef9a6d2f
* Version Independent ID: f6a5326a-e275-7e8f-a9bb-46606d46aeec
* Content: [IBuffer Interface (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.Streams.IBuffer#Windows_Storage_Streams_IBuffer_Length)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.ibuffer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.ibuffer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by 958877748** [comment]
但是在js里怎么用node 的模块,更难,看了一天,require('fs'); 还是报错

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
