### ISSUE TITLE
publisherUserId isn't optional

### ISSUE THREAD

**Issue by bezysoftware** [MicrosoftDocs/winrt-api#508]
The docs say publisherUserId is optional, but it isn't (it must be set in code)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f85bf6-849d-020a-7c1b-fc949e102eee
* Version Independent ID: 26ce2d38-6da1-59f2-88dd-f386ba61f2e1
* Content: [StoreContext.GetCustomerPurchaseIdAsync(String, String) Method (Windows.Services.Store) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.getcustomerpurchaseidasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storecontext.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storecontext.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. I have revised the description for this parameter to clarify that it is not optional.
