### ISSUE TITLE
Other values can show up here

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/winrt-api#509]
For example if a PushNotificationTrigger is registered, this field will contain a RawNotification object. This information is CRITICAL to respond to a background Push notification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1a6384-e7cc-470d-c621-8d104164ef0d
* Version Independent ID: 7878d44c-643d-691f-ff45-747e59635dd3
* Content: [IBackgroundTaskInstance.TriggerDetails Property (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.ibackgroundtaskinstance.triggerdetails#Windows_ApplicationModel_Background_IBackgroundTaskInstance_TriggerDetails)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.ibackgroundtaskinstance.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.ibackgroundtaskinstance.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
Apologies for leaving this issue unresolved for so long.

I've added this information to the article in question. Thank you.
