### ISSUE TITLE
Broken Link : RequestAccessAsync

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/winrt-api#510]
Broken link to RequestAccessAsync in the Important box, looks like it's moved to https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.geolocator.requestaccessasync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5cf370-aafa-838f-0dbd-75640537759e
* Version Independent ID: 07d3c8a5-fc31-9324-34c6-37c7892b3c19
* Content: [Windows.Devices.Geolocation Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
