### ISSUE TITLE
404 - Page not found for SetMediaPlayer 

### ISSUE THREAD

**Issue by zipswich** [MicrosoftDocs/winrt-api#512]
When I click SetMediaPlayer (https://docs.microsoft.com/en-us/uwp/api/mediaplayerelement_setmediaplayer), I get the following:

404 - Page not found
Hmm, we couldn't find this link, but here are some related search results that may be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b8bdb23-8a5d-4421-dab8-d78f52b95a19
* Version Independent ID: 4c739d1d-a8ba-9b09-71cc-0fd6b04095cf
* Content: [MediaPlayerElement Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaplayerelement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.mediaplayerelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.mediaplayerelement.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
