### ISSUE TITLE
Can this be used in C++?

### ISSUE THREAD

**Issue by JBradon** [MicrosoftDocs/winrt-api#513]
If so could you please add a section "Enumerating the collection in C++"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aef02eb-7867-a4a2-0cca-4a41bed7d72a
* Version Independent ID: 502edaff-708b-9776-2712-76c5057c8c84
* Content: [PnpObjectCollection Class (Windows.Devices.Enumeration.Pnp) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.pnp.pnpobjectcollection)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.pnp.pnpobjectcollection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.pnp.pnpobjectcollection.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @JBradon, thanks for raising this issue. Yes, all collections can be enumerated using C++ (C++/WinRT being the current recommended projection of the Windows Runtime into C++). I've just edited this topic and that change will be live within 24 hours. Meanwhile, FYI, here's the content that I added.

### Enumerating the collection in C++/WinRT

```cppwinrt
...
using namespace Windows::Devices::Enumeration::Pnp;
...
void EnumerateCollection(PnpObjectCollection const& collection)
{
    for (PnpObject const& object : collection)
    {
        // ...
    }
}
```

Also see [Collections with C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/collections).

**Comment by JBradon** [comment]
Steve, 
Thanks - that;s helpful. 
John

**Comment by stevewhims** [comment]
You're welcome, John. Thanks for filing the issue! ~Steve
