### ISSUE TITLE
BrightnessLevel

### ISSUE THREAD

**Issue by MS-DaveH** [MicrosoftDocs/winrt-api#516]
Can we add a note to clarify, does BrightnessLevel represent the current system temp if I retrieve Brightness Override using GetForCurrentView()? What about GetDefaultForSystem()? I've seen multiple questions about this in forums.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09243f27-7f60-4778-3815-5706b797e70d
* Version Independent ID: 0091221e-6f25-c5ae-6620-9fae55ca537b
* Content: [BrightnessOverride Class (Windows.Graphics.Display) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.display.brightnessoverride)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.display.brightnessoverride.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by kwiqniss** [comment]
Note, this is very similar to issue 514, but for a separate article on the larger topic.

**Comment by MS-DaveH** [comment]
Note, this is very similar to issue 514, but for a separate article on the larger topic.

**Comment by kwiqniss** [comment]
I filed this with an account that wasn't linked. Commenting here with the proper account.

**Comment by stevewhims** [comment]
Hi, David, it's been a very long time since you filed this issue, and it's only just gotten attention. To answer this question we'll need to reach out to the feature team. If I get the info, then I can update the topic. So I'll start an internal email thread about this now, and I'll close this issue.

Thanks!
Steve

**Comment by mylim83** [comment]
Hi guys, any update on this issue? I would like to know too...
Please share.. Thanks.

**Comment by stevewhims** [comment]
Hi, @mylim83, I've updated the topic with more info.

Thanks!
Steve

**Comment by ELVdev** [comment]
@stevewhims Thanks! 
However, seems like it's still unsupported for Window IoT Core. :(
