### ISSUE TITLE
The API is present is Windows Phone but does not function

### ISSUE THREAD

**Issue by WDev20** [MicrosoftDocs/winrt-api#518]
The Ussd protocol API does not work in Windows Phone 10, I've tried sideloading the test app and using the required permissions, but it gives me a COMException with message: "The request is not supported". Is there a way to workaround this limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75cbc922-237f-68e8-f87a-5f50af349096
* Version Independent ID: 4620abe9-10ea-752f-a1df-e29409b360e2
* Content: [UssdSession Class (Windows.Networking.NetworkOperators) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.NetworkOperators.UssdSession)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.networkoperators.ussdsession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.networkoperators.ussdsession.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Thanks for raising this issue, @WDev20. I'll discuss this with the product team and I'll get back to you with info when I have it. ~Steve

**Comment by stevewhims** [comment]
Hi, @WDev20, there isn't a workaround. **UssdSession** is applicable to Windows 10 for desktop form factors (MBIM-based modems), but not to Windows 10 Mobile (RIL-based modems). I've just merged a change with that additional info into master; I expect the live topic to be updated within 24 hours. ~Steve

**Comment by stevewhims** [comment]
Thanks for the info, @WDev20! The additional info is now live in the topic, so I'll close this issue. Please reopen if necessary. ~Steve.
