### ISSUE TITLE
Exceptions section is missed

### ISSUE THREAD

**Issue by GDreyV** [MicrosoftDocs/winrt-api#519]
Please keep in mind that this method throws exception If there isn't any elements in storage. Moreover it throws different exceptions in Debug and Release mods. For Debug it's System.Runtime.InteropServices.COMException and in Release it's System.Exception. So id doesn't make any sense to check if returned collection is empty or not as it's always not empty (if no exception thrown).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1dd0828-0934-443e-b5b6-8a8b75d00dde
* Version Independent ID: 8118e607-52b6-f76c-0c2d-ff4014a3ea0d
* Content: [PasswordVault.FindAllByResource(String) Method (Windows.Security.Credentials) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.passwordvault.findallbyresource?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Security.Credentials.PasswordVault.FindAllByResource)%3Bk(SolutionItemsProject)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.credentials.passwordvault.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.credentials.passwordvault.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @GDreyV, thanks for raising this issue, and sorry for the delay in getting back to you. I'm investigating this at the moment, and that'll involve talking to the product team to get the official info on what kind of exception-handling we expect folks to need to do with these APIs. It sounds like you're using C# with these APIs, is that correct?

Thanks again!
~Steve

**Comment by stevewhims** [comment]
Yes, this is in fact a known issue. There's currently a work item in the works to get this fixed. In the spirit of full disclosure and cooperation, until this has been completely fixed and documented, I'll give you all the info I have on the problem in case it helps you at all in your development against these APIs.

The scope of the problem: when you call for example Retrieve, RetrieveAll, FindAllByResource, or FindAllByUserName, if there is nothing to be found, then the call returns 0x80070490. And that projects as an exception. The APIs should not do that: exceptions are for errors in programming against the APIs (errors that can be fixed at development/debug time), and not for general error conditions that the app needs to protect against in production.

The fact is that there is currently no way to use the PasswordVault and guarantee that you will not get an exception. Specifically:

- PasswordVault.RetrieveAll throws if the password vault is empty, but the only way to know whether the password vault is empty is to retrieve items from it and see whether you get anything.
- PasswordVault.Retrieve throws if the item is not present in the password vault, but the only way you know whether the item is present is to try to retrieve it.
- PasswordVault.Remove throws if the item is not present, but the end user can manually remove items from the password vault via the Credential Manager control panel, so the app has no guarantee that any password credential added to the vault will still be there at any point in the future.
- PasswordCredential.RetrievePassword throws if the user removed the item from the password vault via the Credential Manager control panel.

**Comment by stevewhims** [comment]
I'll go ahead and close this doc issue for now. Once the APIs are corrected, then we'll loop back and make appropriate updates to the docs. But since the focus here is more on an API issue (which we're already tracking internally) rather than on documentation specifically, then it feels correct to close this issue.

~Steve
