### ISSUE TITLE
More description is needed for all the printing properties

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/winrt-api#520]
For all the printing properties, more description is needed!

What is hole punch, binding, bordering, InputBin, etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff22bd4-874c-f8b3-029b-77ff57165b6a
* Version Independent ID: fd18196b-c25b-e82f-48e2-a6fda92ffa9d
* Content: [StandardPrintTaskOptions.HolePunch Property (Windows.Graphics.Printing) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.printing.standardprinttaskoptions.holepunch)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.standardprinttaskoptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.standardprinttaskoptions.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the delay in responding. I have added new remarks and see also links to StandardPrintTaskOptions and all of its members to help provide more context about the purpose of each member, including links to the official [UWP printing sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing) and the [Customize the print preview UI](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/customize-the-print-preview-ui) article. These changes will be published to the live site within the next day or so.
