### ISSUE TITLE
Broken link for CompositionObject::StartAnimation

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#526]
https://docs.microsoft.com/en-us/uwp/api/compositionobject_startanimation leads to a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc66dab8-b0c2-a5c0-0eaf-14e26f94f74c
* Version Independent ID: 417754fb-e004-222f-4f20-26e9bc7aa4b0
* Content: [ScalarKeyFrameAnimation Class (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Composition.ScalarKeyFrameAnimation)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.scalarkeyframeanimation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.scalarkeyframeanimation.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
