### ISSUE TITLE
Broken links on Pointer Class page

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/winrt-api#527]
There are broken links to GetCurrentPoint and GetIntermediatePoints methods, leading to 404 pages:
https://docs.microsoft.com/en-us/uwp/windows.ui.input/pointerpoint_getintermediatepoints.md
https://docs.microsoft.com/en-us/uwp/api/pointerroutedeventargs_getcurrentpoint
There might be other broken links, not tested all of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee94e1fc-9cd1-5c50-7d38-544e56d79777
* Version Independent ID: 1f764361-1cc5-788b-ede0-c75d407b9e2a
* Content: [Pointer Class (Windows.UI.Xaml.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.pointer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.pointer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.pointer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
