### ISSUE TITLE
PointerCanceled missing in CoreComponentInputSource

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/winrt-api#528]
Just wondering, why is there no PointerCanceled event in CoreComponentInputSource?  
The UIElement has the same set of events with this only difference.  
  
I just spent half day debugging one issue where the CoreComponentInputSource.PointerReleased is not called reliably when I focus another element in a wrong moment. Having PointerCanceled might have been the fix here.  

Same question goes for CoreIndependentInputSource.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 2d9133c9-df09-7b73-b8c9-23912821f366
* Version Independent ID: 4c0b53fe-5151-71aa-e402-8413b3fe013b
* Content: [CoreComponentInputSource Class (Windows.UI.Core) - UWP app developer](https://docs.microsoft.com/cs-cz/uwp/api/windows.ui.core.corecomponentinputsource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecomponentinputsource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecomponentinputsource.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
My apologies for the delayed response to this issue.

I'm afraid that this feedback channel only covers specific documentation fixes, so I can't tell you why that particular event isn't handled by this API, only that it's not. If this is still a question you need answered, I'd recommend that you'd ask the community of experts and Microsoft engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).

I'll be marking this issue closed for now, but thank you for your question and contribution.
