### ISSUE TITLE
Link to GetInkPoints on InkStroke.GetRenderingSegments Method is 404

### ISSUE THREAD

**Issue by ChumpChief** [MicrosoftDocs/winrt-api#529]
On page https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.inking.inkstroke.getrenderingsegments

I believe the link should be https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.inking.inkstroke.getinkpoints but instead is https://docs.microsoft.com/en-us/uwp/api/inkstroke_getinkpoints

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91980bb-2701-c4d2-3f27-c35cf2d2ff89
* Version Independent ID: 3eadc58e-c5ba-6a43-d14d-102b8f6a1fd7
* Content: [InkStroke.GetRenderingSegments Method (Windows.UI.Input.Inking) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.inking.inkstroke.getrenderingsegments)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.inking.inkstroke.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.inking.inkstroke.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
