### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#530]
The AudioFrameOutputNode.GetFrame hyperlink is broken. Consider using https://docs.microsoft.com/en-us/uwp/api/windows.media.audio.audioframeoutputnode.getframe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d73e9c-d8f4-ac97-503e-f878358a67a7
* Version Independent ID: 91cdf43b-15cd-e2ba-45a5-c771b22c9c96
* Content: [AudioGraph.QuantumProcessed Event (Windows.Media.Audio) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.audio.audiograph.quantumprocessed)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audiograph.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.audio.audiograph.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
