### ISSUE TITLE
References to IDictionary and ICollection are not links

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#531]
You can see several references in this doc to things like ```System.Collections.Generic.IDictionary`2.Add(`0,`1)```. It seems like these things were intended to be links. There are some in the "See Also" section and some outside of it.

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6dd1542-eb79-4a77-bc94-717598a7d78a
* Version Independent ID: cea7f775-1e01-b306-bdc5-b78fa69b541b
* Content: [IDictionary&lt;TKey, TValue&gt;.Item Property (System.Collections.Generic) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.valueset.item#Windows_Foundation_Collections_ValueSet_Item__0_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.valueset.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.collections.valueset.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
This page no longer exists. I'm going to close this issue.
