### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by AdamSzofran** [MicrosoftDocs/winrt-api#532]
The See Also link for "Composition visual without framework sample (Windows 10)" points to the wrong page. It should point to: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CompositionVisual

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 724827cf-15a5-d5d6-5679-b4712d2c03ee
* Version Independent ID: cc05a8ff-4afb-bf61-fb81-fe02bf1bb7a0
* Content: [Compositor Class (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositor.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositor.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks. This link has been fixed.
