### ISSUE TITLE
What's the difference between `SwitchAsync(Int32)` and `SwitchAsync(Int32, Int32)`?

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#533]
From reading the documentation, it's unclear to me when I would want to use `SwitchAsync(Int32)` vs `SwitchAsync(Int32, Int32)`. The latter takes an extra parameter but the documentation doesn't indicate how the API uses that parameter. Both APIs have an identical description: "Visually replaces the calling window (app view) with a specified window."

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4757641d-4f21-7b5e-8450-330f197d0734
* Version Independent ID: e87f9e89-4051-14e8-ce7c-20754bf36ab6
* Content: [ApplicationViewSwitcher.SwitchAsync Method (Windows.UI.ViewManagement) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationviewswitcher.switchasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.applicationviewswitcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.viewmanagement.applicationviewswitcher.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by daniedr** [comment]
Hi Adam,

The primary difference between two calls is that `SwitchAsync(Int32)` requires the caller make the call from the ASTA thread of the view desired to be replaced as the "from" view. By calling from the ASTA thread of that view, it is implicitly determined by the API call. The `SwitchAsync(Int32, Int32)` call allows the specification of the view to switch from, which frees the caller from executing the call on the ASTA thread of the "from" view. By explicitly passing the same view ID as would be inferred via the `SwitchAsync(Int32)` call, the outcome of the calls are identical.

Danny Draper

**Comment by rigdern** [comment]
@daniedr thanks for the explanation! Can we update the docs to make this relationship clearer?

Is the doc for `SwitchAsync(Int32, Int32)` incorrect in that it says "Visually replaces the calling window (app view) with a specified window."? Is there really a "calling window" in this context or should it use the term "fromViewId" instead of "calling window"?

I think it would be helpful to mention in the `SwitchAsync(Int32)` doc that it's like `SwitchAsync(Int32, Int32)` except it infers the `fromViewId` parameter based on what dispatcher it's called from.

Any update you make to the `SwitchAsync(Int32, Int32)` doc should probably also be made to the `SwitchAsync(Int32, Int32, ApplicationViewSwitchingOptions)` doc.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @rigdern - topics have been revised for clarity. Please review and open a new issue if updates are not adequate.

**Comment by rigdern** [comment]
@Karl-Bridge-Microsoft thanks for the update. Where can I see the changes? I looked through the [history of windows.ui.viewmanagement/applicationviewswitcher.md](https://github.com/MicrosoftDocs/winrt-api/commits/docs/windows.ui.viewmanagement/applicationviewswitcher.md) but couldn't find any commits related to this issue.

**Comment by Karl-Bridge-Microsoft** [comment]
The updates are made in a private branch that can take some time to propagate. Barring pipeline issues, the updates should be live by tomorrow.
