### ISSUE TITLE
 API contract version is missing for Application events

### ISSUE THREAD

**Issue by mogikanin** [MicrosoftDocs/winrt-api#534]
Minimal API contract version is missing. The same for `LeavingBackground` event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83ac29f3-e779-338d-3f36-879fcc1acd57
* Version Independent ID: 7055801b-e684-f795-f742-3b67bd12deae
* Content: [Application.EnteredBackground Event (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.enteredbackground?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Application.EnteredBackground)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.application.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
The API version doesn't seem to be on any Properties/Methods/Events  when I was clicking around. It was appearing on the root class docs though. @mijacobs  can you help?

**Comment by mijacobs** [comment]
Forwarded to docs engineering.

**Comment by mijacobs** [comment]
Filed a work item to track, closing the issue.
