### ISSUE TITLE
Missing info about Pin and Person cursors

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/winrt-api#535]
The page does not show information that Pin and Person cursors are only available starting Windows 10 Version 10.0.16299.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da15f38-4a63-3242-6714-042d5742dee4
* Version Independent ID: 20fe3e6d-634d-77b0-bf93-d88f10aa7fdc
* Content: [CoreCursorType Enum (Windows.UI.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.corecursortype)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecursortype.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.corecursortype.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Doc was updated so that is shown now.
