### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#537]
The **OnNavigatedTo**, **OnNavigatingFrom**, and **OnNavigatedFrom** links, in the **Remarks** section, are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cb6376e-2c9f-10e5-24c5-56bd78a6956b
* Version Independent ID: 42069986-5904-e987-b6d4-ccede63326e1
* Content: [Page Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.page)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.page.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.page.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for letting us know. Should be fixed now.
