### ISSUE TITLE
Update link to method documentation.

### ISSUE THREAD

**Issue by Jace-Samsung** [MicrosoftDocs/winrt-api#540]
Update link to "StorageFile.getThumbnailAsync" (currently pointing to: https://docs.microsoft.com/en-us/uwp/windows.storage/storagefile_getthumbnailasync.md) to be pointing to https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getthumbnailasync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4c757c-ee40-f440-b3a4-7e98addbcbd3
* Version Independent ID: 7980ccb0-9daa-1cc5-156e-5c9cc29d6ac6
* Content: [StorageItemThumbnail Class (Windows.Storage.FileProperties) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.storageitemthumbnail)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.storageitemthumbnail.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.storageitemthumbnail.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Closing this Issue as the links have since been fixed. Appreciate your contribution, @Jace-Samsung !
