### ISSUE TITLE
Extensions?

### ISSUE THREAD

**Issue by lisardggY** [MicrosoftDocs/winrt-api#541]
This sample shows an "extension" element under the stylesheet, but this doesn't show up in the reference linked. Is there any documentation on extensions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 604a5ccd-9320-483d-fe75-20b776ff84d6
* Version Independent ID: 3c04111c-d6cf-eb99-8a2a-772a6ba0693c
* Content: [MapElement.MapStyleSheetEntry Property (Windows.UI.Xaml.Controls.Maps) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.maps.mapelement.mapstylesheetentry#Windows_UI_Xaml_Controls_Maps_MapElement_MapStyleSheetEntry)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapelement.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by normesta** [comment]
Thank you for bringing this to our attention. We've added some content that clarifies the purpose of this extension element. It should appear on the page shortly.

**Comment by normesta** [comment]
Ok. The topic has been updated with a better description of that element. Does this help?

**Comment by lisardggY** [comment]
The main problem isn't with this page specifically, but just that the Extensions mechanism described off-hand in it, in the code sample, isn't documented anywhere else I could find in the Bing Maps styling documentation.

**Comment by hickeys** [comment]
We have some new documentation pages you might be interested in, with a more complete listing of properties and entries in map stylesheets. Though they're technically accessible from the maps documentation if you click a specific series of links, the new pages aren't as discoverable as they should be. There's definitely some work to be done here on updating the UWP map documentation to consistently point to the new pages, but that will take some time. In the meantime, I'll post the links here for anyone who needs them.

[Map style sheet entries](https://docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entries)
[Map style sheet entry properties](https://docs.microsoft.com/en-us/BingMaps/styling/map-style-sheet-entry-properties)

I'll leave this issue open until I can update the maps docs properly, then close it once the links are all updated.

**Comment by hickeys** [comment]
I added a link to extensions documentation to the mapstylesheetentry doc, since it's used on that page. The rest of the documentation looks good, so I'm going to close this issue. My changes should be published sometime today.
