### ISSUE TITLE
The link is missing!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#542]
The link of the "ConvertStringToBinary" and "ConvertBinaryToString" are all missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e66b32d-61d4-01a1-8aab-7e8a9db61f94
* Version Independent ID: 2269d232-3a68-c4cf-7975-532246c64ff9
* Content: [BinaryStringEncoding Enum (Windows.Security.Cryptography) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.binarystringencoding)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.binarystringencoding.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.binarystringencoding.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Closing this Issue as the links have since been fixed. Appreciate your contribution, @moyanming !
