### ISSUE TITLE
Are ToolTips now popups?

### ISSUE THREAD

**Issue by drpritch** [MicrosoftDocs/winrt-api#543]
The docs state that "A ToolTip is also not considered a popup, it's considered a child of the element that uses the ToolTipService attached properties to host it." However, my testing in Windows 10 1803 with Live Visual Tree shows ToolTip elements under PopupRoot, and no children under the host element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: facbdac9-ed16-fd9e-dce3-e66169c9613f
* Version Independent ID: 341e059f-f94d-ec87-84f4-b4d888005780
* Content: [VisualTreeHelper.GetOpenPopups(Window) Method (Windows.UI.Xaml.Media) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.visualtreehelper.getopenpopups)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.visualtreehelper.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.visualtreehelper.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by YuliKl** [comment]
@drpritch - Tooltips have used the popup primitive as an implementation detail in, I believe, all versions of Windows 10. The statement that the documentation is making is specific to the GetOpenPopus method and not about tooltip's internal structure. This method will not return any tooltips even if one is currently visible.
