### ISSUE TITLE
VoiceCommandConfirmationResult can't handle ContentTileType.TitleWith280x140Icon && TitleWith280x140IconAndText

### ISSUE THREAD

**Issue by christian-becker-ta** [MicrosoftDocs/winrt-api#548]
It is not possible for Cortana to handle these two ContentTileTypes in ConfirmationResult. 

Can you please check it?

If you need any further Information do not hesitate.
Greetings Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec09195-0387-0f8f-5467-f652cb4ed077
* Version Independent ID: 9985092a-2764-a641-d4e1-0a2aa49bdb3c
* Content: [VoiceCommandServiceConnection.RequestConfirmationAsync(VoiceCommandResponse) Method (Windows.ApplicationModel.VoiceCommands) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.voicecommands.voicecommandserviceconnection.requestconfirmationasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.voicecommands.voicecommandserviceconnection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.voicecommands.voicecommandserviceconnection.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by christian-becker-ta** [comment]
Any Update?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @TiMeJuMp - MaxSupportedVoiceCommandContentTiles specifies the maximum number of tiles the background app service can display on the Cortana canvas.
The maximum number of tiles that can be displayed depends on the feedback screen being shown. One item when the VoiceCommandResponse is created for ReportProgressAsync or RequestConfirmationAsync, and more than one item when the VoiceCommandResponse is created for RequestDisambiguationAsync.

**Comment by christian-becker-ta** [comment]
Hi @Karl-Bridge-Microsoft, i think this isn't the answer for my question.

I'll try to explain it better.
If you create a Cortana Response with ONE ContentItem of ContentTileType.TitleWith280x140Icon, it is not possible to send it as a RequestConfirmationAsync and receive a Confirmation of the User. it only works with smaller ContentTyleTypes.  (like shown on this Site. http://www.guruumeditation.net/integration-of-an-application-to-cortana/ )

Cortana reads out the correct SpokenMessage, but show the Error Screen "AppName ran into an issue".
