### ISSUE TITLE
Example how to set the fields in XAML

### ISSUE THREAD

**Issue by BYTEzel** [MicrosoftDocs/winrt-api#549]
I'm missing an example of how to set the fields in XAML code. I would like to define myself a Thickness-property in my App.xaml file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9654762b-f3d4-6259-2b8e-874d9185be19
* Version Independent ID: 52145687-0078-79c2-2235-b24d9c5822c1
* Content: [Thickness Struct (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.thickness)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.thickness.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.thickness.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by robloo** [comment]
This doesn't seem possible and it's a fundamental oversight. We should be able to set them directly in XAML and with bindings. Once again, WPF was the pinnacle of XAML It has been downhill since :(

```
<TextBlock.Margin>
  <Thickness Left="10"
             Top="10"
             Right="10"
             Bottom="{Binding Path='BottomMargin', Mode=OneWay" />
</TextBlock.Margin>
```

**Comment by jevansaks** [comment]
I will follow up and turn this into a feature request in the Microsoft/microsoft-ui-xaml repo.

**Comment by jevansaks** [comment]
Now tracked as a feature proposal on microsoft-ui-xaml.
