### ISSUE TITLE
This can throw when given a malformed Unicode character!

### ISSUE THREAD

**Issue by pedasmith** [MicrosoftDocs/winrt-api#551]
I was totally surprised that the behavior when the text contains a malformed Unicode character is to throw. I expected instead that the text be encoded as well as possible, under the circumstances.

Kind of like how when you enter a bus, and you don't have exact change for the $2.50 fare, so you just put in 3 one-dollar bills. And the bus explodes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2be794-a63c-0875-c610-dcb41bd3dae2
* Version Independent ID: 60582cba-1c92-4b1e-1766-4724e441bce3
* Content: [PathIO.WriteTextAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pathio.writetextasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.Storage.PathIO.WriteTextAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pathio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pathio.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
