### ISSUE TITLE
Kool app

### ISSUE THREAD

**Issue by dking34** [MicrosoftDocs/winrt-api#552]
N,a

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e2f9617-2d65-38f1-1148-a20d3540997a
* Version Independent ID: 01700234-c4c7-18b1-e79f-2208c5b1281e
* Content: [GCPressureAttribute Constructor (Windows.Foundation.Metadata) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.gcpressureattribute.-ctor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.gcpressureattribute.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.gcpressureattribute.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Thanks for your feedback, @dking34.
