### ISSUE TITLE
ToolTipServicePlacement links broken

### ISSUE THREAD

**Issue by bezysoftware** [MicrosoftDocs/winrt-api#565]
They lead to https://docs.microsoft.com/en-us/uwp/api/tooltipservice_placement but this gives 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ec3c3e2-a68b-e6b3-f6ec-ffc8b8c5857a
* Version Independent ID: 9fc3a5bd-d3d7-ee11-5da8-c921f53c0ec3
* Content: [ToolTipService Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.tooltipservice)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.tooltipservice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.tooltipservice.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Links to attached properties have been updated.
