### ISSUE TITLE
Page not found on AutomationProperties.LiveSetting

### ISSUE THREAD

**Issue by Ar5ham** [MicrosoftDocs/winrt-api#567]
[Enter feedback here]
Invalid link under "See also" section, "AutomationProperties.LiveSetting" link will go "404 - page not found" page.
https://docs.microsoft.com/en-us/uwp/windows.ui.xaml.automation/automationproperties_livesetting.md 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2965160b-f231-fff6-7926-4f1ecb7ceab1
* Version Independent ID: 63adb728-1f70-2d6a-63ac-cd7c3580a4db
* Content: [AutomationLiveSetting Enum (Windows.UI.Xaml.Automation.Peers) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.peers.automationlivesetting)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.peers.automationlivesetting.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.peers.automationlivesetting.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Ar5ham - Thanks for the bug report! Unfortunately, this is structural issue with our CMS and attached property docs. Our engineering team is working on a fix, but there is no ETA. I'm closing this issue as the fix will be universal when it rolls out and is not tied to this specific topic.

**Comment by Ar5ham** [comment]
Do you have a work item or bug/issue related to the fix the engineering team is working on? If so, you might want to add related issue #.

**Comment by Karl-Bridge-Microsoft** [comment]
Sorry, internal tracking only.
