### ISSUE TITLE
Exception thrown when using OneDrive On-Demand Files

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/winrt-api#568]
The following code results in an exception being thrown when picking a file from FileOpenPicker.PickMultipleFilesAsync, when the file is a OneDrive On-Demand file, even when the file has been downloaded before.

```
                    using (StorageItemThumbnail thumbnail = await file.GetThumbnailAsync(Windows.Storage.FileProperties.ThumbnailMode.PicturesView))
                    {
                        await Bitmap.SetSourceAsync(thumbnail);
                    }
```

That throws a System.ArgumentException `The parameter is incorrect. streamSource`

Changing to use **ThumbnailMode.SingleItem** makes it work though.

Docs should be updated to note this bug (I assume this is a bug, it seems like it definitely should work, otherwise this is an AppCompat issue).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9b19b5-9b36-67ac-f224-722356a4ffc0
* Version Independent ID: aae2ca06-7de3-76fb-2b0c-995f84736f9f
* Content: [StorageFile.GetThumbnailAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getthumbnailasync#Windows_Storage_StorageFile_GetThumbnailAsync_Windows_Storage_FileProperties_ThumbnailMode_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Hi @andrewleader , it seems this Issue has remained stale since the initial submission. I'm currently assigned so I'll create an internal work item to drive this to completion. If otherwise, let me know. I'll mark this Issue as Closed now. Feel free to follow-up either directly in this thread or via Teams/email. Thanks!

**Comment by andrewleader** [comment]
Hey lastnameholiu, sounds good! I think I used this API in one of my old Windows Phone apps and I no longer maintain that app, but hopefully other people benefit from the fix!
