### ISSUE TITLE
Incorrect thumbnail obtained when calling GetThumbnailAsync on just-downloaded OneDrive On-Demand picture

### ISSUE THREAD

**Issue by andrewleader** [MicrosoftDocs/winrt-api#569]
When using FileOpenPicker.PickMultipleFIlesAsync on a not-yet-downloaded OneDrive On-Demand picture file, and then subsequently calling GetThumbnailAsync(ThumbnailMode.SingleItem), it often times just returns the generic picture icon, even though the picture is downloaded by the time that's called and **IsAvailable** returns true.

![image](https://user-images.githubusercontent.com/13246069/44378336-b6efba00-a4b5-11e8-8d6c-7856ec1ede8f.png)

The repro isn't consistent, but it happens most of the time. One time, I've had it actually correctly display the thumbnail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e9b19b5-9b36-67ac-f224-722356a4ffc0
* Version Independent ID: aae2ca06-7de3-76fb-2b0c-995f84736f9f
* Content: [StorageFile.GetThumbnailAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getthumbnailasync#Windows_Storage_StorageFile_GetThumbnailAsync_Windows_Storage_FileProperties_ThumbnailMode_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by XeorgeXeorge** [comment]
Can confirm, can recreate, this issue is frustrating.
Sometimes it returns the right thumbnail, most of the times won't.

Edit: found a workaround.

>  file.GetThumbnailAsync(Windows.Storage.FileProperties.ThumbnailMode.SingleItem, 160, Windows.Storage.FileProperties.ThumbnailOptions.UseCurrentScale))

it seems that you gotta downscale the acquisition size to a small amount like 160, this issue is probably related to the OneDrive system only caching small thumbnails to conserve bandwidth.

**Comment by hkhmsft** [comment]
If there are any significant updates you all would like to see on our documentation, please open up this thread again. Closing for now due to staleness. Many thanks.
