### ISSUE TITLE
Correct usage needs further explaination

### ISSUE THREAD

**Issue by sjb-sjb** [MicrosoftDocs/winrt-api#570]
People who want to use ContentDialog correctly should review the information on the UWP section of UserVoice. This information about the usage should be described on the ContentDialog documentation page. 

For example, extra work is required to center the content dialog and to prevent multiple dialogs from being displayed at the same time.  See https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/32946220-contentdialog-locking-and-placement 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16c14008-04b3-438b-5fae-3577cf233ab9
* Version Independent ID: 52f2f07b-034e-1d24-1b48-b4de7585e71a
* Content: [ContentDialog Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
@sjb-sjb these sound like bugs or feature requests. Can you open them on https://github.com/Microsoft/microsoft-ui-xaml/issues ?
