### ISSUE TITLE
Why is this a pre-release API?

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/winrt-api#573]
Windows 10 isn't prerelease, why is this API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc2a4feb-a073-ef7e-d102-61553041e0b1
* Version Independent ID: 269a5dba-bcf1-4ed7-5eb4-286d7d92be5d
* Content: [Border Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Border)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.border.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.border.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
It is no longer marked as such.
