### ISSUE TITLE
Two or more consecutive confirmations 

### ISSUE THREAD

**Issue by christian-becker-ta** [MicrosoftDocs/winrt-api#574]
If you ask two or more times for a confirmation in one VoiceCommand, the second, thrid... confirmation will be the same like the first one. the User has no chance to select another answer. Will this be fixed sometime?

If you need further information do not hesitate.
Christian 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dec09195-0387-0f8f-5467-f652cb4ed077
* Version Independent ID: 9985092a-2764-a641-d4e1-0a2aa49bdb3c
* Content: [VoiceCommandServiceConnection.RequestConfirmationAsync(VoiceCommandResponse) Method (Windows.ApplicationModel.VoiceCommands) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.voicecommands.voicecommandserviceconnection.requestconfirmationasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.voicecommands.voicecommandserviceconnection.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.voicecommands.voicecommandserviceconnection.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @TiMeJuMp - There are no plans to change this behavior. Thanks for your feedback!
