### ISSUE TITLE
Only first part of namespace is a link

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#575]
For example, in `Windows::System::Threading::ThreadPool::RunAsync`, I would expect the whole string to be a link (underlined and blue). Instead, only `Windows`, the first portion of the namespace, is a link.

Screen shot:

![image](https://user-images.githubusercontent.com/199935/44612679-1bb15a00-a7bf-11e8-94aa-c9d9612fb91f.png)

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331adaef-1035-fd88-0d7b-ca4ff97ee761
* Version Independent ID: 173e41e3-b747-cf7b-9b43-3d678f21eacb
* Content: [CoreDispatcher.RunAsync(CoreDispatcherPriority, DispatchedHandler) Method (Windows.UI.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.runasync#remarks)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coredispatcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coredispatcher.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
@rigdern, thanks again for letting us know about this issue. The links are fixed now.
