### ISSUE TITLE
Not all installed voices can be used?

### ISSUE THREAD

**Issue by PeterOeClausen** [MicrosoftDocs/winrt-api#578]
"Microsoft Helle", a Danish text-to-speech voice, is installed on my Windows PC among others.
I have the English, Danish and Spanish language packs installed on my PC (including text-to-speak and speech recognition), but only few voice options shows up with the call "GetInstalledVoices()", namely:
Microsoft David Desktop
Microsoft Hazel Desktop
Microsoft Zira Desktop
Microsoft Helena Desktop

David, Hazel and Zira are English voices, while Helena is a Spanish voice.
However "Microsoft Helle" shows up in my settings, but not when calling GetInstalledVoices().
Could you please provide an overview of which voices are available?
Why can't I choose to use "Microsoft Helle" as my text to speech voice?
Best, Peter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20958ed-3b18-3792-ff82-a8f62037342d
* Version Independent ID: 8ba019bb-4bc5-1c33-d1db-463621b39248
* Content: [SpeechSynthesizer Class (Windows.Media.SpeechSynthesis) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechsynthesis.speechsynthesizer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechsynthesis.speechsynthesizer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @PeterOeClausen - GetInstalledVoices is not a supported method of the UWP SpeechSynthesizer object. This object supports an AllVoices property.

The list of supported voices is at https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer.voice.

**Comment by tbafna** [comment]
Hi @Karl-Bridge-Microsoft 

Would it be possible to know if Danish is going to be added to the list of supported voices any time soon?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @PeterOeClausen: I'm afraid I can't provide a definitive answer to your question, but considering the level of investment in the UWP speech platform, I doubt support for Danish is in the works.
