### ISSUE TITLE
fernando

### ISSUE THREAD

**Issue by cuevasf** [MicrosoftDocs/winrt-api#579]
para trabajo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84fa6960-88f0-ef2b-259d-e327b1c63dde
* Version Independent ID: e63a64f4-6460-e0f5-8ce3-1bc267393bd5
* Content: [Windows.Devices.Scanners Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.scanners)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.scanners.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.scanners.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @cuevasf -- let us know if you have any feedback on the page. Thanks!
