### ISSUE TITLE
Following links should stay in the computing language of the previous page

### ISSUE THREAD

**Issue by Bluesman74** [MicrosoftDocs/winrt-api#580]
I got to this link by following a link from https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#add-a-property-of-type-bookstoreviewmodel-to-mainpage that is a Winrt C++ page, so it seems bad to end up at this C# page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f7ae11-e83b-edc5-c24b-e9ff1b5dc7ac
* Version Independent ID: 8ea46d28-2007-02ac-02a4-9ec4e89198bf
* Content: [ICustomPropertyProvider Interface (Windows.UI.Xaml.Data) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.icustompropertyprovider)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.icustompropertyprovider.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.icustompropertyprovider.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @Bluesman74, please see my response in https://github.com/MicrosoftDocs/windows-uwp/issues/938. These two issues seem to be duplicates. Thanks! ~Steve
