### ISSUE TITLE
Using "retrieve" instead of "reset"

### ISSUE THREAD

**Issue by PawelWMS** [MicrosoftDocs/winrt-api#581]
It seems like part of this documentation was copied from [here](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.magneticstripereader.retrievestatisticsasync) and so there are leftover words *retrieves* used instead of *resets*. For instance in *empty string ("") **retrieves** all statistics*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eaf7273-3556-b9ca-4ed6-8581379e039d
* Version Independent ID: 95f5b649-c536-03da-630f-6669ab8d878d
* Content: [ClaimedMagneticStripeReader.ResetStatisticsAsync(IIterable&lt;String&gt;) Method (Windows.Devices.PointOfService) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.claimedmagneticstripereader.resetstatisticsasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.claimedmagneticstripereader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.claimedmagneticstripereader.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Fixed, thanks for catching this!
