### ISSUE TITLE
Bring back automatic "Derived" section in all pages

### ISSUE THREAD

**Issue by verelpode** [MicrosoftDocs/winrt-api#582]
The automatic listing of derived classes seems to have been lost in the UWP documentation.  For example, if you look at the older non-UWP documentation at  https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.tilebrush  you can see that it automatically lists "Inheritance" followed by "Derived", but this "Derived" section is missing when you look at the UWP page at  https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.tilebrush .

Yes I realize that the UWP page manually says "TileBrush is the parent class for ImageBrush and WebViewBrush", and I thank you for manually writing that useful info, but could you please bring back the automatic listing of derived classes in EVERY doc page?  (Everywhere, not only for TileBrush.)

You could save yourselves from a bunch of manual work.  Instead of manually describing the derived classes in each and every class, you could bring back the ability to automatically list the derived classes.  Thanks for considering it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5680566-8c0c-987a-e87c-eadb74d5f80c
* Version Independent ID: 414eedd6-3a7e-81f1-0d3d-1c575a61a229
* Content: [TileBrush Class (Windows.UI.Xaml.Media) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.tilebrush)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.tilebrush.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.tilebrush.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
@mijacobs can you help route this to the appropriate engineering team?

**Comment by jwmsft** [comment]
When UWP docs are switched over to the .NET rendering pipeline, the docs will have derived type info like the WPF docs do. This work is being tracked in our internal Azure Devops database.

**Comment by verelpode** [comment]
Thanks!  That's good news, especially because it's much faster to view derived classes in the docs than to use the "Object Browser" window in VS.  The Object Browser window is quite useful and it can show derived classes but it's painfully slow at producing the list of derived classes, so it will be nice to have this info brought back in the docs.

I don't know how "the .NET rendering pipeline" works, but it sounds like it might fix other problems in the UWP docs.  For example, when you search for `WebView.Refresh`, Help Viewer 2.3 (VS 16.2.0) fails to find the documentation for the `Refresh` member of `WebView`.  Some members of `WebView` succeed and some fail. Although `WebView.Refresh` fails, now try and search for `WebView.ContainsFullScreenElement` and it succeeds.  Maybe these problems will also be fixed by the switchover to the .NET rendering pipeline ?
