### ISSUE TITLE
Bring back vector-based tiled brushes

### ISSUE THREAD

**Issue by verelpode** [MicrosoftDocs/winrt-api#583]
Could you please consider bringing back the ability and description for how to make checkerboard and gridline brushes?  This already existed previously but disappeared in UWP.  Prior to UWP, TileBrush had a derived class called [DrawingBrush](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.drawingbrush) and you can see examples of gridline brushes and checkerboard brushes in the second image in ["Painting with Images, Drawings, and Visuals"](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/painting-with-images-drawings-and-visuals?view=netframework-4.7.2), under the heading "Paint an Area with a Drawing".  But how can this be done in UWP?  Please note these were vector-based brushes not bitmaps.  How can we make such vector-based tiled brushes in UWP?

The following example XAML demonstrates how to make a checkerboard brush in WPF, but this stopped working in UWP because UWP doesn't have DrawingBrush.   How can we do the equivalent in UWP?

```
<DrawingBrush Viewport="0,0,20,20" ViewportUnits="Absolute" Stretch="None" TileMode="Tile">
   <DrawingBrush.Drawing>
     <DrawingGroup>
       <GeometryDrawing Brush="#18FFFFFF">
         <GeometryDrawing.Geometry>
           <GeometryGroup>
             <RectangleGeometry Rect="0,0,10,10"/>
             <RectangleGeometry Rect="10,10,10,10"/>
           </GeometryGroup>
         </GeometryDrawing.Geometry>
       </GeometryDrawing>
       <GeometryDrawing Brush="#34FFFFFF">
         <GeometryDrawing.Geometry>
           <GeometryGroup>
             <RectangleGeometry Rect="10,0,10,10"/>
             <RectangleGeometry Rect="0,10,10,10"/>
           </GeometryGroup>
         </GeometryDrawing.Geometry>
       </GeometryDrawing>
     </DrawingGroup>
   </DrawingBrush.Drawing>
 </DrawingBrush> 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5680566-8c0c-987a-e87c-eadb74d5f80c
* Version Independent ID: 414eedd6-3a7e-81f1-0d3d-1c575a61a229
* Content: [TileBrush Class (Windows.UI.Xaml.Media) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.tilebrush)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.tilebrush.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.tilebrush.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
This is a great feature request. We are asking customers to request features via our github: https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose.

**Comment by verelpode** [comment]
Thanks for the guidance.  It is not so easy to know the most appropriate place to post a request, considering the huge scope of Visual Studio, C#, UWP, etc.  Just now I posted it to that GitHub as [#536](https://github.com/Microsoft/microsoft-ui-xaml/issues/536).

**Comment by jevansaks** [comment]
Thanks!
