### ISSUE TITLE
WebViewBrush.Redraw should support continuation

### ISSUE THREAD

**Issue by PeterWone** [MicrosoftDocs/winrt-api#585]
The documentation clearly states that this method is asynchronous. If you need to wait for render because you are paginating a print job you have to resort to horrible hacky thread sleeps.

You could add a new method RedrawAsync that returns a Task so continuation can be supported.

Or you could change Redraw to return a Task since currently it returns void and this would not be a breaking change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f991fb6-d05a-fa32-f963-33c4fa6b56fc
* Version Independent ID: 7461cb55-b2d0-b7bc-b3d9-339df63d4ec8
* Content: [WebViewBrush.Redraw Method (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewbrush.redraw)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webviewbrush.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webviewbrush.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chrisglein** [comment]
Great suggestion! It totally makes sense that you'd want a version of Redraw that gives you an opportunity to respond to it. This seems like a feature request, not a doc issue with the existing method. Can you open a feature request under our GitHub repo here? https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose
