### ISSUE TITLE
'ImageableRect` Property description missing words

### ISSUE THREAD

**Issue by ScottIsAFool** [MicrosoftDocs/winrt-api#586]
If you look at the property description for `ImageableRect` it is missing some information. The text reads like so:
> Content outside of the , whether less or greater than the page size...

Note the missing word(s) before the comma
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1d7a5a-767e-bb30-e287-caeef5f44bab
* Version Independent ID: 85b0d795-5a00-3f14-bcab-3ffa73840a95
* Content: [PrintPageDescription Struct (Windows.Graphics.Printing) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.printing.printpagedescription)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.printpagedescription.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.printpagedescription.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by ScottIsAFool** [comment]
*bump* just noticed this issue has still not been resolved and the issue is still present.

**Comment by drewbatgit** [comment]
Thank you for reporting this typo in the documentation. It has been fixed.
