### ISSUE TITLE
BASSAM

### ISSUE THREAD

**Issue by shashika1** [MicrosoftDocs/winrt-api#588]
BASSAM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d31f1d8-199f-e1d7-52ae-8872f5637400
* Version Independent ID: 04724f66-aa82-8e9b-7ed9-a6edcd9e1b1c
* Content: [WiFiNetworkReport.AvailableNetworks Property (Windows.Devices.WiFi) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifi.wifinetworkreport.availablenetworks#Windows_Devices_WiFi_WiFiNetworkReport_AvailableNetworks)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.wifi.wifinetworkreport.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.wifi.wifinetworkreport.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
hi @shashika1 -- let us know if you have any feedback on our docs. Thanks!
