### ISSUE TITLE
How to check if user has purchased the app?

### ISSUE THREAD

**Issue by thomasdao** [MicrosoftDocs/winrt-api#589]
I have setup the app with free trial, and when I download the free trial, the StoreAppLicense object is as below. However `isTrial` is `false` and `isTrialOwnedByThisUser` is `false` and `trialUniqueId` is also empty. Those data seems not quite useful to determine if user has purchased the app. Is there any way to check if user has purchased the app from the StoreAppLicense object? My app is an Electron app and I use NodeRT to retrieve StoreAppLicense. Many thanks 
```
StoreAppLicense
__winRtInstance__:true
addOnLicenses:Windows::Foundation::Collections:IMapView
expirationDate:Fri Dec 31 9999 07:00:00 GMT+0700 (SE Asia Standard Time)
extendedJsonData:"{"productAddOns":[],"isActive":true,"isTrial":false,"isTrialOwnedByThisUser":false,"expiration":"9999-12-31 00:00:00"}"
isActive:true
isTrial:false
isTrialOwnedByThisUser:false
skuStoreId:""
trialTimeRemaining:922337203685477.6
trialUniqueId:""
__proto__:Object
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49c9379-e5e3-ae2e-a7a3-11134bf151fe
* Version Independent ID: a329890c-0af1-5dba-26df-54c8543ff130
* Content: [StoreAppLicense Class (Windows.Services.Store) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storeapplicense)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storeapplicense.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storeapplicense.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
The StoreAppLicense.IsTrial property is designed to give you the information you're looking for: it will return true if the current user has a trial license and it will return false if they have a full license. 

Have you (or someone else) previously installed the full version of this app on the computer on which you have downloaded the trial and are seeing IsTrial==false? If so, that would explain what you're seeing. When you install the full version of an app on a given computer, the entire computer gets licensed to use the app, even if another user signs in later. To fully test out the trial scenario, you would need to install the trial on a computer (or virtual machine) where the full version has not yet been installed.

Note that IsTrialOwnedByThisUser is specifically only relevant to usage-limited trials, which are a special type of trial that is only available to certain managed Xbox developer accounts at this time.

**Comment by thomasdao** [comment]
I published the app on the Store, download it using “free trial” button. Then I close the app from Store and launch my development version to check the console. I am sure I’m the only one who use the computer. And then I found isTrial return false. Is that correct way to test the purchase flow? Thanks

**Comment by mcleanbyron** [comment]
To clarify a few things:

- Are you saying that you downloaded the trial version of your app from the Store, ran and closed the trial, and then you ran the development version of your app (i.e., your built Visual Studio project) on the same computer?

- Is it possible that at some point in the past you downloaded and ran the full version of your app from the Store on the same computer?

**Comment by thomasdao** [comment]
Hi @mcleanbyron, yes I only downloaded the trial version from the Store. My app is a paid app with unlimited trial, and I don't remember I've ever entered any payment details.

This is also the first time I download from the Store, before that I only have dev build in my computer. There's no one else use the computer.

My project is an Electron project and I use https://www.npmjs.com/package/@nodert-win10-rs4/windows.services.store to retrieve the StoreAppLicense. My code is as below

```javascript
let storeContext

export const init = () => {
  try {
    let windowsStore = require('windows.services.store')
    storeContext = windowsStore.StoreContext.getDefault()
    handleLicenseChanged()
    storeContext.on('offlineLicensesChanged', handleLicenseChanged)
  } catch (error) {
    console.error('Error init windowsStore', error)
  }
}

const handleLicenseChanged = async () => {
  if (storeContext) {
    storeContext.getAppLicenseAsync(async (err, appLicense) => {
      if (!err) {
        console.log('handleLicenseChanged', appLicense)
      } else {
        console.error('getAppLicenseAsync', err)
      }
    })
  }
}
```

**Comment by mcleanbyron** [comment]
A developer who works on this API had a look at this thread, and he noticed that the [SkuStoreId ](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storeapplicense.skustoreid)property in your license data is empty in the data you provided in your initial post. This indicates that for some reason the license isn't valid. He recommends that you do the following:

1. Uninstall the app from your computer.

2. Install the trial version again from the Store (this will re-install the license). 

3. Sideload the dev version of your app on top of the existing package and run it.

This should get you to a point where the license has a valid SkuStoreId. Until the license has this value, the license isn't valid and it will default to the standard dev license values you're seeing.

If these steps still don't fix the issue, please file feedback via Feedback Hub and post a link to that feedback. The feedback process will gather logs our engineering team can use to try to help diagnose what is going on.

**Comment by thomasdao** [comment]
Thanks for helping to check this issue. I’m away this weekend and will try this as soon as when I’m back.

**Comment by thomasdao** [comment]
Hi @mcleanbyron, I had tried all the steps you described, but unfortunately it does not help. I had uninstalled the app from the store, click "Free Trial" from the Store and download it again. When the app is fully downloaded, I opened it, and also launch the dev version, the SkuStoreId is empty. I closed the app from Store, closed dev version, restart my computer to make sure nothing weird is running. I launch my dev version again, and SkuStoreId is still empty. (The response is still the same as my original post).

**Comment by thomasdao** [comment]
Oh I had just found a message from the Developer dashboard `We’re seeing app install failures with error code 0x800b0100 because of incorrect store signing. We have fixed the issue for new submissions and are actively working on rectifying the impacted apps.`. May be this is the root cause? I'll probably resubmit a new build to see if it fixes this issue

**Comment by thomasdao** [comment]
I think something is wrong at the Store. I’ve been trying to upload new build several times today, uploaded fine but stuck at “Validating”.

**Comment by thomasdao** [comment]
I try again today. I can upload new build to the store, it is no longer stuck and now validated, and I can publish the new build. When it's published, I delete the old app, download free trial from the Store and run it. Then running the dev version, it gives the same response as in my original post. I pretty much give up at this point.

**Comment by mcleanbyron** [comment]
I'm sorry you're still running into problems with this. At this point, the problem you're facing appears to be beyond the scope of the docs (the focus of this GitHub repo), so your best bet is to open a support request at http://aka.ms/storesupport so that our support team can engage with you directly on this. Before doing this, I also recommend that you try downloading the trial and then sideloading/running your dev app again and then file feedback via Feedback Hub. The feedback process will gather logs our support team can use to try to help diagnose what is going on. I hope this helps.
