### ISSUE TITLE
Finding use of the library from a C++ code

### ISSUE THREAD

**Issue by jecalderon** [MicrosoftDocs/winrt-api#593]
I will like to see same samples tomanipulate a UVC device from C++. Please comment in how to accomplish this.  My strudents are only finding OpenCV available , but I was hoping to allow us the opportunity tocode with the SDK or API tools. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 892df813-9780-020a-3dc0-b8b649ca0d74
* Version Independent ID: 80bd099e-e13a-66e7-1367-5739fb70b9c6
* Content: [CameraCaptureUI Class (Windows.Media.Capture) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Capture.CameraCaptureUI)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.cameracaptureui.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.cameracaptureui.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mkorat1717** [comment]
What is the simplest way to use camera functionalities into C# WPF, WinForm application without using Universal Framework?

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
