### ISSUE TITLE
How to get RequestAccessAsync to re-prompt for permission?

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/winrt-api#595]
The user is only prompted once (per app), how can we manually reset this so that the app will prompt again for permission?  Would be useful for testing the behaviour during development.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94ea023-a313-891b-9469-f86a6f160731
* Version Independent ID: 9d800f57-4458-e1b9-0e24-d4678e5eb99e
* Content: [Geolocator.RequestAccessAsync Method (Windows.Devices.Geolocation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.geolocator.requestaccessasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.geolocator.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.geolocation.geolocator.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by the-jedi-code** [comment]
I would also like this feature. If the user is prompted to allow access and says no the next time they try to use location it just fails and there is no way to re-prompt them for permission. I don't want to have to prompt users to leave the app and go to settings to give permission there, better experience would be to provide and overload that would explicitly allow for re-prompting.  Geolocator.RequestAccessAsync(reprompt:true); i.e. if the user has previously denied the location access this would force a new prompt instead of just returning denied over and over again.

**Comment by mcleanbyron** [comment]
Thanks for your feedback! You are correct that Geolocator.RequestAccessAsync only displays the prompt once per app, as documented in the [API article](https://docs.microsoft.com/en-us/uwp/api/windows.devices.geolocation.geolocator.requestaccessasync) and [here](https://docs.microsoft.com/en-us/windows/uwp/maps-and-location/get-location). After the first prompt, your app can programmatically open the location settings UX to enable the user to make further changes. Note that this behavior resets if the user uninstalls and reinstalls the app, and this is another alternative that might work for some development/testing scenarios.

It sounds like you are requesting a feature change for the API to programmatically launch the prompt after the first time. This repo is specifically for feedback on the documentation, and it is not intended as a resource for product feedback or technical support. I recommend that you submit this request via [Feedback Hub](https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) on a Windows 10 computer so your request is triaged by the appropriate engineering team. You'll probably want to choose "Developer Platform" and "API Feedback" as the categories.
