### ISSUE TITLE
Request to add additional note in Remarks section on caching not provided by API call

### ISSUE THREAD

**Issue by nmanis** [MicrosoftDocs/winrt-api#596]
Hello,

For this request, like to propose for triage to add following to Remarks

If the connection is terminated during a download, a subsequent call to the API will not resume from the prior download location and the progress will start from the beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7a82b0-1a6a-76e2-a0f9-d3eff051ae51
* Version Independent ID: b84deb39-5895-ab8e-d197-8756ce16ba14
* Content: [StoreContext.TrySilentDownloadStorePackageUpdatesAsync(IIterable&lt;StorePackageUpdate&gt;) Method (Windows.Services.Store) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.trysilentdownloadstorepackageupdatesasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storecontext.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storecontext.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Thanks for the feedback. I've added a note to the page. It will be published the next time we push out the API reference content.
