### ISSUE TITLE
Remarks reason for RawPosition manipulation is incorrect

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#597]
From dev: RawPosition can still be changed to reflect touch targeting result adjustment when touching close to edge of an UI element. For inking scenarios in advanced apps where accuracy and performance is critical, it’s usually better to use RawPosition and handle prediction in the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0377c27b-e0b3-6476-548f-a207afafbc8d
* Version Independent ID: 16539458-eb00-c743-9475-909b37fa2d60
* Content: [PointerPoint.RawPosition Property (Windows.UI.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerpoint.rawposition#Windows_UI_Input_PointerPoint_RawPosition)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.pointerpoint.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.pointerpoint.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @michael-hawker - Can you be more clear on your comments? Not sure what the significance is of the first sentence compared to the original (and how it makes it incorrect). For the second sentence, is this where you beleive the original is incorrect? Are you suggesting we replace the current comment with this second sentence? Or just append it?

**Comment by michael-hawker** [comment]
Thanks @Karl-Bridge-Microsoft, the issue is that RawPosition's remarks are a copy of [Position's Remarks](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.pointerpoint.position).

So first sentence is good, but 2nd sentence needs to change and become something like:

```
RawPosition contains the client coordinates of the input pointer as reported by the input device. Under some circumstances, such as touch targeting close to a UIElement, this data can be modified by the system.
```

Then add something like:

```
For inking scenarios in advanced apps where accuracy and performance is critical, it’s usually better to use RawPosition and handle prediction in the app.
```

**Comment by Karl-Bridge-Microsoft** [comment]
@michael-hawker - thanks for the clarification! I've updated the topic. It should be live in the next couple of days.
