### ISSUE TITLE
Request to triage Remarks section to add note about using with applications running full screen

### ISSUE THREAD

**Issue by nmanis** [MicrosoftDocs/winrt-api#598]
Hi,

Report from forums on RecognizeWithUIAsync API not showing listening dialog when an application is full screen.  Request to update this Remarks to mention this API will show the listening dialog when applications are not full screen.

Steps to reproduce
  1) Open the official sample : https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SpeechRecognitionAndSynthesis.
  2) Run the app and choose Scenario_PredefinedWebSearchGammar.
  3) Click “With UI” button
  4) The listening dialog shows correctly.
  5) Back to App.xaml.cs
  6) Add ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.FullScreen;
  7) Run the app and repeat step 2 and step3
  8) The listening dialog doesn’t show

Thanks,
Nathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5eddbb6-3658-936f-f9aa-c764c60cd08e
* Version Independent ID: a91c07e9-b9d9-1901-4c0d-63101868dcbf
* Content: [SpeechRecognizer.RecognizeWithUIAsync Method (Windows.Media.SpeechRecognition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognizer.recognizewithuiasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechrecognition.speechrecognizer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.speechrecognition.speechrecognizer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @nmanis. This is not expected behavior. I've informed the feature team and they're looking into it.
