### ISSUE TITLE
Add cancellation token

### ISSUE THREAD

**Issue by under3415** [MicrosoftDocs/winrt-api#599]
Can you add cancellation token here? Running a "deep" query takes forever and cannot be cancelled!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9dd15ed-b41c-a906-6768-3b818dca73b6
* Version Independent ID: f04d7b02-e96b-419f-e2a6-897bedae311e
* Content: [StorageFolder.GetFilesAsync Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.getfilesasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @under3415, apologies for the lengthy delay in replying. The Windows Runtime has four asynchronous operation types (named IAsyncXxx). This particular API returns IAsyncOperation<T>. All four types derive from IAsyncInfo, which has a Cancel() function on it.

```csharp
// Get the first 1000 pictures, sorted by date.
StorageFolder picturesFolder = KnownFolders.PicturesLibrary;
var cancel = picturesFolder.GetFilesAsync(CommonFileQuery.OrderByDate, 0, 1000);
// ...
cancel.Cancel();
```

There are C++/WinRT code examples here: [Canceling an asychronous operation, and cancellation callbacks](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/concurrency#canceling-an-asychronous-operation-and-cancellation-callbacks).

I hope that helps!
~Steve

**Comment by hkhmsft** [comment]
It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
