### ISSUE TITLE
Syntax block doesn't render return types using a collection correctly

### ISSUE THREAD

**Issue by peterfoot** [MicrosoftDocs/winrt-api#6]
For example:-
[https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio#Windows_Devices_Radios_Radio_GetRadiosAsync](https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio#Windows_Devices_Radios_Radio_GetRadiosAsync)
The method returns an IAsyncOperation<IVectorView<Radio>> but it is shown in the C# syntax block as
IAsyncOperation<Radio>>
Notice the mismatched brackets.
For C# this should be displayed as:-
IAsyncOperation<IReadOnlyList<Radio>>
The VisualBasic and C++ versions are also wrong (though C++ should display the IVectorView type as it is the raw WinRT type rather than IReadOnlyList which is the .NET mapping).
I suspect this could also be a problem for other async methods which return collections.

**Comment by kevinyr** [comment]
We're close to having this issue fixed.

**Comment by kevinyr** [comment]
This issue is resolved.
