### ISSUE TITLE
The IdleDispatchedHandlerArgs.IsDispatcherIdle property usage is unclear

### ISSUE THREAD

**Issue by JohnTasler** [MicrosoftDocs/winrt-api#600]
> if the IdleDispatchedHandler delegate returned by the callback has the IsDispatcherIdle property set to false, the work item immediately exits background processing until the event queue is empty again.

This sentence seems to be erroneous and confusing in these ways:
1. The `IdleDispatchedHandler` delegate is **not** _returned_ by the callback. The callback _is_ the `IdleDispatchedHandler` delegate.
    I think this means to say that the `IdleDispatchedHandlerArgs` _sent to_ the `IdleDispatchedHandler` delegate
2. By "the work item immediately exits", is this telling me that my **callback** should exit processing? If `IsDispatcherIdle` **is** false, then why was my callback even called? I thought it only should be called when the `CoreDispatcher` is Idle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf4cafd3-1bf0-d95c-3ec8-92eb9c6ef6f1
* Version Independent ID: 8b869f1c-e1e5-1740-bdd0-159464b26de0
* Content: [IdleDispatchedHandlerArgs.IsDispatcherIdle Property (Windows.UI.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.idledispatchedhandlerargs.isdispatcheridle)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.idledispatchedhandlerargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.idledispatchedhandlerargs.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
Apologies for the lengthy delay on this item.

1: You're right that the wording on this description is incorrect. I've updated it, and the changes should be live later today.

2: I believe that the text here is an accurate description of the behavior - if the dispatcher is not idle, the item will not process until the queue is empty (though this might be a back-up in case of unintended behavior?). Regardless, I've changed "exits" to "suspends," as I believe it gives the better impression here. Thank you.
