### ISSUE TITLE
Link to Media extension sample invalid for UWP

### ISSUE THREAD

**Issue by mjmeans** [MicrosoftDocs/winrt-api#601]
This page is referring to UWP APIs and presumably VS 2017. The See Also link for "Media extension sample" doesn't target universal apps at all. That sample works with VS 2013 (not appropriate for UWP apps) and Windows Runtime, Windows 8.1, and Windows Phone 8.1 projects which won't load in VS 2017. I think it's time for a new media extension sample for UWP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db1895c-9404-8133-e222-58a1151d0598
* Version Independent ID: 4d74a4c1-65e9-8c04-ece6-3bd987f6fb67
* Content: [VideoEffects Class (Windows.Media) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.VideoEffects#Windows_Media_VideoEffects_VideoStabilization)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.videoeffects.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.videoeffects.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I know this is a very old request, but indeed, a new media extension sample is on our backlog of work items. I will note that there is interest in this and bump the priority up.
