### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by peterfreese-zz** [MicrosoftDocs/winrt-api#602]
Typo in "it can then specify a viewport to fill the quad layer with *jut* a subset of the image."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b71c46aa-6068-e301-5309-974b9ce9e953
* Version Independent ID: 786f0940-bd81-0796-b9d1-f271266fe31e
* Content: [HolographicQuadLayerUpdateParameters.UpdateViewport(Rect) Method (Windows.Graphics.Holographic) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicquadlayerupdateparameters.updateviewport)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicquadlayerupdateparameters.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicquadlayerupdateparameters.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by GrantMeStrength** [comment]
Thanks! We also need to improve the intro sentence a little: "Updates the viewport rectangle within the quad layer's texture to display." could be worded a little more clearly.

**Comment by eliotcowley** [comment]
Fixed, thanks for catching this @peterfreese!
