### ISSUE TITLE
PlaybackRate is described as a percentage, but it's actually a ratio

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#603]
The Remarks section is correct -- 1.5 means 150%.  But the initial descriptions says it's "expressed as a percentage" (so you'd set it to 150 to get 150%)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd39a0b-05c9-0c41-5b98-bb8752c59987
* Version Independent ID: 99c3fab3-16f0-4642-c617-d94429a34f86
* Content: [MediaPlayer.PlaybackRate Property (Windows.Media.Playback) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer.PlaybackRate)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.playback.mediaplayer.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for helping to improve the documentation. The language has been fixed in the source and the change will show up on the live site within ~24 hours.
