### ISSUE TITLE
FaceAnalysis MinDetectableFaceSize cannot be set

### ISSUE THREAD

**Issue by Manimojy** [MicrosoftDocs/winrt-api#604]
MinDetectableFaceSize is always set to the default 2584. Is this a bug?

**Comment by ginami** [comment]
Hi @Manimojy -- which page in our docs are you referring to? (This will help me route your question to the correct author.) Thank you!

**Comment by Manimojy** [comment]
@ginami This is the link :
https://docs.microsoft.com/en-us/uwp/api/windows.media.faceanalysis.facedetector.mindetectablefacesize#Windows_Media_FaceAnalysis_FaceDetector_MinDetectableFaceSize

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
