### ISSUE TITLE
Event doesn't always fire if item is added or deleted from the folder

### ISSUE THREAD

**Issue by mjmeans** [MicrosoftDocs/winrt-api#605]
If an item is moved into or out of a monitored folder, for example via a Cut/Paste operation, this event should fire. But it doesn't.

As a matter of principle, whenever the folder is gaining or losing a file entry, the contents of the query results should have corresponding added or deleted entries. i.e. if the query were run again, it would be different. It shouldn't matter whether this was caused by an external file create, file delete, file copy, or file move operation. The first three cause the contents changed event to fire, the last doesn't. This creates an inconsistency in behavior.

Firing this even on a file move operation is critical if you have a process that creates files and moves them into a monitored folder for further processing. Currently I see no way to accomplish this with UWP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03156c78-1c4b-fd58-2434-23b34cd1b82f
* Version Independent ID: b21fda23-4834-41fa-5fb7-40f312cbb9ef
* Content: [StorageFileQueryResult.ContentsChanged Event (Windows.Storage.Search) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.storagefilequeryresult.contentschanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.storagefilequeryresult.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.storagefilequeryresult.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by lukeblevins** [comment]
I can also confirm this is a very pronounced issue.

**Comment by lukeblevins** [comment]
Sometimes this event fires multiple times, fails to fire at all, or fires after an unacceptable delay. Still very unreliable!

**Comment by VictorDenisenko** [comment]
Yes, this event can arise 11 times if I change file only one time, but sometimes it do not rise at all.

**Comment by yanxiaodi** [comment]
Same here. We have tried to monitor the changes for a specific file but this event could be triggered quite a few times when there are no changes to the file. It is not a reliable option at the moment.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. It seems this Issue leans more towards product feedback rather than specific documentation fixes.  The community of experts and Microsoft engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) can provide timely answers to technical questions and continue this discussion. Closing this Issue.
