### ISSUE TITLE
Please add the ability to hide inherited members.

### ISSUE THREAD

**Issue by jolleekin** [MicrosoftDocs/winrt-api#606]
Please add the ability to hide inherited members.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e2ad352-fa12-14ff-1c34-e4af87761fe6
* Version Independent ID: 5efa357f-147f-1151-5f85-e8ba74b98d48
* Content: [FlipViewItem Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.FlipViewItem)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.flipviewitem.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.flipviewitem.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by benstevens48** [comment]
This would be very useful. Especially for classes derived from UIElement/FrameworkElement as it's very difficult to see what the unique properties are.

**Comment by YuliKl** [comment]
@mijacobs, @jwmsft - this is a request for the docs website that we agree feels incredibly helpful to users.

**Comment by benstevens48** [comment]
Nice to see that this is getting some attention. I guess a checkbox saying 'Hide inherited items' or something like that would be the most obvious UI, but what would be a nice addition would be if after checking that, you would see an extra option saying 'From' followed by a drop down menu listing all the parent classes, with the immediate parent selected by default. Also, it might be nice if this option was remembered during the browsing session and applied to the whole docs, although if there was the second dropdown option I'm not sure how it would work in that case - perhaps don't remember the setting for that option.

**Comment by mdmozibur** [comment]
Any progress?

**Comment by jolleekin** [comment]
At least I found a workaround by expanding the navigation tree in the left pane.


![image](https://user-images.githubusercontent.com/5405376/60611761-4877ca00-9df1-11e9-8354-4a25497feab8.png)

**Comment by SvenEV** [comment]
For what it's worth, here's a JS snippet for the browser console to remove all inherited members from the page:
```javascript
for (let td of $('td:last-child'))
  if (td.innerText.includes('(Inherited from'))
    td.parentElement.remove()
```
I strongly agree, though, that there should be a more user friendly way.

**Comment by QuinnRadich** [comment]
Apologies for letting this issue stand for so long.

This request has been passed on to our docs engineering team. However, isn't something that's actionable for us as writers, and is more an issue with the docs platform than with the content on this page itself. As such, I'm closing this issue.

Thank you.
