### ISSUE TITLE
DataBitLength misstatement

### ISSUE THREAD

**Issue by zaguoba** [MicrosoftDocs/winrt-api#609]
Code example states:

// Conversion happens on a 16-bit frame 
settings.DataBitLength = 16; 

However, on my Raspberry Pi 3B exception pops out as soon as I try to instatiate SpiDevice with such setting, claiming that this DataBitLength value is not supported. Apparently, what I've got from other site, RPi is hardware limited to 8/9 bit length word for SPI, can anyone confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889b677e-2b24-db98-81eb-3777db18a898
* Version Independent ID: 6d4078f8-4bc6-c597-22d3-ab8c60ee1a8c
* Content: [SpiConnectionSettings Class (Windows.Devices.Spi) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.spi.spiconnectionsettings)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.spi.spiconnectionsettings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.spi.spiconnectionsettings.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
Sorry for letting this issue stand for so long.

I believe that the specific example in this article covers a device with certain settings, which are not shared for a Raspberry Pi. As RPi is a common development platform, I'm adding a note stating that the example bit length might need to be changed to account for your device.

Thank you.
