### ISSUE TITLE
Need example showing how to use Flyout.OverlayInputPassThroughElement

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#612]
It'd be nice for this to point to the example of how to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 250b94e3-c8a2-f1ac-c01e-3bdd55532fba
* Version Independent ID: f3c09389-70f5-ad62-6963-724c4330e3c9
* Content: [FlyoutBase.OverlayInputPassThroughElement Property (Windows.UI.Xaml.Controls.Primitives) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutbase.overlayinputpassthroughelement?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.Primitives.FlyoutBase.OverlayInputPassThroughElement)%3Bk(VS.XamlEditor)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutbase.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
For example, this article mentions it and what it does: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/flyouts, but isn't linked to at the property level here.

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue, and thanks for the suggestion. The doc has been updated with links to more information.
