### ISSUE TITLE
Use of FocusMode::Manual ?

### ISSUE THREAD

**Issue by Tryum** [MicrosoftDocs/winrt-api#613]
I tried to implement manual focus just by reading the API reference. I thought about using FocusSettings to set Manual Mode and Focus Distance/Value... didn't work. Checked the samples, it's done with FocusControl::LockAsync() and FocusControl::SetValueAsync(), so I'm wondering what's the use of the FocusMode::Manual ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfcc599b-d8a6-4ada-11b1-d59c34d90180
* Version Independent ID: db1524bc-78d9-a05b-01d4-4778c169348e
* Content: [FocusSettings.Mode Property (Windows.Media.Devices) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.focussettings.mode#Windows_Media_Devices_FocusSettings_Mode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.devices.focussettings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.devices.focussettings.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Have you tried the sample code for implementing manual focus that is included in the focus section here?:

https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/capture-device-controls-for-photo-and-video-capture#focus

**Comment by Tryum** [comment]
As said in the ticket, I managed to implement manual focus reading the sample.
I'm just wondering why is there unused code laying around. (Which actually crashes with a message mentionning incorrect settings).

**Comment by drewbatgit** [comment]
Sorry for the extremely delayed response to this. I believe the issue here is a semantic one. "Manual" in this case means that the app sets the focus value by calling SetValueAsync (presumably as a result of the user "manually" adjusting a control). This is as opposed to "auto" where the capture device driver sets the focus point without any calls from the app.
