### ISSUE TITLE
PrepareFileTranscodeAsync locks source file

### ISSUE THREAD

**Issue by andriysavin** [MicrosoftDocs/winrt-api#614]
I understand this is for docs feedback, however I don't know where to post this. In short, when calling from a desktop .Net app PrepareFileTranscodeAsync method leaves source file locked (even without starting transcoding itself). If you try to delete (in code) the source file after this, you will get an error saying the file is locked by other process. I'm sure this is a bug and should be reported somehow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2dff11-2bbc-502b-c541-ac64c4ff9b6c
* Version Independent ID: 4ad32238-098c-aa9d-4601-6840b271a28a
* Content: [MediaTranscoder.PrepareFileTranscodeAsync(IStorageFile, IStorageFile, MediaEncodingProfile) Method (Windows.Media.Transcoding) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.transcoding.mediatranscoder.preparefiletranscodeasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.transcoding.mediatranscoder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.transcoding.mediatranscoder.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. As you are aware, the scope of our feedback channel here on GitHub covers specific documentation fixes, but the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
