### ISSUE TITLE
Interop Sample points to old location?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#615]
I would imagine the sample here: http://go.microsoft.com/fwlink/p/?LinkID=309155 should instead be in the Universal Samples GitHub?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5516b37-eaf6-30c4-c277-27cd25e2c406
* Version Independent ID: e9ff7113-e3c0-183b-cd86-8e2a3910656b
* Content: [CoreIndependentInputSource Class (Windows.UI.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core.CoreIndependentInputSource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coreindependentinputsource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coreindependentinputsource.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks. The sample link has been updated.
