### ISSUE TITLE
C# Sample for CoreIndependentInputSource?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#616]
It'd be nice to know how to use this input loop in C#.  It seems it's not intuitive to port the C++ code: https://social.msdn.microsoft.com/Forums/en-US/ad4d42a2-a709-4862-9e53-a9baeae667b8/how-do-i-use-swapchainpanelcreatecoreindependentinputsource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5516b37-eaf6-30c4-c277-27cd25e2c406
* Version Independent ID: e9ff7113-e3c0-183b-cd86-8e2a3910656b
* Content: [CoreIndependentInputSource Class (Windows.UI.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Core.CoreIndependentInputSource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coreindependentinputsource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.coreindependentinputsource.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @michael-hawker, and thanks for filing this issue. I'll ping you internally to decide what to do here. I'll go ahead and close this issue, and we'll pursue it over email.

Thanks again!
Steve

**Comment by valdirSalgueiro** [comment]
Wondering if is there any update to this issue. Having the sample problem right now ( no c# sample usage and there is no directly way to convert cpp code that I am aware of )
