### ISSUE TITLE
Needs to be super clear that this method can be used in UWP apps for desktop.

### ISSUE THREAD

**Issue by colinkiama** [MicrosoftDocs/winrt-api#621]
Apparently, this method can be used on Desktops: http://answers.flyppdevportal.com/MVC/Post/Thread/82b8a23e-0110-4984-a382-568f6b2387b2?category=wpdevelop

However, the wording needs to be clearer as it may be about something else like Windows 8.1 or desktop bridge callers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8046a633-5aa1-00cf-233e-ddf8f898347e
* Version Independent ID: 6a30ec5e-e369-54c0-1446-6612eed9f2e9
* Content: [ToastNotifier.GetScheduledToastNotifications Method (Windows.UI.Notifications) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotifier.getscheduledtoastnotifications#Windows_UI_Notifications_ToastNotifier_GetScheduledToastNotifications)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotifier.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotifier.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
Thanks for your patience on this issue. This does seem like a confusing use of the term "desktop," and I've updated the note to reflect the intended message in a more accurate terminology. This change will be going live shortly.
