### ISSUE TITLE
simultaneously using of cameras

### ISSUE THREAD

**Issue by sepu1235** [MicrosoftDocs/winrt-api#622]
How can I use two cameras (Infered and Color) simultaneously in c++ winrt?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05bcdb69-ef00-9598-d66e-12fbfa696935
* Version Independent ID: 20719af7-1e1b-1d6c-b93b-53fd4a9d70cc
* Content: [MediaCaptureInitializationSettings.SourceGroup Property (Windows.Media.Capture) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacaptureinitializationsettings.sourcegroup#Windows_Media_Capture_MediaCaptureInitializationSettings_SourceGroup)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacaptureinitializationsettings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacaptureinitializationsettings.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by sepu1235** [comment]
I would like to do something like this:
https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/capture-from-multiple-sources-simultaneously
in c++

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. If still relevant, the right channel for this would be [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). The community of Microsoft experts over there offer timely answers to a multitude of technical questions surrounding windows-uwp.
