### ISSUE TITLE
Method is obsolete

### ISSUE THREAD

**Issue by asanfilov** [MicrosoftDocs/winrt-api#623]
Warning	CS0618	'GattDeviceService.Device.get' is obsolete: 'Use Session instead of Device property.  For more information, see MSDN.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 015dcc15-9b33-a258-2864-b7935abd98e1
* Version Independent ID: 5bc67eb3-08d9-6553-4731-9bc217e83148
* Content: [GattDeviceService.Device Property (Windows.Devices.Bluetooth.GenericAttributeProfile) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattdeviceservice.device)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattdeviceservice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattdeviceservice.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @aprobinda. Thanks for filing this issue, and my apologies for the delay in responding.

I've published an update to the topic to make it consistent with Visual Studio. I'll go ahead and close this issue now.

Thanks again!
Steve
