### ISSUE TITLE
ojio

### ISSUE THREAD

**Issue by WALBAR63** [MicrosoftDocs/winrt-api#624]
buena

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b699d3-80cb-76b5-179d-503e1d111551
* Version Independent ID: 921727d3-3d16-de77-daf6-3c2db52674d5
* Content: [PackageManager Constructor (Windows.Management.Deployment) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.-ctor#Windows_Management_Deployment_PackageManager__ctor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by ginami** [comment]
Hi @WALBAR63 -- thanks for your comment! Let us know if you have any document-specific feedback. :)
