### ISSUE TITLE
OnMPEFullWindowChanged() is wrong

### ISSUE THREAD

**Issue by mjmeans** [MicrosoftDocs/winrt-api#626]
The page refers to OnMPEFullWindowChanged(), but this is not a method or event in MPE.

The example concerning IsFullWindow is wrong. There appears to be no way to get a FullWindowChanged event from MPE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b8bdb23-8a5d-4421-dab8-d78f52b95a19
* Version Independent ID: 4c739d1d-a8ba-9b09-71cc-0fd6b04095cf
* Content: [MediaPlayerElement Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaplayerelement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.mediaplayerelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.mediaplayerelement.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi @mjmeans, I checked this code, and it works as expected. OnMPEFullWindowChanged is not a member of MPE, it's part of the app code as shown in the example. The example uses RegisterPropertyChangedCallback, which lets you create change notification handlers for properties that don't have built in change notification events. Please see [RegisterPropertyChangedCallback](https://docs.microsoft.com/uwp/api/windows.ui.xaml.dependencyobject.registerpropertychangedcallback) for more information about how this works.

**Comment by mjmeans** [comment]
You are correct of course. Sorry. I should have been more observant.
