### ISSUE TITLE
Async methods

### ISSUE THREAD

**Issue by dpierangeli** [MicrosoftDocs/winrt-api#628]
Is possibile to invoke C# async methods in javascript?
In that case the javascript thread is stalled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c6f680c-1a5d-b71e-dfa1-06dd299aeab4
* Version Independent ID: 0eb44846-ae8d-267f-972f-7cd971eb9778
* Content: [WebView.AddWebAllowedObject(String, Object) Method (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.addweballowedobject#Windows_UI_Xaml_Controls_WebView_AddWebAllowedObject_System_String_System_Object_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
I believe the answer to these is yes, but this isn't feedback about this doc page so I'm going to close this issue.
