### ISSUE TITLE
Missing Properties like ContentLenght, ContentType

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/winrt-api#631]
Who will add properties here like ContentLenght, ContentType.. etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b195d006-dff9-0a63-7008-3f50887c3be9
* Version Independent ID: a2f8a231-97e4-6f69-7100-93e19171ecb5
* Content: [HttpClient.DefaultRequestHeaders Property (Windows.Web.Http) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpclient.defaultrequestheaders#Windows_Web_Http_HttpClient_DefaultRequestHeaders)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpclient.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by StingyJack** [comment]
Someone who needs to send the same thing every time, like a heartbeat, keepalive, or other static/monitoring system.

**Comment by arvindrajachourasiya** [comment]
@StingyJack  - Are you saying I every time write negative comments/feedback?

**Comment by StingyJack** [comment]
No, you asked a question and I gave examples of answers to that question. No more, no less.

**Comment by arvindrajachourasiya** [comment]
@StingyJack - You are writing poetic response, I mean your English is high level. Still not able to understand. Even I asked the same question on English language learners forums 
https://ell.stackexchange.com/questions/183397/meaning-of-like-a-heartbeat-keepalive-or-other-static-monitoring-system

**Comment by StingyJack** [comment]
If a program named "Program1" is very important and must be executing all the time, sometimes a different program named "Program2" is created to inquire " Program1 every 5 minutes and report back to a user if Program1 is not running.

Every time Program2 makes this request to Program1, the message it sends is `"Are you alive?"`.   That message is always the same length.

> Who will add properties here like ContentLenght, ... [to the DefaultRequestHeaders]?

Program2 will, as its a static monitoring system.

**Comment by stevewhims** [comment]
Hi, @arvindrajachourasiya. Thanks for filing this issue, and my apologies for the extremely long delay in responding.

I've read the thread, and it looks like there's no action items for the documentation itself. I'll go ahead and close the issue, but please reopen it (or, better, create a new one) with details about what changes need to be made to the documentation.

Thanks again!
Steve
