### ISSUE TITLE
WebView Class page - Events list

### ISSUE THREAD

**Issue by RobDev23** [MicrosoftDocs/winrt-api#633]
It seems that the WebView control only supports a subset of the events listed on this page. It is not clear from this page which events are supported and which aren't. It is also not clear why some events, inherited from UIElement, aren't supported, particularly as some of the unsupported events would have been very useful in UWP app development.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1e6f48-d57c-65c1-9f05-1d76db94294f
* Version Independent ID: d69a866b-7f25-5543-6fa2-fbf9b830548b
* Content: [WebView Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.WebView#events)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
Can you be more specific about which event you were hoping to get? I believe all these events *can* be raised, but the integrate with WebView may make it hard for it to happen.
