### ISSUE TITLE
Note block not correct

### ISSUE THREAD

**Issue by riverar** [MicrosoftDocs/winrt-api#635]
See above, [!NOTE] is showing through to viewers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c519e067-d83e-69d5-0320-4789232d9b3d
* Version Independent ID: 9f48eb80-ccb5-f04e-9bbb-e224e4971485
* Content: [StorePackageLicense Class (Windows.Services.Store) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storepackagelicense)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storepackagelicense.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storepackagelicense.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mhopkins-msft** [comment]
Thanks Rafael, I've updated the content and will publish it with our next doc update.
