### ISSUE TITLE
What is the Maximum Freshness Time?

### ISSUE THREAD

**Issue by urjapatel** [MicrosoftDocs/winrt-api#637]
[Enter feedback here]
For my Application, I need to know maximum Freshness Time .
In my application, when i Set Freshness Time to 43,200 Minutes (i.e 30days * 24hours* 60minutes) it throws exception,

System.ArgumentException: Value does not fall within the expected range.
at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()

How do i Solve this? I want to know the maximum time limit as soon as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d3de97d-fc21-5fe6-29f4-364ca773c3c6
* Version Independent ID: af8a5566-19a0-636e-d3ee-d87fba67f0d9
* Content: [TimeTrigger.FreshnessTime Property (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.timetrigger.freshnesstime)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.timetrigger.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.timetrigger.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
Apologies for letting this issue sit unattended for so long.

My understanding is that this class is intended for continuously running apps, and is disabled when the device is turned off or goes into battery saver mode. I don't think such a long freshness time is the intended or functional use of this API.

If you're still having this issue, feel free to re-open this inquiry. For the time being, I'll be closing it. Thank you.
