### ISSUE TITLE
ContactList.GetContactAsync(contactId) Doesn't work.

### ISSUE THREAD

**Issue by maxmin88** [MicrosoftDocs/winrt-api#641]
ContactStore store = await ContactManager.RequestStoreAsync(ContactStoreAccessType.AllContactsReadWrite);
IReadOnlyList&lt;ContactList&gt; lists = await store.FindContactListsAsync();
ContactList list = lists.FirstOrDefault(s =&gt; s.DisplayName == "xxxxxx");
Contact storeContact = await list.GetContactAsync(listContact.ContactId); 

with a valid Contact.Id errors on: System.ArgumentException: 'Value does not fall within the expected range.'

My ContactList is from a different app list name "xxxxxxx" but I have authorized access on my local PC in the Package.appxmanifest with:
    &lt;rescap:Capability Name="contactsSystem" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1db0d9f8-80d4-11ca-7957-ec260c95460d
* Version Independent ID: bf0ac130-bb3a-dca9-a870-bd6ddaab9c1e
* Content: [ContactList.GetContactAsync(String) Method (Windows.ApplicationModel.Contacts) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.contacts.contactlist.getcontactasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.contacts.contactlist.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.contacts.contactlist.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hi, thanks for leaving feedback! Feedback here is used to improve our documentation experience. For development issues, please use our developer support center here: https://developer.microsoft.com/windows/support.
