### ISSUE TITLE
What value is this property?

### ISSUE THREAD

**Issue by dave-c-whitney** [MicrosoftDocs/winrt-api#642]
There doesn't appear to be a way to determine the current aggregate size of my RoamingStorage, so knowing the quota isn't overly helpful. How do I know I'm approaching the quota? Or over it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94fa9f72-099f-7db4-372f-57d28a30fcbb
* Version Independent ID: 691458fd-5758-9b0e-471d-b6202181f69a
* Content: [ApplicationData.RoamingStorageQuota Property (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.applicationdata.roamingstoragequota)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdata.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.applicationdata.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by tqk2811** [comment]
[100kb](https://stackoverflow.com/questions/35385645/uwp-is-the-size-of-roaming-applicationdata-the-file-actual-size-or-size-on-disk) 

[RoamingStorageQuota](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data) that example say 100kb

**Comment by dave-c-whitney** [comment]
That's not the question. The total _quota_ is 100kb. But how much of it is used right now? How much remains for me to use? How do I find out?

**Comment by dave-c-whitney** [comment]
It looks like

ApplicationData.RoamingFolder.Properties.RetrievePropertiesAsync("System.Capacity","System.FileAllocationSize","System.TotalFileSize")

might give me what I want. Time to experiment.

**Comment by dave-c-whitney** [comment]
Nope. "Capacity" is the size of the disk, not the size of the content in the folder. The others are NULL for the folder.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by dave-c-whitney** [comment]
https://docs.microsoft.com/en-us/answers/questions/80662/regarding-applicationdataroamingstoragequota.html

**Comment by hkhmsft** [comment]
Excellent! Thanks for opening the thread. Let me know of any developments and we'll work to document this.
