### ISSUE TITLE
Whom should we contact in Microsoft to run this API?

### ISSUE THREAD

**Issue by minghaojiang** [MicrosoftDocs/winrt-api#643]
Microsoft must approve your use of them and provision your developer account. 
Whom should I contact?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b63c355f-bbb7-2791-e771-c89e9880e720
* Version Independent ID: 4c4b05e1-fda4-d6c7-3592-00d84a073ac6
* Content: [EmailStore Class (Windows.ApplicationModel.Email) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.email.emailstore)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.email.emailstore.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.email.emailstore.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hi! Approval is necessary before publishing an app that uses these APIs. The approval and provisioning happens as part of the store app submission process. I'll update the wording here to be more clear about that. If you run into any issues using the APIs, please check out our developer support pages or leave a post on a support forum: https://developer.microsoft.com/windows/support
