### ISSUE TITLE
Windows.UI.Core.KeyEventArgs: args.DeviceId throws Exception

### ISSUE THREAD

**Issue by emyfreya** [MicrosoftDocs/winrt-api#644]
When getting DeviceId from the args of the KeyDown event, I got an exception: "An exception of type 'System.InvalidCastException' occurred in my.exe but was not handled in user code
Unable to cast object of type 'Windows.UI.Core.KeyEventArgs' to type 'Windows.UI.Core.IKeyEventArgs2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eab2a2ef-b0bf-1c56-d179-caf5433eafe7
* Version Independent ID: 8e6ee661-4b4a-7bbf-acef-a4dc37e13285
* Content: [KeyboardDeliveryInterceptor Class (Windows.UI.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.keyboarddeliveryinterceptor)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.keyboarddeliveryinterceptor.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.keyboarddeliveryinterceptor.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @JeremyFerreira. Need more detail/code. Thanks!

**Comment by Karl-Bridge-Microsoft** [comment]
No response from OP.
