### ISSUE TITLE
How to make derived classes of Shape

### ISSUE THREAD

**Issue by verelpode** [MicrosoftDocs/winrt-api#645]
Hello.  Could you please explain how we can write derived classes of the Shape class?  For comparison, in the older WPF-Desktop, we created derived classes by overriding the following members of Shape, but these members do not exist in UWP.  

* `System.Windows.Shapes.Shape.DefiningGeometry`
* `System.Windows.Shapes.Shape.RenderedGeometry`
* `System.Windows.Shapes.Shape.OnRender(System.Windows.Media.DrawingContext)`

We have a few special shapes written for WPF-Desktop and I need to port these classes to UWP, but I cannot find any explanation of how to make a class that derives from `Windows.UI.Xaml.Shapes.Shape`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7475331d-1803-ba3c-aab7-a1ac12f2ae10
* Version Independent ID: da916ffb-d93b-1425-9a3c-9b3720057af4
* Content: [Shape Class (Windows.UI.Xaml.Shapes) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.shape?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Shapes.Shape)%3Bk(vs.objectbrowser)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.shapes.shape.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.shapes.shape.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
The shape support in UWP is fairly limited. Did you file a product feedback for this on uservoice or a feature request on https://github.com/Microsoft/microsoft-ui-xaml/issues?
