### ISSUE TITLE
The documentation should state what SettingsIdentifier actually does

### ISSUE THREAD

**Issue by xyzzer** [MicrosoftDocs/winrt-api#647]
As is - it doesn't make anything clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8b19d8a-1300-d8e6-c6eb-18f377b5ba64
* Version Independent ID: 8d3cdd1c-c2c7-4879-7202-35c0ba600408
* Content: [FileSavePicker.SettingsIdentifier Property (Windows.Storage.Pickers) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.filesavepicker.settingsidentifier)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.filesavepicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.filesavepicker.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Marv51** [comment]
Any progress on this issue from 2018? Documentation still does not explain how this should be used at all.

**Comment by hkhmsft** [comment]
It seems there have been documentation updates since the Issue was filed. It seems there is no further actionable items here. Though I'm closing this Issue, feel free to follow-up below for any updates. Many thanks!
