### ISSUE TITLE
Please specify exact SDK version this is available in

### ISSUE THREAD

**Issue by partnerinflight** [MicrosoftDocs/winrt-api#651]
Just saying "Latest SDK" isn't helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe5bde2f-bc88-0b43-9207-9e60117f901e
* Version Independent ID: ecfe5132-43ac-458c-c8b9-f1831ab07cad
* Content: [ComboBox.IsEditable Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox.iseditable#Windows_UI_Xaml_Controls_ComboBox_IsEditable)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.combobox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.combobox.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
@mijacobs @mimisasouvanh the members aren't showing the SDK version available. This one may be a special snowflake because the getter was available since the beginning but setter was introduced in 17763.

**Comment by mijacobs** [comment]
Is this a request for SDK info in addition to the API contract, or would it be enough to provide the API contract? We don't show the required SDK on types, either.

**Comment by jevansaks** [comment]
API contract should be fine too. Will that be coming back to type member pages?

**Comment by mijacobs** [comment]
We've submitted this request to our engineering team; thank you for the feedback!
