### ISSUE TITLE
Clarification on how CreateWatcher() creates a DeviceWatcher

### ISSUE THREAD

**Issue by raadkhan** [MicrosoftDocs/winrt-api#652]
Great documentation overall. It is very clear how to create a `DeviceWatcher` to watch for specific devices using `CreateWatcher()`. 

I would like to know what happens on the other side- how does the `DeviceWatcher` when it is created know which physical device to use as the device watcher? For example in a Bluetooth application, how does the `DeviceWatcher` know to use the Bluetooth Adapter in the PC to start enumerating devices? And if possible, how can the developer choose which physical device the `DeviceWatcher` will use? So going back to the example, say the developer wants the `DeviceWatcher` to use a Bluetooth Dongle instead of the Bluetooth Adapter.

Thanks in advance @ginami

---
#### Document Details

* ID: 0e9fbace-e538-e625-70f9-3ba8fbfe7271
* Version Independent ID: a5b605c2-0b64-7747-de3e-40eb55b013da
* Content: [DeviceInformation.CreateWatcher Method (Windows.Devices.Enumeration) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.deviceinformation.createwatcher#Windows_Devices_Enumeration_DeviceInformation_CreateWatcher_System_String_Windows_Foundation_Collections_IIterable_System_String__Windows_Devices_Enumeration_DeviceInformationKind_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.deviceinformation.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. This GitHub repo is specifically for reporting documentation bugs. For deeper technical questions like this, please see the community of experts and Microsoft engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).

I'm marking this issue as closed now, but please feel free to reopen it if you have more information that indicates a real doc bug here. Thanks again!
