### ISSUE TITLE
Suggestions: Add links to "Relative mouse movement and CoreWindow" in the See Also

### ISSUE THREAD

**Issue by Code-ScottLe** [MicrosoftDocs/winrt-api#653]
A lot of people would come here looking for a way to track/ get mouse movement delta, which this article has nothing on it.

Adding a link to https://docs.microsoft.com/en-us/windows/uwp/gaming/relative-mouse-movement would help tremendously. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c6c666c-ca0d-adcb-945e-fdd430c933a1
* Version Independent ID: e246ec70-8347-227f-2b1a-b126d3294cfb
* Content: [UIElement.PointerMoved Event (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.pointermoved)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @Code-ScottLe. I've updated a number of related API topics with this link.
