### ISSUE TITLE
InvokedItemContainer not avaible on C++/CX

### ISSUE THREAD

**Issue by Tryum** [MicrosoftDocs/winrt-api#654]
And as I have two items with the same content, I'm a bit stuck with the suggested way to operate item selection...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb5d73f1-f61b-6d23-f178-1a0058764d98
* Version Independent ID: 3fdd8311-597d-7e1a-b2f5-1bdb177ecb3a
* Content: [NavigationViewItemInvokedEventArgs Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationviewiteminvokedeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewiteminvokedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewiteminvokedeventargs.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
API contract information may have been missing at the time you opened this issue, but InvokedItemContainer was not added until 17763. You could also switch to using the WinUI nuget package to have the property available everywhere. http://aka.ms/winui.

**Comment by jevansaks** [comment]
The recommended workaround prior to this was to use the Tag property.
