### ISSUE TITLE
More info needed

### ISSUE THREAD

**Issue by TyJOrtiz** [MicrosoftDocs/winrt-api#655]
like can you explain what capabilities are needed, or if this even works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8817446f-d25f-dbf2-f820-bee9fbb93cf7
* Version Independent ID: 5415f3e1-04be-274f-111d-16dc999c0911
* Content: [GlobalSystemMediaTransportControlsSessionManager.RequestAsync Method (Windows.Media.Control) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmanager.requestasync#Windows_Media_Control_GlobalSystemMediaTransportControlsSessionManager_RequestAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.control.globalsystemmediatransportcontrolssessionmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.control.globalsystemmediatransportcontrolssessionmanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by saber-nyan** [comment]
Got error `HRESULT: 0x80070005 (E_ACCESSDENIED)`, what permissions do i need to call `GlobalSystemMediaTransportControlsSessionManager.RequestAsync()`?

**Comment by drewbatgit** [comment]
Hello, thanks for your feedback on this issue. The required capability for these APIs is globalMediaControl. This information has been added to the API reference page for [GlobalSystemMediaTransportControlsSessionManager](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssessionmanager.requestasync#Windows_Media_Control_GlobalSystemMediaTransportControlsSessionManager_RequestAsync) and other related APIs. It has also been added to the [App capability declarations](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations) article. 

An internal issue has been filed to get this capability added to the app manifest GUI in Visual Studio, but until then, you will need to manually add the uap7 namespace to your manifest file:
```
<Fragment xmlns="http://schemas.microsoft.com/appx/2010/manifest"
          xmlns:m2="http://schemas.microsoft.com/appx/2013/manifest"
          xmlns:uap7="http://schemas.microsoft.com/appx/manifest/uap/windows10/7">>
```
And then, reference the namespace in the Capability element:
```
<Capabilities>
      <uap7:Capability Name="globalMediaControl" />
</Capabilities>
```
