### ISSUE TITLE
Action values not documented

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#656]
I'm not sure why this is an int instead of an enum like all the other APIs like this, but even then, the possible values and their meanings should be documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56061e79-d396-42c2-5ed8-af15ca4af718
* Version Independent ID: 504782d8-534d-d10e-22ed-4d188a1127a8
* Content: [ItemsChangedEventArgs.Action Property (Windows.UI.Xaml.Controls.Primitives) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.itemschangedeventargs.action#Windows_UI_Xaml_Controls_Primitives_ItemsChangedEventArgs_Action)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.itemschangedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.itemschangedeventargs.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
I dug a bit and it looks like it's using the same [CollectionChange enum](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Collections.CollectionChange), but it's just cast to an int for some reason? :(

**Comment by micahl** [comment]
ItemsChangedEventArgs is only used on VirtualizingPanel which I believe we consider deprecated.  If so, that should be documented.

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue, and thanks for the suggestion. The doc has been updated with the missing information.
