### ISSUE TITLE
Maybe C# example instead of JS?

### ISSUE THREAD

**Issue by codec-abc** [MicrosoftDocs/winrt-api#658]
Maybe C# example instead of JS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86a6e383-57dc-22cb-d7a9-5af7c48260f2
* Version Independent ID: 4f7180b3-53d1-f343-2cf1-1224cf369fce
* Content: [BitmapEncoder Class (Windows.Graphics.Imaging) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.bitmapencoder)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.bitmapencoder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.imaging.bitmapencoder.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Jace-Samsung** [comment]
C# code examples are available.  You can change the language of sample code via the drop-down menu at the top-right corner of the web page - just left of the "Sign In" button - the drop-down menu's text changes based on the currently selected language.

**Comment by Jace-Samsung** [comment]
Unfortunately, this particular page only has a JavaScript example, but here's a link to a bit more involved example which uses BitmapEncoder and BitmapDecoder:
https://gist.github.com/alexsorokoletov/71431e403c0fa55f1b4c942845a3c850

**Comment by Jace-Samsung** [comment]
Or, this page if you want to stay within Microsoft documentation:
https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/imaging#save-a-softwarebitmap-to-a-file-with-bitmapencoder

**Comment by codec-abc** [comment]
Thanks.
