### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#660]
The "Using Advanced Query Syntax Programmatically" link is broken.
Consider using https://docs.microsoft.com/en-us/windows/desktop/search/-search-3x-advancedquerysyntax

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f7ae70-9575-df95-e2f9-ea8eea9a8341
* Version Independent ID: 8958ec32-28f7-6d4b-4cc5-d83b9858aafa
* Content: [QueryOptions.ApplicationSearchFilter Property (Windows.Storage.Search) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.queryoptions.applicationsearchfilter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.queryoptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.search.queryoptions.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Sorry for the delay @EddieLotter , but the changes have been applied and the link has been fixed. You will see this reflected on the live docs within 24 hours. Many thanks once again.
