### ISSUE TITLE
sample code on how to create new views and manage them

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/winrt-api#661]
we need some sample code or sample app for this, where can can see how to create an app like "Sticky Notes v 3.0" using these APIs. I dont see a method to create a new window and then show it, the api looks incomplete because of no sample code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b92801-f6d2-cd04-7aaa-e9b872cc6030
* Version Independent ID: 5cfdf701-334a-3985-2cbc-7090fe20c577
* Content: [NotesWindowManagerPreview Class (Windows.ApplicationModel.Preview.Notes) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.preview.notes.noteswindowmanagerpreview)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.preview.notes.noteswindowmanagerpreview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.preview.notes.noteswindowmanagerpreview.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hi Touseef, 

Thanks for your feedback! I'll pass this along to the team that maintains the corresponding sample code. 

Nick
