### ISSUE TITLE
Obsolete description of ShowShareUI in the context of UWP apps

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/winrt-api#663]
The description of `ShowShareUI` method is obsolete because it describes the situation in Windows 8, not Windows 10.
```
We recommend that you use this method only when absolutely necessary. Users expect to launch the Share user interface through the Share charm. Launching the user interface programmatically can create a confusing user experience.
```
In Windows 10 the situation is quite different. There is no Share charm anymore. The only way to launch sharing it calling `ShowShareUI`. The documentation should reflect that and include maybe box describing the differences in behavior on Windows 8.

Also the sample code is only available in JavaScript, it might be useful to have C# example as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a87f9407-06bc-6967-918e-8ab31f70ca54
* Version Independent ID: 6b52bede-c0a5-8e8d-3372-8dd290952173
* Content: [DataTransferManager.ShowShareUI Method (Windows.ApplicationModel.DataTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datatransfermanager.showshareui)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.datatransfermanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.datatransfermanager.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by knightmeister** [comment]
Can't believe this is still open almost a year later.... came to report the same thing.

**Comment by citelao** [comment]
This is still the case in 2020. The Share charm has not existed for some time. @GrantMeStrength, are there any updates here?

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. This is a great catch, and I am updating all of the DataTransferManager-related articles to remove text that refers to the Share charm.
