### ISSUE TITLE
Links are dead.

### ISSUE THREAD

**Issue by MarcoAzer** [MicrosoftDocs/winrt-api#664]
The first and last AdaptiveMediaSource links get 404 errors. The middle AdaptiveMediaSource link seems to be the correct one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4114e8d2-5734-4d9f-2bbe-b2f03627c99b
* Version Independent ID: a4b76bdb-e992-2ccd-37d3-00a324816445
* Content: [MediaSource.AdaptiveMediaSource Property (Windows.Media.Core) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediasource.adaptivemediasource#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediasource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.mediasource.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for catching this. The link has been updated in the source. The fix should be seen on the live site within 24 hours.
