### ISSUE TITLE
How to set the run-order of the work items?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#665]
Hi,
It seems that the thread pool is a queue, does this queue is FIFO?
If all the work items have the same priority, is there method to set the order?
Is there more docs about what the max number threads can be run at the same time?
Dose the "System.Threading.ThreadPool" class is better than "Windows.System.Threading.ThreadPool" class?
Best regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db06291c-a440-fd71-2020-86c9affb97a8
* Version Independent ID: 85382cef-3cf2-bccf-19b8-011a77de2849
* Content: [Windows.System.Threading Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.system.threading)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.threading.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.threading.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for taking the time to open this issue and we sincerely apologize for the delayed response. 

According to the docs, "Work items run asynchronously and can run in any order, so it's best to use the thread pool for work items that don't take a lot of time and don't depend on each other's output." In the underlying win32 API, threadpools default to 500 maximum threads. You might want to consult the [Win32 Threadpool docs](https://docs.microsoft.com/en-us/windows/win32/procthread/thread-pools) for more information about what is happening under the hood. Obviously, not all of the features /behaviors discussed in those docs are available in the WinRT API, but it still may be of value.
