### ISSUE TITLE
Why are E0E4 and E0E5 not in this content? 

### ISSUE THREAD

**Issue by ingyeoking13** [MicrosoftDocs/winrt-api#666]
Hi, I have a little question. It is not Important.
I found that `CalendarView` has E0E4, E0E5 symbol to navigate calendar, But those set are not in this Document. 
If this Document has a part of UI symbol, then where can I get a full of Segoe UI Font? 
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39b122b1-0319-ec9a-2cad-6b31be0d6de6
* Version Independent ID: 16103a85-0a90-2580-6634-d4033e289eec
* Content: [Symbol Enum (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.symbol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.symbol.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
@ingyeoking13 - Thank you for your feedback. Symbol enum is just a subset of Segoe MDL2 Assets font, thus the table you point out in the documentation does not list out all the characters in the Segoe MDL2 Assets.

**Comment by chigy** [comment]
Closing as resolved.
