### ISSUE TITLE
Link to Samples is not rendered correctly

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#667]
This is what the link to the samples looks like:

![image](https://user-images.githubusercontent.com/199935/47054821-e561dc80-d168-11e8-96b4-e307e77edb31.png)

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e8711f-c7a0-4361-0342-32b32c2c082e
* Version Independent ID: 1800da03-8f01-0c5d-d4ae-d149e5dfd2a1
* Content: [HidDevice.FromIdAsync(String, FileAccessMode) Method (Windows.Devices.HumanInterfaceDevice) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.humaninterfacedevice.hiddevice.fromidasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.humaninterfacedevice.hiddevice.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @rigdern. There's a bug in our md rendering for See also sections (we don't support standard md in that section for some reason). I've stripped out the unsupported markdown, so all these links should now work.
