### ISSUE TITLE
No default indexed property

### ISSUE THREAD

**Issue by cartwrightluke** [MicrosoftDocs/winrt-api#669]
I wasn't able to use the [] notation in c++/cx.
error C3915: 'Windows::Data::Json::JsonArray' has no default indexed property
I had to use the Get[Object|*]At(UINT32) directly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10c2dc44-0b2d-dff3-b257-e0bc08c1d48e
* Version Independent ID: 1440e2f9-c5af-debe-f147-cece8ba82051
* Content: [JsonArray Class (Windows.Data.Json) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.data.json.jsonarray)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.json.jsonarray.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.json.jsonarray.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. 

Though the scope of our feedback channel here on GitHub covers specific documentation bugs, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to technical questions about UWP development.

If you do create a thread over at Microsoft Q&A that provides information that you believe should be captured in this article, it would be fantastic if you could update this issue and share that link here. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
