### ISSUE TITLE
Please have RoutedEventArgs inherit from System.EventArgs.

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/winrt-api#671]
Posted [here](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/35761855-please-have-routedeventargs-inherit-from-eventargs) too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91fe990f-733e-a47a-792e-05538a141d61
* Version Independent ID: 35c54709-7590-b353-058b-009aef00f883
* Content: [RoutedEventArgs Class (Windows.UI.Xaml) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.routedeventargs)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.routedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.routedeventargs.yml&version=GBlive&_a=contents)
* Product: **windows**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
Issue was answered on the other forum as well -- we have no plans to change this.
