### ISSUE TITLE
Note about UnsetValue from DependencyProperty should be called out here?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#679]
There's a remark in [UnsetValue](
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyproperty.unsetvalue#Windows_UI_Xaml_DependencyProperty_UnsetValue) documentation about how it should be returned instead of null by IValueConverters.  If that is indeed the proper guidance than this IValueConverter page should call that out as well and its sample should show that scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1e0293-4dd3-9057-4e47-da7861c86151
* Version Independent ID: 4b19dea0-4b17-614b-d13d-d7b5556d5012
* Content: [IValueConverter Interface (Windows.UI.Xaml.Data) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.ivalueconverter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.ivalueconverter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.data.ivalueconverter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Thanks for the suggestion. This information has been added.
