### ISSUE TITLE
Need an example

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#680]
How do I use this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d358d6f1-d12f-1d2a-2f84-0be0a9b30cd8
* Version Independent ID: 43356929-8f15-a2d1-dbe9-504078ed4986
* Content: [IconSourceElement Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.iconsourceelement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.iconsourceelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.iconsourceelement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue, and thanks for the suggestion. The doc has been updated with the missing information.
