### ISSUE TITLE
Link assosiated with "TooltipService.ToolTip" is 404

### ISSUE THREAD

**Issue by miueda8** [MicrosoftDocs/winrt-api#683]
Clicking TooltipService.ToolTip in this page leads to below link and it's 404.
https://docs.microsoft.com/en-us/uwp/api/tooltipservice_tooltip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d1cc8a-cbde-8f1e-5a08-f85889b725e8
* Version Independent ID: c8182ca4-1b51-1cf4-ca8c-2791ba3a5f83
* Content: [ToolTip.Placement Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.tooltip.placement#Windows_UI_Xaml_Controls_ToolTip_Placement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.tooltip.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.tooltip.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
This is tracked by issue #565
