### ISSUE TITLE
Enum values missing from MSDN CoreDistpacher article

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/winrt-api#70]
I was just reading this page:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher
and I noticed, that in all places where a specific **CoreDispatcherPriority** enum value is used, the actual value is not shown in the article, only the type. Because of this issue lots of parts of the text does not make any sense:
![image](https://cloud.githubusercontent.com/assets/3041397/24500465/d100401e-1545-11e7-9f40-341daf84a118.png)
It's possible this issue with enum values is on much more MSDN pages.

**Comment by mattwojo** [comment]
@kevinyr -- Is this a known issue?
*Is this the same issue? https://github.com/MicrosoftDocs/winrt-api/issues/7

**Comment by mattwojo** [comment]
Closing this issue as a duplicate to issue https://github.com/MicrosoftDocs/winrt-api/issues/7 --- engineering team is aware and working on a fix -- should have something soon. Thanks @martinsuchan!
