### ISSUE TITLE
Device Family is incorrect

### ISSUE THREAD

**Issue by rjmurillo** [MicrosoftDocs/winrt-api#708]
WebViewControl was initially offered in 17134, April 2018, not 17763 October 2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c7ef60-bad2-7e7e-4aee-ef5bfc24e853
* Version Independent ID: 6c9d565a-fbeb-d614-a84f-e7fa6c940ab1
* Content: [WebViewControl Class (Windows.Web.UI.Interop) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.web.ui.interop.webviewcontrol)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by erikadoyle** [comment]
Hmm, I'm seeing 17763 in Windows.Web.UI classes too. The version gets populated from an automated WinRT diffing system. Tracking down a contact...

**Comment by erikadoyle** [comment]
Issue's already filed (VSO 19489340). Will update this once fixed.

**Comment by erikadoyle** [comment]
Fixed now.
