### ISSUE TITLE
Add more info about ItemContainerStyle like the original WPF docs

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#711]
Would be nice if the UWP docs could provide the similar type of info and detail that the WPF docs do here: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.itemscontrol.itemcontainerstyle?view=netframework-4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f7ca349-dfe4-3c7a-56ba-2b26a736b312
* Version Independent ID: d1400646-6d97-7844-8f4c-231310308d39
* Content: [ItemsControl.ItemContainerStyle Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemscontrol.itemcontainerstyle#Windows_UI_Xaml_Controls_ItemsControl_ItemContainerStyle)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemscontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemscontrol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
@micahl

**Comment by citelao** [comment]
I agree. I would love to understand if I can bind to the item in the `ItemContainerStyle`.

**Comment by chigy** [comment]
@anawishnoff , please take a look.

**Comment by anawishnoff** [comment]
Looking into this now. 

@citelao just need a bit of clarification - what exactly do you mean by binding to the item in ItemContainerStyle? Are you asking about the use case of changing a setter property/ItemContainerStyle in the code-behind?

**Comment by anawishnoff** [comment]
@michael-hawker @citelao @chigy 

A pull request has been opened [here](https://github.com/MicrosoftDocs/winrt-api/pull/1389). Please feel free to review it and let me know if I left out any important sections or details that would benefit this page.

**Comment by citelao** [comment]
Hi @anawishnoff! Thanks for the response. I wanted some clarification to see if I could bind AutomationProperties of the item container using styles:

```
<ListView>
  <!-- ... -->
  <ListView.ItemContainerStyle>
    <Style>
       <Setter Property="AutomationProperties.HelpText" Value="{Binding SomePropertyOnTheItem}" />
    </Style>
  </ListView.ItemContainerStyle>
</ListView>
```

But I consulted with a XAML expert on my team and found the answer to be "no." 

I ended up creating a custom derivation of `ListView` as suggested by [this StackOverflow question](https://stackoverflow.com/questions/39043795/automationproperties-helptext-doesnt-work-on-uwp-listview)

**Comment by anawishnoff** [comment]
@citelao Got it, glad you got it figured out!
