### ISSUE TITLE
OnNavigatedFrom not called by default

### ISSUE THREAD

**Issue by fmccown** [MicrosoftDocs/winrt-api#712]
The OnNavigatedFrom() method is not called by default. A call to Frame.GetNavigationState() must be added to the OnSuspending() event handler in App.xaml.cs to trigger the calling of OnNavigatedFrom() method.  This information should be included in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde24ba9-744f-da43-3ec2-8ce312e6fa12
* Version Independent ID: e86233a8-5062-d9f8-8b71-97a6c0421f45
* Content: [Page.OnNavigatedFrom(NavigationEventArgs) Method (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.page.onnavigatedfrom#Windows_UI_Xaml_Controls_Page_OnNavigatedFrom_Windows_UI_Xaml_Navigation_NavigationEventArgs_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.page.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.page.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by fmccown** [comment]
To further clarify, the MainPage's OnNavigatedFrom() method is not called by default when the app is terminated unless Frame.GetNavigationState() is added to OnSuspending(). If navigating to another page from within the app, OnNavigatedFrom() is called by default.

**Comment by chigy** [comment]
@fmccown - Thank you for the feedback. Suspending an app does not navigate Frames, thus pages do not get OnNavigatedFrom called. In case your scenario requires OnNavigatedFrom to be called on the page, use Frame.GetNavigationState which will navigate the Page to Null and will call the Page's OnNavigatedFrom.

I'm working to get the document updated to make this clearer.

**Comment by chigy** [comment]
@fmccown , the document was updated. Let me know if there is anything else.
