### ISSUE TITLE
NavigationViewPaneDisplayMode.Top does not update the selectedItem at the ViewModel

### ISSUE THREAD

**Issue by Leisvan** [MicrosoftDocs/winrt-api#713]
My NavigationView items's source is an ICollectionView in the ViewModel. I make the correct conversions and data templates and bind a property in my ViewModel to the MenuItemsSource property of the NavigationView. When I select an item in the NavigationView or change the CurrentItem at the ICollectionView the other end updates the selected item. Well, that doesn't happens when the NavigationViewPaneDisplayMode property in the NavigationView is set to "Top".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4dc6f7-f3bd-16b7-7dbc-56727af3fb97
* Version Independent ID: 89dadeaf-9bba-a58a-24cb-f731de2b7265
* Content: [NavigationView Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.NavigationView)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by YuliKl** [comment]
@Leisvan - Thank you for the bug report. I believe this is the same issue as [NavigationView does not update selected Item when Display Mode is set to Top](https://github.com/Microsoft/microsoft-ui-xaml/issues/86). In case I am mistaken, please open a new issue in [Microsoft-ui-xaml](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose) to track this.
