### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#714]
Really would like to see specific C++/winrt examples for the  usage of every class and method. How to declare a virtual drawing surface and place it as the content of a Grid or Canvas, how to draw a few shapes into it, how to declare a handler for draw events, etc. etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 252d3758-5db3-e4dc-a6c3-7c27a8580a3e
* Version Independent ID: f9107e9d-cc33-77da-930e-2a8f00ab4ea0
* Content: [CompositionVirtualDrawingSurface(RectInt32\[\]) Class (Windows.UI.Composition) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.composition.compositionvirtualdrawingsurface)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositionvirtualdrawingsurface.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.composition.compositionvirtualdrawingsurface.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @jevansAN, CompositionVirtualDrawingSurface inherits from CompositionDrawingSurface (and adds just one member to that). There's a C++/WinRT CoreWindow (admittedly, not a XAML app) code example of CompositionDrawingSurface here: https://docs.microsoft.com/windows/uwp/composition/composition-native-interop. And then this topic shows how to use Composition + XAML with C++/WinRT: https://docs.microsoft.com/windows/uwp/composition/using-the-visual-layer-with-xaml. I realize that these don't show exactly what you're asking for (and we don't aim to have a code example for EVERY class and member), but I wanted to draw those two topics (and their code examples) to your attention to see whether together they constitute any help with your scenario.

**Comment by stevewhims** [comment]
Hi, @jevansAN. I'll go ahead and close this issue now. It's been a while, and my comment above is the resolution that I'd offer. Please reopen if I made a mistake in closing. ~Steve

**Comment by jevansAN** [comment]
I appreciate the response, Steven.


On Jan 23, 2019, at 12:33 PM, Steven White <notifications@github.com> wrote:

Closed #714 <https://github.com/MicrosoftDocs/winrt-api/issues/714>.
