### ISSUE TITLE
How should i use this event?

### ISSUE THREAD

**Issue by dhlolo-envision** [MicrosoftDocs/winrt-api#720]
I tried and failed to use my own customed event to override system app close event:
            SystemNavigationManagerPreview.GetForCurrentView().CloseRequested += closeRequestedHandler;
and I made a function as:
public async void closeRequestedHandler(object sender, SystemNavigationCloseRequestedPreviewEventArgs args)
        {
            x = 111;
            MessageDialog md = new MessageDialog("Catch App close");
            var tUI = md.ShowAsync();
            await Task.Delay(TimeSpan.FromSeconds(3));
            tUI.Cancel();
        }

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cd653644-7246-93a2-5fb1-035c487d548b
* Version Independent ID: 0bc615cc-1401-a197-2454-e35bf1d256e0
* Content: [SystemNavigationManagerPreview.CloseRequested Event (Windows.UI.Core.Preview) - UWP app developer](https://docs.microsoft.com/zh-cn/uwp/api/windows.ui.core.preview.systemnavigationmanagerpreview.closerequested)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.preview.systemnavigationmanagerpreview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.core.preview.systemnavigationmanagerpreview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by dhlolo-envision** [comment]
It's closed now, there should be "e.Handled = true;" at the begin of the function, so as to prevent the default shutdown process.

**Comment by hhguijin** [comment]
I did the same thing but the program never reached the event handler of my own when I closed the app. Why?

**Comment by GrantMeStrength** [comment]
Hi! I'm sorry, we're focusing on issues with the documentation when report via this channel. We can't offer general support. However, I would suggest you visit Microsoft Q&A if this is still an issue for you. Here's the link:  https://docs.microsoft.com/en-us/answers/index.html
