### ISSUE TITLE
Compiler error C2280 when try to register callback.

### ISSUE THREAD

**Issue by art-wenyi** [MicrosoftDocs/winrt-api#721]
Hi, I am trying to register a callback after device enumeration is complete. 
The code like this:

void DeviceWatcher_EnumCompleted(DeviceWatcher const sender, IInspectable const args){ // blank print here}
TypedEventHandler deviceInfoEnumCompleted = TypedEventHandler&lt;DeviceWatcher, IInspectable&gt;(DeviceWatcher_EnumCompleted);
deviceWatcher.EnumerationCompleted(auto_revoke, deviceInfoRemovedHandler);

For Added, Removed and Updated, it all success, only this one has error.
Would you please help me with it?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49dd87da-d4a9-e6c3-7aab-e8e799a6d0ce
* Version Independent ID: 43a6e630-febc-4a85-7340-935cf21cf38e
* Content: [DeviceWatcher.EnumerationCompleted Event (Windows.Devices.Enumeration) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicewatcher.enumerationcompleted)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.devicewatcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.enumeration.devicewatcher.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by art-wenyi** [comment]
I only find my error when I post =.=. My type error on registration, changed to deviceWatcher.EnumerationCompleted(auto_revoke, DeviceWatcher_EnumCompleted); and it works.
Awkward =.=

**Comment by mcleanbyron** [comment]
Thanks for submitting your issue, @art-wenyi. It sounds like you figured out the solution to your problem on your own, so I'm closing this issue. If you haven't done so already, you might also refer to the device enumeration sample [here](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DeviceEnumerationAndPairing).
