### ISSUE TITLE
Code values ?

### ISSUE THREAD

**Issue by Tryum** [MicrosoftDocs/winrt-api#723]
Would be nice to provide common error code in the documentation.
Also I noticed that the preview of the Code value in msvc2017 is a masked value of the actual value returned by Code(), is this documented somewhere ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7292563c-1603-2ded-73a4-9dc69928f644
* Version Independent ID: f804b998-6132-b823-95a7-3d468d308236
* Content: [MediaCaptureFailedEventArgs.Code Property (Windows.Media.Capture) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapturefailedeventargs.code#Windows_Media_Capture_MediaCaptureFailedEventArgs_Code)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapturefailedeventargs.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.capture.mediacapturefailedeventargs.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by atiyka** [comment]
I'm also interested in code values. Thank you!

**Comment by drewbatgit** [comment]
Thanks for taking the time to open an issue and we sincerely apologize for the delayed response. The code values are bubbled up from the underlying system, so there's not a set list of error codes that are returned, and without access to the underlying media pipeline, there's no path to recovery at runtime other than retrying. It may be useful to log the error codes/messages and if there is a consistent failure, you can search the Media Foundation documentation for insight into what might be causing the error.
