### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by SilverSilence** [MicrosoftDocs/winrt-api#724]
"All color info is stripped from the bitmap when the BitmapIcon renders in an AppBarButton."

This seems to not be true? I'm using a BitmapIcon inside a Grid and it still got stripped of its color.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b12a439-32ae-b5c1-988b-2f593394ed1b
* Version Independent ID: 0ebae0f4-aa05-4833-c09f-54f56f169645
* Content: [BitmapIcon Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.BitmapIcon)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.bitmapicon.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.bitmapicon.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
@SilverSilence - Thank you for the feedback. The documentation already appears to have been resolved. BitmapIcon always strips out the color, not just for AppBarButton. You can override that (again, not just for AppBarButton), by setting BitmapIcon.ShowAsMonochrome.
