### ISSUE TITLE
Hard to determine what Limited-Access Means

### ISSUE THREAD

**Issue by RoseHiggins** [MicrosoftDocs/winrt-api#729]
These documents refer to requiring limited access and say to look at the pinning secondary tile documents.  The secondary tile docs I found did not reference limited access, so I'm at a loss.  If there is a doc that explains it that I could not find, it should be linked in the documentation for the APIs that require limited access.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8237598a-dcef-3a70-fab2-4275d15add39
* Version Independent ID: c0bb397a-406a-73b7-fc26-a5f96f9a26ea
* Content: [TaskbarManager Class (Windows.UI.Shell) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.shell.taskbarmanager)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.shell.taskbarmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.shell.taskbarmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
Hi Rose,

The limited access referred to in the docs is defined here:

https://docs.microsoft.com/en-us/windows/uwp/design/shell/pin-to-taskbar#4-pin-your-app

Essentially, it just requires user approval. I agree that the documentation is unclear, I'll make a task to update the documentation.

-Shawn

**Comment by RoseHiggins** [comment]
Thank you so much for speedy help!
