### ISSUE TITLE
Event WebResourceRequested not defined

### ISSUE THREAD

**Issue by nicowitteman** [MicrosoftDocs/winrt-api#731]
Trying to figure out what i am doing wrong: I cannot find the event WebResourceRequested for my WebView in a UWP app. I have the latest Win10 SDK installed 10.0.17134), UWP 6.2.2. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f79ab8-f9a0-a9a1-17b7-3392a052beac
* Version Independent ID: df35ce59-f871-1819-80e4-b76a4391fd4d
* Content: [WebView.WebResourceRequested Event (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.webresourcerequested)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.webview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jwmsft** [comment]
@nicowitteman,
The auto-generated requirements block that indicates the required SDK version is currently missing from Event pages. We are working to correct this.
This event requires [SDK 17763](https://developer.microsoft.com/windows/downloads/windows-10-sdk).
**Device family: Windows 10, version 1809 (introduced v10.0.17763.0)** 
**API contract: Windows.Foundation.UniversalApiContract (introduced v7)**

**Comment by nicowitteman** [comment]
Thanks for the info. Too bad it took me so long trying to figure it out for myself.

**Comment by sharkAndshark** [comment]
how can i get the response content and change it?
i just get null....
`
      private async void Webview1_WebResourceRequested(WebView sender, WebViewWebResourceRequestedEventArgs args)
        {
            var res = args.Response;
            var isNull = res == null;//True
        }
`

**Comment by michael-hawker** [comment]
@jwmsft the page still hasn't been updated to list the SDK requirement for this event.  Is there another bug tracking the generation of these pages so that it can be updated?

**Comment by michael-hawker** [comment]
@sharkAndshark probably best to start a new issue, but the `WebResourceRequested` occurs before the response, it's for manipulating the request or providing a cached or alternate response.

**Comment by jwmsft** [comment]
@michael-hawker, this update is included with a broader update to the UWP API docs scheduled for Q1 2020.
