### ISSUE TITLE
`media` and `Returns` descriptions are incorrect

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#732]
The description for the `media` parameter says: "The object representing the new outgoing call." This is not a "call" object. It's a `VoipPhoneCallMedia` enum. When fixing this, please ensure the new description isn't too vague as described in #733.

The description for the return value says: "The object representing the new incoming call." It's not an "incoming" call. It's an "outgoing" call.

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d206afd2-5d58-49a2-2b04-01951fb8c687
* Version Independent ID: aa75e07f-ae91-5063-d3c2-ae2783e6d4a7
* Content: [VoipCallCoordinator.RequestNewOutgoingCall(String, String, String, VoipPhoneCallMedia) Method (Windows.ApplicationModel.Calls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.voipcallcoordinator.requestnewoutgoingcall)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.voipcallcoordinator.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.voipcallcoordinator.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hi Adam, 

Thanks for your feedback! I am going to contact you internally, and we can update this thread when a solution is reached.

Nick

**Comment by knicholasa** [comment]
The page is now updated with correct information, the modifications will show up soon.
