### ISSUE TITLE
Description of `media` parameter is vague

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/winrt-api#733]
I'm confused about what the `media` parameter means and how to decide what to pass there. To give you an idea of my confusion, here are some questions that come to mind when thinking about how to use the `media` parameter:
  - If I'm receiving a call and the caller has his video on, should I pass `VoipPhoneCallMedia.Video` here?
  - Should I pass `VoipPhoneCallMedia.Video` if the caller has a camera but the caller currently has his video off (since the caller might later turn on his video turning this into a video call)?
  - If the callee (me) has a camera, should `VoipPhoneCallMedia.Video` be passed here?

In summary, it's unclear whether the `media` parameter the caller or the callee's state and whether it's about the presence of a camera or the presence of an active video stream in the call.

Perhaps giving some examples of how the system uses this parameter could shed light on the appropriate value to pass here.

When making tweaks to the `media` parameter description, ensure to update the `media` description in other places in the docs (e.g. `RequestNewIncomingCall`, `VoipPhoneCall.NotifyCallAccepted`).

Adam Comella
Microsoft Corp.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b02d937e-cc84-db24-f937-162da290df58
* Version Independent ID: ef32709d-5280-63ad-0d9c-c14695aded5e
* Content: [VoipCallCoordinator.RequestNewAppInitiatedCall(String, String, String, String, VoipPhoneCallMedia) Method (Windows.ApplicationModel.Calls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.calls.voipcallcoordinator.requestnewappinitiatedcall)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.voipcallcoordinator.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.calls.voipcallcoordinator.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hi Adam, 

Thanks for your feedback! I am going to contact you internally, and we can update this thread when a solution is reached.

Nick

**Comment by knicholasa** [comment]
The page is now updated with more complete information, the modifications will show up soon.
