### ISSUE TITLE
Broken Link:  Canvas.ZIndex

### ISSUE THREAD

**Issue by dan-meier** [MicrosoftDocs/winrt-api#736]
Looks like all the links to "Canvas.ZIndex" are broken on this page.  The link points to https://docs.microsoft.com/en-us/uwp/api/canvas_zindex, which returns a "404 - Page not found" error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fed10e1-9283-ba00-dccd-998f1c135c9e
* Version Independent ID: 2dcd2ecd-94cd-b106-b828-1f70a909fbc2
* Content: [Canvas.SetZIndex(UIElement, Int32) Method (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.canvas.setzindex)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.canvas.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jevansaks** [comment]
I think the problem is that Canvas.ZIndex isn't actually a property, it's Canvas.ZIndexProperty.

**Comment by jwmsft** [comment]
Links to attached properties have been updated.
