### ISSUE TITLE
Different XML in the UWP .appxmanifest sample in the docs and in the sample repo

### ISSUE THREAD

**Issue by Sergio0694** [MicrosoftDocs/winrt-api#739]
As the title says, the docs indicate that for UWP application, the XML code should only contain `<uap5:Extension Category="windows.startupTask">`, with no explicit entry point and executable, while the .appxmanifest file in the sample repo (see [line 66](https://github.com/Microsoft/AppModelSamples/blob/master/Samples/TestStartup/TestStartup/Package.appxmanifest#L66)) includes the `Executable` and `EntryPoint` parameters as well.
Which one is the right one?

Sidenote: tried both, step by step, none seems to work for me (see [this SO question](https://stackoverflow.com/questions/53343852/uwp-app-fails-to-start-on-login-using-the-startuptask-apis)).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9f62b48-2100-6dbf-173e-3b10184b0c8f
* Version Independent ID: 3f376d66-a0e5-62bf-9d6c-408661bb8baa
* Content: [StartupTask Class (Windows.ApplicationModel) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.startuptask)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.startuptask.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.startuptask.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Sergio0694** [comment]
Also @knicholasa - I've tried following the docs on two different UWP apps using Desktop Bridge and I couldn't get either of them to run properly (see [this SO question](https://stackoverflow.com/questions/53343852/uwp-app-fails-to-start-on-login-using-the-startuptask-apis) I opened).

EDIT: also paging @qmatteoq while I'm at it, not sure what's the proper support channel for Desktop Bridge issues, but you might be interested in that SO question 😄

EDIT n. 2: I've got help from Stefan Wick on SO and managed to fix that, turns out the extension described in the docs as being for UWP apps is also the right one to add to the package manifest file, if a UWP app is inside a package and not a standalone app. I think it might be a good idea to mention this in the post, as it's not really clear from the code samples provided there and on GitHub 👍

**Comment by knicholasa** [comment]
Hi @Sergio0694, thanks for the in-depth write up, and you did the right thing going to SO to get your issue resolved. We use feedback on the docs site to improve our documentation. 

I agree that this document could be more clear, and I am working on changing the wording to address the issue you raised. Like Stefan said on SO, our documentation around mixed UWP and win32 apps is evolving. 

I'm wondering if your confusion centered around the term "Desktop Bridge App". That term generally refers to a desktop application that has been packaged to allow it to be published in the Microsoft Store and use UWP APIs (along with a few other features). It does not refer to a UWP app that may have some other desktop app components. See the documentation here for more information: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root .

Would changing this page to be more specific about what we mean by UWP App vs Desktop Bridge App have helped you avoid your issue?

**Comment by Sergio0694** [comment]
Hi @knicholasa - thank you for your reply!
Yeah part of my confusion was about the term "Desktop Bridge", which I assumed covered both Win32 programs extended with possibly UWP APIs, as well as UWP apps extended with Win32 components, as from what I understand, in both cases you still end up with a packaging projects which links to the various executables in the bundle.

The specific issue I had was that the docs didn't explicitly mention where to place the XML declaration for a startup task, in case you wanted to startup a UWP app which also happened to be the entry point of a package project. As I've mentioned before, the code sample just says to place that declaration either in the `.appxmanifest` file of the UWP app, if it's a standalone UWP app, or in the `.appxmanifest` file of the packaging project, if the Win32 program was the actual entry point of the bridge app.

What's missing is the specific case where a UWP app is the entry point of a packaging project (in which case you have to place the UWP declaration in the package manifest instead, not in the UWP app project manifest). From what I understand this is not really a common practice (as most devs would expand an original Win32 app towards UWP, not the other way around starting with a UWP app in the first place), but still, since this is actually possible I think it might be worth mentioning.

Thanks again for your help! 😊

**Comment by knicholasa** [comment]
@Sergio0694 You're very welcome :) And thanks for clarifying, I'll look into that case when I redo the wording on this page.
