### ISSUE TITLE
This property not work at start up !

### ISSUE THREAD

**Issue by slewden** [MicrosoftDocs/winrt-api#740]
This doesn't work on my machine ! NavigationView is always open when application start
In design mode sometimes it work, sometimes not !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e748bea5-7d20-2614-0b36-ce0a6495f658
* Version Independent ID: 134ae890-b156-32be-6b16-4fe6c7258568
* Content: [NavigationView.IsPaneOpen Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/fr-fr/uwp/api/windows.ui.xaml.controls.navigationview.ispaneopen?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DFR-FR%26k%3Dk(Windows.UI.Xaml.Controls.NavigationView.IsPaneOpen)%3Bk(VS.XamlEditor)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by YuliKl** [comment]
@slewden - Thank you for reporting this bug. The feature team has made fixes to the IsPaneOpen property and it should be working as expected in the latest [Microsoft.UI.Xaml NuGet package](https://www.nuget.org/packages/Microsoft.UI.Xaml/). 

If you encounter any other bugs with NavigationView, please report them in the [Microsoft-ui-xaml GitHub repo](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose).
