### ISSUE TITLE
Base Class, not Collection Class

### ISSUE THREAD

**Issue by kburgoyne** [MicrosoftDocs/winrt-api#755]
"Represents a collection of map data" is misleading. This is only a base class useful for deriving other classes from. It would be extremely useful for this page to list the derived classes. In particular, MapElementsLayer should be mentioned as the class the user is most likely looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5fe7a61-0560-fd35-e3f4-a73184a2caa7
* Version Independent ID: 038cbb77-40de-4c46-9e8e-d275a6d1c841
* Content: [MapLayer Class (Windows.UI.Xaml.Controls.Maps) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.maps.maplayer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.maplayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.maplayer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
Thank you for logging this. Your point is well taken, but I don't see this as a specific issue with the MapLayer class. Adding the comment you've requested is more of a one-off fix for a class of issues that exists in quite a few places. I'd like to address this as a more fundamental issue across all UWP documentation, which means it will likely take a little longer than just adding a note in the documentation.

I'll post more updates when I have them.

**Comment by hickeys** [comment]
@kburgoyne Okay, so almost two years later I think I finally have *sort of* addressed this. As I said in 2018, this is an issue with every parent class in UWP, and there's no straightforward way to manually direct users to the "right" class. However, I've finally managed to add a list of derived types to every class page. As you can see now, the MapLayer class lists MapElementLayer as a derived type, which at least provides a suggestion that maybe you should be using that instead. 

It isn't exactly what you were asking for, but hopefully it helps some people. If you have any other suggestions for this issue, please let me know. Otherwise, thanks for your patience!

Shawn

**Comment by kburgoyne** [comment]
@hickeys Woah, I'm impressed with your devotion to addressing this. I'm assuming you're saying you've added the "Derived" lists I'm seeing on the pages? I can't keep clear what's in different regions of the docs.  I remember such sections on the old MSDN pages.  If this is what you've added, it's seriously cool.  

The one subsequent step I'd recommend is some kind of list length limited with a button (whatever) to say "show me the rest of the list".  I know I've seen that pattern somewhere in the documentation.  

If you look at the "Exception" class (as a good example), the list of derived classes makes the page pretty long before getting down to anything below the derived classes.  That being said, it's still way better to have the list.  

I remember using the derived lists on the MSDN site as a path toward finding the specific class I wanted.  As a simple minded example of this, knowing (or guessing) there is an existing Exception derived class that would be the best to use for a throw but not having any idea what specifically it is.  So the easy path is to pop over to the Exception class page and browse down the list of derived classes.  

Or another example would be knowing about one class but not realizing there is a derived class which "might" be a better option.  The derived class list can be very educational for this purpose.

Anyway, what you've added is a powerful upgrade to the docs. Thanks.
