### ISSUE TITLE
How can I set AudioEffectType value to NoiseSuppression

### ISSUE THREAD

**Issue by 07101994** [MicrosoftDocs/winrt-api#756]
I want to set the AudioEffectType value to AudioEffectType.NoiseSuppression. I am not able to find any way to set AudioEffectType. Can you please help me with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf3c8af-b4f3-905d-e06f-355c68fdd2f5
* Version Independent ID: 4a9e9822-94e0-4299-6a5b-31ecc0aa85ff
* Content: [AudioEffect.AudioEffectType Property (Windows.Media.Effects) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.effects.audioeffect.audioeffecttype)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.effects.audioeffect.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.effects.audioeffect.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
The AudioEffectType property is read-only and is intended to allow apps to categorize effects that are available. It's not intended to for enabling or disabling effects. The [Audio Effects Discovery Sample](https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Official%20Windows%20Platform%20Sample/Audio%20effects%20discovery%20sample) linked at the bottom of the page demonstrates the scenario of retrieving the effects provided by an audio device. The sample uses the AudioEffectType as a label for each discovered effect.
