### ISSUE TITLE
VideoEncodingProperties.CreateH264 method documentation says it will create H.263 encoding properties

### ISSUE THREAD

**Issue by ArturAguiar** [MicrosoftDocs/winrt-api#761]
Looks like the method name and documentation don't match here. Intuitively, CreateH264 should create H.264 encoding properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df4a05ad-2f5b-ef28-4637-753b1da0689f
* Version Independent ID: 0fd29644-c66a-8c21-eb15-558143bf3600
* Content: [VideoEncodingProperties.CreateH264 Method (Windows.Media.MediaProperties) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.videoencodingproperties.createh264)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.videoencodingproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.videoencodingproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Thanks for reporting this! This fix for this should be visible on the live site within ~24 hours.
