### ISSUE TITLE
Broken link.

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#763]
The "Bluetooth SIG-defined Service UUIDs" link is broken.
Consider using: https://www.bluetooth.com/specifications/gatt/services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfa2f9b3-6764-929a-8fbc-b1a61d204b36
* Version Independent ID: f6df42c4-345a-eefe-8be5-cd7ccf6e711c
* Content: [GattServiceUuids Class (Windows.Devices.Bluetooth.GenericAttributeProfile) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Bluetooth.GenericAttributeProfile.GattServiceUuids)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattserviceuuids.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.bluetooth.genericattributeprofile.gattserviceuuids.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @EddieLotter. Thanks for filing this issue, and my apologies for the delay in responding.

I've published an update to the topic to fix the link. I'll go ahead and close this issue now.

Thanks again!
Steve

**Comment by EddieLotter** [comment]
@stevewhims, no problem. :) Thanks for taking care of it.
