### ISSUE TITLE
No "backgroundMediaRecording" capabilities!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#764]
There is no "backgroundMediaRecording" capabilities [here](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations).

**Comment by mcleanbyron** [comment]
Thanks for bringing this to our attention. I have added an entry for that capability to the article you mentioned, and this change should be published to the live docs site in the next few days.
