### ISSUE TITLE
SpatialInteractionManager does not trigger events after 17763.134 Hololens update

### ISSUE THREAD

**Issue by ThJOD** [MicrosoftDocs/winrt-api#765]
[Enter feedback here]
Hello,
since we updated the hololens to Windows Version: 17763.134 
we have the problem that the spatialinteractionmanager does not trigger its events anymore and therefore no sources are detected and interaction is impossible.

I was able to reproduce the error on the following Windows UWP sample:
Windows-universal-samples/Samples/SpatialInteractionSource
If you edit the file: cpp/HolographicPaintMain.cpp you can reproduce it.
Just replace the Lines 43 - 72 with:
"""
    //m_spatialInteractionManager = SpatialInteractionManager::GetForCurrentView();
    // Handle source detectionand loss by adding wrappers which will transform low level interactions into application-level commands
    m_sourceDetectedToken = 
        SpatialInteractionManager::GetForCurrentView()->SourceDetected += 
            ref new TypedEventHandler<SpatialInteractionManager^, SpatialInteractionSourceEventArgs^>(
                std::bind(&HolographicPaintMain::OnSourceDetected, this, _1, _2));
    m_sourceLostToken =
        SpatialInteractionManager::GetForCurrentView()->SourceLost +=
            ref new TypedEventHandler<SpatialInteractionManager^, SpatialInteractionSourceEventArgs^>(
                std::bind(&HolographicPaintMain::OnSourceLost, this, _1, _2));

    // SourcePressed is raised when a button is pressed (or in case of Air Tap for Hand) and we will transmit this event to the corresponding source wrapper
    // to take actions such as opening the tool selection carousel or validating a tool
    m_sourcePressedToken =
        SpatialInteractionManager::GetForCurrentView()->SourcePressed +=
            ref new TypedEventHandler<SpatialInteractionManager^, SpatialInteractionSourceEventArgs^>(
                std::bind(&HolographicPaintMain::OnSourcePressed, this, _1, _2));

    // Source Updated is raised when the input state or the location of a source changes. The main usage is to display the too associated to a controller
    // at the right position
    m_sourceUpdatedToken =
        SpatialInteractionManager::GetForCurrentView()->SourceUpdated +=
            ref new TypedEventHandler<SpatialInteractionManager^, SpatialInteractionSourceEventArgs^>(
                std::bind(&HolographicPaintMain::OnSourceUpdated, this, _1, _2));

    // Interaction detected is raised when the select button is pressed which will allow to delegate gesture recognition to a SpatialGestureRecognizer
    m_interactionDetectedToken =
        SpatialInteractionManager::GetForCurrentView()->InteractionDetected +=
            ref new TypedEventHandler<SpatialInteractionManager^, SpatialInteractionDetectedEventArgs^>(
            std::bind(&HolographicPaintMain::OnInteractionDetected, this, _1, _2));

"""
If you then run the sample on a hololens the source events won't be triggered anymore.
The thing is that this example still works if you just uncomment the line 43:
//m_spatialInteractionManager = SpatialInteractionManager::GetForCurrentView();

Then the events are triggered again.

My assumption is that the SpatialInteractionManager might be accidentally garbage collected and by keeping a reference to it you stop that from happening.

But I would say the SpatialInteractionManager should not be garbage collected anyway.

I would be very happy, if you could confirm whether this is a bug, or if you could explain, why this is a wanted behaviour.

Best regards
Jannik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e393f99-448b-1ed6-a821-859d5187dc43
* Version Independent ID: 9b32e364-cac4-2a36-600f-d739d671319d
* Content: [SpatialInteractionManager Class (Windows.UI.Input.Spatial) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.spatial.spatialinteractionmanager)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.spatial.spatialinteractionmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.input.spatial.spatialinteractionmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @TheoneandonlyJOD : I've contacted the feature team and asked them to respond with more info. Due to vacations, the response might not come before the new year.

**Comment by Karl-Bridge-Microsoft** [comment]
@TheoneandonlyJOD: Turns out this is a known issue. A switch to weak references requires you to keep the SpatialInteractionManager instance alive in order to get input. A fix is in development, but I'm unable to provide a release date at this time. Thanks!
