### ISSUE TITLE
See Also list contains duplicate items, and references to this page

### ISSUE THREAD

**Issue by rcbevans** [MicrosoftDocs/winrt-api#767]
See Also list contains duplicate items, and references to this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78bd1caa-862b-bfdc-7329-1a00aa9905e1
* Version Independent ID: 174dd38e-42a5-4803-bc18-07acfd074bbf
* Content: [SuspendingOperation Class (Windows.ApplicationModel) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.suspendingoperation)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.suspendingoperation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.suspendingoperation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by knicholasa** [comment]
Hey thanks for bringing this to our attention! It looks like those items are not duplicates although the pages look almost identical. The second set of links points to the corresponding windows.ui.webui page. I'll add some labels to make that more clear.
