### ISSUE TITLE
how can I add multiple folders selected from suggestions?

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/winrt-api#768]
RequestAddFolderAsync() method returns just 1 folder, but if the dialog with this api shows some folder suggestions and user selects all of them , we still get 1 folder returned instead of all selected folders by the user.

AreFolderSuggestionsAvailableAsync() tells us whether there are suggestion availble or not, but we do not have any method which returns a list of all folders which user selected to add? why is that? Basically even when the user selected multiple folders from suggestions, the method still adds only 1 of them to the library, which is a bug I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 058023ae-9935-f721-98aa-51ef12bdd001
* Version Independent ID: 14aee406-475e-adea-43aa-89c2b1b63d06
* Content: [StorageLibrary Class (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagelibrary)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagelibrary.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagelibrary.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Hi @touseefbsb - Thanks for reaching out to us with your question. This repo is specifically for feedback on the docs, and it is not intended as a resource for technical support or filing bugs against Windows APIs. For questions like this in the future I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/en-US/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions).

In this case, it sounds like RequestAddFolderAsync is indeed designed to only return one folder (and this is even noted in the code example for [AreFolderSuggestionsAvailableAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagelibrary.arefoldersuggestionsavailableasync). I reached out to the engineering team that owns this API. It sounds like  they responded with several ideas:

* You could check StorageLibrary.Folders immediately before and after the call to RequestAddFolderAsync() and diff the lists.
* You could [subscribe to changes in the library](https://docs.microsoft.com/en-us/windows/uwp/files/change-tracking-filesystem) to be notified if the user added more folders.
