### ISSUE TITLE
StorageProviderSyncRootManager throws exceptions and is not documented

### ISSUE THREAD

**Issue by AmadeusW** [MicrosoftDocs/winrt-api#769]
The `StorageProviderSyncRootManager` APIs throw exceptions and the documentation does not indicate why.

I'm trying to understand what I can accomplish with the StorageProviderSyncRootManager, and so far my experiments are unsuccessful because of exceptions thrown by lines marked with `// Exception` in the code below. Furthermore, the documentation is lacking and I don't know if I'm missing something obvious.

{System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Windows.Storage.Provider.StorageProviderSyncRootManager.___

```
public async Task InitializeAsync()
        {
// Exception 1:
            var test = StorageProviderSyncRootManager.GetCurrentSyncRoots();

            var folderPicker = new Windows.Storage.Pickers.FolderPicker();
            folderPicker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.Desktop;
            folderPicker.FileTypeFilter.Add("*");
            var userFolder = await folderPicker.PickSingleFolderAsync();
// Exception 2:
            var info = StorageProviderSyncRootManager.GetSyncRootInformationForFolder(userFolder);
            
            var sampleInfo = new StorageProviderSyncRootInfo()
            {
                Path = userFolder,
                Id = "sample text",
            };
// Exception 3:
            StorageProviderSyncRootManager.Register(sampleInfo);
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ebe7c3-e2a1-b60f-f424-14b32bdc7c39
* Version Independent ID: d279cbd4-8578-7b92-c6cb-61b98a346cf2
* Content: [StorageProviderSyncRootManager.GetSyncRootInformationForFolder(IStorageFolder) Method (Windows.Storage.Provider) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.storageprovidersyncrootmanager.getsyncrootinformationforfolder#Windows_Storage_Provider_StorageProviderSyncRootManager_GetSyncRootInformationForFolder_Windows_Storage_IStorageFolder_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.provider.storageprovidersyncrootmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.provider.storageprovidersyncrootmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Hi @AmadeusW. Generally speaking, Windows Runtime APIs are designed not to throw exceptions of the kind that we expect deployed code to handle at runtime. That's why the docs are not in the habit of mentioning them. However, there are some cases where that rule is not followed. I have sent your findings to the product team and will respond back with their guidance, and then I'll work with them on whether/what to document here regarding exceptions.

**Comment by AmadeusW** [comment]
Thank you! 
I would love to hack on this API, would you please connect me with the product team? My alias is amwieczo@microsoft.com and I would be happy to report back my experience to improve the docs.

**Comment by mcleanbyron** [comment]
Thanks for reaching out. Since you are a Microsoft employee, I will follow up with you internally.

**Comment by alim-n** [comment]
What are requirements to obtain permissions to use StorageProviderSyncRootManager?
I managed to run cloudmirror sample and started implementation in my project, however I can't figure out why I keep getting HRESULT: 0x80070005 (E_ACCESSDENIED). I've tried creating similar project structure by including UWP C# project into application packaging project, but it didn't change anything

**Comment by tqk2811** [comment]
Any example to use it?
Can it work look like "file on-demand" in onedrive sync app?
Thank

**Comment by lukeblevins** [comment]
@mcleanbyron @AmadeusW Can you please share how you figured out how to fix this? I'm still running into the same problem as @nzer even though I have broadFileSystemAccess and Windows Desktop extension referenced.

The error causes the program to break at the first line:
```
if (StorageProviderSyncRootManager.IsSupported())
 {
      var syncRoots = StorageProviderSyncRootManager.GetCurrentSyncRoots();
      foreach(StorageProviderSyncRootInfo syncRootInfo in syncRoots)
      {
            var cloudStorageItem = new DriveItem()
            {
                 Root = syncRootInfo.Path as StorageFolder,
                 Text = syncRootInfo.DisplayNameResource,
                 VirtualDriveIconPath = syncRootInfo.IconResource,
                 Path = syncRootInfo.Path.Path,
                 Type = DriveType.VirtualDrive,
             };
             list.Add(cloudStorageItem);
       }
 }
```
