### ISSUE TITLE
There is an error in the  Progress Property

### ISSUE THREAD

**Issue by Frederisk** [MicrosoftDocs/winrt-api#771]
The description should be: Gets the current progress of the "download" operation.
Instead of "upload".
And you should make it clear that this property is a BackgroundDownloadProgress Struct.
The same error exists in Visual Studio 2017.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 20a23550-5126-e2b0-f2a0-0aa4da29bcc8
* Version Independent ID: 07e6eec6-10e2-09e0-abbb-1a338a25a5bb
* Content: [DownloadOperation Class (Windows.Networking.BackgroundTransfer) - UWP app developer](https://docs.microsoft.com/zh-tw/uwp/api/windows.networking.backgroundtransfer.downloadoperation)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.downloadoperation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.backgroundtransfer.downloadoperation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @Frederisk, thanks for filing this issue. I have merged a change into master (it should be live within 24 hours) making the fixes that you point out. This fix will eventually find its way into Visual Studio. ~Steve
