### ISSUE TITLE
what is the default value?

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/winrt-api#774]
Please specify what is the default value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d642ee31-dd8e-55ce-364a-905f321f6552
* Version Independent ID: d39b52a0-feed-1836-0330-3df5bd9f99a5
* Content: [HttpBaseProtocolFilter.MaxConnectionsPerServer Property (Windows.Web.Http.Filters) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.filters.httpbaseprotocolfilter.maxconnectionsperserver#Windows_Web_Http_Filters_HttpBaseProtocolFilter_MaxConnectionsPerServer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.filters.httpbaseprotocolfilter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.filters.httpbaseprotocolfilter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @MNF, I've kicked off a thread with the product team, and I'll report back when I have any info to update the topic with. Thanks! ~Steve

**Comment by stevewhims** [comment]
@MNF, the update to this topic should be live within 24 hours, but here's a copy of the info I just added. Please let me know whether this helps, and we'll go ahead and close the issue if so.

The **MaxConnectionsPerServer** property determines the maximum number of TCP connections to an HTTP server allowed on the **HttpBaseProtocolFilter** object. The best value for your application to set this property to depends on your usage pattern, and on the server, and it also depends on whether you're optimizing for performance for a single query or performance for all queries.

The default value for this property is currently 6. But the default value is a function of the version of the **HttpBaseProtocolFilter**, and it is not guaranteed to be unchanged from one release to another.

**Comment by MNF** [comment]
Thanks, Looks good
