### ISSUE TITLE
Sample code?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#775]
Would love to see a few lines of sample code in C++/winrt showing how to read all bytes of a binary file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5000468-1b4c-a60f-c63e-2578cad0e0b0
* Version Independent ID: 368bd70a-2ddb-b18a-0120-cc466597ee02
* Content: [DataReader.LoadAsync(UInt32) Method (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader.loadasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I am following up with the engineering team to confirm what improvements we can make to these docs, and will update this issue when I know more.

**Comment by hkhmsft** [comment]
It looks like there is no actionable feedback here, so I am closing the issue. Please open a new issue if you have feedback you would like to be addressed.
