### ISSUE TITLE
Example code needed

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#776]
Just a few lines to show clearly how in C++/winrt one could read binary files. Especially if there is a series of files of files to be read, such as the contents of a StorageFolder. I've found some examples of reading in strings, but not binary data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9316ab88-b9fe-2400-1613-1885e34763bf
* Version Independent ID: 8e58ff87-5f01-a90e-5c9e-07e328533d6b
* Content: [IInputStream.ReadAsync(IBuffer, UInt32, InputStreamOptions) Method (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.iinputstream.readasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.iinputstream.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.iinputstream.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. I am following up with the engineering team to confirm what improvements we can make to these docs, and will update this issue when I know more.

**Comment by MelbourneDeveloper** [comment]
Yes, this definitely needs an example!

**Comment by daviddetweiler** [comment]
Should also mention in said future example that `ReadAsync` can (and does) return 0-length buffers for certain end-of-stream conditions (in my case, I observed this behavior on the `InputStream` of a `StreamSocket` whose connection had closed).

**Comment by hkhmsft** [comment]
I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate the suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
