### ISSUE TITLE
System Properties Page links to previous-version page

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#777]
Feel like it should link to the latest version of the page? (assuming there is one, if not there should be).  That page also doesn't have any introductions or context, it's just links.  It'd be nice if it was a table of property name and brief description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07176389-0e29-907b-5b9d-d50c1ca530df
* Version Independent ID: 4326075c-b954-ed41-2fa4-c60a582bba1d
* Content: [StorageItemContentProperties.RetrievePropertiesAsync(IIterable&lt;String&gt;) Method (Windows.Storage.FileProperties) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.storageitemcontentproperties.retrievepropertiesasync#Windows_Storage_FileProperties_StorageItemContentProperties_RetrievePropertiesAsync_Windows_Foundation_Collections_IIterable_System_String__)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.storageitemcontentproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.storageitemcontentproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
Looks like it should probably link here, though that page isn't labeled as such for this purpose: https://docs.microsoft.com/en-us/windows/desktop/properties/core-bumper

**Comment by mcleanbyron** [comment]
Thanks for alerting us about this issue. I've fixed the link in the article.
