### ISSUE TITLE
See Also should also link to the list of extra properties available for RetrievePropertiesAsync

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#778]
The example uses RetrievePropertiesAsync, but it doesn't tell you here where to find out what properties are available.  If you dig to the method, it has a link to an outdated page (filed a separate bug there about that), but this page should also link to that property list as well.  (outdated link would be http://msdn.microsoft.com/library/e86e5836-522f-4084-8bb3-4c0d4da9cb26)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4672134c-30c9-f848-71ff-b7f1d78e8f19
* Version Independent ID: cf34c717-8bdd-c949-3eba-8dc612a8689b
* Content: [StorageItemContentProperties Class (Windows.Storage.FileProperties) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.FileProperties.StorageItemContentProperties)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.storageitemcontentproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.storageitemcontentproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
See #777, think latest table type link would be something like this: https://docs.microsoft.com/en-us/windows/desktop/properties/core-bumper

**Comment by mcleanbyron** [comment]
Thanks for your suggestion! I have added this link to the page, and this change is now published to the live docs site.
