### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#779]
Would be interesting to hear the purpose of DetachBuffer(). What are the circumstances in which DetachBuffer() is useful?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eaf6e1f-929b-02d6-fa89-7ae341e1bac0
* Version Independent ID: 3eca355f-d556-5778-ad5f-525f82179cf2
* Content: [DataReader.DetachBuffer Method (Windows.Storage.Streams) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader.detachbuffer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by MikeHillberg** [comment]
It detaches the buffer from the DataReader, so that Disposing the DataReader won't delete it.

**Comment by jevansAN** [comment]
Ah - that is useful. To be able to retain the buffer. Thanks very much.

Jeff

On Dec 3, 2018, at 7:44 PM, MikeHillberg wrote:

It detaches the buffer from the DataReader, so that Disposing the DataReader won't delete it.

**Comment by mcleanbyron** [comment]
Thanks for submitting this feedback. It looks like @MikeHellberg has already answered your question about the purpose for DetachBuffer. I have also expanded the summary for this API ref page to include a few more details, and these updates should be published to the live site in the next few days.
