### ISSUE TITLE
Documentation is too vague for WaitForFrameToFinish

### ISSUE THREAD

**Issue by beteitle** [MicrosoftDocs/winrt-api#781]
We should explain what "current frame is finished" means exactly for WaitForFrameToFinish, which should be the time the next frame should start its pose-dependent rendering.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de586cf7-8f53-07b0-39cc-44d7670507fb
* Version Independent ID: 5e20abe2-dc78-7fad-b8ef-f2ebedb2ec07
* Content: [HolographicFramePresentWaitBehavior Enum (Windows.Graphics.Holographic) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicframepresentwaitbehavior)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicframepresentwaitbehavior.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.holographic.holographicframepresentwaitbehavior.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by drewbatgit** [comment]
Per our email thread, this content has been updated to 
“Wait for the time to start head pose dependent rendering for the next frame.  This method must only be called after PresentUsingCurrentPrediction has already been called on this frame.” 
Closing issue.
