### ISSUE TITLE
Is this really all there is?

### ISSUE THREAD

**Issue by ajventi** [MicrosoftDocs/winrt-api#782]
There must be more to tell us here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1af0f1-5e90-39ad-0cb1-3dc015880eaf
* Version Independent ID: 30cca0ac-4c05-2566-b3c0-733c0c58762c
* Content: [ListViewBase.ItemClick Event (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.itemclick)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by ajventi** [comment]
I am finding The following Link
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.itemclick
much more useful than any links into and out of this page

**Comment by chigy** [comment]
@micahl

**Comment by jevansaks** [comment]
> I am finding The following Link
> https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.itemclick
> much more useful than any links into and out of this page

The docs seem ok, and the link you provided here seems to be the same as the one you reported the issue on. Can you provide more details?
