### ISSUE TITLE
Stop with the stubs and give us something useful

### ISSUE THREAD

**Issue by ajventi** [MicrosoftDocs/winrt-api#783]
Put hyperlinks into the pages that actually have useful information, like RoutedEventHandler Stop wasting time with stub pages that do nothing but waste time please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e138cb-ad34-327c-4484-19e39d584102
* Version Independent ID: 290dc734-db22-7ffc-1ab6-b363fdbe8885
* Content: [ButtonBase.Click Event (Windows.UI.Xaml.Controls.Primitives) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.buttonbase.click)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.buttonbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.buttonbase.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
@kikisaints

**Comment by citelao** [comment]
This seems to be a recurring issue for XAML events.

@chigy, @kikisaints, can we find a way to automatically link event handlers to their delegates? I frequently load pages like this, then have to search *again* to learn what the delegate should look like.

Specifically, can event pages link:

* [x] To their owner (seems to be done on most pages)
* [ ] To their delegate (`RoutedEventHandler` in this case)

Thanks!

**Comment by jwmsft** [comment]
Links to delegates are now added automatically in the doc build.
