### ISSUE TITLE
Doesn't work for me.

### ISSUE THREAD

**Issue by Tobi696** [MicrosoftDocs/winrt-api#786]
&lt;TextBox PlaceholderText="placeholderString" HorizontalAlignment="Center" TextAlignment="Center" Height="26" Margin="117,151,117,0" Padding="3" TextWrapping="Wrap" Name="Username"  VerticalAlignment="Top" Width="137" Grid.Column="1"/&gt;

This produces invalid markup error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f014ca2e-97fa-b8cb-241f-f2e4dd182b67
* Version Independent ID: ff9618c2-a0e1-1980-1e2c-c3576dd00adb
* Content: [TextBox.PlaceholderText Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.placeholdertext)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by michael-hawker** [comment]
@Tobi696 the XAML you provided works for me in XAML Studio.  What error are you getting in Visual Studio?  If you're on the latest VS version and getting this error still, it'd be good to use the `Report a Problem` link in the dropdown next to the Quick Launch box at the top-right of the IDE:

![image](https://user-images.githubusercontent.com/24302614/53847974-8fe76a00-3f67-11e9-8f36-48e162344b57.png)
