### ISSUE TITLE
ApplicationTrigger requestAccess

### ISSUE THREAD

**Issue by kittycatbytes** [MicrosoftDocs/winrt-api#789]
When I try to run ApplicationTrigger.requestAsync from inside the UI thread, I get:
`0x80004005 - JavaScript runtime error: Unspecified error`
Does this function require user consent? I need to run a background task when the user inside our app (not the Microsoft user) changes. I was hoping to use this function to trigger this during these changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5865233-a56f-4211-c2ea-f6a008bec9ca
* Version Independent ID: f9a75e6f-6233-8dcd-e719-b8382b7194d2
* Content: [ApplicationTrigger.RequestAsync Method (Windows.ApplicationModel.Background) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.applicationtrigger.requestasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.applicationtrigger.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.applicationtrigger.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by kittycatbytes** [comment]
I was attempting to assign multiple triggers to the same task.  However, after getting past this problem, where I have individual background tasks for each trigger type, I now have the issue where I am unable to execute the background task more than once per app run.  On subsequent attempts, requestAsync returns "3", which is an unknown error.

**Comment by knicholasa** [comment]
Hi @kittycatbytes, feedback here is meant for issues related to documentation. I think the fastest way to get help with your issue would be to post to one of the developer forums here https://social.msdn.microsoft.com/Forums or find the resource that best meets your needs here https://developer.microsoft.com/windows/support .

Hope that helps!
