### ISSUE TITLE
How to use StandardUICommand in Xaml?

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/winrt-api#790]
I cannot get [StandardUICommand] working in Xaml.

I watched the Microsoft Ignite 2018 presentation [What's new for Windows UX developers: WinUI XAML and Fluent - BRK2108](https://www.youtube.com/watch?v=JI0brtoRwmA) and in there, Paul introduces the StandardUICommand and how to use it in Xaml. The example he gives is the following:

```
<Button>
   <Button.Command>
        <StandardUICommand Kind="Delete" Command="{x:Bind vm.DeleteCommand}" />
   <Button.Command>
</Button>
```

(See https://youtu.be/JI0brtoRwmA?t=2602 for the exact presentation.)

So, I went ahead and wanted to use StandardUICommand in my Xaml code too. Turns out, the [Kind]-property Paul sets above cannot be set in Xaml because it doesn't have an accessible setter!

What is going on here? I'd have thought the Xaml code presented by Paul (given how close it was to the release of the latest windows sdk) would have shown usable code to developers. Could you please give us examples (in this article) how to use StandardUICommand in Xaml?

Appreciate it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2476209c-27d8-986a-4df4-bef15c5cd9e6
* Version Independent ID: 9b00b0cf-0b8b-bd86-2500-3d513c80ef78
* Content: [StandardUICommand Class (Windows.UI.Xaml.Input) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.standarduicommand)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.standarduicommand.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.standarduicommand.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Felix-Dev! Thanks for the feedback. We're working on a commanding topic right now that should address your comments. I

**Comment by Felix-Dev** [comment]
Excellent! Looking forward to the documentation. Thanks!

**Comment by chigy** [comment]
@adambarlow for awareness

**Comment by adambarlow** [comment]
@Felix-Dev 
Thanks for reaching out. It's true we are working on new documentation in this regard. 

The reason you are running into this issue is that there is a bug in the implementation (which will be fixed in the next release). Regrettably, If you would like to use StandardUICommand with this SDK version you will need to do so in code behind. Or alternatively you can use XamlUICommand and set your own icons, shortcuts, etc.

**Comment by Felix-Dev** [comment]
@adambarlow 

Thanks for the info. Yes, I've seen it being listed in the changes included in the next Windows 10 SDK. 

Also went with XamlUICommand for the time being and will change them to StandardUICommand once that is working (in Xaml).

**Comment by VatsikDimon** [comment]
Why it not working with swipe item. I cannot use MVVM with swipe

**Comment by adambarlow** [comment]
@VatsikDimon can you describe your problem more in depth?

**Comment by VatsikDimon** [comment]
@adambarlow shore. I using mvvmlight in UWP, and cannot catch event on command in swipeitem control.

**Comment by sharpninja** [comment]
In the absence of the Kind property setter, how do we create a resource from a StandardUICommand using the constructor?

**Comment by Karl-Bridge-Microsoft** [comment]
@chigy @adambarlow - any updates on this? Was there a resolution that didn't get communicated here?

**Comment by adambarlow** [comment]
Yes, the API for this is now documented here, including the kind property and available commands:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.standarduicommand

**Comment by Karl-Bridge-Microsoft** [comment]
The API for this is now documented here, including the kind property and available commands:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.standarduicommand.
