### ISSUE TITLE
Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by urjapatel** [MicrosoftDocs/winrt-api#793]
On Calling below mentioned method for getting list of available serial ports throws exception
**"Error HRESULT E_FAIL has been returned from a call to a COM component."**

**Called Method**
Windows.Devices.Enumeration.DeviceInformation.FindAllAsync(String aqsFilter, IEnumerable`1 additionalProperties)

**Stack Strace**
Windows.Devices.Enumeration.DeviceInformation.FindAllAsync(String aqsFilter, IEnumerable`1 additionalProperties)

This exception occurs 2-3 times on calling FindAllAsync method again and again, after few trials I get list of ports available.
**How to solve this to get list of port on first time executing FindAllAsync method?**

**Code**
public async Task GetAllDevices()
{
string aqs = Windows.Devices.SerialCommunication.SerialDevice.GetDeviceSelector();

// Find all COM ports
var dis = await Windows.Devices.Enumeration.DeviceInformation.FindAllAsync(aqs, null);
}

Please help if anyone knows about this error. Thank you.

**Comment by ginami** [comment]
Hi @urjapatel -- thank you for your comment. Can you tell me which page in our docs this refers to? (This will help me route your question to the correct author.) Thank you!

**Comment by urjapatel** [comment]
This refers to below mentioned link.
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.devices.enumeration/deviceinformation_findallasync_1257462890.md

I hope this helps. Thank you.

**Comment by mcleanbyron** [comment]
I'm sorry your encountering this problem with this API. This repo is specifically for feedback on the docs, and it is not intended as a resource for technical support. I recommend that you ask this question on our [forums](https://social.msdn.microsoft.com/Forums/en-US/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions).
