### ISSUE TITLE
The GetResults() can't block the calling thread!

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#794]
The [System.Threading.Tasks.Task.Result](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1.result?view=netframework-4.7.2) property will block the caller thread. But why the IAsyncOperaion.GetResults() method can't?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b15ea25d-feb1-597e-439d-e9588fc09447
* Version Independent ID: bb93f39b-b721-873d-3306-5774a45c9a83
* Content: [IAsyncOperation&lt;TResult&gt;.GetResults Method (Windows.Foundation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperation-1.getresults#Windows_Foundation_IAsyncOperation_1_GetResults)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncoperation_tresult_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncoperation_tresult_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
GetResults() is asynchronous and will not block the calling thread. I am curious why it is that you're using these APIs directly. From the [IAsyncOperation page](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperation_tresult_#remarks)

> It's not common to use IAsyncOperation; directly even if you don't use a language-specific awaitable syntax. Each of the languages has extension points that are generally easier to use than the Windows Runtime interface. JavaScript has WinJS.Promise, and the then/done syntax. .NET has the AsTask extension method, and once the IAsyncOperation; is converted to a Task<TResult>, it's easier to get the result, cancel, get notification on completion, and so on. For C++/CX, you can wrap the calls using the Concurrency runtime (and use create_task). **In other words, IAsyncOperation; can be considered runtime-level infrastructure, which each of the languages use as a framework to support awaitable syntax or asynchronous programming models in their own way**.

Perhaps there is an easier way to do what you are attempting to do. For more information, I recommend opening a topic on [Microsoft Tech Community](https://techcommunity.microsoft.com) as GitHub issues are strictly for errors in technical documentation.
