### ISSUE TITLE
The link of the AsTask?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/winrt-api#795]
The link of the AsTask is the root of the System Namespace, is there an exactly page for the AsTask?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbfaabda-7b03-c053-c527-b583a82aeafd
* Version Independent ID: a0419a42-9f60-8f5a-bf2d-ca9ba57c99db
* Content: [IAsyncOperation&lt;TResult&gt; Interface (Windows.Foundation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperation_tresult_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncoperation_tresult_.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.iasyncoperation_tresult_.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
Thanks for the feedback. I've updated the link. Expect to see it reflected in the docs in the next few hours.
