### ISSUE TITLE
StorageFile.GetFileFromPathAsync Exceptions not documented

### ISSUE THREAD

**Issue by Felix-Dev** [MicrosoftDocs/winrt-api#798]
Please describe the possible exceptions which can be thrown by calling GetFileFromStoragePathAsync().

@ginami This is just a reminder about an issue which has been raised in the past already without a single comment from the MS docs team: See https://github.com/MicrosoftDocs/winrt-api/issues/576 (August, 25th). You assigned @laurenhughes to the issue yet we never got any comment from her/him. 
I don't want to criticize your system here, but I can't help but feel that some sort of control-system should be in place to check whether the assigned members actually comment/work on "their" issue.
The way it is all too often right now is that you, @ginami, assing someone to an issue, yet that person seemingly never bothers to take a look at it. With the result that it is up to the community to constantly raise the same issues again and again in the hope that at least once, someone at MS will actually take a look at it.
Does that sound acceptable to you?

So, please, this time, don't assign @laurenhughes to this issue because he/she apparently can't work on it. It would also be welcomed if you could make sure that the person you assigned actually takes a look at the issue and comment back to the community.

Appreciate it,
Felix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1a0b142-3819-3929-bc93-c4d8e0598978
* Version Independent ID: 932a8fe2-dc4e-ade9-e67d-45897840c037
* Content: [StorageFile.GetFileFromPathAsync(String) Method (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getfilefrompathasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by jillre** [comment]
Thanks for the feedback, @Felix-Dev. We're tracking this on https://github.com/MicrosoftDocs/winrt-api/issues/576.
