### ISSUE TITLE
Please add remark that InkCanvas needs Width and Height

### ISSUE THREAD

**Issue by jlautman** [MicrosoftDocs/winrt-api#799]
I added an InkCanvas to a ListView in some Microsoft internal test code, and was surprised when the ListView's background was visible in the app but no input reached the InkCanvas until I set the width and height. On the other hand, when I set the canvas directly as the XAML root the InkCanvas expanded to fit the entire app. I think it would be helpful to add something about this to the Remarks section. I suspect it has to do with InkCanvas not having a default MinHeight/MinWidth?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29c7ad0c-5df6-0677-083c-fd15ed7fc3cf
* Version Independent ID: 38d461fa-136c-5eee-bd1c-6eec26d5ed16
* Content: [InkCanvas Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.InkCanvas)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.inkcanvas.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.inkcanvas.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by Karl-Bridge-Microsoft** [comment]
@jlautman - thanks for the feedback. I've added more detail to both the API topic and the related conceptual topic.
