### ISSUE TITLE
How can a Win32 app be notified when the `DocumentTitle` changes?

### ISSUE THREAD

**Issue by quadrupleslap** [MicrosoftDocs/winrt-api#801]
How can a Win32 app be notified when the `DocumentTitle` changes?

Edit: For reference, DocumentTitle is a dependency property in the XAML WebView.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900eeab9-e94b-a29a-2b5d-665f9b5e43e0
* Version Independent ID: 2c1e903d-532d-0bb9-e136-9eb27522776e
* Content: [WebViewControl.DocumentTitle Property (Windows.Web.UI.Interop) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.web.ui.interop.webviewcontrol.documenttitle#Windows_Web_UI_Interop_WebViewControl_DocumentTitle)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.ui.interop.webviewcontrol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by GrantMeStrength** [comment]
Thanks for contacting us, and sorry for the delay.

It seems like there isn't a good way to do this in WebView:

https://stackoverflow.com/questions/61445905/uwp-webview-trigger-event-when-tab-title-changes-documenttitle

WebView has been replaced by  WebView2

https://docs.microsoft.com/en-us/microsoft-edge/webview2/

And if there is no notification mechanism this is great time to reach out the WebView2 team and make a feature request.

-John
