### ISSUE TITLE
Bounding volume required

### ISSUE THREAD

**Issue by joejo-unity** [MicrosoftDocs/winrt-api#803]
You must have set a bounding volume prior to setting this event or you will most likely get no surfaces from the spatial observer when you call GetObservedSurfaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97562317-0bd6-baa3-8d84-7321cbc423e2
* Version Independent ID: e9b1c180-5080-e1ae-d9b1-c62016fa91e2
* Content: [SpatialSurfaceObserver.ObservedSurfacesChanged Event (Windows.Perception.Spatial.Surfaces) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.surfaces.spatialsurfaceobserver.observedsurfaceschanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.surfaces.spatialsurfaceobserver.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.surfaces.spatialsurfaceobserver.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
I've added a note about what will happen if no bounding volume has been set. Thanks for logging the issue, and thanks for your patience.
