### ISSUE TITLE
Bounding volume required

### ISSUE THREAD

**Issue by joejo-unity** [MicrosoftDocs/winrt-api#804]
If you don't have a bounding volume set on your SpatialSurfaceObserver instance then you will not get any surfaces returned from this call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bff5819-b49f-db13-e0f5-d0c760ca514f
* Version Independent ID: ccf915c2-42ad-091d-305c-427289e78c73
* Content: [SpatialSurfaceObserver.GetObservedSurfaces Method (Windows.Perception.Spatial.Surfaces) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.perception.spatial.surfaces.spatialsurfaceobserver.getobservedsurfaces)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.surfaces.spatialsurfaceobserver.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.perception.spatial.surfaces.spatialsurfaceobserver.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
I've added a note about what will happen if no bounding volume has been set. Thanks for logging the issue, and thanks for your patience.
