### ISSUE TITLE
Important link

### ISSUE THREAD

**Issue by radev8** [MicrosoftDocs/winrt-api#805]
Thanks for including how to change the value.  This points to an obsolete feature.  should refer to ChangeView.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312e82a0-2119-24ed-2f39-42151b07aac4
* Version Independent ID: 80e3a8e2-a361-43fc-0030-8e035c402123
* Content: [ScrollViewer.ZoomFactor Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer.zoomfactor?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.ScrollViewer.ZoomFactor)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-VB)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.scrollviewer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.scrollviewer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
@micahl

**Comment by jwmsft** [comment]
Link was updated.
