### ISSUE TITLE
Should link to another doc explaining the different available contract versions

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#808]
It'd be nice to know where to find out which contract versions are available and which major sets of features they provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d455e949-526e-e3d6-fc15-444364fb9bad
* Version Independent ID: 9ad3c6f9-9c3f-fbca-6632-b552f545d28b
* Content: [ApiInformation.IsApiContractPresent Method (Windows.Foundation.Metadata) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.apiinformation.isapicontractpresent)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.apiinformation.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.metadata.apiinformation.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
I've added a note linking to our documentation on how to use API contracts. Thanks for your patience on this issue.
