### ISSUE TITLE
Sample code needed for C++/winrt

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#813]
The usual C++/winrt method of setting a property, e.g. theDialog.Title(L"The Title") doesn't seem to work here. Really need to see an example of how to create a ContentDialog programmatically using C++/winrt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16c14008-04b3-438b-5fae-3577cf233ab9
* Version Independent ID: 52f2f07b-034e-1d24-1b48-b4de7585e71a
* Content: [ContentDialog Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by stevewhims** [comment]
Hi, @jevansAN, for a property of type string (for example, CloseButtonText), passing a wide string literal as you show in your example is correct. But note that the Title property is documented not as being of type string but rather of type IInspectable. You can box a wide string literal (or any scalar value) to pass it to a property that expects an IInspectable, like this:

noWifiDialog.Title(winrt::box_value(L"No wifi connection"));

More info on un/boxing here, fyi: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/boxing

```cppwinrt
    Windows::Foundation::IAsyncAction MainPage::ClickHandler(IInspectable const&, RoutedEventArgs const&)
    {
        ContentDialog noWifiDialog;

        noWifiDialog.Title(winrt::box_value(L"No wifi connection"));
        noWifiDialog.Content(winrt::box_value(L"Check connection and try again."));
        noWifiDialog.CloseButtonText(L"Ok");

        co_await noWifiDialog.ShowAsync();
    }
```

**Comment by jevansAN** [comment]
Very nice, thanks! Finally I begin to understand IInspectable.

Jeff


On Jan 7, 2019, at 6:12 PM, Steven White <notifications@github.com> wrote:

Hi, @jevansAN <https://github.com/jevansAN>, for a property of type string (for example, CloseButtonText), passing a wide string literal as you show in your example is correct. But note that the Title property is documented not as being of type string but rather of type IInspectable. You can box a wide string literal (or any scalar value) to pass it to a property that expects an IInspectable, like this:

noWifiDialog.Title(winrt::box_value(L"No wifi connection"));

More info on un/boxing here, fyi: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/boxing <https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/boxing>

**Comment by stevewhims** [comment]
Cool, I'm happy to help. I'll go ahead and close the issue now, then. Thanks for filing this GitHub issue! ~Steve

**Comment by Ezmonie77** [comment]
Thanks everyone!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jevansAN** [comment]
No sooner was it closed than I ran into a method that use IReference arguments instead of IInspectable (ScrollViewer.ChangeView). So an IReference is different from IInspectable - is there an example somewhere showing how one might provide the arguments to ChangeView in C++/winrt? Thanks.

**Comment by stevewhims** [comment]
Here's how you do that (you can think of IReference as a nullable type):

```cppwinrt
bool flag{ myScrollViewer.ChangeView(Windows::Foundation::IReference<double>{2.f}, nullptr, nullptr) };
flag = myScrollViewer.ChangeView(nullptr, nullptr, Windows::Foundation::IReference<float>{2.f});
```

I'll go ahead and add C++/WinRT versions of the C# code examples for the relevant ScrollViewer members, and I'll do the same with [IReference](https://docs.microsoft.com/uwp/api/windows.foundation.ireference_t_). Thanks for the heads up about the gap in the docs! ~Steve

**Comment by jevansAN** [comment]
I appreciate that fast response! But I get an error: 

“winrt::Windows::Foundation::IReference<T>::IReference(const winrt::Windows::Foundation::IInspectable &value) [with T=float]” (declared at line 2964 of “C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt\winrt\Windows.Foundation.h”)is inaccessible”

This happens whether or not i prepend “winrt” to the qualified name.

Here is the code as written:

viewer.ChangeView(nullptr, nullptr, Windows::Foundation::IReference<double>{newZoomFactor});

The intent is to change the zoom without altering the vertical or horizontal offsets.

The term “inaccessible” is a new one to me in such a context.

Thanks, Jeff

On Jan 10, 2019, at 2:07 PM, Steven White <notifications@github.com> wrote:

Here's how you do that (you can think of IReference as a nullable type):

bool flag{ myScrollViewer.ChangeView(Windows::Foundation::IReference<double>{2.f}, nullptr, nullptr) };
flag = myScrollViewer.ChangeView(nullptr, nullptr, Windows::Foundation::IReference<float>{2.f});

I'll go ahead and add C++/WinRT versions of the C# code examples for the relevant ScrollViewer members, and I'll do the same with IReference. Thanks for the heads up about the gap in the docs! ~Steve

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
[EDITED because my angle brackets were removed because I didn't escape them] Ah, the template parameter type for that third parameter is declared as float. So you want:

```cppwinrt
viewer.ChangeView(nullptr, nullptr, Windows::Foundation::IReference<float>{newZoomFactor});
```

The first two are IReference of double, but the last one is different. That's doc'd in the API ref. There actually is a private conversion constructor for winrt::Windows::Foundation::IReference, and since IReference\<double\> is being passed where IReference\<float\> is expected, the compiler is attempting to call that conversion constructor on the float specialization, but finding it to be private. ~Steve

**Comment by jevansAN** [comment]
And that does it. Thanks again, Steven. It’s great to be able to ask about some of these mysteries.




On Jan 10, 2019, at 2:48 PM, Steven White <notifications@github.com> wrote:

Ah, the template parameter type for that third parameter is declared as float. So you want:

viewer.ChangeView(nullptr, nullptr, Windows::Foundation::IReference<float>{newZoomFactor});
The first two are IReference of double, but the last one is different. That's doc'd in the API ref. There actually is a private conversion constructor for winrt::Windows::Foundation::IReference, and since IReference is being passed where IReference is expected, the compiler is attempting to call that conversion constructor, but finding it to be private. ~Steve

**Comment by stevewhims** [comment]
Cool, you're welcome, Jeff!
