### ISSUE TITLE
Could you please make it possible to distinguish between Inherited properties and new properties? 

### ISSUE THREAD

**Issue by mdmozibur** [MicrosoftDocs/winrt-api#814]
It's messy and hard to find a property amongst so many properties, also, we don't always need to see those inherited properties. It will be great to see properties separated by the interfaces they implement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e994a2-fff3-82f8-2582-791606e71db6
* Version Independent ID: 6e56c4e9-b07e-b3b6-d461-2e7b3ac73c59
* Content: [TreeView Class (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.treeview)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.treeview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by chigy** [comment]
This is tracked by another issue. #606
