### ISSUE TITLE
Minimum Windows Version Should be listed.

### ISSUE THREAD

**Issue by mscherotter** [MicrosoftDocs/winrt-api#815]
The minimum Windows version should be listed in the documentation as this event was introduced in Windows 10 1803

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f824fb69-0ca4-5238-a081-2e2ea1bd1869
* Version Independent ID: 571e2059-feb0-ff13-e797-58b5e4650b9f
* Content: [NavigationView.BackRequested Event (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.backrequested?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Controls.NavigationView.BackRequested)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by benstevens48** [comment]
It should be a priority to show the minimum supported version for events as it's very easy to write code which will crash otherwise and it's not that easy to test on older platforms.

**Comment by jevansaks** [comment]
This was missing from the docs for a long time but is finally back.

**Comment by jevansaks** [comment]
Actually ... it's still not on these events or properties. I don't know why. @IrinVoso ?

**Comment by turbolocust** [comment]
It's at least listed in the version history of the class. But in my opinion this should also be listed here.

**Comment by jwmsft** [comment]
All member pages should now have this information in the _Applies to_ section.
