### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by XeorgeXeorge** [MicrosoftDocs/winrt-api#816]
it is StandardDataFormats.Text
not StandardDataFormats.text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de7ec5f-50fd-b673-f6bb-9b41d1732106
* Version Independent ID: e362c6e4-068b-5a7f-0ac4-de6ae39b5809
* Content: [DataPackageView Class (Windows.ApplicationModel.DataTransfer) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.DataTransfer.DataPackageView)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.datapackageview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.datatransfer.datapackageview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by eliotcowley** [comment]
Hi @moneylow, the snippet is in JavaScript, and in JS the API is actually `text`, so it's correct. Thanks for being vigilant, though!
