### ISSUE TITLE
Valid address range

### ISSUE THREAD

**Issue by dipen-1337lab** [MicrosoftDocs/winrt-api#818]
Namaste Team,

Could you help me understand the valid range of I2C address mentioned above (8 to 119)?

I was able to interface the Grove Multichannel Gas Sensor having Slave address 0x04 and, the I2C communication worked as desired.

Thanks | Regards,
Dipen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5c04901-543d-18bf-f5dc-743d9b9575ed
* Version Independent ID: aa879b9e-5d08-1466-5fb8-f15c526126f3
* Content: [I2cConnectionSettings.SlaveAddress Property (Windows.Devices.I2c) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.devices.i2c.i2cconnectionsettings.slaveaddress)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.i2c.i2cconnectionsettings.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.i2c.i2cconnectionsettings.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by QuinnRadich** [comment]
Sorry for leaving this issue unattended for so long.

You are correct in that the the wording in this documentation is incorrect as to how 7-bit addressing is supported. I've updated it to be more accurate.

Thank you.
