### ISSUE TITLE
Mass field of See Also 'Kind' links isn't helpful

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#819]
All the 'See Also' links are just labelled 'Kind' so it's hard to know what they're linking to.  They should have better descriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce9b7ae-7634-baf1-8b7c-4b59a8452795
* Version Independent ID: 3c4d5a74-71fe-d78b-9c77-e830e449acca
* Content: [ActivationKind Enum (Windows.ApplicationModel.Activation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.activationkind)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.activationkind.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.activationkind.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
You're right, that's not useful. I'll look into fixing this.

**Comment by knicholasa** [comment]
The issue has been logged and hopefully a fix will come soon. Closing the issue for now.
