### ISSUE TITLE
Can there be more than one activation kind?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#820]
Would be helpful to know if this is a flag and can have multiple or not.  Maybe in the remarks here or on the event itself have more info about how to properly handle activation (or a link to the article that talks about it - if there is one).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce9b7ae-7634-baf1-8b7c-4b59a8452795
* Version Independent ID: 3c4d5a74-71fe-d78b-9c77-e830e449acca
* Content: [ActivationKind Enum (Windows.ApplicationModel.Activation) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.activationkind)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.activationkind.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.activation.activationkind.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
I am going to contact you directly and will update this thread with the results of that discussion.

**Comment by knicholasa** [comment]
I am going to update the page based on our offline discussion by clarifying the description and adding a link to a simple overview of Activation. Results should be visible soon.
