### ISSUE TITLE
Link to Control.IsTemplateFocusTarget doesn't work

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#824]
Get 404 page :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b59b36-5478-4b00-90b6-ad697db038b0
* Version Independent ID: 58049b07-eae7-52c1-642b-04eae4f212b1
* Content: [Control.IsTemplateFocusTargetProperty Property (Windows.UI.Xaml.Controls) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.istemplatefocustargetproperty)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.control.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Another instance of attached property mentioning non-attached property that doesn't exist.

**Comment by jwmsft** [comment]
Links to attached properties have been updated.
