### ISSUE TITLE
walidcafe

### ISSUE THREAD

**Issue by WALLOUD** [MicrosoftDocs/winrt-api#825]
*-*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4cb107-8295-b904-c1ca-728848351fe0
* Version Independent ID: 0e8b60c5-e4ae-a743-b5aa-f97b22fb78e0
* Content: [StorageFile Class (Windows.Storage) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefile.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
It looks like some of your feedback didn't make it through. If you have feedback you want to provide, please reopen this issue. Thanks!
