### ISSUE TITLE
Font family names?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#827]
Would be great to reference here a list of standard font family names as included in default WIn10 systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31874255-c39d-ed8e-0e40-35281620e29e
* Version Independent ID: c057c98a-9b09-0e20-237e-5b4f6589dae8
* Content: [FontFamily.Source Property (Windows.UI.Xaml.Media) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.fontfamily.source)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.fontfamily.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.fontfamily.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Here's a list for Windows 10: https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list
