### ISSUE TITLE
Package​Manager.​Update​Package​Async() gives a System.IO.FileLoadException

### ISSUE THREAD

**Issue by endyb66** [MicrosoftDocs/winrt-api#828]
On my OnNavigatedTo-Event, i check if a new version is available and if so, i'm using the Package​Manager.​Update​Package​Async() with the Apppackage and its Dependencies. The update goes well, but then everytime i hit a System.IO.FileLoadException - The file is in use. Please close the file before continuing. I don't know why that happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fe338d2-ea00-96f2-b6b0-3a950cf79e53
* Version Independent ID: ce59f2d0-5664-2cd9-b22b-d73ccbb71153
* Content: [PackageManager.UpdatePackageAsync(Uri, IIterable&lt;Uri&gt;, DeploymentOptions) Method (Windows.Management.Deployment) - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.updatepackageasync#Windows_Management_Deployment_PackageManager_UpdatePackageAsync_Windows_Foundation_Uri_Windows_Foundation_Collections_IIterable_Windows_Foundation_Uri__Windows_Management_Deployment_DeploymentOptions_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hickeys** [comment]
I'm sorry you're having trouble with PackageManager. Unfortunately, GitHub issues are only for feedback on documentation, not technical support. For support, I recommend starting a conversation at [Microsoft Tech Community](https://techcommunity.microsoft.com/).
