### ISSUE TITLE
XINPUT: Does 'Windows.Gaming.Input' supersede XINPUT API

### ISSUE THREAD

**Issue by NeoBeum** [MicrosoftDocs/winrt-api#829]
[Enter feedback here]
Nothing is referenced regarding XInput.
The XInput Rudiments page for API does not mention Windows 10, or Xbox One.
https://docs.microsoft.com/en-us/windows/desktop/api/_xinput/

Please update API documents for both Windows.Gaming.Input and XInput

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c382eaa-aecb-0f26-ab0e-e752c9a36713
* Version Independent ID: 7b0c1235-3109-5b93-33c7-203426d2fad6
* Content: [Windows.Gaming.Input Namespace - UWP app developer](https://docs.microsoft.com/en-us/uwp/api/Windows.Gaming.Input)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.gaming.input.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @NeoBeum. Thanks for filing this issue, and my apologies for the very long delay in responding.

I haven't heard that Windows.Gaming.Input (the Windows Runtime API) supersedes XINPUT (the Win32 API), but if you're writing a Universal Windows Platform (UWP) application, and Windows.Gaming.Input has everything that you need, then I'd recommend using that. One benefit of going that route is that you can use any of the WinRT programming languages. If you're not writing a UWP app, and/or W.G.I doesn't have all that you need, then it'd be appropriate to fall back to XINPUT, in which case you'd be using C++. But typically the factors that I've outlined (the type of app you're writing, and/or the programming language you're most familiar with) would inform which of the WinRT or Win32 APIs to use if more than one serve your needs.

Typically, individual API topics have operating system version requirements listed. I checked a few samples topics in this case, in both API areas, to confirm. If you find that info's missing from an API, then please go ahead and leave feedback on that topic, to that effect.

Thanks!
Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
