### ISSUE TITLE
Windows.Media.SpeechSynthesis.SpeechSynthesizer.SpeechSynthesizer ctor throws

### ISSUE THREAD

**Issue by ohhmm** [MicrosoftDocs/winrt-api#83]
Please, describe cases when the ctor can throw for example FileNotFound exception here
https://github.com/MicrosoftDocs/winrt-api/blob/docs/windows.media.speechsynthesis/speechsynthesizer_speechsynthesizer_1221375020.md
or here https://docs.microsoft.com/en-us/uwp/api/windows.media.speechsynthesis.speechsynthesizer#remarks

**Comment by mattwojo** [comment]
@Karl-Bridge-Microsoft -- Can you help with connecting the correct person on the speech synthesis team to loop in here to see if they can help with addressing this issue?

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for your suggestion! We don't typically document exceptions for UWP constructors. That said, I've passed this issue on to our API documentation v-team for further assessment. They will need to come up with a global recommendation.
