### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by rogino** [MicrosoftDocs/winrt-api#832]
' not the@Windows.UI.Xaml.Controls.SemanticZoom?text=SemanticZoom class.'
Likely just a missing space

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1af0f1-5e90-39ad-0cb1-3dc015880eaf
* Version Independent ID: 30cca0ac-4c05-2566-b3c0-733c0c58762c
* Content: [ListViewBase.ItemClick Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listviewbase.itemclick)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listviewbase.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Link works now, formatting is a little weird.
