### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by MRatnam** [MicrosoftDocs/winrt-api#836]
Documentation containts no samples of how to use

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d20d11e7-4a52-b5b0-22d8-bf03bd79bf95
* Version Independent ID: 50f7ed85-71ce-8516-26e7-afaa54a0a8de
* Content: [XmlDocument.SelectSingleNode(String) Method (Windows.Data.Xml.Dom) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.xml.dom.xmldocument.selectsinglenode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.xml.dom.xmldocument.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.xml.dom.xmldocument.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. For examples that demonstrate how to use the XmlDocument class, see the [XML DOM sample (Windows 10)](http://go.microsoft.com/fwlink/p/?LinkId=620639). In particular, the [Scenario4_GiftDispatch.xaml.cs](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/XmlDocument/cs/Scenario4_GiftDispatch.xaml.cs) code file demonstrates the SelectSingleNode method. I have added a remark about this sample to the article, and this change should go live in the docs in the next day or so.
