### ISSUE TITLE
GetFilesAsync(CommonFileQuery) func return unexpected files 

### ISSUE THREAD

**Issue by AceLearnGit** [MicrosoftDocs/winrt-api#837]
var folder = KnownFolders.PicturesLibrary;
var picturesLibraryFiles = await folder.GetFilesAsync(Windows.Storage.Search.CommonFileQuery.OrderByDate);

some files in D:// also  saw in picturesLibraryFiles 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f9dd15ed-b41c-a906-6768-3b818dca73b6
* Version Independent ID: f04d7b02-e96b-419f-e2a6-897bedae311e
* Content: [StorageFolder.GetFilesAsync Method (Windows.Storage) - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.storage.storagefolder.getfilesasync#Windows_Storage_StorageFolder_GetFilesAsync_Windows_Storage_Search_CommonFileQuery_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.storagefolder.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. Is it possible that D:// has been added to the Pictures library on the computer where you are seeing this? If so, this is expected behavior.

Unfortunately, this docs repo is not a support channel. If you don't have any further feedback specifically on the documentation, please see [this page](https://developer.microsoft.com/en-us/windows/support) for your support options.

**Comment by AceLearnGit** [comment]
I have not add D:// to Pictures library, but i noticed that it's possible Photos App make this.
Here are my steps:
1. open Photos App
2. Setting - Sources- Add a folder
if add D:// to Sources of Photos App, I will get files in D:// by  Code:

var folder = KnownFolders.PicturesLibrary;
var picturesLibraryFiles = await folder.GetFilesAsync(Windows.Storage.Search.CommonFileQuery.OrderByDate);

Does steps above means add D:// to Pictures Library? I don't think it's a good idea that a uwp App can effect the result of API

**Comment by AceLearnGit** [comment]
> Thanks for reporting this issue. Is it possible that D:// has been added to the Pictures library on the computer where you are seeing this? If so, this is expected behavior.
> 
> Unfortunately, this docs repo is not a support channel. If you don't have any further feedback specifically on the documentation, please see [this page](https://developer.microsoft.com/en-us/windows/support) for your support options.

I have not add D:// to Pictures library, but i noticed that it's possible Photos App make this.
Here are my steps:

open Photos App
Setting - Sources- Add a folder
if add D:// to Sources of Photos App, I will get files in D:// by Code:
var folder = KnownFolders.PicturesLibrary;
var picturesLibraryFiles = await folder.GetFilesAsync(Windows.Storage.Search.CommonFileQuery.OrderByDate);

Does steps above means add D:// to Pictures Library? I don't think it's a good idea that a uwp App can effect the result of API
