### ISSUE TITLE
IOutputStream::FlushAsync return value

### ISSUE THREAD

**Issue by krzys-h** [MicrosoftDocs/winrt-api#841]
This function returns an async task that returns a bool - but the meaning of the returned bool value doesn't seem to be documented

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 92bf5a70-6962-f6a6-ecfc-3ad2123573cc
* Version Independent ID: 122e3975-8d37-d648-f989-351243d3b420
* Content: [IOutputStream.FlushAsync Method (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/pl-pl/uwp/api/windows.storage.streams.ioutputstream.flushasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.ioutputstream.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.ioutputstream.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by stevewhims** [comment]
Reassigning as per ownership info from previous assignee.  My 2c: what’s being returned isn’t “The stream flush operation”, but rather (wording something like) “An asynchronous operation object which, on completion, contains a Boolean value that indicates [what?]”. The product team PM/dev will be able to fill in that blank. Also, while you're working in the topic, MVP feedback is that the part “It's generally recommended to avoid this method if possible” should explain *when* it’s possible, and what else to use when it is.

**Comment by GrantMeStrength** [comment]
Another option: 

https://stackoverflow.com/questions/14096704/what-is-the-meaning-of-ioutputstream-flushasyncs-return-value

But I am currently trying to track down the PM that owns this for a definitive answer.

**Comment by GrantMeStrength** [comment]
This asynchronous operation, when awaited, returns a boolean value indicating whether the flush operation succeeded
