### ISSUE TITLE
I Need to know how we can run a GattService in a background task 

### ISSUE THREAD

**Issue by AlexTrepanier** [MicrosoftDocs/winrt-api#842]
I need to know how we can run a GattService with caracteristics and read and write request events in a background task

how exactly can the client trigger the bluetooth gattserviceprovidertrigger?  
Should we create the characterics before registring the gattserviceprovidertrigger or when the gattserviceprovidertrigger is run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a6be801-d431-6046-6444-bd23b7feb593
* Version Independent ID: 996d371c-a133-2c21-c571-38747c8506cb
* Content: [Windows.ApplicationModel.Background Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.background.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **misatranjr**
* Microsoft Alias: **misatran**

**Comment by MatchaMatch** [comment]
Thanks for taking the time to submit an issue. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers) offer timely answers to questions like this.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed, please treat this thread as an open thread for follow-ups. Thanks!
