### ISSUE TITLE
UIElement.OpacityTransition Property supported minimal value 0.002?

### ISSUE THREAD

**Issue by Weissu** [MicrosoftDocs/winrt-api#844]
Is this some kind of bug but I cannot create Opacity Transition from value x to 0? Minimal supported (working) value looks to be 0.002. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 997fcadb-7cdc-533b-d74c-fed838c8800d
* Version Independent ID: cd08fe3c-514c-5dc4-0432-d2ba6ca722ec
* Content: [UIElement.OpacityTransition Property (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.opacitytransition)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by stmoy** [comment]
Thank you for reporting this issue @Weissu! This is a known issue in the platform related to an optimization that the framework makes for elements that have a 0 opacity. In the meantime, animating to a very small non-zero number is the best way to work around this issue until we have a fix in the platform.

**Comment by chigy** [comment]
Closing the issue as resolved. @Weissu, please let us know otherwise.

**Comment by stmoy** [comment]
Quickly following up on this: we've fixed the bug in the platform. The fix will be found in the next version of Windows 10 (May 2019 Update). If your app targets previous versions of Windows 10, you'll still need to animate to a small non-zero number; however, in the latest version of Win10, you can animate directly to 0. 

Thank you again for reporting this issue!
