### ISSUE TITLE
There is no documentation of the various `requestKind` values and what they do

### ISSUE THREAD

**Issue by ZodmanPerth** [MicrosoftDocs/winrt-api#848]
Apart from a few smatterings of values in (blog) posts that aren't code documentation, there is no indication of what values to use for the `requestKind` parameter on `SendRequestAsync`.  It would be very helpful for people investigating how to use this service if the values and a description of the service were listed on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aff33a0f-f3ea-ddd0-ac9b-f43628db244d
* Version Independent ID: cd62bb9e-0998-778a-bf4c-d646f6a1a090
* Content: [StoreRequestHelper.SendRequestAsync(StoreContext, UInt32, String) Method (Windows.Services.Store) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storerequesthelper.sendrequestasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storerequesthelper.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.services.store.storerequesthelper.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Xansky**
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi ZodmanPerth,

Current valid values for requestKind are documented on the [Send requests to the Microsoft Store](https://docs.microsoft.com/windows/uwp/monetize/send-requests-to-the-store) page.

Thanks,
 ~ _Mark_
