### ISSUE TITLE
Enhancement Request : Put links to the control template of each control in all documented controls

### ISSUE THREAD

**Issue by the-jedi-code** [MicrosoftDocs/winrt-api#852]
Example: 
the link to the control template documentation is here.
https://msdn.microsoft.com/en-us/library/windows/apps/mt185407.aspx 

I want to style the control so I need to start with a copy of it's default control template then add it to a resource dictionary and then style it. I'd like to see a link at the top of the documentation page that I can click to find the control template for every control so that I can copy and paste it's control template. It's much harder to find control template when googling. Why not provide developers a quick link to that resource. Even in this documentation there is a section talking about styles and control template customization and it doesn't even provide a link to this controls template 
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.passwordbox#control-style-and-template

What is also really annoying is that when you find the control template documentation it conveniently provides you the link you to this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b4e589f-50cf-8205-d939-6a27d73cd1eb
* Version Independent ID: 37b49d79-b385-f617-66fc-539229e217e6
* Content: [PasswordBox Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.passwordbox)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.passwordbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.passwordbox.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Templates change much more frequently than the APIs so this would be hard to maintain. Good news is that most of the styles are now open-source so you can find and search them in our github. https://github.com/Microsoft/microsoft-ui-xaml.
