### ISSUE TITLE
TimePicker shows event SelectedTimeChanged via docs but that event is not available.

### ISSUE THREAD

**Issue by MichaelPuckett2** [MicrosoftDocs/winrt-api#853]
```Windows.UI.Xaml.Controls.TimePicker``` control shows event ```SelectedTimeChanged``` via docs but that event is not available.

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.timepicker.selectedtimechanged

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6465d9e9-19dc-833f-7e4a-51259e724ae2
* Version Independent ID: cf490fd4-5a71-55ab-4c40-2f2ffd64e3ba
* Content: [TimePicker.SelectedTimeChanged Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.timepicker.selectedtimechanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.timepicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.timepicker.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
@MichaelPuckett2, the SelectedTimeChanged event is new in Windows 10, version 1809 ([SDK 17763](https://developer.microsoft.com/windows/downloads/windows-10-sdk)). Your project needs to target this version to use this event. 

This should be shown on the event's doc page, but a bug in the doc generation system is preventing that right now. A fix is being worked on.

**Comment by MichaelPuckett2** [comment]
@jwmsft Thanks Jim.  I have replied to a comment on SO about this and pointed / quoted your response.  However; I quickly tried to target 1809 and try this and couldn't in VS2017.  I could in VS2019 Preview but then it wouldn't compile.  This could be a number of reasons that I haven't taken the time to work out so just FYI ATM.
https://stackoverflow.com/questions/54154077/uwp-timepicker-selectedtimechanged-doesnt-exist
