### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#854]
I hope MS people reading this won't tire of my frequent questions of this type, but I would love to see an example of how one might in C++/winrt create a handler for ViewChanged. ViewChanged is not a class member of ScrollViewer and it doesn't appear this is done with a lambda like click handlers - just a couple of lines would do the trick!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd470e1-38ac-a76f-883c-6096a6dcc128
* Version Independent ID: 23494efd-9886-a0c8-a132-18db50245536
* Content: [ScrollViewer.ViewChanged Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer.viewchanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.scrollviewer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.scrollviewer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansAN** [comment]
Let me append to that question: On stackoverflow I found an example in which the author added an event handler to a scrollviewer, and it was accomplished in C# by scrollviewer.ViewChanged += ViewChangedHandler. But in C++/winrt, ViewChanged is not a member of scrollviewer. What I would like to see is an example of how one would define and register an event handler like this in C++/winrt.  Thanks.

**Comment by jevansAN** [comment]
And now I think I can answer my question: it appears this can be done with a lambda as follows, where m_scroll_viewer is a reference to the UIElement. This is declared in the constructor for the class that contains the scrollviewer:

m_scroll_viewer.ViewChanged([=](winrt::Windows::Foundation::IInspectable const& sender, winrt::Windows::UI::Xaml::Controls::ScrollViewerViewChangedEventArgs const& e)
			{
			HandleViewChange(e);
			});

**Comment by jevansaks** [comment]
Yes, that's the recommended approach.
