### ISSUE TITLE
"UX guidelines for layout and scaling" link doesn't work

### ISSUE THREAD

**Issue by Dimitrias** [MicrosoftDocs/winrt-api#855]
The last link just goes to the main fluent design page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7d0526-465a-4425-4c70-b9df627863b8
* Version Independent ID: b995affa-afbe-0775-f9cb-04f2a0f97622
* Content: [BitmapImage.DecodePixelType Property (Windows.UI.Xaml.Media.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapimage.decodepixeltype#Windows_UI_Xaml_Media_Imaging_BitmapImage_DecodePixelType)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.bitmapimage.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.bitmapimage.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
This link has been updated. Thanks.
