### ISSUE TITLE
Any equivalence for Windows.Graphics.Capture?

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/winrt-api#856]
Windows.Graphics.Capture seem similar in concept, but the source is virtual instead of hardware like webcam, CAMERA, etc.
It is possible to use this to render Screen Capture Stream?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb54ac5-27ea-249a-6134-871a3c8708c9
* Version Independent ID: f6438e11-b101-cd7b-03f4-842534eb0205
* Content: [CaptureElement Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.captureelement)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.captureelement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.captureelement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@jesbis can you answer this?

**Comment by jesbis** [comment]
There's more info and examples for screen capture available here: [Screen capture](https://docs.microsoft.com/windows/uwp/audio-video-camera/screen-capture).

One option is to capture content from the screen using `GraphicsCapturePicker` and get `Direct3D11CaptureFrame` frames from it, which can then be rendered to a DirectX surface (e.g. using Win2D as shown in the link above), or to a video stream using `MediaStreamSource` and [`MediaStreamSample.CreateFromDirect3D11Surface`](https://docs.microsoft.com/uwp/api/windows.media.core.mediastreamsample.createfromdirect3d11surface) which could then be rendered using a [`MediaPlayerElement`](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.MediaPlayerElement).

The comments in this issue may help: https://github.com/MicrosoftDocs/windows-uwp/issues/612

Other options are:

1. If you just need an easy way to record your own app window to a video for a desktop app, you can use the functionality from [Windows.Media.AppRecording](https://docs.microsoft.com/uwp/api/windows.media.apprecording)

2. If you just need a simple way to get snapshots of UI content from your own app and render them then you can use the [RenderTargetBitmap](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Media.Imaging.RenderTargetBitmap) class, or Windows.UI.Composition.VisualSurface (VisualSurface is new in the Windows 10 May 2019 Update).
