### ISSUE TITLE
Why does this return IList<object>?

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/winrt-api#857]
I guess my real question is why are there no c# bindings for this library?  If Xamarin can generate C# binding for objective-c why can't UWP have c# bindings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0198b8-df12-08f5-45a3-3e0f7220dbe1
* Version Independent ID: e9016425-80f2-c00c-9d1e-f9572f9b018b
* Content: [NavigationView.MenuItems Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.menuitems#Windows_UI_Xaml_Controls_NavigationView_MenuItems)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
What do you mean by C# bindings?  At the WinRT level it returns an IVector<IInspectable>, which projects to C# as IList<object>.  Or is the question: why doesn't this return IList<MenuItem>?

**Comment by jevansaks** [comment]
Or is the issue that NavigationView isn't easily bindable? If you want to bind to a datasource you should use the MenuItemsSource property.
