### ISSUE TITLE
string size limited

### ISSUE THREAD

**Issue by daoluong** [MicrosoftDocs/winrt-api#860]
input text limited to 100 characters in total. and there was no warning about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0161bfef-0bde-a788-3a85-6c4e020cef20
* Version Independent ID: 5d2bd606-d371-9300-70da-5ac81c6aa4c9
* Content: [JapanesePhoneticAnalyzer.GetWords Method (Windows.Globalization) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.japanesephoneticanalyzer.getwords#Windows_Globalization_JapanesePhoneticAnalyzer_GetWords_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.japanesephoneticanalyzer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.japanesephoneticanalyzer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@daoluong - Thanks for the feedback. You are correct, there is an internal limitation of 100 characters for the input string. I've updated the relevant ref topics with this detail and submitted a PR to update the Windows universal sample with a new comment.
