### ISSUE TITLE
Why there is no ReadLine() method implemented like in the StreamReader class?

### ISSUE THREAD

**Issue by gmgallo** [MicrosoftDocs/winrt-api#861]
The lack of this method lends to a lengthy and inefficient code to parse text files one line at a time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61bf27d-d169-da09-5c90-25a4448488a4
* Version Independent ID: ccc5fdef-a25a-6eba-5a91-64d1eae4484c
* Content: [DataReader Class (Windows.Storage.Streams) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datareader)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.streams.datareader.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to submit your feedback and I sincerely apologize for the delayed response. Although this GitHub repo is specifically for reporting documentation bugs, I have passed your feedback on to the Windows product team. If you have further technical questions about this API, please see the community of experts and Microsoft engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).
