### ISSUE TITLE
Missing generic types in remarks and incorrect class specified?

### ISSUE THREAD

**Issue by rawlinson** [MicrosoftDocs/winrt-api#862]
Within the remarks sections in states that:
"The ItemsControl can provide better performance if the ItemsSource property value also implements a random-access list interface: ... In C#, this means IList, IReadOnlyCollection, or IList."
Presumably, this should be "IList&lt;T&gt;, IReadOnlyList&lt;T&gt;, or IList."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21122397-9785-9288-f57c-521109978c38
* Version Independent ID: cce4bb61-d808-e6c1-0f0f-4ed36ec30b34
* Content: [ItemsControl.ItemsSource Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemscontrol.itemssource#Windows_UI_Xaml_Controls_ItemsControl_ItemsSource)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemscontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.itemscontrol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
I'm guessing the markdown renderer ate the <T> part. I see it in the .md file. Will fix.
