### ISSUE TITLE
What are the bounds of DateTime?

### ISSUE THREAD

**Issue by antmor** [MicrosoftDocs/winrt-api#867]
Is there any guidance to what the largest "DateTime" could be? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd5e8342-d0f1-2e2f-6458-e1cd8f09d901
* Version Independent ID: 15c7ce82-4791-4529-d657-24ebfec741b7
* Content: [DateTimeFormatter.Format Method (Windows.Globalization.DateTimeFormatting) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.datetimeformatting.datetimeformatter.format#Windows_Globalization_DateTimeFormatting_DateTimeFormatter_Format_Windows_Foundation_DateTime_System_String_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.datetimeformatting.datetimeformatter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.datetimeformatting.datetimeformatter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @antmor. I've added a link to the parameter type topic to both this topic and a number of related topics.
