### ISSUE TITLE
Poulating the MapElements list after layer creation

### ISSUE THREAD

**Issue by gmgallo** [MicrosoftDocs/winrt-api#868]
If you plan to add more elements to the MapElements property after it is attached to the layer use:
 IList&lt;MapElement&gt; mapElements = new  ObservableCollection&lt;MapElement&gt;();
instead of:
new List&lt;MapElements&gt;();
like all the examples show. Otherwise the new elements won't be displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf1364d-ebfc-d0df-881f-b98e5ae1a1c0
* Version Independent ID: fd32442f-502b-d2a3-80e6-086d7c65bf5b
* Content: [MapElementsLayer.MapElements Property (Windows.UI.Xaml.Controls.Maps) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.maps.mapelementslayer.mapelements)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapelementslayer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapelementslayer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
This is true, however this is not the place for that specific piece of documentation. There are many places where IList<> is used, and mentioning the difference between List<> and ObservableCollection<> in all of these places is not feasible and distracts from the point of the API documentation, which is to provide a simple, technical explanation of the APIs. Understanding the behaviors of the various types of collections available in UWP is more appropriately done elsewhere, such as the articles regarding ObservableCollection<>, which already provides this information.
