### ISSUE TITLE
Show Derived classes in UWP documentation

### ISSUE THREAD

**Issue by opcodewriter** [MicrosoftDocs/winrt-api#870]
When looking at a class from UWP, can we please have the UWP docuemntation show the derived classes ?
The WPF documentation shows it, but not the UWP documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f6e0bc-a81e-013e-847b-8eb197a31f60
* Version Independent ID: 0b91329e-cd29-2ee5-c6a0-d6ddcb06a738
* Content: [Block Class (Windows.UI.Xaml.Documents) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.documents.block)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.documents.block.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.documents.block.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by mijacobs** [comment]
Thank you for the feedback. We have a request to engineering for this feature.
