### ISSUE TITLE
1803 or earlier, some of the enums fail.

### ISSUE THREAD

**Issue by mobiletonster** [MicrosoftDocs/winrt-api#872]
Please specify which contract version applies to the new enums.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a9d93e-4772-fa99-6482-fea4087fe214
* Version Independent ID: 4e33b460-8e6e-e5a6-9dca-785159590917
* Content: [FlyoutPlacementMode Enum (Windows.UI.Xaml.Controls.Primitives) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutplacementmode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutplacementmode.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.primitives.flyoutplacementmode.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@mijacobs @mimisasouvanh This is an issue with the doc system. We have the version info in the metadata but it's not being displayed in the docs.

**Comment by mijacobs** [comment]
We have a bug filed against engineering for this issue.
