### ISSUE TITLE
Please add units

### ISSUE THREAD

**Issue by blujel** [MicrosoftDocs/winrt-api#873]
There are no units associated with the memory usage level. Is the memory usage in bits, bytes, kbytes? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6c4c342-e96e-c1b8-4a4d-07b8969ba626
* Version Independent ID: 218d94e2-d97a-a285-61b3-4ff7f269d1f9
* Content: [MemoryManager.AppMemoryUsageLevel Property (Windows.System) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.memorymanager.appmemoryusagelevel)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.memorymanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.memorymanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I've added units where they were missing. Changes should show up shortly.
