### ISSUE TITLE
How to release memory of mapcontrol?

### ISSUE THREAD

**Issue by AceLearnGit** [MicrosoftDocs/winrt-api#875]
I use mapctrl in one of page in my uwp app,the map ctrl will use lots of memory while  using it,but when i navigate back or go to other pages, the app still keep high memory,unless i close or minimize my app, so how to release the mapcontrol when i don't use it?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a2e00175-951b-ebab-ec6f-f870f2ed4525
* Version Independent ID: e402b470-bb92-c372-fc2c-da83780d9ab9
* Content: [MapControl Class (Windows.UI.Xaml.Controls.Maps) - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.ui.xaml.controls.maps.mapcontrol?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(Windows.UI.Xaml.Controls.Maps.MapControl)%3Bk(VS.XamlEditor)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%26rd%3Dtrue#methods)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapcontrol.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapcontrol.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our forums or StackOverflow. For other support options, check out the developer support page. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.

Thanks,
Shawn
