### ISSUE TITLE
Javascript Example

### ISSUE THREAD

**Issue by driesvandamme** [MicrosoftDocs/winrt-api#876]
Could someone give a javascript example on how to call this? My app seems to get stuck when running the above example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb69cc83-27fc-5cf4-fe69-98ab75c4d061
* Version Independent ID: 62dbf413-5f27-f370-b024-f4aa014109a5
* Content: [Package.CheckUpdateAvailabilityAsync Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.checkupdateavailabilityasync#Windows_ApplicationModel_Package_CheckUpdateAvailabilityAsync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by driesvandamme** [comment]
0x80040155 - JavaScript runtime error: Interface not registered

Failed to find proxy registration for IID: {4020C034-C762-5152-BEEF-F03471E885B9}.
WinRT information: Failed to find proxy registration for IID: {4020C034-C762-5152-BEEF-F03471E885B9}.

**Comment by knicholasa** [comment]
Unfortunately it turns out that calling checkUpdateAvailabilityAsync() is not yet supported from JavaScript. Thanks for bringing this to my attention. I'll update the page to reflect it. In the mean time, if you'd like help with development issues, please check out the developer support pages: https://developer.microsoft.com/en-us/windows/support

**Comment by mcleanbyron** [comment]
We have added remarks to this article about the current lack of JavaScript support and a link to a workaround.
