### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by Robelind** [MicrosoftDocs/winrt-api#877]
Why on earth is this property not bindable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5d8195-7873-655b-2dbf-640ef32a75d9
* Version Independent ID: 10543dd3-f885-8183-3529-2a455e7e8e50
* Content: [ListBox.SelectedItems Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.listbox.selecteditems)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.listbox.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
This is a feature request. We're asking folks to file feature requests for XAML on https://github.com/Microsoft/microsoft-ui-xaml. Thanks!
