### ISSUE TITLE
Information regarding what build this API was implemented on is missing

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#879]
It is important that ALL API's report what contract it requires so that code is properly protected. this missing caused a crash in our app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01c49aba-1cfd-7f99-70dd-a56f9d3c6c16
* Version Independent ID: 660b8e43-4b97-451a-1f41-49f8645bb015
* Content: [FocusManager.LosingFocus Event (Windows.UI.Xaml.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.focusmanager.losingfocus?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Input.FocusManager.LosingFocus)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.focusmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.focusmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @JuanMejiaVelez. This is a known issue (requirements details missing on member pages) and is being addressed by our engineering team. This should be fixed in the near future.
