### ISSUE TITLE
IMemoryBufferReference.Closed needs to clarify when the event fires

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/winrt-api#880]
Based on my understanding of the design (from an internal email thread) this event fires before the buffer resource has been freed and provides the handler the opportunity to cleanup. so something like "before the resource is freed"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d29c961b-bd2f-a026-533d-a07cd98c28bc
* Version Independent ID: 8495e39c-34f1-0ae8-29eb-c596e8b56f97
* Content: [IMemoryBufferReference.Closed Event (Windows.Foundation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.imemorybufferreference.closed)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.imemorybufferreference.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.foundation.imemorybufferreference.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by smk2007** [comment]
The documentation suggests that the Closed() event “Occurs when MemoryBuffer.Close has been called and this IMemoryBufferReference has been closed.” However, based on the behavior of the MemoryBufferReference and internal discussion, this is fired when Close() is called on the MemoryBufferReference and offers event-handlers one last chance to access the memory before it becomes inaccessible. There is no dependence on the source MemoryBuffer and its closed state.

**Comment by hickeys** [comment]
Thanks. I've reviewed the internal email thread and updated the documentation accordingly. It should show up on docs.microsoft.com shortly.
