### ISSUE TITLE
NavigationView: Settings button reposition itself with some delay

### ISSUE THREAD

**Issue by fede9876** [MicrosoftDocs/winrt-api#881]
When resizing the height of the NavigationView, the Settings button reposition itself to the correct position with some delay.
The problem is very noticeable when positioning a PaneFooter element near the Settings button because the PaneFooter doesn't have this problem, so for a short time they overlap with each others.

Step to reproduce the problem:

- Windows 10 October update (Build 17763)
- create an empty project with Min version and Target version = "Windows 10, version 1809 (Build 17763)"
- add this code between `Grid` tags in MainPane.xaml

```
<NavigationView IsSettingsVisible="True">
    <NavigationView.PaneFooter>
        <NavigationViewItem Content="My Pane Footer"/>
    </NavigationView.PaneFooter>
</NavigationView>
```

Here's a preview of the problem (the entity of the delay may vary between different devices).
![bug](https://user-images.githubusercontent.com/46969041/51625874-992ff080-1f3e-11e9-9f2a-2d64f77e96d8.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4dc6f7-f3bd-16b7-7dbc-56727af3fb97
* Version Independent ID: 89dadeaf-9bba-a58a-24cb-f731de2b7265
* Content: [NavigationView Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationview.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Good bug. Thanks for the gif, that really helped explain it. We are asking for bugs to be filed on https://github.com/Microsoft/microsoft-ui-xaml. I can move this issue over for you.
