### ISSUE TITLE
how

### ISSUE THREAD

**Issue by vafa68** [MicrosoftDocs/winrt-api#884]
soso

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda936b8-a85b-a6b1-b3b6-d2d845e31ffe
* Version Independent ID: 0d5dc733-9377-8a09-ae60-a922db2d8627
* Content: [WebAuthenticationOptions Enum (Windows.Security.Authentication.Web) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.webauthenticationoptions)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.webauthenticationoptions.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.authentication.web.webauthenticationoptions.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **misatranjr**
* Microsoft Alias: **misatran**

**Comment by ginami** [comment]
Hi @vafa68 -- please let us know if you have specific feedback on our docs. Thanks!
