### ISSUE TITLE
call from 32-bit app to those code, always get 0   

### ISSUE THREAD

**Issue by cai6jing** [MicrosoftDocs/winrt-api#885]
[Enter feedback here]
when call those code from 64-bit app,  list. get () can return valid value, but if call from 32-bit app  always get 0   

IAsyncOperation<IVectorView<Radio>> list = Radio::GetRadiosAsync();
IVectorView<Radio> radios = list.get();
int32_t nRadioNum = radios.Size();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f21cd4-880d-b4d3-19ce-3214bd577861
* Version Independent ID: f29e26e0-5a3f-5fc7-e5a8-87d11465c50d
* Content: [Radio.GetRadiosAsync Method (Windows.Devices.Radios) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.radios.radio.getradiosasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.radios.radio.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @cai6jing. Thanks for filing this issue, and my apologies for the very long delay in responding.

You're right that this API is subject to architecture requirements. There are more details in the [Remarks](https://docs.microsoft.com/uwp/api/windows.devices.radios.radio.getradiosasync#remarks) section.

Thanks!
Steve

**Comment by jiangxincode** [comment]
Hi, @stevewhims , I also hunt for a alternative method to get the radio device using a 32-compiled program on 64 os system.

**Comment by stevewhims** [comment]
@jiangxincode, please see the info in https://github.com/MicrosoftDocs/winrt-api/issues/338, which is closed, but it describes how customers can pursue seeking product support. This particular case isn't something that I can resolve by updating the documentation, so I'd encourage customers to seek product support.

Thanks!
Steve
