### ISSUE TITLE
PackageUpdateAvailability enum

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/winrt-api#886]
When targeting 1809, PackageUpdateAvailabilityResult doesn't contain any PackageUpdateAvailabilityResult method.
result.PackageUpdateAvailability will return build error complaining about it. 

It should be result.Availability instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb69cc83-27fc-5cf4-fe69-98ab75c4d061
* Version Independent ID: 62dbf413-5f27-f370-b024-f4aa014109a5
* Content: [Package.CheckUpdateAvailabilityAsync Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.checkupdateavailabilityasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by mcleanbyron** [comment]
Thanks for catching this issue. I have fixed the code examples in the article and the fixes should be published to the live docs site in the next day or two.

**Comment by driesvandamme** [comment]
Could you maybe do it in the other samples as well? @mcleanbyron

https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageupdateavailabilityresult

**Comment by mcleanbyron** [comment]
Thanks for catching the additional affected samples! I just checked in fixes for the examples in [PackageUpdateAvailabilityResult](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageupdateavailabilityresult) and [PackageUpdateAvailability](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.packageupdateavailability). These fixes should go live in the next day or two.
