### ISSUE TITLE
Need hardware list in order to test some of these samples

### ISSUE THREAD

**Issue by dtobias** [MicrosoftDocs/winrt-api#889]
Hi, 
For any samples that are looking for specific hardware I think you should have a required hardware list.  In this case, what barometer do I need to hook up.  Is it I2C?  SPI?  Is it available as USB??  These are required to know if we want to test your samples!  Thanks for the opportunity to provide feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7891c60b-f384-77ef-85ba-5d02e5599c60
* Version Independent ID: 091ef31b-1048-73fa-a1ab-795ae1610872
* Content: [Barometer Class (Windows.Devices.Sensors) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.barometer)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.sensors.barometer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.sensors.barometer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, @dtobias. As this isn't actionable feedback for the API documentation, I suggest you log an issue against the sample at https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Barometer.
