### ISSUE TITLE
Sample code missing xmlns=

### ISSUE THREAD

**Issue by peteams** [MicrosoftDocs/winrt-api#896]
I believe the first line of the sample misses the first part of the xmlns definition mentioned in the third bullet point. That is the line that reads

string xaml =
"&lt;Ellipse Name=\"EllipseAdded\" Width=\"300.5\" Height=\"200\" 
Fill=\"Red\" \"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"/&gt;";

should actually read

string xaml =
"&lt;Ellipse Name=\"EllipseAdded\" Width=\"300.5\" Height=\"200\" 
Fill=\"Red\" xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"/&gt;";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe705b66-ab93-9b90-1799-f95d1d6c0448
* Version Independent ID: f0c09a66-b141-3792-af6c-802f09313db8
* Content: [XamlReader.Load(String) Method (Windows.UI.Xaml.Markup) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.markup.xamlreader.load?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Markup.XamlReader.Load)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.markup.xamlreader.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.markup.xamlreader.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Thanks for reporting, we'll fix this!

**Comment by jevansaks** [comment]
Fixed, should be live in a couple days.
