### ISSUE TITLE
Reference broken

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/winrt-api#898]
The reference to AsRandomAccessStream broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eef8d8f8-37d6-391d-3c67-9fbcf9cfd8ca
* Version Independent ID: d2b48dc4-4f60-a8e5-847d-311485809301
* Content: [BitmapSource.SetSourceAsync(IRandomAccessStream) Method (Windows.UI.Xaml.Media.Imaging) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapsource.setsourceasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Windows.UI.Xaml.Media.Imaging.BitmapSource.SetSourceAsync)%3Bk(TargetFrameworkMoniker-.NETCore%2CVersion%3Dv5.0)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.bitmapsource.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.media.imaging.bitmapsource.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
The link seems to be working now, can you try again?
