### ISSUE TITLE
Unable to find the dependent Assembly

### ISSUE THREAD

**Issue by amitvineti** [MicrosoftDocs/winrt-api#899]
How do I download Windows.Security.Cryptography.Core.dll, Windows.dll? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99f953c-7c3d-1f6e-e994-e3fda8ce9856
* Version Independent ID: dc111fd6-12b4-56d5-c759-7fe90be52e67
* Content: [Windows.Security.Cryptography.Core Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.core#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.core.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **msatranjr**
* Microsoft Alias: **misatran**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
