### ISSUE TITLE
JavaScript supportability

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/winrt-api#902]
Although we have a JavaScript snippet sample for this method, our Product group confirmed that checkUpdateAvailabilityAsync() is not yet supported as being called from JavaScript.

Can we remove this part from our samples? At this point only C# & C++/WinRT calls are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb69cc83-27fc-5cf4-fe69-98ab75c4d061
* Version Independent ID: 62dbf413-5f27-f370-b024-f4aa014109a5
* Content: [Package.CheckUpdateAvailabilityAsync Method (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.checkupdateavailabilityasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Sounds good. I'll update the page.

**Comment by knicholasa** [comment]
@cheles Actually, if your API does not support Javascript you should add the WebHostHidden attribute to the source code and the example will be omitted here.  Anything that supports C# should also support VB and the other .NET languages, but if you do need to remove the C++/WinRT and VB examples as well and I will follow up.

**Comment by mcleanbyron** [comment]
We have added remarks to this article about the current lack of JavaScript support and a link to a workaround.
