### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by moshegutman** [MicrosoftDocs/winrt-api#905]
I tested this with an SVG image and it works too. The documentation should be updated to include support for SVG images.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2533bb3b-0009-9747-c89f-4cfc90472c7c
* Version Independent ID: cc2ba119-f61c-b99d-da2b-d9487aa665e6
* Content: [MapIcon.Image Property (Windows.UI.Xaml.Controls.Maps) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.maps.mapicon.image)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapicon.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.maps.mapicon.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by QuinnRadich** [comment]
Thanks for your patience on this issue. I've added a note to the documentation detailing this support, which will go live shortly.
