### ISSUE TITLE
Incorrect assembly information for ClosedCaptionProperties

### ISSUE THREAD

**Issue by rahulsingh11** [MicrosoftDocs/winrt-api#906]
The correct assembly for this class is Windows.Media.dll and not Windows.Media.ClosedCaptioning.dll as mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 892c130c-f2d2-18aa-20b2-0a75e591a2bf
* Version Independent ID: 24be0079-0ca3-312a-f28c-ebe0ebb97758
* Content: [ClosedCaptionProperties Class (Windows.Media.ClosedCaptioning) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.ClosedCaptioning.ClosedCaptionProperties)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.closedcaptioning.closedcaptionproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.closedcaptioning.closedcaptionproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by FactoryXCode** [comment]
That's correct. There is no such Windows.Media.ClosedCaptioning.dll. Not in the 32 or 64 bit version of (1903 build 18362.267) Windows 10 may 2019.

**Comment by drewbatgit** [comment]
We are no longer listing assembly information in API reference pages.
