### ISSUE TITLE
Example code request for C++/winrt

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#907]
Could we see an example in C++/winrt of initializing an instance of HttpFormUrlEncodedContent with key-value pairs? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93344730-8243-faa4-4025-7724b874f3ae
* Version Independent ID: 791bf82f-73da-f094-5deb-efa1aef7f62f
* Content: [HttpFormUrlEncodedContent(IIterable&lt;IKeyValuePair&lt;String, String&gt;&gt;) Constructor (Windows.Web.Http) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.httpformurlencodedcontent.-ctor#Windows_Web_Http_HttpFormUrlEncodedContent__ctor_Windows_Foundation_Collections_IIterable_Windows_Foundation_Collections_IKeyValuePair_System_String_System_String___)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpformurlencodedcontent.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.web.http.httpformurlencodedcontent.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @jevansAN, the topic should be updated shortly with a code example. Meanwhile, here's the code I added to the topic, I hope it helps.

```cppwinrt
auto contentKeyValuePairs{
winrt::single_threaded_map<winrt::hstring, winrt::hstring>(std::map<winrt::hstring, winrt::hstring>{
    { L"firstname", L"Jane" }, { L"lastname", L"Austen" }
})
};
Windows::Web::Http::HttpFormUrlEncodedContent content1{ contentKeyValuePairs };

Windows::Web::Http::HttpFormUrlEncodedContent content2{
    std::map<winrt::hstring, winrt::hstring>{
        { L"firstname", L"Jane" }, { L"lastname", L"Austen" }}
};
```

~Steve

**Comment by jevansAN** [comment]
Great! That is exactly the sort of thing that I think will help me and others.

Jeff


On Feb 7, 2019, at 1:00 PM, Steven White <notifications@github.com> wrote:

Hi, @jevansAN <https://github.com/jevansAN>, the topic should be updated shortly with a code example. Meanwhile, here's the code I added to the topic, I hope it helps.

auto contentKeyValuePairs{
winrt::single_threaded_map<winrt::hstring, winrt::hstring>(std::map<winrt::hstring, winrt::hstring>{
    { L"firstname", L"Jane" }, { L"lastname", L"Austen" }
})
};
Windows::Web::Http::HttpFormUrlEncodedContent content1{ contentKeyValuePairs };

Windows::Web::Http::HttpFormUrlEncodedContent content2{
    std::map<winrt::hstring, winrt::hstring>{
        { L"firstname", L"Jane" }, { L"lastname", L"Austen" }}
};
~Steve

—

**Comment by stevewhims** [comment]
Great! I'll leave the issue open until I see that the code example is live.

**Comment by jevansAN** [comment]
Thanks again. Never would have guessed that std::map was the answer! Seems more obvious in retrospect.
What I’m trying to do is to POST a block of binary data to an online file; on the Mac I do this with Multipart form data but on Win it was appearing to me that I could use buffercontent. Only trouble is that key value pairs are required to get through a cgi script that handles incoming. Would be even greater if there were a recipe somewhere for doing this kind of thing with httpclieint in C++/winrt.


On Feb 7, 2019, at 1:33 PM, Steven White <notifications@github.com> wrote:

Great! I'll leave the issue open until I see that the code example is live.

**Comment by stevewhims** [comment]
Jeff, it'd be great if you could give me more details about that latest ask, please, because I don't grok it yet. Perhaps if you file a new issue against the WinRT class in question? The more info you can give about your scenario, and what you want a code example to do, the more that'll help me get my head around it and think about a solution (and/or get help from the product team, if necessary). :) Thanks! ~Steve

**Comment by jevansAN** [comment]
Steve, Great offer - can I put it here?

The app has binary data that needs to be POSTed to a file online.
The destination base address is a cgi script.

On the Mac I use multipart form data but it’s not clear to me that this is necessary with HttpClient.

To summarize, on the Mac I begin with a url request constructed with an argument like this:

"https://www.oursite.com/cgi-bin/thescript.cgi?PIN=123456"

Then I use that request’s setHTPPMethod method to set the method to “POST” I suppose that httpClient’s PostAsync automatically takes care of  setting the method.

Then I add a key/value pair setting the Content-Type to multipart/form-data and supply a Boundary

Then I append path to the file on the server:

Content-Disposition: form-data;name=\"UPLOADED\"; filename=\”thePath\"\r\n\r\n”

And follow that with the block of binary data - this is hard to summarize unless I put in the actual objective-c code here but boundaries are put in to set off the data, etc.

All I really need is to get that data to the online file one way or another, first passing inspection at the cgi script. Maybe this can’t be done with HttpBufferContent. Maybe I need HttpMultipartContent. But a straight recipe for doing this sort of thing in C++/winrt would be very useful.

Thanks, Jeff


On Feb 7, 2019, at 2:23 PM, Steven White <notifications@github.com> wrote:

Jeff, it'd be great if you could give me more details about that latest ask, please, because I don't grok it yet. Perhaps if you file a new issue against the WinRT class in question? The more info you can give about your scenario, and what you want a code example to do, the more that'll help me get my head around it and think about a solution (and/or get help from the product team, if necessary). :) Thanks! ~Steve

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
Great detail, thanks. I'll go ahead and get advice from the product team about this. Once I know how to do it, in general, with the WinRT APIs, then I should be able to represent that in C++/WinRT code.

**Comment by stevewhims** [comment]
!!UPDATED with corrected code!!

Jeff, you're right that HttpClient.PostAsync automatically takes care of setting the POST method for you. And, we believe that the right thing is for you to use the HttpMultipartContent class for the content object that you pass to PostAsync. Here's some code:

```cppwinrt
    Windows::Web::Http::HttpMultipartContent content;
    Windows::Web::Http::Headers::HttpContentDispositionHeaderValue disposition{ L"attachment" };
    content.Headers().ContentDisposition(disposition);
    disposition.FileName(L"thePath");
    disposition.Name(L"UPLOADED");

    // Then add your binary content... (but not pre-encoded; the APIs do all of the bits needed).

    content.Add(httpBufferContent1);
    content.Add(httpBufferContent2);
    content.Add(httpBufferContent3);
```

Also see [HttpContentHeaderCollection.ContentDisposition](https://docs.microsoft.com/uwp/api/windows.web.http.headers.httpcontentheadercollection.contentdisposition) for more code (in C#) about that aspect.

**Comment by jevansAN** [comment]
Steven, That is very helpful, thanks; I’m going to it a try.

Hope you at MS can find food during the snowpocalypse.

Jeff

On Feb 11, 2019, at 2:57 PM, Steven White <notifications@github.com> wrote:

Jeff, you're right that HttpClient.PostAsync automatically takes care of setting the POST method for you. And, we believe that the right thing is for you to use the HttpMultipartContent class for the content object that you pass to PostAsync. Here's some code:

    Windows::Web::Http::HttpMultipartContent content;
    auto disposition{ content.Headers().ContentDisposition() };
    disposition.FileName(L"PUT_THE_FILE_PATH_HERE");
    disposition.Name(L"UPLOADED");

    // Then add your binary content... (but not pre-encoded; the APIs do all of the bits needed).

    content.Add(httpBufferContent1);
    content.Add(httpBufferContent2);
    content.Add(httpBufferContent3);
Also see HttpContentHeaderCollection.ContentDisposition <https://docs.microsoft.com/uwp/api/windows.web.http.headers.httpcontentheadercollection.contentdisposition> for more code (in C#) about that aspect.

**Comment by stevewhims** [comment]
Haha, thanks, Jeff! :D

**Comment by jevansAN** [comment]
Steven,

	A little progress here - 
	It looks to me like the content object in your first line below is never created.
	To get past that I changed the first line this way:

   winrt::Windows::Web::Http::HttpMultipartContent content = winrt::Windows::Web::Http::HttpMultipartContent();

   Which gets us to the next line, where the content’s disposition turns out to be null and one can’t set its filename or name. So I’m creating that and then setting the file name and name fields.

	Doesn’t move anything to the server, though. The trouble could lie in the meaning of Path here. On the Mac I init a URLRequest with the path to the cgiscript, and that path includes both PIN=123456 and PATH=. followed by the local path to file name. So I’m assuming that the destination uri for PostAsync might look like this:
	
	winrt::Windows::Foundation::Uri destinationUri{ L"https://www.ourdomain.com/cgi-bin/ourscript.cgi?PIN=123456”};

	Then I set the FileName field in contentDisposition to the path and file name, e.g.

	contentDisposition.FileName(L”rootDirectory/fileFolder/theFile.dat”);

	And then

	contentDisposition.Name(L”UPLOADED”);

	// I create a buffer with the data, like so

	winrt::Windows::Storage::Streams::IBuffer buffer;	//init this with filebytes
	std::vector<unsigned char> byteArray = std::vector<unsigned char>();
	byteArray.assign(fileBytes, fileBytes + fileLength);
	buffer = winrt::Windows::Security::Cryptography::CryptographicBuffer::CreateFromByteArray(byteArray);
	Windows::Web::Http::HttpBufferContent bufferContent{ buffer };
	content.Add(bufferContent);
	
	And finally call

	httpResponseMessage = co_await m_http_client.PostAsync(destinationUri, content);

	If this ever gets worked out I can supply a more complete example if it will be  helpful. Right now it runs without error but also without result!

	Jeff


On Feb 11, 2019, at 2:57 PM, Steven White <notifications@github.com> wrote:

Jeff, you're right that HttpClient.PostAsync automatically takes care of setting the POST method for you. And, we believe that the right thing is for you to use the HttpMultipartContent class for the content object that you pass to PostAsync. Here's some code:

    Windows::Web::Http::HttpMultipartContent content;
    auto disposition{ content.Headers().ContentDisposition() };
    disposition.FileName(L"PUT_THE_FILE_PATH_HERE");
    disposition.Name(L"UPLOADED");

    // Then add your binary content... (but not pre-encoded; the APIs do all of the bits needed).

    content.Add(httpBufferContent1);
    content.Add(httpBufferContent2);
    content.Add(httpBufferContent3);
Also see HttpContentHeaderCollection.ContentDisposition <https://docs.microsoft.com/uwp/api/windows.web.http.headers.httpcontentheadercollection.contentdisposition> for more code (in C#) about that aspect.

**Comment by stevewhims** [comment]
I've corrected the code (if you scroll back up to my reply with the code, that's now UPDATED). The ```Windows::Web::Http::HttpMultipartContent content;``` part is correct; it's a briefer way and slightly faster way of saying ```winrt::Windows::Web::Http::HttpMultipartContent content = winrt::Windows::Web::Http::HttpMultipartContent();```. But you're right that we have to create an instance of the disposition, because it's null initially.

As for the remaining issue, is there some uncertainty around how the cgi script works, and what it expects? Or do you have that working on Mac already? I'm just curious what might be a function of your particular app/server, and what might be an issue that needs documenting. If you're still having issues, and you suspect it's the latter, then please give me a full example and I'll ask the feature team folks. ~Steve

**Comment by jevansAN** [comment]
Great, Thanks. Didn’t realize it wasn’t necessary to say HttpMultipartContent() - 

I could ask our server guy to tell me exactly what comes in when I do this from the Mac code, though I expect there’s going to be a lot in there that isn’t specified in the code itself.
My uploader on the Mac begins with the the path to the the cgi script, followed by the PIN= and the PIN number. That is the serverURL and becomes the argument to a URLRequest.
Then I set the HTTP method of that request to POST I set a header field, Content-Type, to multipart/form-data and I specify a boundary. I don’t see any boundary stuff in the supplied code - maybe it’s built-in?
Then the data is appended to the content, then a boundary, then "Content-Disposition: form-data; NAME = \”UPLOADED\”; filename=, then some returns and linefeeds followed by the local file path on the server and another boundary.

Hope that’s not too vague. If you don’t mind looking at Objective-C I could send the actual code.

Really appreciate all the help,

Jeff



On Feb 11, 2019, at 7:15 PM, Steven White <notifications@github.com> wrote:

I've corrected the code. The Windows::Web::Http::HttpMultipartContent content; part is correct; it's a briefer way and slightly faster way of saying winrt::Windows::Web::Http::HttpMultipartContent content = winrt::Windows::Web::Http::HttpMultipartContent();. But you're right that we have to create an instance of the disposition, because it's null initially.

As for the remaining issue, is there some uncertainty around how the cgi script works, and what it expects? Or do you have that working Mac already? I'm just curious what might be a function of your particular app, and what might be an issue that needs documenting. If you're still having issues, and you suspect it's the latter, then please give me a full example and I'll ask the feature team folks. ~Steve

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
Jeff, I've sent an email to the feature team, with a summary of where we are. I hope we can figure this out, and then I can get the solution documented. I'll keep you posted. ~Steve

**Comment by jevansAN** [comment]
Steven, It might help for me to supply the most recent complete code I’m attempting. Only part left out here is the PostAsync, which I’ve moved to a separate method for easier debugging.  Of course, the addresses are changed here to protect the innocent:

	std::wstring requestURL = (L"https://www.ourdomain.com/cgi-bin/ourscript.cgi?PIN=123456”);
	winrt::Windows::Foundation::Uri requestUri{ requestURL };

	//Fill a buffer

	winrt::Windows::Storage::Streams::IBuffer buffer;
	std::vector<unsigned char> byteArray = std::vector<unsigned char>();
	byteArray.assign(fileBytes, fileBytes + fileLength);
	buffer = winrt::Windows::Security::Cryptography::CryptographicBuffer::CreateFromByteArray(byteArray);

	//Create multipartformdatacontent

	winrt::Windows::Web::Http::HttpMultipartFormDataContent content = winrt::Windows::Web::Http::HttpMultipartFormDataContent(L"Xx11811dJe”);

	//Init the contentdisposition header since they are initially null

	auto contentDisposition = winrt::Windows::Web::Http::Headers::HttpContentDispositionHeaderValue(L"form-data");
	contentDisposition.Name(L"UPLOADED");
	contentDisposition.FileName(path);
	content.Headers().ContentDisposition(contentDisposition);

	//Add the buffer
	Windows::Web::Http::HttpBufferContent bufferContent{ buffer };
	content.Add(bufferContent);

	//Go to PostAsync (result is an error 5004)
	CompleteFileUpload(requestUri, content);

The server script receives traffic from this but apparently doesn’t find a file path. We know the script itself works because it’s being used for receiving file data from the Mac version, also using multipart.

Thanks, Jeff


On Feb 12, 2019, at 12:42 PM, Steven White <notifications@github.com> wrote:

Jeff, I've sent an email to the feature team, with a summary of where we are. I hope we can figure this out, and then I can get the solution documented. I'll keep you posted. ~Steve

**Comment by stevewhims** [comment]
Thanks, Jeff. While we're waiting for help from the product team, I was reading https://tools.ietf.org/html/rfc1867, part of which says:

   The original local file name may be supplied as well, either as a
   'filename' parameter either of the 'content-disposition: form-data'
   header or in the case of multiple files in a 'content-disposition:
   file' header of the subpart. The client application should make best
   effort to supply the file name; if the file name of the client's
   operating system is not in US-ASCII, the file name might be
   approximated or encoded using the method of [RFC 1522](https://tools.ietf.org/html/rfc1522).

Is it possible that you're running into an encoding difference between the Mac and Windows clients? Specifically, the encoding of the filename string that we're passing, which starts out as a wide string in the C++/WinRT code, but I don't know how it's encoded over the wire.

Also, the [Content-Disposition](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Disposition) docs say, "The filename is always optional and must not be used blindly by the application: path information should be stripped, and conversion to the server file system rules should be done. This parameter provides mostly indicative information."

That last part is interesting. It seems like it's domain-specific exactly what the server should do with that filename. Can you compare the actual filename parameter (directive) that arrives at the server from the two client systems (Mac and Win) to confirm that they're identical when they hit the server? Just a thought.

**Comment by stevewhims** [comment]
Some good advice from the product team: "For this sort of issue, the best way to proceed is to collect HTTP traces. That way, we can compare the successful (Mac) HTTP POST request against the unsuccessful (Windows) HTTP POST request. Once we know what the HTTP-level differences are, it’ll be easy to determine the necessary code change."

Would you be able to go about collecting those traces?

**Comment by jevansAN** [comment]
Thanks - I suppose that would require figuring out how to use Fiddler; maybe I can get someone to try looking at that.

Jeff


On Feb 14, 2019, at 4:19 PM, Steven White <notifications@github.com> wrote:

Some good advice from the product team: "For this sort of issue, the best way to proceed is to collect HTTP traces. That way, we can compare the successful (Mac) HTTP POST request against the unsuccessful (Windows) HTTP POST request. Once we know what the HTTP-level differences are, it’ll be easy to determine the necessary code change."

Would you be able to go about collecting those traces?

**Comment by jevansAN** [comment]
Our web guy did give me a trace today for the Win POST - it may be enough to tell the tale.

It was very brief. First I’ll show the relevant code. For the test I sent just 4 bytes, ’StHd’,  and the path argument was a path from root to and including the desired file name, as we do on the Mac side:

winrt::Windows::Web::Http::HttpMultipartFormDataContent content = winrt::Windows::Web::Http::HttpMultipartFormDataContent(L”—Xx11811dJe");
	auto contentDisposition = winrt::Windows::Web::Http::Headers::HttpContentDispositionHeaderValue(L"form-data");
	contentDisposition.Name(L"UPLOADED");
	contentDisposition.FileName(path);
	content.Headers().ContentDisposition(contentDisposition);
	Windows::Web::Http::HttpBufferContent bufferContent{ buffer };
	content.Add(bufferContent);
	CompleteFileUpload(requestUri, content);	//This goes to an IAsyncAction to do to do the PostAsync

The trace at the server showed this:

Feb-15-2019 17:11;48

—Xx11811dJe
Content-Length: 4
Content-Disposition: form-data

StHd
—Xx11811dJe—

What is missing from that is the contentDisposition.Name and the contentDisposition.FileName. A mystery to me. Are those fields not correctly set in Content.Headers ?

Thanks, Jeff



On Feb 14, 2019, at 4:19 PM, Steven White <notifications@github.com> wrote:

Some good advice from the product team: "For this sort of issue, the best way to proceed is to collect HTTP traces. That way, we can compare the successful (Mac) HTTP POST request against the unsuccessful (Windows) HTTP POST request. Once we know what the HTTP-level differences are, it’ll be easy to determine the necessary code change."

Would you be able to go about collecting those traces?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by PeterSmithRedmond** [comment]
Can you try setting the name and the filename on the BufferContent and  not the 'content' item. Getting the Mac POST, though, will be tremendously useful because then you can compare one against the other directly.

**Comment by jevansAN** [comment]
Peter, thanks for getting back. I now have the Mac data and will supply it below.

By ’setting name and the filename on the BufferContent’ I guess you mean to add the ContentDisposition item to the buffer content’s header() rather than addition to the multipart form content item, like this:

winrt::Windows::Web::Http::HttpMultipartFormDataContent content = winrt::Windows::Web::Http::HttpMultipartFormDataContent(L"0xKhTmLbOuNdArY");
	auto contentDisposition = winrt::Windows::Web::Http::Headers::HttpContentDispositionHeaderValue(L"form-data");
	contentDisposition.Name(L"UPLOADED");
	contentDisposition.FileName(path);
	Windows::Web::Http::HttpBufferContent bufferContent{ buffer };
	bufferContent.Headers().ContentDisposition(contentDisposition);
	content.Add(bufferContent);

I hope that’s not what you meant, because it didn’t alter the results! Since HttpBufferContent doesn’t seem to have name and filename properties I don’t know what else I’d do with them.

The trace of the Mac input looked like this,, with arbitrary path substituted:

Feb-15-2019 17:49:33:

—0xKhTmLbOuNdArY
Content-Disposition: form-data;name=“UPLOADED”; filename=“aDirectory/anotherDirectory/yetAnotherDirectory/BergAlban363316.stu”

StHd
—0xKhTmLbOuNdArY

That is, it’s the same as the Win version except that Content-Disposition includes the name and filename. One thing I wonder about: in C++/winrt all these objects taking a string argument require wide strings. Yet the data arriving at the server might need to be char string? Maybe the system converts those.

Jeff

On Feb 17, 2019, at 2:51 PM, Peter Smith <notifications@github.com> wrote:

Can you try setting the name and the filename on the BufferContent and not the 'content' item. Getting the Mac POST, though, will be tremendously useful because then you can compare one against the other directly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by PeterSmithRedmond** [comment]
Yes, sorry for not being clear. This is what I get for my outgoing request:
HTTP REQUEST:
--Xx11811dJe
Content-Length: 33
Content-Disposition: form-data; name="UPLOADED"; filename="path/to/file"

this is my file
it has two lines
--Xx11811dJe--


and here's my C# code. I make a ContentdispositionHeaderValue
```
            var contentDisposition = new HttpContentDispositionHeaderValue("form-data");
            contentDisposition.Name = "UPLOADED";
            contentDisposition.FileName = "path/to/file";
```
then I set the ContentDisposition on the HttpBufferContent.

AFAICT, this is exactly what you're doing now.

**Comment by jevansAN** [comment]
Thanks - interesting that mine doesn’t show Content-Length in either the working Mac trace or the nonworking Win trace.
When you set the ContentDIsposition on the HttpBufferContent I expect you are doing this, with differences for C+/winrt:

bufferContent.Headers().ContentDisposition(contentDisposition);

In C++/Winrt the Headers() just gets you the Headers object and the then the ContentDisposition property of the Headers gets set to contentDisposition. .

The only other thing I can guess at is that your C# code is using char* arguments while the C++/winrt is using wchar_t*.
Unless C# doesn’t work that way, for all I know.

Jeff


On Feb 17, 2019, at 4:56 PM, Peter Smith <notifications@github.com> wrote:

Yes, sorry for not being clear. This is what I get for my outgoing request:
HTTP REQUEST:
--Xx11811dJe
Content-Length: 33
Content-Disposition: form-data; name="UPLOADED"; filename="path/to/file"

this is my file
it has two lines
--Xx11811dJe--

and here's my C# code. I make a ContentdispositionHeaderValue

            var contentDisposition = new HttpContentDispositionHeaderValue("form-data");
            contentDisposition.Name = "UPLOADED";
            contentDisposition.FileName = "path/to/file";

then I set the ContentDisposition on the HttpBufferContent.

AFAICT, this is exactly what you're doing now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
FYI, C# doesn't use narrow strings. It uses Unicode strings, so you can interpret C#'s "literal" the same as C++'s L"literal".

**Comment by jevansAN** [comment]
Thanks - that’s good to know. Now just have to find out why that header content isn’t getting to the server script. Has me stumped.

Jeff


On Feb 19, 2019, at 2:42 PM, Steven White <notifications@github.com> wrote:

FYI, C# doesn't use narrow strings. It uses Unicode strings, so you can interpret C#'s "literal" the same as C++'s L"literal".

**Comment by jevansAN** [comment]
Steven,
	
	Thanks for your latest responses; I’m about to review them. Meanwhile, we did work out the POST with http client, and I’ll show you how we did it, if the info is of any use:

	
std::wstring requestURL = (L"https://www.ourdomain.com/cgi-bin/ourscript.cgi?PIN=123456");
	winrt::Windows::Foundation::Uri requestUri{ requestURL };

	//Create buffer and init it with the fileData/fileLength supplied to this upload method
	winrt::Windows::Storage::Streams::IBuffer buffer;	
	std::vector<unsigned char> byteArray = std::vector<unsigned char>();
	byteArray.assign(fileBytes, fileBytes + fileLength);
	buffer = winrt::Windows::Security::Cryptography::CryptographicBuffer::CreateFromByteArray(byteArray);
	auto bufferContent = winrt::Windows::Web::Http::HttpBufferContent(buffer);

	//All the header stuff needs to be on the buffer content

	bufferContent.Headers().Append(L"Content-Type", L"image/jpeg");	//or application/octet-stream? Binary, that is	  Windows::Web::Http::Headers::HttpContentDispositionHeaderValue disposition{ L"form-data" };
	disposition.Name(L"UPLOADED");
	disposition.FileName(path);
	bufferContent.Headers().ContentDisposition(disposition);

	std::wstring boundary = std::wstring(L”XxThisiSDaBouNDary");
	auto content = winrt::Windows::Web::Http::HttpMultipartFormDataContent(boundary);
	content.Add(bufferContent);

	//The following is the AsyncAction that completes the PostAsync. This is separate for debugging purposes.
	CompleteFileUpload(requestUri, content);
----
On Feb 19, 2019, at 4:11 PM, Jeff Evans <jevans@ars-nova.com> wrote:

Thanks - that’s good to know. Now just have to find out why that header content isn’t getting to the server script. Has me stumped.

Jeff


On Feb 19, 2019, at 2:42 PM, Steven White <notifications@github.com> wrote:

FYI, C# doesn't use narrow strings. It uses Unicode strings, so you can interpret C#'s "literal" the same as C++'s L"literal".

**Comment by stevewhims** [comment]
That's great info, thanks, Jeff! It seems like the trick was to apply the content disposition to the buffer (rather than the post) content, so I've changed the code in my topic to match that. Thanks for the update! :)

~Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this issue now, since we got it resolved. ~Steve
