### ISSUE TITLE
C++ methods should be searchable

### ISSUE THREAD

**Issue by CaptainZippy** [MicrosoftDocs/winrt-api#908]
To reproduce:

Try to search the web for "RunWithPriorityAndOptionsAsync". 0 hits on most engines.
(Though bing seems to have some smarts)

It seems this method has been projected as an overload of RunAsync. In general there
should be a way for people to find the right content using the interface names.
And when they get there, to see the projected vs raw names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d09968d-d6f4-eee7-ff2c-943ceb4025c5
* Version Independent ID: ac8915b6-a8ef-d629-0bef-c0e16293eff2
* Content: [ThreadPool Class (Windows.System.Threading) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.System.Threading.ThreadPool)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.threading.threadpool.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.threading.threadpool.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for your input. This will require some investigation and, potentially, an engineering fix. I've added this issue to our queue to investigate.
