### ISSUE TITLE
No link to Package class

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#909]
There's no link to jump to the Package class in this article; it makes it harder to navigate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 708a3ece-610f-6481-ac54-59e49359fb1d
* Version Independent ID: f15dc0e2-c450-0bef-bde0-2de09f784f15
* Content: [PackageManager.FindPackages Method (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackages)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by riverar** [comment]
Adding @dend, it's been a year with no ack.

**Comment by glibnub** [comment]
@GrantMeStrength - can you please take a look? Seems like something your team can address.

**Comment by hickeys** [comment]
I apologize for the delay in responding to this issue. This is really good feedback; there should absolutely have been a link to the Package class in this and every other article in this section. I've added links to all files. I just merged the changes into the public branch, they should be live within the next 24 hours. Thanks for logging this issue.
