### ISSUE TITLE
cues flicker

### ISSUE THREAD

**Issue by brabebhin** [MicrosoftDocs/winrt-api#910]
Calling this method when there is an active, displayed cue will cause said cue to flicker. 

This document does not provide any clues on how to fix this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7d1df21-773b-7667-c465-30cca9bfbab3
* Version Independent ID: 7d56d10a-71e9-4a7c-e680-dad3ad81728b
* Content: [TimedMetadataTrack.AddCue(IMediaCue) Method (Windows.Media.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.core.timedmetadatatrack.addcue#Windows_Media_Core_TimedMetadataTrack_AddCue_Windows_Media_Core_IMediaCue_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.timedmetadatatrack.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.core.timedmetadatatrack.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. Though the scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
