### ISSUE TITLE
Was this event introduced after 16299?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/winrt-api#912]
I can't seem to use this on 16299 (get a cast exception below).  However, if that's the case, the API version isn't called out in the docs that this particular event is only usable on a newer system.

    "Unable to cast object of type 'Windows.System.RemoteSystems.RemoteSystemWatcher' to type 'Windows.System.RemoteSystems.IRemoteSystemWatcher2'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 907ec6be-271d-7b46-9e8d-b973c31329aa
* Version Independent ID: c8487fbb-d4e7-6a51-cb97-6248b3c19223
* Content: [RemoteSystemWatcher.EnumerationCompleted Event (Windows.System.RemoteSystems) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.remotesystems.remotesystemwatcher.enumerationcompleted)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.remotesystems.remotesystemwatcher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.remotesystems.remotesystemwatcher.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **msatranjr**
* Microsoft Alias: **misatran**

**Comment by michael-hawker** [comment]
Confirmed with platform team that `IRemoteSystemWatcher2` was introduced in 17134.  That includes both events `EnumerationCompleted` and `ErrorOccurred`.  So, the docs for these two events should call that out as such.  Thanks!

**Comment by stevewhims** [comment]
Hi, @michael-hawker. Looks like the topics for the two events you mention are documented as being introduced in 10.0.17134.0.

I'll go ahead and close this issue.

Thanks!
