### ISSUE TITLE
Incorrect Assembly stated

### ISSUE THREAD

**Issue by rahulsingh11** [MicrosoftDocs/winrt-api#914]
Windows.Media.ClosedCaptioning can be found in the Windows.Media.dll assembly. 

There is no Windows.Media.ClosedCaptioning.dll on Windows 10. As such, the Assemblies info on this page should be updated to reflect this.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b9cbfd5-5329-8557-7617-1eb1dbd7d422
* Version Independent ID: 6c373ba3-d646-0a30-2937-c799966205ba
* Content: [Windows.Media.ClosedCaptioning Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.closedcaptioning)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.closedcaptioning.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.closedcaptioning.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thank you for your feedback. We no longer display assembly information in WinRT API reference pages.
