### ISSUE TITLE
How do these SubTypes correlate to File Extensions?

### ISSUE THREAD

**Issue by StevenEdwardWood** [MicrosoftDocs/winrt-api#917]
If an application only has the user's selected filename and extension then what should be the SubType string.  If the application allows the user to select the SubType, from a drop down list for example, then what should be the file extension?  If an application allows the user to select both a file extension and SubType then how do they correlate?  For example if the user first selects the SubType then what file extensions should the application suggest?  And, vice versa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a06d8b-c459-6fb5-ac00-307125fe0aa0
* Version Independent ID: ab2e0e70-9ee5-9718-f94e-66715ba33f0e
* Content: [AudioEncodingProperties.Subtype Property (Windows.Media.MediaProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.mediaproperties.audioencodingproperties.subtype)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.audioencodingproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.mediaproperties.audioencodingproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hi, most of the audio file subtype names are the same as the associated file extension, with some exceptions (vorbis -> ogg). But there is not always a 1:1 mapping of file format to extension. For example, many different media formats can be placed inside an AVI container. Also, audio can be encoded in, say, mp3 format and then included in a stream in an .mp4 file. So, when you are encoding audio to a file, you should pick an appropriate extension for the subtype you are using to encode, but you shouldn't assume a subtype of someone else's file based on the file extension.
