### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#918]
For example, the link from here to CommandBar is:

    https://docs.microsoft.com/en-us/uwp/windows.ui.xaml.controls/commandbar.md

which gives 404.  This works:

    https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CommandBar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af4281b-e911-b8a2-ed6c-e01864ab9cc7
* Version Independent ID: 095a3d25-fd96-aae9-13f5-f6b55d813d74
* Content: [KeyboardAccelerator Class (Windows.UI.Xaml.Input) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Input.KeyboardAccelerator)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.keyboardaccelerator.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.input.keyboardaccelerator.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Issue identified and fixed.
