### ISSUE TITLE
Cannot format ISO 8601 using the DateTimeFormatter

### ISSUE THREAD

**Issue by Travis-Snoozy** [MicrosoftDocs/winrt-api#919]
There is no direct option to select whether a 24H or 12H representation for the "hours" place is used -- instead, it defers to the "Clock" setting (which is just a string, and is not usefully documented).

{timezone} is also not well-documented enough to be included in the manual construction of an ISO 8601 string. I have no idea if {timezone}/{timezone.full}/{timezone.abbreviated} will result in -08:00/-08:00/-08 or in something more bizarre like Pacific/Pacific Standard Time/-08.

This means that, in the best-case scenario, a DateTimeFormatter has to be explicitly constructed with a correct locale/clock in order to output an ISO 8601 string, then used with a UTC time so that the timezone situation can be sidestepped (with a Z at the end). In the worst-case scenario, such a string could only be constructed by changing the system's locale/clock, or guess-and-checking (manually re-parsing/re-generating the output string as necessary) to detect 12H hour values and convert them to 24H instead.

Ideally, there would be a format for {datetime} (or similar) that simply output a correct ISO 8601 datetime+timezone stamp directly. Barring that, an {hours.invariant} (or similar) would be necessary to construct one, e.g., {year}-{month.integer(2)}-{day.integer(2)}T{hour.invariant.integer(2)}:{minute.integer(2)}:{second.integer(2)}Z (assuming the input time is UTC), or {year}-{month.integer(2)}-{day.integer(2)}T{hour.invariant.integer(2)}:{minute.integer(2)}:{second.integer(2)}{timezone} (assuming that the {timezone} tag expands to ISO 8601 valid values, e.g., Z, -08, +10, -0700, +11:00).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac5acf1-6bda-78f4-4879-8abdb864ee8a
* Version Independent ID: 46c1be16-5071-dd28-4fd5-544b9dc09d40
* Content: [DateTimeFormatter Class (Windows.Globalization.DateTimeFormatting) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.datetimeformatting.datetimeformatter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.datetimeformatting.datetimeformatter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.datetimeformatting.datetimeformatter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! However, this appears to be a product issue and not a doc bug (at this time), so please consider posting the issue at https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose for the product team to track publicly.
