### ISSUE TITLE
The Remarks are incorrect

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/winrt-api#921]
This event is actually designed as a companion to DragStarting, so is fired by elements with CanDrag = true, after the drag and drop operation initiated from that element has finished (successfully or unsuccessfully). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad59210-d313-291b-1683-e709a6b10a74
* Version Independent ID: f96daf06-a3fe-1d13-27c7-f47b85c2d365
* Content: [UIElement.DropCompleted Event (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.dropcompleted)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by predavid-zz** [comment]
@jwmsft - could you please update the doc to update the remark mentioned  in this Issue.

**Comment by jwmsft** [comment]
The doc has been updated.
