### ISSUE TITLE
pin secondary tile to taskbar

### ISSUE THREAD

**Issue by icodingforfood** [MicrosoftDocs/winrt-api#924]
No docs about pin secondary tiles to taskbar and no more infos about Limited-Access.  The "See also“  is https link?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e8e3f90a-5801-64be-d1bf-3d47616d6966
* Version Independent ID: 556b20f9-75d6-a5b2-0d5c-48b0fba8bda9
* Content: [TaskbarManager.RequestPinSecondaryTileAsync(SecondaryTile) Method (Windows.UI.Shell) - Windows UWP applications](https://docs.microsoft.com/zh-cn/uwp/api/windows.ui.shell.taskbarmanager.requestpinsecondarytileasync#Windows_UI_Shell_TaskbarManager_RequestPinSecondaryTileAsync_Windows_UI_StartScreen_SecondaryTile_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.shell.taskbarmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.shell.taskbarmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
The Limited-access is described in the link in the first paragraph. You're right though, it's not particular clear so I've updated the language a little to more accurately describe the process. Changes should show up shortly.
