### ISSUE TITLE
hakim mazigh

### ISSUE THREAD

**Issue by hakimmazigh** [MicrosoftDocs/winrt-api#925]
Mymazigha_IBM_

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 26c44946-e6fc-05ca-5fed-999ddba59e64
* Version Independent ID: ef2b2cb3-dc6a-e21a-ce00-cfefaa0da217
* Content: [Windows.ApplicationModel.Payments Namespace - Windows UWP applications](https://docs.microsoft.com/ar-sa/uwp/api/windows.applicationmodel.payments)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.payments.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.payments.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi, this doesn't look like documentation feedback to me. Closing. Please open a new issue if this was closed by mistake.
