### ISSUE TITLE
Document is not detailed enough

### ISSUE THREAD

**Issue by izikbru-dev** [MicrosoftDocs/winrt-api#928]
This subject is not so simple. There is not much data how to make UWP with desktop apps, and this page is not really informative. Need a guide that explain what to do and give example for each step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8aa76ad-d68d-53a1-8821-526ae1f618e4
* Version Independent ID: a3a99abf-5843-057e-dcc9-027d524bcd37
* Content: [FullTrustProcessLauncher Class (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.FullTrustProcessLauncher#remarks)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.fulltrustprocesslauncher.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.fulltrustprocesslauncher.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi, can you clarify what you are looking for? Perhaps [this guide](https://blogs.msdn.microsoft.com/appconsult/2016/12/19/desktop-bridge-the-migrate-phase-invoking-a-win32-process-from-a-uwp-app/) would be useful. In general, API Reference documents are kept more succinct and do not include step-by-step guides. 

Also, I encourage you to check out our [Windows developer support center](https://developer.microsoft.com/windows/support) for help writing applications.

**Comment by auserwhowouldnotdisclosehisorhername** [comment]
Is there any security concerns to activate a win32 component from an UWP app through FullTrustProcessLauncher?

**Comment by izikbru-dev** [comment]
Hi, not about security, just tried to work with UWP and another desktop app. unfortunately, I gave up this idea for it's complexity, but I'll try the guide u send, Thanks.

**Comment by jtorjo** [comment]
Yeah, this is simply unseable - #1349
