### ISSUE TITLE
Putting a margin on the content is not the way to centre it when using labels on the right

### ISSUE THREAD

**Issue by geometrikal** [MicrosoftDocs/winrt-api#929]
If you have `DefaultLabelPosition="Right"` for the CommandBar, then you need to remove the margins on the content and instead add `VerticalContentAlignment="Center"` to the CommandBar, otherwise the CommandBar will shift vertically when the secondary commands are opened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3599dc1-9592-6a5b-b74a-ed723a61948d
* Version Independent ID: 65c4cda8-612a-683b-e739-120da95bf716
* Content: [CommandBar Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CommandBar)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.commandbar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.commandbar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Great feedback. We should definitely use layout properties here to position.

**Comment by YuliKl** [comment]
@geometrikal - can you provide a code snippet of what isn't working, and how you were able to correct the alignment?

**Comment by jwmsft** [comment]
I was not able to repro any issues with example. If there is still an issue to be fixed, feel free to re-open and provide more detail as requested by YuliKl
