### ISSUE TITLE
Performance information missing.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#930]
Hi,
This is a general issue with documentation, but I'm looking at one method right now as an example of my requirement, CryptographicBuffer.CreateFromByteArray(Byte[]). What I would like to see is some performance information, so is this an expensive operation (does it copy the data) or is it cheap (does it create a view of the existing data). I mean I have no idea what a buffer actually is, I don't even know why I want a buffer if I already have a byte[], why would I want to write a buffer to file and not a byte[]. Is there some hidden quality of the buffer object that I don't know about?

Some information would be good, because I want to know if Conversion to a buffer has to copy the data or is it an instant method call.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3191bfe1-8acf-3387-5138-b06918f78c3d
* Version Independent ID: e89e0601-a957-18c3-10ab-738ea96e0076
* Content: [CryptographicBuffer.CreateFromByteArray(Byte\[\]) Method (Windows.Security.Cryptography) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.security.cryptography.cryptographicbuffer.createfrombytearray)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.security.cryptography.cryptographicbuffer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **msatranjr**
* Microsoft Alias: **misatran**

**Comment by GrantMeStrength** [comment]
Thanks for the comment, and sorry for the delay in addressing it. 

This is a great point, and something which is not addressed in the current documentation at all. The good news is that there is a new initiative focused on performance, and I will share this issue with the team - so hopefully the situation will improve in the near future.

Thanks for taking the time to leave feedback, and again, sorry for the delay. We do read bugs as they come in, but may not add comments immediately, which gives a poor impression - I apologize. -John

**Comment by Gavin-Williams** [comment]
Thank you, that's great to hear.

Just to slightly expand, as someone who is focusing on game and graphics development mostly, these little performance questions are sometimes important. Because I'm often trying to perform an operation on a time-budget , which can be 16ms or 7ms, it may be an in-frame operation or it may be loading resources and I need to know which operation needs to be async or threaded. Just knowing which method is going to be costly can be helpful, and it's not always obvious, particularly for people (such as myself) who don't have a deep understanding of how these 'transformations' or 'views' work.

I know I can investigate performance issues when they arise, and when there's serious problems I do. But this is something that has come up occasionally, where, just by looking at the API and docs, I actually have no idea what a call costs. It may well be too much effort and too dependent on usage. But I thought I would bring it up as something that might be helpful. Even if methods were identified as performing 'deep copies' internally or if performance scaling were highlighted, perhaps by some automated mechanism just to add this bit of extra info about a call.
