### ISSUE TITLE
Where is the LocalFolder?

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/winrt-api#931]
You don't tell us where the package or the LocalFolder are. How are we meant to verify files existence and contents?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55183d06-94e7-2410-23e2-3e414a190bc9
* Version Independent ID: 9ac42a48-e4c5-23d6-d5d5-cf8c4d51e30c
* Content: [Package.InstalledLocation Property (Windows.ApplicationModel) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.package.installedlocation#Windows_ApplicationModel_Package_InstalledLocation)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.package.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi Gavin, 

If you are developing an app and are stuck, you should be able to get help via our [Windows developer support](https://developer.microsoft.com/en-us/windows/support) center. 

These articles might also be helpful: 
https://docs.microsoft.com/uwp/api/windows.storage.applicationdata 
https://docs.microsoft.com/uwp/api/windows.storage.applicationdata.localfolder

If you can elaborate on what information you would like added to this page, or how the content could be clearer, I can see about updating the content. 

Nick

**Comment by knicholasa** [comment]
Closing issue. Please open a new one if you have additional docs feedback.
