### ISSUE TITLE
Please, fix the link to the "AutomationProperties.ItemStatus". Thanks.

### ISSUE THREAD

**Issue by Matteo-T** [MicrosoftDocs/winrt-api#934]
Please, fix the link to the "AutomationProperties.ItemStatus". Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30244990-18f5-9be7-656a-90b25d19147e
* Version Independent ID: 769bdad8-6d68-e955-f1ef-9ac10c58fff1
* Content: [AutomationProperties.SetItemStatus(DependencyObject, String) Method (Windows.UI.Xaml.Automation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties.setitemstatus)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@Matteo-T - thanks for the feedback. I've revised the topic as required.
