### ISSUE TITLE
Change the Genre property

### ISSUE THREAD

**Issue by BlueEmb3r** [MicrosoftDocs/winrt-api#937]
What if I want to change the Genre property? What can be a way of doing it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a3936c1-c359-eceb-fe2b-b1782064f238
* Version Independent ID: 7813bfa3-f81f-1584-8c6d-2c6b68059d31
* Content: [MusicProperties Class (Windows.Storage.FileProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.musicproperties)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.musicproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.musicproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The Genre property is just a list of strings. The list collection object itself is read-only (that is, you can't assign the Genre property to a different list collection object), but you can freely remove or add genre strings to the collection by using methods of the IList object such as Insert, Add, Remove, etc. After you make your changes, call [SavePropertiesAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.musicproperties.savepropertiesasync) to save the changes.

I hope this helps!
