### ISSUE TITLE
LineSample simple docs

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/winrt-api#939]
I installed and deployed the app to a box with a line display.  I assume that the app auto loads all LineDisplays into the DisplaysListBox but mine remains empty so at that point the app is dead in the water since you can't move past Scenario1.  Is there a forum or other way to share in working with these samples?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eae601b-a158-0014-11a7-e8bd00174a99
* Version Independent ID: bbf8fa46-8710-04dd-e145-92f3c06d6eac
* Content: [LineDisplay Class (Windows.Devices.PointOfService) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.pointofservice.linedisplay)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.linedisplay.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.pointofservice.linedisplay.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @lightstamp. Thanks for filing this issue, and my apologies for the very long delay in responding.

You could try filing a GitHub issue in the repo from which you downloaded the sample: https://github.com/Microsoft/Windows-universal-samples/issues.

Thanks!
Steve
