### ISSUE TITLE
Is this official api?

### ISSUE THREAD

**Issue by TyJOrtiz** [MicrosoftDocs/winrt-api#941]
you should specify whether its prerelease api, or if functionality isn't there, or its restricted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f39f756-df4e-1db4-a96a-61432eaa547b
* Version Independent ID: 084d9582-b752-4fb9-b171-8ef641fae383
* Content: [GlobalSystemMediaTransportControlsSession Class (Windows.Media.Control) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.media.control.globalsystemmediatransportcontrolssession)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.control.globalsystemmediatransportcontrolssession.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.media.control.globalsystemmediatransportcontrolssession.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by TyJOrtiz** [comment]
Can i be assigned to someone else? i dont understand why no one respnds

**Comment by drewbatgit** [comment]
Thanks for taking the time to open this issue we sincerely apologize for the delayed response. GlobalSystemMediaTransportControls is a public API, it is restricted by a capability however it’s a public capability. The capability is “globalMediaControl” and with this apps should be able to control any app that has integrated with SystemMediaTransportControls API.
