### ISSUE TITLE
Revision for C++/winrt code

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#942]
I think it would help people using C++/winrt to see what a handler for this sort of event actually looks like - I can't see much relationship with the declaration shown above. This works for me, similar to the handlers for KeyDown, etc, that can use lambdas:

mainGrid.LostFocus([&](winrt::Windows::Foundation::IInspectable const& sender, IRoutedEventArgs const& args)
			{
				DoSomethingAboutIt();

			});

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1455f08-078c-f037-2236-b46f5950a714
* Version Independent ID: 13904b4d-eac0-15c3-f135-fcb5c50d3d3c
* Content: [UIElement.LostFocus Event (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.lostfocus)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.uielement.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Hi, @jevansAN, have you seen the topic about handling events using C++/WinRT? https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events. The first examples there use ButtonBase::Click (which is very similar to UIElement::LostFocus). Once you've followed along with that topic, you'll be able to use the syntax block in any event topic to handle the event. But please let me know if there are any issues. ~Steve

**Comment by jevansAN** [comment]
Steven, thanks - but that page is forbidden! Must be hot stuff.

Jeff


On Feb 25, 2019, at 5:12 PM, Steven White <notifications@github.com> wrote:

Hi, @jevansAN <https://github.com/jevansAN>, have you seen the topic about handling events using C++/WinRT? https://review.docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events?branch=master <https://review.docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events?branch=master>. The first examples there use ButtonBase::Click (which is very similar to UIElement::LostFocus). Once you've followed along with that topic, you'll be able to use the syntax block in any event topic to handle the event. But please let me know if there are any issues. ~Steve

**Comment by stevewhims** [comment]
Sorry, I fixed the link above, and here it is again: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events. :)

**Comment by stevewhims** [comment]
Hi, @jevansAN, we resolved this issue, so I'll go ahead and close it. Thanks! ~Steve
