### ISSUE TITLE
PeopleNames similar but not the same as Keywords

### ISSUE THREAD

**Issue by eowarren625** [MicrosoftDocs/winrt-api#943]
Keywords -&gt; IList&lt;string&gt; and can be cleared by using .clear().
PeopleNames -&gt; IReadOnlyList&lt;string&gt; without a .clear()

So the Remark in PeopleNames is factually true they are similar, they really are not functionally the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81f60e0-32b5-083a-0a1f-a2de0d310d02
* Version Independent ID: b4ca48be-9764-901b-954b-bcf2403027a2
* Content: [ImageProperties.PeopleNames Property (Windows.Storage.FileProperties) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.imageproperties.peoplenames)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.imageproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.fileproperties.imageproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback and for catching this! I changed the remarks to "This property is read-only. You can't delete or replace the collection itself, and the contents of the collection are also read-only". This change should be published to the live docs site in the next day or so.
