### ISSUE TITLE
I cannot find the Windows.Data.Text.dll file

### ISSUE THREAD

**Issue by slim16165** [MicrosoftDocs/winrt-api#944]
I made a lot of research on google but it's not easy to find or download it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5436764c-2b30-1f5f-9f12-e6ecc8317e62
* Version Independent ID: af39a6cb-4659-aec9-e9f0-348f47da2a18
* Content: [WordsSegmenter Class (Windows.Data.Text) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.data.text.wordssegmenter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.text.wordssegmenter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.data.text.wordssegmenter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The Windows.Data.Text.dll file cannot be downloaded separately. To use the WordsSegmenter class, make sure you have the [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) installed, and then make sure you have the Universal Windows SDK referenced in your UWP app project (this is referenced by default). If you install Visual Studio 2017 with the "Visual Studio Tools for Universal Windows Apps" installed, then you already have the Windows 10 SDK.
