### ISSUE TITLE
New formatter mode

### ISSUE THREAD

**Issue by dmitriy-proskurin** [MicrosoftDocs/winrt-api#945]
I wont request new formatter mode, which allow display sum without currency code/symbol. It may be useful when i need display some of values in a column(without currency symbol/code) with total at bottom(with currency symbol/code). 
Also, that formatter mode may useful when i was parse value with currency rules(decimal devider, etc.), but without currency symbol. Current implementation of DeciamalFormatter always requires currency symbol at string, otherwise it's returns null after call ParseDouble method, even if provider string satisfy currency rules for current region settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab3ec7c7-bfea-934c-f85f-01d8b31ca17f
* Version Independent ID: ede8d66e-6811-3fd8-1d8c-fa2c124981a1
* Content: [CurrencyFormatter.Mode Property (Windows.Globalization.NumberFormatting) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.numberformatting.currencyformatter.mode#Windows_Globalization_NumberFormatting_CurrencyFormatter_Mode)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.numberformatting.currencyformatter.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.globalization.numberformatting.currencyformatter.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by dmitriy-proskurin** [comment]
May be someone can say something about that?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @dmitriy-proskurin , thanks for the feedback. As this is product feedback and not documentation feedback, I suggest you revisit the page and submit your feedback using the "This product" button. Your feedback should then be routed to the feature team for consideration.
