### ISSUE TITLE
concurrency::parallel_for seems to run on an STA some of the time -> !is_sta() false error

### ISSUE THREAD

**Issue by lawabider** [MicrosoftDocs/winrt-api#946]
For now I am trying to use concurrency::parallel_for. I know that UWP does have its own threadpool `api.`

I am trying to do a .get() on one of the async methods. concurrency::parallel_for seems to run on an STA sometimes (possibly on the IU thread?). Hence I get the !is_sta() error.  Is there any way to prevent this?  Concurrency Runtime seems quite nice, even if it was not made for UWP.

UPDATE: I had an opencv imshow in the loop shown below (for debug build & development). Removing this seemed to remove the problem. 

```
		winrt::apartment_context _foreground_context; 

		co_await winrt::resume_background();

		concurrency::parallel_for(size_t(0), size_t(_files.Size()), [&](size_t i)
		{

			winrt::apartment_context _parallel_context;

			auto _stream = _files.GetAt(i).OpenReadAsync().get()

```

//#ifdef _DEBUG
//			cv::Mat _mat(_scaledHeight, _scaledWidth, CV_8UC4, _com_Array.data());
//			cv::normalize(_mat, _mat, 1.0, 0.0, cv::NormTypes::NORM_L1);
//			cv::imshow("Scaled Image from Windows.", _mat);
//#endif

**Comment by ginami** [comment]
Hi @lawabider -- thank you for your feedback. This list is for doc-specific issues; are you referring to a specific doc? If you let me know the URL, I can route your comments to the correct page owner. Thanks!

**Comment by lawabider** [comment]
Hi @ginami,
sorry; please feel free to delete this Issue. As I have noted it was caused by using opencv to pop up images, for debugging purposes, so probably is not really an issue.

**Comment by ginami** [comment]
No worries, @lawabider! Can't delete, but I'll close it out. Thank you!
