### ISSUE TITLE
Missing information about title bar occlussion

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/winrt-api#948]
When you set this to true, the view's content extends into the title bar region at the top, the height of which is given by CoreApplicationViewTitleBar.Height.  But note that that region is still treated like a title bar, in that you can drag the window with it, double-click to maximize, and right-click to bring up the system menu.  So you need to avoid putting pointer-interactive content in this region.  But further note that if you call Window.SetTitleBar to set a Xaml element as the title bar, this unclickable region is removed, and you needn't avoid putting pointer-interactive content in the region.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf71d8c9-232a-0dd5-16c6-460f9ea12791
* Version Independent ID: 63f11ecd-1fc5-c228-0909-2c1c362305dc
* Content: [CoreApplicationViewTitleBar.ExtendViewIntoTitleBar Property (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Core.CoreApplicationViewTitleBar.ExtendViewIntoTitleBar)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplicationviewtitlebar.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplicationviewtitlebar.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi Mike, thanks for the feedback. How about I add this to the remarks section of the page: 

When **ExtendViewIntoTitleBar** is true, the view's content will extend by **CoreApplicationViewTitleBar.Height** into the title bar region. The region will still be treated like a title bar, meaning you can still drag the window with it, double-click to maximize, and right-click to bring up the system menu. For this reason, you should avoid putting pointer-interactive content in the region. However, if you call Window.SetTitleBar to set a Xaml element as the title bar, the unclickable region is removed and it is no longer necessary to avoid putting pointer-interactive content in the region.

**Comment by MikeHillberg** [comment]
Looks great, thanks!
