### ISSUE TITLE
Additional Firing Conditions Missing

### ISSUE THREAD

**Issue by MichaelKintscher** [MicrosoftDocs/winrt-api#950]
This event fires more than just "when manipulations such as scrolling and zooming have caused the view to change". It also fires while the ScrollViewer is loading... and it may even fire at other times as well. I have verified the former, and the latter is causing me some current trouble. When else does this event actually fire? This documentation would be useful for writing a reliable event handler for this event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd470e1-38ac-a76f-883c-6096a6dcc128
* Version Independent ID: 23494efd-9886-a0c8-a132-18db50245536
* Content: [ScrollViewer.ViewChanged Event (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer.viewchanged)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.scrollviewer.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.scrollviewer.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response. 

The topic states "such as" in the description. These are examples, not an comprehensive list.

If you think the issue still exists and should be addressed, please open a new issue with any details/suggestions you think might be helpful.
