### ISSUE TITLE
Size (width and height) limitations need to be defined

### ISSUE THREAD

**Issue by jfranki** [MicrosoftDocs/winrt-api#951]
As far as I know it is not posible to set a ContentDialog's height or size to a desired value, not through attributes not through code-behind (correct me if I'm wrong). There seems to be a limitation on both properties, like predefined maximum values, which could make this control not valid for some scenarios.

I think this should be explained in Remarks. If I'm wrong and there is indeed a way to modify the size please add it too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16c14008-04b3-438b-5fae-3577cf233ab9
* Version Independent ID: 52f2f07b-034e-1d24-1b48-b4de7585e71a
* Content: [ContentDialog Class (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog#remarks)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.contentdialog.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by fabfella** [comment]
Yes im also troubled by this at the moment! Please provide an answer as soon as posible

**Comment by MikeHillberg** [comment]
You can set the Width/Height on the Content of the ContentDialog as an alternate solution.

**Comment by jfranki** [comment]
> You can set the Width/Height on the Content of the ContentDialog as an alternate solution.

Already tried that, does not work.

**Comment by jevansaks** [comment]
Thanks for reporting! We are tracking this over in Microsoft/microsoft-ui-xaml#424.
