### ISSUE TITLE
Change the cover art of a file

### ISSUE THREAD

**Issue by BlueEmb3r** [MicrosoftDocs/winrt-api#952]
How can I use this API to change the cover art of, for example, a mp3 file?

**Comment by ginami** [comment]
Hi @BlueEmb3r -- can you give me the URL of the doc that you're referring to? Thank you!

**Comment by BlueEmb3r** [comment]
@ginami 
https://docs.microsoft.com/uwp/api/windows.storage.systemproperties.music

**Comment by mcleanbyron** [comment]
Hi @BlueEmb3r - The album art thumbnail for an .mp3 file is accessible via the same thumbnail API that is used for any type of file: the [StorageFile.GetThumbnailAsync](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefile.getthumbnailasync) method. For more information, see [Thumbnail images](https://docs.microsoft.com/en-us/windows/uwp/files/thumbnails) and scenario 2 in the [File thumbnails](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/FileThumbnails) sample. I hope this helps!
