### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#954]
Could you show an example of a C++/winrt handler created to, say, track the IsOpen property of a Popup? The translation from the above declaration is fairly obscure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b56eb5a-b67f-0df4-cca6-24329f9b2138
* Version Independent ID: 4c41e0f1-2f02-051a-8d1c-07a25823366d
* Content: [PropertyChangedCallback Delegate (Windows.UI.Xaml) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.propertychangedcallback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.propertychangedcallback.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.propertychangedcallback.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by MikeHillberg** [comment]
Note there's a C# example here:
https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-dependency-properties#calling-register-with-property-metadata

(In fact, if you use the Language drop-down on that webpage, you can choose between several languages)

**Comment by jevansAN** [comment]
Thanks for that, but I’ve decided it would make more sense for my purposes to handle the Closed event on the popups I’m dealing with. A similar problem appears, though: It’s not clear to me why the docs don’t show the arguments for an event as they would appear when setting a lambda to handle the event in C++/winrt.

For example, the KeyDown event is documented in a way very similar to Close, with the Register/Revoke business:

event_token KeyDown(KeyEventHandler const& handler) const;

But in C++/winrt I actually handle the keydown this way, declaring the following in the object constructor:

m_item.KeyDown([&](winrt::Windows::Foundation::IInspectable const & sender, IKeyRoutedEventArgs const & args)
{
HandleKeyDown(args);

	});
That’s made easier because the docs tell me the arguments are of type IKeyRoutedEventArgs. But the docs for Close don’t mention what sort of arguments would be provided if Close were to be handled similarly to KeyDown. I don’t quite get how one would implement the keydown handler described in the docs but fortunately someone somewhere provided an example of how to set up that lambda and it works great. Could we please have similar example code for other events?

I appreciate the responses, 

Jeff





On Mar 1, 2019, at 4:28 PM, MikeHillberg <notifications@github.com> wrote:

Note there's a C# example here:
https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/custom-dependency-properties#calling-register-with-property-metadata

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


If this email is spam, report it to www.OnlyMyEmail.com

**Comment by stevewhims** [comment]
Hi, @jevansAN, I added details to the other issue: [Arguments for lambda in C++/WinRT](https://github.com/MicrosoftDocs/winrt-api/issues/955). Hopefully the steps described there will cover the general case. And I've updated the event-handling topic in the C++/WinRT docs (should be published soon). I think there are enough examples there, and with the general-purpose (teach-a-person-to-fish-type approach) I'm hoping we're covered for any and all event-handling use cases. But please let me know if I'm wrong.

Also, I think you're right to handle the Close event instead of looking at handling dependency property changed events (which are only for custom DPs, whereas this one is built into the platform).

~Steve

**Comment by stevewhims** [comment]
Hi, @jevansAN, we resolved this one, so I'll go ahead and close it. Thanks! ~Steve
