### ISSUE TITLE
Setting command in C++/winrt programmatically?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#957]
If not using xaml designer, how can one set the command programmatically in C++/winrt? I have a large project that began before the xaml designer was available in C++/winrt, so I'm committed to code-behind UI. The paragraphs above seem to suggest that there is no way to set the command outside xaml designer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fc3748e-24db-fbb2-6020-747e142a5fd6
* Version Independent ID: d837d584-8006-8545-c8ce-9d0abd0a45f1
* Content: [MenuFlyoutItem.Command Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.menuflyoutitem.command)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.menuflyoutitem.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.menuflyoutitem.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansAN** [comment]
p.s. for general info, I guess the solution is to just handle the Click event on the menuflyoutitem and implement the command directly that way, using the KeyboardAcceleratorTextOverride to show the key equivalent.

**Comment by stevewhims** [comment]
Hi, @jevansAN. Let's say I have a Windows Runtime type like this in my IDL.

```idl
...
runtimeclass BookSku : Windows.UI.Xaml.Input.ICommand
{
    BookSku();
}
...
```

And markup like this.

```xaml
...
<MenuFlyoutItem x:Name="myMenuFlyoutItem" Text="Perform work" />
...
```

If I want to set an instance of BookSku to serve as the command object for that MenuFlyoutItem, then I can do something like this:

```cppwinrt
        MYNAMESPACE::BookSku m_bookSku{ nullptr };
...
        m_bookSku = winrt::make<MYNAMESPACE::implementation::BookSku>();
        myMenuFlyoutItem().Command(m_bookSku);
```

It's not unusual for topics in this area to show properties being set in markup. But you can still set such properties imperatively, too.

~Steve

**Comment by stevewhims** [comment]
This one's resolved, so I'll go ahead and close it. Thanks! ~Steve
