### ISSUE TITLE
namespaces and usings incomplete for c++ example

### ISSUE THREAD

**Issue by snellejelle99** [MicrosoftDocs/winrt-api#958]
copying the c++ example leads to a shitload of errors mostly related to certain things not being defined.
please add a comment with which namespaces and includes should be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce88b8b-ad32-bcc7-bb9c-834d3cc487e8
* Version Independent ID: eef88d4b-6051-95fe-b180-868dd8ff4db7
* Content: [FileSavePicker Class (Windows.Storage.Pickers) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.Pickers.FileSavePicker#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.filesavepicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.filesavepicker.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mcleanbyron**
* Microsoft Alias: **mcleans**

**Comment by knicholasa** [comment]
Thanks for leaving your feedback. The code snippets on this page are part of a broader code sample, you can find the required includes in [the complete sample code](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/FilePicker). I'm going to update this page to point to that updated sample and I'll add a note about this to the page.

**Comment by stevewhims** [comment]
Thanks, @snellejelle99, and apologies for the long delay between updates.

That code example was C++/CX, and C++/CX has been superseded by C++/WinRT. Since there is a C++/WinRT version of that sample app, I've mentioned that in the topic, kept the link to it, and removed the obsolete C++/CX sample.

Thanks!
-Steve

**Comment by snellejelle99** [comment]
Don't worry about it. It's only been three years. :")
