### ISSUE TITLE
Obsolete reference?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#961]
What is described as the complete listing for this and other printing scenarios links to what is apparently an obsolete page, one no longer being updated, describing printing in a Javascript/HTML app. Could we  have a more complete description of the printing setup/flow as it would be accomplished in a C++/winrt app? Some sample code would be very useful. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73fd3ed3-2205-bb64-cc18-edaf11dc1e66
* Version Independent ID: f2cb7e89-17e8-98fc-a4b9-51c9fd3f0e52
* Content: [PrintManager.PrintTaskRequested Event (Windows.Graphics.Printing) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.printing.printmanager.printtaskrequested)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.printmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.graphics.printing.printmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **drewbatgit**
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. I have created an internal work item to investigate the usage statistics for these APIs and potentially add sample code for this printing scenario.
