### ISSUE TITLE
There's no way to integrate proofing menu in a custom context menu

### ISSUE THREAD

**Issue by MarcAnt01** [MicrosoftDocs/winrt-api#964]
If spell check isn't disabled it also displays over custom context menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2572e9d9-0cfa-09e6-e537-83b806501e9c
* Version Independent ID: 83de1b98-bb45-efe7-8159-b62c0a007bfe
* Content: [TextBox.ProofingMenuFlyout Property (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.proofingmenuflyout)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.textbox.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
@MarcAnt01 are you looking for clarification on the docs or reporting a bug? If you think this is a bug, please file an issue over at https://github.com/Microsoft/microsoft-ui-xaml and include more details about the repro. Thanks!

**Comment by MarcAnt01** [comment]
Thanks, as it is a bug, I'll report the right repository. Cannot attach repro steps, as I am not a developer and haven't worked personally on implementing this stuff

**Comment by jevansaks** [comment]
Sorry, I'm confused exactly about what is being reported. Since you're not a developer does that mean you're seeing a problem with the proofing menu in an application you're using?

**Comment by MarcAnt01** [comment]
Proofing menu is provided by Windows and covers custom context menu

**Comment by MarcAnt01** [comment]
@FrayxRulez is a developer and maybe he can explain things better
