### ISSUE TITLE
Do we have any sample code for C++/CX for Windows.Networking.Vpn?

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#965]
[Is there any sample code or blog to clearly show the usage of VPN APIs? They will be very helpful.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a47d2c-61a3-01b3-d0dc-73a4b7d5117f
* Version Independent ID: 4c713fb3-f086-5319-cf44-33346a7a14b7
* Content: [Windows.Networking.Vpn Namespace - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @defaultshr, thanks for filing this issue.

[C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) is our recommended replacement for the C++/CX language projection, and for the Windows Runtime C++ Template Library (WRL). We don't provide sample code for every API, but the fact that you're asking in this case means that there's a demand, so I'll take that into account with my planning and my TODO list. However, any C++ code that we'd add would be C++/WinRT.

FYI, the C++/WinRT documentation (link above) covers all kinds of techniques around using C++/WinRT in general. Handling events, authoring and consuming APIs, asynchronous patterns, and so on. It's likely that the content there will be all you need to get started with Windows::Networking::Vpn and C++/WinRT. If you come across any specific scenarios or APIs with Windows::Networking::Vpn that are challenging to use, then please let me know and I'll see whether I can provide C++/WinRT code for them and/or fill any doc gaps.

Btw, the C++/WinRT docs includes info about both interoperating with, and porting from, C++/CX and WRL.

~Steve

**Comment by defaultshr** [comment]
Thank you for the clarification. Yes, I would certainly appreciate a sample
code for Windows::Networking::Vpn using C++/WinRT.

~Shrini

**Comment by stevewhims** [comment]
Great, that's good to know! So, then, I'd still advise that you use the main [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) documentation for coding techniques, info, and guidance. There's plenty of code examples in there showing all kinds of techniques. And there's [C++/WinRT API reference content](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/winrt), too. As I say, we don't provide sample code for every API. So, after looking at the content I mentioned, and making a start programming Windows::Networking::Vpn with C++/WinRT, if you come across any specific scenarios or APIs that are challenging to use, then please let me know and I'll see whether I can provide C++/WinRT code for them and/or fill any doc gaps. ~Steve

**Comment by defaultshr** [comment]
Thank you Steve, in fact I posted another specific query on the thread
regards to Vpn. Basically, I am looking for using IPSec over UDP sockets.
My VPN client and server application shall generate the SPI and symmetric
encryption key by itself and made known to each other using non-IPSec
methods.
I was trying to find a way to set SPI and symmetric encryption key on to
the channel VPN profiles (one for outgoing IPSec and one for incoming IPSec
stream). I could not figure out a way to do so in the available
documentation. This is similar to functionality available in Linux ip-fxrm
where we can set rules to establish IPSec channel without doing
key-exchange via IPSec.

Thank you
Shrini

**Comment by stevewhims** [comment]
Hi, @defaultshr. Yes, I see that other GitHub issue. So, I'll go ahead and work with you on that other issue in that other thread. As for this thread, which is about C++/WinRT code examples, I'll go ahead and close it for now. So, we'll work on the other issue in the other thread; and, if you have any specific C++/WinRT questions, then please open a new issue on whichever topic is relevant.

Thanks!
~Steve
