### ISSUE TITLE
AutomationProperties.LabeledBy link is broken.

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#968]
In this content the in the section Property Value, there is a link to AutomationProperties.LabeledBy which leads to a page that does not exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7532c5b1-207e-9122-f473-9d8821e6b592
* Version Independent ID: 885408f3-7981-5ac1-0563-d569b96e4ec1
* Content: [AutomationProperties.LabeledByProperty Property (Windows.UI.Xaml.Automation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties.labeledbyproperty#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback @JuanMejiaVelez. This is a known issue introduced by our open authoring platform. We will be moving to a new publishing pipeline soon that should fix this. In the meantime, we've updated the links to point to a generic attached properties topic.
