### ISSUE TITLE
None of the properties is documented

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/winrt-api#969]
All the properties for AutomationProperties are missing in this documentation. only the attached properties exists. Although, there are multiple references to the properties but all lead to 404 error pages. Please, fix this and provide code samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b19312-d5aa-8024-9009-d56f43898596
* Version Independent ID: 4f9ea65e-5c52-3d3c-75c9-596c175dca13
* Content: [AutomationProperties Class (Windows.UI.Xaml.Automation) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.automation.automationproperties.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **Karl-Bridge-Microsoft**
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback @JuanMejiaVelez! This is a known issue that was introduced by our new open authoring publishing tools. We're moving to a new publishing pipeline in the near future with the hope that this issue will be resolved.
