### ISSUE TITLE
Link goes to 404 error

### ISSUE THREAD

**Issue by YuliKl** [MicrosoftDocs/winrt-api#971]
The SelectionFollowsFocus link is broken. Should go to https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.selectionfollowsfocus#Windows_UI_Xaml_Controls_NavigationView_SelectionFollowsFocus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb5d9ab5-9358-bc88-a404-30c8c13d283f
* Version Independent ID: b1d70c70-d49f-e824-3258-4277a65baa1b
* Content: [NavigationViewShoulderNavigationEnabled Enum (Windows.UI.Xaml.Controls) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationviewshouldernavigationenabled#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewshouldernavigationenabled.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.controls.navigationviewshouldernavigationenabled.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Link works now.
