### ISSUE TITLE
Events in JavaScript

### ISSUE THREAD

**Issue by tomasjiricek** [MicrosoftDocs/winrt-api#973]
When trying to add listeners for JavaScript I found out events should be lowercase not camelCase.
"enteredBackground" never gets triggered. If you want to listen to it, you'll have to listen to "enteredbackground". Same for the other events (leavingBackground etc).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c748a20-066a-4cab-dbb8-803579583150
* Version Independent ID: adc70719-5c9b-70bc-c461-9c01731713f8
* Content: [WebUIApplication.LeavingBackground Event (Windows.UI.WebUI) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.webui.webuiapplication.leavingbackground#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.webui.webuiapplication.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.webui.webuiapplication.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mijacobs**
* Microsoft Alias: **mijacobs**

**Comment by jwmsft** [comment]
I believe this issue was fixed. Feel free to reopen if there is still a problem. Thanks.
