### ISSUE TITLE
 Xbox UWP app

### ISSUE THREAD

**Issue by saadataz** [MicrosoftDocs/winrt-api#974]
For clarification, Prelaunch is not available for Xbox UWP app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dab608fa-1552-c653-f71b-0daa592d3d01
* Version Independent ID: 31e7b28a-6d4b-2cb8-10f4-bd934f4cbf8f
* Content: [CoreApplication.EnablePrelaunch(Boolean) Method (Windows.ApplicationModel.Core) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.core.coreapplication.enableprelaunch#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplication.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.applicationmodel.core.coreapplication.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hello! Thanks for your feedback. I've reached out to the team that owns this feature to ask about updating the page.
