### ISSUE TITLE
ToastNotification.Tag Property setter has undocumented exceptional cases

### ISSUE THREAD

**Issue by AliveDevil** [MicrosoftDocs/winrt-api#975]
The `Tag` property on `ToastNotification` throws Exceptions on setting its value to either
* `null`
* `""` (or `string.Empty`).

This behavior in the setter is not described and must be added to the documentation as this is a critical information which must not be omitted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f39c0e31-2734-a029-3c95-43a7885a50c1
* Version Independent ID: 1942cc7f-6cd4-9a8c-93a3-a9bd889d54b0
* Content: [ToastNotification.Tag Property (Windows.UI.Notifications) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification.tag)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotification.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.notifications.toastnotification.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **mijacobs**
* Microsoft Alias: **mijacobs**

**Comment by QuinnRadich** [comment]
Thank you for your patience on this issue. I've added a note to the documentation, which should go live shortly.
