### ISSUE TITLE
Sample application code utilizing plugin facility

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#983]
Could you kindly make available a sample code with either C++/CX or C++/WinRT and make available for reference implementation. 

I tried coding for a plugin and invoked VpnChannel::ProcessEventAsync() from background task's run method by passing the same plugin. But, I do not see plugin's connect() method being invoked. BTW, my manifest.xml has rescap for Vpn capability added. Any help will be appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4a88e25-2948-fb1e-146e-b99eb119afe6
* Version Independent ID: e85f2e71-e3bc-c611-aaa3-529ddf81c38d
* Content: [IVpnPlugIn Interface (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.ivpnplugin)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.ivpnplugin.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.ivpnplugin.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by defaultshr** [comment]
I am able to now hit plugin's connect method by creating new "VPN Connection" in the system's VPN settings. However, channel->StartWithMainTransport(…) invocation throws exception ("The operation was cancelled by user") on Visual Studio. 
On the system's VPN settings following error is seen - "remote access service ip configuration is unusable" 

However, I think I am passing correctly v4 and v6 address to the channel->StartWithMainTransport(…) API which are bound to my m/c network I/f. What other validations may have caused this issue. I do not want to configure certificates etc for the VpnChannel as I plan to implement encapsulate and decapsulate myself in VpnPlugin. 

Sample code for Plugin's connect method where exception gets thrown on call to channel->StartWithMainTransport(...) is below.

-------------------------------------------------------------------------------------------------------

// Sample Plugin's connect implementation 
void TunnelPlugin::Connect(Windows::Networking::Vpn::VpnChannel^ channel)
{
	this->dSock = ref new DatagramSocket();
	Platform::String^ svcName = "22111";
	auto result = create_task(dSock->BindServiceNameAsync(svcName));
	result.get();

	// Connect to the destination tunnel address on UDP socket.
	HostName^ remoteTunnelIP = ref new HostName("192.168.1.137");
	Platform::String^ remoteTunnelPort = "22112";
	result = create_task(this->dSock->ConnectAsync(remoteTunnelIP, remoteTunnelPort));
	result.get();

	channel->AssociateTransport(this->dSock, nullptr);
	VpnChannelConfiguration^ chanCfg = channel->Configuration;

	// IP destinations to be routed via VPN
	VpnRouteAssignment^ routeScope = ref new VpnRouteAssignment();
	routeScope->Ipv4InclusionRoutes->Append(ref new VpnRoute(ref new HostName("192.168.1.111"), 32));
	Vector<HostName^>^ localV4Addrs = ref new Vector<HostName^>;
	localV4Addrs->Append(ref new HostName("192.168.1.133")); // Local host name to be bound.

	Vector<HostName^>^ localV6Addrs = ref new Vector<HostName^>;
	localV6Addrs->Append(ref new HostName("fc00::44fd:d3ed:b02a:a05e"));

	Vector<HostName^>^ dnsServers = ref new Vector<HostName^>;
	dnsServers->Append(ref new HostName("1.1.1.1"));
	VpnDomainNameInfo^ dnsInfo = ref new VpnDomainNameInfo(".", VpnDomainNameType::Suffix, dnsServers, ref new Vector<HostName^>);
	VpnDomainNameAssignment^ dnsAssignment = ref new VpnDomainNameAssignment;
	dnsAssignment->DomainNameList->Append(dnsInfo);

	try
	{
		channel->StartWithMainTransport(localV4Addrs->GetView(), localV6Addrs->GetView(), nullptr, routeScope, dnsAssignment, 1400, 1412, false, this->dSock);
	}
	catch (Exception^ exc)
	{
		auto type = exc->GetType();
		Platform::String^ str = exc->ToString();
	}
}

-------------------------------------------------------------------------------------------------------

**Comment by defaultshr** [comment]
I am able to resolve the exception. For some reason the PPP network adapter created for above VPN had IP assigned automatically from 169.254... range. I don't know the reason for same. However, after creating the new VPN configuration, the API worked without any exception. 

However, I will leave this issue open for tracking the need for sample application code for writing VPN applications.

**Comment by stevewhims** [comment]
Thanks for the update, @defaultshr! ~Steve

**Comment by defaultshr** [comment]
Hi Steve, Managed to get sample working VPN application in github. If possible, Microsoft engineering support team may however post a better application as I am not an expert Windows programmer. 

C++/CX code base for reference in following place:
https://github.com/defaultshr/UWPVPNPluginSample

You may however close the ticket if you feel appropriate OR keep it open for better sample application.

**Comment by stevewhims** [comment]
Thanks for the update, @defaultshr! I've passed the info along internally. ~Steve

**Comment by stevewhims** [comment]
I'll go ahead and close this one now; thanks for your work here, @defaultshr! ~Steve
