### ISSUE TITLE
Event object which can trigger the plugin "connect" method

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/winrt-api#984]
I invoke this API by passing a Vpn plugin object reference from a background task's run method. However, I do not get "Connect" method invoked on the plugin. 

What specific event object does the ProcessEventAsync method expect to kick start the Vpn Plugin's connect method. Appreciate your response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f5bb7f-941f-eef8-2126-c324462e362d
* Version Independent ID: 51cc7fb0-9faa-8e6c-b323-9d968070704e
* Content: [IVpnChannelStatics.ProcessEventAsync(Object, Object) Method (Windows.Networking.Vpn) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn.ivpnchannelstatics.processeventasync)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.ivpnchannelstatics.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.networking.vpn.ivpnchannelstatics.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **stevewhims**
* Microsoft Alias: **stwhi**

**Comment by defaultshr** [comment]
I think I get this issue resolved. Basically manifest need to have task extensions present as follows. Refer [ uap:Task Type="vpnClient" ] in the following content, which is the key. 

      <Extensions>
        <Extension Category="windows.backgroundTasks" Executable="BackgroundTask.exe" EntryPoint="Tasks.SampleBackgroundTask">
          <BackgroundTasks>
            <uap:Task Type="vpnClient" />
          </BackgroundTasks>
        </Extension>
      </Extensions>

**Comment by stevewhims** [comment]
Thanks for the update, @defaultshr! ~Steve
