### ISSUE TITLE
This method is returning NULL for packages installed by default on Windows 10.

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/winrt-api#986]
As posted below. The method is returning NULL for packages installed by default on Windows 10. What could be a reason?

https://stackoverflow.com/q/55270248/1232087

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad2072a-e249-6d75-7770-8e9f05917f63
* Version Independent ID: 36891e06-dd39-14fb-8559-5bbf6e4f7574
* Content: [PackageManager.FindPackageForUser(String, String) Method (Windows.Management.Deployment) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.management.deployment.packagemanager.findpackageforuser#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.management.deployment.packagemanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **wdg-dev-content**
* Microsoft Alias: **wdg-dev-content**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and I sincerely apologize for the delayed response. The right channel for this would be [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html). The community of Microsoft engineers and experts can offer timely answers to a multitude of technical questions surrounding windows-uwp.
