### ISSUE TITLE
Strange comment in documentation

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/winrt-api#987]
When using `AdvertisingManager.AdvertisingId` in Visual Studio when coding, it shows some cryptical message that probably should not be there, see the attached screenshot.  
Expected behavior, show proper documentation for this property in Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6697dd2-4e73-f2d9-23b9-15ff9709338c
* Version Independent ID: 3df06de3-a6d6-9e60-4e04-76fb49e33623
* Content: [AdvertisingManager.AdvertisingId Property (Windows.System.UserProfile) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.system.userprofile.advertisingmanager.advertisingid#feedback)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.userprofile.advertisingmanager.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.system.userprofile.advertisingmanager.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **hickeys**
* Microsoft Alias: **hickeys**

**Comment by martinsuchan** [comment]
Here's the screenshot.
This happened to me in Visual Studio 2019 RC3.
![D2Lj4APWwAMAZni](https://user-images.githubusercontent.com/3041397/54761440-63338380-4bf2-11e9-931b-53b070fdd04a.png)

**Comment by QuinnRadich** [comment]
Apologies for the delay in this response.

This is, in all honesty, something of a fascinating issue. I have my suspicions on what's causing this, and I'm forwarding them on to the VS team to investigate. However, as this is a VS or Intellisense issue and not directly related to this documentation page, I'm closing this issue for now.

Thank you!
