### ISSUE TITLE
Markup error in the See Also section

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/winrt-api#988]
A markup error in the See Also section is preventing a link from being clickable.
> Windows.Storage.Pickers.FileExtensionVector eopenpicker.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28945089-32b1-c441-1d5a-166421ad1e4d
* Version Independent ID: 74739713-33de-0a45-b47a-a60b30a0d24c
* Content: [FileOpenPicker.FileTypeFilter Property (Windows.Storage.Pickers) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.filetypefilter#Windows_Storage_Pickers_FileOpenPicker_FileTypeFilter)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.fileopenpicker.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.storage.pickers.fileopenpicker.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Git Login: **knicholasa**
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for catching that! Fixing it now.
