### ISSUE TITLE
Can a CanvasVIrtualControl serve as a pageVisual?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/winrt-api#998]
When trying to print content of a CanvasVirtualControl it doesn't seem to work as a UIElement for AddPage. Is it possible to use a CanvasVirtualControl as an argument for PrintDocument.AddPage? If not, is there any documentation available on printing a CanvasVirtualControl?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20435a22-bc4d-aeaa-faee-e35d3a16e86d
* Version Independent ID: 9a8207d3-ba6c-8d10-515e-3c38d77d999e
* Content: [PrintDocument.AddPage(UIElement) Method (Windows.UI.Xaml.Printing) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.printing.printdocument.addpage#Windows_UI_Xaml_Printing_PrintDocument_AddPage_Windows_UI_Xaml_UIElement_)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.printing.printdocument.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.ui.xaml.printing.printdocument.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **jwmsft**
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
Seems like a bug with CanvasVirtualControl itself if it doesn't support printing. Let me see if this is a platform issue or Win2D and i'll get back to you.

**Comment by jevansAN** [comment]
jevan (is your name actually Jeff, too?)
	
	I found out that CanvasVirtualControl can’t be used as a UIElement argument for a PrintDocument source - it’s necessary to instead create a CanvasPrintDocument. And the CanvasPrintDocument doesn’t have the Paginate, etc. events so using it is quite a bit different from what is described in the print-from-your-app docs. Works, though.

	Jeff


On Apr 19, 2019, at 11:20 AM, Jevan Saks <notifications@github.com> wrote:

Seems like a bug with CanvasVirtualControl itself if it doesn't support printing. Let me see if this is a platform issue or Win2D and i'll get back to you.

**Comment by jevansaks** [comment]
Ah! Glad you figured it out. I'll close this issue then.

And my name is actually "Jevan", but I assume you're my long lost twin every time I see your github handle. 😁
