### ISSUE TITLE
USB device class property usage issue on Docs

### ISSUE THREAD

**Issue by BarryWangMSDN** [MicrosoftDocs/winrt-api#999]
Link back to here: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/9312e45b-da84-4d79-a4fc-79bf4a89a36e/usb-device-class-property-usage-issue-on-docs?forum=wpdevelop
currently there is no Class/SubClass properties under UsbDeviceClass, but only ClassCode/SubclassCode so the correct working codes should look like this:

byte deviceClassCode = 0xf0;

byte deviceSubclassCode = 0x01;

UsbDeviceClass deviceClass = new UsbDeviceClass

{

     ClassCode = deviceClassCode,

     SubclassCode = deviceSubclassCode

};

string selector = UsbDevice.GetDeviceClassSelector(deviceClass);

var myDevices = await Windows.Devices.Enumeration.DeviceInformation.FindAllAsync(selector);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b3e6ad8-ce6f-26b2-873a-2a984aca1598
* Version Independent ID: baff7d32-8677-c2f6-cfa9-33a13c86d468
* Content: [UsbDeviceClass Class (Windows.Devices.Usb) - Windows UWP applications](https://docs.microsoft.com/en-us/uwp/api/windows.devices.usb.usbdeviceclass)
* Content Source: [https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.usb.usbdeviceclass.yml&version=GBlive&_a=contents](https://cpubwin.visualstudio.com/DefaultCollection/windows-uwp/_git/winrt-api-build?path=%2fwinrt-api-build%2fwindows.devices.usb.usbdeviceclass.yml&version=GBlive&_a=contents)
* Product: **uwp**
* Technology: **winrt-reference**
* Git Login: **eliotcowley**
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @BarryWangMSDN. Thanks for filing this issue, and my apologies for the long delay in responding.

Yes, that code was indeed incorrect. I've fixed it up and re-published. I'll go ahead and close the issue.

Thanks again!
Steve
